#!/usr/bin/env python3
"""Independent Phase B/C reconstruction for T-44 displayed rank-108 construct.

This script deliberately stays inside the data generated by
check_oracle_108e_mod31_tietze_certificate.py: the 14 homological generators
over F_3, their Sp_6(F_3) action on H_1, and the induced dual action on the
729 level-3 characters.  It does not import a 27-dimensional odd-theta target
or Fox/Picard-Lefschetz Prym fiber matrices, because those are precisely the
source-grade blocks marked absent by the local team audits.
"""

from __future__ import annotations

import json
from collections import deque
from itertools import product


P = 3
N = 6

TWIST_NAMES = ["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2"]
PUSH_NAMES = ["Pa1", "Pb1", "Pa2", "Pb2", "Pa3", "Pb3"]
GENERATOR_NAMES = TWIST_NAMES + PUSH_NAMES


def mat_identity(n: int = N) -> list[list[int]]:
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def mat_mul(a: list[list[int]], b: list[list[int]]) -> list[list[int]]:
    rows = len(a)
    inner = len(b)
    cols = len(b[0])
    return [
        [sum(a[i][k] * b[k][j] for k in range(inner)) % P for j in range(cols)]
        for i in range(rows)
    ]


def mat_vec_mul(a: list[list[int]], v: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(sum(a[i][j] * v[j] for j in range(len(v))) % P for i in range(len(a)))


def row_mat_mul(v: tuple[int, ...], a: list[list[int]]) -> tuple[int, ...]:
    return tuple(sum(v[i] * a[i][j] for i in range(len(v))) % P for j in range(len(a[0])))


def mat_transpose(a: list[list[int]]) -> list[list[int]]:
    return [[a[j][i] for j in range(len(a))] for i in range(len(a[0]))]


def mat_inv(a: list[list[int]]) -> list[list[int]]:
    n = len(a)
    aug = [list(row) + [1 if i == j else 0 for j in range(n)] for i, row in enumerate(a)]
    for col in range(n):
        pivot = None
        for row in range(col, n):
            if aug[row][col] % P:
                pivot = row
                break
        if pivot is None:
            raise ValueError("matrix is singular over F_3")
        aug[col], aug[pivot] = aug[pivot], aug[col]
        inv_pivot = pow(aug[col][col] % P, -1, P)
        aug[col] = [(x * inv_pivot) % P for x in aug[col]]
        for row in range(n):
            if row == col:
                continue
            factor = aug[row][col] % P
            if factor:
                aug[row] = [(x - factor * y) % P for x, y in zip(aug[row], aug[col])]
    return [row[n:] for row in aug]


def rank_modp(rows: list[list[int]]) -> int:
    a = [[x % P for x in row] for row in rows if any(x % P for x in row)]
    if not a:
        return 0
    m = len(a)
    n = len(a[0])
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if a[i][c] % P:
                pivot = i
                break
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        inv = pow(a[r][c] % P, -1, P)
        a[r] = [(x * inv) % P for x in a[r]]
        for i in range(m):
            if i != r and a[i][c] % P:
                factor = a[i][c] % P
                a[i] = [(x - factor * y) % P for x, y in zip(a[i], a[r])]
        r += 1
        if r == m:
            break
    return r


J = [
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [2, 0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0],
]


def basis_vec(label: str) -> list[int]:
    if label.startswith("e"):
        out = [0] * N
        out[int(label[1]) - 1] = 1
        return out
    if label.startswith("f"):
        out = [0] * N
        out[3 + int(label[1]) - 1] = 1
        return out
    raise ValueError(f"unknown basis label {label}")


def vec_diff(left: str, right: str) -> list[int]:
    a = basis_vec(left)
    b = basis_vec(right)
    return [(a[i] - b[i]) % P for i in range(N)]


def jv(v: list[int]) -> list[int]:
    return [sum(J[i][j] * v[j] for j in range(N)) % P for i in range(N)]


def transvection(v: list[int]) -> list[list[int]]:
    """The oracle checker's convention: M(v) = I_6 - v (Jv)^T over F_3."""
    j_vec = jv(v)
    out = mat_identity()
    for i in range(N):
        for k in range(N):
            out[i][k] = (out[i][k] - v[i] * j_vec[k]) % P
    return out


def is_sp6(m: list[list[int]]) -> bool:
    return mat_mul(mat_mul(m, J), mat_transpose(m)) == J


def build_generators() -> tuple[dict[str, list[list[int]]], dict[str, list[int] | None]]:
    twist_vectors = {
        "A1": basis_vec("e1"),
        "A2": basis_vec("e2"),
        "A3": basis_vec("e3"),
        "B1": basis_vec("f1"),
        "B2": basis_vec("f2"),
        "B3": basis_vec("f3"),
        "C1": vec_diff("e1", "e2"),
        "C2": vec_diff("e2", "e3"),
    }
    generators = {name: transvection(vector) for name, vector in twist_vectors.items()}
    for name in PUSH_NAMES:
        generators[name] = mat_identity()
    vectors: dict[str, list[int] | None] = {name: twist_vectors.get(name) for name in GENERATOR_NAMES}
    return generators, vectors


def character_orbits(generators: dict[str, list[list[int]]]) -> list[int]:
    """Orbit sizes for row characters chi under chi -> chi * M^{-1}."""
    all_chars = [tuple(v) for v in product(range(P), repeat=N)]
    unseen = set(all_chars)
    inverse_twists = [mat_inv(generators[name]) for name in TWIST_NAMES]
    orbit_sizes: list[int] = []
    while unseen:
        start = next(iter(unseen))
        queue: deque[tuple[int, ...]] = deque([start])
        unseen.remove(start)
        size = 0
        while queue:
            chi = queue.popleft()
            size += 1
            for inv_g in inverse_twists:
                nxt = row_mat_mul(chi, inv_g)
                if nxt in unseen:
                    unseen.remove(nxt)
                    queue.append(nxt)
        orbit_sizes.append(size)
    return sorted(orbit_sizes)


def fixed_space_dimension(generators: dict[str, list[list[int]]]) -> int:
    rows: list[list[int]] = []
    identity = mat_identity()
    for name in GENERATOR_NAMES:
        matrix = generators[name]
        for i in range(N):
            rows.append([(matrix[i][j] - identity[i][j]) % P for j in range(N)])
    return N - rank_modp(rows)


def matrix_restricts_to_indices(matrix: list[list[int]], indices: list[int]) -> bool:
    index_set = set(indices)
    for col in indices:
        image = mat_vec_mul(matrix, tuple(1 if i == col else 0 for i in range(N)))
        for row, value in enumerate(image):
            if row not in index_set and value % P:
                return False
    return True


def submatrix_on_indices(matrix: list[list[int]], indices: list[int]) -> list[list[int]]:
    return [[matrix[i][j] % P for j in indices] for i in indices]


def natural_dimensions_from_local_data() -> dict[str, object]:
    return {
        "base_H1_dim": 6,
        "character_count": 3**6,
        "nontrivial_character_count": 3**6 - 1,
        "team_local_W_chi0_display_dim": 4,
        "nontrivial_local_Prym_fiber_dim_from_phase_A_team_file": 4,
        "closed_surface_lift_accounting_dim": 6 + (3**6 - 1) * 4,
        "natural_108_dimensional_representation_found": False,
        "comment": (
            "The locally computable dimensions are 6, 4, 729 characters, 728 nontrivial "
            "characters, and the closed-surface accounting 2918 = 6 + 728*4.  A 108-entry "
            "intertwiner can be parsed as 27*4 unknowns, but that is not itself a "
            "108-dimensional representation."
        ),
    }


def phase_c_placeholder(generators: dict[str, list[list[int]]]) -> dict[str, object]:
    indices = [1, 4, 2, 5]  # [a2,b2,a3,b3] in the oracle basis [a1,a2,a3,b1,b2,b3].
    restricted: dict[str, object] = {}
    for name in TWIST_NAMES:
        stable = matrix_restricts_to_indices(generators[name], indices)
        restricted[name] = {
            "span_a2_b2_a3_b3_stable_in_base_H1": stable,
            "base_H1_restriction_matrix_if_stable": submatrix_on_indices(generators[name], indices) if stable else None,
        }
    return {
        "rho_in_dim": 4,
        "rho_out_dim": 27,
        "candidate_unknown_count": 4 * 27,
        "rho_out_construction_status": "PLACEHOLDER_UNBOUND",
        "linear_system_rank": None,
        "Hom_dim": None,
        "source_restriction_attempt": restricted,
        "notes": (
            "The source span [a2,b2,a3,b3] is not a Mod_{3,1}-stable subrepresentation "
            "of the base H1 action for all eight twists; for example C1 and C2 mix handles "
            "outside that span.  The team's displayed W_chi0 is a separate 4-dimensional "
            "fiber model.  No source-grade rho_out block, W_fiber_block, transporter_block, "
            "ordered generator binding, or Hom-equation schema is reconstructed from the "
            "14 homological generators, so the 27-dimensional target is left unbound."
        ),
    }


def main() -> None:
    generators, vectors = build_generators()
    identity = mat_identity()

    twist_checks = {
        name: {
            "listed_vector": vectors[name],
            "matches_oracle_transvection_formula": generators[name] == transvection(vectors[name]),  # type: ignore[arg-type]
            "in_Sp6_F3": is_sp6(generators[name]),
            "matrix": generators[name],
        }
        for name in TWIST_NAMES
    }
    point_push_checks = {
        name: {
            "acts_as_identity_on_H1_F3": generators[name] == identity,
            "in_Sp6_F3": is_sp6(generators[name]),
        }
        for name in PUSH_NAMES
    }
    orbit_partition = character_orbits(generators)
    fixed_dim = fixed_space_dimension(generators)

    report = {
        "schema": "independent_team_construct_phaseB_recon_v1",
        "field": "F_3",
        "basis": ["a1/e1", "a2/e2", "a3/e3", "b1/f1", "b2/f2", "b3/f3"],
        "generator_count": len(generators),
        "twist_generator_count": len(TWIST_NAMES),
        "point_push_generator_count": len(PUSH_NAMES),
        "all_twists_match_listed_transvections": all(
            item["matches_oracle_transvection_formula"] for item in twist_checks.values()
        ),
        "all_point_pushes_identity_on_H1_F3": all(
            item["acts_as_identity_on_H1_F3"] for item in point_push_checks.values()
        ),
        "all_generators_in_Sp6_F3": all(is_sp6(generators[name]) for name in GENERATOR_NAMES),
        "character_count": 3**6,
        "Sp6F3_orbit_partition": orbit_partition,
        "trivial_character_orbit_size": 1 if 1 in orbit_partition else None,
        "nontrivial_character_orbit_size": 728 if 728 in orbit_partition else None,
        "trivial_isotype_dim_in_base_H1": fixed_dim,
        "natural_dimensions_from_local_data": natural_dimensions_from_local_data(),
        "phase_C_placeholder": phase_c_placeholder(generators),
        "twist_checks": twist_checks,
        "point_push_checks": point_push_checks,
    }
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
