#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Symbolic Taylor expansion for the neg-carry potential (phi_-).

In appendix `sections/appendix/sync_kernel/app__vector-potential.tex`, the pressure P(theta)
for the potential phi_-(s->t)=1_{t in Q_-} is determined by the Perron root
lambda(u) (u = e^theta) of the cubic:

  lambda^3 - (u+2) lambda^2 + (u-2) lambda + 3u = 0.

This script expands:
  P(theta) = log lambda(e^theta)
around theta=0 to a chosen order, and exports:
  - sections/generated/eq_sync_kernel_phi_minus_cubic_series.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import sympy as sp

from common_paths import generated_dir


def _series_lam_coeffs(order: int) -> sp.Expr:
    """
    Return lambda(theta) as a formal series:
      lambda(theta) = 3 + a1*theta + ... + a_order*theta^order
    solving the cubic with u = exp(theta) on the Perron branch.
    """
    theta = sp.Symbol("theta")
    u = sp.exp(theta)

    a = sp.symbols("a1:%d" % (order + 1))
    lam = sp.Integer(3)
    for k in range(1, order + 1):
        lam += a[k - 1] * theta**k

    f = lam**3 - (u + 2) * lam**2 + (u - 2) * lam + 3 * u
    f_ser = sp.series(sp.expand(f), theta, 0, order + 1).removeO()

    subs = {}
    for k in range(1, order + 1):
        ck = sp.expand(sp.series(f_ser.subs(subs), theta, 0, k + 1).removeO()).coeff(theta, k)
        sol = sp.solve(sp.Eq(ck, 0), a[k - 1], dict=True)
        if not sol:
            raise ValueError(f"Failed to solve coefficient at order {k}")
        subs[a[k - 1]] = sp.simplify(sol[0][a[k - 1]])

    lam_ser = sp.expand(lam.subs(subs))
    return sp.series(lam_ser, theta, 0, order + 1).removeO()


def _pressure_series(order: int) -> sp.Expr:
    theta = sp.Symbol("theta")
    lam_ser = _series_lam_coeffs(order)
    P_ser = sp.series(sp.log(lam_ser), theta, 0, order + 1).removeO()
    return sp.expand(P_ser)


def _kth_derivative_at_0_from_series(expr: sp.Expr, k: int) -> sp.Expr:
    theta = sp.Symbol("theta")
    ck = sp.expand(expr).coeff(theta, k)
    return sp.simplify(sp.factorial(k) * ck)


def write_eq_tex(path: Path, order: int) -> None:
    theta = sp.Symbol("theta")
    P_ser = _pressure_series(order)

    # Derivatives
    P2 = _kth_derivative_at_0_from_series(P_ser, 2)
    P3 = _kth_derivative_at_0_from_series(P_ser, 3)
    P4 = _kth_derivative_at_0_from_series(P_ser, 4)
    P5 = _kth_derivative_at_0_from_series(P_ser, 5)

    gamma1 = sp.simplify(P3 / (P2 ** sp.Rational(3, 2)))
    gamma2 = sp.simplify(P4 / (P2**2))

    gamma1_num = float(sp.N(gamma1, 60))
    gamma2_num = float(sp.N(gamma2, 60))

    P_tex = sp.latex(P_ser)
    P2_tex = sp.latex(P2)
    P3_tex = sp.latex(P3)
    P4_tex = sp.latex(P4)
    P5_tex = sp.latex(P5)
    g1_tex = sp.latex(gamma1)
    g2_tex = sp.latex(gamma2)

    lines: list[str] = []
    lines.append("% Generated by scripts/exp_sync_kernel_phi_minus_cubic_series.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append("P(\\theta)")
    lines.append(f"&={P_tex}+O(\\theta^{{{order+1}}}),\\\\")
    lines.append(
        f"P''(0)&={P2_tex},\\qquad P^{{(3)}}(0)={P3_tex},\\qquad P^{{(4)}}(0)={P4_tex},\\qquad P^{{(5)}}(0)={P5_tex},\\\\"
    )
    lines.append(
        f"\\gamma_1&:=\\frac{{P^{{(3)}}(0)}}{{(P''(0))^{{3/2}}}}={g1_tex}\\ \\ (\\approx {gamma1_num:.6g}),\\\\"
    )
    lines.append(
        f"\\gamma_2&:=\\frac{{P^{{(4)}}(0)}}{{(P''(0))^2}}={g2_tex}\\ \\ (\\approx {gamma2_num:.6g})."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Taylor series for phi_- cubic pressure.")
    parser.add_argument(
        "--order",
        type=int,
        default=5,
        help="Taylor order (>=2). Default: 5",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_sync_kernel_phi_minus_cubic_series.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()
    if args.order < 2:
        raise ValueError("--order must be >= 2")

    write_eq_tex(Path(args.tex_out), order=args.order)
    print(f"[phi-minus-cubic] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

