#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spectral-tax workload table for the prime-modulus scan rho_{p,p,p}/lambda.

Given the audited scan output (scripts/exp_real_input_40_rho_ppp_prime_scan.py),
we form a derived "workload" metric that makes the space/time tradeoff explicit:

  r(p) := rho_{p,p,p}/lambda in (0,1]
  Delta(p) := -log r(p)            (spectral-tax rate)
  |G_p| := p^3                      (residue class count for ((p,p,p)))
  W(p) := log |G_p| / Delta(p)      (steps needed to amortize log|G_p|)

This is the simplest auditable proxy for “adding axes may slow down”: if p grows
but r(p) approaches 1 (Delta shrinks), then W(p) can increase.

Outputs:
  - artifacts/export/real_input_40_spectral_tax_workload.json
  - sections/generated/tab_real_input_40_spectral_tax_workload.tex

All stdout is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Sequence

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class Row:
    p: int
    axis: str
    rho_over_lambda: float
    delta_minus_log_rho_over_lambda: float
    log_G: float
    workload_W: float


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _write_tex(path: Path, rows: Sequence[Row]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_spectral_tax_workload.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{Spectral-tax workload proxy for the prime-modulus scan. "
        "For $((p,p,p))$ we have $|G_p|=p^3$ classes. "
        "Given $r=\\rho_{p,p,p}/\\lambda$ and $\\Delta=-\\log r$, we report "
        "$W(p)=\\log|G_p|/\\Delta=3\\log p/(-\\log(\\rho/\\lambda))$. "
        "Non-monotonicity of $W(p)$ makes the statement “adding axes may slow down” "
        "auditable.}"
    )
    lines.append("\\label{tab:real-input-40-spectral-tax-workload}")
    lines.append("\\begin{tabular}{r l r r r r}")
    lines.append("\\toprule")
    lines.append("$p$ & axis & $\\rho/\\lambda$ & $\\Delta$ & $\\log|G_p|$ & $W(p)$\\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.p} & {r.axis} & {_fmt(r.rho_over_lambda)} & {_fmt(r.delta_minus_log_rho_over_lambda)}"
            f" & {_fmt(r.log_G)} & {_fmt(r.workload_W)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Derived workload W(p) from rho_{p,p,p}/lambda scan JSON.")
    ap.add_argument(
        "--in-json",
        type=str,
        default=str(export_dir() / "real_input_40_rho_ppp_prime_scan.json"),
        help="Input JSON from exp_real_input_40_rho_ppp_prime_scan.py",
    )
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_spectral_tax_workload.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_real_input_40_spectral_tax_workload.tex"),
    )
    args = ap.parse_args()

    in_path = Path(args.in_json)
    payload = json.loads(in_path.read_text(encoding="utf-8"))
    rows_in = payload.get("rows", [])
    if not isinstance(rows_in, list) or not rows_in:
        raise SystemExit(f"[spectral-tax] empty or invalid rows in {in_path}")

    rows: List[Row] = []
    for d in rows_in:
        if not isinstance(d, dict):
            continue
        p = int(d["p"])
        axis = str(d.get("third_axis", ""))
        rho_over_lambda = float(d["rho_over_lambda"])
        delta = float(d["delta_minus_log_rho_over_lambda"])
        log_G = 3.0 * math.log(float(p))
        W = float("inf") if not (delta > 0.0) else (log_G / delta)
        rows.append(
            Row(
                p=p,
                axis=axis,
                rho_over_lambda=rho_over_lambda,
                delta_minus_log_rho_over_lambda=delta,
                log_G=log_G,
                workload_W=W,
            )
        )

    rows.sort(key=lambda r: (r.axis, r.p))

    out_payload: Dict[str, Any] = {
        "meta": {"script": Path(__file__).name, "in_json": str(in_path)},
        "rows": [asdict(r) for r in rows],
    }
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(out_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[spectral-tax] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, rows)
    print(f"[spectral-tax] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

