#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Large-deviation rate function interface for the fold gauge anomaly.

This script is English-only by repository convention.

We expose the LDP interface for the mismatch count
  G_m = sum_{t=1}^m 1{X_t != Y_t}
under the uniform micro baseline (IID Bernoulli(1/2) input driving the Berstel
unambiguous Zeckendorf normalizer).

The SCGF (pressure) is:
  P_G(theta) = log rho(A_theta),
with A_theta the 4x4 weighted adjacency from exp_fold_gauge_anomaly_pressure.py.

The LDP rate function is the Legendre--Fenchel transform:
  I(a) = sup_theta (a theta - P_G(theta)).

We also report endpoint closed forms:
  I(0) = -lim_{theta->-inf} P_G(theta) = log(2/phi),
  I(1) = -lim_{theta->+inf} (P_G(theta) - theta) = log 2.

Output:
- sections/generated/eq_fold_gauge_anomaly_ldp_rate.tex
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import List

import sympy as sp

from common_paths import generated_dir


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    _t0 = time.time()

    # TeX-friendly endpoint closed forms.
    I0_tex = r"\log(2/\varphi)"
    I1_tex = r"\log 2"

    # TeX fragment (Chinese, consistent with the paper).
    tex: List[str] = []
    tex.append("% Auto-generated by scripts/exp_fold_gauge_anomaly_ldp_rate.py")
    tex.append(r"\begin{proposition}[规范差的大偏差率函数接口（Legendre 变换 + 端点闭式）]\label{prop:fold-gauge-anomaly-ldp}")
    tex.append(
        r"在均匀基线 $\omega\sim\mathrm{Unif}(\Omega_{m+1})$ 下，令 $G_m=\sum_{t=1}^{m}g_t$，其中 $g_t=\mathbf 1\{X_t\neq Y_t\}$ 为规范差的逐位失配指示。"
        r"则对任意 $a\in[0,1]$，比例 $G_m/m$ 满足大偏差原理，其速率函数可由压力函数做 Legendre--Fenchel 变换给出："
    )
    tex.append(r"\[")
    tex.append(r"I(a)=\sup_{\theta\in\mathbb R}\bigl(a\theta-P_G(\theta)\bigr),\qquad P_G(\theta)=\log\rho(A_\theta),")
    tex.append(r"\]")
    tex.append(
        r"其中 $A_\theta$ 为命题 \ref{prop:fold-gauge-anomaly-pressure} 的 $4\times 4$ 加权邻接矩阵。"
        r"并且端点的稀有事件指数具有完全闭式："
    )
    tex.append(r"\[")
    tex.append(r"\boxed{\ I(0)=%s,\qquad I(1)=%s\ }." % (I0_tex, I1_tex))
    tex.append(r"\]")
    tex.append(r"\end{proposition}")
    tex.append("")
    tex.append(r"\begin{proof}[证明要点（可审计）]")
    tex.append(
        r"由于 $g_t$ 是有限状态边移位上的可加观测量，G\"artner--Ellis 定理给出 $I$ 为 $P_G$ 的 Legendre--Fenchel 变换。"
        r"端点闭式来自极限扭曲：当 $\theta\to-\infty$（即 $u=e^\theta\to 0$）时，失配边权趋于 $0$，谱半径退化为“全匹配子图”的 Perron 根，给出 $P_G(-\infty)=\log(\varphi/2)$，故 $I(0)=-P_G(-\infty)=\log(2/\varphi)$；"
        r"当 $\theta\to+\infty$ 时，谱半径由全失配三环支配，满足 $P_G(\theta)=\theta-\log 2+o(1)$，故 $I(1)=\log 2$。"
    )
    tex.append(r"\end{proof}")
    tex.append("")

    out_tex = generated_dir() / "eq_fold_gauge_anomaly_ldp_rate.tex"
    _write_text(out_tex, "\n".join(tex))
    print(f"[fold_gauge_anomaly_ldp_rate] wrote {out_tex}", flush=True)
    _ = _t0  # suppress unused-variable lint in some editors


if __name__ == "__main__":
    main()

