#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit the decomposition M(u)=M0+u*M1 for the real-input 40-state kernel (output potential only).

This script is intentionally *audit-oriented*:
- constructs integer adjacency matrices M0 (e=0 edges) and M1 (e=1 edges),
- checks whether M1^2 is identically zero (it is not, even on the largest SCC),
- computes the 2-step effective operator A := M0*M1 + M1*M0 and its spectral radius,
  and compares it to the quartic root y_max solving y^4-6y^3+9y^2-y-1=0.

Outputs:
- artifacts/export/real_input_40_output_potential_M1_audit.json
- sections/generated/eq_real_input_40_output_potential_M1_audit.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import mpmath as mp
import numpy as np

from common_paths import export_dir, generated_dir
from exp_sync_kernel_real_input_40 import build_kernel_edges, build_kernel_map, build_real_input_states


State = Tuple[str, int, int]  # (kernel_state, p_x, p_y)


@dataclass(frozen=True)
class Edge:
    src_idx: int
    dst_idx: int
    src: State
    dst: State
    x: int
    y: int
    d: int
    e: int


def _outgoing_edges(
    states: Sequence[State],
    idx: Dict[State, int],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
    i: int,
) -> List[Edge]:
    s, px, py = states[i]
    out: List[Edge] = []
    for x in (0, 1):
        if px == 1 and x == 1:
            continue
        for y in (0, 1):
            if py == 1 and y == 1:
                continue
            d = x + y
            dst_s, e = kernel_map[(s, d)]
            dst = (dst_s, x, y)
            j = idx[dst]
            out.append(
                Edge(
                    src_idx=i,
                    dst_idx=j,
                    src=states[i],
                    dst=dst,
                    x=x,
                    y=y,
                    d=d,
                    e=e,
                )
            )
    return out


def _kosaraju_scc(adj: List[List[int]]) -> List[List[int]]:
    n = len(adj)
    rev: List[List[int]] = [[] for _ in range(n)]
    for i in range(n):
        for j in adj[i]:
            rev[j].append(i)

    seen = [False] * n
    order: List[int] = []

    def dfs(v: int) -> None:
        seen[v] = True
        for w in adj[v]:
            if not seen[w]:
                dfs(w)
        order.append(v)

    for v in range(n):
        if not seen[v]:
            dfs(v)

    comp = [-1] * n
    comps: List[List[int]] = []

    def dfs2(v: int, cid: int) -> None:
        comp[v] = cid
        comps[-1].append(v)
        for w in rev[v]:
            if comp[w] == -1:
                dfs2(w, cid)

    for v in reversed(order):
        if comp[v] == -1:
            cid = len(comps)
            comps.append([])
            dfs2(v, cid)

    return comps


@dataclass(frozen=True)
class Witness2Step:
    # e=1 then e=1 path
    step1: Edge
    step2: Edge


def _find_M1_squared_witness(
    out_edges: List[List[Edge]],
) -> Optional[Witness2Step]:
    n = len(out_edges)
    M1_out: List[List[Edge]] = [[] for _ in range(n)]
    for i in range(n):
        M1_out[i] = [e for e in out_edges[i] if e.e == 1]
    for i in range(n):
        for e1 in M1_out[i]:
            j = e1.dst_idx
            for e2 in M1_out[j]:
                return Witness2Step(step1=e1, step2=e2)
    return None


def _fmt_state(st: State) -> str:
    s, px, py = st
    return f"({s};p_x={px},p_y={py})"


def _write_tex(path: Path, payload: dict) -> None:
    w = payload["witness_e1_e1"]
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_output_potential_M1_audit.py")
    lines.append("\\paragraph{Audit: $M(u)=M_0+uM_1$ and the two-step operator $M_0M_1+M_1M_0$ (real-input-40, output potential)}")
    lines.append("We split the 40-state adjacency by the output bit $e\\in\\{0,1\\}$ as $M(u)=M_0+uM_1$.")
    lines.append("On this kernel, $M_1^2$ is \\emph{not} zero, even restricted to the largest SCC of the underlying directed graph.")
    lines.append("")
    lines.append("\\begin{equation*}")
    lines.append(
        "\\boxed{\\ \\rho(M_0M_1+M_1M_0)=y_{\\max},\\quad y_{\\max}^4-6y_{\\max}^3+9y_{\\max}^2-y_{\\max}-1=0\\ }"
    )
    lines.append("\\end{equation*}")
    lines.append("\\noindent Numerical certificate (double precision):")
    lines.append("\\begin{equation*}")
    lines.append(
        f"\\rho(M_0M_1+M_1M_0)\\approx {payload['rho_A']},\\qquad y_\\max\\approx {payload['y_max']}."
    )
    lines.append("\\end{equation*}")
    lines.append("")
    lines.append("\\noindent Explicit 2-step witness for $M_1^2\\ne 0$ (two consecutive $e=1$ steps):")
    lines.append("\\begin{align*}")
    lines.append(
        "&v_0="
        + f"\\text{{{w['v0']}}}\\ (\\# {w['i0']})"
        + "\\xrightarrow{(x,y)="
        + f"({w['x0']},{w['y0']}),\\ d={w['d0']},\\ e=1"
        + "}v_1="
        + f"\\text{{{w['v1']}}}\\ (\\# {w['i1']})\\\\"
    )
    lines.append(
        "&v_1="
        + f"\\text{{{w['v1']}}}\\ (\\# {w['i1']})"
        + "\\xrightarrow{(x,y)="
        + f"({w['x1']},{w['y1']}),\\ d={w['d1']},\\ e=1"
        + "}v_2="
        + f"\\text{{{w['v2']}}}\\ (\\# {w['i2']}) ."
    )
    lines.append("\\end{align*}")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit M0/M1 and the two-step operator for real-input-40.")
    parser.add_argument(
        "--dps",
        type=int,
        default=80,
        help="mpmath precision for quartic root computation.",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_output_potential_M1_audit.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_real_input_40_output_potential_M1_audit.tex"),
    )
    args = parser.parse_args()

    kernel_map = build_kernel_map(build_kernel_edges())
    states = build_real_input_states()
    idx = {st: i for i, st in enumerate(states)}
    n = len(states)

    out_edges: List[List[Edge]] = [
        _outgoing_edges(states, idx, kernel_map, i) for i in range(n)
    ]

    # Underlying adjacency (ignoring multiplicities).
    adj: List[List[int]] = []
    for i in range(n):
        adj.append(sorted({e.dst_idx for e in out_edges[i]}))
    sccs = _kosaraju_scc(adj)
    scc_sizes = sorted([len(c) for c in sccs], reverse=True)
    largest_scc = max(sccs, key=len)
    S = sorted(largest_scc)

    # Build integer adjacency matrices M0/M1 with multiplicities.
    M0 = np.zeros((n, n), dtype=int)
    M1 = np.zeros((n, n), dtype=int)
    for i in range(n):
        for e in out_edges[i]:
            if e.e == 0:
                M0[i, e.dst_idx] += 1
            else:
                M1[i, e.dst_idx] += 1

    M1_sq = M1 @ M1
    M1_S = M1[np.ix_(S, S)]
    M1_sq_S = M1_S @ M1_S

    # Two-step effective operator.
    A = (M0.astype(float) @ M1.astype(float)) + (M1.astype(float) @ M0.astype(float))
    rho_A = float(np.max(np.abs(np.linalg.eigvals(A))))

    mp.mp.dps = int(args.dps)
    roots = mp.polyroots([1, -6, 9, -1, -1])  # y^4 - 6 y^3 + 9 y^2 - y - 1
    reals = [r.real for r in roots if abs(r.imag) < mp.mpf("1e-40")]
    y_max = max(reals)

    # Find an explicit e=1 then e=1 witness.
    w = _find_M1_squared_witness(out_edges)
    if w is None:
        raise SystemExit("Unexpected: no e=1->e=1 witness found, but M1^2 should be nonzero.")

    witness = {
        "i0": int(w.step1.src_idx),
        "i1": int(w.step1.dst_idx),
        "i2": int(w.step2.dst_idx),
        "v0": _fmt_state(w.step1.src),
        "v1": _fmt_state(w.step1.dst),
        "v2": _fmt_state(w.step2.dst),
        "x0": int(w.step1.x),
        "y0": int(w.step1.y),
        "d0": int(w.step1.d),
        "x1": int(w.step2.x),
        "y1": int(w.step2.y),
        "d1": int(w.step2.d),
    }

    payload: Dict[str, object] = {
        "n_states": n,
        "scc_count": len(sccs),
        "scc_sizes_desc": scc_sizes,
        "largest_scc_size": len(S),
        "M1_nonzeros": int(np.count_nonzero(M1)),
        "M1_sq_nonzeros": int(np.count_nonzero(M1_sq)),
        "M1_nonzeros_on_largest_scc": int(np.count_nonzero(M1_S)),
        "M1_sq_nonzeros_on_largest_scc": int(np.count_nonzero(M1_sq_S)),
        "rho_A": float(rho_A),
        "y_max": float(y_max),
        "abs_diff_rhoA_ymax": float(abs(mp.mpf(rho_A) - y_max)),
        "witness_e1_e1": witness,
    }

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[M1-audit] wrote {jout}", flush=True)

    _write_tex(Path(args.tex_out), payload)
    print(f"[M1-audit] wrote {args.tex_out}", flush=True)
    print("[M1-audit] done", flush=True)


if __name__ == "__main__":
    main()

