#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
De-prime-powers primitive error for the real-input 40-state kernel.

We work with the untwisted 40x40 adjacency M and its Perron root λ=ρ(M)=φ^2.
Let a_n := Tr(M^n) and define primitive orbit counts (Witt/Möbius):
  p_n := (1/n) * sum_{d|n} μ(d) a_{n/d}.

To remove the "prime-powers/Perron" contamination inside the Möbius inversion,
define the de-prime-powers primitive:
  p_n^sharp := (1/n) * sum_{d|n} μ(d) (a_{n/d} - λ^{n/d}).

Normalize at square-root scale:
  E_n^plain := (n/λ^{n/2}) * (p_n - λ^n/n),
  E_n^sharp := (n/λ^{n/2}) * p_n^sharp.

Under kernel-RH with semisimple critical-circle spectrum μ_j=√λ e^{iα_j},
one has E_n^sharp = Σ_j e^{inα_j} + o(1), while E_n^plain mixes in the
Perron prime-powers term(s) (e.g. the d=2 parity gate).

Outputs (default):
  - artifacts/export/real_input_40_pn_sharp.json
  - sections/generated/tab_real_input_40_pn_sharp.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import cmath
import json
import math
from dataclasses import dataclass
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress
from exp_sync_kernel_real_input_40 import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_matrix_int,
    build_real_input_states,
    mobius,
    spectral_radius,
    traces_and_primitives_int,
)


@dataclass(frozen=True)
class PhasePeak:
    theta: float
    magnitude: float


def _divisors_upto(N: int) -> List[List[int]]:
    divs: List[List[int]] = [[] for _ in range(N + 1)]
    for d in range(1, N + 1):
        for n in range(d, N + 1, d):
            divs[n].append(d)
    return divs


def _top_phase_peaks_from_series(
    series: Sequence[complex],
    *,
    grid: int,
    top_k: int,
    min_sep_bins: int,
) -> List[PhasePeak]:
    """Return top peaks of |Σ_{n>=1} series[n-1] e^{-i n θ}| on a uniform θ-grid."""
    if grid <= 16:
        raise ValueError("grid too small; use >= 16")
    if top_k <= 0:
        return []
    if min_sep_bins < 0:
        min_sep_bins = 0

    N = len(series)
    if N == 0:
        return []

    twopi = 2.0 * math.pi
    mags: List[Tuple[float, float]] = []  # (mag, theta)
    for k in range(grid):
        theta = twopi * (float(k) / float(grid))
        acc = 0.0 + 0.0j
        for n, z in enumerate(series, start=1):
            acc += z * cmath.exp(-1j * float(n) * theta)
        mags.append((abs(acc) / float(N), float(theta)))
    mags.sort(key=lambda t: (-t[0], t[1]))

    picked: List[PhasePeak] = []
    used_bins: List[int] = []
    for mag, theta in mags:
        if len(picked) >= top_k:
            break
        b = int(round(theta / twopi * grid)) % grid
        ok = True
        for ub in used_bins:
            dist = min((b - ub) % grid, (ub - b) % grid)
            if dist <= min_sep_bins:
                ok = False
                break
        if not ok:
            continue
        used_bins.append(b)
        picked.append(PhasePeak(theta=float(theta), magnitude=float(mag)))
    return picked


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_table_tex(
    *,
    out_path: Path,
    n_list: List[int],
    E_plain: List[float],
    E_sharp: List[float],
    pred_plain: List[float],
    pred_sharp: List[float],
    head_rows: int,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    rows = min(int(head_rows), len(n_list))
    if rows <= 0:
        rows = min(16, len(n_list))

    def fmt(x: float) -> str:
        return f"{x:+.8f}".replace("+", "\\phantom{-}")

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_pn_sharp.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{De-prime-powers primitive error for the real-input 40-state kernel. "
        "We report $E_n^{\\mathrm{plain}}$ vs $E_n^{\\sharp}$ on the first few lengths $n$.}"
    )
    lines.append("\\label{tab:real_input_40_pn_sharp}")
    lines.append("\\begin{tabular}{r r r r r}")
    lines.append("\\toprule")
    lines.append("$n$ & $E_n^{\\mathrm{plain}}$ & $E_n^{\\sharp}$ & pred$(E_n^{\\mathrm{plain}})$ & pred$(E_n^{\\sharp})$\\\\")
    lines.append("\\midrule")
    for i in range(rows):
        n = n_list[i]
        lines.append(
            f"{n} & {fmt(E_plain[i])} & {fmt(E_sharp[i])} & {fmt(pred_plain[i])} & {fmt(pred_sharp[i])}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="De-prime-powers primitive error (real-input 40-state kernel).")
    ap.add_argument("--N", type=int, default=200, help="Max n for a_n/p_n and E_n series (default: 200)")
    ap.add_argument("--precision", type=int, default=160, help="Decimal precision (digits) for de-prime-powers cancellation")
    ap.add_argument("--phase-grid", type=int, default=4096, help="DFT grid size for phase peak scan")
    ap.add_argument("--phase-top-k", type=int, default=6, help="How many phase peaks to report")
    ap.add_argument("--phase-min-sep-bins", type=int, default=8, help="Min separation (grid bins) between reported peaks")
    ap.add_argument("--eig-tol", type=float, default=1e-8, help="Tolerance for | |mu|-sqrt(lambda) | when extracting critical phases")
    ap.add_argument("--head-rows", type=int, default=20, help="How many rows to show in the LaTeX head table")
    ap.add_argument("--no-tex", action="store_true", help="Skip writing LaTeX output")
    ap.add_argument("--no-json", action="store_true", help="Skip writing JSON output")
    ap.add_argument("--json-out", type=str, default="", help="Override JSON output path")
    ap.add_argument("--tex-out", type=str, default="", help="Override LaTeX output path")
    args = ap.parse_args()

    N = int(args.N)
    if N <= 0:
        raise SystemExit("--N must be positive")
    if int(args.precision) < 60:
        raise SystemExit("--precision too small; use >= 60")

    prog = Progress(label="real-input-40-pn-sharp", every_seconds=20.0)
    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()
    M_int = build_real_input_matrix_int(states, kernel_map)
    traces = traces_and_primitives_int(M_int, max_n=N, prog=prog)
    a_list_int = traces["a_n"]  # length N, 1-indexed by n+1
    p_list_int = traces["p_n"]  # length N

    # High-precision algebraic λ=φ^2 (and √λ=φ) in Decimal.
    getcontext().prec = int(args.precision)
    sqrt5 = Decimal(5).sqrt()
    lam = (Decimal(3) + sqrt5) / Decimal(2)  # φ^2
    sqrt_lam = lam.sqrt()  # φ

    # Precompute λ^k and (√λ)^k for k<=N.
    lam_pow: List[Decimal] = [Decimal(1)]
    for _k in range(1, N + 1):
        lam_pow.append(lam_pow[-1] * lam)
    sqrt_lam_pow: List[Decimal] = [Decimal(1)]
    for _k in range(1, N + 1):
        sqrt_lam_pow.append(sqrt_lam_pow[-1] * sqrt_lam)

    # Precompute divisors.
    divs = _divisors_upto(N)

    # Compute E_n^plain and E_n^sharp.
    n_list: List[int] = list(range(1, N + 1))
    E_plain: List[float] = []
    E_sharp: List[float] = []
    for n in range(1, N + 1):
        # plain: (n/λ^{n/2})(p_n - λ^n/n)
        pn = Decimal(int(p_list_int[n - 1]))
        En_plain = (Decimal(n) / sqrt_lam_pow[n]) * (pn - (lam_pow[n] / Decimal(n)))

        # sharp: (n/λ^{n/2}) * (1/n) Σ_{d|n} μ(d) (a_{n/d} - λ^{n/d})
        acc = Decimal(0)
        for d in divs[n]:
            mu = int(mobius(d))
            if mu == 0:
                continue
            k = n // d
            ak = Decimal(int(a_list_int[k - 1]))
            acc += Decimal(mu) * (ak - lam_pow[k])
        pn_sharp = acc / Decimal(n)
        En_sharp = (Decimal(n) / sqrt_lam_pow[n]) * pn_sharp

        E_plain.append(float(En_plain))
        E_sharp.append(float(En_sharp))

    # Extract critical-circle phases from the numeric spectrum (sanity cross-check).
    M_float = np.array(M_int, dtype=float)
    eigs = np.linalg.eigvals(M_float)
    lam_float = spectral_radius(M_float)
    sqrt_lam_float = float(lam_float**0.5)
    tol = float(args.eig_tol)
    critical_eigs: List[complex] = []
    critical_phases: List[float] = []
    for ev in eigs:
        if abs(abs(ev) - sqrt_lam_float) <= tol:
            critical_eigs.append(complex(ev))
            critical_phases.append(float(cmath.phase(complex(ev))))
    critical_phases.sort()

    def _pred_plain(n: int) -> float:
        # For this kernel: single phase α=π with the Perron "d=2" gate.
        # Pred(E_plain) ~ (-1)^n - 1_{2|n}.
        return (-1.0 if (n % 2 == 1) else 0.0)

    def _pred_sharp(n: int) -> float:
        # Pred(E_sharp) ~ (-1)^n.
        return (-1.0 if (n % 2 == 1) else +1.0)

    pred_plain = [_pred_plain(n) for n in n_list]
    pred_sharp = [_pred_sharp(n) for n in n_list]

    # Phase scan peaks from the empirical E_sharp series.
    peaks = _top_phase_peaks_from_series(
        [complex(x, 0.0) for x in E_sharp],
        grid=int(args.phase_grid),
        top_k=int(args.phase_top_k),
        min_sep_bins=int(args.phase_min_sep_bins),
    )

    # Tail errors (last window) as compact fingerprints.
    tail = max(10, min(50, N // 4))
    err_plain_tail = max(abs(E_plain[i] - pred_plain[i]) for i in range(N - tail, N))
    err_sharp_tail = max(abs(E_sharp[i] - pred_sharp[i]) for i in range(N - tail, N))

    payload: Dict[str, object] = {
        "kernel": "real_input_40",
        "N": int(N),
        "decimal_precision": int(args.precision),
        "lambda": float(lam),
        "sqrt_lambda": float(sqrt_lam),
        "spectrum": {
            "lambda_numeric": float(lam_float),
            "sqrt_lambda_numeric": float(sqrt_lam_float),
            "eig_tol": float(tol),
            "critical_eigs": [{"re": float(z.real), "im": float(z.imag), "abs": float(abs(z))} for z in critical_eigs],
            "critical_phases": [float(t) for t in critical_phases],
        },
        "series": {
            "n": n_list,
            "E_plain": [float(x) for x in E_plain],
            "E_sharp": [float(x) for x in E_sharp],
            "pred_plain": [float(x) for x in pred_plain],
            "pred_sharp": [float(x) for x in pred_sharp],
        },
        "phase_peaks_from_E_sharp": [{"theta": float(p.theta), "magnitude": float(p.magnitude)} for p in peaks],
        "tail_fingerprint": {
            "tail_window": int(tail),
            "max_abs_err_plain_tail": float(err_plain_tail),
            "max_abs_err_sharp_tail": float(err_sharp_tail),
        },
        "notes": {
            "pred_plain": "For this kernel, pred(E_plain) ≈ (-1)^n - 1_{2|n}.",
            "pred_sharp": "For this kernel, pred(E_sharp) ≈ (-1)^n (prime-powers removed).",
        },
    }

    if not args.no_json:
        out_json = Path(str(args.json_out)) if str(args.json_out).strip() else (export_dir() / "real_input_40_pn_sharp.json")
        _write_json(out_json, payload)
        print(f"[pn-sharp] wrote {out_json}", flush=True)

    if not args.no_tex:
        out_tex = Path(str(args.tex_out)) if str(args.tex_out).strip() else (generated_dir() / "tab_real_input_40_pn_sharp.tex")
        _write_table_tex(
            out_path=out_tex,
            n_list=n_list,
            E_plain=E_plain,
            E_sharp=E_sharp,
            pred_plain=pred_plain,
            pred_sharp=pred_sharp,
            head_rows=int(args.head_rows),
        )
        print(f"[pn-sharp] wrote {out_tex}", flush=True)

    print(
        "[pn-sharp] "
        f"N={N} tail={tail} "
        f"max_err_plain_tail={err_plain_tail:.3e} max_err_sharp_tail={err_sharp_tail:.3e} "
        f"phase_peaks={[(round(p.theta,6), round(p.magnitude,6)) for p in peaks]}",
        flush=True,
    )


if __name__ == "__main__":
    main()

