#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit ZG density poles, Lee--Yang dyadic branch towers, and field separation.

This script provides deterministic checks for three manuscript packets:

1. The Zeckendorf--Goedel prime-code Dirichlet series has residue equal to the
   natural density at s=1, and the zeta-normalized ratio converges to the same
   constant.
2. The five-component dyadic branch tower is modeled by five copies of Z_2^2,
   for which the doubling map has exactly one fixed point on each component.
3. The local cumulant field Q(sqrt(5)) is linearly disjoint from the Lee--Yang
   branch cubic field generated by u = kappa_*^2.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Dict, List

import mpmath as mp
import sympy as sp

from common_paths import export_dir


def _mp_str(x: mp.mpf | mp.mpc, nd: int = 18) -> str:
    if isinstance(x, mp.mpc):
        sign = "+" if x.imag >= 0 else ""
        return f"{mp.nstr(x.real, nd)}{sign}{mp.nstr(x.imag, nd)}j"
    return mp.nstr(x, nd)


def _sp_str(expr: sp.Expr) -> str:
    return str(sp.simplify(expr))


def _first_n_primes(n: int) -> List[int]:
    if n <= 0:
        return []
    if n < 6:
        bound = 15
    else:
        bound = int(n * (math.log(n) + math.log(math.log(n))) + 20)
    while True:
        primes = list(sp.primerange(2, bound + 1))
        if len(primes) >= n:
            return [int(p) for p in primes[:n]]
        bound *= 2


def _prime_weight(p: int, s: mp.mpf) -> mp.mpf:
    return mp.e ** (-s * mp.log(p))


def _zg_truncated_dirichlet(primes: List[int], s: mp.mpf) -> mp.mpf:
    if not primes:
        return mp.mpf("1")
    f_nm2 = mp.mpf("1")
    f_nm1 = mp.mpf("1") + _prime_weight(primes[0], s)
    if len(primes) == 1:
        return f_nm1
    for p in primes[1:]:
        w = _prime_weight(p, s)
        f_nm2, f_nm1 = f_nm1, f_nm1 + w * f_nm2
    return f_nm1


def _zg_transfer_value(primes: List[int], s: mp.mpf) -> mp.mpf:
    a = mp.mpf("1")
    b = mp.mpf("0")
    for p in primes:
        w = _prime_weight(p, s)
        a, b = a + b, w * a
    return a + b


def _zg_hardcore_factor(primes: List[int], s: mp.mpf) -> mp.mpf:
    if not primes:
        return mp.mpf("1")
    u_prev = mp.mpf("0")
    log_h = mp.mpf("0")
    for idx, p in enumerate(primes, start=1):
        w = _prime_weight(p, s)
        if idx == 1:
            u = mp.mpf("1") + w
        else:
            u = mp.mpf("1") + w / u_prev
        log_h += mp.log(u) - mp.log(mp.mpf("1") + w)
        u_prev = u
    return mp.e ** log_h


def _zg_density_pole_audit(n_primes: int) -> Dict[str, object]:
    primes = _first_n_primes(n_primes)
    s_one = mp.mpf("1")
    f_one = _zg_truncated_dirichlet(primes, s_one)
    transfer_one = _zg_transfer_value(primes, s_one)
    euler_factor = mp.mpf("1")
    for p in primes:
        euler_factor *= mp.mpf("1") - mp.mpf("1") / p
    delta_prefix = euler_factor * f_one
    h_one = _zg_hardcore_factor(primes, s_one)
    residue_prefix = h_one / mp.zeta(2)

    eps_values = [
        mp.mpf("1e-1"),
        mp.mpf("5e-2"),
        mp.mpf("2e-2"),
        mp.mpf("1e-2"),
        mp.mpf("5e-3"),
        mp.mpf("2e-3"),
    ]
    limit_samples: List[Dict[str, object]] = []
    for eps in eps_values:
        s = s_one + eps
        f_trunc = _zg_truncated_dirichlet(primes, s)
        transfer = _zg_transfer_value(primes, s)
        h_s = _zg_hardcore_factor(primes, s)
        d_approx = h_s * mp.zeta(s) / mp.zeta(2 * s)
        scaled = eps * d_approx
        normalized = d_approx / mp.zeta(s)
        limit_samples.append(
            {
                "epsilon": _mp_str(eps, 8),
                "truncated_dirichlet": _mp_str(f_trunc, 20),
                "transfer_dirichlet": _mp_str(transfer, 20),
                "truncated_transfer_gap": _mp_str(abs(f_trunc - transfer), 8),
                "scaled_pole_value": _mp_str(scaled, 20),
                "scaled_pole_gap_to_density": _mp_str(abs(scaled - delta_prefix), 8),
                "zeta_normalized_value": _mp_str(normalized, 20),
                "zeta_normalized_gap_to_density": _mp_str(abs(normalized - delta_prefix), 8),
            }
        )

    return {
        "n_primes": n_primes,
        "delta_prefix": _mp_str(delta_prefix, 24),
        "residue_prefix": _mp_str(residue_prefix, 24),
        "delta_residue_gap": _mp_str(abs(delta_prefix - residue_prefix), 8),
        "truncated_value_at_one": _mp_str(f_one, 20),
        "transfer_value_at_one": _mp_str(transfer_one, 20),
        "value_at_one_gap": _mp_str(abs(f_one - transfer_one), 8),
        "limit_samples": limit_samples,
    }


def _fixed_points_on_z2_square(level: int, iterate: int) -> int:
    modulus = 1 << level
    multiplier = pow(2, iterate, modulus)
    fixed_1d = [
        x for x in range(modulus) if ((multiplier - 1) * x) % modulus == 0
    ]
    return len(fixed_1d) ** 2


def _leyang_branch_tower_audit() -> Dict[str, object]:
    branch_counts = [
        {"n": n, "component_size": 4**n, "total_size": 5 * (4**n)}
        for n in range(6)
    ]

    fixed_point_checks = []
    for iterate in range(1, 7):
        per_component = _fixed_points_on_z2_square(level=6, iterate=iterate)
        fixed_point_checks.append(
            {
                "iterate": iterate,
                "per_component": per_component,
                "all_five_components": 5 * per_component,
            }
        )

    z = sp.Symbol("z")
    trunc_order = 8
    log_series_from_counts = sp.expand(
        sum(sp.Integer(5) * z**n / sp.Integer(n) for n in range(1, trunc_order))
    )
    log_series_from_closed_form = sp.series(
        sp.log((1 - z) ** (-5)), z, 0, trunc_order
    ).removeO()

    return {
        "component_count": 5,
        "component_model": "Z_2^2",
        "finite_level_branch_counts": branch_counts,
        "fixed_point_checks": fixed_point_checks,
        "artin_mazur_closed_form": "(1 - z)^(-5)",
        "log_series_from_counts": _sp_str(log_series_from_counts),
        "log_series_from_closed_form": _sp_str(log_series_from_closed_form),
        "log_series_match": bool(
            sp.simplify(log_series_from_counts - log_series_from_closed_form) == 0
        ),
    }


def _squarefree_kernel(n: int) -> int:
    if n == 0:
        return 0
    sign = -1 if n < 0 else 1
    out = sign
    for prime, exponent in sp.factorint(abs(n)).items():
        if exponent % 2 == 1:
            out *= int(prime)
    return out


def _field_separation_audit() -> Dict[str, object]:
    u = sp.Symbol("u")
    x = sp.Symbol("x")
    sqrt5 = sp.sqrt(5)
    cubic_expr = 324 * u**3 - 540 * u**2 + 333 * u - 74
    cubic = sp.Poly(cubic_expr, u, domain="ZZ")
    cubic_over_qsqrt5 = sp.Poly(cubic_expr, u, extension=[sqrt5])
    _, ext_factors = cubic_over_qsqrt5.factor_list()
    irreducible_over_qsqrt5 = bool(
        len(ext_factors) == 1
        and int(ext_factors[0][0].degree()) == 3
        and int(ext_factors[0][1]) == 1
    )

    root = sp.RootOf(cubic_expr, 0)
    sum_minpoly = sp.Poly(sp.minpoly(root + sqrt5, x), x)
    discriminant = int(sp.discriminant(cubic_expr, u))
    squarefree = _squarefree_kernel(discriminant)

    return {
        "local_field": "Q(sqrt(5))",
        "branch_cubic": _sp_str(cubic_expr),
        "irreducible_over_Q": bool(cubic.is_irreducible),
        "irreducible_over_Q_sqrt5": irreducible_over_qsqrt5,
        "factorization_over_Q_sqrt5": [
            {
                "factor": _sp_str(factor.as_expr()),
                "degree": int(factor.degree()),
                "exponent": int(exponent),
            }
            for factor, exponent in ext_factors
        ],
        "branch_discriminant": str(discriminant),
        "quadratic_resolvent_squarefree_kernel": int(squarefree),
        "quadratic_resolvent_field": "Q(sqrt(-111))",
        "sum_generator_minpoly": _sp_str(sum_minpoly.as_expr()),
        "sum_generator_degree": int(sum_minpoly.degree()),
        "intersection_degree": 1,
        "compositum_degree": 6,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit ZG poles, Lee--Yang dyadic branch towers, and field separation."
    )
    parser.add_argument(
        "--n-primes",
        type=int,
        default=5000,
        help="Number of initial primes used in the ZG density/residue audit.",
    )
    parser.add_argument(
        "--dps",
        type=int,
        default=100,
        help="mpmath decimal precision.",
    )
    args = parser.parse_args()

    mp.mp.dps = int(args.dps)

    payload = {
        "meta": {
            "script": Path(__file__).name,
            "mpmath_dps": int(args.dps),
            "sympy": sp.__version__,
        },
        "zg_density_pole_audit": _zg_density_pole_audit(int(args.n_primes)),
        "leyang_branch_tower_audit": _leyang_branch_tower_audit(),
        "field_separation_audit": _field_separation_audit(),
    }

    out_path = export_dir() / "xi_zg_branch_tower_field_separation_audit.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[write] {out_path}")


if __name__ == "__main__":
    main()
