#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Strong lumpability counterexample for the Q6 simple random walk under Fold^{bin}_6 fibers.

All code is English-only by repository convention.

We consider the simple random walk on the 6-cube:
  - State space: Omega_6 = {0,1}^6, identified with integers n in {0,...,63} via int_6.
  - One step: pick a coordinate uniformly among 6 and flip it (i.e., n -> n XOR 2^j).

Let F6(omega) = Fold^{bin}_6(int_6(omega)) in X6.
The partition into fibers {F6^{-1}(x)}_{x in X6} is strongly lumpable iff for any x and any two
microstates n,n' in the same fiber, the one-step probability mass sent to each fiber y is identical.
Equivalently, for fixed x, the neighbor-label count vector must be constant on the fiber.

This script exports an explicit witness of failure at window-6:
  n=0 (bits 000000) and n'=21 (bits 010101) lie in the same fiber x=000000,
  but their neighbor-label multisets (and hence neighbor count vectors) differ.

Outputs:
  - artifacts/export/foldbin6_strong_lumpability_counterexample.json
  - sections/generated/eq_foldbin6_strong_lumpability_counterexample.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str, zeckendorf_digits


def _bits6_str(n: int) -> str:
    if n < 0 or n >= 64:
        raise ValueError("n must be in [0,63]")
    return "".join("1" if (n >> k) & 1 else "0" for k in [5, 4, 3, 2, 1, 0])


def _foldbin6_label(n: int) -> str:
    # For m=6, K(6)=9 (F_{10}=55 ≤ 63 < F_{11}=89), so digits up to k=9 are exact.
    digits = zeckendorf_digits(n, 9)  # digits for weights F_{k+1}, k=1..9
    return word_to_str(digits[:6])


def _neighbor_ints(n: int) -> List[int]:
    return [n ^ (1 << j) for j in range(6)]


def _neighbor_labels(n: int, *, label_of_n: List[str]) -> List[str]:
    return [label_of_n[nn] for nn in _neighbor_ints(n)]


def _count_labels(labels: List[str]) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for w in labels:
        out[w] = out.get(w, 0) + 1
    return out


def _write_eq_tex(
    *,
    x: str,
    n0: int,
    n1: int,
    nb0: List[str],
    nb1: List[str],
    witness_y: str,
    c0: int,
    c1: int,
    out_path: Path,
) -> None:
    # We display the two neighbor multisets explicitly (6 items each), plus one differing count.
    def _tex_list(words: List[str]) -> str:
        inner = ",\\ ".join([f"\\texttt{{{w}}}" for w in sorted(words)])
        return f"\\bigl\\{{{inner}\\bigr\\}}"

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_foldbin6_strong_lumpability_counterexample.py")
    lines.append("\\begin{equation}\\label{eq:foldbin6_strong_lumpability_counterexample}")
    lines.append("\\begin{aligned}")
    lines.append(
        f"F_6(\\texttt{{{_bits6_str(n0)}}})&=F_6(\\texttt{{{_bits6_str(n1)}}})=\\texttt{{{x}}},\\\\"
    )
    lines.append(
        f"\\#\\{{\\omega'\\sim\\texttt{{{_bits6_str(n0)}}}:\\ F_6(\\omega')=\\texttt{{{witness_y}}}\\}}"
        f"&={c0},\\qquad"
        f"\\#\\{{\\omega'\\sim\\texttt{{{_bits6_str(n1)}}}:\\ F_6(\\omega')=\\texttt{{{witness_y}}}\\}}={c1},\\\\"
    )
    lines.append(
        f"\\bigl\\{{F_6(\\omega'):\\ \\omega'\\sim\\texttt{{{_bits6_str(n0)}}}\\bigr\\}}&={_tex_list(nb0)},\\\\"
        f"\\bigl\\{{F_6(\\omega'):\\ \\omega'\\sim\\texttt{{{_bits6_str(n1)}}}\\bigr\\}}&={_tex_list(nb1)}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Export a strong lumpability counterexample for Fold^{bin}_6 on Q6.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "foldbin6_strong_lumpability_counterexample.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_foldbin6_strong_lumpability_counterexample.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    args = ap.parse_args()

    label_of_n: List[str] = [_foldbin6_label(n) for n in range(64)]
    x6_words = sorted(set(label_of_n))
    if len(x6_words) != 21:
        raise RuntimeError(f"Unexpected |X6|={len(x6_words)} (expected 21).")

    # Witness (paper-level): n=0 and n=21 are in the same fiber x=000000.
    n0, n1 = 0, 21
    x0, x1 = label_of_n[n0], label_of_n[n1]
    if x0 != x1:
        raise RuntimeError(f"Witness microstates are not in the same fiber: {x0} vs {x1}")
    x = x0

    nb0 = _neighbor_labels(n0, label_of_n=label_of_n)
    nb1 = _neighbor_labels(n1, label_of_n=label_of_n)
    cnb0 = _count_labels(nb0)
    cnb1 = _count_labels(nb1)

    # Find a stable type y with differing neighbor counts.
    diffs: List[Tuple[str, int, int]] = []
    for y in x6_words:
        a = cnb0.get(y, 0)
        b = cnb1.get(y, 0)
        if a != b:
            diffs.append((y, a, b))
    if not diffs:
        raise RuntimeError("Unexpected: witness microstates have identical neighbor-label counts.")
    witness_y, c0, c1 = diffs[0]

    # Global strong lumpability scan: count fibers where neighbor profile is not constant.
    fibers: Dict[str, List[int]] = {w: [] for w in x6_words}
    for n in range(64):
        fibers[label_of_n[n]].append(n)

    nonconstant_fibers: List[str] = []
    for w, pts in fibers.items():
        profiles = set()
        for n in pts:
            prof = tuple(_count_labels(_neighbor_labels(n, label_of_n=label_of_n)).get(y, 0) for y in x6_words)
            profiles.add(prof)
        if len(profiles) != 1:
            nonconstant_fibers.append(w)

    payload: Dict[str, object] = {
        "m": 6,
        "x6_words": x6_words,
        "witness": {
            "fiber_x": x,
            "n0": n0,
            "n1": n1,
            "bits0": _bits6_str(n0),
            "bits1": _bits6_str(n1),
            "neighbor_ints0": _neighbor_ints(n0),
            "neighbor_ints1": _neighbor_ints(n1),
            "neighbor_bits0": [_bits6_str(nn) for nn in _neighbor_ints(n0)],
            "neighbor_bits1": [_bits6_str(nn) for nn in _neighbor_ints(n1)],
            "neighbor_labels0": nb0,
            "neighbor_labels1": nb1,
            "neighbor_label_counts0": {k: int(v) for k, v in sorted(cnb0.items())},
            "neighbor_label_counts1": {k: int(v) for k, v in sorted(cnb1.items())},
            "first_diff_y": witness_y,
            "first_diff_counts": {"from_bits0": int(c0), "from_bits1": int(c1)},
        },
        "strong_lumpability": {
            "holds": False,
            "nonconstant_fibers_count": len(nonconstant_fibers),
            "nonconstant_fibers": nonconstant_fibers,
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = Path(str(args.tex_eq_out))
    _write_eq_tex(
        x=x,
        n0=n0,
        n1=n1,
        nb0=nb0,
        nb1=nb1,
        witness_y=witness_y,
        c0=c0,
        c1=c1,
        out_path=tex_out,
    )

    print(f"[foldbin6_lumpability] wrote {json_out}", flush=True)
    print(f"[foldbin6_lumpability] wrote {tex_out}", flush=True)


if __name__ == "__main__":
    main()

