#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: Slater three-return-times for an induced rotation.

This script is English-only by repository convention.

We numerically verify, away from endpoints, that the first return time to
I=[0,beta) under rotation by alpha takes values in {r,s,r+s}, where
  r = min{k>=1: {k alpha} in [0,beta)}
  s = min{k>=1: {k alpha} in (1-beta,1)}.

Outputs a LaTeX table snippet for insertion into the paper.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from decimal import Decimal, getcontext
from pathlib import Path
from typing import List, Set, Tuple


ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "sections" / "generated"


@dataclass
class Progress:
    label: str
    every_seconds: float = 20.0
    _t0: float = time.time()
    _last: float = 0.0

    def tick(self, msg: str) -> None:
        now = time.time()
        if self._last == 0.0:
            self._last = now
        if now - self._last >= self.every_seconds:
            dt = now - self._t0
            print(f"[{self.label}] t={dt:.1f}s {msg}", flush=True)
            self._last = now


def frac(x: Decimal) -> Decimal:
    return x - x.to_integral_value(rounding="ROUND_FLOOR")


def first_hit(alpha: Decimal, beta: Decimal, max_k: int, eps: Decimal) -> int:
    for k in range(1, max_k + 1):
        t = frac(Decimal(k) * alpha)
        if t >= -eps and t < beta - eps:
            return k
    raise RuntimeError("first_hit did not find within max_k")


def first_hit_upper(alpha: Decimal, beta: Decimal, max_k: int, eps: Decimal) -> int:
    one = Decimal(1)
    for k in range(1, max_k + 1):
        t = frac(Decimal(k) * alpha)
        if t > one - beta + eps and t < one - eps:
            return k
    raise RuntimeError("first_hit_upper did not find within max_k")


def return_time(
    alpha: Decimal, beta: Decimal, x: Decimal, max_k: int, eps: Decimal
) -> int:
    # x assumed in [0,beta)
    for k in range(1, max_k + 1):
        t = frac(x + Decimal(k) * alpha)
        if t >= -eps and t < beta - eps:
            return k
    raise RuntimeError("return_time did not return within max_k")


def sample_return_times(
    alpha: Decimal,
    beta: Decimal,
    samples: int,
    max_k: int,
    eps: Decimal,
    prog: Progress,
) -> Set[int]:
    vals: Set[int] = set()
    for j in range(samples):
        # Midpoint sampling avoids endpoints.
        x = (Decimal(j) + Decimal("0.5")) * beta / Decimal(samples)
        vals.add(return_time(alpha, beta, x, max_k=max_k, eps=eps))
        if (j + 1) % 200 == 0:
            prog.tick(f"beta={beta} sampled={j + 1}/{samples} unique={len(vals)}")
    return vals


def fmt_set(s: Set[int]) -> str:
    return "{" + ",".join(str(v) for v in sorted(s)) + "}"


def compute_row(
    alpha: Decimal,
    beta: Decimal,
    samples: int,
    max_k: int,
    eps: Decimal,
    prog: Progress,
) -> Tuple[int, int, Set[int]]:
    r = first_hit(alpha, beta, max_k=max_k, eps=eps)
    s = first_hit_upper(alpha, beta, max_k=max_k, eps=eps)
    vals = sample_return_times(
        alpha, beta, samples=samples, max_k=max_k, eps=eps, prog=prog
    )
    allowed = {r, s, r + s}
    bad = vals - allowed
    if bad:
        raise RuntimeError(
            f"Found disallowed return times {bad} for beta={beta}; allowed={allowed}"
        )
    return r, s, vals


def write_tex(rows: List[Tuple[str, int, int, Set[int]]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_return_time_slater_certificate.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{rlll}")
    lines.append("\\toprule")
    lines.append("$\\beta$ & $r$ & $s$ & observed $\\{\\tau_I(x)\\}$ \\\\")
    lines.append("\\midrule")
    for beta_s, r, s, vals in rows:
        vals_s = ",".join(str(v) for v in sorted(vals))
        lines.append(f"{beta_s} & {r} & {s} & $\\{{{vals_s}\\}}$ \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Numerical audit (away from endpoints) for Slater's three-return-times property (Theorem~\\ref{thm:slater-three-return-times}) at $\\alpha=\\varphi^{-2}$.}"
    )
    lines.append("\\label{tab:slater_return_time_certificate}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    getcontext().prec = 80
    prog = Progress("slater")

    sqrt5 = Decimal(5).sqrt()
    phi = (Decimal(1) + sqrt5) / Decimal(2)
    alpha = Decimal(1) / (phi * phi)

    # A few betas, chosen to avoid trivialities and to show 2- and 3-value cases.
    betas = [
        Decimal("0.10"),
        Decimal("0.20"),
        Decimal("0.30"),
        Decimal("0.38196601125010515179"),  # phi^{-2}
    ]
    eps = Decimal("1e-30")
    samples = 2000
    max_k = 20000

    rows: List[Tuple[str, int, int, Set[int]]] = []
    for beta in betas:
        r, s, vals = compute_row(
            alpha, beta, samples=samples, max_k=max_k, eps=eps, prog=prog
        )
        beta_s = str(beta.normalize())
        rows.append((beta_s, r, s, vals))
        prog.tick(f"done beta={beta_s} r={r} s={s} vals={sorted(vals)}")

    out = GEN / "tab_slater_return_time_certificate.tex"
    write_tex(rows, out)
    print(f"File: {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
