#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Exact hitting-time quantiles for the event clock (real-input 40-state kernel).

We work at theta=0 (unweighted adjacency), under the Parry equilibrium Markov chain.
The event clock is the additive functional

  T_n := sum_{t=0}^{n-1} e_t,

where e_t in {0,1} is the output bit on the edge taken at step t.

We compute the exact distribution of T_n for n=0..N via dynamic programming on
the (state, event-count) space, and derive exact quantiles for the hitting time

  tau(k) := inf { n >= 1 : T_n >= k }.

Identity used:
  P(tau(k) <= n) = P(T_n >= k).

Outputs:
- artifacts/export/real_input_40_hitting_time_exact_quantiles.json
- sections/generated/tab_real_input_40_hitting_time_exact_quantiles.tex
"""

from __future__ import annotations

import argparse
import json
import math
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from exp_real_input_40_time_correlation import _pick_pf_eigpair, parry_markov
from exp_sync_kernel_real_input_40 import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_states,
    build_weighted_matrix,
)


def _fmt(x: float) -> str:
    if math.isnan(x):
        return "\\mathrm{NaN}"
    if not math.isfinite(x):
        return "\\infty"
    # For table readability: integer-like values still display with decimals.
    return f"{x:.12f}"


def _edge_e(
    states: List[Tuple[str, int, int]],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
    i: int,
    j: int,
) -> int:
    (s, _px, _py) = states[i]
    (dst_state, x, y) = states[j]
    d = int(x) + int(y)
    dst2, e = kernel_map[(s, d)]
    if dst2 != dst_state:
        raise RuntimeError(
            f"edge mismatch: {states[i]} -> {states[j]} gives dst={dst2}"
        )
    return int(e)


def _event_weighted_transition(
    P: np.ndarray,
    states: List[Tuple[str, int, int]],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
) -> np.ndarray:
    n = int(P.shape[0])
    E = np.zeros((n, n), dtype=np.int8)
    for i in range(n):
        for j in range(n):
            if float(P[i, j]) <= 0.0:
                continue
            E[i, j] = np.int8(_edge_e(states, kernel_map, i=i, j=j))
    return E


def _mu_from_edges(pi: np.ndarray, P: np.ndarray, E: np.ndarray) -> float:
    # mu = E[e_0] where e_0 is on the first step.
    # Starting with state distribution pi, then one transition.
    return float(np.sum((pi[:, None] * P) * E))


def _dist_Tn(
    *,
    pi: np.ndarray,
    P: np.ndarray,
    E: np.ndarray,
    n_max: int,
    tick_seconds: float = 20.0,
) -> List[np.ndarray]:
    # Returns list dist[n][m] = P(T_n = m) for n=0..n_max.
    n_states = int(P.shape[0])
    dists: List[np.ndarray] = []

    # dp[state, m] at current n.
    dp = np.zeros((n_states, n_max + 1), dtype=float)
    dp[:, 0] = pi
    dist0 = np.sum(dp, axis=0)
    dists.append(dist0.copy())

    t_last = time.time()
    for n in range(1, n_max + 1):
        nxt = np.zeros_like(dp)
        # Complexity: O(n_states^2 * n_max) with small constants.
        for i in range(n_states):
            row = dp[i]
            if float(np.sum(row)) <= 0.0:
                continue
            for j in range(n_states):
                pij = float(P[i, j])
                if pij <= 0.0:
                    continue
                e = int(E[i, j])
                if e == 0:
                    nxt[j, :] += row * pij
                else:
                    # shift by one in event-count
                    nxt[j, 1:] += row[:-1] * pij
        dp = nxt
        dist = np.sum(dp, axis=0)
        dists.append(dist.copy())

        now = time.time()
        if now - t_last >= tick_seconds:
            print(f"[hit-quant] progressed n={n}/{n_max}", flush=True)
            t_last = now
    return dists


def _tau_cdf_from_dist(dist: np.ndarray, k: int) -> float:
    # P(tau(k) <= n) = P(T_n >= k)
    if k <= 0:
        return 1.0
    if k >= len(dist):
        return 0.0
    return float(np.sum(dist[k:]))


def _quantile_tau(
    dists: List[np.ndarray],
    k: int,
    q: float,
) -> int:
    # Minimal n >= 1 such that P(tau(k) <= n) >= q.
    if not (q >= 0.0 and q <= 1.0):
        raise ValueError("q must be in [0,1]")
    for n in range(1, len(dists)):
        if _tau_cdf_from_dist(dists[n], k=k) >= q:
            return n
    return len(dists) - 1


def _write_tex(
    path: Path,
    mu: float,
    q_lo: float,
    q_hi: float,
    rows: List[Dict[str, float]],
) -> None:
    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_hitting_time_exact_quantiles.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{事件时钟击中时间 $\\tau(k)$ 的精确分位数区间（真实输入 40 状态核；$t=0$ Parry 平衡态）。"
        f"设 $T_n=\\sum_{{t=0}}^{{n-1}} e_t$，$\\mu_e={_fmt(mu)}$，$\\tau(k)=\\inf\\{{n\\ge1:\\,T_n\\ge k\\}}$。"
        f"表中 $n_{{\\mathrm{{lo}}}}$ 与 $n_{{\\mathrm{{hi}}}}$ 分别为 $\\mathbb{{P}}(\\tau(k)\\le n_{{\\mathrm{{lo}}}})\\ge {q_lo:.3g}$ 与"
        f" $\\mathbb{{P}}(\\tau(k)\\le n_{{\\mathrm{{hi}}}})\\ge {q_hi:.3g}$ 的最小整数解（精确分布递推，无近似）。"
        "其中 $k/\\mu_e$ 为均值换时的参照点。}"
    )
    lines.append("\\label{tab:real-input-40-hitting-time-exact-quantiles}")
    lines.append("\\begin{tabular}{r r r r r r}")
    lines.append("\\toprule")
    lines.append(
        "$k$ & $k/\\mu_e$ & $n_{\\mathrm{lo}}$ & $n_{\\mathrm{med}}$ & $n_{\\mathrm{hi}}$ & $\\max\\{|n_{\\mathrm{lo}}-k/\\mu_e|,|n_{\\mathrm{hi}}-k/\\mu_e|\\}$\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{int(r['k'])}"
            f" & {_fmt(r['k_over_mu'])}"
            f" & {int(r['n_lo'])}"
            f" & {int(r['n_med'])}"
            f" & {int(r['n_hi'])}"
            f" & {_fmt(r['max_abs_dev'])}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class Payload:
    model: str
    n_max: int
    mu_event: float
    q_lo: float
    q_hi: float
    k_list: List[int]
    rows: List[Dict[str, float]]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Exact tau(k) quantiles (real-input 40)."
    )
    parser.add_argument("--n-max", type=int, default=200)
    parser.add_argument("--q-lo", type=float, default=0.05)
    parser.add_argument("--q-hi", type=float, default=0.95)
    # Include k=8 since k_mix=ceil(mu_e*tau_mix)=8 for the default (3,3,5) twisted worst case.
    parser.add_argument("--k-list", type=str, default="5,8,10,20,50")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_hitting_time_exact_quantiles.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(
            generated_dir() / "tab_real_input_40_hitting_time_exact_quantiles.tex"
        ),
    )
    args = parser.parse_args()

    n_max = int(args.n_max)
    q_lo = float(args.q_lo)
    q_hi = float(args.q_hi)
    if n_max < 1:
        raise SystemExit("--n-max must be >= 1")
    if not (0.0 < q_lo < 1.0 and 0.0 < q_hi < 1.0 and q_lo < q_hi):
        raise SystemExit("need 0<q_lo<q_hi<1")

    k_list = [int(x.strip()) for x in str(args.k_list).split(",") if x.strip()]
    k_list = sorted({k for k in k_list if k >= 1})
    if not k_list:
        raise SystemExit("empty --k-list")

    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()
    B0 = build_weighted_matrix(0.0, 0.0, 0.0, states, kernel_map)
    lam, _eigvals, v, u = _pick_pf_eigpair(B0)
    pi, P = parry_markov(B0, lam=lam, v=v, u=u)
    E = _event_weighted_transition(P, states, kernel_map)
    mu = _mu_from_edges(pi, P, E)

    dists = _dist_Tn(pi=pi, P=P, E=E, n_max=n_max)
    print(f"[hit-quant] computed exact distributions up to n={n_max}", flush=True)

    rows: List[Dict[str, float]] = []
    for k in k_list:
        k_over_mu = float(k) / float(mu)
        n_lo = _quantile_tau(dists, k=k, q=q_lo)
        n_med = _quantile_tau(dists, k=k, q=0.5)
        n_hi = _quantile_tau(dists, k=k, q=q_hi)
        max_abs_dev = float(
            max(abs(float(n_lo) - k_over_mu), abs(float(n_hi) - k_over_mu))
        )
        rows.append(
            {
                "k": float(k),
                "k_over_mu": float(k_over_mu),
                "n_lo": float(n_lo),
                "n_med": float(n_med),
                "n_hi": float(n_hi),
                "max_abs_dev": float(max_abs_dev),
            }
        )

    payload = Payload(
        model="real_input_40",
        n_max=int(n_max),
        mu_event=float(mu),
        q_lo=float(q_lo),
        q_hi=float(q_hi),
        k_list=[int(k) for k in k_list],
        rows=rows,
    )
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(
        json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"[hit-quant] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, mu=mu, q_lo=q_lo, q_hi=q_hi, rows=rows)
    print(f"[hit-quant] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()
