#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit the minimal 2/3/5 CRT depth (m=58) and the collision-gap coupling.

This script is intentionally small and fully deterministic. It turns the
paper-side statements into a machine-checkable certificate.

Outputs:
- artifacts/export/gut_crt_235_m58_collision_gap.json
- sections/generated/eq_gut_crt_235_m58_collision_gap.tex
"""

from __future__ import annotations

import json
from fractions import Fraction
from pathlib import Path
from typing import Dict, List, Tuple

from sympy import Poly, Symbol, factorint, nroots

from common_paths import export_dir, generated_dir
from common_phi_fold import fib_upto


def _format_sci_tex(x: float, sig: int = 5) -> str:
    """Format a positive float in TeX scientific notation."""
    if x == 0.0:
        return "0"
    if x < 0.0:
        raise ValueError("x must be non-negative")
    s = f"{x:.{sig}e}"  # e.g. 8.79650e-13
    mantissa, exp = s.split("e")
    exp_i = int(exp)
    mantissa = mantissa.rstrip("0").rstrip(".")
    return f"{mantissa}\\times 10^{{{exp_i}}}"


def _fib(n: int) -> int:
    if n <= 0:
        raise ValueError("n must be positive")
    return fib_upto(n)[-1]


def _find_min_m_for_mod30(m_max: int = 400) -> int:
    # We need the minimal m such that 30 | F_{m+2}.
    fib = fib_upto(m_max + 2)
    for m in range(1, m_max + 1):
        M = fib[m + 1]  # F_{m+2}
        if M % 30 == 0:
            return m
    raise RuntimeError(f"no solution found for m <= {m_max}")


def _s2_recurrence(m: int) -> int:
    """Exact S_2(m) from the 3rd-order recurrence (m>=2)."""
    if m < 2:
        raise ValueError("Require m >= 2")
    if m == 2:
        return 6
    if m == 3:
        return 14
    if m == 4:
        return 36
    s2 = {2: 6, 3: 14, 4: 36}
    for k in range(5, m + 1):
        s2[k] = 2 * s2[k - 1] + 2 * s2[k - 2] - 2 * s2[k - 3]
    return int(s2[m])


def _r2_root() -> float:
    """Largest real root of x^3 - 2x^2 - 2x + 2."""
    x = Symbol("x")
    poly = Poly(x**3 - 2 * x**2 - 2 * x + 2, x)
    roots = list(nroots(poly, n=50))
    real_roots = [complex(r) for r in roots if abs(complex(r).imag) < 1e-30]
    if not real_roots:
        raise RuntimeError("no real root found")
    r2 = max(real_roots, key=lambda z: z.real).real
    return float(r2)


def main() -> None:
    m_min = _find_min_m_for_mod30()
    n = m_min + 2
    if m_min != 58 or n != 60:
        raise RuntimeError(f"unexpected min depth: m_min={m_min}, n={n} (expected 58,60)")

    F_n = _fib(n)
    fac: Dict[int, int] = {int(p): int(e) for p, e in factorint(F_n).items()}

    S2 = _s2_recurrence(m_min)
    Col = Fraction(S2, 4**m_min)
    one_over_Fn = Fraction(1, F_n)
    gap = Col - one_over_Fn

    # Scaled ratios (dimensionless).
    Fn_Col = float(Col * F_n)
    Fn_gap = float(gap * F_n)

    # Zero-set lower bound on the m=58 (n=60) window: F_{n/2} = F_{30}.
    F_half = _fib(n // 2)

    # Exponential upper bound constant from Corollary cor:fold-col-gap-exp-upper.
    r2 = _r2_root()
    v_sum = 1.0 + r2 + r2 / (r2 - 1.0)
    C2 = 2.0 * v_sum / (r2 * r2)
    col_upper = C2 * (r2 / 4.0) ** m_min

    payload = {
        "params": {
            "m_min": m_min,
            "n": n,
            "modulus": "F_{m+2}",
            "axes": [2, 3, 5],
        },
        "F_n": {
            "n": n,
            "value": int(F_n),
            "factorization": {str(p): int(e) for p, e in sorted(fac.items())},
        },
        "collision": {
            "m": m_min,
            "S2": int(S2),
            "Col_frac": f"{Col.numerator}/{Col.denominator}",
            "Col_float": float(Col),
            "one_over_Fn_float": float(one_over_Fn),
            "gap_frac": f"{gap.numerator}/{gap.denominator}",
            "gap_float": float(gap),
            "Fn_times_Col": Fn_Col,
            "Fn_times_gap": Fn_gap,
        },
        "zero_set_lb": {
            "m": m_min,
            "value": int(F_half),
            "as": f"F_{{{n//2}}}",
        },
        "exp_upper_bound": {
            "r2": r2,
            "C2": C2,
            "Col_upper_float": col_upper,
        },
    }

    out_json = export_dir() / "gut_crt_235_m58_collision_gap.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_lines: List[str] = []
    tex_lines.append("% Auto-generated by exp_gut_crt_235_m58_collision_gap.py")
    tex_lines.append("\\[")
    tex_lines.append(
        "\\mathsf{Col}_{58}\\approx %s,\\qquad"
        % _format_sci_tex(float(Col), sig=5)
    )
    tex_lines.append(
        "\\frac{1}{F_{60}}\\approx %s,\\qquad"
        % _format_sci_tex(float(one_over_Fn), sig=5)
    )
    tex_lines.append(
        "g_{\\mathrm{col}}^2(58)\\approx %s."
        % _format_sci_tex(float(gap), sig=5)
    )
    tex_lines.append("\\]")
    tex_lines.append("\\[")
    tex_lines.append(
        "F_{60}\\mathsf{Col}_{58}\\approx %.6f,\\qquad F_{60}g_{\\mathrm{col}}^2(58)\\approx %.6f."
        % (Fn_Col, Fn_gap)
    )
    tex_lines.append("\\]")

    out_tex = generated_dir() / "eq_gut_crt_235_m58_collision_gap.tex"
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(tex_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()

