#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit certificate: mod-p factorization patterns for the A4(t) characteristic family.

We consider the integral one-parameter family
  p_t(x) = det(x I - A_4(t)) = x^5 - 2 x^4 - t x^3 - 2 x + 2  in Z[x].

For the congruence classes used in the paper, we certify:
  - mod 5: irreducibility for t ≡ 2,3 (so Gal contains a 5-cycle),
  - mod 29: factor pattern (1)(1)(1)(2) for t ≡ 0,1,7,28 (so Gal contains a transposition),
  - nonvanishing of the discriminant bracket polynomial Q(t) modulo 5 and 29
    at those residue classes (so the primes are unramified and Dedekind applies).

Outputs:
  - artifacts/export/collision_kernel_A4t_integral_charpoly_galois_modp_certificate.json
  - sections/generated/eq_collision_kernel_A4t_integral_charpoly_galois_modp_certificate.tex
"""

from __future__ import annotations

import argparse
import json
import warnings
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import sympy as sp

from common_paths import export_dir, generated_dir

try:
    from sympy.utilities.exceptions import SymPyDeprecationWarning

    warnings.filterwarnings("ignore", category=SymPyDeprecationWarning)
except Exception:
    # Compatibility fallback if SymPy changes warning paths.
    pass


@dataclass(frozen=True)
class ModFactorization:
    modulus: int
    t_value: int
    poly_mod: str
    factor_degrees: List[int]
    factors: List[str]


def _p_expr(t: int) -> sp.Expr:
    x = sp.Symbol("x")
    return x**5 - 2 * x**4 - t * x**3 - 2 * x + 2


def _Q_expr() -> sp.Expr:
    t = sp.Symbol("t")
    return 27 * t**5 + 35 * t**4 + 434 * t**3 + 4394 * t**2 + 10832 * t + 7403


def _factor_mod(p: int, t_value: int) -> ModFactorization:
    x = sp.Symbol("x")
    poly = sp.Poly(_p_expr(t_value), x, modulus=p)
    coeff, facs = sp.factor_list(poly)
    factors = [sp.Poly(f, x, modulus=p) for (f, _e) in facs for _ in range(_e)]
    degs = [int(f.degree()) for f in factors]
    # Stable formatting: use Poly.as_expr() (coeffs reduced mod p) then latex/string.
    return ModFactorization(
        modulus=p,
        t_value=t_value,
        poly_mod=str(poly.as_expr()),
        factor_degrees=sorted(degs, reverse=True),
        factors=[str(f.as_expr()) for f in factors],
    )


def _write_tex(path: Path, rows5: List[ModFactorization], rows29: List[ModFactorization]) -> None:
    Q = _Q_expr()
    t = sp.Symbol("t")

    def qmod(val: int, mod: int) -> int:
        return int(sp.Integer(Q.subs({t: val})) % mod)

    def poly_tex_from_str(expr_s: str, mod: int) -> str:
        x = sp.Symbol("x")
        poly = sp.Poly(sp.sympify(expr_s), x, modulus=mod)
        coeffs = [int(c) % mod for c in poly.all_coeffs()]
        deg = poly.degree()
        terms: List[str] = []
        for i, c in enumerate(coeffs):
            if c == 0:
                continue
            power = deg - i
            if power == 0:
                terms.append(f"{c}")
                continue
            if c == 1:
                coef = ""
            else:
                coef = f"{c} "
            if power == 1:
                terms.append(f"{coef}x".rstrip())
            else:
                terms.append(f"{coef}x^{{{power}}}".rstrip())
        return " + ".join(terms) if terms else "0"

    lines: List[str] = []
    lines.append(r"% Auto-generated by scripts/exp_collision_kernel_A4t_integral_charpoly_galois_modp_certificate.py")
    lines.append(r"\begin{equation}\label{eq:collision_kernel_A4t_integral_charpoly_galois_modp_certificate}")
    lines.append(r"\begin{aligned}")
    lines.append(
        r"Q(t)&:=27t^5+35t^4+434t^3+4394t^2+10832t+7403,"
    )

    # mod 5 irreducibility representatives
    for row in rows5:
        irreducible = row.factor_degrees == [5]
        status = r"\text{不可约}" if irreducible else r"\text{可约}"
        lines.append(
            rf"p_{{{row.t_value}}}(x)&\equiv {poly_tex_from_str(row.poly_mod, row.modulus)}\pmod{{{row.modulus}}},\quad {status},"
        )
    lines.append(
        rf"Q(2)&\equiv {qmod(2, 5)}\pmod{{5}},\qquad Q(3)\equiv {qmod(3, 5)}\pmod{{5}},"
    )

    # mod 29 transposition pattern representatives
    for row in rows29:
        fac_tex = "".join([f"({poly_tex_from_str(f, row.modulus)})" for f in row.factors])
        lines.append(
            rf"p_{{{row.t_value}}}(x)&\equiv {fac_tex}\pmod{{{row.modulus}}},"
        )
    lines.append(
        rf"Q(0)&\equiv {qmod(0, 29)}\pmod{{29}},\quad "
        rf"Q(1)\equiv {qmod(1, 29)}\pmod{{29}},\quad "
        rf"Q(7)\equiv {qmod(7, 29)}\pmod{{29}},\quad "
        rf"Q(28)\equiv {qmod(28, 29)}\pmod{{29}}."
    )

    lines.append(r"\end{aligned}")
    lines.append(r"\end{equation}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Certify mod-p factorization patterns for p_t(x)=x^5-2x^4-tx^3-2x+2."
    )
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4t_integral_charpoly_galois_modp_certificate.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4t_integral_charpoly_galois_modp_certificate.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    args = ap.parse_args()

    # Representatives of the congruence classes used in the paper.
    rows5 = [_factor_mod(5, 2), _factor_mod(5, 3)]
    rows29 = [_factor_mod(29, 0), _factor_mod(29, 1), _factor_mod(29, 7), _factor_mod(29, 28)]

    out = {
        "mod5": [asdict(r) for r in rows5],
        "mod29": [asdict(r) for r in rows29],
    }

    json_path = Path(args.json_out)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_path = Path(args.tex_eq_out)
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    _write_tex(tex_path, rows5=rows5, rows29=rows29)


if __name__ == "__main__":
    main()

