#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Even-spectrum (z^2) elimination for the 4th-collision kernel family A_4(t).

We consider the one-parameter family (t replaces the single multi-edge weight "7"):

  A_4(t) =
    [[0,1,0,0,0],
     [0,0,t,0,1],
     [0,1,2,0,0],
     [1,0,1,0,0],
     [0,0,0,1,0]].

Define:
  D_t(z) := det(I - z A_4(t)),
  E_t(u) := det(I - u A_4(t)^2)  (u = z^2).

Then D_t(z) D_t(-z) = det(I - z^2 A_4(t)^2) = E_t(z^2), and E_t(u) is a quintic
polynomial with integer coefficients in (t,u). Its discriminant in u factorizes
explicitly and excludes even-spectrum degeneracy for t >= 0.

Moreover, eliminating r between the Perron curve P_t(r)=det(rI-A_4(t)) and the even
spectrum embedding constraint r^5 E_t(1/r)=0 yields a resultant whose nontrivial
degree-8 factor is exactly the Newman/RH threshold certificate P_4(t).

In addition, the 'completed' even-spectrum polynomial

  Xi_t(u) := u^5 E_t(1/u) + 4 E_t(u)

admits a full factorization into a linear factor and two quadratic Gamma-factors.
This yields a closed reconstruction formula expressing E_t(u) purely in terms of
those Gamma-factors, and shows that the curve constraint r^5 E_t(1/r)=0 is (up to
a constant 15) equivalent to a shorter, purely Gamma-defined quintic.

Outputs:
  - artifacts/export/collision_kernel_A4_even_zeta_elimination.json
  - sections/generated/eq_collision_kernel_A4_even_zeta_quintic.tex
  - sections/generated/eq_collision_kernel_A4_newman_resultant_curve_intersection.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Tuple

import sympy as sp

from common_paths import export_dir, generated_dir


def _A4(t: sp.Symbol) -> sp.Matrix:
    return sp.Matrix(
        [
            [0, 1, 0, 0, 0],
            [0, 0, t, 0, 1],
            [0, 1, 2, 0, 0],
            [1, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
        ]
    )


def _poly_P4() -> sp.Poly:
    t = sp.Symbol("t")
    P4 = t**8 - 10 * t**7 + 72 * t**6 - 24 * t**5 - 1924 * t**4 - 2904 * t**3 + 1312 * t**2 + 1464 * t - 1412
    return sp.Poly(sp.expand(P4), t)


def _factorint_str(n: int) -> Dict[str, int]:
    return {str(int(p)): int(e) for p, e in sp.factorint(int(n)).items()}


@dataclass(frozen=True)
class Payload:
    # E_t(u)
    E_t_u: str
    disc_u_E: str
    disc_u_E_factor: str
    # completed polynomial and Gamma factorization
    Xi_t_u: str
    Xi_t_u_factor: str
    Q_t_u: str
    E_from_Q: str
    # gamma curve reduction
    G_t_r: str
    # sanity checks
    check_E_ok: bool
    check_Xi_ok: bool
    check_E_from_Q_ok: bool
    check_G_ok: bool
    # resultant certificate
    resultant_r: str
    resultant_r_factor: str
    resultant_expected: str
    # sanity checks
    checks_ok: bool


def _write_tex_even_quintic(path: Path, *, E: sp.Expr, disc_u: sp.Expr) -> None:
    # Use a stable, human-auditable TeX certificate string (avoid reordering/expansion).
    E_tex = r"1-(2t+4)u+(t^2-4)u^2+(4t+8)u^3+4u^4-4u^5"
    disc_tex = (
        r"-256\,(t-1)^2(t+1)^2"
        r"\Bigl(27t^5+35t^4+434t^3+4394t^2+10832t+7403\Bigr)"
    )

    lines = [
        "% Auto-generated by scripts/exp_collision_kernel_A4_even_zeta_elimination.py",
        r"\begin{equation}\label{eq:collision_kernel_A4_even_zeta_quintic}",
        r"\begin{aligned}",
        rf"E_t(u):=\det(I-uA_4(t)^2)&={E_tex},\\",
        rf"\mathrm{{Disc}}_u(E_t)&={disc_tex}.",
        r"\end{aligned}",
        r"\end{equation}",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_tex_resultant(path: Path, *, P4: sp.Poly, Res: sp.Expr, Q: sp.Expr) -> None:
    # Stable, factored TeX certificate (matches the paper's edge-weight threshold polynomial).
    resultant_tex = (
        r"-8\,(t+1)^2"
        r"\Bigl(t^8-10t^7+72t^6-24t^5-1924t^4-2904t^3+1312t^2+1464t-1412\Bigr)"
    )

    lines = [
        "% Auto-generated by scripts/exp_collision_kernel_A4_even_zeta_elimination.py",
        r"\begin{equation}\label{eq:collision_kernel_A4_newman_resultant_curve_intersection}",
        r"\begin{aligned}",
        r"P_t(r)&:=r^5-2r^4-tr^3-2r+2,\\",
        r"r^5E_t(1/r)&=r^5-2tr^4-4r^4+t^2r^3-4r^3+4tr^2+8r^2+4r-4,\\",
        rf"\mathrm{{Res}}_r\!\bigl(P_t(r),\,r^5E_t(1/r)\bigr)&={resultant_tex}.",
        r"\end{aligned}",
        r"\end{equation}",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute E_t(u), Disc_u(E_t), and the Perron/even-spectrum resultant for A_4(t).")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4_even_zeta_elimination.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-even-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_even_zeta_quintic.tex"),
        help="Output TeX path for E_t(u) and Disc_u(E_t).",
    )
    parser.add_argument(
        "--tex-resultant-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_newman_resultant_curve_intersection.tex"),
        help="Output TeX path for the resultant identity.",
    )
    args = parser.parse_args()

    t = sp.Symbol("t")
    u = sp.Symbol("u")
    r = sp.Symbol("r")

    A = _A4(t)
    E = sp.expand((sp.eye(5) - u * (A**2)).det())

    # Closed form expected for E_t(u).
    E_expected = sp.expand(1 - (2 * t + 4) * u + (t**2 - 4) * u**2 + (4 * t + 8) * u**3 + 4 * u**4 - 4 * u**5)
    check_E = sp.expand(E - E_expected)

    disc_u = sp.discriminant(sp.Poly(E, u), u)
    disc_u_fact = sp.factor(disc_u)

    # Completed polynomial and Gamma-factorization.
    Xi = sp.expand(u**5 * sp.together(E_expected.subs(u, 1 / u)) + 4 * E_expected)
    Xi_fact = sp.factor(Xi)
    Q_u = sp.expand((t * u + 3 * u**2 - 2) * (t * u + 4 * t - 5 * u**2 + 4 * u + 6))
    Xi_expected = sp.expand(u * Q_u)
    check_Xi = sp.expand(Xi - Xi_expected)

    # Reconstruction of E_t(u) from Q_t(u).
    E_from_Q = sp.together((4 * u * Q_u - u**4 * sp.together(Q_u.subs(u, 1 / u))) / 15)
    E_from_Q = sp.expand(E_from_Q)
    check_E_from_Q = sp.expand(E_from_Q - E_expected)

    # Perron curve and even-spectrum embedding curve.
    P = sp.expand(r**5 - 2 * r**4 - t * r**3 - 2 * r + 2)
    Q = sp.expand(r**5 * sp.together(E_expected.subs(u, 1 / r)))
    # Ensure Q is polynomial in r.
    Q = sp.expand(sp.together(Q))

    # Short Gamma-based quintic (up to the constant 15): G_t(r) = 15 r^5 E_t(1/r).
    Q_r = sp.expand(Q_u.subs(u, r))
    Q_1r = sp.expand(sp.together(Q_u.subs(u, 1 / r)))
    G = sp.expand(4 * r**4 * Q_1r - r * Q_r)
    check_G = sp.expand(G - 15 * Q)

    Res = sp.resultant(P, Q, r)
    Res_fact = sp.factor(Res)

    P4 = _poly_P4()
    expected = sp.expand(-8 * (t + 1) ** 2 * P4.as_expr())
    check_Res = sp.expand(Res - expected)

    check_E_ok = (check_E == 0)
    check_Xi_ok = (check_Xi == 0)
    check_E_from_Q_ok = (check_E_from_Q == 0)
    check_G_ok = (check_G == 0)
    checks_ok = check_E_ok and check_Xi_ok and check_E_from_Q_ok and check_G_ok and (check_Res == 0)

    _write_tex_even_quintic(Path(args.tex_even_out), E=E_expected, disc_u=disc_u_fact)
    _write_tex_resultant(Path(args.tex_resultant_out), P4=P4, Res=Res, Q=Q)

    payload = Payload(
        E_t_u=str(E_expected),
        disc_u_E=str(disc_u),
        disc_u_E_factor=str(disc_u_fact),
        Xi_t_u=str(Xi_expected),
        Xi_t_u_factor=str(Xi_fact),
        Q_t_u=str(Q_u),
        E_from_Q=str(E_from_Q),
        G_t_r=str(G),
        check_E_ok=bool(check_E_ok),
        check_Xi_ok=bool(check_Xi_ok),
        check_E_from_Q_ok=bool(check_E_from_Q_ok),
        check_G_ok=bool(check_G_ok),
        resultant_r=str(Res),
        resultant_r_factor=str(Res_fact),
        resultant_expected=str(expected),
        checks_ok=bool(checks_ok),
    )

    out = Path(args.json_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[A4-even-zeta-elimination] wrote {out}", flush=True)
    if not checks_ok:
        raise RuntimeError("Sanity checks failed: expected closed forms did not match symbolic computations.")


if __name__ == "__main__":
    main()

