#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Monte Carlo audit of the fold-aware restriction gauge anomaly density.

This script is English-only by repository convention.

We sample omega ~ Unif(Omega_{m+1}) = {0,1}^{m+1} and estimate:
  E[G_m(omega)/m],
where
  G_m(omega) = | r_{m+1->m}(omega) xor r~_{m+1->m}(omega) |_0
is the Hamming distance between the naive truncation prefix and the fold-aware
restriction prefix of Fold_{m+1}.

Outputs:
- artifacts/export/fold_gauge_anomaly_mc.json
- sections/generated/tab_fold_gauge_anomaly_mc.tex
"""

from __future__ import annotations

import argparse
import json
import math
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Sequence

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress, fib_upto


def _parse_int_list(s: str) -> List[int]:
    s = s.strip()
    if not s:
        return []
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def _zeckendorf_digits_from_fib(N: int, m: int, fib: Sequence[int]) -> List[int]:
    """Zeckendorf digits (c_1..c_m) for weights F_{k+1}, k=1..m, using a provided fib table.

    Requirements:
    - fib must contain Fibonacci numbers F_1..F_{m+2} with F_1=F_2=1,
      i.e. len(fib) >= m+2 and fib[k] == F_{k+1}.
    """
    if N < 0:
        raise ValueError("N must be non-negative")
    if m <= 0:
        return []
    if len(fib) < m + 2:
        raise ValueError("fib table too short for requested m")

    digits = [0] * m
    remaining = N
    k = m
    while remaining > 0 and k >= 1:
        w = fib[k]  # weight F_{k+1}
        if w <= remaining:
            digits[k - 1] = 1
            remaining -= w
            k -= 2  # skip adjacent position
        else:
            k -= 1
    return digits


def _gauge_anomaly_ratio(bits: Sequence[int], m: int, fib: Sequence[int]) -> float:
    """Compute G_m(omega)/m for a length-(m+1) micro word omega."""
    if len(bits) != m + 1:
        raise ValueError("bits must have length m+1")
    prefix = bits[:-1]  # naive truncation r_{m+1->m}

    # N(omega) = sum_{k=1..m+1} omega_k F_{k+1}
    N = 0
    for k, b in enumerate(bits, start=1):
        if b:
            N += fib[k]  # F_{k+1}

    # Fold_{m+1}: compute Zeckendorf digits up to length (m+2) then drop overflow.
    digits = _zeckendorf_digits_from_fib(N, m + 2, fib)
    rem = digits[:m]  # fold-aware restriction prefix r~_{m+1->m}

    g = 0
    for a, b in zip(prefix, rem):
        g += int(a) ^ int(b)
    return g / float(m)


@dataclass(frozen=True)
class Row:
    m: int
    samples: int
    mean: float
    se: float
    abs_err_vs_4_9: float


def _write_tex(rows: List[Row], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    target = 4.0 / 9.0
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_gauge_anomaly_mc.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.12}")
    lines.append("\\begin{tabular}{rrrrr}")
    lines.append("\\toprule")
    lines.append("$m$ & samples & $\\widehat{\\mathbb{E}}[G_m/m]$ & SE & $\\,|\\,\\widehat{\\mathbb{E}}[G_m/m]-4/9\\,|$ \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.m} & {r.samples} & {r.mean:.6f} & {r.se:.2e} & {r.abs_err_vs_4_9:.6f} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Monte Carlo audit of the gauge-anomaly density $\\bar G_m/m$ under the uniform baseline "
        "$\\omega\\sim\\mathrm{Unif}(\\Omega_{m+1})$ at larger $m$. "
        "We report the sample mean of $G_m/m$ with its standard error (SE), "
        "and compare to the exact limit $4/9$ from Theorem~\\ref{thm:fold-gauge-anomaly-density}. "
        f"(Target $4/9\\approx {target:.6f}$.)}}"
    )
    lines.append("\\label{tab:fold_gauge_anomaly_mc}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Monte Carlo table for the gauge-anomaly density.")
    ap.add_argument("--ms", type=str, default="40,100,200", help="Comma-separated list of m values.")
    ap.add_argument(
        "--samples",
        type=str,
        default="20000,20000,80000",
        help="Comma-separated list of sample sizes (either one value or one per m).",
    )
    ap.add_argument("--seed", type=int, default=7, help="Base RNG seed (row i uses seed+1000*i).")
    ap.add_argument(
        "--json-out",
        type=Path,
        default=export_dir() / "fold_gauge_anomaly_mc.json",
        help="Output JSON path.",
    )
    ap.add_argument(
        "--tex-out",
        type=Path,
        default=generated_dir() / "tab_fold_gauge_anomaly_mc.tex",
        help="Output TeX table path.",
    )
    args = ap.parse_args()

    ms = _parse_int_list(str(args.ms))
    if not ms:
        raise SystemExit("Require at least one m.")

    ns = _parse_int_list(str(args.samples))
    if not ns:
        raise SystemExit("Require --samples.")
    if len(ns) == 1:
        ns = ns * len(ms)
    if len(ns) != len(ms):
        raise SystemExit("If --samples is a list, it must match the length of --ms.")
    if any(m <= 1 for m in ms):
        raise SystemExit("All m must be >= 2.")
    if any(n <= 0 for n in ns):
        raise SystemExit("All sample sizes must be positive.")

    t0 = time.time()
    prog = Progress("fold_gauge_anomaly_mc", every_seconds=20.0)
    rows: List[Row] = []
    target = 4.0 / 9.0

    for i, (m, n) in enumerate(zip(ms, ns)):
        rng = random.Random(int(args.seed) + 1000 * i + m)

        # Precompute Fibonacci table up to F_{(m+2)+2} = F_{m+4}.
        # Indices satisfy fib[k] == F_{k+1}, so we need k up to (m+2).
        fib = fib_upto(m + 4)

        # Welford for x = G_m/m
        mean = 0.0
        m2 = 0.0
        cnt = 0
        for s in range(n):
            bits = [rng.getrandbits(1) for _ in range(m + 1)]
            x = _gauge_anomaly_ratio(bits, m=m, fib=fib)
            cnt += 1
            delta = x - mean
            mean += delta / cnt
            delta2 = x - mean
            m2 += delta * delta2
            prog.tick(f"row={i+1}/{len(ms)} m={m} sample={s+1}/{n}")

        var = (m2 / (cnt - 1)) if cnt > 1 else 0.0
        se = math.sqrt(var / cnt) if cnt > 0 else float("nan")
        rows.append(Row(m=m, samples=n, mean=mean, se=se, abs_err_vs_4_9=abs(mean - target)))

        print(f"[fold_gauge_anomaly_mc] done m={m} n={n} mean(Gm/m)={mean:.6f} SE={se:.2e}", flush=True)

    # Write outputs.
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "rows": [asdict(r) for r in rows],
        "ms": ms,
        "samples": ns,
        "target_4_over_9": target,
        "seed": int(args.seed),
        "generated_at_unix_s": time.time(),
        "elapsed_s": time.time() - t0,
    }
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[fold_gauge_anomaly_mc] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(rows, tout)
    print(f"[fold_gauge_anomaly_mc] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

