#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Conditional covariance from the 3D Hessian at theta=0.

Appendix `sections/appendix/sync_kernel/app__vector-potential.tex` records the exact Hessian
for (phi_e, phi_-, phi_2) at theta=0. This script computes the conditional
covariance and correlation:
  Cov(phi_e, phi_- | phi_2)
from the Schur complement, and exports:
  - sections/generated/eq_sync_kernel_3d_conditional_covariance.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import sympy as sp

from common_paths import generated_dir


def write_eq_tex(path: Path) -> None:
    Hee = sp.Rational(11, 102)
    Hnn = sp.Rational(25, 128)
    H22 = sp.Rational(2, 9)
    He2 = sp.Rational(181, 1632)
    Hn2 = sp.Rational(5, 128)
    Hen = sp.Rational(0, 1)

    cond_cov = sp.simplify(Hen - He2 * Hn2 / H22)
    cond_var_e = sp.simplify(Hee - He2**2 / H22)
    cond_var_n = sp.simplify(Hnn - Hn2**2 / H22)
    cond_corr = sp.simplify(cond_cov / sp.sqrt(cond_var_e * cond_var_n))

    cond_cov_num = float(sp.N(cond_cov, 80))
    cond_corr_num = float(sp.N(cond_corr, 80))

    lines: list[str] = []
    lines.append("% Generated by scripts/exp_sync_kernel_3d_conditional_covariance.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\mathrm{Cov}(\\varphi_e,\\varphi_-\\mid\\varphi_2)"
        "=\\partial_{\\theta_e\\theta_-}^2P(0)"
        "-\\frac{\\partial_{\\theta_e\\theta_2}^2P(0)\\,\\partial_{\\theta_-\\theta_2}^2P(0)}{\\partial_{\\theta_2\\theta_2}^2P(0)}"
    )
    lines.append(f"&={sp.latex(cond_cov)}\\ \\ (\\approx {cond_cov_num:.6g}),\\\\")
    lines.append(
        "\\mathrm{Corr}(\\varphi_e,\\varphi_-\\mid\\varphi_2)"
        "=\\frac{\\mathrm{Cov}(\\varphi_e,\\varphi_-\\mid\\varphi_2)}"
        "{\\sqrt{\\mathrm{Var}(\\varphi_e\\mid\\varphi_2)\\,\\mathrm{Var}(\\varphi_-\\mid\\varphi_2)}}"
    )
    lines.append(f"&\\approx {cond_corr_num:.6g}.")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Conditional covariance from 3D Hessian.")
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_sync_kernel_3d_conditional_covariance.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()
    write_eq_tex(Path(args.tex_out))
    print(f"[sync-3d-cond] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

