#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Zero-parameter Hecke/E4 prime-skeleton audit.

This script generates a tiny, fully deterministic audit artifact:
for primes p in {2,3,5} it records the predicted coefficients

  a_p = 240(1+p^3)

of the weight-4 Eisenstein series E_4(q)=1+240*sum_{n>=1} sigma_3(n) q^n.

Outputs:
  - artifacts/export/hecke_e4_prime_audit_p235.json
  - sections/generated/tab_hecke_e4_prime_audit_p235.tex
"""

from __future__ import annotations

import json
from typing import Dict, List

from common_paths import export_dir, generated_dir


def _a_p(p: int) -> int:
    return 240 * (1 + p**3)


def main() -> None:
    primes = [2, 3, 5]
    rows: List[Dict[str, int]] = [{"p": p, "a_p": _a_p(p)} for p in primes]

    payload = {
        "formula": "a_p = 240(1+p^3) (prime p; weight-4 Eisenstein series E4)",
        "primes": primes,
        "rows": rows,
    }

    out_json = export_dir() / "hecke_e4_prime_audit_p235.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    lines = [f'{r["p"]} & {r["a_p"]} \\\\' for r in rows]

    out_tex = generated_dir() / "tab_hecke_e4_prime_audit_p235.tex"
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(
        "% AUTO-GENERATED by scripts/exp_hecke_e4_prime_audit.py\n"
        "\\begin{table}[H]\n"
        "\\centering\n"
        "\\scriptsize\n"
        "\\caption{零参数审计：权 $4$ Eisenstein 级数 $E_4(q)=1+240\\sum_{n\\ge 1}\\sigma_3(n)q^n$ 的素数系数预测。若某候选顶层统一母函数被声明为 $X(1)$ 上的标量 Hecke-闭合对象，则其素数骨架系数 $a_p$ 必须满足 $a_p=240(1+p^3)$；下表列出最小否定判据素数点 $p\\in\\{2,3,5\\}$.}\n"
        "\\label{tab:hecke_e4_prime_audit_p235}\n"
        "\\begin{tabular}{r r}\n"
        "\\toprule\n"
        "$p$ & $a_p=240(1+p^3)$\\\\\n"
        "\\midrule\n"
        + "\n".join(lines)
        + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n",
        encoding="utf-8",
    )

    print(f"[hecke_e4_prime_audit] wrote {out_json}")
    print(f"[hecke_e4_prime_audit] wrote {out_tex}")


if __name__ == "__main__":
    main()

