#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Bridge-Kit: a strictifiable, auditable bridge pack for prime-like vs trace-side checks.

This script bundles a *single runnable interface* that produces:
  - Anom_G (character-basis anomaly signature) from twisted finite-part constants,
  - Dirichlet–Mertens constant tensor C_r (class-basis constants),
  - low-dimensional fingerprints (delta_spec, E1, eta_tail, SVD),
  - optional "prime-like" cross-check: compute the same twisted constants via
    trace -> primitive (Möbius/Witt) -> partial sums, without log(det) evaluation,
  - optional anomaly-robust prime-register budget patch: P > 2 * exp(A_inf) * B_m(eps).

Current implementation targets the real-input 40-state kernel and the 3D arity tensor
((m1,m2,m3)) with third axis in {Ne, N2}, matching the paper pipeline scripts.

Outputs (default):
  - artifacts/export/bridge_kit_real_input_40_arity_{m1}{m2}{m3}_{axis}.json

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from common_tail_budget import (
    B_from_logB,
    gamma_cert_from_rq,
    logB_from_gamma,
    prime_list_for_log_target,
)
from exp_sync_kernel_real_input_40_arity_3d import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_states,
    build_weighted_matrix_numeric,
    mobius,
    spectral_radius,
    _twist_constant_via_mobius_logzeta,
)


GAMMA_EULER = 0.5772156649015329
PHI = (1.0 + 5.0**0.5) / 2.0
LAMBDA_UNTWISTED = PHI * PHI
Z_STAR = 1.0 / LAMBDA_UNTWISTED


class _NullProgress:
    """Minimal Progress stub for library helpers that call prog.tick()."""

    def tick(self, _msg: str) -> None:
        return


def _parse_triple(s: str) -> Tuple[int, int, int]:
    parts = [p.strip() for p in str(s).split("x")]
    if len(parts) != 3:
        raise SystemExit(f"Bad --triple {s!r}. Use m1xm2xm3, e.g. 3x3x5.")
    try:
        m1, m2, m3 = (int(parts[0]), int(parts[1]), int(parts[2]))
    except ValueError as exc:
        raise SystemExit(f"Bad --triple {s!r}. Use integers like 3x3x5.") from exc
    if m1 < 2 or m2 < 2 or m3 < 2:
        raise SystemExit("Triple entries must be >= 2.")
    return m1, m2, m3


def _fmt(x: float) -> str:
    return f"{x:.12g}"


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_bridgekit_fingerprint_tex(
    *,
    out_path: Path,
    third_axis: str,
    A_inf: float,
    delta_spec: float,
    E1: float,
    eta_tail: float,
    eta3_raw: float,
    eta3_centered: float,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_bridge_kit.py")
    lines.append(f"% Bridge-Kit fingerprints for ((3,3,5)) with third axis {third_axis}.")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\displaystyle "
        "A_\\infty"
        ":=\\max_{j\\ne 0}\\bigl|C(j)-\\log\\mathfrak{M}\\bigr|"
        f"&\\approx {A_inf:.12g},\\\\"
    )
    lines.append(
        "\\displaystyle "
        "\\delta_{\\mathrm{spec}}"
        ":=1-\\rho_{3,3,5}/\\lambda"
        f"&\\approx {delta_spec:.12g},\\\\"
    )
    lines.append(
        "\\displaystyle "
        "\\mathcal{E}_1"
        f"&\\approx {E1:.12g},\\qquad "
        "\\eta_{\\mathrm{tail}}"
        f"\\approx {eta_tail:.12g},\\\\"
    )
    lines.append(
        "\\displaystyle "
        "\\eta^{\\mathrm{raw}}_3"
        ":=\\frac{s_1^2+s_2^2+s_3^2}{\\sum_i s_i^2}"
        f"&\\approx {eta3_raw:.12g},\\\\"
    )
    lines.append(
        "\\displaystyle "
        "\\eta^{\\mathrm{cen}}_3"
        ":=\\frac{(s^{\\mathrm{cen}}_1)^2+(s^{\\mathrm{cen}}_2)^2+(s^{\\mathrm{cen}}_3)^2}{\\sum_i (s^{\\mathrm{cen}}_i)^2}"
        f"&\\approx {eta3_centered:.12g}.\\\\"
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")
    lines.append("\\[")
    lines.append(
        "\\boxed{\\;P\\;>\\;2\\,e^{A_\\infty}\\,B_m(\\varepsilon)\\;}"
        "\\qquad\\text{(anomaly-robust prime-register padding; constant-level)}"
    )
    lines.append("\\]")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _traces_from_matrix(M: np.ndarray, max_n: int) -> List[complex]:
    if max_n <= 0:
        return []
    A = M.copy()
    out: List[complex] = []
    for n in range(1, max_n + 1):
        if n > 1:
            A = A @ M
        out.append(complex(np.trace(A)))
    return out


def _pvals_from_traces(traces: List[complex]) -> List[complex]:
    max_n = len(traces)
    pvals: List[complex] = []
    for n in range(1, max_n + 1):
        s = 0.0 + 0.0j
        for d in range(1, n + 1):
            if n % d == 0:
                s += mobius(d) * traces[n // d - 1]
        pvals.append(s / float(n))
    return pvals


def _twist_constant_via_primitive_partial_sum(
    *,
    q: complex,
    r: complex,
    u: complex,
    states: List[Tuple[str, int, int]],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
    third_axis: str,
    N: int,
    z: float = Z_STAR,
) -> complex:
    """Prime-like estimator for C(q,r,u): truncate P(z)=sum_{n>=1} p_n z^n at n<=N."""
    if N <= 0:
        raise ValueError("N must be positive for primitive partial sum estimator")
    M = build_weighted_matrix_numeric(q, r, u, states, kernel_map, third_axis=third_axis)
    traces = _traces_from_matrix(M, max_n=N)
    pvals = _pvals_from_traces(traces)
    acc = 0.0 + 0.0j
    zz = float(z)
    for n, pn in enumerate(pvals, start=1):
        acc += pn * (zz**n)
    return acc


def _tensor_from_class_constants_335(class_C: Dict[str, float]) -> np.ndarray:
    """Return tensor C[a,b,c] in R^{3x3x5} from class_constants keys 'a,b,c'."""
    C = np.zeros((3, 3, 5), dtype=float)
    for a in range(3):
        for b in range(3):
            for c in range(5):
                C[a, b, c] = float(class_C[f"{a},{b},{c}"])
    return C


@dataclass(frozen=True)
class Fingerprints:
    rho_max_ratio: float
    delta_spec: float
    E1: float
    eta_tail: float
    svd_raw_energy_cum3: float
    svd_centered_energy_cum3: float


def _fingerprints_335_n2(
    *,
    class_C: Dict[str, float],
    rho_map: Dict[str, float],
    lam: float = LAMBDA_UNTWISTED,
) -> Tuple[Fingerprints, dict]:
    """Compute a compact set of audited fingerprints for ((3,3,5))."""
    # Spectral gap
    rho_max = max(float(v) for v in rho_map.values()) if rho_map else 0.0
    rho_ratio = (rho_max / float(lam)) if lam > 0 else 0.0
    delta_spec = 1.0 - rho_ratio

    C = _tensor_from_class_constants_335(class_C)

    # Fourier compression along c: A^(1), A^(2)
    omega = complex(math.cos(2 * math.pi / 5), math.sin(2 * math.pi / 5))
    A1 = np.zeros((3, 3), dtype=complex)
    A2 = np.zeros((3, 3), dtype=complex)
    for a in range(3):
        for b in range(3):
            f = np.array([C[a, b, c] for c in range(5)], dtype=complex)
            A1[a, b] = (1.0 / 5.0) * sum(f[c] * (omega ** (-1 * c)) for c in range(5))
            A2[a, b] = (1.0 / 5.0) * sum(f[c] * (omega ** (-2 * c)) for c in range(5))
    eA1 = float(np.sum(np.abs(A1) ** 2))
    eA2 = float(np.sum(np.abs(A2) ** 2))
    E1 = (eA1 / (eA1 + eA2)) if (eA1 + eA2) > 0 else float("nan")

    # Tail scalarization fingerprint eta_tail
    eta_tail = 0.0
    for c in (2, 3, 4):
        sl = C[:, :, c]
        mean_c = float(np.mean(sl))
        denom = abs(mean_c)
        if denom <= 0:
            continue
        delta = float(np.linalg.norm(sl - mean_c * np.ones((3, 3)), ord="fro"))
        eta_tail = max(float(eta_tail), float(delta) / float(denom))

    # SVD fingerprints: raw T (5x9) and c-centered T
    T = np.zeros((5, 9), dtype=float)
    for a in range(3):
        for b in range(3):
            col = a * 3 + b
            for c in range(5):
                T[c, col] = C[a, b, c]
    s_raw = np.linalg.svd(T, compute_uv=False)
    e_raw = s_raw**2
    svd_raw_energy_cum3 = float(np.sum(e_raw[:3]) / float(np.sum(e_raw))) if float(np.sum(e_raw)) > 0 else float("nan")

    Tc = T - np.mean(T, axis=0, keepdims=True)
    s_c = np.linalg.svd(Tc, compute_uv=False)
    e_c = s_c**2
    svd_centered_energy_cum3 = float(np.sum(e_c[:3]) / float(np.sum(e_c))) if float(np.sum(e_c)) > 0 else float("nan")

    fp = Fingerprints(
        rho_max_ratio=float(rho_ratio),
        delta_spec=float(delta_spec),
        E1=float(E1),
        eta_tail=float(eta_tail),
        svd_raw_energy_cum3=float(svd_raw_energy_cum3),
        svd_centered_energy_cum3=float(svd_centered_energy_cum3),
    )

    extra = {
        "rho_max": float(rho_max),
        "rho_max_ratio": float(rho_ratio),
        "delta_spec": float(delta_spec),
        "A1_frob2": float(eA1),
        "A2_frob2": float(eA2),
        "E1": float(E1),
        "eta_tail": float(eta_tail),
        "svd_raw_singular_values": [float(x) for x in s_raw],
        "svd_centered_singular_values": [float(x) for x in s_c],
        "svd_raw_energy_cum": {
            "1": float(e_raw[0] / np.sum(e_raw)),
            "2": float(np.sum(e_raw[:2]) / np.sum(e_raw)),
            "3": float(np.sum(e_raw[:3]) / np.sum(e_raw)),
        },
        "svd_centered_energy_cum": {
            "1": float(e_c[0] / np.sum(e_c)),
            "2": float(np.sum(e_c[:2]) / np.sum(e_c)),
            "3": float(np.sum(e_c[:3]) / np.sum(e_c)),
        },
        "slice_c0": [[float(C[a, b, 0]) for a in range(3)] for b in range(3)],
        "slice_c1": [[float(C[a, b, 1]) for a in range(3)] for b in range(3)],
        "c_means": [float(np.mean(C[:, :, c])) for c in range(5)],
    }
    return fp, extra


def _anom_signature(
    *, twist_C: Dict[str, Dict[str, float]], log_mathfrak_M: float
) -> Tuple[Dict[str, Dict[str, float]], float]:
    """Return anomaly vector Anom(j)=C(j)-logMfrak (as complex dict) and its l_inf size."""
    out: Dict[str, Dict[str, float]] = {}
    A_inf = 0.0
    for key, z in twist_C.items():
        # key is "j1,j2,j3"
        re = float(z["re"]) - float(log_mathfrak_M)
        im = float(z["im"])
        out[key] = {"re": float(re), "im": float(im)}
        A_inf = max(float(A_inf), float(abs(complex(re, im))))
    return out, float(A_inf)


def _rq_table_fold_exact(q_max: int) -> Dict[int, float]:
    """Load the audited exact Fold collision r_q table (q<=17) for budget patch."""
    import exp_fold_collision_renyi_spectrum as rs

    if q_max > 17:
        raise ValueError("Exact Fold r_q table only available up to q<=17.")
    rq: Dict[int, float] = {2: float(rs.perron_root_r2()), 3: float(rs.perron_root_r3()), 4: float(rs.perron_root_r4())}
    for q, v in rs.PRECOMPUTED_RQ.items():
        if int(q) <= int(q_max):
            rq[int(q)] = float(v)
    return rq


def main() -> None:
    ap = argparse.ArgumentParser(description="Bridge-Kit (real-input-40): Anom + constant tensor + fingerprints + optional cross-check/budget patch.")
    ap.add_argument("--third-axis", type=str, default="N2", choices=["Ne", "N2"])
    ap.add_argument("--triple", type=str, default="3x3x5", help="Group triple m1xm2xm3 (default: 3x3x5)")
    ap.add_argument("--k-max", type=int, default=200, help="Max k for Möbius/log-zeta twisted constants")
    ap.add_argument("--mertens-n", type=int, default=200, help="Max n for untwisted logMfrak estimate")
    ap.add_argument("--prime-like-n", type=int, default=0, help="If >0, cross-check twisted constants via primitive partial sums up to N")
    ap.add_argument("--prime-like-max-chars", type=int, default=12, help="How many characters to cross-check (unless --prime-like-all)")
    ap.add_argument("--prime-like-all", action="store_true", help="Cross-check all nontrivial characters (may be slow)")
    ap.add_argument("--fold-budget-m", type=int, default=0, help="If >0, compute Fold prime-register budget at this m (q<=17 exact table)")
    ap.add_argument("--eps", type=float, default=0.0, help="If in (0,1), compute anomaly-robust budget patch using Fold r_q table")
    ap.add_argument("--q-max", type=int, default=17, help="Max q for Fold r_q budget patch (<=17 for exact table)")
    ap.add_argument("--no-output", action="store_true", help="Skip writing JSON output")
    ap.add_argument("--output", type=str, default="", help="Output JSON path (default under artifacts/export)")
    args = ap.parse_args()

    third_axis = str(args.third_axis)
    m1, m2, m3 = _parse_triple(args.triple)
    if (m1, m2, m3) != (3, 3, 5):
        # The fingerprint extraction below is currently specialized to (3,3,5).
        raise SystemExit("This Bridge-Kit script currently supports --triple 3x3x5 only (fingerprints hard-coded).")

    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()

    # Untwisted finite-part constant estimate: logMfrak and mathsf_M = gamma + logMfrak.
    mertens_n = int(args.mertens_n)
    if mertens_n < 10:
        raise SystemExit("--mertens-n too small; use >= 10 for a stable estimate.")
    M_untwisted = build_weighted_matrix_numeric(1.0 + 0.0j, 1.0 + 0.0j, 1.0 + 0.0j, states, kernel_map, third_axis=third_axis)
    p_one = _pvals_from_traces(_traces_from_matrix(M_untwisted, max_n=mertens_n))
    log_mathfrak_M_est = 0.0
    for n, pn in enumerate(p_one, start=1):
        log_mathfrak_M_est += (pn.real / (LAMBDA_UNTWISTED**n)) - 1.0 / float(n)
    mathsf_M_est = float(log_mathfrak_M_est + GAMMA_EULER)

    # Twisted constants C(j) via convergent Möbius/log-zeta identity at z=1/lambda.
    k_max = int(args.k_max)
    if k_max < 10:
        raise SystemExit("--k-max too small; use >= 10 for stable twisted constants.")

    omega1 = np.exp(2j * math.pi / 3)
    omega2 = np.exp(2j * math.pi / 3)
    omega3 = np.exp(2j * math.pi / 5)
    prog = _NullProgress()

    twist_C: Dict[str, Dict[str, float]] = {}
    rho_map: Dict[str, float] = {}
    for j1 in range(3):
        q = omega1**j1
        for j2 in range(3):
            r = omega2**j2
            for j3 in range(5):
                if j1 == 0 and j2 == 0 and j3 == 0:
                    continue
                u = omega3**j3
                key = f"{j1},{j2},{j3}"
                C = _twist_constant_via_mobius_logzeta(
                    q=q,
                    r=r,
                    u=u,
                    z=Z_STAR,
                    k_max=k_max,
                    prog=prog,
                    states=states,
                    kernel_map=kernel_map,
                    label=f"bridge-kit j={key}",
                    third_axis=third_axis,
                )
                twist_C[key] = {"re": float(C.real), "im": float(C.imag)}
                rho_map[key] = float(
                    spectral_radius(build_weighted_matrix_numeric(q, r, u, states, kernel_map, third_axis=third_axis))
                )

    # Class constants tensor C_{a,b,c} via character inversion (real part).
    denom = float(3 * 3 * 5)
    class_C: Dict[str, float] = {}
    for a in range(3):
        for b in range(3):
            for c in range(5):
                acc = mathsf_M_est / denom
                for j1 in range(3):
                    q = omega1**j1
                    for j2 in range(3):
                        r = omega2**j2
                        for j3 in range(5):
                            if j1 == 0 and j2 == 0 and j3 == 0:
                                continue
                            u = omega3**j3
                            key = f"{j1},{j2},{j3}"
                            phase = (q ** (-a)) * (r ** (-b)) * (u ** (-c))
                            acc += (phase * complex(twist_C[key]["re"], twist_C[key]["im"])) / denom
                class_C[f"{a},{b},{c}"] = float(acc.real)

    # Anomaly signature (character basis) + l_inf size A_infty.
    anom, A_inf = _anom_signature(twist_C=twist_C, log_mathfrak_M=float(log_mathfrak_M_est))

    # Fingerprints (specialized to 3x3x5)
    fp, fp_extra = _fingerprints_335_n2(class_C=class_C, rho_map=rho_map, lam=LAMBDA_UNTWISTED)

    # Optional: rational tail candidates on c-axis means for 335/N2.
    # (These are the "tail means" that were observed near -1/28,-1/17,-1/14 in the manuscript.)
    c_means = list(fp_extra["c_means"])
    rational_tail = {
        "c=2": {"mean": float(c_means[2]), "candidate": "-1/28", "candidate_value": -1.0 / 28.0, "abs_err": abs(float(c_means[2]) + 1.0 / 28.0)},
        "c=3": {"mean": float(c_means[3]), "candidate": "-1/17", "candidate_value": -1.0 / 17.0, "abs_err": abs(float(c_means[3]) + 1.0 / 17.0)},
        "c=4": {"mean": float(c_means[4]), "candidate": "-1/14", "candidate_value": -1.0 / 14.0, "abs_err": abs(float(c_means[4]) + 1.0 / 14.0)},
    }

    # Optional: prime-like cross-check for a subset of characters.
    prime_like_check: dict | None = None
    Np = int(args.prime_like_n)
    if Np > 0:
        keys = sorted(twist_C.keys())
        if not args.prime_like_all:
            keys = keys[: max(1, int(args.prime_like_max_chars))]
        rows: Dict[str, Dict[str, float]] = {}
        max_abs = 0.0
        for key in keys:
            j1, j2, j3 = (int(x) for x in key.split(","))
            q = omega1**j1
            r = omega2**j2
            u = omega3**j3
            est = _twist_constant_via_primitive_partial_sum(
                q=q,
                r=r,
                u=u,
                states=states,
                kernel_map=kernel_map,
                third_axis=third_axis,
                N=Np,
                z=Z_STAR,
            )
            ref = complex(twist_C[key]["re"], twist_C[key]["im"])
            err = abs(est - ref)
            max_abs = max(float(max_abs), float(err))
            rows[key] = {
                "est_re": float(est.real),
                "est_im": float(est.imag),
                "ref_re": float(ref.real),
                "ref_im": float(ref.imag),
                "abs_err": float(err),
            }
        prime_like_check = {
            "method": "trace->primitive->partial_sum",
            "N": int(Np),
            "checked": keys,
            "max_abs_err": float(max_abs),
            "rows": rows,
        }

    # Optional: anomaly-robust prime-register budget patch (Fold table).
    budget_patch: dict | None = None
    fold_m = int(args.fold_budget_m)
    eps = float(args.eps)
    if fold_m > 0 and (0.0 < eps < 1.0):
        q_max = int(args.q_max)
        rq_by_q = _rq_table_fold_exact(q_max=q_max)
        cert = gamma_cert_from_rq(m=fold_m, eps=eps, rq_by_q=rq_by_q, out_alphabet_size=2)
        logB = logB_from_gamma(m=fold_m, gamma=cert.gamma)
        B = B_from_logB(logB)
        # Baseline: require P > 2B. Patched: P > 2 * exp(A_inf) * B.
        log_target_base = math.log(2.0) + float(logB)
        log_target_patched = float(log_target_base) + float(A_inf)
        primes_base, logP_base = prime_list_for_log_target(log_target_base)
        primes_patched, logP_patched = prime_list_for_log_target(log_target_patched)
        budget_patch = {
            "fold_m": int(fold_m),
            "eps": float(eps),
            "q_max": int(q_max),
            "gamma_cert": {
                "gamma": float(cert.gamma),
                "q_star": int(cert.q_star),
            },
            "logB": float(logB),
            "B": None if B is None else float(B),
            "A_infty": float(A_inf),
            "log_target_base": float(log_target_base),
            "log_target_patched": float(log_target_patched),
            "primes_base": primes_base,
            "logP_base": float(logP_base),
            "primes_patched": primes_patched,
            "logP_patched": float(logP_patched),
        }

    payload: Dict[str, object] = {
        "kernel": "real_input_40",
        "third_axis": third_axis,
        "group_triple": [int(m1), int(m2), int(m3)],
        "lambda": float(LAMBDA_UNTWISTED),
        "z_star": float(Z_STAR),
        "params": {
            "k_max": int(k_max),
            "mertens_n": int(mertens_n),
            "prime_like_n": int(Np),
        },
        "finite_part": {
            "log_mathfrak_M_est": float(log_mathfrak_M_est),
            "mathsf_M_est": float(mathsf_M_est),
            "gamma_euler": float(GAMMA_EULER),
        },
        "twist_constants_C": twist_C,
        "anom_character_basis": {
            "anom": anom,
            "A_infty": float(A_inf),
            "reference": "Anom(j)=C(j)-log_mathfrak_M (j != 0).",
        },
        "class_constants_tensor_C": class_C,
        "fingerprints_335": {
            "rho_max_ratio": float(fp.rho_max_ratio),
            "delta_spec": float(fp.delta_spec),
            "E1": float(fp.E1),
            "eta_tail": float(fp.eta_tail),
            "svd_raw_energy_cum3": float(fp.svd_raw_energy_cum3),
            "svd_centered_energy_cum3": float(fp.svd_centered_energy_cum3),
            "extra": fp_extra,
            "rational_tail_candidates": rational_tail,
        },
        "prime_like_crosscheck": prime_like_check,
        "prime_register_budget_patch": budget_patch,
    }

    if not args.no_output:
        out = (
            Path(args.output)
            if str(args.output).strip()
            else export_dir()
            / f"bridge_kit_real_input_40_arity_{m1}{m2}{m3}_{third_axis}.json"
        )
        _write_json(out, payload)
        print(f"[bridge-kit] wrote {out}", flush=True)

        out_tex = generated_dir() / f"eq_bridge_kit_real_input_40_arity_{m1}{m2}{m3}_{third_axis}.tex"
        _write_bridgekit_fingerprint_tex(
            out_path=out_tex,
            third_axis=third_axis,
            A_inf=float(A_inf),
            delta_spec=float(fp.delta_spec),
            E1=float(fp.E1),
            eta_tail=float(fp.eta_tail),
            eta3_raw=float(fp.svd_raw_energy_cum3),
            eta3_centered=float(fp.svd_centered_energy_cum3),
        )
        print(f"[bridge-kit] wrote {out_tex}", flush=True)

    # Small console summary (kept short).
    print(
        "[bridge-kit] "
        f"logMfrak~{_fmt(log_mathfrak_M_est)} mathsf_M~{_fmt(mathsf_M_est)} "
        f"A_inf~{_fmt(A_inf)} delta_spec~{_fmt(fp.delta_spec)} E1~{_fmt(fp.E1)} eta_tail~{_fmt(fp.eta_tail)}",
        flush=True,
    )


if __name__ == "__main__":
    main()

