#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Event-time dilation for the real-input 40-state kernel.

We combine two already-audited readouts at the unweighted (theta=0) Parry equilibrium:

1) Correlation time (in step units):
   tau_corr := 1/(-log r), where r = Lambda/lambda1 is the subleading spectral radius ratio
   on the chi-slice time-correlation dataset.

2) Event clock rate from the output-bit potential:
   mu_e := E[e] = P_e'(0), where P_e(theta)=log lambda(exp(theta)) for the output-bit
   observable e in {0,1}.

Under the typical relation T_n := sum_{t< n} e_t ~= mu_e * n, we report the converted
correlation time in event-time units:
   tau_event := mu_e * tau_corr,
and likewise the half-life t_{1/2,event} := mu_e * t_{1/2,step}.

Inputs:
- artifacts/export/real_input_40_time_correlation.json
- artifacts/export/real_input_40_output_potential_cumulants_closed.json

Outputs:
- artifacts/export/real_input_40_event_time_dilation.json
- sections/generated/tab_real_input_40_event_time_dilation.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict

from common_paths import export_dir, generated_dir, paper_root


@dataclass(frozen=True)
class EventTimeDilation:
    r_corr: float
    gap_corr: float
    tau_corr_step: float
    half_step: float
    mu_event: float
    tau_corr_event: float
    half_event: float


def _load_json(rel: str) -> Dict[str, Any]:
    return json.loads((paper_root() / rel).read_text(encoding="utf-8"))


def _gap_tau_half(r: float) -> tuple[float, float, float]:
    r = float(r)
    if not (0.0 < r < 1.0):
        return (float("inf"), float("inf"), float("inf"))
    gap = -math.log(r)
    if gap <= 0.0:
        return (float("inf"), float("inf"), float("inf"))
    tau = 1.0 / gap
    half = math.log(2.0) / gap
    return (gap, tau, half)


def _extract_r_at_t0(payload: Dict[str, Any]) -> float:
    # Prefer the explicit "corr.r" if present; otherwise take the nearest grid entry at t=0.
    corr = payload.get("corr")
    if isinstance(corr, dict):
        try:
            r0 = float(corr.get("r", float("nan")))
            if math.isfinite(r0) and r0 > 0.0:
                return r0
        except Exception:
            pass

    grid = payload.get("grid")
    if not isinstance(grid, list) or not grid:
        return float("nan")

    best: Dict[str, Any] | None = None
    best_d = float("inf")
    for g in grid:
        if not isinstance(g, dict):
            continue
        try:
            t = float(g.get("t", float("nan")))
            r = float(g.get("r", float("nan")))
        except Exception:
            continue
        if not (math.isfinite(t) and math.isfinite(r) and r > 0.0):
            continue
        d = abs(t - 0.0)
        if d < best_d:
            best_d = d
            best = g
    if best is None:
        return float("nan")
    return float(best.get("r", float("nan")))


def _extract_mu_event(cum: Dict[str, Any]) -> float:
    # Prefer numeric float string.
    for k in ("P1_float", "P1"):
        v = cum.get(k)
        if isinstance(v, (int, float)):
            return float(v)
        if isinstance(v, str):
            try:
                return float(v)
            except Exception:
                continue
    return float("nan")


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _write_tex(path: Path, res: EventTimeDilation) -> None:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_event_time_dilation.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{Event-time dilation at the unweighted (t=0) Parry equilibrium for the real-input 40-state kernel. "
        "We convert the step-time correlation scale $\\tau_{\\mathrm{corr}}$ to event-time units using the output-bit rate "
        "$\\mu_e=P_e'(0)$ from the closed-form output potential curve.}"
    )
    lines.append("\\label{tab:real-input-40-event-time-dilation}")
    lines.append("\\begin{tabular}{l r}")
    lines.append("\\toprule")
    lines.append("quantity & value\\\\")
    lines.append("\\midrule")
    lines.append("$r_{\\mathrm{corr}}(0)$ & " + _fmt(res.r_corr) + "\\\\")
    lines.append("$-\\log r_{\\mathrm{corr}}(0)$ & " + _fmt(res.gap_corr) + "\\\\")
    lines.append(
        "$\\tau_{\\mathrm{corr}}$ (step) & " + _fmt(res.tau_corr_step) + "\\\\"
    )
    lines.append("$t_{1/2}$ (step) & " + _fmt(res.half_step) + "\\\\")
    lines.append("\\midrule")
    lines.append("$\\mu_e=P_e'(0)$ & " + _fmt(res.mu_event) + "\\\\")
    lines.append(
        "$\\tau_{\\mathrm{corr}}$ (event) & " + _fmt(res.tau_corr_event) + "\\\\"
    )
    lines.append("$t_{1/2}$ (event) & " + _fmt(res.half_event) + "\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Event-time dilation (real-input 40-state)."
    )
    parser.add_argument(
        "--time-corr-json",
        type=str,
        default="artifacts/export/real_input_40_time_correlation.json",
    )
    parser.add_argument(
        "--cumulants-json",
        type=str,
        default="artifacts/export/real_input_40_output_potential_cumulants_closed.json",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_event_time_dilation.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_real_input_40_event_time_dilation.tex"),
    )
    args = parser.parse_args()

    tc = _load_json(str(args.time_corr_json))
    cum = _load_json(str(args.cumulants_json))

    r = _extract_r_at_t0(tc)
    gap, tau_step, half_step = _gap_tau_half(r)

    mu = _extract_mu_event(cum)
    tau_event = (
        (mu * tau_step)
        if (math.isfinite(mu) and math.isfinite(tau_step))
        else float("inf")
    )
    half_event = (
        (mu * half_step)
        if (math.isfinite(mu) and math.isfinite(half_step))
        else float("inf")
    )

    res = EventTimeDilation(
        r_corr=float(r),
        gap_corr=float(gap),
        tau_corr_step=float(tau_step),
        half_step=float(half_step),
        mu_event=float(mu),
        tau_corr_event=float(tau_event),
        half_event=float(half_event),
    )

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(
        json.dumps(asdict(res), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"[event-time] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, res)
    print(f"[event-time] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()
