#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Derived bias audits for the (2,2,2) Dirichlet–Mertens constants tensor.

We read the exported JSON produced by exp_sync_kernel_real_input_40_arity_3d.py and
compute low-dimensional marginal biases:
  - chi mod 2 marginal difference Delta_chi
  - N_e mod 2 marginal difference Delta_Ne

Outputs:
  - sections/generated/eq_real_input_40_arity_dirichlet_mertens_222_bias.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Tuple

from common_paths import export_dir, generated_dir


def main() -> None:
    jin = export_dir() / "sync_kernel_real_input_40_arity_3d.json"
    data = json.loads(jin.read_text(encoding="utf-8"))
    C: Dict[str, float] = data["triple_class_C"]["2x2x2"]

    def get(a: int, b: int, c: int) -> float:
        return float(C[f"{a},{b},{c}"])

    # Margins.
    sum_a = {a: 0.0 for a in (0, 1)}
    sum_c = {c: 0.0 for c in (0, 1)}
    for a in (0, 1):
        for b in (0, 1):
            for c in (0, 1):
                val = get(a, b, c)
                sum_a[a] += val
                sum_c[c] += val

    delta_chi = sum_a[1] - sum_a[0]
    delta_ne = sum_c[1] - sum_c[0]

    out = generated_dir() / "eq_real_input_40_arity_dirichlet_mertens_222_bias.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by scripts/exp_real_input_40_mertens_tensor_bias_222.py",
        "\\[",
        "\\begin{aligned}",
        f"\\sum_{{b,c}}\\bigl(C_{{1bc}}-C_{{0bc}}\\bigr)&\\approx {delta_chi:.12g},\\\\",
        f"\\sum_{{a,b}}\\bigl(C_{{ab1}}-C_{{ab0}}\\bigr)&\\approx {delta_ne:.12g}.",
        "\\end{aligned}",
        "\\]",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[real-input-40-mertens-222-bias] read {jin}", flush=True)
    print(f"[real-input-40-mertens-222-bias] wrote {out}", flush=True)
    print("[real-input-40-mertens-222-bias] done", flush=True)


if __name__ == "__main__":
    main()

