#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Centralizer size and conjugacy class size of the geometric involution element
inside the discrete fiber-permutation (gauge) group for window-6.

All code is English-only by repository convention.

Inputs:
  - artifacts/export/foldbin6_geo_orbit_charge.json  (from exp_foldbin6_geo_orbit_charge.py)

Outputs:
  - artifacts/export/foldbin6_geo_gauge_centralizer.json
  - sections/generated/eq_foldbin6_geo_gauge_centralizer.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Tuple

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class OrbitCharge:
    fixed_points: int
    two_cycles: int

    @property
    def fiber_size(self) -> int:
        return self.fixed_points + 2 * self.two_cycles

    def centralizer_size_in_Sd(self) -> int:
        # Cycle type is 1^{f} 2^{p}. Centralizer size is f! * 2^p * p!
        f = self.fixed_points
        p = self.two_cycles
        return math.factorial(f) * (2**p) * math.factorial(p)


def _parse_q_key(key: str) -> Tuple[int, int]:
    # key like "(2,1)"
    s = key.strip()
    if not (s.startswith("(") and s.endswith(")")):
        raise ValueError(f"bad q key: {key!r}")
    a, b = s[1:-1].split(",")
    return int(a), int(b)


def _write_eq_tex(*, out_path: Path, gauge_order_factored: Dict[int, int], centralizer: int, conj_class: int) -> None:
    # Render |G| as a compact product of factorial powers: prod (d!)^{count_d}
    fac_terms = " ".join([f"({d}!)^{{{cnt}}}" for d, cnt in sorted(gauge_order_factored.items())])
    lines = [
        "% AUTO-GENERATED by scripts/exp_foldbin6_geo_gauge_centralizer.py",
        "\\begin{equation}\\label{eq:foldbin6_geo_gauge_centralizer}",
        "\\begin{aligned}",
        f"|G_6^{{\\mathrm{{bin}}}}|&={fac_terms},\\\\",
        f"|C_{{G_6^{{\\mathrm{{bin}}}}}}(g)|&={centralizer:,},\\\\",
        f"|G_6^{{\\mathrm{{bin}}}}:C_{{G_6^{{\\mathrm{{bin}}}}}}(g)|&={conj_class:,}.",
        "\\end{aligned}",
        "\\end{equation}",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute centralizer size for sigma_geo element in G_6^{bin}.")
    ap.add_argument(
        "--orbit-charge-json",
        type=str,
        default=str(export_dir() / "foldbin6_geo_orbit_charge.json"),
        help="Path to orbit charge JSON (from exp_foldbin6_geo_orbit_charge.py).",
    )
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "foldbin6_geo_gauge_centralizer.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_foldbin6_geo_gauge_centralizer.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    args = ap.parse_args()

    payload = json.loads(Path(args.orbit_charge_json).read_text(encoding="utf-8"))
    q_hist_raw: Dict[str, int] = payload["q_histogram"]

    q_hist: Dict[OrbitCharge, int] = {}
    for k, cnt in q_hist_raw.items():
        f, p = _parse_q_key(k)
        q_hist[OrbitCharge(fixed_points=f, two_cycles=p)] = int(cnt)

    # Discrete gauge group order: product over fibers of (d_x)!.
    # We compute it in factored form by fiber size histogram.
    gauge_order_factored: Dict[int, int] = {}
    for q, cnt in q_hist.items():
        d = q.fiber_size
        gauge_order_factored[d] = gauge_order_factored.get(d, 0) + cnt

    # Centralizer in the product group: product of centralizers per fiber.
    centralizer = 1
    centralizer_terms: Dict[str, int] = {}
    for q, cnt in sorted(q_hist.items(), key=lambda t: (t[0].fiber_size, t[0].fixed_points, t[0].two_cycles)):
        c = q.centralizer_size_in_Sd()
        centralizer *= c**cnt
        centralizer_terms[f"q=({q.fixed_points},{q.two_cycles})"] = c

    gauge_order = 1
    for d, cnt in gauge_order_factored.items():
        gauge_order *= (math.factorial(d) ** cnt)
    conj_class = gauge_order // centralizer

    if gauge_order % centralizer != 0:
        raise RuntimeError("centralizer does not divide gauge group order")

    out_payload = {
        "m": 6,
        "gauge_group": {
            "factored_order": {str(d): int(cnt) for d, cnt in sorted(gauge_order_factored.items())},
            "order": int(gauge_order),
        },
        "element": {"name": "sigma_geo fiberwise permutation g", "cycle_type": "1^f 2^p on each fiber"},
        "orbit_charge_histogram": {f"({q.fixed_points},{q.two_cycles})": int(cnt) for q, cnt in sorted(q_hist.items(), key=lambda t: (t[0].fiber_size, t[0].fixed_points, t[0].two_cycles))},
        "centralizer": {
            "terms_per_orbit_charge": centralizer_terms,
            "order": int(centralizer),
        },
        "conjugacy_class": {"size": int(conj_class)},
    }

    json_out = Path(args.json_out)
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(out_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    _write_eq_tex(
        out_path=Path(args.tex_eq_out),
        gauge_order_factored=gauge_order_factored,
        centralizer=centralizer,
        conj_class=conj_class,
    )

    print(f"[foldbin6_geo_gauge_centralizer] wrote {json_out}", flush=True)
    print(f"[foldbin6_geo_gauge_centralizer] wrote {args.tex_eq_out}", flush=True)


if __name__ == "__main__":
    main()

