#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: the orthogonal part generated by commutators [L_i, L_j] on window-6.

We construct the coordinate pushforward operators L_i exactly as in exp_window6_lie_envelope.py,
then compute the Lie subalgebra
  k_6 := Lie⟨ [L_i, L_j] : 1 ≤ i < j ≤ 6 ⟩
over a large prime field F_p and output its dimension certificate.

Outputs:
  - artifacts/export/window6_lie_envelope_orthogonal_part.json
  - sections/generated/eq_window6_lie_envelope_orthogonal_part_dim.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np

from common_paths import export_dir, generated_dir

# Reuse the canonical window-6 constructions and modular Lie closure.
from exp_window6_lie_envelope import (  # noqa: E402
    Heartbeat,
    _as_np_int64,
    _foldbin6_label,
    _lie_closure_mod,
    _mod_comm,
)


def main() -> None:
    ap = argparse.ArgumentParser(description="Audit k_6 := Lie<[L_i,L_j]> for window-6.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_lie_envelope_orthogonal_part.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_window6_lie_envelope_orthogonal_part_dim.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    ap.add_argument(
        "--prime",
        type=int,
        default=1_000_003,
        help="Single prime modulus for the audit (default: 1000003).",
    )
    args = ap.parse_args()

    hb = Heartbeat(interval_s=20.0)
    print("[info] starting: window6 orthogonal-part audit", file=sys.stderr, flush=True)

    labels = [_foldbin6_label(n) for n in range(64)]
    words = sorted(set(labels))
    if len(words) != 21:
        raise RuntimeError(f"Unexpected |X_6| from Fold^{{bin}}_6: {len(words)}")
    idx = {w: i for i, w in enumerate(words)}

    fiber_size: Dict[str, int] = {w: 0 for w in words}
    for w in labels:
        fiber_size[w] += 1

    # Coordinate directions i=1..6 correspond to flipping omega_i, i.e. XOR with 2^{6-i}.
    bits = [1 << (6 - i) for i in range(1, 7)]
    L_int: List[List[List[int]]] = []
    for bit in bits:
        M = [[0 for _ in range(21)] for _ in range(21)]
        for n in range(64):
            nn = n ^ bit
            a = idx[labels[n]]
            b = idx[labels[nn]]
            M[a][b] += 1
        # Row sums should equal fiber sizes (one outgoing i-edge per microstate).
        for w in words:
            r = idx[w]
            if int(sum(M[r][c] for c in range(21))) != int(fiber_size[w]):
                raise RuntimeError("Row-sum check failed for some L_i.")
        L_int.append(M)

    hb.beat("constructed coordinate pushforward operators L_i")

    p = int(args.prime)
    hb.beat(f"mod-audit: p={p}")
    L = [_as_np_int64(M) % p for M in L_int]

    # Generators for k_6: all commutators [L_i, L_j].
    comm_gens: List[np.ndarray] = []
    for i in range(6):
        for j in range(i + 1, 6):
            C = _mod_comm(L[i], L[j], p)
            comm_gens.append(C)

    # Basic sanity: commutators should be skew-symmetric in odd characteristic.
    for t, C in enumerate(comm_gens):
        if not np.array_equal((C.T + C) % p, np.zeros_like(C)):
            raise RuntimeError(f"Generator {t} is not skew-symmetric mod p={p}.")

    hb.beat("constructed commutator generators")

    basis_k = _lie_closure_mod(comm_gens, p=p, hb=hb)
    dim_k = int(len(basis_k))

    print(f"[info] computed k_6 dim_k={dim_k} (mod p={p})", file=sys.stderr, flush=True)

    payload: Dict[str, object] = {
        "m": 6,
        "mod_prime": int(p),
        "k6_commutator_subalgebra": {
            "dim_k": dim_k,
            "num_generators": int(len(comm_gens)),
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[info] wrote JSON: {json_out}", file=sys.stderr, flush=True)

    tex_out = Path(str(args.tex_eq_out))
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_window6_lie_envelope_orthogonal_part.py")
    lines.append("\\begin{equation}\\label{eq:window6_lie_envelope_orthogonal_part_dim}")
    lines.append(f"\\dim\\mathfrak{{k}}_6={dim_k}.")
    lines.append("\\end{equation}")
    lines.append("")
    tex_out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[info] wrote TeX: {tex_out}", file=sys.stderr, flush=True)

    print(f"File: {json_out.relative_to(export_dir().parent.parent)}")
    print(f"File: {tex_out.relative_to(generated_dir().parent.parent)}")


if __name__ == "__main__":
    main()

