#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Real-axis branchpoint and unit-circle touchpoints for the 4th-collision kernel family A_4(t).

We work with the one-parameter family (t replaces the single multi-edge weight "7"):

  A_4(t) =
    [[0,1,0,0,0],
     [0,0,t,0,1],
     [0,1,2,0,0],
     [1,0,1,0,0],
     [0,0,0,1,0]].

Let the characteristic polynomial be
  p_t(λ) = det(λ I - A_4(t)) = λ^5 - 2λ^4 - tλ^3 - 2λ + 2.

Then:
  - Disc_λ(p_t) = -16 Q(t), where Q(t) is an explicit quintic with exactly one real root t_ep.
    Hence t=t_ep is the unique real spectral-branchpoint (double eigenvalue) on the parameter axis.
  - Unit-circle eigenvalues (|λ|=1) occur iff t ∈ {-11/4, -1, 1}, with fully explicit λ.
  - For the even-spectrum quintic E_t(u)=det(I-uA_4(t)^2), the u-discriminant is
      Disc_u(E_t) = -256 (t-1)^2 (t+1)^2 Q(t),
    so the even-spectrum has double-root degeneracies at t=±1 and at t=t_ep.
    The common double root is given uniformly by a rational function u_*(t), obtained from the
    degree-1 subresultant of (E_t, ∂_u E_t).

Outputs:
  - artifacts/export/collision_kernel_A4_unit_circle_branchpoints.json
  - sections/generated/eq_collision_kernel_A4_unit_circle_branchpoints.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import sympy as sp
from sympy.polys.polytools import subresultants

from common_paths import export_dir, generated_dir


def _A4(t: sp.Symbol) -> sp.Matrix:
    return sp.Matrix(
        [
            [0, 1, 0, 0, 0],
            [0, 0, t, 0, 1],
            [0, 1, 2, 0, 0],
            [1, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
        ]
    )


@dataclass(frozen=True)
class Payload:
    # characteristic polynomial/discriminant factor
    p_t_lambda: str
    disc_lambda_p: str
    disc_lambda_p_factor: str
    Q_t: str
    Q_real_root_count: int
    t_ep_approx: str
    # sample real-root counts for p_t
    p_t_real_roots_count_t0: int
    p_t_real_roots_count_t1: int
    t0: str
    t1: str
    # unit-circle touchpoints for p_t
    unit_circle_t_values: List[str]
    unit_circle_lambdas: Dict[str, List[str]]
    unit_circle_u_values: Dict[str, List[str]]
    # even-spectrum double root data
    E_t_u: str
    disc_u_E_factor: str
    u_star: str
    u_star_num: str
    u_star_den: str
    u_star_at_minus1: str
    u_star_at_plus1: str
    u_ep_approx: str
    lambda_ep_approx: str
    # sanity checks
    checks_ok: bool


def _as_decimal(z: sp.Expr, *, digits: int = 16) -> str:
    # A stable decimal for the paper: fixed digits, no scientific notation unless necessary.
    # sympy.N respects the current precision of the expression; enforce high precision first.
    s = sp.N(z, 80)
    # Convert through Python's string formatting on mpf/mpc, then trim.
    # For reals: keep 'digits' after decimal when possible.
    if isinstance(s, sp.core.numbers.Float):
        return f"{float(s):.{digits}f}"
    return str(s)


def _write_tex(path: Path, *, t_ep: sp.Expr, u_ep: sp.Expr, lambda_ep: sp.Expr) -> None:
    # Use stable, human-auditable TeX certificates (avoid sympy's term reordering).
    Q_tex = r"27t^5+35t^4+434t^3+4394t^2+10832t+7403"
    u_star_num_tex = (
        r"27t^{7}+62t^{6}+226t^{5}+1252t^{4}+3080t^{3}+5790t^{2}+7960t+4728"
    )
    u_star_den_tex = (
        r"27t^{8}+8t^{7}+264t^{6}+3056t^{5}+4160t^{4}-8064t^{3}-17728t^{2}-6832t+1984"
    )

    t_ep_s = _as_decimal(t_ep, digits=16)
    u_ep_s = _as_decimal(u_ep, digits=16)
    lam_ep_s = _as_decimal(lambda_ep, digits=16)

    lines = [
        "% Auto-generated by scripts/exp_collision_kernel_A4_unit_circle_branchpoints.py",
        r"\begin{equation}\label{eq:collision_kernel_A4_unit_circle_branchpoints}",
        r"\begin{aligned}",
        rf"Q(t)&:={Q_tex},\\",
        rf"t_{{\mathrm{{ep}}}}&\approx {t_ep_s},\\",
        r"u_\ast(t)",
        rf"&:=\frac{{{u_star_num_tex}}}{{{u_star_den_tex}}},\\",
        rf"u_\ast(-1)&=1,\qquad u_\ast(1)=-1,\qquad u_\ast(t_{{\mathrm{{ep}}}})=:u_{{\mathrm{{ep}}}}\approx {u_ep_s},\\",
        rf"\lambda_{{\mathrm{{ep}}}}&:=u_{{\mathrm{{ep}}}}^{{-1/2}}\approx {lam_ep_s}.",
        r"\end{aligned}",
        r"\end{equation}",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit A_4(t): real-axis exceptional point, unit-circle touchpoints, and even-spectrum double roots.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4_unit_circle_branchpoints.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_unit_circle_branchpoints.tex"),
        help="Output TeX path.",
    )
    args = parser.parse_args()

    t = sp.Symbol("t")
    lam = sp.Symbol("lam")
    u = sp.Symbol("u")

    # Characteristic polynomial p_t(λ).
    p = sp.expand(lam**5 - 2 * lam**4 - t * lam**3 - 2 * lam + 2)
    disc_lam = sp.discriminant(sp.Poly(p, lam), lam)
    disc_lam_fact = sp.factor(disc_lam)
    Q = sp.expand(-disc_lam_fact / 16)
    Q_poly = sp.Poly(Q, t)

    # Unique real root t_ep.
    Q_real_roots = Q_poly.real_roots()
    Q_real_root_count = len(Q_real_roots)
    if Q_real_root_count != 1:
        raise RuntimeError(f"Expected Q(t) to have exactly 1 real root, got {Q_real_root_count}.")
    t_ep = sp.N(Q_real_roots[0], 80)

    # Sample real-root counts: one point on each side of t_ep.
    t0 = sp.Integer(0)
    t1 = sp.Integer(-2)
    p0 = sp.Poly(p.subs(t, t0), lam)
    p1 = sp.Poly(p.subs(t, t1), lam)
    c0 = int(p0.count_roots(sp.S.NegativeInfinity, sp.S.Infinity))
    c1 = int(p1.count_roots(sp.S.NegativeInfinity, sp.S.Infinity))

    # Unit-circle touchpoints for p_t: eliminate t between p_t(λ)=0 and p_t(1/λ)=0.
    # For |λ|=1, conjugation gives p_t(1/λ)=0, hence this captures all unit-circle roots.
    eq1 = sp.expand(t * lam**3 - (lam**5 - 2 * lam**4 - 2 * lam + 2))
    eq2 = sp.expand(t * lam**2 - (1 - 2 * lam - 2 * lam**4 + 2 * lam**5))
    F = sp.factor(sp.resultant(eq1, eq2, t) / lam**2)
    F_expected = sp.factor(-(lam - 1) * (lam + 1) * (lam**2 + 1) * (2 * lam**2 - 3 * lam + 2))
    check_F_ok = (sp.factor(F - F_expected) == 0)

    # Map each unit-circle root type to its parameter t and even-spectrum u=1/λ^2.
    t_expr = sp.simplify((lam**5 - 2 * lam**4 - 2 * lam + 2) / lam**3)
    lambda_by_t: Dict[str, List[sp.Expr]] = {
        "-1": [sp.Integer(1), sp.Integer(-1)],
        "1": [sp.I, -sp.I],
        "-11/4": [sp.Rational(3, 4) + sp.I * sp.sqrt(7) / 4, sp.Rational(3, 4) - sp.I * sp.sqrt(7) / 4],
    }
    unit_circle_t_values = ["-11/4", "-1", "1"]

    # Verify the mapping and prepare JSON-friendly strings.
    unit_circle_lambdas: Dict[str, List[str]] = {}
    unit_circle_us: Dict[str, List[str]] = {}
    check_unit_circle_ok = True
    for t_key, lams in lambda_by_t.items():
        unit_circle_lambdas[t_key] = []
        unit_circle_us[t_key] = []
        for lv in lams:
            tv = sp.simplify(t_expr.subs(lam, lv))
            check_unit_circle_ok = check_unit_circle_ok and (sp.simplify(tv - sp.Rational(t_key)) == 0)
            unit_circle_lambdas[t_key].append(str(sp.simplify(lv)))
            uv = sp.simplify(1 / (lv**2))
            uv = sp.simplify(sp.expand_complex(uv))
            unit_circle_us[t_key].append(str(uv))

    # Even-spectrum quintic E_t(u) and its u-discriminant factorization.
    E = sp.expand(1 - (2 * t + 4) * u + (t**2 - 4) * u**2 + (4 * t + 8) * u**3 + 4 * u**4 - 4 * u**5)
    disc_u = sp.discriminant(sp.Poly(E, u), u)
    disc_u_fact = sp.factor(disc_u)
    disc_u_expected = sp.factor(-256 * (t - 1) ** 2 * (t + 1) ** 2 * Q)
    check_disc_u_ok = (sp.factor(disc_u_fact - disc_u_expected) == 0)

    # Degree-1 subresultant gives the common root u_*(t) when Disc_u(E_t)=0.
    E_poly = sp.Poly(E, u)
    Ep_poly = sp.Poly(sp.diff(E, u), u)
    subs = subresultants(E_poly, Ep_poly)
    S1 = subs[4]  # degree-1 subresultant in u
    coeff_u, const = S1.all_coeffs()
    u_star = sp.simplify(-const / coeff_u)
    u_star_num, u_star_den = sp.together(u_star).as_numer_denom()

    # Special values.
    u_star_minus1 = sp.simplify(u_star.subs(t, -1))
    u_star_plus1 = sp.simplify(u_star.subs(t, 1))
    u_ep = sp.N(u_star.subs(t, t_ep), 80)
    lambda_ep = sp.N(u_ep ** (-sp.Rational(1, 2)), 80)

    # Sanity: substituting u_*(t) into E and E' yields numerators divisible by (t-1)^2(t+1)^2 Q(t).
    fac = sp.factor((t - 1) ** 2 * (t + 1) ** 2 * Q)
    E_sub = sp.together(E.subs(u, u_star))
    Ep_sub = sp.together(sp.diff(E, u).subs(u, u_star))
    E_num = sp.factor(E_sub.as_numer_denom()[0])
    Ep_num = sp.factor(Ep_sub.as_numer_denom()[0])
    check_u_star_sat = sp.factor(E_num / fac).is_polynomial(t) and sp.factor(Ep_num / fac).is_polynomial(t)

    checks_ok = bool(
        check_F_ok
        and check_unit_circle_ok
        and check_disc_u_ok
        and (u_star_minus1 == 1)
        and (u_star_plus1 == -1)
        and check_u_star_sat
        and (Q_poly.count_roots(sp.S.NegativeInfinity, sp.S.Infinity) == 1)
        and (c0 in {1, 3, 5})
        and (c1 in {1, 3, 5})
    )

    _write_tex(Path(args.tex_out), t_ep=t_ep, u_ep=u_ep, lambda_ep=lambda_ep)

    payload = Payload(
        p_t_lambda=str(p),
        disc_lambda_p=str(disc_lam),
        disc_lambda_p_factor=str(disc_lam_fact),
        Q_t=str(Q),
        Q_real_root_count=int(Q_real_root_count),
        t_ep_approx=str(sp.N(t_ep, 40)),
        p_t_real_roots_count_t0=int(c0),
        p_t_real_roots_count_t1=int(c1),
        t0=str(t0),
        t1=str(t1),
        unit_circle_t_values=list(unit_circle_t_values),
        unit_circle_lambdas=unit_circle_lambdas,
        unit_circle_u_values=unit_circle_us,
        E_t_u=str(E),
        disc_u_E_factor=str(disc_u_fact),
        u_star=str(u_star),
        u_star_num=str(sp.expand(u_star_num)),
        u_star_den=str(sp.expand(u_star_den)),
        u_star_at_minus1=str(u_star_minus1),
        u_star_at_plus1=str(u_star_plus1),
        u_ep_approx=str(sp.N(u_ep, 40)),
        lambda_ep_approx=str(sp.N(lambda_ep, 40)),
        checks_ok=bool(checks_ok),
    )

    out = Path(args.json_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[A4-unit-circle-branchpoints] wrote {out}", flush=True)
    if not checks_ok:
        raise RuntimeError("Sanity checks failed: expected identities did not match symbolic computations.")


if __name__ == "__main__":
    main()

