#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit endomorphism-ring rigidity for the genus-2 Lee–Yang discriminant ridge Jacobian.

Curve:
  C: w^2 = -y(y-1)P_LY(y),
  P_LY(y) = 256y^3 + 411y^2 + 165y + 32.

For good primes p, the Jacobian J(C) has a degree-4 Weil (Frobenius) polynomial
  P_p(x) = x^4 - a1 x^3 + a2 x^2 - a1 p x + p^2,
recovered from point counts #C(F_p), #C(F_{p^2}).

We compute at p=17 and p=29:
  - P_p(x) in Z[x] and certify irreducibility over Q.
  - The Galois group of P_p(x) (as a transitive subgroup of S4), expecting D4.
  - The quadratic real subfield generated by u_p := pi_p + p/pi_p, whose minpoly is
        u^2 - a1 u + (a2 - 2p) = 0.

Outputs:
  - artifacts/export/fold_zm_discriminant_ridge_jacobian_endomorphism_ring_audit.json
  - sections/generated/eq_fold_zm_discriminant_ridge_jacobian_endomorphism_ring_audit.tex
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

import sympy as sp
from sympy.polys.numberfields.galoisgroups import galois_group

from common_paths import export_dir, generated_dir


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _legendre_symbol(a: int, p: int) -> int:
    """Return (a/p) for odd prime p as -1,0,1."""
    a %= p
    if a == 0:
        return 0
    t = pow(a, (p - 1) // 2, p)
    return -1 if t == p - 1 else int(t)


def _squarefree_part(n: int) -> int:
    """Return the signed squarefree part of a nonzero integer n."""
    if n == 0:
        return 0
    sign = -1 if n < 0 else 1
    n_abs = abs(int(n))
    fac = sp.factorint(n_abs)
    sf = 1
    for q, e in fac.items():
        if e % 2 == 1:
            sf *= int(q)
    return sign * int(sf)


def P_LY_int(y: int) -> int:
    y = int(y)
    return 256 * y**3 + 411 * y**2 + 165 * y + 32


def f_int(y: int) -> int:
    """f(y) = -y(y-1)P_LY(y) over Z."""
    y = int(y)
    return -y * (y - 1) * P_LY_int(y)


class Fp2:
    """Element of F_{p^2}=F_p[alpha]/(alpha^2-d), represented as a + b*alpha."""

    __slots__ = ("a", "b", "p", "d")

    def __init__(self, a: int, b: int, *, p: int, d: int) -> None:
        self.p = int(p)
        self.d = int(d) % self.p
        self.a = int(a) % self.p
        self.b = int(b) % self.p

    def __add__(self, other: "Fp2") -> "Fp2":
        return Fp2(self.a + other.a, self.b + other.b, p=self.p, d=self.d)

    def __sub__(self, other: "Fp2") -> "Fp2":
        return Fp2(self.a - other.a, self.b - other.b, p=self.p, d=self.d)

    def __neg__(self) -> "Fp2":
        return Fp2(-self.a, -self.b, p=self.p, d=self.d)

    def __mul__(self, other: "Fp2") -> "Fp2":
        # (a+bα)(c+dα)=(ac+bd*d0) + (ad+bc)α, α^2=d0
        p = self.p
        d0 = self.d
        a, b = self.a, self.b
        c, d = other.a, other.b
        ac = (a * c) % p
        bd = (b * d) % p
        ad_bc = (a * d + b * c) % p
        return Fp2(ac + bd * d0, ad_bc, p=p, d=d0)

    def __pow__(self, e: int) -> "Fp2":
        e = int(e)
        if e < 0:
            return self.inv().__pow__(-e)
        p, d0 = self.p, self.d
        result = Fp2(1, 0, p=p, d=d0)
        base = self
        k = e
        while k:
            if k & 1:
                result = result * base
            base = base * base
            k >>= 1
        return result

    def inv(self) -> "Fp2":
        # (a+bα)^{-1} = (a-bα)/N, N=a^2 - b^2*d0 in F_p
        p, d0 = self.p, self.d
        a, b = self.a, self.b
        n = (a * a - (b * b % p) * d0) % p
        if n == 0:
            raise ZeroDivisionError("Fp2 inverse of zero-norm element")
        n_inv = pow(n, -1, p)
        return Fp2(a * n_inv, (-b) * n_inv, p=p, d=d0)

    def is_zero(self) -> bool:
        return (self.a % self.p) == 0 and (self.b % self.p) == 0

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Fp2):
            return False
        return self.p == other.p and self.d == other.d and self.a == other.a and self.b == other.b


def _nonsquare_d(p: int) -> int:
    """Return a small d that is a nonsquare mod p (odd prime)."""
    for d in range(2, p):
        if _legendre_symbol(d, p) == -1:
            return int(d)
    raise RuntimeError("failed to find nonsquare")


def _quad_char_fp2(a: Fp2) -> int:
    """Quadratic character on F_{p^2}: returns -1,0,1."""
    if a.is_zero():
        return 0
    q = a.p * a.p
    t = a ** ((q - 1) // 2)
    one = Fp2(1, 0, p=a.p, d=a.d)
    minus_one = Fp2(-1, 0, p=a.p, d=a.d)
    if t == one:
        return 1
    if t == minus_one:
        return -1
    raise RuntimeError(f"unexpected quadratic character value: {t}")


def _eval_f_fp2(y: Fp2) -> Fp2:
    """Evaluate f(y) = -y(y-1)P_LY(y) in F_{p^2}."""
    p, d0 = y.p, y.d
    c0 = Fp2(32, 0, p=p, d=d0)
    c1 = Fp2(165, 0, p=p, d=d0)
    c2 = Fp2(411, 0, p=p, d=d0)
    c3 = Fp2(256, 0, p=p, d=d0)
    P = c0 + c1 * y + c2 * (y**2) + c3 * (y**3)
    return -(y * (y - Fp2(1, 0, p=p, d=d0)) * P)


def count_C_Fp(p: int) -> int:
    """Count #C(F_p) for w^2=f(y), deg f=5 (one point at infinity)."""
    p = int(p)
    total = 1  # point at infinity
    for y in range(p):
        rhs = f_int(y) % p
        ls = _legendre_symbol(rhs, p)
        total += 1 + ls
    return int(total)


def count_C_Fp2(p: int) -> int:
    """Count #C(F_{p^2}) by explicit enumeration in a quadratic extension."""
    p = int(p)
    d0 = _nonsquare_d(p)
    total = 1  # point at infinity (odd degree model)
    for a in range(p):
        for b in range(p):
            y = Fp2(a, b, p=p, d=d0)
            rhs = _eval_f_fp2(y)
            chi = _quad_char_fp2(rhs)
            total += 1 + chi
    return int(total)


@dataclass(frozen=True)
class PrimeRow:
    p: int
    n_fp: int
    n_fp2: int
    a1: int
    a2: int
    Pp_x: str
    Pp_latex: str
    Pp_irreducible_Zx: bool
    gal_order: int
    gal_is_dihedral: bool
    u_minpoly: str
    u_minpoly_latex: str
    u_disc: int
    u_disc_squarefree: int


def main() -> None:
    t0 = time.time()
    print("[fold-zm-ridge-endo] start", flush=True)

    x = sp.Symbol("x")
    u = sp.Symbol("u")

    primes = [17, 29]
    expected_Pp = {
        17: sp.Poly(x**4 - 3 * x**3 + 28 * x**2 - 51 * x + 289, x, domain="ZZ"),
        29: sp.Poly(x**4 + x**3 + 40 * x**2 + 29 * x + 841, x, domain="ZZ"),
    }

    rows: List[PrimeRow] = []
    for p in primes:
        n1 = count_C_Fp(p)
        n2 = count_C_Fp2(p)
        a1 = p + 1 - n1
        s2 = p * p + 1 - n2
        a2 = (a1 * a1 - s2) // 2
        if 2 * a2 != (a1 * a1 - s2):
            raise RuntimeError(f"Non-integral a2 at p={p}")

        Pp = sp.Poly(x**4 - a1 * x**3 + a2 * x**2 - a1 * p * x + (p * p), x, domain="ZZ")
        if sp.factor(Pp.as_expr()) != Pp.as_expr():
            irreducible = False
        else:
            irreducible = True

        if Pp != expected_Pp[p]:
            raise RuntimeError(f"Unexpected P_{p}(x): got {Pp.as_expr()}, expected {expected_Pp[p].as_expr()}")

        G, _is_real = galois_group(Pp)
        gal_order = int(G.order())
        gal_is_dihedral = bool(G.is_dihedral and gal_order == 8)

        u_poly = sp.Poly(u**2 - a1 * u + (a2 - 2 * p), u, domain="ZZ")
        u_disc = int(sp.discriminant(u_poly.as_expr(), u))
        u_disc_sf = int(_squarefree_part(u_disc))

        rows.append(
            PrimeRow(
                p=int(p),
                n_fp=int(n1),
                n_fp2=int(n2),
                a1=int(a1),
                a2=int(a2),
                Pp_x=sp.sstr(Pp.as_expr()),
                Pp_latex=sp.latex(Pp.as_expr()),
                Pp_irreducible_Zx=bool(irreducible),
                gal_order=int(gal_order),
                gal_is_dihedral=bool(gal_is_dihedral),
                u_minpoly=sp.sstr(u_poly.as_expr()),
                u_minpoly_latex=sp.latex(u_poly.as_expr()),
                u_disc=int(u_disc),
                u_disc_squarefree=int(u_disc_sf),
            )
        )

    payload: Dict[str, object] = {
        "curve": "w^2 = -y(y-1)(256y^3+411y^2+165y+32)",
        "primes": primes,
        "rows": [asdict(r) for r in rows],
    }

    out_json = export_dir() / "fold_zm_discriminant_ridge_jacobian_endomorphism_ring_audit.json"
    _write_json(out_json, payload)

    r17 = next(r for r in rows if r.p == 17)
    r29 = next(r for r in rows if r.p == 29)

    # Short TeX snippet: P_p(x), D4 Galois group, and real quadratic subfields.
    tex_lines = [
        "% Auto-generated by scripts/exp_fold_zm_discriminant_ridge_jacobian_endomorphism_ring_audit.py",
        "\\[",
        f"P_{{17}}(x)={r17.Pp_latex},\\qquad P_{{29}}(x)={r29.Pp_latex}.",
        "\\]",
        "\\[",
        "\\mathrm{Gal}(P_{17}/\\QQ)\\cong D_4,\\qquad \\mathrm{Gal}(P_{29}/\\QQ)\\cong D_4\\qquad (|D_4|=8).",
        "\\]",
        "\\[",
        (
            f"u_{17}:\\ {r17.u_minpoly_latex}=0\\ \\Rightarrow\\ \\QQ(u_{17})=\\QQ(\\sqrt{{{r17.u_disc_squarefree}}}),\\qquad "
            f"u_{29}:\\ {r29.u_minpoly_latex}=0\\ \\Rightarrow\\ \\QQ(u_{29})=\\QQ(\\sqrt{{{r29.u_disc_squarefree}}})."
        ),
        "\\]",
        "",
    ]

    out_tex = generated_dir() / "eq_fold_zm_discriminant_ridge_jacobian_endomorphism_ring_audit.tex"
    _write_text(out_tex, "\n".join(tex_lines))

    dt = time.time() - t0
    print(f"[fold-zm-ridge-endo] wrote {out_json}", flush=True)
    print(f"[fold-zm-ridge-endo] wrote {out_tex}", flush=True)
    print(f"[fold-zm-ridge-endo] seconds={dt:.3f}", flush=True)
    print("[fold-zm-ridge-endo] done", flush=True)


if __name__ == "__main__":
    main()
