#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compute Taylor constants for log2 lambda(q) at q=0 (composition multiplicity).

We study W_q(t) = sum_{k>=1} F_{k+2}^q t^k and define rho(q) by W_q(rho(q))=1,
lambda(q)=rho(q)^{-1}. At q=0, rho(0)=1/2 and lambda(0)=2.

This script computes the explicit series constants (base-2 logs):
  S1   := sum_{k>=1} 2^{-k} log2 F_{k+2}
  S2   := sum_{k>=1} 2^{-k} (log2 F_{k+2})^2
  S11  := sum_{k>=1} k 2^{-k} log2 F_{k+2}
and the Taylor coefficients for log2 lambda(q):
  (d/dq) log2 lambda(q) |_{q=0} = S1/2
  (d^2/dq^2) log2 lambda(q) |_{q=0} = c2
with
  c2 = ln(2) * [ 0.5*(S2 - S11*S1) + 0.75*S1^2 ].

Exports:
  - artifacts/export/pom_multiplicity_lambdaq_taylor_q0_constants.json
  - sections/generated/eq_pom_multiplicity_lambdaq_taylor_q0_constants.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

from common_paths import export_dir, generated_dir


def _fib_up_to(n_max: int) -> List[int]:
    if n_max < 0:
        raise ValueError("n_max must be >= 0")
    F = [0, 1]
    for _ in range(2, n_max + 1):
        F.append(F[-1] + F[-2])
    return F[: n_max + 1]


def _tex_float(x: float, nd: int = 16) -> str:
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


def _series_constants(n_terms: int) -> Tuple[float, float, float, float]:
    # Need F_{k+2} up to k=n_terms -> index n_terms+2.
    F = _fib_up_to(n_terms + 2)
    S1 = 0.0
    S2 = 0.0
    S11 = 0.0
    for k in range(1, n_terms + 1):
        a = math.log(F[k + 2], 2.0)  # log2 F_{k+2}
        w = 2.0 ** (-k)
        S1 += w * a
        S2 += w * (a * a)
        S11 += w * (k * a)
    c2 = math.log(2.0) * (0.5 * (S2 - S11 * S1) + 0.75 * S1 * S1)
    return S1, S2, S11, c2


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute Taylor constants for log2 lambda(q) at q=0.")
    parser.add_argument(
        "--n-terms",
        type=int,
        default=400,
        help="Number of series terms to truncate at k<=n_terms.",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "pom_multiplicity_lambdaq_taylor_q0_constants.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_pom_multiplicity_lambdaq_taylor_q0_constants.tex"),
        help="Output TeX equation fragment path.",
    )
    args = parser.parse_args()

    n_terms = int(args.n_terms)
    if n_terms < 10:
        raise SystemExit("Require --n-terms >= 10 for stability.")

    S1, S2, S11, c2 = _series_constants(n_terms)
    half_S1 = 0.5 * S1

    payload: Dict[str, Any] = {
        "definition": {
            "series_weight": "2^{-k}",
            "log_base": 2,
            "Fibonacci": {"F0": 0, "F1": 1},
            "S1": "sum_{k>=1} 2^{-k} log2 F_{k+2}",
            "S2": "sum_{k>=1} 2^{-k} (log2 F_{k+2})^2",
            "S11": "sum_{k>=1} k 2^{-k} log2 F_{k+2}",
            "c2": "ln(2) * [0.5*(S2 - S11*S1) + 0.75*S1^2]",
        },
        "truncation": {"n_terms": n_terms},
        "values": {
            "S1": float(S1),
            "S2": float(S2),
            "S11": float(S11),
            "S1_over_2": float(half_S1),
            "c2": float(c2),
        },
    }

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_pom_multiplicity_lambdaq_taylor_q0_constants.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(f"\\frac{{S_1}}{{2}}&\\approx {_tex_float(half_S1, 16)},\\\\")
    lines.append(f"c_2&\\approx {_tex_float(c2, 16)}.")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[pom-multiplicity-lambdaq-taylor-q0] wrote {jout}", flush=True)
    print(f"[pom-multiplicity-lambdaq-taylor-q0] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

