#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compute constants for the Fibonacci-residue pushforward gap bound.

We export a numeric TeX fragment for:
  - D_phi := sum_{n=2}^∞ (1 - cos(2π φ^{-n}))
  - κ_phi := D_phi / (1 - C_phi^2)

The C_phi product is consistent with exp_fold_critical_resonance_constant.py.

Outputs:
  - artifacts/export/fold_residual_gap_constants_phi.json
  - sections/generated/eq_fold_residual_gap_constants_phi.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import PHI


def c_phi_partial(n_max: int) -> float:
    """Partial product Π_{n=2}^{n_max} |cos(π φ^{-n})|."""
    if n_max < 2:
        raise ValueError("n_max must be >= 2")
    p = 1.0
    for n in range(2, n_max + 1):
        p *= abs(math.cos(math.pi * (PHI ** (-n))))
    return float(p)


def d_phi_partial(n_max: int) -> float:
    """Partial sum Σ_{n=2}^{n_max} (1 - cos(2π φ^{-n}))."""
    if n_max < 2:
        raise ValueError("n_max must be >= 2")
    s = 0.0
    for n in range(2, n_max + 1):
        s += 1.0 - math.cos(2.0 * math.pi * (PHI ** (-n)))
    return float(s)


def d_phi_tail_upper_bound(n_start: int) -> float:
    """Upper bound for Σ_{n=n_start}^∞ (1 - cos(2π φ^{-n})).

    Uses 1 - cos x <= x^2 / 2 and sums the geometric series.
    """
    if n_start < 2:
        raise ValueError("n_start must be >= 2")
    # (2π φ^{-n})^2 / 2 = 2π^2 φ^{-2n}
    ratio = PHI ** (-2.0)
    first = 2.0 * (math.pi**2) * (PHI ** (-2.0 * n_start))
    return float(first / (1.0 - ratio))


def d_phi_tail_log10_upper_bound(n_start: int) -> float:
    """Compute log10 of the same tail upper bound without underflow."""
    if n_start < 2:
        raise ValueError("n_start must be >= 2")
    ratio = PHI ** (-2.0)
    c = 2.0 * (math.pi**2) / (1.0 - ratio)
    return float(math.log10(c) - 2.0 * n_start * math.log10(PHI))


def _tex_float(x: float, nd: int = 16) -> str:
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute D_phi and kappa_phi constants (LaTeX + JSON)."
    )
    parser.add_argument(
        "--c-n-max",
        type=int,
        default=200,
        help="Partial product cutoff for C_phi (starts at n=2).",
    )
    parser.add_argument(
        "--d-n-max",
        type=int,
        default=600,
        help="Partial sum cutoff for D_phi (starts at n=2).",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "fold_residual_gap_constants_phi.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_fold_residual_gap_constants_phi.tex"),
        help="Output TeX equation fragment path.",
    )
    args = parser.parse_args()

    c_n_max = int(args.c_n_max)
    d_n_max = int(args.d_n_max)
    if c_n_max < 2 or d_n_max < 2:
        raise SystemExit("Require --c-n-max >= 2 and --d-n-max >= 2")

    C_phi = c_phi_partial(c_n_max)
    D_phi = d_phi_partial(d_n_max)
    D_tail_ub = d_phi_tail_upper_bound(d_n_max + 1)
    D_tail_log10 = d_phi_tail_log10_upper_bound(d_n_max + 1)

    denom = 1.0 - C_phi * C_phi
    kappa_phi = D_phi / denom

    payload: Dict[str, Any] = {
        "definition": {
            "phi": float(PHI),
            "C_phi": "prod_{n=2..inf} |cos(pi * phi^{-n})|",
            "D_phi": "sum_{n=2..inf} (1 - cos(2*pi*phi^{-n}))",
            "kappa_phi": "D_phi / (1 - C_phi^2)",
        },
        "partial": {
            "C_phi": {"n_max": c_n_max, "value": float(C_phi)},
            "D_phi": {"n_max": d_n_max, "value": float(D_phi)},
            "D_phi_tail_upper_bound_from_n": d_n_max + 1,
            "D_phi_tail_upper_bound": float(D_tail_ub),
            "D_phi_tail_upper_bound_log10": float(D_tail_log10),
        },
        "derived": {
            "one_minus_C_phi_sq": float(denom),
            "kappa_phi": float(kappa_phi),
        },
    }

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fold_residual_gap_constants_phi.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "C_\\varphi^{(\\le "
        + str(c_n_max)
        + ")}:=\\prod_{n=2}^{"
        + str(c_n_max)
        + "}\\bigl|\\cos(\\pi\\varphi^{-n})\\bigr|"
        + f"&\\approx {_tex_float(C_phi, 16)},\\\\"
    )
    lines.append(
        "1-(C_\\varphi^{(\\le "
        + str(c_n_max)
        + ")})^2"
        + f"&\\approx {_tex_float(denom, 16)},\\\\"
    )
    lines.append(
        "\\mathsf D_\\varphi^{(\\le "
        + str(d_n_max)
        + ")}:=\\sum_{n=2}^{"
        + str(d_n_max)
        + "}\\Bigl(1-\\cos(2\\pi\\varphi^{-n})\\Bigr)"
        + f"&\\approx {_tex_float(D_phi, 16)},\\\\"
    )
    lines.append(
        "\\sum_{n>"
        + str(d_n_max)
        + "}\\Bigl(1-\\cos(2\\pi\\varphi^{-n})\\Bigr)"
        + (
            f"&\\le {_tex_float(D_tail_ub, 16)},\\\\"
            if (D_tail_ub != 0.0 and D_tail_ub >= 1e-12)
            else "&\\le 10^{" + str(int(math.floor(D_tail_log10))) + "},\\\\"
        )
    )
    lines.append(
        "\\kappa_\\varphi^{(\\le "
        + str(d_n_max)
        + ")}&:=\\frac{\\mathsf D_\\varphi^{(\\le "
        + str(d_n_max)
        + ")}}{1-(C_\\varphi^{(\\le "
        + str(c_n_max)
        + ")})^2}"
        + f"\\approx {_tex_float(kappa_phi, 16)}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")

    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[fold-residual-gap-constants] wrote {jout}", flush=True)
    print(f"[fold-residual-gap-constants] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

