#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Binary-interval fold degeneracy spectra at m=6,8,10,12.

All code is English-only by repository convention.

We study the binary-interval fold:
  Fold^{bin}_m : {0,1,...,2^m-1} → X_m
and its fiber degeneracy:
  d^{bin}_m(w) := |Fold^{bin}_m{}^{-1}(w)|

This script computes the exact degeneracy histograms over stable types w ∈ X_m
for m in {6,8,10,12}, using the digit-DP backend shared with the m=6 gauge
invariants script.

Artifacts:
  - artifacts/export/fold_bin_degeneracy_spectrum_m6_m12.json
  - sections/generated/tab_fold_bin_degeneracy_spectrum_m6_m12.tex
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress, fib_upto
from exp_fold_bin_gauge_m6_invariants import _K_of_m, _V_m, _count_tail_leq, _golden_words


def _compute_histogram(m: int) -> Tuple[int, Dict[int, int]]:
    """Return (K(m), hist) where hist maps degeneracy d -> count of w in X_m."""
    if m <= 0:
        raise ValueError("m must be positive")

    target = (1 << m) - 1
    K = _K_of_m(target)
    fib = fib_upto(K + 2)  # F_1..F_{K+2}

    hist: Dict[int, int] = {}
    for w in _golden_words(m):
        V = _V_m(w, fib)
        d = int(_count_tail_leq(limit=target - V, m=m, K=K, w_m=w[-1]))
        hist[d] = hist.get(d, 0) + 1
    return K, dict(sorted(hist.items()))


def _hist_to_tex(hist: Dict[int, int]) -> str:
    parts = [f"{d}:{c}" for d, c in sorted(hist.items())]
    return ",\\,".join(parts)


def _write_tex_table(rows: List[Dict[str, object]], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fold_bin_degeneracy_spectrum_m6_m12.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{二进制区间折叠 $\\mathrm{Fold}^{\\mathrm{bin}}_m$ 的纤维退化谱（$m\\in\\{6,8,10,12\\}$）。"
        "对每个 $m$，按稳定类型 $w\\in X_m$ 统计退化度 $d^{\\mathrm{bin}}_m(w)=|\\mathrm{Fold}^{\\mathrm{bin}}_m{}^{-1}(w)|$ "
        "的尺寸直方图，并列出 $K(m)$（定义~\\ref{def:K-of-m}）、最小退化度与其扇区大小。}"
    )
    lines.append("\\label{tab:fold_bin_degeneracy_spectrum_m6_m12}")
    lines.append("\\begin{tabular}{rrrrrrl}")
    lines.append("\\toprule")
    lines.append(
        "$m$ & $|X_m|$ & $K(m)$ & $d_{\\min}$ & $\\#\\{d=d_{\\min}\\}$ & $d_{\\max}$ & size hist $\\{d:\\#w\\}$\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        m = int(r["m"])
        X = int(r["X_size"])
        K = int(r["K"])
        dmin = int(r["d_min"])
        cmin = int(r["count_min"])
        dmax = int(r["d_max"])
        hist_tex = str(r["hist_tex"])
        lines.append(
            f"{m} & {X} & {K} & {dmin} & {cmin} & {dmax} & ${hist_tex}$\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    t0 = time.time()
    prog = Progress("fold_bin_deg")

    ms = [6, 8, 10, 12]
    rows: List[Dict[str, object]] = []
    payload: Dict[str, object] = {"m_list": ms, "rows": [], "wall_time_seconds": None}

    for i, m in enumerate(ms, start=1):
        prog.tick(f"compute m={m} ({i}/{len(ms)})")
        K, hist = _compute_histogram(m)
        d_min = min(hist.keys())
        d_max = max(hist.keys())
        count_min = int(hist[d_min])
        row = {
            "m": int(m),
            "K": int(K),
            "X_size": int(sum(hist.values())),
            "d_min": int(d_min),
            "d_max": int(d_max),
            "count_min": int(count_min),
            "hist": {str(k): int(v) for k, v in hist.items()},
            "hist_tex": _hist_to_tex(hist),
        }
        rows.append(row)
        payload["rows"].append(row)

    payload["wall_time_seconds"] = float(time.time() - t0)

    jout = export_dir() / "fold_bin_degeneracy_spectrum_m6_m12.json"
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = generated_dir() / "tab_fold_bin_degeneracy_spectrum_m6_m12.tex"
    _write_tex_table(rows, tex_out)

    print(f"[fold_bin_deg] wrote {jout}", flush=True)
    print(f"[fold_bin_deg] wrote {tex_out}", flush=True)
    print(
        f"[fold_bin_deg] done wall_s={payload['wall_time_seconds']:.3f}",
        flush=True,
    )


if __name__ == "__main__":
    main()

