#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Event-clock correlation scale vs twisted mixing scale (real-input 40-state kernel).

This script produces a compact, auditable table that combines already-generated exports:

Inputs:
- artifacts/export/real_input_40_event_time_dilation.json
  (mu_event, tau_corr_step, tau_corr_event, etc.)
- artifacts/export/sync_kernel_real_input_40_arity_3d_N2_335.json
  (triple_rho_max_ratio['3x3x5'] = rho_{3,3,5}/lambda)

Outputs:
- artifacts/export/real_input_40_event_clock_vs_tau_mix.json
- sections/generated/tab_real_input_40_event_clock_vs_tau_mix.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict

from common_paths import export_dir, generated_dir, paper_root


def _load_json(rel: str) -> Dict[str, Any]:
    return json.loads((paper_root() / rel).read_text(encoding="utf-8"))


def _gap_tau_half(r: float) -> tuple[float, float, float]:
    r = float(r)
    if not (0.0 < r < 1.0):
        return (float("inf"), float("inf"), float("inf"))
    gap = -math.log(r)
    if gap <= 0.0:
        return (float("inf"), float("inf"), float("inf"))
    tau = 1.0 / gap
    half = math.log(2.0) / gap
    return (gap, tau, half)


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


@dataclass(frozen=True)
class EventVsMix:
    triple: str
    r_mix: float
    gap_mix: float
    tau_mix: float
    half_mix: float
    mu_event: float
    tau_corr_step: float
    tau_corr_event: float
    tau_ratio_mix_over_event: float
    half_ratio_mix_over_event: float


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare event-time correlation scale vs twisted mixing time (real-input 40)."
    )
    parser.add_argument(
        "--event-time-json",
        type=str,
        default="artifacts/export/real_input_40_event_time_dilation.json",
    )
    parser.add_argument(
        "--arity-json",
        type=str,
        default="artifacts/export/sync_kernel_real_input_40_arity_3d_N2_335.json",
    )
    parser.add_argument(
        "--triple",
        type=str,
        default="3x3x5",
        help="Triple key inside arity JSON (default: 3x3x5)",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_event_clock_vs_tau_mix.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_real_input_40_event_clock_vs_tau_mix.tex"),
    )
    args = parser.parse_args()

    ev = _load_json(str(args.event_time_json))
    ar = _load_json(str(args.arity_json))

    triple = str(args.triple)
    ratios = ar.get("triple_rho_max_ratio")
    if not isinstance(ratios, dict) or triple not in ratios:
        raise SystemExit(
            f"missing triple_rho_max_ratio['{triple}'] in {args.arity_json}"
        )
    r_mix = float(ratios[triple])
    gap_mix, tau_mix, half_mix = _gap_tau_half(r_mix)

    mu_event = float(ev.get("mu_event", float("nan")))
    tau_corr_step = float(ev.get("tau_corr_step", float("nan")))
    tau_corr_event = float(ev.get("tau_corr_event", float("nan")))
    half_event = float(ev.get("half_event", float("nan")))

    tau_ratio = (
        (tau_mix / tau_corr_event)
        if (
            math.isfinite(tau_mix)
            and math.isfinite(tau_corr_event)
            and tau_corr_event > 0
        )
        else float("inf")
    )
    half_ratio = (
        (half_mix / half_event)
        if (math.isfinite(half_mix) and math.isfinite(half_event) and half_event > 0)
        else float("inf")
    )

    res = EventVsMix(
        triple=triple,
        r_mix=float(r_mix),
        gap_mix=float(gap_mix),
        tau_mix=float(tau_mix),
        half_mix=float(half_mix),
        mu_event=float(mu_event),
        tau_corr_step=float(tau_corr_step),
        tau_corr_event=float(tau_corr_event),
        tau_ratio_mix_over_event=float(tau_ratio),
        half_ratio_mix_over_event=float(half_ratio),
    )

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(
        json.dumps(asdict(res), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"[event-vs-mix] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_event_clock_vs_tau_mix.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{事件时钟尺度与角色扭曲混合尺度的分离（真实输入 40 状态核；$t=0$ Parry 平衡态）。"
        "事件时间尺度 $\\tau_{\\mathrm{corr}}^{(e)}=\\mu_e\\tau_{\\mathrm{corr}}$ 来自输出位事件率 $\\mu_e=P_e'(0)$ 对步数时间的重标定；"
        "而 $\\tau_{\\mathrm{mix}}$ 来自 $((3,3,5))$ 最坏角色扭曲的谱半径比 $r=\\rho_{3,3,5}/\\lambda$。}"
    )
    lines.append("\\label{tab:real-input-40-event-clock-vs-tau-mix}")
    lines.append("\\begin{tabular}{l r}")
    lines.append("\\toprule")
    lines.append("quantity & value\\\\")
    lines.append("\\midrule")
    lines.append("$\\mu_e=P_e'(0)$ & " + _fmt(res.mu_event) + "\\\\")
    lines.append(
        "$\\tau_{\\mathrm{corr}}$ (step) & " + _fmt(res.tau_corr_step) + "\\\\"
    )
    lines.append(
        "$\\tau_{\\mathrm{corr}}^{(e)}$ (event) & " + _fmt(res.tau_corr_event) + "\\\\"
    )
    lines.append("\\midrule")
    lines.append(
        f"$r_{{\\mathrm{{mix}}}}=\\rho_{{{triple.replace('x', ',')}}}/\\lambda$ & "
        + _fmt(res.r_mix)
        + "\\\\"
    )
    lines.append("$\\tau_{\\mathrm{mix}}$ & " + _fmt(res.tau_mix) + "\\\\")
    lines.append("$t_{1/2,\\mathrm{mix}}$ & " + _fmt(res.half_mix) + "\\\\")
    lines.append("\\midrule")
    lines.append(
        "$\\tau_{\\mathrm{mix}}/\\tau_{\\mathrm{corr}}^{(e)}$ & "
        + _fmt(res.tau_ratio_mix_over_event)
        + "\\\\"
    )
    lines.append(
        "$t_{1/2,\\mathrm{mix}}/t_{1/2,\\mathrm{corr}}^{(e)}$ & "
        + _fmt(res.half_ratio_mix_over_event)
        + "\\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[event-vs-mix] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()
