#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Window-6 fiber independence-complex homotopy audit.

For each stable type x in X_6, we compute the exact fiber size d_6(x)=|Fold_6^{-1}(x)|.
At m=6 (k_+=ceil(6/2)=3) this determines the candidate-path component-length multiset
(ℓ_i) uniquely. We then compute:
  τ(x) = Σ_i floor((ℓ_i+1)/3),
and the homotopy type predicted in the paper:
  - contractible if any ℓ_i ≡ 1 (mod 3),
  - otherwise |Ind^Δ(Γ_x)| ≃ S^{τ(x)-1}.

Outputs:
  - artifacts/export/fold_fiber_homotopy_window6.json
  - sections/generated/tab_fold_fiber_homotopy_m6.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from common_fold_map_cache import fold_map_packed
from common_paths import export_dir, generated_dir


def _bits_str(w: int, m: int) -> str:
    return "".join("1" if ((w >> (m - 1 - i)) & 1) else "0" for i in range(m))


def _infer_ell_from_fiber_size_m6(d: int) -> List[int]:
    # For m=6, k_+=3 and the only possible independent-set counts are:
    #  d=1 -> () , d=2 -> (1), d=3 -> (2), d=4 -> (1,1), d=5 -> (3).
    if d == 1:
        return []
    if d == 2:
        return [1]
    if d == 3:
        return [2]
    if d == 4:
        return [1, 1]
    if d == 5:
        return [3]
    return [-1]


def tau_from_ell(ell: List[int]) -> int:
    return int(sum((n + 1) // 3 for n in ell))


def homotopy_type(ell: List[int]) -> str:
    if any((n % 3) == 1 for n in ell):
        return "contractible"
    tau = tau_from_ell(ell)
    return f"S^{tau-1}"


@dataclass(frozen=True)
class Row:
    x_bits: str
    fiber_size: int
    ell: List[int]
    tau: int
    kind: str

    def to_dict(self) -> Dict[str, object]:
        return {
            "x_bits": self.x_bits,
            "fiber_size": int(self.fiber_size),
            "ell": [int(a) for a in self.ell],
            "tau": int(self.tau),
            "kind": str(self.kind),
        }


def write_table(rows: List[Row], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_fiber_homotopy_window6.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{5pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.08}")
    lines.append(
        (
            "\\caption{Window-$6$ 纤维独立集复形同伦型的有限窗审计："
            "对每个稳定类型 $x\\in X_6$，由纤维大小 $d_6(x)$ 推出候选位点图分量长度 $(\\ell_i)$，"
            "并计算 $\\tau(x)=\\sum_i\\lfloor(\\ell_i+1)/3\\rfloor$ 及相应的球面/可缩二分律"
            "（定理~\\ref{thm:pom-fiber-independence-complex-classification}）。}"
        )
    )
    lines.append("\\label{tab:fold_fiber_homotopy_m6}")
    lines.append("\\begin{tabular}{l r l r l}")
    lines.append("\\toprule")
    lines.append("$x$ & $d_6(x)$ & $(\\ell_i)$ & $\\tau(x)$ & homotopy type\\\\")
    lines.append("\\midrule")
    for r in rows:
        ell_tex = "(" + ",".join(str(a) for a in r.ell) + ")" if r.ell else "()"
        if r.kind == "contractible":
            kind_tex = "\\texttt{contractible}"
        else:
            # r.kind is of the form "S^k" (k may be negative). Render in math mode.
            exp = r.kind.split("^", 1)[1]
            kind_tex = f"$S^{{{exp}}}$"
        lines.append(
            f"\\texttt{{{r.x_bits}}} & {r.fiber_size} & ${ell_tex}$ & {r.tau} & {kind_tex}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    m = 6
    fold_map = fold_map_packed(m)

    fibers: Dict[int, int] = {}
    for w in range(1 << m):
        x = int(fold_map[w])
        fibers[x] = fibers.get(x, 0) + 1

    rows: List[Row] = []
    for x in sorted(fibers.keys()):
        d = int(fibers[x])
        ell = _infer_ell_from_fiber_size_m6(d)
        if -1 in ell:
            raise AssertionError(f"Unexpected fiber size at m=6: x={x} d={d}")
        tau = tau_from_ell(ell)
        kind = homotopy_type(ell)
        rows.append(Row(x_bits=_bits_str(x, m), fiber_size=d, ell=ell, tau=tau, kind=kind))

    payload: Dict[str, object] = {"params": {"m": m}, "rows": [r.to_dict() for r in rows]}
    export_path = export_dir() / "fold_fiber_homotopy_window6.json"
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_path = generated_dir() / "tab_fold_fiber_homotopy_m6.tex"
    write_table(rows, tex_path)


if __name__ == "__main__":
    main()

