#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Event clock deviation certificate (real-input 40-state kernel).

We treat the unweighted (theta=0) Parry equilibrium as an internal source of randomness.
The event clock is the additive functional

  T_n := sum_{t=0}^{n-1} e_t,

where e_t in {0,1} is the kernel output bit at step t.

This script computes, by finite-dimensional linear algebra:

1) The stationary Parry Markov chain (pi,P) for the 40-state real-input adjacency.
2) The autocovariance Cov(e_0, e_k) for k=0..K.
3) The finite-n variance Var(T_n) for n=1..N, and the partial sums S_n:=sum_{t<=n}Var(T_t).

From (S_n), we produce an explicit, auditable Chebyshev+union certificate:

  P( max_{1<=t<=n} |T_t - mu_e t| >= b_n(delta) ) <= delta,
  b_n(delta) := sqrt(S_n / delta).

Outputs:
- artifacts/export/real_input_40_event_clock_deviation_certificate.json
- sections/generated/tab_real_input_40_event_clock_deviation_certificate.tex
- sections/generated/tab_real_input_40_hitting_time_deviation_certificate.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from exp_real_input_40_time_correlation import _pick_pf_eigpair, parry_markov
from exp_sync_kernel_real_input_40 import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_states,
    build_weighted_matrix,
)


def _fmt(x: float) -> str:
    if math.isnan(x):
        return "\\mathrm{NaN}"
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _edge_e(
    states: List[Tuple[str, int, int]],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
    i: int,
    j: int,
) -> int:
    (s, _px, _py) = states[i]
    (dst_state, x, y) = states[j]
    d = int(x) + int(y)
    dst2, e = kernel_map[(s, d)]
    if dst2 != dst_state:
        raise RuntimeError(
            f"edge mismatch: {states[i]} -> {states[j]} gives dst={dst2}"
        )
    return int(e)


def _covariances_event_bit(
    pi: np.ndarray,
    P: np.ndarray,
    states: List[Tuple[str, int, int]],
    kernel_map: Dict[Tuple[str, int], Tuple[str, int]],
    k_max: int,
) -> Tuple[float, List[float]]:
    n = int(P.shape[0])
    eP = np.zeros((n, n), dtype=float)
    g = np.zeros(n, dtype=float)
    for i in range(n):
        for j in range(n):
            pij = float(P[i, j])
            if pij <= 0.0:
                continue
            e = float(_edge_e(states, kernel_map, i=i, j=j))
            eP[i, j] = pij * e
            g[i] += pij * e
    mu = float(np.dot(pi, g))

    covs: List[float] = []
    # k=0: e_0 in {0,1} so E[e_0^2]=E[e_0]=mu.
    cov0 = mu - mu * mu
    covs.append(float(cov0))
    if k_max <= 0:
        return mu, covs

    # For k>=1: E[e_0 e_k] = pi^T * (eP @ (P^{k-1} g)).
    tmp = g.copy()  # P^{0} g
    for k in range(1, k_max + 1):
        ee = float(np.dot(pi, eP @ tmp))
        covs.append(float(ee - mu * mu))
        tmp = P @ tmp
    return mu, covs


def _var_partial_sums_from_cov(
    covs: List[float], n_max: int
) -> Tuple[List[float], List[float]]:
    # covs[k] = Cov(e_0, e_k), k>=0.
    if n_max <= 0:
        return ([], [])
    if len(covs) < n_max:
        raise ValueError("need covs up to n_max-1")

    var_e = float(covs[0])
    vars_t: List[float] = []
    sums: List[float] = []
    s = 0.0
    for n in range(1, n_max + 1):
        v = float(n) * var_e
        # 2 * sum_{k=1}^{n-1} (n-k) Cov(e_0,e_k)
        for k in range(1, n):
            v += 2.0 * float(n - k) * float(covs[k])
        vars_t.append(v)
        s += v
        sums.append(s)
    return vars_t, sums


def _write_tex(
    path: Path,
    delta: float,
    mu: float,
    p2: float,
    rows: List[Dict[str, float]],
) -> None:
    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_event_clock_deviation_certificate.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{事件时钟偏差的可审计证书（真实输入 40 状态核；$t=0$ Parry 平衡态）。"
        f"设 $T_n=\\sum_{{t=0}}^{{n-1}} e_t$ 且 $\\mu_e={_fmt(mu)}$。"
        f"表中 $V_n=\\mathrm{{Var}}(T_n)$ 由有限维 Parry 链精确计算；"
        f"$S_n=\\sum_{{t=1}}^n V_t$，并定义 $b_n(\\delta)=\\sqrt{{S_n/\\delta}}$（此处 $\\delta={delta:.3g}$）。"
        "由并合界 + Chebyshev 不等式可得 $\\mathbb{P}(\\max_{1\\le t\\le n}|T_t-\\mu_e t|\\ge b_n(\\delta))\\le\\delta$。"
        "此外给出渐近方差密度 $P_e''(0)$ 作为对照。}"
    )
    lines.append("\\label{tab:real-input-40-event-clock-deviation-certificate}")
    lines.append("\\begin{tabular}{r r r r r r r}")
    lines.append("\\toprule")
    lines.append(
        "$n$ & $\\mu_e n$ & $V_n$ & $V_n/n$ & $P_e''(0)$ & $|V_n/n-P_e''(0)|$ & $b_n(\\delta)$\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{int(r['n'])}"
            f" & {_fmt(r['mu_n'])}"
            f" & {_fmt(r['var_Tn'])}"
            f" & {_fmt(r['var_Tn_over_n'])}"
            f" & {_fmt(p2)}"
            f" & {_fmt(r['abs_gap'])}"
            f" & {_fmt(r['b_uniform'])}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _hitting_time_rows(
    *,
    mu: float,
    vars_Tn: List[float],
    delta: float,
    k_list: List[int],
) -> List[Dict[str, float]]:
    # For tau(k) := inf {n : T_n >= k}, we use:
    #   P(tau(k) > n) = P(T_n < k) = P(mu n - T_n > mu n - k)
    #               <= Var(T_n) / (mu n - k)^2,  for mu n > k.
    #   P(tau(k) <= n) = P(T_n >= k) = P(T_n - mu n >= k - mu n)
    #                 <= Var(T_n) / (k - mu n)^2, for k > mu n.
    # (Chebyshev, one-sided via |X| >= a.)
    if not (math.isfinite(mu) and mu > 0.0):
        raise ValueError("mu must be finite and > 0")
    if not (math.isfinite(delta) and delta > 0.0 and delta < 1.0):
        raise ValueError("delta must be in (0,1)")

    n_max = len(vars_Tn)
    rows: List[Dict[str, float]] = []
    for k in k_list:
        kk = float(k)
        k_over_mu = kk / float(mu)

        # Left tail: find the largest n with k > mu n and bound <= delta.
        n_lo = float("nan")
        p_lo = float("nan")
        gap_lo = float("nan")
        for n in range(1, n_max + 1):
            gap = kk - float(mu) * float(n)
            if gap <= 0.0:
                break
            v = float(vars_Tn[n - 1])
            bound = v / (gap * gap) if gap > 0.0 else float("inf")
            if bound <= delta:
                n_lo = float(n)
                p_lo = float(bound)
                gap_lo = float(gap)

        # Right tail: find the smallest n with mu n > k and bound <= delta.
        n_hi = float("nan")
        p_hi = float("nan")
        gap_hi = float("nan")
        for n in range(1, n_max + 1):
            gap = float(mu) * float(n) - kk
            if gap <= 0.0:
                continue
            v = float(vars_Tn[n - 1])
            bound = v / (gap * gap) if gap > 0.0 else float("inf")
            if bound <= delta:
                n_hi = float(n)
                p_hi = float(bound)
                gap_hi = float(gap)
                break

        rows.append(
            {
                "k": float(k),
                "k_over_mu": float(k_over_mu),
                "n_lo": float(n_lo),
                "p_lo": float(p_lo),
                "gap_lo": float(gap_lo),
                "n_hi": float(n_hi),
                "p_hi": float(p_hi),
                "gap_hi": float(gap_hi),
            }
        )
    return rows


def _write_tex_hitting_time(
    path: Path,
    delta: float,
    mu: float,
    rows: List[Dict[str, float]],
) -> None:
    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_event_clock_deviation_certificate.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{事件时钟的击中时间 $\\tau(k)$ 偏差证书（真实输入 40 状态核；$t=0$ Parry 平衡态）。"
        f"设 $T_n=\\sum_{{t=0}}^{{n-1}} e_t$ 且 $\\mu_e={_fmt(mu)}$，并定义 $\\tau(k):=\\inf\\{{n:\\,T_n\\ge k\\}}$。"
        f"对给定 $\\delta={delta:.3g}$，表中 $n_-(k,\\delta)$ 为满足 $\\mathbb{{P}}(\\tau(k)\\le n_-)\\le\\delta$ 的最大 $n$（左尾），"
        "$n_+(k,\\delta)$ 为满足 $\\mathbb{P}(\\tau(k)>n_+)\\le\\delta$ 的最小 $n$（右尾），"
        "二者均由 $\\mathbb{P}(|T_n-\\mu_e n|\\ge a)\\le \\mathrm{Var}(T_n)/a^2$（Chebyshev）与恒等式 $\\mathbb{P}(\\tau(k)>n)=\\mathbb{P}(T_n<k)$ 推出。"
        "因此由并合界可得 $\\mathbb{P}(n_-<\\tau(k)\\le n_+)\\ge 1-2\\delta$。}"
    )
    lines.append("\\label{tab:real-input-40-hitting-time-deviation-certificate}")
    lines.append("\\begin{tabular}{r r r r r r}")
    lines.append("\\toprule")
    lines.append(
        "$k$ & $k/\\mu_e$ & $n_-(k,\\delta)$ & $\\mathbb{P}(\\tau(k)\\le n_-)$ 上界 & $n_+(k,\\delta)$ & $\\mathbb{P}(\\tau(k)>n_+)$ 上界\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        k = int(r["k"])
        n_lo = r["n_lo"]
        n_hi = r["n_hi"]
        lines.append(
            f"{k}"
            f" & {_fmt(r['k_over_mu'])}"
            f" & {_fmt(n_lo)}"
            f" & {_fmt(r['p_lo'])}"
            f" & {_fmt(n_hi)}"
            f" & {_fmt(r['p_hi'])}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class Payload:
    model: str
    delta: float
    mu_event: float
    p2: float
    n_max: int
    cov_k_max: int
    covs: List[float]
    vars_Tn: List[float]
    sums_Sn: List[float]
    rows: List[Dict[str, float]]
    ht_k_list: List[int]
    ht_rows: List[Dict[str, float]]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Event clock deviation certificate (real-input 40)."
    )
    parser.add_argument("--delta", type=float, default=0.05)
    parser.add_argument("--n-max", type=int, default=200)
    parser.add_argument("--rows", type=str, default="3,10,20,50,100,200")
    parser.add_argument(
        "--cumulants-json",
        type=str,
        default="artifacts/export/real_input_40_output_potential_cumulants_closed.json",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(
            export_dir() / "real_input_40_event_clock_deviation_certificate.json"
        ),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(
            generated_dir() / "tab_real_input_40_event_clock_deviation_certificate.tex"
        ),
    )
    parser.add_argument(
        "--ht-tex-out",
        type=str,
        default=str(
            generated_dir() / "tab_real_input_40_hitting_time_deviation_certificate.tex"
        ),
    )
    parser.add_argument(
        "--ht-k-list",
        type=str,
        default="5,10,20,50",
        help="Comma-separated event thresholds k for tau(k) certificate.",
    )
    args = parser.parse_args()

    delta = float(args.delta)
    n_max = int(args.n_max)
    row_ns = [int(x.strip()) for x in str(args.rows).split(",") if x.strip()]
    row_ns = sorted({x for x in row_ns if x >= 1})
    if not row_ns:
        raise SystemExit("empty --rows")

    cum = json.loads(
        (Path(__file__).resolve().parent.parent / args.cumulants_json).read_text(
            encoding="utf-8"
        )
    )
    mu = float(cum.get("P1_float", float("nan")))
    p2 = float(cum.get("P2_float", float("nan")))

    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()
    B0 = build_weighted_matrix(0.0, 0.0, 0.0, states, kernel_map)
    lam, _eigvals, v, u = _pick_pf_eigpair(B0)
    pi, P = parry_markov(B0, lam=lam, v=v, u=u)

    cov_k_max = max(n_max - 1, max(row_ns))
    mu2, covs = _covariances_event_bit(pi, P, states, kernel_map, k_max=cov_k_max)
    if math.isfinite(mu) and math.isfinite(mu2) and abs(mu - mu2) > 5e-10:
        # keep internal consistency for downstream.
        mu = mu2

    vars_Tn, sums_Sn = _var_partial_sums_from_cov(covs, n_max=n_max)

    ht_k_list = [int(x.strip()) for x in str(args.ht_k_list).split(",") if x.strip()]
    ht_k_list = sorted({k for k in ht_k_list if k >= 1})
    ht_rows = _hitting_time_rows(mu=mu, vars_Tn=vars_Tn, delta=delta, k_list=ht_k_list)

    rows: List[Dict[str, float]] = []
    for n in row_ns:
        if n > n_max:
            continue
        var_Tn = float(vars_Tn[n - 1])
        Sn = float(sums_Sn[n - 1])
        b = math.sqrt(Sn / delta) if (delta > 0.0 and Sn >= 0.0) else float("inf")
        abs_gap = (
            abs(float(var_Tn / float(n)) - float(p2))
            if math.isfinite(p2)
            else float("nan")
        )
        rel_gap = (
            (abs_gap / abs(float(p2)))
            if (math.isfinite(abs_gap) and math.isfinite(p2) and float(p2) != 0.0)
            else float("nan")
        )
        rows.append(
            {
                "n": float(n),
                "mu_n": float(mu * n),
                "var_Tn": float(var_Tn),
                "var_Tn_over_n": float(var_Tn / float(n)),
                "Sn": float(Sn),
                "abs_gap": float(abs_gap),
                "rel_gap": float(rel_gap),
                "b_uniform": float(b),
            }
        )

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    payload = Payload(
        model="real_input_40",
        delta=float(delta),
        mu_event=float(mu),
        p2=float(p2),
        n_max=int(n_max),
        cov_k_max=int(cov_k_max),
        covs=[float(x) for x in covs[: cov_k_max + 1]],
        vars_Tn=[float(x) for x in vars_Tn],
        sums_Sn=[float(x) for x in sums_Sn],
        rows=rows,
        ht_k_list=[int(k) for k in ht_k_list],
        ht_rows=ht_rows,
    )
    jout.write_text(
        json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"[event-clock-cert] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, delta=delta, mu=mu, p2=p2, rows=rows)
    print(f"[event-clock-cert] wrote {tout}", flush=True)

    ht_out = Path(args.ht_tex_out)
    _write_tex_hitting_time(ht_out, delta=delta, mu=mu, rows=ht_rows)
    print(f"[event-clock-cert] wrote {ht_out}", flush=True)


if __name__ == "__main__":
    main()
