#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
E8 square-spectrum collapse: quartic certificate, discriminant, and index decomposition.

We consider the "square-collapsed" E8 Coxeter spectrum values

  r_k := 4 cos^2(pi k / 30),  k in {1,7,11,13},

and show they are exactly the four real roots of a single monic integer quartic.
We also relate the resulting field discriminant (cyclotomic-ADE layer) to the
discriminant of the E8 intersection parameter t_{E8} on the A4(t) Perron curve,
thereby isolating the large prime factors as an index (power-basis) artifact.

Outputs:
  - artifacts/export/collision_kernel_E8_square_spectrum_collapse.json
  - sections/generated/eq_collision_kernel_E8_square_spectrum_collapse.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import mpmath as mp
import sympy as sp

from common_paths import export_dir, generated_dir


def _fmt(x: mp.mpf, nd: int = 16) -> str:
    return mp.nstr(x, nd)


def _poly_primitive_integer(expr: sp.Expr, var: sp.Symbol) -> sp.Poly:
    """Clear denominators and return primitive Poly over ZZ with positive LC."""
    pQQ = sp.Poly(sp.expand(expr), var, domain=sp.QQ)
    den_lcm = sp.ilcm(*[sp.denom(c) for c in pQQ.all_coeffs()]) if pQQ.degree() >= 0 else sp.Integer(1)
    pZ = sp.Poly(sp.expand(den_lcm * pQQ.as_expr()), var, domain=sp.ZZ)
    content = sp.gcd_list(pZ.all_coeffs()) if pZ.degree() >= 0 else sp.Integer(1)
    pZ = sp.Poly(sp.expand(pZ.as_expr() / content), var, domain=sp.ZZ)
    if pZ.LC() < 0:
        pZ = -pZ
    return pZ


def _factorint_abs(n: sp.Integer) -> Dict[int, int]:
    fac = sp.factorint(int(abs(n)))
    return {int(p): int(e) for p, e in fac.items()}


def _factor_tex(fac: Dict[int, int]) -> str:
    parts: List[str] = []
    for p in sorted(fac.keys()):
        e = fac[p]
        if e == 1:
            parts.append(f"{p}")
        else:
            parts.append(f"{p}^{{{e}}}")
    return r"\cdot ".join(parts) if parts else "1"


def _cyclotomic_discriminant(n: int) -> sp.Integer:
    """Disc(Q(zeta_n)) as an integer, using the standard closed form."""
    phi = int(sp.totient(n))
    disc = sp.Integer(n) ** phi
    for p in sp.factorint(n).keys():
        disc //= sp.Integer(p) ** (phi // (int(p) - 1))
    return sp.Integer(disc)


@dataclass(frozen=True)
class Payload:
    dps: int
    # E8 square-spectrum quartic
    poly_x_coeffs_desc: List[int]
    disc_poly_x: str
    disc_poly_x_factor: Dict[int, int]
    sym_s1_sum: int
    sym_s2_pair: int
    sym_s3_triple: int
    sym_s4_prod: int
    # cyclotomic / field discriminant (real subfield of zeta_30)
    disc_cyclo_30: str
    disc_cyclo_30_factor: Dict[int, int]
    disc_real_30: str
    disc_real_30_factor: Dict[int, int]
    # t_{E8} order discriminant and index
    poly_t_coeffs_desc: List[int]
    disc_poly_t: str
    disc_poly_t_factor: Dict[int, int]
    index_ok: bool
    index_value: str
    index_factor: Dict[int, int]
    # numeric anchors
    r_e8_value: str
    t_e8_value: str


def _write_tex(
    path: Path,
    *,
    poly_x: sp.Poly,
    disc_x: sp.Integer,
    disc_x_fac: Dict[int, int],
    disc_cyc: sp.Integer,
    disc_cyc_fac: Dict[int, int],
    disc_real: sp.Integer,
    disc_real_fac: Dict[int, int],
    poly_t: sp.Poly,
    disc_t: sp.Integer,
    disc_t_fac: Dict[int, int],
    index_val: sp.Integer,
    index_fac: Dict[int, int],
    r_e8: mp.mpf,
    t_e8: mp.mpf,
) -> None:
    x = sp.Symbol("x")
    t = sp.Symbol("t")

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_collision_kernel_E8_square_spectrum_collapse.py")
    lines.append(r"\begin{equation}\label{eq:collision_kernel_E8_square_spectrum_collapse}")
    lines.append(r"\begin{aligned}")
    lines.append(
        r"\mathcal R_{E_8}"
        r"&:=\left\{4\cos^2\!\left(\frac{\pi k}{30}\right):\ k\in\{1,7,11,13\}\right\},\\"
    )
    lines.append(r"\prod_{r\in\mathcal R_{E_8}}(x-r)&=" + sp.latex(poly_x.as_expr()) + r",\\")
    lines.append(
        r"\mathrm{Disc}_x\!\left(\prod_{r\in\mathcal R_{E_8}}(x-r)\right)"
        + r"&="
        + str(int(disc_x))
        + r"="
        + _factor_tex(disc_x_fac)
        + r",\\"
    )
    coeffs = [int(c) for c in poly_x.all_coeffs()]
    # poly is monic quartic: x^4 + c3 x^3 + c2 x^2 + c1 x + c0
    c3, c2, c1, c0 = coeffs[1], coeffs[2], coeffs[3], coeffs[4]
    s1 = -c3
    s2 = c2
    s3 = -c1
    s4 = c0
    lines.append(
        r"\sum_{r\in\mathcal R_{E_8}}r"
        + r"&="
        + str(s1)
        + r",\qquad"
        + r"\sum_{i<j}r_ir_j="
        + str(s2)
        + r",\qquad"
        + r"\sum_{i<j<k}r_ir_jr_k="
        + str(s3)
        + r",\qquad"
        + r"\prod_{r\in\mathcal R_{E_8}}r="
        + str(s4)
        + r",\\"
    )
    lines.append(
        r"\mathrm{Disc}\!\left(\QQ(\zeta_{30})\right)"
        + r"&="
        + str(int(disc_cyc))
        + r"="
        + _factor_tex(disc_cyc_fac)
        + r",\\"
    )
    lines.append(
        r"\mathrm{Disc}(K_{E_8})=\mathrm{Disc}\!\left(\QQ(\zeta_{30})^+\right)"
        + r"&="
        + str(int(disc_real))
        + r"="
        + _factor_tex(disc_real_fac)
        + r",\\"
    )
    lines.append(r"P_{E_8}(t)&:=" + sp.latex(poly_t.as_expr()) + r",\\")
    lines.append(r"\mathrm{Disc}_t(P_{E_8})" + r"&=" + str(int(disc_t)) + r"=" + _factor_tex(disc_t_fac) + r",\\")
    lines.append(
        r"[\mathcal O_{K_{E_8}}:\ZZ[t_{E_8}]]"
        + r"&="
        + str(int(index_val))
        + r"="
        + _factor_tex(index_fac)
        + r",\\"
    )
    lines.append(
        r"r_{E_8}&:=4\cos^2\!\left(\frac{\pi}{30}\right)\approx "
        + _fmt(r_e8, 16)
        + r",\qquad "
        + r"t_{E_8}\approx "
        + _fmt(t_e8, 16)
        + r"."
    )
    lines.append(r"\end{aligned}")
    lines.append(r"\end{equation}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="E8 square-spectrum quartic and index decomposition certificates.")
    parser.add_argument("--dps", type=int, default=120, help="Working decimal precision.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_E8_square_spectrum_collapse.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_E8_square_spectrum_collapse.tex"),
    )
    args = parser.parse_args()

    dps = int(args.dps)
    if dps < 60:
        raise SystemExit("Require --dps >= 60 for stable algebraic evaluation.")
    mp.mp.dps = dps

    x = sp.Symbol("x")
    t = sp.Symbol("t")

    # E8 square-collapsed spectrum roots
    r_e8 = sp.simplify(4 * sp.cos(sp.pi / 30) ** 2)
    roots = [sp.simplify(4 * sp.cos(sp.pi * k / 30) ** 2) for k in (1, 7, 11, 13)]

    # Quartic certificate: minimal polynomial of r_{E8}
    poly_x_expr = sp.minimal_polynomial(r_e8, x)
    poly_x = _poly_primitive_integer(poly_x_expr, x)
    disc_x = sp.Integer(sp.discriminant(poly_x.as_expr(), x))
    disc_x_fac = _factorint_abs(disc_x)

    # Verify each listed root annihilates the quartic.
    for rr in roots:
        if sp.simplify(poly_x.as_expr().subs(x, rr)) != 0:
            raise RuntimeError("E8 square-spectrum root does not satisfy the quartic certificate.")

    # Cyclotomic discriminant and its real-subfield square root (n=30, degree 8 -> real degree 4)
    disc_cyc_30 = _cyclotomic_discriminant(30)
    disc_real_30 = sp.sqrt(disc_cyc_30)
    if not disc_real_30.is_Integer:
        raise RuntimeError("Expected Disc(Q(zeta_30)) to be a perfect square for the real subfield.")
    disc_real_30 = sp.Integer(disc_real_30)
    disc_cyc_fac = _factorint_abs(disc_cyc_30)
    disc_real_fac = _factorint_abs(disc_real_30)

    # t_{E8} as a rational function of r_{E8} on the A4(t) Perron curve
    t_of_I = sp.simplify((x**5 - 2 * x**4 - 2 * x + 2) / (x**3))
    t_e8_alg = sp.simplify(t_of_I.subs(x, r_e8))
    poly_t_expr = sp.minimal_polynomial(t_e8_alg, t)
    poly_t = _poly_primitive_integer(poly_t_expr, t)
    disc_t = sp.Integer(sp.discriminant(poly_t.as_expr(), t))
    disc_t_fac = _factorint_abs(disc_t)

    # Index decomposition: Disc(Z[t_{E8}]) = Disc(K_{E8}) * index^2
    ratio = sp.Integer(disc_t // disc_real_30)
    if disc_t % disc_real_30 != 0:
        raise RuntimeError("Disc(P_{E8}) is not divisible by Disc(K_{E8}); unexpected.")
    index_val = sp.sqrt(ratio)
    index_ok = bool(index_val.is_Integer)
    if not index_ok:
        raise RuntimeError("Expected discriminant ratio to be a perfect square (integral index).")
    index_val = sp.Integer(index_val)
    index_fac = _factorint_abs(index_val)

    # Numeric anchors
    r_e8_num = mp.mpf(str(sp.N(r_e8, dps)))
    t_e8_num = mp.mpf(str(sp.N(t_e8_alg, dps)))

    # Symmetric sums from coefficients (monic quartic)
    coeffs_desc = [int(c) for c in poly_x.all_coeffs()]
    c3, c2, c1, c0 = coeffs_desc[1], coeffs_desc[2], coeffs_desc[3], coeffs_desc[4]
    s1, s2, s3, s4 = -c3, c2, -c1, c0

    payload = Payload(
        dps=dps,
        poly_x_coeffs_desc=coeffs_desc,
        disc_poly_x=str(int(disc_x)),
        disc_poly_x_factor=disc_x_fac,
        sym_s1_sum=int(s1),
        sym_s2_pair=int(s2),
        sym_s3_triple=int(s3),
        sym_s4_prod=int(s4),
        disc_cyclo_30=str(int(disc_cyc_30)),
        disc_cyclo_30_factor=disc_cyc_fac,
        disc_real_30=str(int(disc_real_30)),
        disc_real_30_factor=disc_real_fac,
        poly_t_coeffs_desc=[int(c) for c in poly_t.all_coeffs()],
        disc_poly_t=str(int(disc_t)),
        disc_poly_t_factor=disc_t_fac,
        index_ok=index_ok,
        index_value=str(int(index_val)),
        index_factor=index_fac,
        r_e8_value=_fmt(r_e8_num, 40),
        t_e8_value=_fmt(t_e8_num, 40),
    )

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[E8-square-spectrum] wrote {jout}", flush=True)

    _write_tex(
        Path(args.tex_out),
        poly_x=poly_x,
        disc_x=disc_x,
        disc_x_fac=disc_x_fac,
        disc_cyc=disc_cyc_30,
        disc_cyc_fac=disc_cyc_fac,
        disc_real=disc_real_30,
        disc_real_fac=disc_real_fac,
        poly_t=poly_t,
        disc_t=disc_t,
        disc_t_fac=disc_t_fac,
        index_val=index_val,
        index_fac=index_fac,
        r_e8=r_e8_num,
        t_e8=t_e8_num,
    )
    print(f"[E8-square-spectrum] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

