#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Zero-temperature scales table for the 9/13/21-local parallel-addition kernels.

We turn the appendix definitions into an auditable, script-generated table:

  - delta_digits: online delay in digit units
  - lambda0: PF root of the carry-free adjacency A0 = M(0)
  - c1: linear-response coefficient in lambda(u)=lambda0+c1 u+O(u^2)
  - chi0 := c1/lambda0  (dimensionless zero-temp response slope)
  - h0 := log lambda0   (carry-free skeleton entropy rate)
  - Xi := chi0/h0       (normalized 2D fingerprint)

Numerically, (lambda0, c1) are recovered directly from the compiled single-flow
state graph (BFS JSON) via PF eigenvectors:

  c1 = (ell^T A1 r) / (ell^T r),

where r, ell are the right/left PF eigenvectors of A0, and A1 is the kappa=1
edge block in the expansion M(u)=A0+uA1+u^2 A2+....

Outputs:
  - artifacts/export/parallel_addition_kernels_zero_temp_scales.json
  - sections/generated/tab_parallel_addition_kernels_zero_temp_scales.tex

All stdout is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

import numpy as np

from common_paths import export_dir, generated_dir


def _phi() -> float:
    return (1.0 + math.sqrt(5.0)) / 2.0


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _kernel_tex_name(name: str) -> str:
    if "9-local" in name:
        return r"$K_{9}$"
    if "13-local" in name:
        return r"$K_{13}$"
    if "21-local" in name:
        return r"$K_{21}$"
    return name.replace("_", r"\_")


def _delta_flow_from_name(name: str) -> int:
    # Matches the appendix + exp_parallel_addition_kernels_bfs.py convention.
    if "9-local" in name:
        return 1
    if "13-local" in name:
        return 3
    if "21-local" in name:
        return 5
    raise ValueError(f"unknown kernel name for delta_flow: {name}")


def _pf_eigenpair_sparse(
    *,
    n: int,
    src: np.ndarray,
    dst: np.ndarray,
    transpose: bool,
    itmax: int = 20000,
    tol: float = 1e-13,
) -> Tuple[float, np.ndarray]:
    """
    Power iteration for a nonnegative sparse adjacency given by (src,dst) edges.

    We interpret the weighted adjacency as:
      M_{i,j} = #{edges i->j}.

    - transpose=False multiplies by M:   y[i] += x[j] over edges i->j.
    - transpose=True  multiplies by M^T: y[j] += x[i] over edges i->j.

    Returns (lambda, v) where v is L1-normalized (sum(v)=1).
    """
    if n <= 0:
        return 0.0, np.zeros(0, dtype=float)

    x = np.full(n, 1.0 / float(n), dtype=float)
    y = np.empty_like(x)
    lam = 0.0

    if transpose:
        def mul(x_in: np.ndarray, y_out: np.ndarray) -> None:
            y_out.fill(0.0)
            np.add.at(y_out, dst, x_in[src])
    else:
        def mul(x_in: np.ndarray, y_out: np.ndarray) -> None:
            y_out.fill(0.0)
            np.add.at(y_out, src, x_in[dst])

    for it in range(1, itmax + 1):
        mul(x, y)
        s = float(np.sum(y))
        if not (s > 0.0):
            return 0.0, x
        y *= 1.0 / s
        lam_new = s
        if it > 80 and abs(lam_new - lam) / max(1.0, abs(lam_new)) < tol:
            return float(lam_new), y.copy()
        lam = lam_new
        x, y = y, x
    return float(lam), x


def _mul_edges_M(
    *,
    n: int,
    src: np.ndarray,
    dst: np.ndarray,
    x: np.ndarray,
    out: np.ndarray,
) -> None:
    """out = M x with M_{i,j}=#{edges i->j}."""
    out.fill(0.0)
    np.add.at(out, src, x[dst])


@dataclass(frozen=True)
class Row:
    kernel: str
    delta_digits: int
    lambda0: float
    c1: float
    chi0: float
    h0: float
    Xi: float


def _write_tex(path: Path, rows: Sequence[Row]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_parallel_addition_kernels_zero_temp_scales.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{Zero-temperature resource point for the $9/13/21$-local kernels. "
        "We report $(\\delta_{\\mathrm{digits}},h_0,\\chi_0)$ with "
        "$h_0=\\log\\lambda_0$, $\\chi_0=c_1/\\lambda_0$, and $\\Xi=\\chi_0/h_0$. "
        "Here $\\lambda_0=\\rho(A_0)$ is the carry-free PF root and "
        "$c_1=(\\ell^\\mathsf{T}A_1 r)/(\\ell^\\mathsf{T}r)$ is the linear-response "
        "coefficient extracted from the BFS-compiled single-flow graph.}"
    )
    lines.append("\\label{tab:parallel-addition-kernels-zero-temp-scales}")
    lines.append("\\begin{tabular}{l r r r r r r}")
    lines.append("\\toprule")
    lines.append("kernel & $\\delta_{\\mathrm{digits}}$ & $\\lambda_0$ & $c_1$ & $\\chi_0$ & $h_0$ & $\\Xi$\\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.kernel} & {r.delta_digits} & {_fmt(r.lambda0)} & {_fmt(r.c1)}"
            f" & {_fmt(r.chi0)} & {_fmt(r.h0)} & {_fmt(r.Xi)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute (delta_digits,h0,chi0,Xi) for 9/13/21-local kernels.")
    ap.add_argument(
        "--in-json",
        type=str,
        default=str(export_dir() / "parallel_addition_kernels_bfs.json"),
        help="Input BFS JSON from exp_parallel_addition_kernels_bfs.py",
    )
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "parallel_addition_kernels_zero_temp_scales.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_parallel_addition_kernels_zero_temp_scales.tex"),
    )
    args = ap.parse_args()

    in_path = Path(args.in_json)
    payload = json.loads(in_path.read_text(encoding="utf-8"))
    kernels = payload.get("kernels", [])
    if not isinstance(kernels, list) or not kernels:
        raise SystemExit(f"[zero-temp] missing/empty kernels in {in_path}")

    rows: List[Row] = []
    details: Dict[str, Any] = {"meta": {"script": Path(__file__).name, "in_json": str(in_path)}, "rows": []}

    for k in kernels:
        if not isinstance(k, dict):
            continue
        name = str(k.get("name", ""))
        if not name:
            continue
        n_states = int(k["states_reachable"])
        block_size = int(k["block_size"])

        edges = k.get("edges", [])
        if not isinstance(edges, list) or not edges:
            raise SystemExit(f"[zero-temp] missing/empty edges for kernel {name}")

        # Parse edges: [src, dst, kappa_A, kappa_B]
        e_arr = np.asarray(edges, dtype=np.int64)
        src_all = e_arr[:, 0]
        dst_all = e_arr[:, 1]
        kappa_all = e_arr[:, 2] + e_arr[:, 3]

        # A0: kappa=0, A1: kappa=1.
        mask0 = kappa_all == 0
        mask1 = kappa_all == 1
        src0 = src_all[mask0]
        dst0 = dst_all[mask0]
        src1 = src_all[mask1]
        dst1 = dst_all[mask1]

        lam0_r, r = _pf_eigenpair_sparse(n=n_states, src=src0, dst=dst0, transpose=False)
        lam0_l, ell = _pf_eigenpair_sparse(n=n_states, src=src0, dst=dst0, transpose=True)
        lam0 = 0.5 * (lam0_r + lam0_l)

        # c1 = (ell^T A1 r) / (ell^T r)
        tmp = np.empty_like(r)
        _mul_edges_M(n=n_states, src=src1, dst=dst1, x=r, out=tmp)
        num = float(np.dot(ell, tmp))
        den = float(np.dot(ell, r))
        c1 = float("nan") if den == 0.0 else (num / den)

        chi0 = float("nan") if not (lam0 > 0.0) else (c1 / lam0)
        h0 = float("nan") if not (lam0 > 0.0) else float(math.log(lam0))
        Xi = float("nan") if not (h0 != 0.0 and math.isfinite(h0)) else (chi0 / h0)

        delta_digits = int(block_size * _delta_flow_from_name(name))

        row = Row(
            kernel=_kernel_tex_name(name),
            delta_digits=delta_digits,
            lambda0=float(lam0),
            c1=float(c1),
            chi0=float(chi0),
            h0=float(h0),
            Xi=float(Xi),
        )
        rows.append(row)

        details["rows"].append(
            {
                "name": name,
                "delta_digits": delta_digits,
                "lambda0_r": float(lam0_r),
                "lambda0_l": float(lam0_l),
                "lambda0_mean": float(lam0),
                "c1": float(c1),
                "chi0": float(chi0),
                "h0": float(h0),
                "Xi": float(Xi),
                "n_states": n_states,
                "n_edges_kappa0": int(src0.shape[0]),
                "n_edges_kappa1": int(src1.shape[0]),
            }
        )

        print(
            f"[zero-temp] {name}: delta_digits={delta_digits} lambda0~{lam0:.12f} c1~{c1:.12f} chi0~{chi0:.12f}",
            flush=True,
        )

    if not rows:
        raise SystemExit("[zero-temp] no kernels processed")

    # Stable ordering: K9, K13, K21.
    order = {"$K_{9}$": 0, "$K_{13}$": 1, "$K_{21}$": 2}
    rows.sort(key=lambda r: order.get(r.kernel, 99))

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(details, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[zero-temp] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, rows)
    print(f"[zero-temp] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

