#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: pi_1 torsion exponent for Aut(C[R_m^{bin}])^0 at m=4.

All code is English-only by repository convention.

We work with the dyadic (binary-interval) fold at m=4:
  Fold^{bin}_4 : {0,...,15} -> X_4,
defined by Zeckendorf digits (c_k) in Fibonacci weights N = sum_{k>=1} c_k F_{k+1}
and the prefix truncation pi_4(c_1,...)= (c_1,...,c_4).

For w in X_4, define the fiber degeneracy
  d^{bin}_4(w) := |Fold^{bin}_4{}^{-1}(w)|.

Then Aut(C[R_4^{bin}])^0 ≅ ∏_{w in X_4} PU(d^{bin}_4(w)), hence
  pi_1 ≅ ∏_{w in X_4} Z/d^{bin}_4(w)Z
and the torsion exponent equals lcm_w d^{bin}_4(w).

Outputs:
  - artifacts/export/foldbin4_groupoid_aut_pi1_torsion_exponent.json
  - sections/generated/eq_foldbin4_groupoid_aut_pi1_torsion_exponent.tex
"""

from __future__ import annotations

import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str, zeckendorf_digits


def _K_of_limit(limit: int) -> int:
    """Unique K with F_{K+1} <= limit < F_{K+2} (F_1=F_2=1)."""
    if limit < 0:
        raise ValueError("limit must be non-negative")
    fib = [1, 1]
    while fib[-1] <= limit:
        fib.append(fib[-1] + fib[-2])
    return len(fib) - 2


def _fold_bin_prefix_word(N: int, m: int) -> str:
    """Compute Fold^{bin}_m(N) = prefix_m(Zeckendorf(N)) as an m-bit string."""
    limit = (1 << m) - 1
    if not (0 <= N <= limit):
        raise ValueError(f"N must be in [0,{limit}] for m={m}")
    K = _K_of_limit(limit)
    digits = zeckendorf_digits(N, K)  # c_1..c_K
    return word_to_str(digits[:m])


def _lcm(a: int, b: int) -> int:
    if a == 0 or b == 0:
        return 0
    return abs(a // math.gcd(a, b) * b)


def main() -> None:
    m = 4
    domain = list(range(0, (1 << m)))

    fibers: Dict[str, List[int]] = defaultdict(list)
    for N in domain:
        w = _fold_bin_prefix_word(N, m)
        fibers[w].append(N)

    fiber_sizes = {w: len(pre) for w, pre in fibers.items()}
    hist = Counter(fiber_sizes.values())  # d -> #{w}

    exp_pi1 = 1
    for d in sorted(hist.keys()):
        exp_pi1 = _lcm(exp_pi1, int(d))

    payload = {
        "m": int(m),
        "domain_size": int(1 << m),
        "X_size": int(len(fibers)),
        "fiber_histogram_d_to_count": {str(d): int(c) for d, c in sorted(hist.items())},
        "pi1_torsion_exponent": int(exp_pi1),
    }

    json_out = export_dir() / "foldbin4_groupoid_aut_pi1_torsion_exponent.json"
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = generated_dir() / "eq_foldbin4_groupoid_aut_pi1_torsion_exponent.tex"
    tex_out.parent.mkdir(parents=True, exist_ok=True)

    hist_tex = ",\\ ".join([f"{d}:{c}" for d, c in sorted(hist.items())])
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_foldbin4_groupoid_aut_pi1_torsion_exponent.py")
    lines.append("\\begin{equation}\\label{eq:foldbin4_groupoid_aut_pi1_torsion_exponent}")
    lines.append("\\begin{aligned}")
    lines.append(f"\\#\\{{d^{{\\mathrm{{bin}}}}_4=d\\}}&:\\quad {hist_tex},\\\\")
    lines.append(
        "\\exp\\bigl(\\pi_1(\\mathrm{Aut}(\\CC[\\mathcal{R}_4^{\\mathrm{bin}}])^0)\\bigr)"
        f"&=\\operatorname{{lcm}}\\{{d^{{\\mathrm{{bin}}}}_4(w):\\ w\\in X_4\\}}={exp_pi1}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")
    tex_out.write_text("\n".join(lines), encoding="utf-8")

    print(f"File: {json_out.relative_to(json_out.parents[2])}")
    print(f"File: {tex_out.relative_to(tex_out.parents[2])}")


if __name__ == "__main__":
    main()

