#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Hypercube separation inside the fibers of Fold^{bin}_6 ∘ int_6.

All code is English-only by repository convention.

We view Omega_6={0,1}^6 with the hypercube graph Q_6 (Hamming distance 1).
Define the label map
  F6(omega) := Fold^{bin}_6(int_6(omega)) ∈ X6,
where Fold^{bin}_6 is the Zeckendorf-prefix fold on the binary interval {0,...,63}.

For each stable type w ∈ X6 we compute:
  - the fiber size |F6^{-1}(w)| = d^{bin}_6(w),
  - the minimal Hamming distance among distinct vertices in the fiber,
    δ_min(w) := min{Ham(x,y) : x≠y, x,y ∈ F6^{-1}(w)}.

Outputs:
  - artifacts/export/foldbin6_fiber_hamming_min_distance.json
  - sections/generated/eq_foldbin6_fiber_hamming_min_distance_value_counts.tex
  - sections/generated/tab_foldbin6_fiber_hamming_min_distance.tex
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str, zeckendorf_digits


Bits6 = Tuple[int, int, int, int, int, int]


def _bits6(n: int) -> Bits6:
    if n < 0 or n >= 64:
        raise ValueError("n must be in [0,63]")
    return (
        (n >> 5) & 1,
        (n >> 4) & 1,
        (n >> 3) & 1,
        (n >> 2) & 1,
        (n >> 1) & 1,
        (n >> 0) & 1,
    )


def _ham(a: Bits6, b: Bits6) -> int:
    return int(sum(int(x != y) for x, y in zip(a, b)))


def _foldbin6_label(n: int) -> str:
    # For m=6, K(6)=9 (F_{10}=55 ≤ 63 < F_{11}=89), so digits up to k=9 are exact.
    digits = zeckendorf_digits(n, 9)  # digits for weights F_{k+1}, k=1..9
    return word_to_str(digits[:6])


def _fmt_int_set(xs: List[int]) -> str:
    inner = ", ".join(str(x) for x in xs)
    return f"$\\{{{inner}\\}}$"


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute fiber-wise minimal Hamming distance for Fold^{bin}_6 ∘ int_6.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "foldbin6_fiber_hamming_min_distance.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-tab-out",
        type=str,
        default=str(generated_dir() / "tab_foldbin6_fiber_hamming_min_distance.tex"),
        help="Path to generated TeX table snippet (\\input{}).",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_foldbin6_fiber_hamming_min_distance_value_counts.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    args = ap.parse_args()

    # Group fibers by stable label.
    fibers: Dict[str, List[int]] = defaultdict(list)
    for n in range(64):
        fibers[_foldbin6_label(n)].append(n)

    rows: List[Dict[str, object]] = []
    delta_values: Dict[int, int] = {}
    for w in sorted(fibers.keys()):
        ns = sorted(fibers[w])
        pts = [_bits6(n) for n in ns]
        d = len(ns)
        if d <= 1:
            raise RuntimeError("Unexpected singleton fiber at m=6 under Fold^{bin}_6.")

        delta_min = 99
        argmin_pairs: List[Tuple[int, int]] = []
        for i in range(d):
            for j in range(i + 1, d):
                dm = _ham(pts[i], pts[j])
                if dm < delta_min:
                    delta_min = dm
                    argmin_pairs = [(ns[i], ns[j])]
                elif dm == delta_min:
                    argmin_pairs.append((ns[i], ns[j]))

        delta_values[int(delta_min)] = delta_values.get(int(delta_min), 0) + 1
        rows.append(
            {
                "w": w,
                "fiber_size": d,
                "delta_min": int(delta_min),
                "preimage_ints": ns,
                "argmin_pairs_ints": argmin_pairs,
            }
        )

    payload: Dict[str, object] = {
        "m": 6,
        "domain_size": 64,
        "codomain_size": len(fibers),
        "delta_min_value_counts": {str(k): int(v) for k, v in sorted(delta_values.items())},
        "rows": rows,
    }

    # Write JSON audit.
    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # Write TeX table.
    tab_out = Path(str(args.tex_tab_out))
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_foldbin6_fiber_hamming_min_distance.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{7pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.10}")
    lines.append(
        "\\caption{Hypercube separation inside the fibers of $F_6(\\omega)=\\mathrm{Fold}^{\\mathrm{bin}}_6(\\mathrm{int}_6(\\omega))$: "
        "for each $w\\in X_6$ we list the preimage integers $\\{n\\in\\{0,\\dots,63\\}:\\ \\mathrm{Fold}^{\\mathrm{bin}}_6(n)=w\\}$, "
        "the fiber size $d^{\\mathrm{bin}}_6(w)$, and the minimal internal Hamming distance "
        "$\\delta_{\\min}(w)=\\min\\{\\mathrm{Ham}(x,y):x\\ne y,\\ x,y\\in F_6^{-1}(w)\\}$.}"
    )
    lines.append("\\label{tab:foldbin6_fiber_hamming_min_distance}")
    lines.append("\\begin{tabular}{l r r l}")
    lines.append("\\toprule")
    lines.append("$w\\in X_6$ & $d^{\\mathrm{bin}}_6(w)$ & $\\delta_{\\min}(w)$ & $\\{n: \\mathrm{Fold}^{\\mathrm{bin}}_6(n)=w\\}$\\\\")
    lines.append("\\midrule")
    for r in rows:
        w = str(r["w"])
        d = int(r["fiber_size"])
        dm = int(r["delta_min"])
        ns = [int(x) for x in r["preimage_ints"]]  # type: ignore[assignment]
        lines.append(f"\\texttt{{{w}}} & {d} & {dm} & {_fmt_int_set(ns)}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    tab_out.parent.mkdir(parents=True, exist_ok=True)
    tab_out.write_text("\n".join(lines), encoding="utf-8")

    # Write TeX equation snippet (value counts).
    eq_out = Path(str(args.tex_eq_out))
    eq_lines: List[str] = []
    eq_lines.append("% AUTO-GENERATED by scripts/exp_foldbin6_fiber_hamming_min_distance.py")
    eq_lines.append("\\begin{equation}\\label{eq:foldbin6_fiber_hamming_min_distance_value_counts}")
    eq_lines.append("\\begin{aligned}")
    for dm in sorted(delta_values.keys()):
        eq_lines.append(f"\\#\\{{w\\in X_6:\\ \\delta_{{\\min}}(w)={dm}\\}}&={delta_values[dm]},\\\\")
    # Replace trailing comma with period.
    if eq_lines[-1].endswith(",\\\\"):
        eq_lines[-1] = eq_lines[-1][:-3] + "."
    eq_lines.append("\\end{aligned}")
    eq_lines.append("\\end{equation}")
    eq_lines.append("")
    eq_out.parent.mkdir(parents=True, exist_ok=True)
    eq_out.write_text("\n".join(eq_lines), encoding="utf-8")


if __name__ == "__main__":
    main()

