#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Cross-scale complement identity: Fold^{bin}_m vs. Fold max fiber D_{2m-2}.

This script is intentionally *derived-only*: it consumes the already reproducible,
enumerated bin-fold degeneracy-spectrum output (m in {6,8,10,12}) and computes a
cross-check against the closed-form max-fiber law for Fold.

Identity (audited on the listed m):
  |X_m \\setminus S_{m,d_min}| = |X_m| - |S_{m,d_min}| = D_{2m-2},
where S_{m,d} := { w in X_m : d^{bin}_m(w)=d }.

Inputs:
  - artifacts/export/fold_bin_degeneracy_spectrum_m6_m12.json

Outputs:
  - artifacts/export/foldbin_fold_complement_identity_m6_m12.json
  - sections/generated/eq_foldbin_fold_complement_identity_m6_m12.tex

All code is English-only by repository convention.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from common_paths import export_dir, generated_dir
from common_phi_fold import fib_upto


def _fold_max_fiber_closed_form(m: int) -> int:
    """Closed-form max fiber D_m for Fold_m, per Theorem 'max-fiber closed form'.

    Convention: Fibonacci F_1=F_2=1.
      - D_{2k}   = F_{k+2}
      - D_{2k+1} = 2 F_{k+1}
    """
    if m <= 0:
        raise ValueError("m must be positive")
    if m % 2 == 0:
        k = m // 2
        return int(fib_upto(k + 2)[-1])
    k = (m - 1) // 2
    return int(2 * fib_upto(k + 1)[-1])


def _load_rows(path: Path) -> List[Dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = data.get("rows")
    if not isinstance(rows, list):
        raise ValueError("unexpected JSON schema: expected dict with key 'rows' as list")
    return rows


def _write_tex(out_path: Path, rows: List[Dict[str, Any]]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_foldbin_fold_complement_identity_m6_m12.py")
    lines.append("\\begin{equation}\\label{eq:foldbin_fold_complement_identity_m6_m12}")
    lines.append("\\begin{aligned}")
    for i, r in enumerate(rows):
        m = int(r["m"])
        X = int(r["X_size"])
        d_min = int(r["d_min"])
        count_min = int(r["count_min"])
        comp = int(r["complement_size"])
        D = int(r["D_2m_minus_2"])
        idx = int(r["index_2m_minus_2"])
        tail = "\\\\" if i != len(rows) - 1 else ""
        lines.append(
            f"\\card{{X_{{{m}}}}}-\\card{{\\mathcal{{S}}_{{{m},{d_min}}}}}"
            f"&= {X}-{count_min} = {comp} = D_{{{idx}}} ({D}){tail}"
        )
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    jin = export_dir() / "fold_bin_degeneracy_spectrum_m6_m12.json"
    if not jin.exists():
        raise SystemExit(f"Missing input JSON: {jin}. Run exp_fold_bin_degeneracy_spectrum_m6_m12.py first.")

    rows_in = _load_rows(jin)
    rows_out: List[Dict[str, Any]] = []
    for r in rows_in:
        m = int(r["m"])
        X = int(r["X_size"])
        d_min = int(r["d_min"])
        count_min = int(r["count_min"])
        comp = int(X - count_min)
        idx = int(2 * m - 2)
        D = _fold_max_fiber_closed_form(idx)
        rows_out.append(
            {
                "m": m,
                "X_size": X,
                "d_min": d_min,
                "count_min": count_min,
                "complement_size": comp,
                "index_2m_minus_2": idx,
                "D_2m_minus_2": int(D),
                "holds": bool(comp == D),
            }
        )

    payload = {
        "input_json": str(jin),
        "rows": rows_out,
        "all_hold": bool(all(bool(rr["holds"]) for rr in rows_out)),
    }

    jout = export_dir() / "foldbin_fold_complement_identity_m6_m12.json"
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[foldbin-fold-complement] wrote {jout}", flush=True)

    tex_out = generated_dir() / "eq_foldbin_fold_complement_identity_m6_m12.tex"
    _write_tex(tex_out, rows_out)
    print(f"[foldbin-fold-complement] wrote {tex_out}", flush=True)


if __name__ == "__main__":
    main()

