#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit: rational reduction u=R(mu), congruence with Tschirnhaus, and b*-minpoly.

This script is English-only by repository convention.
"""

from __future__ import annotations

import json
import time
import warnings
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

import sympy as sp
from sympy.utilities.exceptions import SymPyDeprecationWarning

from common_paths import export_dir, generated_dir


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> None:
    warnings.filterwarnings("ignore", category=SymPyDeprecationWarning)

    t0 = time.time()
    print("[fold-gauge-anomaly-branchpoint-rational-b] start", flush=True)

    mu, u, b = sp.symbols("mu u b")

    # Must match the paper (and exp_fold_gauge_anomaly_branch_points.py).
    F = mu**4 - mu**3 - (2 * u + 1) * mu**2 + (2 * u - u**3) * mu + 2 * u
    F_mu = sp.diff(F, mu)

    # Rational reduction derived from F - mu*F_mu = 0.
    R = sp.simplify(mu**2 * (3 * mu**2 - 2 * mu - 1) / (2 * (mu**2 + 1)))
    elim_identity = sp.simplify(2 * u * (mu**2 + 1) - mu**2 * (3 * mu**2 - 2 * mu - 1))

    # Verify: (F=0, F_mu=0) => elim_identity=0 by Groebner reduction.
    G = sp.groebner([F, F_mu], [u, mu], order="lex", domain=sp.QQ)
    _q, red = G.reduce(elim_identity)
    assert sp.simplify(red) == 0

    # Q10 and Tschirnhaus T(mu) from the manuscript.
    Q10 = (
        27 * mu**10
        - 81 * mu**9
        + 90 * mu**8
        - 46 * mu**7
        + 11 * mu**6
        - mu**5
        - 32 * mu**4
        + 32 * mu**3
        + 16 * mu
        + 16
    )
    T = sp.Rational(1, 200) * (
        -189 * mu**9
        + 540 * mu**8
        - 360 * mu**7
        - 308 * mu**6
        + 329 * mu**5
        + 304 * mu**4
        - 104 * mu**3
        - 196 * mu**2
        - 128 * mu
        - 16
    )

    congr = sp.simplify((R - T) - (7 * mu + 1) * Q10 / (200 * (mu**2 + 1)))
    assert congr == 0

    # b*(mu,u) = -2 F_u / (F_mumu * mu^2).
    F_u = sp.diff(F, u)
    F_mumu = sp.diff(F, mu, 2)
    b_expr = sp.simplify((-2 * F_u) / (F_mumu * mu**2))

    # Substitute u=R(mu) to get a pure rational function B(mu).
    B_mu = sp.simplify(b_expr.subs(u, R))

    # Eliminate mu between Q10(mu)=0 and b=B(mu) to get minpoly in b.
    num = sp.together(B_mu).as_numer_denom()[0]
    den = sp.together(B_mu).as_numer_denom()[1]
    eq_b = sp.expand(b * den - num)

    Res = sp.resultant(Q10, eq_b, mu)
    Res_poly = sp.Poly(sp.factor(Res), b, domain=sp.ZZ)

    # Remove content / sign normalization.
    _content, prim = Res_poly.primitive()
    if prim.LC() < 0:
        prim = -prim

    # The expected degree-10 polynomial (manuscript).
    expected = sp.Poly(
        316283904 * b**10
        - 52713984 * b**9
        + 379196672 * b**8
        + 406374016 * b**7
        + 670701296 * b**6
        + 1305085464 * b**5
        + 761320448 * b**4
        + 12917152 * b**3
        + 53372880 * b**2
        + 7820550 * b
        - 1303425,
        b,
        domain=sp.ZZ,
    )
    assert prim == expected

    seconds = time.time() - t0

    payload = {
        "meta": {
            "script": Path(__file__).name,
            "seconds": seconds,
        },
        "identities": {
            "F": str(F),
            "R": str(R),
            "Q10": str(Q10),
            "T": str(T),
            "congruence_ok": True,
            "b_expr": str(b_expr),
            "B_mu": str(B_mu),
            "b_minpoly_coeffs_high_to_low": [int(c) for c in expected.all_coeffs()],
        },
    }

    out_json = export_dir() / "fold_gauge_anomaly_branchpoint_rational_b_invariant_audit.json"
    _write_json(out_json, payload)

    tex = r"""% Auto-generated by scripts/exp_fold_gauge_anomaly_branchpoint_rational_b_invariant_audit.py
\begin{align}
u&=\frac{\mu^2(3\mu^2-2\mu-1)}{2(\mu^2+1)},\\
\mathcal R(\mu)-T(\mu)&=\frac{(7\mu+1)\,Q_{10}(\mu)}{200(\mu^2+1)},\\
\mathrm{MinPoly}(b_\ast)&=316283904\, b^{10}-52713984\, b^{9}+379196672\, b^{8}+406374016\, b^{7}
+670701296\, b^{6}+1305085464\, b^{5}+761320448\, b^{4}+12917152\, b^{3}
+53372880\, b^{2}+7820550\, b-1303425.
\end{align}
"""
    out_tex = generated_dir() / "eq_fold_gauge_anomaly_branchpoint_rational_b_invariant_audit.tex"
    _write_text(out_tex, tex)

    print(f"[fold-gauge-anomaly-branchpoint-rational-b] ok seconds={seconds:.3f}", flush=True)


if __name__ == "__main__":
    main()

