#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Window-6 uplift branch lock by family number N_f (Zeckendorf top term).

All code is English-only by repository convention.

Context (manuscript):
  - The window-6 uplift tail admits three nonzero offsets {F8,F9,F10}={21,34,55}.
  - In the manuscript, these top Fibonacci terms align with the top Zeckendorf terms
    of SU(5)/SO(10)/E6 in the Zeckendorf--GUT signature dictionary.

This script adds a small, auditable bridge used in the manuscript prose:
  - Take the standard SU(5) per-family chiral matter count as an external input: 15.
  - For N_f in {2,3,4}, compute M(N_f)=15*N_f and its Zeckendorf decomposition.
  - Record the highest Zeckendorf term and its match to the window-6 tail offsets.
  - Record the window-6 boundary-sector cardinality |X_6^{bdry}|=F4=3 and the
    discrete completion identity 45+3=48=3*16.

Outputs:
  - artifacts/export/window6_family_uplift_lock.json
  - sections/generated/tab_window6_family_uplift_lock.tex
  - sections/generated/eq_window6_family_singlet_completion.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Sequence

from common_paths import export_dir, generated_dir
from common_phi_fold import fib_upto


def _fib_value(k: int) -> int:
    """Return Fibonacci number F_k with F_1=F_2=1 (k>=1)."""
    if k <= 0:
        raise ValueError("k must be >= 1")
    return int(fib_upto(int(k))[-1])


def zeckendorf_decompose(D: int) -> List[int]:
    """Return Zeckendorf indices S such that D = sum_{k in S} F_k (k>=2, no adjacent)."""
    if D < 0:
        raise ValueError("D must be non-negative")
    if D == 0:
        return []

    k_max = 2
    while _fib_value(k_max) < D:
        k_max += 1

    rem = int(D)
    picks: List[int] = []
    k = int(k_max)
    while rem > 0:
        while k >= 2 and _fib_value(k) > rem:
            k -= 1
        if k < 2:
            raise RuntimeError(f"Zeckendorf decomposition failed for D={D} (rem={rem})")
        picks.append(int(k))
        rem -= _fib_value(k)
        k -= 2  # enforce non-adjacent indices

    for a, b in zip(picks, picks[1:]):
        if not (a > b + 1):
            raise RuntimeError(f"Adjacent/unsorted Zeckendorf picks for D={D}: {picks}")
    if sum(_fib_value(kk) for kk in picks) != D:
        raise RuntimeError(f"Bad Zeckendorf sum for D={D}: picks={picks}")
    return picks


def _tex_zeckendorf_sum(D: int, picks: Sequence[int]) -> str:
    parts = "+".join(f"F_{{{int(k)}}}" for k in picks)
    vals = "+".join(str(_fib_value(int(k))) for k in picks)
    return f"{int(D)}={parts}={vals}"


@dataclass(frozen=True)
class Row:
    N_f: int
    M: int
    zeckendorf_indices: List[int]
    zeckendorf_tex: str
    top_index: int
    top_value: int
    uplift_branch: str


def write_outputs(*, json_out: Path, tex_tab: Path, tex_eq: Path) -> None:
    # External input (by convention): 15 chiral matter dof per SU(5) family.
    per_family = 15

    # Window-6 tail offsets and their top-term alignments (manuscript corollary).
    top_term_to_gut = {8: "SU(5)", 9: "SO(10)", 10: "E_6"}

    rows: List[Row] = []
    for Nf in (2, 3, 4):
        M = int(per_family * Nf)
        picks = zeckendorf_decompose(M)
        top_k = int(picks[0])  # picks are descending
        top_v = _fib_value(top_k)
        gut = top_term_to_gut.get(top_k, "?")
        rows.append(
            Row(
                N_f=int(Nf),
                M=int(M),
                zeckendorf_indices=picks,
                zeckendorf_tex=_tex_zeckendorf_sum(M, picks),
                top_index=top_k,
                top_value=int(top_v),
                uplift_branch=f"F_{{{top_k}}}\\ (\\text{{aligns with }}{gut})",
            )
        )

    # Boundary-sector cardinality at m=6: |X_6^{bdry}| = F_{6-2} = F_4 = 3.
    X6_bdry = _fib_value(4)

    payload: Dict[str, object] = {
        "params": {"per_family_SU5_matter_count": per_family, "Nf_list": [2, 3, 4]},
        "rows": [asdict(r) for r in rows],
        "X6_bdry_count": int(X6_bdry),
        "identities": {
            "M3": int(per_family * 3),
            "M3_plus_X6_bdry": int(per_family * 3 + X6_bdry),
            "three_times_16": int(3 * 16),
        },
    }
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # --- LaTeX table fragment ---
    tab_lines: List[str] = []
    tab_lines.append("% AUTO-GENERATED by scripts/exp_window6_family_uplift_lock.py")
    tab_lines.append("\\begin{table}[H]")
    tab_lines.append("\\centering")
    tab_lines.append("\\small")
    tab_lines.append("\\setlength{\\tabcolsep}{8pt}")
    tab_lines.append("\\renewcommand{\\arraystretch}{1.10}")
    tab_lines.append(
        "\\caption{Family-number locking of the window-6 three-branch uplift tail. "
        "Using the standard SU(5) per-family chiral matter count $15$ as an external input, "
        "the totals $M(N_f)=15N_f$ for $N_f\\in\\{2,3,4\\}$ have Zeckendorf top terms "
        "$F_8,F_9,F_{10}$, matching the window-6 uplift-tail offsets and aligning with the "
        "top Zeckendorf terms of $SU(5)/SO(10)/E_6$ in Corollary~\\ref{cor:fold6-tail-offsets-gut-top-terms}.}"
    )
    tab_lines.append("\\label{tab:window6_family_uplift_lock}")
    tab_lines.append("\\begin{tabular}{r r l l l}")
    tab_lines.append("\\toprule")
    tab_lines.append("$N_f$ & $M(N_f)$ & Zeckendorf & top term & uplift branch\\\\")
    tab_lines.append("\\midrule")
    for r in rows:
        top = f"$F_{{{r.top_index}}}={r.top_value}$"
        branch = "$" + r.uplift_branch + "$"
        tab_lines.append(
            f"{r.N_f} & {r.M} & ${r.zeckendorf_tex}$ & {top} & {branch}\\\\"
        )
    tab_lines.append("\\bottomrule")
    tab_lines.append("\\end{tabular}")
    tab_lines.append("\\end{table}")
    tab_lines.append("")
    tex_tab.parent.mkdir(parents=True, exist_ok=True)
    tex_tab.write_text("\n".join(tab_lines), encoding="utf-8")

    # --- LaTeX equation fragment (singlet completion slot identity at m=6) ---
    eq_lines: List[str] = []
    eq_lines.append("% AUTO-GENERATED by scripts/exp_window6_family_uplift_lock.py")
    eq_lines.append("\\begin{equation}\\label{eq:window6_family_singlet_completion}")
    eq_lines.append("\\begin{aligned}")
    eq_lines.append(
        r"|X^{\mathrm{bdry}}_6|&=F_4=3,\\qquad 15\cdot 3+|X^{\mathrm{bdry}}_6|=45+3=48=3\cdot 16,\\"
    )
    eq_lines.append(
        r"15N_f+|X^{\mathrm{bdry}}_6|=16N_f\ &\Longleftrightarrow\ N_f=|X^{\mathrm{bdry}}_6|=3."
    )
    eq_lines.append("\\end{aligned}")
    eq_lines.append("\\end{equation}")
    eq_lines.append("")
    tex_eq.parent.mkdir(parents=True, exist_ok=True)
    tex_eq.write_text("\n".join(eq_lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Window-6 family-number uplift-branch lock (Zeckendorf top term).")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_family_uplift_lock.json"),
    )
    ap.add_argument(
        "--tex-tab",
        type=str,
        default=str(generated_dir() / "tab_window6_family_uplift_lock.tex"),
    )
    ap.add_argument(
        "--tex-eq",
        type=str,
        default=str(generated_dir() / "eq_window6_family_singlet_completion.tex"),
    )
    args = ap.parse_args()
    write_outputs(json_out=Path(args.json_out), tex_tab=Path(args.tex_tab), tex_eq=Path(args.tex_eq))
    print(f"[window6-family-lock] wrote {args.json_out}", flush=True)
    print(f"[window6-family-lock] wrote {args.tex_tab}", flush=True)
    print(f"[window6-family-lock] wrote {args.tex_eq}", flush=True)


if __name__ == "__main__":
    main()

