#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Certified carry-constant decomposition for the real-input-40 Abel constant.

We work at z_* = phi^{-2} and C = (47+21*sqrt(5))/100.

Define the carry constant:
  log M_carry := - sum_{m>=2} mu(m)/m * [ log(1-3 q^m + q^{2m}) + log(1+q^m-q^{2m}) ]
  M = C * q * (1+q)^3 * exp(q^3) * M_carry

We compute truncated sums up to m<=N, and provide a certified tail bound using
the paper's inequality:
  |S3_tail| + |Spm_tail| <= 5 * sum_{m>N} q^m/m <= 5*q^{N+1}/((N+1)(1-q)).

Outputs:
- artifacts/export/real_input_40_carry_constant_certified.json
- sections/generated/eq_real_input_40_carry_constant_certified.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict

import mpmath as mp

from common_paths import export_dir, generated_dir


def mobius(n: int) -> int:
    """Compute Möbius mu(n) via trial division; sufficient for n up to ~1e6."""
    if n == 1:
        return 1
    x = n
    mu = 1
    p = 2
    while p * p <= x:
        if x % p == 0:
            x //= p
            mu = -mu
            if x % p == 0:
                return 0
            while x % p == 0:
                x //= p
        p = 3 if p == 2 else p + 2
    if x > 1:
        mu = -mu
    return mu


def tail_bound(q: mp.mpf, N: int) -> mp.mpf:
    return (5 * q ** (N + 1)) / ((N + 1) * (1 - q))


@dataclass(frozen=True)
class Payload:
    N: int
    dps: int
    z_star: str
    C: str
    log_triv: str
    log_carry: str
    log_M: str
    tail_bound: str


def main() -> None:
    t0 = time.time()
    ap = argparse.ArgumentParser(description="Certified carry constant for real-input-40.")
    ap.add_argument("--N", type=int, default=160, help="Truncation for m>=2 sums.")
    ap.add_argument("--dps", type=int, default=120, help="mpmath decimal precision.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_carry_constant_certified.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_real_input_40_carry_constant_certified.tex"),
    )
    args = ap.parse_args()

    N = int(args.N)
    if N < 20:
        raise SystemExit("Require N>=20 for a meaningful certified bound.")
    mp.mp.dps = int(args.dps)

    phi = (1 + mp.sqrt(5)) / 2
    q = phi ** (-2)  # z_*
    C = (mp.mpf(47) + mp.mpf(21) * mp.sqrt(5)) / 100

    # Trivial closed-form part:
    # log_triv = log C + log q + 3 log(1+q) + q^3
    log_triv = mp.log(C) + mp.log(q) + 3 * mp.log(1 + q) + q**3

    S3 = mp.mpf("0")
    Spm = mp.mpf("0")
    for m in range(2, N + 1):
        mu = mobius(m)
        if mu == 0:
            continue
        t = q**m
        S3 += mp.mpf(mu) * mp.log(1 - 3 * t + t * t) / m
        Spm += mp.mpf(mu) * mp.log(1 + t - t * t) / m
        if m % 25 == 0:
            elapsed = time.time() - t0
            print(f"[carry-const] m={m}/{N} elapsed={elapsed:.1f}s", flush=True)

    log_carry = -(S3 + Spm)
    log_M = log_triv + log_carry
    bd = tail_bound(q, N)

    payload = Payload(
        N=N,
        dps=int(args.dps),
        z_star=str(q),
        C=str(C),
        log_triv=str(log_triv),
        log_carry=str(log_carry),
        log_M=str(log_M),
        tail_bound=str(bd),
    )

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # TeX equation block with certified bound.
    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    # Show ~30-40 digits (readable but meaningful).
    nd = 36
    lines = []
    lines.append("% Generated by scripts/exp_real_input_40_carry_constant_certified.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\log\\mathfrak{M}"
        "=\\log\\Bigl(C\\,z_\\star(1+z_\\star)^3 e^{z_\\star^3}\\Bigr)"
        "+\\log\\mathfrak{M}_{\\mathrm{carry}},"
    )
    lines.append("\\\\")
    lines.append(
        "\\log\\mathfrak{M}_{\\mathrm{carry}}"
        ":=-\\sum_{m\\ge 2}\\frac{\\mu(m)}{m}\\Bigl[\\log(1-3z_\\star^{m}+z_\\star^{2m})+\\log(1+z_\\star^{m}-z_\\star^{2m})\\Bigr]."
    )
    lines.append("\\\\[2pt]")
    lines.append(f"z_\\star=\\varphi^{{-2}},\\quad C=\\frac{{47+21\\sqrt5}}{{100}},\\quad N={N}.")
    lines.append("\\\\")
    lines.append(
        f"\\log\\Bigl(C\\,z_\\star(1+z_\\star)^3 e^{{z_\\star^3}}\\Bigr)\\approx {mp.nstr(log_triv, nd)},"
    )
    lines.append("\\\\")
    lines.append(
        f"\\log\\mathfrak{{M}}_{{\\mathrm{{carry}}}}\\approx {mp.nstr(log_carry, nd)}."
    )
    lines.append("\\\\")
    lines.append(f"\\log\\mathfrak{{M}}\\approx {mp.nstr(log_M, nd)}.")
    lines.append("\\\\[2pt]")
    lines.append(
        f"\\text{{Certified tail bound:}}\\quad"
        f"\\Bigl|\\mathrm{{tail}}(N)\\Bigr|\\le \\frac{{5 z_\\star^{{N+1}}}}{{(N+1)(1-z_\\star)}}\\approx {mp.nstr(bd, 8)}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")

    dt = time.time() - t0
    print(f"[carry-const] wrote {jout} and {tout} in {dt:.2f}s", flush=True)


if __name__ == "__main__":
    main()

