#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Subleading eigenmode phase and intrinsic oscillation scale (real-input 40-state kernel).

We work on the arity-charge slice theta(t)=(t,0,-t). For each t we extract:
- lambda1(t): Perron-Frobenius eigenvalue (largest modulus)
- lambda2(t): a subleading eigenvalue with maximal modulus among the rest
and report its complex phase arg(lambda2).

This phase controls the oscillatory factor in the dominant subleading mode
of time correlations: (lambda2/lambda1)^n = (|lambda2|/lambda1)^n * exp(i n arg(lambda2)).

Outputs:
- artifacts/export/real_input_40_time_correlation_phase.json
- artifacts/export/real_input_40_time_correlation_phase.png
- sections/generated/fig_real_input_40_time_correlation_phase.tex
- sections/generated/tab_real_input_40_time_correlation_phase.tex
"""

from __future__ import annotations

import argparse
import json
import math
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress
from exp_sync_kernel_real_input_40 import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_states,
    build_weighted_matrix,
)


def _principal_arg(z: complex) -> float:
    return float(math.atan2(float(np.imag(z)), float(np.real(z))))


def _pick_leading_and_subleading(eigvals: np.ndarray) -> Tuple[int, int]:
    mags = np.abs(eigvals)
    k1 = int(np.argmax(mags))

    mags2 = mags.copy()
    mags2[k1] = -1.0
    m2 = float(np.max(mags2))
    cand = [i for i, m in enumerate(mags2) if abs(float(m) - m2) <= 1e-12]
    if not cand:
        k2 = int(np.argmax(mags2))
        return k1, k2

    # Prefer a representative with non-negative imaginary part for stability.
    cand_sorted = sorted(
        cand, key=lambda i: (-float(np.imag(eigvals[i])), -float(np.real(eigvals[i])))
    )
    k2 = int(cand_sorted[0])
    return k1, k2


def _fmt_float(x: float, ndp: int = 12) -> str:
    if not math.isfinite(x):
        return "\\infty"
    if x == 0.0:
        return "0"
    ax = abs(x)
    if ax < 1e-4 or ax >= 1e4:
        return f"{x:.6e}"
    return f"{x:.{ndp}f}"


def _write_fig_tex(fig_name: str, png_rel: str, caption: str, label: str) -> None:
    p = generated_dir() / f"{fig_name}.tex"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "\\begin{figure}[H]\n"
        "\\centering\n"
        f"\\includegraphics[width=0.92\\linewidth]{{{png_rel}}}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        "\\end{figure}\n",
        encoding="utf-8",
    )


def _write_table_tex(rows: List[Dict[str, float]]) -> None:
    tex_path = generated_dir() / "tab_real_input_40_time_correlation_phase.tex"
    tex_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_time_correlation_phase.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{真实输入 40 状态核在 $\\chi$ 切片 $\\theta(t)=(t,0,-t)$ 下的次主模态相位读出。"
        "记 $\\lambda_1(t)$ 为 Perron--Frobenius 主特征值，$\\lambda_2(t)$ 为其余谱中模最大的特征值之一，"
        "并令 $\\rho_2(t)=|\\lambda_2(t)|/\\lambda_1(t)$，$\\omega(t)=\\arg(\\lambda_2(t))$（主辐角）。"
        "若 $\\omega(t)\\ne 0$，则由 $(\\lambda_2/\\lambda_1)^n$ 的因子可定义内生振荡周期 $T_{\\mathrm{osc}}(t)=2\\pi/|\\omega(t)|$。}"
    )
    lines.append("\\label{tab:real-input-40-time-corr-phase}")
    lines.append("\\begin{tabular}{r r r r r r}")
    lines.append("\\toprule")
    lines.append(
        " $t$ & $\\lambda_1$ & $\\Re\\lambda_2$ & $\\Im\\lambda_2$ & $\\rho_2$ & $T_{\\mathrm{osc}}$\\\\"
    )
    lines.append("\\midrule")
    for row in rows:
        t = float(row["t"])
        lam1 = float(row["lambda1"])
        r2 = float(row["rho2"])
        re2 = float(row["lambda2_re"])
        im2 = float(row["lambda2_im"])
        Tosc = float(row["Tosc"])
        lines.append(
            f"{_fmt_float(t, ndp=3)} & {_fmt_float(lam1)} & {_fmt_float(re2)} & {_fmt_float(im2)} & {_fmt_float(r2)} & {_fmt_float(Tosc, ndp=6)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    tex_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Subleading eigenmode phase for real-input 40-state kernel (chi slice)"
    )
    parser.add_argument("--t-min", type=float, default=-1.0)
    parser.add_argument("--t-max", type=float, default=1.0)
    parser.add_argument("--t-steps", type=int, default=61)
    parser.add_argument("--table-ts", type=str, default="-1,-0.5,0,0.5,1")
    parser.add_argument("--no-output", action="store_true")
    args = parser.parse_args()

    prog = Progress(label="real-input-40-time-corr-phase", every_seconds=20.0)
    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()

    ts = (
        [0.0]
        if args.t_steps <= 1
        else [
            args.t_min + (args.t_max - args.t_min) * i / float(args.t_steps - 1)
            for i in range(args.t_steps)
        ]
    )

    grid: List[Dict[str, float]] = []
    for t in ts:
        B = build_weighted_matrix(
            theta_e=t, theta_neg=0.0, theta_2=-t, states=states, kernel_map=kernel_map
        )
        eigvals = np.linalg.eigvals(B)
        k1, k2 = _pick_leading_and_subleading(eigvals)
        lam1 = float(np.real(eigvals[k1]))
        lam2 = complex(eigvals[k2])
        lam2_abs = float(abs(lam2))
        rho2 = float(lam2_abs / lam1) if lam1 > 0.0 else 0.0
        rho2 = min(max(rho2, 0.0), 1.0)
        omega = float(_principal_arg(lam2))
        Tosc = (
            float(2.0 * math.pi / abs(omega))
            if math.isfinite(omega) and abs(omega) > 0.0
            else float("inf")
        )
        grid.append(
            {
                "t": float(t),
                "lambda1": float(lam1),
                "lambda2_re": float(np.real(lam2)),
                "lambda2_im": float(np.imag(lam2)),
                "lambda2_abs": float(lam2_abs),
                "rho2": float(rho2),
                "omega": float(omega),
                "Tosc": float(Tosc),
            }
        )
        prog.tick(f"grid t={t:.4g}")

    table_ts: List[float] = []
    for s in str(args.table_ts).split(","):
        s = s.strip()
        if not s:
            continue
        table_ts.append(float(s))
    if not table_ts:
        table_ts = [-1.0, -0.5, 0.0, 0.5, 1.0]

    # Nearest-neighbor sampling from the computed grid.
    grid_ts = [float(x["t"]) for x in grid]
    table_rows: List[Dict[str, float]] = []
    for t in table_ts:
        j = int(np.argmin([abs(gt - t) for gt in grid_ts]))
        row = dict(grid[j])
        row["t"] = float(t)
        table_rows.append(row)

    out_png = export_dir() / "real_input_40_time_correlation_phase.png"
    out_json = export_dir() / "real_input_40_time_correlation_phase.json"

    fig, ax = plt.subplots(1, 2, figsize=(10.8, 4.2))
    ax[0].plot([g["t"] for g in grid], [g["rho2"] for g in grid], lw=2.0)
    ax[0].set_xlabel(r"$t$")
    ax[0].set_ylabel(r"$\rho_2(t)=|\lambda_2|/\lambda_1$")
    ax[0].set_title("subleading modulus ratio")
    ax[0].grid(True, alpha=0.3)

    ax[1].plot([g["t"] for g in grid], [g["omega"] / math.pi for g in grid], lw=2.0)
    ax[1].set_xlabel(r"$t$")
    ax[1].set_ylabel(r"$\omega(t)/\pi$ (principal)")
    ax[1].set_title("subleading phase")
    ax[1].grid(True, alpha=0.3)

    plt.tight_layout()
    if not args.no_output:
        out_png.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_png, dpi=160)
    plt.close(fig)

    payload: Dict[str, object] = {
        "model": "real_input_40",
        "slice": "chi",
        "theta_map": "theta(t)=(t,0,-t)",
        "grid": grid,
        "table": {"t": table_ts, "rows": table_rows},
    }
    if not args.no_output:
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        _write_table_tex(table_rows)
        _write_fig_tex(
            fig_name="fig_real_input_40_time_correlation_phase",
            png_rel="artifacts/export/real_input_40_time_correlation_phase.png",
            caption=(
                "真实输入 40 状态核在 $\\chi$ 切片 $\\theta(t)=(t,0,-t)$ 下的次主模态读出："
                "左为 $\\rho_2(t)=|\\lambda_2|/\\lambda_1$；右为 $\\omega(t)=\\arg(\\lambda_2(t))$（主辐角，以 $\\pi$ 归一）。"
                "该相位决定相关函数中主导次主项的振荡因子 $\\exp(i n\\omega(t))$，从而给出内生振荡尺度。"
            ),
            label="fig:real-input-40-time-correlation-phase",
        )

    print(f"[real-input-40-time-corr-phase] wrote {out_json}", flush=True)
    print(f"[real-input-40-time-corr-phase] wrote {out_png}", flush=True)
    print("[real-input-40-time-corr-phase] done", flush=True)


if __name__ == "__main__":
    main()
