#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Monte Carlo audit for the k-step fold gauge-anomaly invariance.

This script is English-only by repository convention.

For fixed k>=1 and m>=1, we sample omega ~ Unif(Omega_{m+k}) = {0,1}^{m+k} and compute:

  G_m^{(k)}(omega) := | r_{m+k->m}(omega) XOR r~_{m+k->m}(omega) |_0,

where:
- r_{m+k->m}(omega) is the naive truncation prefix omega_1..omega_m,
- r~_{m+k->m}(omega) is the fold-aware restriction prefix:
    r~_{m+k->m}(omega) := pi_{m+k->m}(Fold_{m+k}(omega)).

We report:
- mean density  E[G_m^{(k)}]/m  (target 4/9),
- variance density Var(G_m^{(k)})/m (target 118/243),
with a standard error for the mean-density estimator.

Outputs (defaults):
- artifacts/export/fold_gauge_anomaly_kstep_mc.json
- sections/generated/tab_fold_gauge_anomaly_kstep_mc.tex
"""

from __future__ import annotations

import argparse
import json
import math
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Sequence, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress, fib_upto


def _parse_int_list(s: str) -> List[int]:
    s = s.strip()
    if not s:
        return []
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def _zeckendorf_digits_from_fib(N: int, m: int, fib: Sequence[int]) -> List[int]:
    """Zeckendorf digits (c_1..c_m) for weights F_{k+1}, k=1..m, using a provided fib table.

    Requirements:
    - fib contains Fibonacci numbers F_1..F_{m+2} with F_1=F_2=1,
      i.e. len(fib) >= m+2 and fib[k] == F_{k+1}.
    """
    if N < 0:
        raise ValueError("N must be non-negative")
    if m <= 0:
        return []
    if len(fib) < m + 2:
        raise ValueError("fib table too short for requested m")

    digits = [0] * m
    remaining = N
    k = m
    while remaining > 0 and k >= 1:
        w = fib[k]  # weight F_{k+1}
        if w <= remaining:
            digits[k - 1] = 1
            remaining -= w
            k -= 2  # skip adjacent position
        else:
            k -= 1
    return digits


def _gauge_anomaly_G_kstep(bits: Sequence[int], *, m: int, k: int, fib: Sequence[int]) -> int:
    """Compute G_m^{(k)} for a length-(m+k) micro word omega."""
    n = m + k
    if len(bits) != n:
        raise ValueError("bits must have length m+k")
    if m <= 0 or k <= 0:
        raise ValueError("Require m>=1 and k>=1")

    # Naive truncation prefix.
    prefix = bits[:m]

    # N(omega) = sum_{j=1..n} omega_j F_{j+1}
    # Using fib table with fib[j] == F_{j+1}.
    N = 0
    for j, b in enumerate(bits, start=1):
        if b:
            N += fib[j]

    # Fold_{n}: compute Zeckendorf digits up to length (n+1) then drop overflow.
    # The restriction to length m is just the first m digits.
    digits = _zeckendorf_digits_from_fib(N, n + 1, fib)
    folded_prefix = digits[:m]

    G = 0
    for a, b in zip(prefix, folded_prefix):
        G += int(a) ^ int(b)
    return G


@dataclass(frozen=True)
class Row:
    k: int
    m: int
    samples: int
    mean_density: float
    se_mean_density: float
    var_density: float
    abs_err_mean_vs_4_9: float
    abs_err_var_vs_118_243: float


def _write_tex(rows: List[Row], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    target_mean = 4.0 / 9.0
    target_var = 118.0 / 243.0

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_gauge_anomaly_kstep_mc.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.12}")
    lines.append("\\begin{tabular}{rrrrrrrr}")
    lines.append("\\toprule")
    lines.append(
        "$k$ & $m$ & samples & $\\widehat{\\mathbb{E}}[G_m^{(k)}/m]$ & SE & "
        "$\\,|\\Delta|$ & $\\widehat{\\mathrm{Var}}(G_m^{(k)})/m$ & $\\,|\\Delta|$ \\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.k} & {r.m} & {r.samples} & {r.mean_density:.6f} & {r.se_mean_density:.2e} & "
            f"{r.abs_err_mean_vs_4_9:.6f} & {r.var_density:.6f} & {r.abs_err_var_vs_118_243:.6f} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Monte Carlo audit for the $k$-step gauge anomaly $G_m^{(k)}$ under the uniform baseline "
        "$\\omega\\sim\\mathrm{Unif}(\\Omega_{m+k})$. "
        "We report the sample mean density $\\widehat{\\mathbb{E}}[G_m^{(k)}/m]$ with its standard error (SE), "
        "and the sample variance density $\\widehat{\\mathrm{Var}}(G_m^{(k)})/m$. "
        "Both are compared to the $k$-independent targets $4/9$ and $118/243$ from "
        "Theorem~\\ref{thm:fold-gauge-anomaly-kstep-invariance}. "
        f"(Targets: $4/9\\approx {target_mean:.6f}$, $118/243\\approx {target_var:.6f}$.)}}"
    )
    lines.append("\\label{tab:fold_gauge_anomaly_kstep_mc}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Monte Carlo table for k-step gauge anomaly invariance.")
    ap.add_argument("--ms", type=str, default="200,600,1200", help="Comma-separated list of m values.")
    ap.add_argument("--ks", type=str, default="1,2,3,5", help="Comma-separated list of k values.")
    ap.add_argument("--samples", type=int, default=6000, help="Samples per (k,m) row.")
    ap.add_argument("--seed", type=int, default=11, help="Base RNG seed.")
    ap.add_argument(
        "--json-out",
        type=Path,
        default=export_dir() / "fold_gauge_anomaly_kstep_mc.json",
        help="Output JSON path.",
    )
    ap.add_argument(
        "--tex-out",
        type=Path,
        default=generated_dir() / "tab_fold_gauge_anomaly_kstep_mc.tex",
        help="Output TeX table path.",
    )
    args = ap.parse_args()

    ms = _parse_int_list(str(args.ms))
    ks = _parse_int_list(str(args.ks))
    samples = int(args.samples)
    if not ms:
        raise SystemExit("Require at least one m.")
    if not ks:
        raise SystemExit("Require at least one k.")
    if any(m <= 1 for m in ms):
        raise SystemExit("All m must be >= 2.")
    if any(k <= 0 for k in ks):
        raise SystemExit("All k must be >= 1.")
    if samples <= 0:
        raise SystemExit("--samples must be positive.")

    target_mean = 4.0 / 9.0
    target_var = 118.0 / 243.0

    t0 = time.time()
    prog = Progress("fold_gauge_anomaly_kstep_mc", every_seconds=20.0)

    rows: List[Row] = []
    total_rows = len(ks) * len(ms)
    row_idx = 0

    for k in ks:
        for m in ms:
            row_idx += 1
            n = m + k
            rng = random.Random(int(args.seed) + 1000 * row_idx + 17 * k + m)

            # Need Fibonacci table up to F_{(n+1)+2} = F_{n+3}.
            fib = fib_upto(n + 3)

            # Welford for G (integer) and for density G/m.
            mean_g = 0.0
            m2_g = 0.0
            mean_d = 0.0
            m2_d = 0.0
            cnt = 0

            for s in range(samples):
                bits = [rng.getrandbits(1) for _ in range(n)]
                G = _gauge_anomaly_G_kstep(bits, m=m, k=k, fib=fib)
                d = G / float(m)

                cnt += 1
                # Update for G
                delta_g = G - mean_g
                mean_g += delta_g / cnt
                delta2_g = G - mean_g
                m2_g += delta_g * delta2_g

                # Update for density d
                delta_d = d - mean_d
                mean_d += delta_d / cnt
                delta2_d = d - mean_d
                m2_d += delta_d * delta2_d

                prog.tick(f"row={row_idx}/{total_rows} k={k} m={m} sample={s+1}/{samples}")

            var_g = (m2_g / (cnt - 1)) if cnt > 1 else 0.0
            var_d = (m2_d / (cnt - 1)) if cnt > 1 else 0.0
            se_mean_d = math.sqrt(var_d / cnt) if cnt > 0 else float("nan")
            var_density = var_g / float(m)

            r = Row(
                k=k,
                m=m,
                samples=samples,
                mean_density=float(mean_d),
                se_mean_density=float(se_mean_d),
                var_density=float(var_density),
                abs_err_mean_vs_4_9=float(abs(mean_d - target_mean)),
                abs_err_var_vs_118_243=float(abs(var_density - target_var)),
            )
            rows.append(r)
            print(
                f"[fold_gauge_anomaly_kstep_mc] done row={row_idx}/{total_rows} "
                f"k={k} m={m} mean={r.mean_density:.6f} SE={r.se_mean_density:.2e} var/m={r.var_density:.6f}",
                flush=True,
            )

    # Write JSON output.
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "rows": [asdict(r) for r in rows],
        "ms": ms,
        "ks": ks,
        "samples_per_row": samples,
        "target_mean_4_over_9": target_mean,
        "target_var_118_over_243": target_var,
        "seed": int(args.seed),
        "generated_at_unix_s": time.time(),
        "elapsed_s": time.time() - t0,
    }
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[fold_gauge_anomaly_kstep_mc] wrote {jout}", flush=True)

    # Write TeX table output.
    tout = Path(args.tex_out)
    _write_tex(rows, tout)
    print(f"[fold_gauge_anomaly_kstep_mc] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

