#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate for the exact cyclic escort tensor-axis crossover at m=6.

All output is English-only by repository convention.

The audited cyclic histogram is
  2:5, 3:4, 4:9,
and the tensor-axis crossover is the unique positive root of
  4*3^q = 4^q + 3*2^q.

Outputs:
  - artifacts/export/window6_cyclic_escort_axis_audit.json
  - sections/generated/eq_window6_cyclic_escort_axis_audit.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from common_paths import export_dir, generated_dir


def _axis_gap(q: float) -> float:
    return 4.0 * (3.0 ** q) - (4.0 ** q) - 3.0 * (2.0 ** q)


def _normalized_magnetization_e1(q: float) -> float:
    numerator = (4.0 ** q) - (2.0 ** q)
    denominator = 5.0 * (2.0 ** q) + 4.0 * (3.0 ** q) + 9.0 * (4.0 ** q)
    return numerator / denominator


def _bisect_unique_root(*, lo: float, hi: float, tol: float = 1.0e-16, max_iter: int = 256) -> float:
    flo = _axis_gap(lo)
    fhi = _axis_gap(hi)
    if flo == 0.0:
        return lo
    if fhi == 0.0:
        return hi
    if flo * fhi > 0.0:
        raise ValueError("Root bracket does not straddle zero.")
    for _ in range(max_iter):
        mid = 0.5 * (lo + hi)
        fmid = _axis_gap(mid)
        if fmid == 0.0 or 0.5 * (hi - lo) < tol:
            return mid
        if flo * fmid <= 0.0:
            hi = mid
            fhi = fmid
        else:
            lo = mid
            flo = fmid
    return 0.5 * (lo + hi)


def _fmt_decimal(x: float) -> str:
    return f"{x:.15f}"


def _fmt_sci(x: float) -> str:
    return f"{x:.16e}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit the exact cyclic escort tensor-axis crossover at m=6.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_cyclic_escort_axis_audit.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_window6_cyclic_escort_axis_audit.tex"),
        help="Output TeX path.",
    )
    args = parser.parse_args()

    print("[window6-cyclic-escort-axis] solving unique tensor-axis crossover", flush=True)
    q_ax = _bisect_unique_root(lo=4.0, hi=5.0)
    residual = _axis_gap(q_ax)
    magnetization_e1 = _normalized_magnetization_e1(q_ax)

    payload = {
        "cyclic_histogram_m6": {"2": 5, "3": 4, "4": 9},
        "first_moment_formula": "m_cyc(q)=(4^q-2^q)e1",
        "second_moment_layer_diagonals": {
            "d4": [5, 6, 2],
            "d3": [4, 0, 4],
            "d2": [1, 4, 4],
        },
        "uniform_tensor_isotropy": "I_cyc(0)=10*I3",
        "axis_crossover_equation": "4*3^q=4^q+3*2^q",
        "q6_ax": q_ax,
        "axis_crossover_residual_at_q6_ax": residual,
        "normalized_magnetization_e1_at_q6_ax": magnetization_e1,
        "normalized_magnetization_limit": "1/9",
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_lines = [
        "% AUTO-GENERATED by scripts/exp_window6_cyclic_escort_axis_audit.py",
        r"\begin{equation}\label{eq:window6_cyclic_escort_axis_audit}",
        r"\begin{aligned}",
        rf"q_{{6,\mathrm{{ax}}}} &\approx {_fmt_decimal(q_ax)},\\",
        rf"4\cdot 3^{{q_{{6,\mathrm{{ax}}}}}}-4^{{q_{{6,\mathrm{{ax}}}}}}-3\cdot 2^{{q_{{6,\mathrm{{ax}}}}}} &\approx {_fmt_sci(residual)},\\",
        rf"\overline{{\mathfrak m}}_{{6,\mathrm{{cyc}}}}(q_{{6,\mathrm{{ax}}}})\cdot e_1 &\approx {_fmt_decimal(magnetization_e1)}.",
        r"\end{aligned}",
        r"\end{equation}",
        "",
    ]
    tex_out = Path(str(args.tex_out))
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    tex_out.write_text("\n".join(tex_lines), encoding="utf-8")

    print(f"File: {json_out.relative_to(export_dir().parent.parent)}", flush=True)
    print(f"File: {tex_out.relative_to(generated_dir().parent.parent)}", flush=True)
    print("[window6-cyclic-escort-axis] done", flush=True)


if __name__ == "__main__":
    main()
