#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compute the bulk resonance constant C_phi and its collision-gap floors.

We study the infinite product
  C_phi := Π_{n=2}^∞ |cos(π φ^{-n})|,
which appears as the limiting normalized Fourier amplitude along the bulk
resonant frequencies k=F_m and k=F_{m+1} (Appendix: fold multiplicity).

This script evaluates a partial product up to n<=N and exports:
  - artifacts/export/fold_critical_resonance_constant.json
  - sections/generated/eq_fold_critical_resonance_constant_numeric.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List

from common_paths import export_dir, generated_dir
from common_phi_fold import PHI


def c_phi_partial(n_max: int) -> float:
    """Partial product Π_{n=2}^{n_max} |cos(π φ^{-n})|."""
    if n_max < 2:
        raise ValueError("n_max must be >= 2")
    p = 1.0
    for n in range(2, n_max + 1):
        p *= abs(math.cos(math.pi * (PHI ** (-n))))
    return float(p)


def _tex_float(x: float, nd: int = 16) -> str:
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute C_phi (partial product) and derived constants (LaTeX + JSON)."
    )
    parser.add_argument(
        "--n-max",
        type=int,
        default=200,
        help="Partial product cutoff N (product starts at n=2).",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "fold_critical_resonance_constant.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_fold_critical_resonance_constant_numeric.tex"),
        help="Output TeX equation fragment path.",
    )
    args = parser.parse_args()

    n_max = int(args.n_max)
    if n_max < 2:
        raise SystemExit("Require --n-max >= 2")

    C_phi = c_phi_partial(n_max)
    two_C2 = 2.0 * C_phi * C_phi
    one_plus_two_C2 = 1.0 + two_C2

    payload: Dict[str, Any] = {
        "definition": {
            "phi": float(PHI),
            "C_phi": "prod_{n=2..inf} |cos(pi * phi^{-n})|",
            "method": "partial_product",
        },
        "partial_product": {
            "n_max": n_max,
            "C_phi_partial": float(C_phi),
        },
        "derived": {
            "two_C_phi_sq": float(two_C2),
            "one_plus_two_C_phi_sq": float(one_plus_two_C2),
        },
    }

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fold_critical_resonance_constant.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "C_\\varphi^{(\\le "
        + str(n_max)
        + ")}:=\\prod_{n=2}^{"
        + str(n_max)
        + "}\\bigl|\\cos(\\pi\\varphi^{-n})\\bigr|"
        + f"&\\approx {_tex_float(C_phi, 16)},\\\\"
    )
    lines.append(f"2C_\\varphi^2&\\approx {_tex_float(two_C2, 16)},\\\\")
    lines.append(f"1+2C_\\varphi^2&\\approx {_tex_float(one_plus_two_C2, 16)}.")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[fold-critical-resonance-constant] wrote {jout}", flush=True)
    print(f"[fold-critical-resonance-constant] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

