#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fold^{bin}_m gauge-group invariants and gauge-volume bounds (default m=6).

All output is English-only by repository convention.

We compute:
  - fiber sizes d^{bin}_m(w) for all w in X_m (exact digit DP),
  - gauge group structure and |G^{bin}_m|,
  - gauge volume density g_m := (1/2^m) log |G^{bin}_m|,
  - kappa_m := (1/2^m) sum_w d(w) log d(w),
  - abelianization rank (fiber-parity charge dimension).

Outputs (default):
  - artifacts/export/fold_bin_gauge_m6_invariants.json
  - sections/generated/tab_fold_bin_gauge_m6_invariants.tex
  - sections/generated/tab_fold_bin_gauge_m6_fibers.tex
"""

from __future__ import annotations

import argparse
import json
import math
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import fib_upto, word_to_str, zeckendorf_digits


def _golden_words(m: int) -> List[List[int]]:
    """All length-m binary words with no adjacent ones (golden mean SFT)."""
    if m < 0:
        raise ValueError("m must be non-negative")
    out: List[List[int]] = []

    def rec(pos: int, prev1: int, acc: List[int]) -> None:
        if pos == m:
            out.append(list(acc))
            return
        acc.append(0)
        rec(pos + 1, 0, acc)
        acc.pop()
        if prev1 == 0:
            acc.append(1)
            rec(pos + 1, 1, acc)
            acc.pop()

    rec(0, 0, [])
    return out


def _fib_precompute_up_to_limit(limit: int) -> List[int]:
    """Return Fibonacci numbers F_1..F_J (F_1=F_2=1) with F_J > limit."""
    fib = [1, 1]
    while fib[-1] <= limit:
        fib.append(fib[-1] + fib[-2])
    return fib


def _K_of_m(limit: int) -> int:
    """Unique K with F_{K+1} <= limit < F_{K+2} (F_1=F_2=1)."""
    fib = _fib_precompute_up_to_limit(limit)
    # len(fib)=J gives F_J > limit and F_{J-1} <= limit, hence K+2=J.
    return len(fib) - 2


def _V_m(w: Sequence[int], fib: Sequence[int]) -> int:
    """Zeckendorf value V_m(w) = sum_{k=1}^m w_k F_{k+1}."""
    s = 0
    for i, bit in enumerate(w, start=1):
        if bit:
            s += fib[i]  # F_{i+1}
    return s


def _count_tail_leq(
    *, limit: int, m: int, K: int, w_m: int
) -> int:
    """Count tails (c_{m+1}..c_K) with:
    - c_k in {0,1}
    - no adjacency: c_k c_{k+1} = 0
    - boundary: w_m c_{m+1} = 0
    - value constraint: sum_{k=m+1}^K c_k F_{k+1} <= limit
    """
    if limit < 0:
        return 0
    if K <= m:
        return 1

    # Zeckendorf digits b_1..b_K for limit, weights F_{k+1}.
    b = zeckendorf_digits(limit, K)

    @lru_cache(None)
    def dp(pos: int, prev1: int, tight: int) -> int:
        if pos == 0:
            return 1
        bpos = b[pos - 1]

        # Forced zeros below/at m and boundary at m+1.
        if pos <= m or (pos == m + 1 and w_m == 1):
            digit = 0
            next_tight = tight and (digit == bpos)
            return dp(pos - 1, digit, 1 if next_tight else 0)

        total = 0
        for digit in (0, 1):
            if digit == 1 and prev1 == 1:
                continue
            if tight and digit > bpos:
                continue
            next_tight = tight and (digit == bpos)
            total += dp(pos - 1, digit, 1 if next_tight else 0)
        return total

    return dp(K, 0, 1)


def _log_factorial(d: int) -> float:
    return float(math.lgamma(d + 1))


def _tex_table(
    *,
    m: int,
    X_size: int,
    hist: Dict[int, int],
    logG: float,
    g_m: float,
    kappa_m: float,
    rank_ab: int,
    out_path: Path,
) -> None:
    hist_tex = ",\\ ".join([f"{d}:{c}" for d, c in sorted(hist.items())])
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fold_bin_gauge_m6_invariants.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{Binary-interval fold gauge invariants at $m=6$: fiber histogram, gauge volume density, "
        "and abelianized parity-charge dimension.}"
    )
    lines.append("\\label{tab:fold_bin_gauge_m6_invariants}")
    lines.append("\\begin{tabular}{l r}")
    lines.append("\\toprule")
    lines.append("quantity & value\\\\")
    lines.append("\\midrule")
    lines.append(f"$|X_{m}|$ & {X_size}\\\\")
    lines.append(f"fiber histogram $(d:\\#)$ & ${hist_tex}$\\\\")
    lines.append(f"$\\log|\\mathcal{{G}}^{{\\mathrm{{bin}}}}_{m}|$ & {logG:.6f}\\\\")
    lines.append(f"$g_{m}=2^{{-{m}}}\\log|\\mathcal{{G}}^{{\\mathrm{{bin}}}}_{m}|$ & {g_m:.6f}\\\\")
    lines.append(f"$\\kappa_{m}=2^{{-{m}}}\\sum_w d\\log d$ & {kappa_m:.6f}\\\\")
    lines.append(f"$\\mathrm{{rank}}\\,\\bigl(\\mathcal{{G}}^{{\\mathrm{{bin}}}}_{m}\\bigr)^{{\\mathrm{{ab}}}}$ & {rank_ab}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _tex_fibers_table(*, m: int, rows: List[Tuple[str, int]], out_path: Path) -> None:
    """Write a canonical X_m listing with d^{bin}_m(w) for auditability."""
    if m != 6:
        # The script name and default output paths are anchored at m=6.
        # We still allow overriding m for local experiments, but keep the TeX label stable.
        pass
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fold_bin_gauge_m6_invariants.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.1}")
    lines.append(
        "\\caption{Binary-interval fold fibers at $m=6$: a canonical lexicographic enumeration of $X_6$ "
        "together with fiber sizes $d^{\\mathrm{bin}}_6(w)=|\\mathrm{Fold}^{\\mathrm{bin}}_6{}^{-1}(w)|$. "
        "This ordering provides a concrete coordinate convention for the parity-charge lattice "
        "$(\\mathbb Z_2)^{X_6}\\cong(\\mathbb Z_2)^{21}$ via the sign map.}"
    )
    lines.append("\\label{tab:fold_bin_gauge_m6_fibers}")
    lines.append("\\begin{tabular}{r l r}")
    lines.append("\\toprule")
    lines.append("index & $w\\in X_6$ & $d^{\\mathrm{bin}}_6(w)$\\\\")
    lines.append("\\midrule")
    for i, (w, d) in enumerate(rows, start=1):
        lines.append(f"{i} & \\texttt{{{w}}} & {int(d)}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Fold^{bin} gauge invariants (default m=6).")
    ap.add_argument("--m", type=int, default=6, help="Window size m.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "fold_bin_gauge_m6_invariants.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_fold_bin_gauge_m6_invariants.tex"),
    )
    ap.add_argument(
        "--tex-fibers-out",
        type=str,
        default=str(generated_dir() / "tab_fold_bin_gauge_m6_fibers.tex"),
        help="Canonical listing of X_6 with fiber sizes (audit coordinate convention).",
    )
    args = ap.parse_args()

    m = int(args.m)
    if m <= 0:
        raise SystemExit("Require m >= 1.")

    target = (1 << m) - 1
    K = _K_of_m(target)
    fib = fib_upto(K + 2)  # F_1..F_{K+2}

    words = _golden_words(m)
    X = [word_to_str(w) for w in words]

    d_map: Dict[str, int] = {}
    hist: Dict[int, int] = {}
    total_micro = 1 << m

    for w in words:
        w_m = w[-1]
        V = _V_m(w, fib)
        slack = target - V
        d = _count_tail_leq(limit=slack, m=m, K=K, w_m=w_m)
        ws = word_to_str(w)
        d_map[ws] = int(d)
        hist[int(d)] = hist.get(int(d), 0) + 1

    # Gauge group order and density.
    logG = sum(count * _log_factorial(d) for d, count in hist.items())
    g_m = logG / float(total_micro)
    kappa_m = sum(count * d * math.log(d) for d, count in hist.items()) / float(total_micro)

    # Abelianization rank: one Z2 per fiber with d>=2.
    rank_ab = sum(1 for d in d_map.values() if d >= 2)

    payload: Dict[str, object] = {
        "m": m,
        "K": K,
        "X_size": len(X),
        "X_words_lex": sorted(X),
        "fiber_histogram": {str(k): int(v) for k, v in sorted(hist.items())},
        "d_map": d_map,
        "gauge_group": {
            "log_order": float(logG),
            "order_str": str(
                math.prod(math.factorial(d) ** count for d, count in hist.items())
            ),
            "g_m": float(g_m),
        },
        "kappa_m": float(kappa_m),
        "bounds_check": {
            "kappa_minus_1": float(kappa_m - 1.0),
            "g_m": float(g_m),
            "kappa_m": float(kappa_m),
            "satisfies": bool((kappa_m - 1.0) <= g_m <= kappa_m),
        },
        "abelianization_rank": int(rank_ab),
        "abelianization_basis_words_lex": [w for w in sorted(X) if int(d_map[w]) >= 2],
        "total_microstates": int(total_micro),
    }

    jout = Path(str(args.json_out))
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    _tex_table(
        m=m,
        X_size=len(X),
        hist=hist,
        logG=logG,
        g_m=g_m,
        kappa_m=kappa_m,
        rank_ab=rank_ab,
        out_path=Path(str(args.tex_out)),
    )

    print(f"[fold-bin-gauge] wrote {jout}", flush=True)
    print(f"[fold-bin-gauge] wrote {args.tex_out}", flush=True)
    _tex_fibers_table(
        m=m,
        rows=[(w, int(d_map[w])) for w in sorted(X)],
        out_path=Path(str(args.tex_fibers_out)),
    )
    print(f"[fold-bin-gauge] wrote {args.tex_fibers_out}", flush=True)
    print("[fold-bin-gauge] done", flush=True)


if __name__ == "__main__":
    main()
