#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit certificate for the explicit Belyi-type family

  Pi_r(lambda,y) = (lambda-1)^r + (y-1) lambda^(r-1),
  f_r(lambda) = 1 - (lambda-1)^r / lambda^(r-1).

Verified items:
  - closed discriminant factorization in y with sign epsilon_r in {+1,-1},
  - branch-value formula y_r = 1 + r^r/(r-1)^(r-1),
  - local ramification checks at y=1, y=y_r, y=infinity,
  - permutation certificate for full symmetric group generation,
  - r=3 recurrence/initial values/discriminant factorization,
  - numerical scaling-limit audit near y=1 at n^{-r} scale.

Outputs:
  - artifacts/export/xi_belyi_full_symmetric_puiseux_audit.json
  - sections/generated/eq_xi_belyi_family_discriminant_recurrence_r3.tex
  - sections/generated/tab_xi_belyi_branch_discriminant_group_audit_r2_r9.tex
  - sections/generated/tab_xi_belyi_scaling_limit_audit.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import mpmath as mp
import sympy as sp
from sympy.combinatorics import Permutation, PermutationGroup

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress


@dataclass(frozen=True)
class BranchDiscRow:
    r: int
    y_r: str
    epsilon_r: int
    disc_formula_ok: bool
    derivative_formula_ok: bool
    local_y1_order_ok: bool
    local_yinfty_type_ok: bool
    local_yr_double_root_ok: bool
    cycle_sigma_1: str
    cycle_sigma_yr: str
    cycle_sigma_infty: str
    generated_group_order: int
    generated_group_is_full_symmetric: bool


@dataclass(frozen=True)
class ScalingRow:
    r: int
    n: int
    max_abs_error: str
    n_times_max_abs_error: str


def _poly_pi(r: int, lam: sp.Symbol, y: sp.Symbol) -> sp.Expr:
    return sp.expand((lam - 1) ** r + (y - 1) * lam ** (r - 1))


def _is_constant_in(expr: sp.Expr, sym: sp.Symbol) -> bool:
    expr = sp.together(sp.simplify(expr))
    num, den = expr.as_numer_denom()
    try:
        deg_num = sp.Poly(num, sym, domain=sp.QQ).degree()
        deg_den = sp.Poly(den, sym, domain=sp.QQ).degree()
    except Exception:
        return False
    return deg_num == 0 and deg_den == 0


def _cycle_type_str(perm: Permutation, degree: int) -> str:
    cyc_lengths = sorted((len(c) for c in perm.cyclic_form), reverse=True)
    moved = sum(cyc_lengths)
    fixed = degree - moved
    parts = [str(v) for v in cyc_lengths] + (["1"] * fixed)
    if not parts:
        parts = ["1"] * degree
    return "(" + ")(".join(parts) + ")"


def _powsum_newton(poly: sp.Poly, n: int) -> sp.Expr:
    # Monic polynomial x^d + a_1 x^(d-1) + ... + a_d
    coeffs = [sp.simplify(c) for c in poly.all_coeffs()]
    d = poly.degree()
    if coeffs[0] != 1:
        raise RuntimeError("Expected monic polynomial for Newton sums.")
    a = coeffs[1:]

    s: Dict[int, sp.Expr] = {0: sp.Integer(d)}
    for k in range(1, n + 1):
        if k <= d:
            rhs = -sum(a[j - 1] * s[k - j] for j in range(1, k))
            rhs -= k * a[k - 1]
            s[k] = sp.simplify(rhs)
        else:
            rhs = -sum(a[j - 1] * s[k - j] for j in range(1, d + 1))
            s[k] = sp.simplify(rhs)
    return sp.simplify(s[n])


def _complex_from_sympy(z: sp.Expr, dps: int = 80) -> mp.mpc:
    zr = sp.re(z).evalf(dps)
    zi = sp.im(z).evalf(dps)
    return mp.mpc(str(zr), str(zi))


def _write_eq_tex(
    *,
    z0: sp.Expr,
    z1: sp.Expr,
    z2: sp.Expr,
    out_path: Path,
) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_xi_belyi_full_symmetric_puiseux_audit.py")
    lines.append(r"\begin{equation}\label{eq:xi_terminal_belyi_family_discriminant_closed}")
    lines.append(
        r"\mathrm{Disc}_{\lambda}(\Pi_r)(y)=\varepsilon_r\,(y-1)^{r-1}\Bigl((r-1)^{r-1}y-\bigl((r-1)^{r-1}+r^r\bigr)\Bigr),\quad \varepsilon_r\in\{\pm1\}."
    )
    lines.append(r"\end{equation}")
    lines.append("")
    lines.append(r"\begin{equation}\label{eq:xi_terminal_belyi_r3_recurrence_discriminant}")
    lines.append(r"\begin{aligned}")
    lines.append(
        r"\Pi_3(\lambda,y)&=(\lambda-1)^3+(y-1)\lambda^2=\lambda^3+(y-4)\lambda^2+3\lambda-1,\\"
    )
    lines.append(
        r"Z_{n+3}(y)&+(y-4)Z_{n+2}(y)+3Z_{n+1}(y)-Z_n(y)=0,\\"
    )
    lines.append(
        rf"Z_0(y)&={sp.latex(z0)},\qquad Z_1(y)={sp.latex(z1)},\qquad Z_2(y)={sp.latex(z2)},\\"
    )
    lines.append(
        r"\mathrm{Disc}_{\lambda}(\Pi_3)(y)&=(y-1)^2(4y-31)."
    )
    lines.append(r"\end{aligned}")
    lines.append(r"\end{equation}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _write_branch_table(rows: Sequence[BranchDiscRow], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_xi_belyi_full_symmetric_puiseux_audit.py")
    lines.append(r"\begin{table}[H]")
    lines.append(r"\centering")
    lines.append(r"\scriptsize")
    lines.append(r"\setlength{\tabcolsep}{5pt}")
    lines.append(
        r"\caption{Belyi 三点分歧族 \(\Pi_r\)（\(2\le r\le 9\)）的判别式因子、局部分歧与置换生成审计。}"
    )
    lines.append(r"\label{tab:xi_belyi_branch_discriminant_group_audit_r2_r9}")
    lines.append(r"\begin{tabular}{r l r c c c r c}")
    lines.append(r"\toprule")
    lines.append(
        r"$r$ & $y_r$ & $\varepsilon_r$ & Disc & $e_{y_r}=2$ & $\sigma_\infty$ type & $|\langle\sigma_1,\sigma_{y_r}\rangle|$ & $=r!$\\"
    )
    lines.append(r"\midrule")
    for row in rows:
        lines.append(
            f"{row.r} & ${row.y_r}$ & {row.epsilon_r} & {int(row.disc_formula_ok)} & "
            f"{int(row.local_yr_double_root_ok)} & ${row.cycle_sigma_infty}$ & {row.generated_group_order} & "
            f"{int(row.generated_group_is_full_symmetric)}\\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _write_scaling_table(rows: Sequence[ScalingRow], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_xi_belyi_full_symmetric_puiseux_audit.py")
    lines.append(r"\begin{table}[H]")
    lines.append(r"\centering")
    lines.append(r"\scriptsize")
    lines.append(r"\setlength{\tabcolsep}{6pt}")
    lines.append(
        r"\caption{局部缩放 \(y=1+t^r/n^r\) 下的数值审计："
        r"\(Z_n^{(r)}\) 与 \(\sum_{k=0}^{r-1}\exp(\omega_r^k\kappa_r t)\) 的最大误差（\(\kappa_r^r=-1\)）。}"
    )
    lines.append(r"\label{tab:xi_belyi_scaling_limit_audit}")
    lines.append(r"\begin{tabular}{r r l l}")
    lines.append(r"\toprule")
    lines.append(r"$r$ & $n$ & max error & $n\cdot$max error\\")
    lines.append(r"\midrule")
    for row in rows:
        lines.append(
            f"{row.r} & {row.n} & ${row.max_abs_error}$ & ${row.n_times_max_abs_error}$\\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit Belyi full-symmetric Puiseux family.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "xi_belyi_full_symmetric_puiseux_audit.json"),
    )
    parser.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_xi_belyi_family_discriminant_recurrence_r3.tex"),
    )
    parser.add_argument(
        "--tex-tab-branch-out",
        type=str,
        default=str(generated_dir() / "tab_xi_belyi_branch_discriminant_group_audit_r2_r9.tex"),
    )
    parser.add_argument(
        "--tex-tab-scaling-out",
        type=str,
        default=str(generated_dir() / "tab_xi_belyi_scaling_limit_audit.tex"),
    )
    args = parser.parse_args()

    progress = Progress("xi_belyi_full_symmetric_puiseux")

    lam, y = sp.symbols("lam y")

    # ------------------------------------------------------------------
    # Family-level branch/discriminant/group audit for r=2..9.
    # ------------------------------------------------------------------
    branch_rows: List[BranchDiscRow] = []
    branch_payload: List[Dict[str, object]] = []
    for r in range(2, 10):
        progress.tick(f"branch/discriminant audit r={r}")
        Pi_r = _poly_pi(r, lam, y)

        # Discriminant closed form in y.
        disc = sp.factor(sp.discriminant(Pi_r, lam))
        target = (y - 1) ** (r - 1) * ((r - 1) ** (r - 1) * y - ((r - 1) ** (r - 1) + r**r))
        ratio = sp.simplify(sp.together(disc / target))
        disc_formula_ok = _is_constant_in(ratio, y) and int(sp.factor(ratio)) in (-1, 1)
        if not disc_formula_ok:
            raise RuntimeError(f"Discriminant closed form failed for r={r}.")
        epsilon_r = int(sp.factor(ratio))

        # f_r derivative and critical value formula.
        f_r = 1 - (lam - 1) ** r / lam ** (r - 1)
        fprime_expected = -((lam - 1) ** (r - 1) * (lam + r - 1)) / lam**r
        derivative_formula_ok = bool(sp.simplify(sp.diff(f_r, lam) - fprime_expected) == 0)

        y_r = sp.simplify(1 + sp.Rational(r**r, (r - 1) ** (r - 1)))
        yr_formula_ok = bool(sp.simplify(f_r.subs(lam, 1 - r) - y_r) == 0)
        if not yr_formula_ok:
            raise RuntimeError(f"Critical value y_r formula failed for r={r}.")

        # Local check at y=1: order-r branch at lambda=1 for Pi_r(lambda,1)=(lambda-1)^r.
        mu = sp.symbols("mu")
        local_series = sp.series(f_r.subs(lam, 1 + mu) - 1, mu, 0, r + 2).removeO()
        local_poly = sp.Poly(sp.expand(local_series), mu)
        local_y1_order_ok = bool(local_poly.coeff_monomial(mu**r) == -1)
        for k in range(1, r):
            local_y1_order_ok = local_y1_order_ok and bool(local_poly.coeff_monomial(mu**k) == 0)

        # Local type at infinity: pole orders r-1 at lambda=0 and 1 at lambda=infinity.
        c0 = sp.simplify(sp.limit(f_r * lam ** (r - 1), lam, 0))
        lead_inf = sp.simplify(sp.limit(f_r / lam, lam, sp.oo))
        local_yinfty_type_ok = bool(c0 != 0 and lead_inf == -1)

        # At y=y_r, exactly one double root at lambda=1-r.
        P_yr = sp.Poly(sp.expand(Pi_r.subs(y, y_r)), lam, domain=sp.QQ)
        g = sp.gcd(P_yr, P_yr.diff())
        gcd_degree = int(g.degree())
        mult_at_crit = 0
        for fac_poly, expv in P_yr.factor_list()[1]:
            if sp.expand(fac_poly.as_expr() - (lam - (1 - r))) == 0:
                mult_at_crit = int(expv)
                break
        local_yr_double_root_ok = bool(gcd_degree == 1 and mult_at_crit == 2)

        # Permutation certificate: r-cycle + transposition generate S_r.
        sigma_1 = Permutation(list(range(1, r)) + [0])  # (1 2 ... r) in 1-based notation
        sigma_yr = Permutation(r - 2, r - 1, size=r)  # transposition (r-1 r)
        sigma_infty = (sigma_1 * sigma_yr) ** -1
        group = PermutationGroup([sigma_1, sigma_yr])
        order = int(group.order())
        is_full = bool(order == math.factorial(r))

        row = BranchDiscRow(
            r=int(r),
            y_r=str(sp.simplify(y_r)),
            epsilon_r=int(epsilon_r),
            disc_formula_ok=bool(disc_formula_ok),
            derivative_formula_ok=bool(derivative_formula_ok),
            local_y1_order_ok=bool(local_y1_order_ok),
            local_yinfty_type_ok=bool(local_yinfty_type_ok),
            local_yr_double_root_ok=bool(local_yr_double_root_ok),
            cycle_sigma_1=_cycle_type_str(sigma_1, r),
            cycle_sigma_yr=_cycle_type_str(sigma_yr, r),
            cycle_sigma_infty=_cycle_type_str(sigma_infty, r),
            generated_group_order=order,
            generated_group_is_full_symmetric=is_full,
        )
        branch_rows.append(row)
        branch_payload.append(asdict(row))

    # ------------------------------------------------------------------
    # r=3 explicit recurrence/discriminant and Lee-Yang interval audit.
    # ------------------------------------------------------------------
    progress.tick("r=3 recurrence/discriminant/interval audit")
    Pi3 = sp.Poly(_poly_pi(3, lam, y), lam, domain=sp.QQ[y])
    Z0 = _powsum_newton(Pi3, 0)
    Z1 = _powsum_newton(Pi3, 1)
    Z2 = _powsum_newton(Pi3, 2)
    r3_initial_ok = bool(
        sp.simplify(Z0 - 3) == 0
        and sp.simplify(Z1 - (4 - y)) == 0
        and sp.simplify(Z2 - (y**2 - 8 * y + 10)) == 0
    )
    disc3 = sp.factor(sp.discriminant(Pi3.as_expr(), lam))
    r3_disc_ok = bool(sp.factor(disc3 - (y - 1) ** 2 * (4 * y - 31)) == 0)

    # Interval (1,31/4): one real root in (0,1) + complex conjugate pair with rho>1.
    yL = mp.mpf("1.0")
    yR = mp.mpf("7.75")
    samples = 60
    interval_ok = True
    interval_checks: List[Dict[str, object]] = []
    for i in range(1, samples + 1):
        yv = yL + (yR - yL) * mp.mpf(i) / mp.mpf(samples + 1)
        poly_num = sp.Poly(Pi3.as_expr().subs(y, sp.N(yv, 80)), lam)
        roots = poly_num.nroots(n=80, maxsteps=200)
        roots_c = [complex(_complex_from_sympy(rr, dps=80)) for rr in roots]
        real_roots = [rr.real for rr in roots_c if abs(rr.imag) < 1e-10]
        nonreal = [rr for rr in roots_c if abs(rr.imag) >= 1e-10]
        one_real = len(real_roots) == 1 and len(nonreal) == 2
        if not one_real:
            interval_ok = False
            break
        lam0 = real_roots[0]
        rho = abs(nonreal[0])
        cond = (0.0 < lam0 < 1.0) and (rho > 1.0) and (abs(lam0 - rho ** (-2)) < 5e-8)
        interval_ok = interval_ok and cond
        if i in (1, samples // 2, samples):
            interval_checks.append(
                {
                    "y": str(yv),
                    "real_root_lambda0": f"{lam0:.16f}",
                    "rho": f"{rho:.16f}",
                    "lambda0_minus_rho_inv_sq": f"{(lam0 - rho**(-2)):.3e}",
                    "check_ok": bool(cond),
                }
            )

    # ------------------------------------------------------------------
    # Scaling-limit audit near y=1 at n^{-r}.
    # Compare with sum_k exp(omega_r^k * kappa_r * t), kappa_r^r=-1.
    # ------------------------------------------------------------------
    progress.tick("scaling-limit audit")
    mp.mp.dps = 90
    t_samples = [
        mp.mpc("0.35", "0.10"),
        mp.mpc("-0.40", "0.00"),
        mp.mpc("0.25", "-0.20"),
        mp.mpc("0.15", "0.30"),
    ]
    scaling_rows: List[ScalingRow] = []
    scaling_payload: List[Dict[str, object]] = []
    for r in (3, 4, 5, 6):
        omega = mp.e ** (2j * mp.pi / r)
        kappa = mp.e ** (1j * mp.pi / r)  # principal r-th root of -1
        for n in (120, 240):
            max_err = mp.mpf("0.0")
            for tval in t_samples:
                yv = 1 + (tval ** r) / (n**r)
                poly_expr = _poly_pi(r, lam, sp.N(yv, 80))
                roots = sp.Poly(poly_expr, lam).nroots(n=80, maxsteps=200)
                roots_mpc = [_complex_from_sympy(rr, dps=80) for rr in roots]
                Z = mp.mpc("0.0")
                for rr in roots_mpc:
                    Z += rr**n
                target = mp.mpc("0.0")
                for k in range(r):
                    target += mp.e ** ((omega**k) * kappa * tval)
                err = abs(Z - target)
                if err > max_err:
                    max_err = err
            row = ScalingRow(
                r=int(r),
                n=int(n),
                max_abs_error=mp.nstr(max_err, 8),
                n_times_max_abs_error=mp.nstr(n * max_err, 8),
            )
            scaling_rows.append(row)
            scaling_payload.append(asdict(row))

    payload: Dict[str, object] = {
        "branch_discriminant_group_rows": branch_payload,
        "r3_recurrence_and_discriminant": {
            "Pi3": str(Pi3.as_expr()),
            "Z0": str(sp.expand(Z0)),
            "Z1": str(sp.expand(Z1)),
            "Z2": str(sp.expand(Z2)),
            "initial_values_match_closed_form": bool(r3_initial_ok),
            "disc_factorization_ok": bool(r3_disc_ok),
        },
        "r3_interval_leyang_boundary_check": {
            "interval_open": "(1,31/4)",
            "sample_count": int(samples),
            "all_samples_ok": bool(interval_ok),
            "spot_checks": interval_checks,
        },
        "scaling_limit_rows": scaling_payload,
        "notes": {
            "scaling_target": "sum_{k=0}^{r-1} exp(omega_r^k * kappa_r * t), with kappa_r^r=-1",
            "normalization_comment": "By reparameterization t -> kappa_r^{-1} t this is equivalent to sum exp(omega_r^k t).",
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    _write_eq_tex(z0=sp.expand(Z0), z1=sp.expand(Z1), z2=sp.expand(Z2), out_path=Path(str(args.tex_eq_out)))
    _write_branch_table(branch_rows, Path(str(args.tex_tab_branch_out)))
    _write_scaling_table(scaling_rows, Path(str(args.tex_tab_scaling_out)))

    print(f"[xi-belyi-full-symmetric-puiseux] wrote {json_out}", flush=True)
    print(f"[xi-belyi-full-symmetric-puiseux] wrote {args.tex_eq_out}", flush=True)
    print(f"[xi-belyi-full-symmetric-puiseux] wrote {args.tex_tab_branch_out}", flush=True)
    print(f"[xi-belyi-full-symmetric-puiseux] wrote {args.tex_tab_scaling_out}", flush=True)


if __name__ == "__main__":
    main()

