#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Cross-layer diagnostics for the (((3,3,5))) arity prime spectrum.

We combine:
  - orbit-layer worst twisted spectral radius rho_{3,3,5} (real-input 40-state kernel),
  - window-layer collision Perron root r2 = rho(A2),
  - low-rank/SVD residual of the constant tensor C^{(3,3,5)} (as a 5x9 matrix),
  - covariance/Hessian correlation between nu (neg-carry) and xi (collision),
  - bias-spectrum (Fourier harmonic amplitudes) vs rate-spectrum (worst j3).

Inputs (generated elsewhere):
  - artifacts/export/sync_kernel_real_input_40_arity_3d_N2_335.json
  - artifacts/export/real_input_40_covariance_worst_character.json

Outputs:
  - sections/generated/eq_arity_335_cross_layer_diagnostics.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Tuple

import numpy as np

from common_paths import generated_dir


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _perron_root_A2() -> float:
    # Largest real root of x^3 - 2 x^2 - 2 x + 2 = 0.
    coeff = [1.0, -2.0, -2.0, 2.0]
    roots = np.roots(coeff)
    rr = [r.real for r in roots if abs(r.imag) < 1e-10]
    if not rr:
        raise ValueError("No real root found for A2 characteristic polynomial")
    return float(max(rr))


def _build_T_from_C(triple_class_C: Dict[str, float]) -> np.ndarray:
    """Return T in R^{5x9} for 3x3x5: rows c=0..4, cols (a,b) flattened."""
    T = np.zeros((5, 9), dtype=float)
    for a in range(3):
        for b in range(3):
            j = a * 3 + b
            for c in range(5):
                key = f"{a},{b},{c}"
                T[c, j] = float(triple_class_C[key])
    return T


def _svd_energy_ratios(T: np.ndarray) -> Tuple[np.ndarray, float]:
    s = np.linalg.svd(T, compute_uv=False)
    e = s**2
    total = float(np.sum(e))
    cum3 = float(np.sum(e[:3]) / total)
    return s, cum3


def _corr_from_sigma(Sigma: np.ndarray, i: int, j: int) -> float:
    return float(Sigma[i, j] / math.sqrt(Sigma[i, i] * Sigma[j, j]))


def _tex_float(x: float, nd: int = 12) -> str:
    # fixed decimal, trimmed
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


def write_eq_tex(*, out_path: Path, arity_json: Path, cov_json: Path) -> None:
    aj = _load_json(arity_json)
    cj = _load_json(cov_json)

    triple = "3x3x5"
    rho335 = float(aj["triple_rho_max"][triple])
    ratio = float(aj["triple_rho_max_ratio"][triple])
    lam = rho335 / ratio

    r2 = _perron_root_A2()
    delta_coll = (rho335 - r2) / r2

    # SVD residual (raw, not c-centered) and epsilon_extra
    C = aj["triple_class_C"][triple]
    T = _build_T_from_C(C)
    _, cum3 = _svd_energy_ratios(T)
    eps_extra = 1.0 - cum3

    # Bias spectrum: compare harmonic amplitudes via already-exported summary numbers if present.
    # We recompute from the raw tensor: along c-axis, only j=1,2 carry nontrivial Fourier modes for real data.
    # Here we use the exported summary in the LaTeX table; but for diagnostics we only need a robust scalar:
    # take the maximum modulus over entries of j=1 and j=2 Fourier matrices.
    omega = complex(math.cos(2 * math.pi / 5), math.sin(2 * math.pi / 5))
    A1 = np.zeros((3, 3), dtype=complex)
    A2 = np.zeros((3, 3), dtype=complex)
    for a in range(3):
        for b in range(3):
            f = np.array([T[c, a * 3 + b] for c in range(5)], dtype=complex)
            A1[a, b] = (1.0 / 5.0) * sum(f[c] * (omega ** (-1 * c)) for c in range(5))
            A2[a, b] = (1.0 / 5.0) * sum(f[c] * (omega ** (-2 * c)) for c in range(5))
    maxA1 = float(np.max(np.abs(A1)))
    maxA2 = float(np.max(np.abs(A2)))
    max_ratio = maxA2 / maxA1 if maxA1 > 0 else float("nan")

    # Rate spectrum: compare worst j3=±1 vs j3=±2 in the rho table (pure collision axis is (0,0,j3)).
    rho_j1 = float(aj["triple_rho"][triple]["0,0,1"])
    rho_j2 = float(aj["triple_rho"][triple]["0,0,2"])
    rate_ratio = rho_j2 / rho_j1

    # Correlation Corr(nu,xi) from covariance_worst_character Sigma
    Sigma = np.array(cj["Sigma"], dtype=float)
    corr_nu_xi = _corr_from_sigma(Sigma, 1, 2)  # (chi,nu,xi) ordering in that JSON/table

    # GRH-style diagnostic: compare rho335 against sqrt(lambda)
    grh_ratio = rho335 / math.sqrt(lam)

    lines: list[str] = []
    lines.append("% Generated by scripts/exp_arity_335_cross_layer_diagnostics.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\Delta_{\\mathrm{coll}}"
        ":=\\frac{\\rho_{3,3,5}-r_2}{r_2}"
        f"&\\approx { _tex_float(delta_coll, 9) },\\\\"
    )
    lines.append(
        "\\varepsilon_{\\mathrm{extra}}"
        ":=1-\\frac{s_1^2+s_2^2+s_3^2}{\\sum_i s_i^2}"
        f"&\\approx { _tex_float(eps_extra, 9) },\\\\"
    )
    lines.append(
        "\\mathrm{Corr}(\\nu,\\xi)"
        f"&\\approx { _tex_float(corr_nu_xi, 6) },\\\\"
    )
    lines.append(
        "\\frac{\\max|A^{(2)}|}{\\max|A^{(1)}|}"
        f"&\\approx { _tex_float(max_ratio, 12) },\\qquad"
        "\\frac{\\rho(0,0,2)}{\\rho(0,0,1)}"
        f"\\approx { _tex_float(rate_ratio, 12) },\\\\"
    )
    lines.append(
        "\\frac{\\rho_{3,3,5}}{\\sqrt{\\lambda}}"
        f"&\\approx { _tex_float(grh_ratio, 12) }."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Cross-layer diagnostics for arity 3x3x5.")
    parser.add_argument(
        "--arity-json",
        type=str,
        default=str(
            Path(__file__).resolve().parent.parent
            / "artifacts/export/sync_kernel_real_input_40_arity_3d_N2_335.json"
        ),
        help="Input arity JSON path.",
    )
    parser.add_argument(
        "--cov-json",
        type=str,
        default=str(
            Path(__file__).resolve().parent.parent
            / "artifacts/export/real_input_40_covariance_worst_character.json"
        ),
        help="Input covariance JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_arity_335_cross_layer_diagnostics.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()

    write_eq_tex(
        out_path=Path(args.tex_out),
        arity_json=Path(args.arity_json),
        cov_json=Path(args.cov_json),
    )
    print(f"[arity-335-cross] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

