#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Exact enumeration of the fold-aware restriction gauge anomaly G_m.

This script is English-only by repository convention.

It defines:
  r_{m+1->m}  : naive truncation of a length-(m+1) micro word to length m
  r~_{m+1->m} : fold-aware restriction, i.e. prefix of Fold_{m+1}
  G_m(omega)  : Hamming distance between the two length-m outputs

Outputs:
- artifacts/export/fold_gauge_anomaly_stats.json
- sections/generated/tab_fold_gauge_anomaly_stats.tex
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, paper_root
from common_fold_map_cache import fold_map_packed
from common_phi_fold import Progress


ROOT = paper_root()
GEN = ROOT / "sections" / "generated"


def build_fold_map(m: int, prog: Progress) -> object:
    """Map w in [0,2^m) to packed Fold_m(word(w)) in [0,2^m)."""
    # Use the shared cached builder to avoid repeated O(2^m) work across scripts.
    return fold_map_packed(m, prog=prog)


def omega_star(m: int) -> List[int]:
    """Explicit omega*(m) from the manuscript (length m+1)."""
    w = [0] * (m + 1)
    for k in range(1, m + 1):
        r = k % 3
        w[k - 1] = 1 if r in (1, 2) else 0
    w[m] = 1 if (m % 3) == 1 else 0
    return w


def pack_bits(bits: List[int]) -> int:
    x = 0
    for b in bits:
        x = (x << 1) | (1 if b else 0)
    return x


@dataclass
class Row:
    m: int
    total: int
    mean: float
    mean_over_m: float
    max_g: int
    max_over_m: float
    omega_star_g: int


def write_tex(rows: List[Row], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_gauge_anomaly.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.12}")
    lines.append("\\begin{tabular}{rrrrrr}")
    lines.append("\\toprule")
    lines.append(
        "$m$ & $|\\Omega_{m+1}|$ & $\\bar G_m$ & $\\bar G_m/m$ & $\\max G_m$ & $G_m(\\omega^\\star)$ \\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.m} & {r.total} & {r.mean:.6g} & {r.mean_over_m:.6g} & {r.max_g} & {r.omega_star_g} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Exact enumeration of the gauge anomaly $G_m(\\omega)$ under the uniform baseline $\\omega\\sim\\mathrm{Unif}(\\Omega_{m+1})$ for $m\\le 20$. Here $\\bar G_m=\\mathbb{E}[G_m]$, and $\\omega^\\star$ is the explicit worst-case construction used in Theorem~\\ref{thm:fold-gauge-anomaly-max}.}"
    )
    lines.append("\\label{tab:fold_gauge_anomaly_stats}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    t0 = time.time()
    prog = Progress("fold_gauge_anomaly", every_seconds=20.0)

    m_max = 20
    fold_maps: Dict[int, object] = {}
    # Prebuild fold maps for m=2..21 (we need m+1 up to 21; m=1 uses size=4 too).
    for L in range(2, m_max + 2):
        fold_maps[L] = build_fold_map(L, prog)

    rows: List[Row] = []
    omega_star_prefixes: Dict[int, Dict[str, str]] = {}

    for m in range(1, m_max + 1):
        L = m + 1
        size = 1 << L
        fold_map_L = fold_maps[L]

        total_g = 0
        max_g = -1
        argmax_w = 0

        for w in range(size):
            prefix_m = w >> 1
            folded_L = int(fold_map_L[w])
            rem_m = folded_L >> 1
            g = int(prefix_m ^ rem_m).bit_count()
            total_g += g
            if g > max_g:
                max_g = g
                argmax_w = w
            prog.tick(f"m={m} w={w}/{size} max_g={max_g}")

        mean = total_g / float(size)
        mean_over_m = mean / float(m)

        w_star_bits = omega_star(m)
        w_star = pack_bits(w_star_bits)
        prefix_star = w_star >> 1
        folded_star = int(fold_map_L[w_star])
        rem_star = folded_star >> 1
        g_star = int(prefix_star ^ rem_star).bit_count()

        rows.append(
            Row(
                m=m,
                total=size,
                mean=mean,
                mean_over_m=mean_over_m,
                max_g=max_g,
                max_over_m=max_g / float(m),
                omega_star_g=g_star,
            )
        )

        # Store a small audit snippet for omega* and argmax.
        def _bits_str(x: int, n: int) -> str:
            return "".join("1" if ((x >> (n - 1 - i)) & 1) else "0" for i in range(n))

        omega_star_prefixes[str(m)] = {
            "omega_star": _bits_str(w_star, L),
            "r_prefix": _bits_str(prefix_star, m),
            "folded": _bits_str(folded_star, L),
            "rem_prefix": _bits_str(rem_star, m),
            "Gm": str(g_star),
            "argmax_omega": _bits_str(argmax_w, L),
            "argmax_Gm": str(max_g),
        }

        print(
            f"[fold_gauge_anomaly] done m={m} mean={mean:.6g} mean/m={mean_over_m:.6g} max={max_g} G(omega*)={g_star}",
            flush=True,
        )

    # Write outputs
    export_path = export_dir() / "fold_gauge_anomaly_stats.json"
    export_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "m_max": m_max,
        "rows": [r.__dict__ for r in rows],
        "audit": omega_star_prefixes,
        "generated_at_unix_s": time.time(),
    }
    export_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"[fold_gauge_anomaly] wrote {export_path}", flush=True)

    tex_path = GEN / "tab_fold_gauge_anomaly_stats.tex"
    write_tex(rows, tex_path)
    print(f"[fold_gauge_anomaly] wrote {tex_path}", flush=True)


if __name__ == "__main__":
    main()

