#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spectral-gap alignment diagnostics for group unification.

We extract two reproducible signals already present in the paper:
  (1) worst twisted spectral ratios rho/lambda for selected 3D residue tensors,
      and their induced spectral-gap scale -log(rho/lambda);
  (2) a low-q R\'enyi near-monofractal check: h3 ≈ 2 h2 and d3 ≈ d2^2.

Inputs (generated elsewhere):
  - artifacts/export/real_input_40_dirichlet_mertens_tensor_anova.json
  - artifacts/export/fold_collision_renyi_spectrum.json

Outputs:
  - artifacts/export/group_unification_spectral_alignment_diagnostics.json
  - sections/generated/eq_group_unification_spectral_alignment_diagnostics.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List

from common_paths import export_dir, generated_dir


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _tex_float(x: float, nd: int = 12) -> str:
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


@dataclass(frozen=True)
class _AnovaKey:
    triple: str
    third_axis: str


def _find_anova_ratio(*, rows: List[Dict[str, Any]], key: _AnovaKey) -> float:
    for r in rows:
        if str(r.get("triple")) == key.triple and str(r.get("third_axis")) == key.third_axis:
            return float(r["rho_over_lambda"])
    raise KeyError(f"ANOVA row not found for triple={key.triple} third_axis={key.third_axis}")


def _find_renyi_row(*, rows: List[Dict[str, Any]], q: int) -> Dict[str, Any]:
    for r in rows:
        if int(r.get("q")) == q:
            return r
    raise KeyError(f"Renyi row not found for q={q}")


def write_outputs(
    *,
    anova_json: Path,
    renyi_json: Path,
    tex_out: Path,
    json_out: Path,
) -> None:
    aj = _load_json(anova_json)
    rj = _load_json(renyi_json)

    anova_rows = aj["rows"]
    renyi_rows = rj["rows"]

    # Selected 3D tensors used as compact anchors in the paper text.
    # Note: 3x3x5 is taken with third-axis N2 (collision axis) to match arity-335 selection law tables.
    anova_keys = [
        _AnovaKey(triple="3x2x2", third_axis="Ne"),
        _AnovaKey(triple="3x3x3", third_axis="Ne"),
        _AnovaKey(triple="3x3x5", third_axis="N2"),
    ]

    ratio: Dict[str, float] = {}
    gap: Dict[str, float] = {}
    tau_mix: Dict[str, float] = {}
    for k in anova_keys:
        rk = _find_anova_ratio(rows=anova_rows, key=k)
        ratio[k.triple] = rk
        gk = -math.log(rk)
        gap[k.triple] = gk
        tau_mix[k.triple] = 1.0 / gk if gk > 0 else float("inf")

    # Low-q Renyi rows
    row2 = _find_renyi_row(rows=renyi_rows, q=2)
    row3 = _find_renyi_row(rows=renyi_rows, q=3)
    r2 = float(row2["r_q"])
    r3 = float(row3["r_q"])
    h2 = float(row2["h_q"])
    h3 = float(row3["h_q"])

    two_h2 = 2.0 * h2
    diff_h = h3 - two_h2
    rel_h = abs(diff_h) / two_h2 if two_h2 != 0 else float("nan")

    d2 = (2.0**2) / r2
    d3 = (2.0**3) / r3
    ratio_d = d3 / (d2 * d2) if d2 != 0 else float("nan")

    # Geometry-normalized Renyi dimensions: D_q = h_q / ((q-1) log phi)
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    log_phi = math.log(phi)
    D2 = h2 / log_phi
    D3 = (h3 / 2.0) / log_phi
    diff_D = D2 - D3

    out_json: Dict[str, Any] = {
        "inputs": {
            "anova_json": str(anova_json),
            "renyi_json": str(renyi_json),
        },
        "anova_selected": [
            {
                "triple": k.triple,
                "third_axis": k.third_axis,
                "rho_over_lambda": ratio[k.triple],
                "gap_minus_log_rho_over_lambda": gap[k.triple],
                "tau_mix": tau_mix[k.triple],
            }
            for k in anova_keys
        ],
        "renyi_low_q": {
            "r2": r2,
            "r3": r3,
            "h2": h2,
            "h3": h3,
            "two_h2": two_h2,
            "diff_h3_minus_2h2": diff_h,
            "rel_abs_diff_over_2h2": rel_h,
            "d2": d2,
            "d3": d3,
            "ratio_d3_over_d2_sq": ratio_d,
            "phi": phi,
            "log_phi": log_phi,
            "D2": D2,
            "D3": D3,
            "diff_D2_minus_D3": diff_D,
        },
    }

    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(out_json, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_group_unification_spectral_alignment_diagnostics.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\frac{\\rho_{3,2,2}}{\\lambda}"
        f"&\\approx {_tex_float(ratio['3x2x2'], 12)},\\\\"
    )
    lines.append(
        "-\\log\\!\\left(\\rho_{3,2,2}/\\lambda\\right)"
        f"&\\approx {_tex_float(gap['3x2x2'], 12)},\\\\"
    )
    lines.append(
        "\\frac{\\rho_{3,3,3}}{\\lambda}"
        f"&\\approx {_tex_float(ratio['3x3x3'], 12)},\\\\"
    )
    lines.append(
        "-\\log\\!\\left(\\rho_{3,3,3}/\\lambda\\right)"
        f"&\\approx {_tex_float(gap['3x3x3'], 12)},\\\\"
    )
    lines.append(
        "\\frac{\\rho_{3,3,5}}{\\lambda}"
        f"&\\approx {_tex_float(ratio['3x3x5'], 12)},\\\\"
    )
    lines.append(
        "-\\log\\!\\left(\\rho_{3,3,5}/\\lambda\\right)"
        f"&\\approx {_tex_float(gap['3x3x5'], 12)},\\\\"
    )
    lines.append(
        "h_2"
        f"&\\approx {_tex_float(h2, 12)},\\qquad "
        "h_3"
        f"\\approx {_tex_float(h3, 12)},\\\\"
    )
    lines.append(
        "2h_2"
        f"&\\approx {_tex_float(two_h2, 12)},\\qquad "
        "h_3-2h_2"
        f"\\approx {_tex_float(diff_h, 12)},\\\\"
    )
    lines.append(
        "\\frac{|h_3-2h_2|}{2h_2}"
        f"&\\approx {_tex_float(rel_h, 12)},\\\\"
    )
    lines.append(
        "d_2:=\\frac{4}{r_2}"
        f"&\\approx {_tex_float(d2, 12)},\\qquad "
        "d_3:=\\frac{8}{r_3}"
        f"\\approx {_tex_float(d3, 12)},\\\\"
    )
    lines.append(
        "\\frac{d_3}{d_2^2}"
        f"&\\approx {_tex_float(ratio_d, 12)},\\\\"
    )
    lines.append(
        "D_2:=\\frac{h_2}{\\log\\varphi}"
        f"&\\approx {_tex_float(D2, 12)},\\qquad "
        "D_3:=\\frac{h_3}{2\\log\\varphi}"
        f"\\approx {_tex_float(D3, 12)},\\qquad "
        "D_2-D_3"
        f"\\approx {_tex_float(diff_D, 12)}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")

    tex_out.parent.mkdir(parents=True, exist_ok=True)
    tex_out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate spectral alignment diagnostics (LaTeX + JSON).")
    parser.add_argument(
        "--anova-json",
        type=str,
        default=str(export_dir() / "real_input_40_dirichlet_mertens_tensor_anova.json"),
        help="Input ANOVA JSON path.",
    )
    parser.add_argument(
        "--renyi-json",
        type=str,
        default=str(export_dir() / "fold_collision_renyi_spectrum.json"),
        help="Input Renyi spectrum JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_group_unification_spectral_alignment_diagnostics.tex"),
        help="Output LaTeX equation path.",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "group_unification_spectral_alignment_diagnostics.json"),
        help="Output JSON path.",
    )
    args = parser.parse_args()

    write_outputs(
        anova_json=Path(args.anova_json),
        renyi_json=Path(args.renyi_json),
        tex_out=Path(args.tex_out),
        json_out=Path(args.json_out),
    )
    print(f"[group-unification-spectral] wrote {args.tex_out}", flush=True)
    print(f"[group-unification-spectral] wrote {args.json_out}", flush=True)


if __name__ == "__main__":
    main()

