#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit the mod-3 Frobenius congruence induced by the anti-invariant 3-torsion.

For the genus-2 discriminant ridge curve

  C: w^2 = -y(y-1) P_LY(y),   P_LY(y)=256y^3+411y^2+165y+32,

let J=Jac(C). For good primes p != 3, the paper claims a congruence

  L_p( chi_{-3}(p) ) == 0 (mod 3),

where L_p(T)=1-a1 T + a2 T^2 - a1 p T^3 + p^2 T^4 and chi_{-3}(p)=( -3 / p ).

We compute #C(F_p), #C(F_{p^2}), recover (a1,a2), evaluate L_p at T=±1, and
verify the congruence for a small set of good primes.

Outputs:
  - artifacts/export/fold_zm_discriminant_ridge_3torsion_frobenius_mod3_audit.json
  - sections/generated/eq_fold_zm_discriminant_ridge_3torsion_frobenius_mod3_audit.tex
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

from common_paths import export_dir, generated_dir
from exp_fold_zm_discriminant_ridge_jacobian_frobenius_audit import count_C_Fp, count_C_Fp2


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def chi_minus3(p: int) -> int:
    p = int(p)
    if p == 3:
        raise ValueError("chi_{-3}(3) is undefined in the audit (exclude p=3).")
    r = p % 3
    if r == 1:
        return 1
    if r == 2:
        return -1
    raise ValueError(f"unexpected p mod 3 for prime p={p}")


def Lp_eval(p: int, a1: int, a2: int, t: int) -> int:
    p = int(p)
    a1 = int(a1)
    a2 = int(a2)
    t = int(t)
    return 1 - a1 * t + a2 * (t * t) - a1 * p * (t * t * t) + (p * p) * (t**4)


@dataclass(frozen=True)
class Row:
    p: int
    chi_m3: int
    n_fp: int
    n_fp2: int
    a1: int
    a2: int
    Lp_at_chi: int
    Lp_at_1: int
    Lp_at_minus1: int
    Lp_at_chi_mod3: int


def main() -> None:
    t0 = time.time()
    print("[fold-zm-ridge-3torsion-mod3] start", flush=True)

    # Good primes for the discriminant ridge curve: exclude {2,3,31,37}.
    primes = [5, 7, 11, 13, 17, 19]

    rows: List[Row] = []
    for p in primes:
        if p in {2, 3, 31, 37}:
            raise ValueError(f"p={p} is excluded (bad reduction or p=3).")
        chi = chi_minus3(p)

        n1 = count_C_Fp(p)
        n2 = count_C_Fp2(p)
        a1 = p + 1 - n1
        s2 = p * p + 1 - n2
        a2_num = a1 * a1 - s2
        if a2_num % 2 != 0:
            raise RuntimeError(f"Non-integral a2 at p={p}: a1^2 - s2 = {a2_num}")
        a2 = a2_num // 2

        L_chi = Lp_eval(p, a1, a2, chi)
        L1 = Lp_eval(p, a1, a2, 1)
        Lm1 = Lp_eval(p, a1, a2, -1)
        if L_chi % 3 != 0:
            raise RuntimeError(f"Congruence failed at p={p}: L_p(chi)={L_chi} not divisible by 3")

        rows.append(
            Row(
                p=int(p),
                chi_m3=int(chi),
                n_fp=int(n1),
                n_fp2=int(n2),
                a1=int(a1),
                a2=int(a2),
                Lp_at_chi=int(L_chi),
                Lp_at_1=int(L1),
                Lp_at_minus1=int(Lm1),
                Lp_at_chi_mod3=int(L_chi % 3),
            )
        )

    payload: Dict[str, object] = {
        "curve": "w^2 = -y(y-1)(256y^3+411y^2+165y+32)",
        "primes": primes,
        "rows": [asdict(r) for r in rows],
    }

    out_json = export_dir() / "fold_zm_discriminant_ridge_3torsion_frobenius_mod3_audit.json"
    _write_json(out_json, payload)

    # Short TeX snippet: sample congruences L_p(chi_{-3}(p)) ≡ 0 (mod 3).
    tex_lines: List[str] = [
        "% Auto-generated by scripts/exp_fold_zm_discriminant_ridge_3torsion_frobenius_mod3_audit.py",
        "\\[",
        "\\begin{aligned}",
    ]
    for i, r in enumerate(rows):
        t = "1" if r.chi_m3 == 1 else "-1"
        punct = "," if i < len(rows) - 1 else "."
        br = "\\\\" if i < len(rows) - 1 else ""
        tex_lines.append(f"L_{{{r.p}}}({t})&={r.Lp_at_chi}\\equiv 0\\pmod 3{punct}{br}")
    tex_lines.append("\\end{aligned}")
    tex_lines.append("\\]")
    tex_lines.append("")

    out_tex = generated_dir() / "eq_fold_zm_discriminant_ridge_3torsion_frobenius_mod3_audit.tex"
    _write_text(out_tex, "\n".join(tex_lines))

    dt = time.time() - t0
    print(f"[fold-zm-ridge-3torsion-mod3] wrote {out_json}", flush=True)
    print(f"[fold-zm-ridge-3torsion-mod3] wrote {out_tex}", flush=True)
    print(f"[fold-zm-ridge-3torsion-mod3] seconds={dt:.3f}", flush=True)
    print("[fold-zm-ridge-3torsion-mod3] done", flush=True)


if __name__ == "__main__":
    main()

