#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Algebraic certificate for the A4 Newman ratio u4 = Lambda4^2 / r4.

Outputs:
  - artifacts/export/collision_kernel_A4_newman_u4_certificate.json
  - sections/generated/eq_collision_kernel_A4_newman_u4_minpoly.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Dict, List, Tuple

import sympy as sp

from common_paths import export_dir, generated_dir


def _p7() -> sp.Poly:
    x = sp.Symbol("x")
    return sp.Poly(x**5 - 2 * x**4 - 7 * x**3 - 2 * x + 2, x, domain=sp.ZZ)


def perron_root_r4(iters: int = 80) -> float:
    def f(x: float) -> float:
        return x**5 - 2.0 * x**4 - 7.0 * x**3 - 2.0 * x + 2.0

    def df(x: float) -> float:
        return 5.0 * x**4 - 8.0 * x**3 - 21.0 * x**2 - 2.0

    x = 3.85
    for _ in range(iters):
        x = x - f(x) / df(x)
    return x


def negative_real_root_mu_minus(iters: int = 80) -> float:
    def f(x: float) -> float:
        return x**5 - 2.0 * x**4 - 7.0 * x**3 - 2.0 * x + 2.0

    def df(x: float) -> float:
        return 5.0 * x**4 - 8.0 * x**3 - 21.0 * x**2 - 2.0

    x = -1.96
    for _ in range(iters):
        x = x - f(x) / df(x)
    return x


def Q4_poly() -> Tuple[sp.Symbol, sp.Poly, List[int]]:
    t = sp.Symbol("t")
    # Coefficients from t^20 down to t^0.
    coeffs = [
        4,
        -64,
        80,
        -46260,
        -127612,
        1584408,
        7293617,
        76445526,
        -26190147,
        -75382686,
        5220754,
        53887216,
        -42120556,
        1739748,
        -3577332,
        760256,
        144576,
        -54720,
        -10880,
        -64,
        64,
    ]
    expr = sum(sp.Integer(c) * t ** (20 - i) for i, c in enumerate(coeffs))
    return t, sp.Poly(expr, t, domain=sp.ZZ), coeffs


def write_eq_tex(path: Path, coeffs: List[int]) -> None:
    # Render Q4(t) in a compact aligned form.
    # We avoid polynomial pretty-print to keep stable output across SymPy versions.
    def term(c: int, deg: int) -> str:
        if c == 0:
            return ""
        sgn = "+" if c > 0 else "-"
        a = abs(c)
        if deg == 0:
            body = f"{a}"
        elif deg == 1:
            body = "t" if a == 1 else f"{a}t"
        else:
            body = f"t^{{{deg}}}" if a == 1 else f"{a}t^{{{deg}}}"
        return f" {sgn} {body}"

    pieces: List[str] = []
    # Leading term (degree 20) without leading '+'.
    lead = coeffs[0]
    pieces.append(f"{lead}t^{{20}}")
    for i, c in enumerate(coeffs[1:], start=1):
        deg = 20 - i
        pieces.append(term(c, deg))

    poly_tex = "".join(pieces).strip()
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_collision_kernel_A4_newman_u4_certificate.py")
    lines.append("\\begin{equation}\\label{eq:collision_kernel_A4_newman_u4_minpoly}")
    lines.append("\\begin{aligned}")
    lines.append(f"Q_4(t):={{}}&{poly_tex}.")
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate algebraic certificate for u4 = Lambda4^2 / r4.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4_newman_u4_certificate.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_newman_u4_minpoly.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()

    r4 = perron_root_r4()
    mu_minus = negative_real_root_mu_minus()
    lambda4 = abs(mu_minus)
    u4 = (lambda4 * lambda4) / r4
    delta4 = math.log(u4)

    t, Q4, coeffs = Q4_poly()
    Q4QQ = sp.Poly(Q4.as_expr(), t, domain=sp.QQ)
    irr = bool(Q4QQ.is_irreducible)

    # Root checks (numeric, high precision).
    roots = [complex(z) for z in sp.nroots(Q4.as_expr(), n=50)]
    reals = sorted([z.real for z in roots if abs(z.imag) < 1e-30])
    in_window = [x for x in reals if 1.0 < x < 1.01]

    payload: Dict[str, object] = {
        "p7": [1, -2, -7, 0, -2, 2],
        "r4": r4,
        "mu_minus": mu_minus,
        "Lambda4": lambda4,
        "u4": u4,
        "delta4": delta4,
        "Q4_coeffs_deg20_to_0": coeffs,
        "Q4_irreducible_over_QQ": irr,
        "Q4_real_roots_count": len(reals),
        "Q4_real_roots_in_(1,1.01)": in_window,
        "Q4_eval_at_u4": float(Q4QQ.eval(u4)),
        "norm_from_coeffs": coeffs[-1] / coeffs[0],
    }
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[A4-u4-certificate] wrote {jout}", flush=True)

    write_eq_tex(Path(args.tex_out), coeffs)
    print(f"[A4-u4-certificate] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

