#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compute high-precision Dirichlet-side constants for the 10-state sync-kernel B.

Outputs:
  - sections/generated/tab_sync_kernel_B_dirichlet_constants.tex

This script is intentionally self-contained and uses only sympy (already in requirements.txt).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import sympy as sp


def zeta_B(z: sp.Expr) -> sp.Expr:
    return sp.Integer(1) / (
        (z - 1) * (z + 1) * (3 * z - 1) * (z**3 - z**2 + z + 1)
    )


def compute_logM_B(prec: int, max_m: int, small_term_target: sp.Float) -> tuple[sp.Expr, int]:
    """
    log 𝔐_B = log C_B + Σ_{m≥2} μ(m)/m log ζ_B(z_*^m),  with z_* = 1/3.
    Returns (logM_expr, m_used).
    """
    z_star = sp.Rational(1, 3)
    C_B = sp.Rational(243, 272)
    logM = sp.log(C_B)

    m_used = 1
    small_hits = 0
    for m in range(2, max_m + 1):
        mu = sp.mobius(m)
        if mu == 0:
            continue
        term = sp.Rational(int(mu), m) * sp.log(zeta_B(z_star**m))
        term_num = sp.N(term, prec)
        logM += term
        m_used = m

        if abs(term_num) < small_term_target:
            small_hits += 1
            if small_hits >= 8 and m >= 24:
                break
        else:
            small_hits = 0

    return sp.N(logM, prec), m_used


def fmt(x: sp.Expr, digits: int) -> str:
    # Sympy's `N` already returns a high-precision Float; format with fixed digits.
    xx = sp.N(x, digits + 10)
    s = sp.sstr(xx)
    # Ensure plain decimal (no scientific) for typical magnitudes in this file.
    if "e" in s or "E" in s:
        s = f"{float(xx):.{digits}f}"
    else:
        # Trim/round to desired digits after decimal point if possible.
        if "." in s:
            head, tail = s.split(".", 1)
            tail = (tail + "0" * digits)[:digits]
            s = head + "." + tail
    return s


def write_tex(
    out_path: Path,
    *,
    digits: int,
    max_m: int,
    m_used: int,
    logM: sp.Expr,
    M_frak: sp.Expr,
    mertens_const: sp.Expr,
    residue: sp.Expr,
    fp_dirichlet: sp.Expr,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_sync_kernel_B_dirichlet_constants.py")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(
        r"\caption{10 状态同步核 $B$ 的 Dirichlet 口径常数（高精度可审计输出；"
        + rf"$\log\mathfrak{{M}}_B$ 按 Möbius--Abel 闭式求和截断到 $m\le {m_used}$，"
        + rf"脚本上限 $m\le {max_m}$）。}}"
    )
    lines.append(r"\label{tab:sync-kernel-B-dirichlet-constants}")
    lines.append(r"\begin{tabular}{@{}ll@{}}")
    lines.append(r"\toprule")
    lines.append(r"量 & 数值 \\")
    lines.append(r"\midrule")
    lines.append(r"$\lambda$ & $3$ \\")
    lines.append(r"$z_\star=\lambda^{-1}$ & $1/3$ \\")
    lines.append(r"$C_B$（主留数常数） & $243/272$ \\")
    lines.append(
        r"$\log\mathfrak{M}_B$ & $\approx "
        + fmt(logM, digits)
        + r"$ \\"
    )
    lines.append(
        r"$\mathfrak{M}_B=\exp(\log\mathfrak{M}_B)$ & $\approx "
        + fmt(M_frak, digits)
        + r"$ \\"
    )
    lines.append(
        r"$\mathsf{M}_B=\gamma+\log\mathfrak{M}_B$ & $\approx "
        + fmt(mertens_const, digits)
        + r"$ \\"
    )
    lines.append(
        r"$\mathrm{Res}_{s=1}\,\zeta_B(3^{-s})=C_B/\log 3$ & $\approx "
        + fmt(residue, digits)
        + r"$ \\"
    )
    lines.append(
        r"$\mathrm{fp}_{s=1}\bigl(\mathcal{P}_B(s)+\log(s-1)\bigr)=\log\mathfrak{M}_B-\log\log 3$ & $\approx "
        + fmt(fp_dirichlet, digits)
        + r"$ \\"
    )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="High-precision Dirichlet-side constants for sync-kernel B"
    )
    parser.add_argument(
        "--digits",
        type=int,
        default=34,
        help="Decimal digits to print (default: 34)",
    )
    parser.add_argument(
        "--prec",
        type=int,
        default=90,
        help="Sympy evaluation precision in digits (default: 90)",
    )
    parser.add_argument(
        "--max-m",
        type=int,
        default=200,
        help="Max m for Möbius tail (default: 200)",
    )
    parser.add_argument(
        "--out-tex",
        type=str,
        default="",
        help="Output .tex path (default: sections/generated/tab_sync_kernel_B_dirichlet_constants.tex)",
    )
    args = parser.parse_args()

    digits = int(args.digits)
    prec = int(args.prec)
    max_m = int(args.max_m)

    small_target = sp.Float(10) ** sp.Integer(-(digits + 12))

    print("[sync-kernel-B-dirichlet] start", flush=True)
    logM, m_used = compute_logM_B(prec=prec, max_m=max_m, small_term_target=small_target)

    M_frak = sp.N(sp.exp(logM), prec)
    mertens_const = sp.N(sp.EulerGamma + logM, prec)
    residue = sp.N(sp.Rational(243, 272) / sp.log(3), prec)
    fp_dirichlet = sp.N(logM - sp.log(sp.log(3)), prec)

    out_tex = (
        Path(args.out_tex)
        if args.out_tex
        else Path(__file__).resolve().parent.parent / "sections" / "generated" / "tab_sync_kernel_B_dirichlet_constants.tex"
    )

    write_tex(
        out_tex,
        digits=digits,
        max_m=max_m,
        m_used=m_used,
        logM=logM,
        M_frak=M_frak,
        mertens_const=mertens_const,
        residue=residue,
        fp_dirichlet=fp_dirichlet,
    )

    print(f"[sync-kernel-B-dirichlet] log 𝔐_B ~ {sp.N(logM, digits+5)}", flush=True)
    print(f"[sync-kernel-B-dirichlet] wrote {out_tex}", flush=True)
    print("[sync-kernel-B-dirichlet] done", flush=True)


if __name__ == "__main__":
    main()

