#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compare alignment cosine with the folding constant sqrt(5)/phi^2.

Inputs:
  - artifacts/export/real_input_40_local_bigeometry_invariants.json

Outputs:
  - artifacts/export/alignment_cos_vs_sqrt5_phi2.json
  - sections/generated/eq_alignment_cos_vs_sqrt5_phi2.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict

from common_paths import export_dir, generated_dir


def _load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _tex_float(x: float, nd: int = 12) -> str:
    s = f"{x:.{nd}f}"
    s = s.rstrip("0").rstrip(".")
    return s


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare cos(v_perp,u_+) to sqrt(5)/phi^2 (LaTeX + JSON).")
    parser.add_argument(
        "--in-json",
        type=str,
        default=str(export_dir() / "real_input_40_local_bigeometry_invariants.json"),
        help="Input invariants JSON path.",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "alignment_cos_vs_sqrt5_phi2.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_alignment_cos_vs_sqrt5_phi2.tex"),
        help="Output TeX equation path.",
    )
    args = parser.parse_args()

    inv = _load_json(Path(args.in_json))
    cos_vu = float(inv["cos_vperp_u_plus"])

    sqrt5 = math.sqrt(5.0)
    phi = (1.0 + sqrt5) / 2.0
    c_lim = sqrt5 / (phi * phi)

    # Normalized mean degeneracy at m=6 (independent check): \bar d_6 (phi/2)^6 = (64/21) (phi/2)^6.
    dbar6 = 64.0 / 21.0
    c_m6 = dbar6 * (phi / 2.0) ** 6

    delta_lim = cos_vu - c_lim
    delta_m6 = cos_vu - c_m6

    payload: Dict[str, Any] = {
        "input": {"invariants_json": str(args.in_json)},
        "constants": {
            "phi": phi,
            "sqrt5_over_phi2": c_lim,
            "dbar6_times_phi_over_2_pow6": c_m6,
        },
        "observed": {"cos_vperp_u_plus_euclidean": cos_vu},
        "diff": {
            "cos_minus_sqrt5_over_phi2": delta_lim,
            "abs_cos_minus_sqrt5_over_phi2": abs(delta_lim),
            "cos_minus_dbar6_phi_over_2_pow6": delta_m6,
            "abs_cos_minus_dbar6_phi_over_2_pow6": abs(delta_m6),
        },
    }

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_alignment_cos_vs_sqrt5_phi2.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\cos(v_\\perp,u_+)\\ \\text{(Euclidean)}"
        f"&\\approx {_tex_float(cos_vu, 12)},\\\\"
    )
    lines.append(
        "\\frac{\\sqrt5}{\\varphi^2}"
        f"&\\approx {_tex_float(c_lim, 12)},\\\\"
    )
    lines.append(
        "\\cos(v_\\perp,u_+)-\\frac{\\sqrt5}{\\varphi^2}"
        f"&\\approx {_tex_float(delta_lim, 12)},\\\\"
    )
    lines.append(
        "\\overline d_6\\left(\\frac{\\varphi}{2}\\right)^6"
        f"&\\approx {_tex_float(c_m6, 12)},\\\\"
    )
    lines.append(
        "\\cos(v_\\perp,u_+)-\\overline d_6\\left(\\frac{\\varphi}{2}\\right)^6"
        f"&\\approx {_tex_float(delta_m6, 12)}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")

    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[align-const] wrote {jout}", flush=True)
    print(f"[align-const] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

