#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit the phase windows of the subleading mode for real-input-40.

Goal
----
Given the phase dataset produced by exp_real_input_40_time_correlation_phase.py,
extract a discrete, reproducible certificate of where the subleading eigenvalue
is real (negative/positive) versus genuinely complex.

Outputs
-------
- artifacts/export/real_input_40_time_correlation_phase_windows.json
- sections/generated/tab_real_input_40_time_correlation_phase_windows.tex
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

from common_paths import export_dir, generated_dir


def _fmt(x: float) -> str:
    if math.isnan(x):
        return "\\mathrm{NaN}"
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _classify(row: Dict[str, float], eps: float) -> str:
    im = float(row.get("lambda2_im", 0.0))
    re = float(row.get("lambda2_re", 0.0))
    if abs(im) > eps:
        return "complex"
    if re < 0.0:
        return "neg_real"
    return "pos_real"


@dataclass(frozen=True)
class Segment:
    kind: str
    t_lo: float
    t_hi: float
    n: int
    rho2_min: float
    rho2_max: float
    omega_min: float
    omega_max: float
    Tosc_min: float
    Tosc_max: float


def _segments(grid: List[Dict[str, float]], eps: float) -> List[Segment]:
    if not grid:
        return []
    rows = sorted(grid, key=lambda r: float(r["t"]))
    segs: List[Segment] = []

    cur_kind = _classify(rows[0], eps=eps)
    cur_rows: List[Dict[str, float]] = [rows[0]]

    def flush() -> None:
        nonlocal cur_rows, cur_kind
        ts = [float(r["t"]) for r in cur_rows]
        rho2s = [float(r["rho2"]) for r in cur_rows]
        omegas = [float(r["omega"]) for r in cur_rows]
        Toscs = [float(r["Tosc"]) for r in cur_rows]
        segs.append(
            Segment(
                kind=cur_kind,
                t_lo=min(ts),
                t_hi=max(ts),
                n=len(cur_rows),
                rho2_min=min(rho2s),
                rho2_max=max(rho2s),
                omega_min=min(omegas),
                omega_max=max(omegas),
                Tosc_min=min(Toscs),
                Tosc_max=max(Toscs),
            )
        )
        cur_rows = []

    for r in rows[1:]:
        k = _classify(r, eps=eps)
        if k != cur_kind:
            flush()
            cur_kind = k
        cur_rows.append(r)
    flush()

    return segs


def _write_tex(path: Path, eps: float, segs: List[Segment]) -> None:
    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_time_correlation_phase_windows.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{次主模态内生相位的离散相区证书（真实输入 40 状态核；$\\chi$ 切片 $\\theta(t)=(t,0,-t)$）。"
        + "基于脚本 \\texttt{scripts/exp\\_real\\_input\\_40\\_time\\_correlation\\_phase.py} 输出的离散网格，"
        + "按 $\\varepsilon="
        + _fmt(eps)
        + "$ 判定 $|\\Im\\lambda_2(t)|>\\varepsilon$ 为复相区（\\texttt{complex}），否则以 $\\Re\\lambda_2(t)$ 的符号区分实相区（\\texttt{neg\\_real}/\\texttt{pos\\_real}）。"
        + "每行对应一个极大连续网格段，并给出 $\\rho_2(t)=|\\lambda_2|/\\lambda_1$、$\\omega(t)=\\arg(\\lambda_2)$ 与 $T_{\\mathrm{osc}}(t)=2\\pi/|\\omega(t)|$ 的段内范围。}"
    )
    lines.append("\\label{tab:real-input-40-time-corr-phase-windows}")
    lines.append("\\begin{tabular}{l r r r r r r}")
    lines.append("\\toprule")
    lines.append(
        "kind & $t_{\\min}$ & $t_{\\max}$ & $\\#\\mathrm{pts}$ & $\\rho_2$ range & $\\omega$ range & $T_{\\mathrm{osc}}$ range\\\\"
    )
    lines.append("\\midrule")

    def kind_label(k: str) -> str:
        if k == "complex":
            return "complex"
        if k == "neg_real":
            return "neg\\_real"
        if k == "pos_real":
            return "pos\\_real"
        return k

    for s in segs:
        lines.append(
            kind_label(s.kind)
            + f" & {_fmt(s.t_lo)} & {_fmt(s.t_hi)} & {int(s.n)}"
            + f" & ${_fmt(s.rho2_min)}\\,\\sim\\,{_fmt(s.rho2_max)}$"
            + f" & ${_fmt(s.omega_min)}\\,\\sim\\,{_fmt(s.omega_max)}$"
            + f" & ${_fmt(s.Tosc_min)}\\,\\sim\\,{_fmt(s.Tosc_max)}$\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract discrete phase windows (real vs complex subleading mode)."
    )
    parser.add_argument(
        "--phase-json",
        type=str,
        default=str(export_dir() / "real_input_40_time_correlation_phase.json"),
        help="Input JSON from exp_real_input_40_time_correlation_phase.py",
    )
    parser.add_argument(
        "--eps",
        type=float,
        default=1e-12,
        help="Imaginary-part threshold for classifying complex vs real.",
    )
    parser.add_argument(
        "--out-json",
        type=str,
        default=str(export_dir() / "real_input_40_time_correlation_phase_windows.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--out-tex",
        type=str,
        default=str(
            generated_dir() / "tab_real_input_40_time_correlation_phase_windows.tex"
        ),
        help="Output TeX table path.",
    )
    args = parser.parse_args()

    inp = Path(args.phase_json)
    data = json.loads(inp.read_text(encoding="utf-8"))
    grid = data.get("grid", [])
    if not grid:
        raise SystemExit("[phase-windows] empty input grid")

    segs = _segments(grid, eps=float(args.eps))

    out_json = Path(args.out_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "eps": float(args.eps),
        "n_points": int(len(grid)),
        "n_segments": int(len(segs)),
        "segments": [asdict(s) for s in segs],
    }
    out_json.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    out_tex = Path(args.out_tex)
    _write_tex(out_tex, eps=float(args.eps), segs=segs)

    print(f"[phase-windows] wrote {out_json}", flush=True)
    print(f"[phase-windows] wrote {out_tex}", flush=True)
    print("[phase-windows] done", flush=True)


if __name__ == "__main__":
    main()
