#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Orbit charge of Fold^{bin}_6 fibers under the unique geometric involution in Aut(Q6).

All code is English-only by repository convention.

Setup:
  - Omega_6 = {0,1}^6, with the hypercube graph Q6 (Hamming adjacency).
  - int_6(omega_1..omega_6) = sum_{k=1}^6 omega_k 2^{6-k}.
  - Fold^{bin}_6(n) = Zeckendorf digits prefix of length 6 for n in {0,...,63}.
  - Label map: F6(omega) := Fold^{bin}_6(int_6(omega)) in X6.

Geometric involution (the nontrivial generator of Stab_geo(F6) in Aut(Q6)):
  sigma_geo(omega_1,...,omega_6) = (1-omega_5, omega_2, omega_3, omega_4, 1-omega_1, omega_6).

For each stable type x in X6, let Fx := {omega in Omega_6 : F6(omega)=x}.
Since sigma_geo preserves F6, it restricts to an involution on Fx. Define the orbit charge
  q(x) := (f_x, p_x),
where f_x is the number of fixed points in Fx and p_x is the number of 2-cycles. Then |Fx| = f_x + 2 p_x.

We enumerate q(x) for all x in X6, and export an auditable histogram + a compact LaTeX table.

Outputs:
  - artifacts/export/foldbin6_geo_orbit_charge.json
  - sections/generated/tab_foldbin6_geo_orbit_charge.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str, zeckendorf_digits


Bits6 = Tuple[int, int, int, int, int, int]


def _bits6(n: int) -> Bits6:
    """Return (b1..b6) for the 6-bit binary expansion of n in [0,63]."""
    if n < 0 or n >= 64:
        raise ValueError("n must be in [0,63]")
    return (
        (n >> 5) & 1,
        (n >> 4) & 1,
        (n >> 3) & 1,
        (n >> 2) & 1,
        (n >> 1) & 1,
        (n >> 0) & 1,
    )


def _int6(bits: Bits6) -> int:
    """Binary index int_6(omega1..omega6)=sum_{k=1}^6 omega_k 2^{6-k}."""
    b1, b2, b3, b4, b5, b6 = bits
    return (b1 << 5) | (b2 << 4) | (b3 << 3) | (b4 << 2) | (b5 << 1) | (b6 << 0)


def _foldbin6_label(n: int) -> str:
    """Fold^{bin}_6(n): Zeckendorf digits prefix of length 6 for n ∈ [0,63]."""
    # For m=6, K(6)=9 (F_{10}=55 ≤ 63 < F_{11}=89), so digits up to k=9 are exact.
    digits = zeckendorf_digits(n, 9)  # digits for weights F_{k+1}, k=1..9
    return word_to_str(digits[:6])


def _sigma_geo_bits(b: Bits6) -> Bits6:
    """sigma_geo(omega_1..omega_6) = (1-omega_5, omega_2, omega_3, omega_4, 1-omega_1, omega_6)."""
    b1, b2, b3, b4, b5, b6 = b
    return (1 - b5, b2, b3, b4, 1 - b1, b6)


def _sigma_geo_int(n: int, *, bits_cache: Sequence[Bits6]) -> int:
    return _int6(_sigma_geo_bits(bits_cache[n]))


@dataclass(frozen=True)
class OrbitCharge:
    fixed_points: int
    two_cycles: int

    @property
    def size(self) -> int:
        return self.fixed_points + 2 * self.two_cycles


def _fmt_q(q: OrbitCharge) -> str:
    return f"({q.fixed_points},{q.two_cycles})"


def _write_table_tex(
    *,
    q_hist: Dict[Tuple[int, int], int],
    full_fixed_types: List[str],
    out_path: Path,
) -> None:
    rows = sorted(((f, p, cnt) for (f, p), cnt in q_hist.items()), key=lambda t: (t[0] + 2 * t[1], t[0], t[1]))

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_foldbin6_geo_orbit_charge.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\caption{几何稳定子生成元 $\\sigma_{\\mathrm{geo}}$ 在 window-$6$ 纤维上的轨道电荷直方图。}")
    lines.append("\\label{tab:foldbin6_geo_orbit_charge}")
    lines.append("\\begin{tabular}{rrrr}")
    lines.append("\\toprule")
    lines.append("$f_x$ & $p_x$ & $|F_x|=f_x+2p_x$ & count \\\\")
    lines.append("\\midrule")
    for f, p, cnt in rows:
        lines.append(f"{f} & {p} & {f + 2 * p} & {cnt} \\\\")
    lines.append("\\midrule")
    ff = ",\\ ".join([f"\\texttt{{{w}}}" for w in full_fixed_types])
    lines.append(f"\\multicolumn{{4}}{{l}}{{\\footnotesize Full-fixed fibers ($f_x=4,p_x=0$): {ff}.}}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute the sigma_geo orbit charge q(x) on Fold^{bin}_6 fibers.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "foldbin6_geo_orbit_charge.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-tab-out",
        type=str,
        default=str(generated_dir() / "tab_foldbin6_geo_orbit_charge.tex"),
        help="Path to generated TeX table snippet (\\input{}).",
    )
    args = ap.parse_args()

    bits_cache: List[Bits6] = [_bits6(n) for n in range(64)]
    label: List[str] = [_foldbin6_label(n) for n in range(64)]
    x6: List[str] = sorted(set(label))

    # Sanity: sigma_geo stabilizes labels.
    for n in range(64):
        n2 = _sigma_geo_int(n, bits_cache=bits_cache)
        if label[n2] != label[n]:
            raise RuntimeError(f"sigma_geo does not stabilize labels: n={n} -> {n2} {label[n]} != {label[n2]}")

    # Fibers on Omega_6 are in bijection with fibers on {0,...,63} via int_6.
    fibers: Dict[str, List[int]] = {x: [] for x in x6}
    for n in range(64):
        fibers[label[n]].append(n)

    # Compute orbit charges.
    q_by_x: Dict[str, OrbitCharge] = {}
    for x in x6:
        pts = fibers[x]
        unseen = set(pts)
        fixed = 0
        twocy = 0
        while unseen:
            n = next(iter(unseen))
            n2 = _sigma_geo_int(n, bits_cache=bits_cache)
            if n2 == n:
                fixed += 1
                unseen.remove(n)
            else:
                # Involution implies a 2-cycle.
                if n2 not in unseen:
                    raise RuntimeError(f"orbit mismatch in fiber {x}: {n} -> {n2} not in same unseen set")
                n3 = _sigma_geo_int(n2, bits_cache=bits_cache)
                if n3 != n:
                    raise RuntimeError(f"sigma_geo not an involution on ints: {n} -> {n2} -> {n3}")
                twocy += 1
                unseen.remove(n)
                unseen.remove(n2)
        q_by_x[x] = OrbitCharge(fixed_points=fixed, two_cycles=twocy)

    q_hist: Dict[Tuple[int, int], int] = {}
    for q in q_by_x.values():
        key = (q.fixed_points, q.two_cycles)
        q_hist[key] = q_hist.get(key, 0) + 1

    full_fixed_types = sorted([x for x, q in q_by_x.items() if (q.fixed_points, q.two_cycles) == (4, 0)])

    fiber_sizes_hist: Dict[int, int] = {}
    for pts in fibers.values():
        fiber_sizes_hist[len(pts)] = fiber_sizes_hist.get(len(pts), 0) + 1

    payload: Dict[str, object] = {
        "m": 6,
        "K_of_m": 9,
        "int6_convention": "int_6(omega1..omega6)=sum_{k=1}^6 omega_k 2^{6-k}",
        "sigma_geo": {
            "formula": "(1-omega5, omega2, omega3, omega4, 1-omega1, omega6)",
            "perm_0_indexed": [4, 1, 2, 3, 0, 5],
            "mask_bits_b1_to_b6": "100010",
            "mask_int": 34,
        },
        "x6_size": len(x6),
        "fiber_sizes_histogram": {str(k): int(v) for k, v in sorted(fiber_sizes_hist.items())},
        "q_histogram": {f"({f},{p})": int(cnt) for (f, p), cnt in sorted(q_hist.items())},
        "full_fixed_types_q_4_0": full_fixed_types,
        "q_by_type": {
            x: {
                "fixed_points": q.fixed_points,
                "two_cycles": q.two_cycles,
                "fiber_size": q.size,
                "fiber_ints": sorted(fibers[x]),
                "fiber_bits": ["".join(str(b) for b in _bits6(n)) for n in sorted(fibers[x])],
            }
            for x, q in q_by_x.items()
        },
    }

    # Write outputs.
    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = Path(str(args.tex_tab_out))
    _write_table_tex(q_hist=q_hist, full_fixed_types=full_fixed_types, out_path=tex_out)

    print(f"[foldbin6_geo_orbit_charge] wrote {json_out}", flush=True)
    print(f"[foldbin6_geo_orbit_charge] wrote {tex_out}", flush=True)


if __name__ == "__main__":
    main()

