#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: Frobenius number of the window-6 tail-offset semigroup.

All output is English-only by repository convention.

We define the numerical semigroup
  S_6 := <21,34,55> ⊂ N
and compute its Frobenius number g(S_6) and conductor c(S_6)=g+1.

Outputs:
  - artifacts/export/window6_tail_semigroup_frobenius.json
  - sections/generated/eq_window6_tail_semigroup_frobenius.tex
"""

from __future__ import annotations

import argparse
import heapq
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class FrobeniusResult:
    generators: Tuple[int, ...]
    frobenius: int
    conductor: int
    apery_a: int
    apery: Tuple[int, ...]  # minimal element for each residue mod a


def _apery_set_via_dijkstra(*, a: int, steps: List[int]) -> List[int]:
    """Compute Apéry set w.r.t. a, using steps that are coprime to a.

    Nodes are residues r mod a, dist[r] = minimal nonnegative sum of steps ≡ r (mod a).
    """
    dist = [10**30] * a
    dist[0] = 0
    pq: List[Tuple[int, int]] = [(0, 0)]
    while pq:
        d, r = heapq.heappop(pq)
        if d != dist[r]:
            continue
        for s in steps:
            r2 = (r + (s % a)) % a
            d2 = d + s
            if d2 < dist[r2]:
                dist[r2] = d2
                heapq.heappush(pq, (d2, r2))
    if any(x >= 10**29 for x in dist):
        raise RuntimeError("Apéry computation failed: unreachable residue class.")
    return dist


def compute_frobenius_semigroup(gens: Tuple[int, ...]) -> FrobeniusResult:
    gens_sorted = tuple(sorted(gens))
    a = gens_sorted[0]
    steps = [g for g in gens_sorted[1:] if g % a != 0]
    apery = _apery_set_via_dijkstra(a=a, steps=steps)
    g = max(apery) - a
    c = g + 1
    return FrobeniusResult(
        generators=gens_sorted,
        frobenius=g,
        conductor=c,
        apery_a=a,
        apery=tuple(int(x) for x in apery),
    )


def _reachable_dp(*, gens: Tuple[int, ...], N: int) -> List[bool]:
    ok = [False] * (N + 1)
    ok[0] = True
    for n in range(1, N + 1):
        ok[n] = any(n - g >= 0 and ok[n - g] for g in gens)
    return ok


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute g(S_6) and c(S_6) for <21,34,55>.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_tail_semigroup_frobenius.json"),
        help="Output JSON path.",
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_window6_tail_semigroup_frobenius.tex"),
        help="Output TeX equation path.",
    )
    args = ap.parse_args()

    gens = (21, 34, 55)
    res = compute_frobenius_semigroup(gens)

    # Verify by brute DP up to conductor + max(gen).
    ok = _reachable_dp(gens=res.generators, N=res.conductor + max(res.generators) + 50)
    assert ok[0]
    gaps = [n for n in range(res.conductor) if not ok[n]]
    if gaps and max(gaps) != res.frobenius:
        raise AssertionError("Mismatch: computed Frobenius number not equal to max gap.")
    if any(not ok[n] for n in range(res.conductor, len(ok))):
        raise AssertionError("Mismatch: DP indicates non-reachability above conductor.")

    payload: Dict[str, object] = {
        "generators": list(res.generators),
        "apery": {
            "a": res.apery_a,
            "values": list(res.apery),
            "max_apery": max(res.apery),
        },
        "frobenius": res.frobenius,
        "conductor": res.conductor,
        "gaps_below_conductor_count": len(gaps),
        "max_gap_check": max(gaps) if gaps else None,
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = Path(str(args.tex_out))
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_window6_tail_semigroup_frobenius.py")
    lines.append("\\begin{equation}\\label{eq:window6_tail_semigroup_frobenius}")
    lines.append(f"g(S_6)={res.frobenius},\\qquad c(S_6)={res.conductor}.")
    lines.append("\\end{equation}")
    lines.append("")
    tex_out.write_text("\n".join(lines), encoding="utf-8")

    # Hard expectations (guard rails).
    if res.frobenius != 659 or res.conductor != 660:
        raise AssertionError(f"Unexpected result: g={res.frobenius}, c={res.conductor}")

    print(f"File: {json_out.relative_to(export_dir().parent.parent)}")
    print(f"File: {tex_out.relative_to(generated_dir().parent.parent)}")


if __name__ == "__main__":
    main()

