#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Exact algebraic audits for the 3D weighted sync-kernel (u,v,w).

This script produces small LaTeX snippets that are fully checkable from the
closed-form coefficients given in `sections/appendix/sync_kernel/app__vector-potential.tex`.

Outputs:
  - sections/generated/eq_sync_kernel_3d_critical_w_half_delta.tex
  - sections/generated/eq_sync_kernel_3d_hessian_inverse_exact.tex
  - sections/generated/eq_sync_kernel_3d_quadratic_orthobasis.tex
  - artifacts/export/sync_kernel_weighted_3d_exact_audits.json

All output is English-only by repository convention.
"""

from __future__ import annotations

import json
from fractions import Fraction
from pathlib import Path
from typing import Dict, Tuple

from common_paths import export_dir, generated_dir


def delta_coeffs(u: Fraction, v: Fraction, w: Fraction) -> Tuple[Fraction, Fraction, Fraction, Fraction, Fraction, Fraction]:
    """Return (c1..c6) for Delta(z;u,v,w) = 1 + sum_{k=1}^6 c_k z^k."""
    c1 = -(u * w + 1)
    c2 = -u * (v * v * w + v * w + v + 2)
    c3 = u * v * (u * w + 1) * (v * w + w + 1)
    c4 = -u * (
        u * u * v * v * w**3
        - 3 * u * v * v * w
        + u * v * (w * w + w - 2)
        + u * (w * w - w)
        + v * v * w
    )
    c5 = u * v * w * (
        u**3 * v * w**3
        - 2 * u * u * v * w
        - u * u * w**3
        - u * v * (w + 1)
        - u
        + v
    )
    c6 = u * u * v * v * w * (2 * w - 1) * (u * u * w + u + 1)
    return c1, c2, c3, c4, c5, c6


def _frac_tex(x: Fraction) -> str:
    if x.denominator == 1:
        return str(x.numerator)
    if x.numerator < 0:
        return f"-\\frac{{{-x.numerator}}}{{{x.denominator}}}"
    return f"\\frac{{{x.numerator}}}{{{x.denominator}}}"


def _pmatrix_tex(M: list[list[Fraction]]) -> str:
    rows = [" & ".join(_frac_tex(x) for x in row) for row in M]
    body = "\\\\\n".join(rows)
    return "\\begin{pmatrix}\n" + body + "\n\\end{pmatrix}"


def write_tex(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def invert_3x3(H: list[list[Fraction]]) -> Tuple[Fraction, list[list[Fraction]]]:
    a, b, c = H[0]
    d, e, f = H[1]
    g, h, i = H[2]
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    C00 = e * i - f * h
    C01 = -(d * i - f * g)
    C02 = d * h - e * g
    C10 = -(b * i - c * h)
    C11 = a * i - c * g
    C12 = -(a * h - b * g)
    C20 = b * f - c * e
    C21 = -(a * f - c * d)
    C22 = a * e - b * d
    adj = [
        [C00, C10, C20],
        [C01, C11, C21],
        [C02, C12, C22],
    ]
    inv = [[adj[r][c] / det for c in range(3)] for r in range(3)]
    return det, inv


def main() -> None:
    # Critical plane audit: u=v=1, w=1/2.
    u = Fraction(1, 1)
    v = Fraction(1, 1)
    w = Fraction(1, 2)
    c1, c2, c3, c4, c5, c6 = delta_coeffs(u, v, w)

    out_delta = generated_dir() / "eq_sync_kernel_3d_critical_w_half_delta.tex"
    def _term(coeff: Fraction, power: int) -> str:
        sign = "+" if coeff > 0 else "-"
        mag = coeff if coeff > 0 else -coeff
        if power == 1:
            zp = "z"
        else:
            zp = f"z^{power}"
        if mag == 1:
            return f"{sign}{zp}"
        return f"{sign}{_frac_tex(mag)}{zp}"

    poly = "1"
    for k, ck in enumerate((c1, c2, c3, c4, c5), start=1):
        poly += _term(ck, k)

    write_tex(
        out_delta,
        [
            "% Auto-generated by scripts/exp_sync_kernel_weighted_3d_exact_audits.py",
            "\\[",
            "\\boxed{\\;",
            "\\Delta\\!\\left(z;1,1,\\tfrac12\\right)",
            "=" + poly + ",",
            "\\;}",
            "\\qquad(c_6=0).",
            "\\]",
        ],
    )

    # Exact Hessian inverse and orthogonal basis at theta=0.
    H = [
        [Fraction(11, 102), Fraction(0, 1), Fraction(181, 1632)],
        [Fraction(0, 1), Fraction(25, 128), Fraction(5, 128)],
        [Fraction(181, 1632), Fraction(5, 128), Fraction(2, 9)],
    ]
    detH, Hinv = invert_3x3(H)

    out_inv = generated_dir() / "eq_sync_kernel_3d_hessian_inverse_exact.tex"
    write_tex(
        out_inv,
        [
            "% Auto-generated by scripts/exp_sync_kernel_weighted_3d_exact_audits.py",
            "\\[",
            "\\boxed{\\;",
            "\\bigl(\\nabla^2P(0)\\bigr)^{-1}=",
            _pmatrix_tex(Hinv),
            "\\;}",
            "\\]",
        ],
    )

    # Orthogonalization coefficients (exact).
    Var_e = H[0][0]
    Var_n = H[1][1]
    Var_2 = H[2][2]
    Cov_e2 = H[0][2]
    Cov_n2 = H[1][2]
    Cov_en = H[0][1]

    alpha = Cov_e2 / Var_2  # eta = e - alpha * phi2
    beta = Cov_n2 / Var_2   # psi = nu - beta * phi2

    Var_eta = Var_e - 2 * alpha * Cov_e2 + alpha * alpha * Var_2
    Var_psi = Var_n - 2 * beta * Cov_n2 + beta * beta * Var_2
    Cov_etapsi = Cov_en - beta * Cov_e2 - alpha * Cov_n2 + alpha * beta * Var_2

    gamma = -Cov_etapsi / Var_eta  # psi' = psi + gamma * eta
    Var_psip = Var_psi + 2 * gamma * Cov_etapsi + gamma * gamma * Var_eta

    out_ortho = generated_dir() / "eq_sync_kernel_3d_quadratic_orthobasis.tex"
    write_tex(
        out_ortho,
        [
            "% Auto-generated by scripts/exp_sync_kernel_weighted_3d_exact_audits.py",
            "\\[",
            "\\begin{aligned}",
            f"\\eta&:=\\varphi_e-{_frac_tex(alpha)}\\,\\varphi_2,\\\\",
            f"\\psi&:=\\varphi_- -{_frac_tex(beta)}\\,\\varphi_2,\\\\",
            f"\\psi'&:=\\psi+{_frac_tex(gamma)}\\,\\eta,\\\\",
            f"\\mathrm{{Var}}(\\eta)&={_frac_tex(Var_eta)},\\\\",
            f"\\mathrm{{Var}}(\\psi')&={_frac_tex(Var_psip)},\\\\",
            f"\\mathrm{{Var}}(\\varphi_2)&={_frac_tex(Var_2)}.",
            "\\end{aligned}",
            "\\]",
        ],
    )

    # JSON export for regression tests.
    jout = export_dir() / "sync_kernel_weighted_3d_exact_audits.json"
    jout.parent.mkdir(parents=True, exist_ok=True)
    payload: Dict[str, object] = {
        "delta_u_v_w": {"u": str(u), "v": str(v), "w": str(w)},
        "delta_c": {"c1": str(c1), "c2": str(c2), "c3": str(c3), "c4": str(c4), "c5": str(c5), "c6": str(c6)},
        "hessian_det": str(detH),
        "hessian_inv": [[str(x) for x in row] for row in Hinv],
        "orthobasis": {
            "alpha": str(alpha),
            "beta": str(beta),
            "gamma": str(gamma),
            "var_eta": str(Var_eta),
            "var_psip": str(Var_psip),
            "var_phi2": str(Var_2),
        },
    }
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[sync-kernel-3d-exact-audits] wrote {out_delta}", flush=True)
    print(f"[sync-kernel-3d-exact-audits] wrote {out_inv}", flush=True)
    print(f"[sync-kernel-3d-exact-audits] wrote {out_ortho}", flush=True)
    print(f"[sync-kernel-3d-exact-audits] wrote {jout}", flush=True)
    print("[sync-kernel-3d-exact-audits] done", flush=True)


if __name__ == "__main__":
    main()

