#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boundary uplift m=10 dictionary from the canonical four-step shift.

All output is English-only by repository convention.

We certify the canonical map (for n>=2):
  iota_n : X_n -> X_{n+4}^{bdry},   iota_n(v)=10 v 01,
and audit its bijection on a finite range of n.

At n=6, this yields an explicit 21-word dictionary for X_10^{bdry} that inherits
the B3 root labeling of X_6^{cyc} plus the three Cartan-like boundary words.

Outputs (default):
  - artifacts/export/boundary_uplift_m10_b3c3_dictionary.json
  - sections/generated/eq_boundary_uplift_m10_isomorphism.tex
  - sections/generated/tab_boundary_uplift_m10_dictionary.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str
from exp_fold6_b3c3_seed import _V_m, _build_dictionary, _golden_words

RootVec = Tuple[int, int, int]


def _is_boundary_word(w: str) -> bool:
    return len(w) >= 2 and w[0] == "1" and w[-1] == "1"


def _iota(v: str) -> str:
    return f"10{v}01"


def _golden_words_str(m: int) -> List[str]:
    return [word_to_str(w) for w in _golden_words(m)]


def _root_class(rv: RootVec) -> str:
    nz = [x for x in rv if x != 0]
    if len(nz) == 1:
        return "short"
    if len(nz) == 2:
        return "A2+" if nz[0] == nz[1] else "A2-"
    raise AssertionError(f"Unexpected root vector shape: {rv}")


def _root_class_tex(cls: str) -> str:
    if cls == "short":
        return "short"
    if cls == "A2+":
        return "$A_2^{(+)}$"
    if cls == "A2-":
        return "$A_2^{(-)}$"
    if cls == "Cartan":
        return "Cartan"
    raise AssertionError(f"Unknown class: {cls}")


def _tex_tt(word: str) -> str:
    return f"\\texttt{{{word}}}"


def _tex_root(rv: RootVec | None) -> str:
    if rv is None:
        return "\\textemdash"
    return f"$({rv[0]},{rv[1]},{rv[2]})$"


@dataclass(frozen=True)
class Entry:
    v: str
    b: str
    cls: str
    root: RootVec | None


def _write_tex_eq(out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_boundary_uplift_m10_b3c3_dictionary.py")
    lines.append("\\[")
    lines.append(
        "X_{10}^{\\mathrm{bdry}}=\\{\\,10\\,v\\,01:\\ v\\in X_6\\,\\},\\qquad |X_{10}^{\\mathrm{bdry}}|=|X_6|=21."
    )
    lines.append("\\]")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _write_tex_table(out_path: Path, entries: Sequence[Entry]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_boundary_uplift_m10_b3c3_dictionary.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.08}")
    lines.append(
        "\\caption{Canonical uplift dictionary from $X_6$ to the boundary layer $X_{10}^{\\mathrm{bdry}}$ via $\\iota_6(v)=10v01$. "
        "Root classes use the $B_3$ normalization of the fold6 dictionary; long roots split into $A_2^{(+)}$ (same-sign) and $A_2^{(-)}$ (opposite-sign) classes.}"
    )
    lines.append("\\label{tab:boundary_uplift_m10_dictionary}")
    lines.append("\\begin{tabular}{l l l l}")
    lines.append("\\toprule")
    lines.append("$v\\in X_6$ & $b=10v01\\in X_{10}^{\\mathrm{bdry}}$ & class & root vector\\\\")
    lines.append("\\midrule")
    for e in entries:
        lines.append(
            f"{_tex_tt(e.v)} & {_tex_tt(e.b)} & {_root_class_tex(e.cls)} & {_tex_root(e.root)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _check_bijection(n_min: int, n_max: int) -> List[dict]:
    out: List[dict] = []
    for n in range(n_min, n_max + 1):
        Xn = _golden_words_str(n)
        Xn4 = _golden_words_str(n + 4)
        bdry_n4 = [w for w in Xn4 if _is_boundary_word(w)]
        image = sorted({_iota(v) for v in Xn})
        ok = set(image) == set(bdry_n4)
        out.append(
            {
                "n": n,
                "X_n_size": len(Xn),
                "X_bdry_nplus4_size": len(bdry_n4),
                "iota_image_size": len(image),
                "is_bijection": bool(ok),
            }
        )
        if not ok:
            raise AssertionError(f"iota_n is not bijective at n={n}")
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Boundary uplift m=10 dictionary (B3/C3 root split).")
    ap.add_argument("--n-min", type=int, default=2, help="Minimum n to certify iota_n bijection.")
    ap.add_argument("--n-max", type=int, default=14, help="Maximum n to certify iota_n bijection.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "boundary_uplift_m10_b3c3_dictionary.json"),
    )
    ap.add_argument(
        "--tex-eq",
        type=str,
        default=str(generated_dir() / "eq_boundary_uplift_m10_isomorphism.tex"),
    )
    ap.add_argument(
        "--tex-table",
        type=str,
        default=str(generated_dir() / "tab_boundary_uplift_m10_dictionary.tex"),
    )
    args = ap.parse_args()

    if int(args.n_min) < 2 or int(args.n_max) < int(args.n_min):
        raise SystemExit("Require n_min >= 2 and n_max >= n_min.")

    # Verify iota_n bijection on a finite range.
    bijection_checks = _check_bijection(int(args.n_min), int(args.n_max))

    # Build X6 and its B3 dictionary.
    X6 = sorted(_golden_words_str(6))
    bdry6 = sorted([w for w in X6 if _is_boundary_word(w)])
    cyc6 = sorted([w for w in X6 if not _is_boundary_word(w)])
    if len(X6) != 21 or len(cyc6) != 18 or len(bdry6) != 3:
        raise AssertionError("Unexpected X6 sizes.")

    b3_dict = _build_dictionary(cyc_words=cyc6, variant="B3")

    # Build X10 boundary set and uplift dictionary.
    X10 = sorted(_golden_words_str(10))
    bdry10 = sorted([w for w in X10 if _is_boundary_word(w)])
    uplift_entries: List[Entry] = []
    class_counts: Dict[str, int] = {"short": 0, "A2+": 0, "A2-": 0, "Cartan": 0}
    class_words: Dict[str, List[str]] = {"short": [], "A2+": [], "A2-": [], "Cartan": []}

    for v in X6:
        b = _iota(v)
        if b not in bdry10:
            raise AssertionError(f"Uplift word not in X_10^bdry: v={v} b={b}")
        if v in bdry6:
            cls = "Cartan"
            rv = None
        else:
            rv = b3_dict[v]
            cls = _root_class(rv)
        class_counts[cls] = class_counts.get(cls, 0) + 1
        class_words[cls].append(v)
        uplift_entries.append(Entry(v=v, b=b, cls=cls, root=rv))

    if set(_iota(v) for v in X6) != set(bdry10):
        raise AssertionError("Mismatch: iota_6(X6) != X_10^bdry.")

    if class_counts != {"short": 6, "A2+": 6, "A2-": 6, "Cartan": 3}:
        raise AssertionError(f"Unexpected class counts: {class_counts}")

    # Sort entries by class, then by Zeckendorf value.
    class_order = {"short": 0, "A2+": 1, "A2-": 2, "Cartan": 3}
    uplift_entries_sorted = sorted(
        uplift_entries,
        key=lambda e: (class_order[e.cls], _V_m(e.v), e.v),
    )

    # JSON export.
    payload: Dict[str, object] = {
        "n_range": {"min": int(args.n_min), "max": int(args.n_max)},
        "bijection_checks": bijection_checks,
        "X6": {"words": X6, "cyc": cyc6, "bdry": bdry6},
        "X10_bdry": {"words": bdry10, "size": len(bdry10)},
        "uplift": [
            {
                "v": e.v,
                "b": e.b,
                "class": e.cls,
                "root_vector": list(e.root) if e.root is not None else None,
            }
            for e in uplift_entries_sorted
        ],
        "class_counts": class_counts,
        "class_words": {k: sorted(v) for k, v in class_words.items()},
        "root_system": "B3",
    }
    jout = Path(str(args.json_out))
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # LaTeX fragments.
    _write_tex_eq(Path(str(args.tex_eq)))
    _write_tex_table(Path(str(args.tex_table)), uplift_entries_sorted)

    print(f"[boundary-uplift-m10] wrote {jout}", flush=True)
    print(f"[boundary-uplift-m10] wrote {args.tex_eq}", flush=True)
    print(f"[boundary-uplift-m10] wrote {args.tex_table}", flush=True)
    print("[boundary-uplift-m10] done", flush=True)


if __name__ == "__main__":
    main()
