#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit the y-image of E[3]\\{O} under the weight map y on E.

This script is English-only by repository convention.

We work with the elliptic curve
  E: Y^2 = X^3 - X + 1/4
and the weight coordinate
  y := X^2 + Y - 1/2.

Eliminating Y gives the quartic relation
  Pi(X,y) := X^4 - X^3 - (2y+1) X^2 + X + y(y+1) = 0.

Let psi_3(X) be the 3-division polynomial for E in X-coordinate form:
  psi_3(X) = 3X^4 - 6X^2 + 3X - 1.

Define the elimination polynomial for the weight image of nontrivial 3-torsion:
  L3(y) := Res_X(psi_3(X), Pi(X,y)) in Z[y].

We certify:
  - psi_3 has discriminant -3^3 * 37^2.
  - L3(y) is the explicit degree-8 integer polynomial stated in the paper.
  - Disc(L3) = -3^31 * 37^10 * 48973^2.
  - (Optional diagnostic) L3(y) factors mod 37 as 7*(y-6)^6*(y^2-5y-1).

Outputs:
  - artifacts/export/fold_zm_elliptic_3torsion_y_image_octic_audit.json
  - sections/generated/eq_fold_zm_elliptic_3torsion_y_image_octic_audit.tex
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

import sympy as sp

from common_paths import export_dir, generated_dir


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _format_factorization_latex(sign: int, fac: Dict[int, int]) -> str:
    parts: List[str] = ["-1"] if sign == -1 else []
    for p in sorted(fac.keys()):
        e = fac[p]
        parts.append(f"{p}" if e == 1 else f"{p}^{{{e}}}")
    return r"\cdot ".join(parts) if parts else "1"


@dataclass(frozen=True)
class Payload:
    psi3_disc: int
    psi3_disc_matches_expected: bool
    l3_degree: int
    l3_lc: int
    l3_coeffs_high_to_low: List[int]
    l3_matches_expected: bool
    l3_disc: int
    l3_disc_matches_expected: bool
    l3_factor_mod37: str
    l3_mod37_matches_expected: bool
    seconds: float


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit L3(y)=Res_X(psi3,Pi) and its discriminant.")
    parser.add_argument("--no-output", action="store_true", help="Skip writing JSON/TeX outputs.")
    args = parser.parse_args()

    t0 = time.time()
    print("[fold-zm-elliptic-3torsion-y-image] start", flush=True)

    X, y = sp.symbols("X y")

    Pi = X**4 - X**3 - (2 * y + 1) * X**2 + X + y * (y + 1)
    psi3 = 3 * X**4 - 6 * X**2 + 3 * X - 1

    psi3_disc = int(sp.discriminant(psi3, X))
    psi3_disc_expected = -(3**3) * (37**2)
    psi3_disc_ok = psi3_disc == psi3_disc_expected

    res = sp.resultant(psi3, Pi, X)
    L3 = sp.Poly(sp.expand(res), y, domain=sp.ZZ)
    _content, L3 = L3.primitive()
    if L3.LC() < 0:
        L3 = -L3

    L3_expected = sp.Poly(
        81 * y**8 - 324 * y**7 + 297 * y**6 + 729 * y**5 - 216 * y**4 - 1395 * y**3 - 480 * y**2 - 120 * y + 7,
        y,
        domain=sp.ZZ,
    )
    l3_ok = L3 == L3_expected

    l3_disc = int(sp.discriminant(L3.as_expr(), y))
    l3_disc_expected = -(3**31) * (37**10) * (48973**2)
    l3_disc_ok = l3_disc == l3_disc_expected

    L3_mod37 = sp.Poly(L3.as_expr(), y, modulus=37)
    l3_factor_mod37 = str(sp.factor(L3_mod37.as_expr(), modulus=37))
    L3_mod37_expected = sp.Poly(7 * (y - 6) ** 6 * (y**2 - 5 * y - 1), y, modulus=37)
    l3_mod37_ok = L3_mod37 == L3_mod37_expected

    dt = time.time() - t0
    payload = Payload(
        psi3_disc=int(psi3_disc),
        psi3_disc_matches_expected=bool(psi3_disc_ok),
        l3_degree=int(L3.degree()),
        l3_lc=int(L3.LC()),
        l3_coeffs_high_to_low=[int(c) for c in L3.all_coeffs()],
        l3_matches_expected=bool(l3_ok),
        l3_disc=int(l3_disc),
        l3_disc_matches_expected=bool(l3_disc_ok),
        l3_factor_mod37=l3_factor_mod37,
        l3_mod37_matches_expected=bool(l3_mod37_ok),
        seconds=float(dt),
    )

    if not args.no_output:
        out_json = export_dir() / "fold_zm_elliptic_3torsion_y_image_octic_audit.json"
        _write_json(out_json, asdict(payload))

        disc_latex = (
            r"-3^{31}\cdot 37^{10}\cdot 48973^{2}"
            if l3_disc_ok
            else _format_factorization_latex(-1 if l3_disc < 0 else 1, {int(p): int(e) for p, e in sp.factorint(abs(l3_disc)).items()})
        )
        tex = "\n".join(
            [
                "% Auto-generated by scripts/exp_fold_zm_elliptic_3torsion_y_image_octic_audit.py",
                "\\[",
                f"\\psi_{{3}}(X)={sp.latex(sp.Poly(psi3, X).as_expr())}.",
                "\\]",
                "\\[",
                r"\operatorname{Disc}(\psi_{3})=-3^{3}\cdot 37^{2}.",
                "\\]",
                "\\[",
                f"L_{{3}}(y)={sp.latex(L3.as_expr())}.",
                "\\]",
                "\\[",
                rf"\\operatorname{{Disc}}\\!\\bigl(L_{{3}}\\bigr)={disc_latex}.",
                "\\]",
                "\\[",
                (
                    r"L_{3}(y)\equiv 7\,(y-6)^{6}\,(y^{2}-5y-1)\pmod{37}."
                    if l3_mod37_ok
                    else rf"L_{{3}}(y)\equiv {sp.latex(sp.factor(L3_mod37.as_expr(), modulus=37))}\pmod{{37}}."
                ),
                "\\]",
                "",
            ]
        )
        out_tex = generated_dir() / "eq_fold_zm_elliptic_3torsion_y_image_octic_audit.tex"
        _write_text(out_tex, tex)

        print(f"[fold-zm-elliptic-3torsion-y-image] wrote {out_json}", flush=True)
        print(f"[fold-zm-elliptic-3torsion-y-image] wrote {out_tex}", flush=True)

    print(
        "[fold-zm-elliptic-3torsion-y-image] checks:"
        f" psi3_disc_ok={psi3_disc_ok} L3_ok={l3_ok} L3_disc_ok={l3_disc_ok} L3_mod37_ok={l3_mod37_ok}"
        f" seconds={dt:.3f}",
        flush=True,
    )
    print("[fold-zm-elliptic-3torsion-y-image] done", flush=True)


if __name__ == "__main__":
    main()

