#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Artin-style factorization of the real-input 40-state Abel/Mertens constant.

We use the unweighted determinant factorization:
  Δ(z)=det(I-zM)=(1-z)^2(1+z)^3(1-3z+z^2)(1+z-z^2),
with λ=ρ(M)=φ^2 and z_* = 1/λ = φ^{-2}.

Define:
  ζ_triv(z) = 1/((1-z)^2 (1+z)^3),
  ζ_even(z) = 1/(1-3z+z^2),
  ζ_χ(z)    = 1/(1+z-z^2)  (the “-F twist” factor in the paper).

Then ζ_M = ζ_triv * ζ_even * ζ_χ and:
  P_triv(z) := Σ_{m≥1} μ(m)/m log ζ_triv(z^m) = -z + 3 z^2,
and at z=z_*:
  P_triv(z_*) = 9 - 4√5.

Moreover, the main-pole residue constant splits as:
  C = C_even * ζ_χ(z_*) * ζ_triv(z_*),
and the Abel finite-part constant splits as:
  log 𝔐 = log 𝔐_even + K_{-F} + P_triv(z_*),
where K_{-F} is the Artin-sign Mertens constant already exported by the pipeline.

Outputs:
  - sections/generated/eq_real_input_40_logM_artin_factorization.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import mpmath as mp
import sympy as sp

from common_paths import export_dir, generated_dir


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _mp(x: str) -> mp.mpf:
    return mp.mpf(x)


def write_tex(out_path: Path) -> None:
    # Load pipeline artifacts
    artin_path = export_dir() / "real_input_40_artin_sign_mertens.json"
    split_path = export_dir() / "real_input_40_abel_mertens_two_series_split.json"
    artin = _read_json(artin_path)
    split = _read_json(split_path)

    mp.mp.dps = 80

    K_minus_F = _mp(artin["K_minus_F"])
    logM = _mp(split["row"]["logM"])

    # Exact algebraic constants in Q(sqrt5)
    sqrt5 = sp.sqrt(5)
    phi = (sp.Integer(1) + sqrt5) / 2
    lam = phi**2
    z_exact = sp.simplify(1 / lam)  # φ^{-2} = (3-√5)/2
    # Use exact algebraic z_* for all numeric reconstructions.
    z_star = mp.mpf(str(sp.N(z_exact, mp.mp.dps)))

    P_triv_exact = sp.simplify(-z_exact + 3 * z_exact**2)  # 9-4√5

    # Residue factorization
    C_even_exact = sp.simplify(1 / (1 - lam ** (-2)))  # 1/(1-λ^{-2})
    zeta_chi_exact = sp.simplify(1 / (1 + z_exact - z_exact**2))
    zeta_triv_exact = sp.simplify(1 / ((1 - z_exact) ** 2 * (1 + z_exact) ** 3))
    C_exact = sp.simplify(C_even_exact * zeta_chi_exact * zeta_triv_exact)
    C_exact_mp = mp.mpf(str(sp.N(C_exact, mp.mp.dps)))

    # Numerical checks (mp)
    zeta_chi_num = 1 / (1 + z_star - z_star**2)
    zeta_triv_num = 1 / ((1 - z_star) ** 2 * (1 + z_star) ** 3)
    # even factor: ζ_even(z) = 1/((1-λ z)(1-λ^{-1} z)), so residue at z=1/λ is 1/(1-λ^{-2})
    # Use z_star directly for high precision: λ^{-2} = z_star^2.
    C_even_num = 1 / (1 - z_star**2)
    C_recon = C_even_num * zeta_chi_num * zeta_triv_num

    # Abel constant decomposition
    P_triv_num = _mp(str(sp.N(P_triv_exact, 80)))
    logM_even_num = logM - K_minus_F - P_triv_num

    # TeX
    lines: list[str] = []
    lines.append("% Generated by scripts/exp_real_input_40_logM_artin_factorization.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        "P_{\\mathrm{triv}}(z)"
        ":=\\sum_{m\\ge 1}\\frac{\\mu(m)}{m}\\log\\zeta_{\\mathrm{triv}}(z^m)"
        "&=-z+3z^2,"
    )
    lines.append("\\\\")
    lines.append(
        f"P_{{\\mathrm{{triv}}}}(z_\\star)"
        f"=-z_\\star+3z_\\star^2"
        f"={sp.latex(P_triv_exact)}"
        f"\\approx {mp.nstr(P_triv_num, 18)}."
    )
    lines.append("\\\\[2pt]")
    lines.append(
        "C"
        "=C_{\\mathrm{even}}\\,\\zeta_{\\chi}(z_\\star)\\,\\zeta_{\\mathrm{triv}}(z_\\star),"
        "\\qquad "
        f"C_{{\\mathrm{{even}}}}={sp.latex(C_even_exact)},"
    )
    lines.append("\\\\")
    lines.append(
        f"\\zeta_\\chi(z_\\star)={sp.latex(zeta_chi_exact)},\\qquad"
        f"\\zeta_{{\\mathrm{{triv}}}}(z_\\star)={sp.latex(zeta_triv_exact)},\\qquad "
        f"C={sp.latex(C_exact)}."
    )
    lines.append("\\\\[2pt]")
    lines.append(
        "\\log\\mathfrak{M}"
        "=\\log\\mathfrak{M}_{\\mathrm{even}}+K_{-F}+P_{\\mathrm{triv}}(z_\\star),"
    )
    lines.append("\\\\")
    lines.append(f"K_{{-F}}\\approx {mp.nstr(K_minus_F, 18)},")
    lines.append("\\\\")
    lines.append(f"\\log\\mathfrak{{M}}_{{\\mathrm{{even}}}}\\approx {mp.nstr(logM_even_num, 18)},")
    lines.append("\\\\")
    lines.append(f"\\log\\mathfrak{{M}}\\approx {mp.nstr(logM, 18)}.")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Basic numeric sanity check against the exact algebraic C.
    if abs(C_recon - C_exact_mp) > mp.mpf("1e-60"):
        raise ValueError(f"Residue factorization mismatch: recon={C_recon}, C_exact={C_exact_mp}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Artin-style factorization for logM (real-input 40).")
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_real_input_40_logM_artin_factorization.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()
    write_tex(Path(args.tex_out))
    print(f"[real-input-40-logM-artin] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

