#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate for exponential decay envelope of the t=0 autocorrelation.

Input:
- artifacts/export/real_input_40_time_correlation.json

Outputs:
- artifacts/export/real_input_40_time_correlation_decay_certificate.json
- sections/generated/tab_real_input_40_time_correlation_decay_certificate.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

from common_paths import export_dir, generated_dir, paper_root
from common_phi_fold import Progress


def _load_json(rel: str) -> Dict[str, Any]:
    return json.loads((paper_root() / rel).read_text(encoding="utf-8"))


def _fmt_float(x: float, ndp: int = 12) -> str:
    if not math.isfinite(x):
        return "\\infty"
    if x == 0.0:
        return "0"
    ax = abs(x)
    if ax < 1e-4 or ax >= 1e4:
        return f"{x:.6e}"
    return f"{x:.{ndp}f}"


def _extract_corr(payload: Dict[str, Any]) -> Tuple[List[int], List[float], float]:
    corr = payload.get("corr")
    if not isinstance(corr, dict):
        raise RuntimeError("missing corr field")
    ns = corr.get("n")
    cs = corr.get("corr")
    r = corr.get("r")
    if not isinstance(ns, list) or not isinstance(cs, list):
        raise RuntimeError("corr.n/corr.corr malformed")
    if len(ns) != len(cs):
        raise RuntimeError("corr.n and corr.corr length mismatch")
    if r is None:
        raise RuntimeError("corr.r missing")
    out_n: List[int] = []
    out_c: List[float] = []
    for n, v in zip(ns, cs):
        out_n.append(int(n))
        out_c.append(float(v))
    return out_n, out_c, float(r)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit certificate for exponential envelope of autocorrelation"
    )
    parser.add_argument(
        "--time-corr-json",
        type=str,
        default="artifacts/export/real_input_40_time_correlation.json",
    )
    parser.add_argument("--rows", type=int, default=20)
    parser.add_argument("--max-n", type=int, default=80)
    args = parser.parse_args()

    prog = Progress(label="real-input-40-time-corr-cert", every_seconds=20.0)
    payload = _load_json(str(args.time_corr_json))
    ns, corr, r = _extract_corr(payload)
    prog.tick("loaded time-corr json")

    if not (0.0 < r < 1.0):
        raise SystemExit(f"invalid r in input: r={r}")

    max_n = int(args.max_n)
    pairs = [(n, c) for n, c in zip(ns, corr) if 0 <= int(n) <= max_n]
    if not pairs:
        raise SystemExit("no correlation samples available")

    ratios: List[Dict[str, float]] = []
    max_ratio = -1.0
    argmax_n = 0
    max_ratio_tail = -1.0
    argmax_n_tail = 1
    for n, c in pairs:
        env = r ** int(n)
        ratio = (abs(float(c)) / env) if env > 0.0 else float("inf")
        ratios.append(
            {
                "n": float(n),
                "corr": float(c),
                "env": float(env),
                "ratio": float(ratio),
            }
        )
        if math.isfinite(ratio) and ratio > max_ratio:
            max_ratio = float(ratio)
            argmax_n = int(n)
        if int(n) >= 1 and math.isfinite(ratio) and ratio > max_ratio_tail:
            max_ratio_tail = float(ratio)
            argmax_n_tail = int(n)
    prog.tick("computed envelope ratios")

    if max_ratio_tail < 0.0:
        raise SystemExit("tail certificate requested but no samples with n>=1")

    out_json = export_dir() / "real_input_40_time_correlation_decay_certificate.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_payload: Dict[str, object] = {
        "model": "real_input_40",
        "slice": "chi",
        "theta_map": "theta(t)=(t,0,-t)",
        "t0": 0.0,
        "r": float(r),
        "n_max": int(max_n),
        "rows": int(args.rows),
        "ratio_max": float(max_ratio),
        "ratio_argmax_n": int(argmax_n),
        "ratio_max_tail": float(max_ratio_tail),
        "ratio_argmax_n_tail": int(argmax_n_tail),
        "ratios": ratios,
        "input": str(args.time_corr_json),
    }
    out_json.write_text(
        json.dumps(out_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    # LaTeX fragment.
    rows = max(1, int(args.rows))
    head = ratios[:rows]

    tex_path = (
        generated_dir() / "tab_real_input_40_time_correlation_decay_certificate.tex"
    )
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_time_correlation_decay_certificate.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{8pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{真实输入 40 状态核在 $t=0$（$\\chi$ 切片 $\\theta(t)=(t,0,-t)$）下的自相关指数包络审计证书。"
        "表中 $r=\\Lambda/\\lambda_1$ 由有限维加权矩阵谱读出，右列为 $|\\mathrm{Corr}(n)|/r^n$；"
        "其最大值给出一个可复现的常数 $C$，使得 $|\\mathrm{Corr}(n)|\\le C r^n$ 在离散样本上成立。}"
    )
    lines.append("\\label{tab:real-input-40-time-corr-decay-certificate}")
    lines.append("\\begin{tabular}{r r r r}")
    lines.append("\\toprule")
    lines.append(
        "\\, $n$ & $\\mathrm{Corr}(n)$ & $r^n$ & $|\\mathrm{Corr}(n)|/r^n$\\\\"
    )
    lines.append("\\midrule")
    for row in head:
        n = int(row["n"])
        c = float(row["corr"])
        env = float(row["env"])
        ratio = float(row["ratio"])
        lines.append(
            f"{n:d} & {_fmt_float(c)} & {_fmt_float(env)} & {_fmt_float(ratio)}\\\\"
        )
    lines.append("\\midrule")
    lines.append(f"$r$ & \\multicolumn{{3}}{{l}}{{{_fmt_float(float(r))}}}\\\\")
    lines.append(
        f"$C:=\\max_n |\\mathrm{{Corr}}(n)|/r^n$ (samples) & \\multicolumn{{3}}{{l}}{{{_fmt_float(float(max_ratio))}}}\\\\"
    )
    lines.append(f"$\\arg\\max$ & \\multicolumn{{3}}{{l}}{{{argmax_n:d}}}\\\\")
    lines.append(
        f"$C^{{(1)}}:=\\max_{{n\\ge 1}} |\\mathrm{{Corr}}(n)|/r^n$ (samples) & \\multicolumn{{3}}{{l}}{{{_fmt_float(float(max_ratio_tail))}}}\\\\"
    )
    lines.append(
        f"$\\arg\\max_{{n\\ge 1}}$ & \\multicolumn{{3}}{{l}}{{{argmax_n_tail:d}}}\\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    tex_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Tail certificate (exclude n=0 to avoid the trivial ratio=1).
    tail_rows = max(1, int(args.rows))
    tail_list = [row for row in ratios if int(row["n"]) >= 1]
    tail_head = tail_list[:tail_rows]

    tail_tex_path = (
        generated_dir()
        / "tab_real_input_40_time_correlation_decay_certificate_tail.tex"
    )
    tail_tex_path.parent.mkdir(parents=True, exist_ok=True)
    tail_lines: List[str] = []
    tail_lines.append(
        "% AUTO-GENERATED by scripts/exp_real_input_40_time_correlation_decay_certificate.py"
    )
    tail_lines.append("\\begin{table}[H]")
    tail_lines.append("\\centering")
    tail_lines.append("\\small")
    tail_lines.append("\\setlength{\\tabcolsep}{8pt}")
    tail_lines.append("\\renewcommand{\\arraystretch}{1.15}")
    tail_lines.append(
        "\\caption{真实输入 40 状态核在 $t=0$ 的自相关指数包络尾部审计证书（排除 $n=0$）。"
        "记 $r=\\Lambda/\\lambda_1$，并定义 $C_N^{(1)}:=\\max_{1\\le n\\le N}|\\mathrm{Corr}(n)|/r^n$；"
        "表中报告离散样本上的 $C_N^{(1)}$ 与其达到位置。}"
    )
    tail_lines.append("\\label{tab:real-input-40-time-corr-decay-certificate-tail}")
    tail_lines.append("\\begin{tabular}{r r r r}")
    tail_lines.append("\\toprule")
    tail_lines.append(
        "\\, $n$ & $\\mathrm{Corr}(n)$ & $r^n$ & $|\\mathrm{Corr}(n)|/r^n$\\\\"
    )
    tail_lines.append("\\midrule")
    for row in tail_head:
        n = int(row["n"])
        c = float(row["corr"])
        env = float(row["env"])
        ratio = float(row["ratio"])
        tail_lines.append(
            f"{n:d} & {_fmt_float(c)} & {_fmt_float(env)} & {_fmt_float(ratio)}\\\\"
        )
    tail_lines.append("\\midrule")
    tail_lines.append(f"$r$ & \\multicolumn{{3}}{{l}}{{{_fmt_float(float(r))}}}\\\\")
    tail_lines.append(
        f"$C_N^{{(1)}}$ (samples) & \\multicolumn{{3}}{{l}}{{{_fmt_float(float(max_ratio_tail))}}}\\\\"
    )
    tail_lines.append(
        f"$\\arg\\max_{{1\\le n\\le N}}$ & \\multicolumn{{3}}{{l}}{{{argmax_n_tail:d}}}\\\\"
    )
    tail_lines.append("\\bottomrule")
    tail_lines.append("\\end{tabular}")
    tail_lines.append("\\end{table}")
    tail_tex_path.write_text("\n".join(tail_lines) + "\n", encoding="utf-8")

    print(f"[real-input-40-time-corr-cert] wrote {out_json}", flush=True)
    print(f"[real-input-40-time-corr-cert] wrote {tex_path}", flush=True)
    print(f"[real-input-40-time-corr-cert] wrote {tail_tex_path}", flush=True)
    print("[real-input-40-time-corr-cert] done", flush=True)


if __name__ == "__main__":
    main()
