#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Audit the cubic minimal polynomial for the squared Puiseux coefficient at the
nontrivial Lee–Yang branch points of the Fold Z_m spectral quartic Pi(lambda,y).

On the Lee–Yang branch locus, the double-root lambda_0 satisfies
  h(lambda) = 16 lambda^3 - 9 lambda^2 + 1 = 0,
and the squared Puiseux leading coefficient can be written as
  s = c0^2 = (2/3) * (3 lambda^2 - 1) / (lambda^2 - 1).

Eliminating lambda via a resultant yields a primitive cubic in s:
  324 s^3 - 540 s^2 + 333 s - 74 = 0.

Outputs:
  - artifacts/export/fold_zm_branch_puiseux_coeff_cubic_audit.json
  - sections/generated/eq_fold_zm_branch_puiseux_coeff_cubic_audit.tex
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

import sympy as sp

from common_paths import export_dir, generated_dir


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_tex(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


@dataclass(frozen=True)
class Payload:
    resultant_factored: str
    primitive_cubic_s: str
    primitive_cubic_s_irreducible_over_Q: bool
    numeric_checks: List[Dict[str, str]]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit the cubic minimal polynomial for the squared Puiseux coefficient (Lee–Yang branch)."
    )
    parser.add_argument("--no-output", action="store_true", help="Skip writing JSON/TeX outputs.")
    parser.add_argument(
        "--out-json",
        default=str(export_dir() / "fold_zm_branch_puiseux_coeff_cubic_audit.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--out-tex",
        default=str(generated_dir() / "eq_fold_zm_branch_puiseux_coeff_cubic_audit.tex"),
        help="Output TeX snippet path (sections/generated).",
    )
    args = parser.parse_args()

    t0 = time.time()
    print("[fold-zm-branch-puiseux-coeff-cubic] start", flush=True)

    lam, s = sp.symbols("lam s")

    h = 16 * lam**3 - 9 * lam**2 + 1
    # s = (2/3) * (3 lam^2 - 1)/(lam^2 - 1)
    rel = (lam**2 - 1) * s - sp.Rational(2, 3) * (3 * lam**2 - 1)

    res = sp.resultant(h, sp.factor(rel), lam)
    res_factored = sp.factor(res)

    primitive = 324 * s**3 - 540 * s**2 + 333 * s - 74
    primitive_irred = bool(sp.factor(primitive) == primitive)

    # Numeric verification on the three conjugate roots of h.
    roots = sp.Poly(h, lam).nroots(n=80)
    checks: List[Dict[str, str]] = []
    for r in roots:
        sval = sp.N((sp.Rational(2, 3) * (3 * r**2 - 1) / (r**2 - 1)), 50)
        evalv = sp.N(primitive.subs(s, sval), 50)
        checks.append(
            {
                "lambda": str(sp.N(r, 50)),
                "s=c0^2": str(sval),
                "primitive_poly_eval": str(evalv),
            }
        )

    payload = Payload(
        resultant_factored=str(res_factored),
        primitive_cubic_s=str(primitive),
        primitive_cubic_s_irreducible_over_Q=primitive_irred,
        numeric_checks=checks,
    )

    if not args.no_output:
        _write_json(Path(args.out_json), asdict(payload))

        tex = (
            "% Auto-generated by scripts/exp_fold_zm_branch_puiseux_coeff_cubic_audit.py\n"
            "\\[\n"
            "\\mathrm{Res}_{\\lambda}\\!\\left(16\\lambda^{3}-9\\lambda^{2}+1,\\ (\\lambda^{2}-1)s-\\frac{2}{3}(3\\lambda^{2}-1)\\right)\n"
            "=-\\frac{16}{27}\\,\\bigl(324s^{3}-540s^{2}+333s-74\\bigr).\n"
            "\\]\n"
        )
        _write_tex(Path(args.out_tex), tex)

    dt = time.time() - t0
    print(f"[fold-zm-branch-puiseux-coeff-cubic] done elapsed_s={dt:.3f}", flush=True)


if __name__ == "__main__":
    main()

