#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Local rate-series coefficients for the output potential of the real-input 40-state kernel.

We use the exact quadratic-field cumulants already established for
    P(theta) = log lambda(exp(theta)),
where lambda(u) is the Perron root of the output-potential transfer matrix.

With
    mu      = P'(0),
    sigma2  = P''(0),
    kappa3  = P^{(3)}(0),
    kappa4  = P^{(4)}(0),
the local Legendre rate expansion around mu is
    I(mu + delta)
      = A2 * delta^2 + A3 * delta^3 + A4 * delta^4 + O(delta^5),
where
    A2 = 1 / (2 sigma2),
    A3 = -kappa3 / (6 sigma2^3),
    A4 = (3 kappa3^2 - sigma2 kappa4) / (24 sigma2^5).

Outputs:
  - artifacts/export/real_input_40_output_potential_local_rate_series.json
  - sections/generated/eq_real_input_40_output_potential_local_rate_series.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path

import sympy as sp

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class LocalRateSeries:
    mu: str
    sigma2: str
    kappa3: str
    kappa4: str
    A2: str
    A3: str
    A4: str
    A2_float: str
    A3_float: str
    A4_float: str


def _fmt_decimal(x: sp.Expr, digits: int) -> str:
    return f"{float(sp.N(x, 50)):.{digits}f}"


def _exact_data() -> dict[str, sp.Expr]:
    sqrt5 = sp.sqrt(5)
    return {
        "mu": sp.Rational(23, 20) - sp.Rational(7, 20) * sqrt5,
        "sigma2": sp.Rational(1791, 200) - sp.Rational(3983, 1000) * sqrt5,
        "kappa3": sp.Rational(1416369, 5000) - sp.Rational(126691, 1000) * sqrt5,
        "kappa4": sp.Rational(1354428303, 100000)
        - sp.Rational(605718497, 100000) * sqrt5,
    }


def _compute_series() -> LocalRateSeries:
    data = _exact_data()
    mu = sp.simplify(data["mu"])
    sigma2 = sp.simplify(data["sigma2"])
    kappa3 = sp.simplify(data["kappa3"])
    kappa4 = sp.simplify(data["kappa4"])
    A2 = sp.simplify(sp.Rational(1, 2) / sigma2)
    A3 = sp.simplify(-kappa3 / (6 * sigma2**3))
    A4 = sp.simplify((3 * kappa3**2 - sigma2 * kappa4) / (24 * sigma2**5))
    return LocalRateSeries(
        mu=str(mu),
        sigma2=str(sigma2),
        kappa3=str(kappa3),
        kappa4=str(kappa4),
        A2=str(A2),
        A3=str(A3),
        A4=str(A4),
        A2_float=_fmt_decimal(A2, 7),
        A3_float=_fmt_decimal(A3, 7),
        A4_float=_fmt_decimal(A4, 7),
    )


def _write_tex(path: Path, series: LocalRateSeries) -> None:
    lines = [
        "% AUTO-GENERATED by scripts/exp_real_input_40_output_potential_local_rate_series.py",
        "\\begin{equation}",
        "\\label{eq:real-input-40-output-potential-local-rate-series}",
        f"I(\\mu+\\delta)={series.A2_float}\\,\\delta^2+{series.A3_float}\\,\\delta^3+{series.A4_float}\\,\\delta^4+O(\\delta^5).",
        "\\end{equation}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Local Legendre rate-series coefficients for the real-input 40-state output potential."
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_output_potential_local_rate_series.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(
            generated_dir() / "eq_real_input_40_output_potential_local_rate_series.tex"
        ),
    )
    args = parser.parse_args()

    series = _compute_series()

    json_path = Path(args.json_out)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(asdict(series), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    tex_path = Path(args.tex_out)
    _write_tex(tex_path, series)

    print(f"[local-rate-series] wrote {json_path}", flush=True)
    print(f"[local-rate-series] wrote {tex_path}", flush=True)
    print("[local-rate-series] done", flush=True)


if __name__ == "__main__":
    main()
