#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: mod-571 spectral collision for window-6 coarse kernel and boundary uplift orders.

This script produces a small, self-contained certificate for:
  - the factorization of f(t)=48114 t^3+7263 t^2-506 t-55 in F_571[t],
  - the resulting (t-1)^2 collision in the characteristic polynomial chi_T(t),
  - multiplicative orders in F_571^× for boundary uplift deltas {34,55,89,144},
  - auxiliary checks for sqrt(5) and golden conjugates in F_571.

Outputs:
  - artifacts/export/window6_mod571_spectral_collision_audit.json
  - sections/generated/eq_window6_mod571_spectral_collision_audit.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, generated_dir


P_STAR = 571


def _mod(x: int, p: int = P_STAR) -> int:
    return x % p


def _inv(a: int, p: int = P_STAR) -> int:
    a = a % p
    if a == 0:
        raise ZeroDivisionError("inverse of 0 mod p")
    return pow(a, -1, p)


def _poly_eval(coeffs_low_to_high: List[int], x: int, p: int = P_STAR) -> int:
    acc = 0
    x = x % p
    for c in reversed(coeffs_low_to_high):
        acc = (acc * x + (c % p)) % p
    return acc


def _div_by_t_minus_a(coeffs_low_to_high: List[int], a: int, p: int = P_STAR) -> Tuple[List[int], int]:
    """Return quotient and remainder of poly / (t-a) in F_p, coefficients low->high."""
    # Synthetic division on highest-first coefficients.
    hi = [c % p for c in reversed(coeffs_low_to_high)]
    out: List[int] = []
    carry = 0
    for c in hi:
        out.append((c + carry) % p)
        carry = (out[-1] * a) % p
    rem = out.pop() % p
    q_hi = out
    q_low = list(reversed(q_hi))
    return q_low, rem


def _factorint(n: int) -> Dict[int, int]:
    n = abs(int(n))
    out: Dict[int, int] = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            out[d] = out.get(d, 0) + 1
            n //= d
        d = 3 if d == 2 else d + 2
    if n > 1:
        out[n] = out.get(n, 0) + 1
    return dict(sorted(out.items()))


def _multiplicative_order(a: int, p: int = P_STAR) -> int:
    """Multiplicative order of a in F_p^× (assumes p is prime and a != 0 mod p)."""
    a %= p
    if a == 0:
        raise ValueError("order undefined for 0")
    phi = p - 1
    fac = _factorint(phi)
    order = phi
    for q in fac:
        while order % q == 0 and pow(a, order // q, p) == 1:
            order //= q
    return order


def _poly_to_tex(coeffs_low_to_high: List[int], var: str, p: int = P_STAR) -> str:
    """Render a poly in Z/pZ with small signed representatives."""
    def rep(c: int) -> int:
        c %= p
        return c if c <= (p // 2) else c - p

    terms: List[str] = []
    for k, c in enumerate(coeffs_low_to_high):
        c = rep(c)
        if c == 0:
            continue
        if k == 0:
            terms.append(str(c))
            continue
        if abs(c) == 1:
            coef = "-" if c < 0 else ""
        else:
            coef = str(c)
        if k == 1:
            terms.append(f"{coef}{var}")
        else:
            terms.append(f"{coef}{var}^{k}")
    if not terms:
        return "0"
    # normalize "+ -" formatting
    s = " + ".join(terms)
    s = s.replace("+ -", "- ")
    return s


def _write_eq_tex(tex_out: Path, payload: Dict[str, object]) -> None:
    p = P_STAR
    fac = payload["factorization_mod_p_star"]
    q = fac["quotient_after_div_t_minus_1"]  # type: ignore[assignment]
    q_monic = fac["monic_quadratic_factor"]  # type: ignore[assignment]
    orders = payload["orders_mod_p_star"]  # type: ignore[assignment]
    aux = payload["auxiliary_checks_mod_p_star"]  # type: ignore[assignment]

    q_low = [int(x) for x in q]  # type: ignore[arg-type]
    q_monic_low = [int(x) for x in q_monic]  # type: ignore[arg-type]

    # quadratic pretty form (monic): t^2 + bt + c
    b = q_monic_low[1] % p
    c = q_monic_low[0] % p
    b_rep = b if b <= (p // 2) else b - p
    c_rep = c if c <= (p // 2) else c - p

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_window6_mod571_spectral_collision_audit.py")
    lines.append("\\begin{equation}\\label{eq:window6_mod571_spectral_collision_audit}")
    lines.append("\\begin{aligned}")
    lines.append(f"p_\\star&:={p},\\\\")
    lines.append(
        "f(t):=48114t^3+7263t^2-506t-55"
        "\\ \\equiv\\ "
        + _poly_to_tex([(-55) % p, (-506) % p, 7263 % p, 48114 % p], "t", p=p)
        + "\\pmod{p_\\star},\\\\"
    )
    lines.append(
        "f(t)"
        "\\ \\equiv\\ "
        + f"{q_low[-1]}(t-1)\\left(t^2+({b_rep})t+({c_rep})\\right)"
        + "\\pmod{p_\\star},\\\\"
    )
    lines.append(
        "\\chi_T(t)=(t-1)\\,p(t)"
        "\\ \\Longrightarrow\\ "
        "\\chi_T(t)\\equiv (t-1)^2\\left(t^2+"
        + (f"{b_rep}" if b_rep >= 0 else f"({b_rep})")
        + "t+"
        + (f"{c_rep}" if c_rep >= 0 else f"({c_rep})")
        + "\\right)\\pmod{p_\\star},\\\\"
    )
    lines.append(
        "\\ord_{p_\\star}(34)="
        + str(orders["34"])
        + ",\\quad "
        + "\\ord_{p_\\star}(21)="
        + str(orders["21"])
        + ",\\quad "
        + "\\ord_{p_\\star}(55)="
        + str(orders["55"])
        + ",\\quad "
        + "\\ord_{p_\\star}(89)="
        + str(orders["89"])
        + ",\\quad "
        + "\\ord_{p_\\star}(144)="
        + str(orders["144"])
        + ",\\\\"
    )
    rel = payload["relations_mod_p_star"]  # type: ignore[assignment]
    lines.append(
        "55\\equiv 34^{"
        + str(rel["exp_34_to_55"])
        + "}\\equiv 21^{"
        + str(rel["exp_21_to_55"])
        + "}\\pmod{p_\\star},\\qquad [\\langle 34\\rangle:\\langle 55\\rangle]="
        + str(rel["index_square_subgroup_to_order19"])
        + ".\\\\"
    )
    lines.append(
        "264^2\\equiv 34\\pmod{p_\\star},\\qquad 24^2\\equiv 5\\pmod{p_\\star},\\qquad "
        + "\\widehat\\varphi_\\pm:=\\frac{1\\pm 24}{2}\\equiv "
        + str(aux["phi_hat_plus"])
        + ",\\ "
        + str(aux["phi_hat_minus"])
        + "\\pmod{p_\\star}."
    )
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")
    tex_out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Audit mod-571 spectral collision and uplift orders for window-6.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_mod571_spectral_collision_audit.json"),
        help="Output JSON path.",
    )
    ap.add_argument(
        "--eq-tex-out",
        type=str,
        default=str(generated_dir() / "eq_window6_mod571_spectral_collision_audit.tex"),
        help="Output TeX equation path.",
    )
    args = ap.parse_args()

    p = P_STAR
    # f(t) = 48114 t^3 + 7263 t^2 - 506 t - 55
    f_low = [-55, -506, 7263, 48114]

    f1 = _poly_eval(f_low, 1, p=p)
    if f1 != 0:
        raise AssertionError(f"Expected f(1)=0 mod {p}, got {f1}")

    q_low, rem = _div_by_t_minus_a(f_low, a=1, p=p)
    if rem % p != 0:
        raise AssertionError(f"Expected remainder 0 dividing by (t-1), got {rem}")

    # Normalize the quadratic quotient to monic: q_low = a2 t^2 + a1 t + a0
    if len(q_low) != 3:
        raise AssertionError(f"Expected quadratic quotient, got degree {len(q_low)-1}")
    a2 = q_low[2] % p
    if a2 == 0:
        raise AssertionError("Unexpected a2=0 mod p (degenerate quotient)")
    inv_a2 = _inv(a2, p=p)
    q_monic_low = [(inv_a2 * (c % p)) % p for c in q_low]
    # Sanity check against the canonical factor shown in the internal audit text.
    if q_monic_low != [(-209) % p, 38 % p, 1]:
        raise AssertionError(f"Unexpected monic quadratic: {q_monic_low}")

    # Orders in F_p^× for boundary uplift deltas.
    orders = {str(a): _multiplicative_order(a, p=p) for a in (21, 34, 55, 89, 144, 274, 298)}
    # Required exact values.
    expected = {"21": 285, "34": 285, "55": 19, "89": 570, "144": 285, "274": 285, "298": 570}
    if any(orders[k] != v for k, v in expected.items()):
        raise AssertionError(f"Unexpected orders: {orders}, expected subset {expected}")

    # Auxiliary checks.
    if pow(264, 2, p) != 34 % p:
        raise AssertionError("Expected 264^2 == 34 mod p")
    if pow(24, 2, p) != 5 % p:
        raise AssertionError("Expected 24^2 == 5 mod p")
    inv2 = _inv(2, p=p)
    phi_hat_plus = ((1 + 24) * inv2) % p
    phi_hat_minus = ((1 - 24) * inv2) % p
    if (phi_hat_plus * phi_hat_plus - phi_hat_plus - 1) % p != 0:
        raise AssertionError("phi_hat_plus does not satisfy x^2-x-1=0 mod p")
    if (phi_hat_minus * phi_hat_minus - phi_hat_minus - 1) % p != 0:
        raise AssertionError("phi_hat_minus does not satisfy x^2-x-1=0 mod p")
    if pow(274, 13, p) != 34 % p:
        raise AssertionError("Expected 274^13 == 34 mod p")
    if pow(89, (p - 1) // 2, p) != p - 1:
        raise AssertionError("Expected 89^285 == -1 mod p")
    if pow(34, 15, p) != 55 % p:
        raise AssertionError("Expected 34^15 == 55 mod p")
    if pow(21, 30, p) != 55 % p:
        raise AssertionError("Expected 21^30 == 55 mod p")

    payload: Dict[str, object] = {
        "p_star": p,
        "polynomial_f": {
            "coeffs_low_to_high_Z": f_low,
            "coeffs_low_to_high_mod_p_star": [c % p for c in f_low],
            "f_1_mod_p_star": f1,
        },
        "factorization_mod_p_star": {
            "root": 1,
            "quotient_after_div_t_minus_1": [int(c % p) for c in q_low],
            "leading_coeff_quotient": int(a2),
            "monic_quadratic_factor": [int(c) for c in q_monic_low],
        },
        "orders_mod_p_star": {k: int(v) for k, v in orders.items()},
        "relations_mod_p_star": {
            "exp_34_to_55": 15,
            "exp_21_to_55": 30,
            "index_square_subgroup_to_order19": 285 // 19,
        },
        "auxiliary_checks_mod_p_star": {
            "sqrt34_witness": 264,
            "sqrt5_witness": 24,
            "phi_hat_plus": int(phi_hat_plus),
            "phi_hat_minus": int(phi_hat_minus),
            "delta34_as_phi_hat_minus_power": {"base": 274, "exp": 13, "value": 34},
            "primitive_root_witness": 89,
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    eq_tex_out = Path(str(args.eq_tex_out))
    eq_tex_out.parent.mkdir(parents=True, exist_ok=True)
    _write_eq_tex(eq_tex_out, payload=payload)


if __name__ == "__main__":
    main()

