#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate for the exact three-level escort model at m=6.

All output is English-only by repository convention.

At m=6 the audited fiber histogram is
  2:8, 3:4, 4:9,
so the finite-window escort partition function is
  Z_6(q) = 8*2^q + 4*3^q + 9*4^q.

We certify the unique crossover q_6^dagger > 0 defined by
  9*4^q = 8*2^q + 4*3^q,
equivalently by the condition that the d=4 mass of the escort law equals 1/2.

Outputs:
  - artifacts/export/window6_escort_threelevel_crossover_audit.json
  - sections/generated/eq_window6_escort_threelevel_crossover_audit.tex
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path

from common_paths import export_dir, generated_dir


def _balance(q: float) -> float:
    return 9.0 * (4.0 ** q) - 8.0 * (2.0 ** q) - 4.0 * (3.0 ** q)


def _partition_function(q: float) -> float:
    return 8.0 * (2.0 ** q) + 4.0 * (3.0 ** q) + 9.0 * (4.0 ** q)


def _mass_d4(q: float) -> float:
    return 9.0 * (4.0 ** q) / _partition_function(q)


def _bisect_unique_root(*, lo: float, hi: float, tol: float = 1.0e-16, max_iter: int = 256) -> float:
    flo = _balance(lo)
    fhi = _balance(hi)
    if flo == 0.0:
        return lo
    if fhi == 0.0:
        return hi
    if flo * fhi > 0.0:
        raise ValueError("Root bracket does not straddle zero.")
    for _ in range(max_iter):
        mid = 0.5 * (lo + hi)
        fmid = _balance(mid)
        if fmid == 0.0 or 0.5 * (hi - lo) < tol:
            return mid
        if flo * fmid <= 0.0:
            hi = mid
        else:
            lo = mid
            flo = fmid
    return 0.5 * (lo + hi)


def _fmt_decimal(x: float) -> str:
    return f"{x:.18f}"


def _fmt_sci(x: float) -> str:
    return f"{x:.16e}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit the exact m=6 escort three-level crossover.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_escort_threelevel_crossover_audit.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_window6_escort_threelevel_crossover_audit.tex"),
        help="Output TeX equation path.",
    )
    args = parser.parse_args()

    print("[window6-escort-threelevel] solving unique crossover", flush=True)
    q_star = _bisect_unique_root(lo=0.0, hi=1.0)
    residual = _balance(q_star)
    z_star = _partition_function(q_star)
    mass_d4 = _mass_d4(q_star)

    payload = {
        "fiber_histogram_m6": {"2": 8, "3": 4, "4": 9},
        "partition_function": "Z_6(q)=8*2^q+4*3^q+9*4^q",
        "q6_dagger": q_star,
        "balance_residual_at_q6_dagger": residual,
        "partition_function_at_q6_dagger": z_star,
        "escort_mass_d4_at_q6_dagger": mass_d4,
        "radial_design_certificate": {
            "sigma6_x1_fourth_moment": {
                "numerator": 2,
                "denominator": 9,
                "decimal": float(Fraction(2, 9)),
            },
            "sphere_x1_fourth_moment": {
                "numerator": 1,
                "denominator": 5,
                "decimal": float(Fraction(1, 5)),
            },
            "Q4_axis_value": 1.0,
            "Q4_diag_value": 0.5,
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_lines = [
        "% AUTO-GENERATED by scripts/exp_window6_escort_threelevel_crossover_audit.py",
        r"\begin{equation}\label{eq:window6_escort_threelevel_crossover_audit}",
        r"\begin{aligned}",
        rf"q_6^\dagger &\approx {_fmt_decimal(q_star)},\\",
        rf"9\cdot 4^{{q_6^\dagger}}-8\cdot 2^{{q_6^\dagger}}-4\cdot 3^{{q_6^\dagger}} &\approx {_fmt_sci(residual)},\\",
        rf"Z_6(q_6^\dagger) &\approx {_fmt_decimal(z_star)},\\",
        rf"\pi_{{6,q_6^\dagger}}(d=4) &\approx {_fmt_decimal(mass_d4)}.",
        r"\end{aligned}",
        r"\end{equation}",
        "",
    ]
    tex_out = Path(str(args.tex_out))
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    tex_out.write_text("\n".join(tex_lines), encoding="utf-8")

    print(f"File: {json_out.relative_to(export_dir().parent.parent)}", flush=True)
    print(f"File: {tex_out.relative_to(generated_dir().parent.parent)}", flush=True)
    print("[window6-escort-threelevel] done", flush=True)


if __name__ == "__main__":
    main()
