#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Prime-modulus scan for the worst twisted spectral ratio rho_{p,p,p}/lambda.

We scan the 3D residue-tensor twisting family used elsewhere in this paper:
  (chi mod p, N_- mod p, third axis mod p),
where the third axis is one of:
  - Ne (output-bit count e)
  - N2 (collision trigger 1_{d=2})

For each p, we compute:
  rho_{p,p,p} := max_{(j1,j2,j3) != (0,0,0)} rho(M(q,r,u)),
  ratio := rho_{p,p,p} / lambda,
  Delta := -log(ratio),
  and diagnostics of the "running law" candidates:
    C1(p) := p * Delta,   (1/p law candidate)
    C2(p) := p^2 * Delta. (1/p^2 (diffusive) candidate)

Outputs:
  - artifacts/export/real_input_40_rho_ppp_prime_scan.json
  - sections/generated/tab_real_input_40_rho_ppp_prime_scan.tex

All stdout is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress
from exp_sync_kernel_real_input_40_arity_3d import (
    build_kernel_edges,
    build_kernel_map,
    build_real_input_states,
    build_weighted_matrix_numeric,
    spectral_radius,
)


def _phi() -> float:
    return (1.0 + math.sqrt(5.0)) / 2.0


def _lambda_phi2() -> float:
    p = _phi()
    return p * p


def _parse_int_list_csv(s: str) -> List[int]:
    out: List[int] = []
    for tok in str(s).split(","):
        t = tok.strip()
        if not t:
            continue
        out.append(int(t))
    # stable, unique
    seen = set()
    uniq: List[int] = []
    for x in out:
        if x in seen:
            continue
        seen.add(x)
        uniq.append(x)
    return uniq


def _support_size(j: Tuple[int, int, int]) -> int:
    return int((j[0] != 0) + (j[1] != 0) + (j[2] != 0))


def _worst_rho_ppp(
    *,
    p: int,
    third_axis: str,
    states,
    kernel_map,
    prog: Progress,
    eps: float,
) -> Tuple[float, List[Tuple[int, int, int]]]:
    if p < 2:
        raise ValueError("p must be >= 2")
    if third_axis not in ("Ne", "N2"):
        raise ValueError("third_axis must be one of {Ne,N2}")

    omega = np.exp(2j * math.pi / float(p))
    roots = [omega**j for j in range(p)]

    rho_max = -1.0
    argmax: List[Tuple[int, int, int]] = []
    total = p * p * p - 1
    done = 0

    for j1 in range(p):
        q = roots[j1]
        for j2 in range(p):
            r = roots[j2]
            for j3 in range(p):
                if j1 == 0 and j2 == 0 and j3 == 0:
                    continue
                u = roots[j3]
                M = build_weighted_matrix_numeric(
                    q, r, u, states, kernel_map, third_axis=third_axis
                )
                rho = float(spectral_radius(M))
                if rho > rho_max + eps:
                    rho_max = rho
                    argmax = [(int(j1), int(j2), int(j3))]
                elif abs(rho - rho_max) <= eps:
                    argmax.append((int(j1), int(j2), int(j3)))

                done += 1
                if done % 200 == 0:
                    prog.tick(f"p={p} scan {done}/{total} rho_max~{rho_max:.12f}")

    # Stable ordering (lexicographic).
    argmax.sort()
    return float(rho_max), argmax


@dataclass(frozen=True)
class Row:
    p: int
    third_axis: str
    lambda_phi2: float
    lambda_pf: float
    lambda_abs_err: float
    rho_max: float
    rho_over_lambda: float
    delta_minus_log_rho_over_lambda: float
    gap_1_minus_rho_over_lambda: float
    C1_p_times_delta: float
    C2_p2_times_delta: float
    argmax_j: List[List[int]]
    j_support_min: int
    j_support_max: int


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _write_tex(path: Path, rows: Sequence[Row]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_rho_ppp_prime_scan.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{Worst twisted spectral ratios $\\rho_{p,p,p}/\\lambda$ for the real-input 40-state kernel, "
        "and two running-law diagnostics $C_1(p)=p\\cdot(-\\log(\\rho/\\lambda))$ and "
        "$C_2(p)=p^2\\cdot(-\\log(\\rho/\\lambda))$ (third axis: $N_e$ or $N_2$).}"
    )
    lines.append("\\label{tab:real-input-40-rho-ppp-prime-scan}")
    lines.append("\\begin{tabular}{r l r r r r}")
    lines.append("\\toprule")
    lines.append(
        "$p$ & axis & $\\rho/\\lambda$ & $-\\log(\\rho/\\lambda)$ & $p\\,\\Delta$ & $p^2\\,\\Delta$\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.p} & {r.third_axis} & {_fmt(r.rho_over_lambda)} & {_fmt(r.delta_minus_log_rho_over_lambda)}"
            f" & {_fmt(r.C1_p_times_delta)} & {_fmt(r.C2_p2_times_delta)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Scan rho_{p,p,p}/lambda for primes p.")
    parser.add_argument(
        "--p-list",
        type=str,
        default="2,3,5,7,11,13",
        help="Comma-separated moduli p (typically primes).",
    )
    parser.add_argument(
        "--third-axis",
        type=str,
        default="Ne",
        choices=["Ne", "N2"],
        help="Third axis choice: Ne (output-bit count) or N2 (collision trigger count).",
    )
    parser.add_argument(
        "--eps-argmax",
        type=float,
        default=1e-10,
        help="Absolute tolerance for collecting argmax character indices.",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_rho_ppp_prime_scan.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_real_input_40_rho_ppp_prime_scan.tex"),
    )
    args = parser.parse_args()

    ps = _parse_int_list_csv(str(args.p_list))
    if not ps:
        raise SystemExit("Empty --p-list")
    third_axis = str(args.third_axis)
    eps = float(args.eps_argmax)

    prog = Progress("rho_ppp_scan", every_seconds=20.0)
    edges = build_kernel_edges()
    kernel_map = build_kernel_map(edges)
    states = build_real_input_states()

    # Baseline lambda check (untwisted). Third axis irrelevant at q=r=u=1.
    lam_phi2 = _lambda_phi2()
    M1 = build_weighted_matrix_numeric(
        1.0 + 0.0j,
        1.0 + 0.0j,
        1.0 + 0.0j,
        states,
        kernel_map,
        third_axis=third_axis,
    )
    lam_pf = float(spectral_radius(M1))
    lam_abs_err = float(abs(lam_pf - lam_phi2))
    if lam_abs_err > 5e-10:
        print(
            f"[rho-ppp] WARNING: spectral_radius(M1)={lam_pf:.12f} differs from phi^2={lam_phi2:.12f} by {lam_abs_err:.3e}",
            flush=True,
        )

    rows: List[Row] = []
    for p in ps:
        rho_max, argmax = _worst_rho_ppp(
            p=int(p),
            third_axis=third_axis,
            states=states,
            kernel_map=kernel_map,
            prog=prog,
            eps=eps,
        )
        ratio = float(rho_max / lam_phi2) if lam_phi2 > 0 else 0.0
        delta = float(-math.log(ratio)) if (0.0 < ratio < 1.0) else float("inf")
        gap_lin = float(1.0 - ratio) if (0.0 < ratio < 1.0) else float("inf")
        C1 = float(p) * float(delta) if math.isfinite(delta) else float("inf")
        C2 = float(p * p) * float(delta) if math.isfinite(delta) else float("inf")
        supps = [_support_size(j) for j in argmax] if argmax else [0]
        rows.append(
            Row(
                p=int(p),
                third_axis=str(third_axis),
                lambda_phi2=float(lam_phi2),
                lambda_pf=float(lam_pf),
                lambda_abs_err=float(lam_abs_err),
                rho_max=float(rho_max),
                rho_over_lambda=float(ratio),
                delta_minus_log_rho_over_lambda=float(delta),
                gap_1_minus_rho_over_lambda=float(gap_lin),
                C1_p_times_delta=float(C1),
                C2_p2_times_delta=float(C2),
                argmax_j=[list(map(int, j)) for j in argmax],
                j_support_min=int(min(supps)),
                j_support_max=int(max(supps)),
            )
        )
        print(
            f"[rho-ppp] p={int(p):>3} axis={third_axis} ratio={ratio:.12f} "
            f"Delta={delta:.12f} p*Delta={C1:.12f} p^2*Delta={C2:.12f} "
            f"support={min(supps)}--{max(supps)} argmax={len(argmax)}",
            flush=True,
        )

    # Stable sort by p.
    rows.sort(key=lambda r: (r.p, r.third_axis))

    # Simple aggregate diagnostics (mean/stdev over p>=3, excluding p=2 if present).
    C1s = [r.C1_p_times_delta for r in rows if r.p >= 3 and math.isfinite(r.C1_p_times_delta)]
    C2s = [r.C2_p2_times_delta for r in rows if r.p >= 3 and math.isfinite(r.C2_p2_times_delta)]
    def _mean_std(xs: Sequence[float]) -> Tuple[float, float]:
        if not xs:
            return (float("nan"), float("nan"))
        m = float(sum(xs) / float(len(xs)))
        v = float(sum((x - m) ** 2 for x in xs) / float(len(xs)))
        return (m, float(v ** 0.5))
    C1_mean, C1_std = _mean_std(C1s)
    C2_mean, C2_std = _mean_std(C2s)

    payload: Dict[str, object] = {
        "params": {
            "p_list": [int(p) for p in ps],
            "third_axis": third_axis,
            "eps_argmax": eps,
        },
        "lambda_phi2": float(lam_phi2),
        "lambda_pf": float(lam_pf),
        "lambda_abs_err": float(lam_abs_err),
        "rows": [asdict(r) for r in rows],
        "aggregates_p_ge_3": {
            "C1_mean": float(C1_mean),
            "C1_std": float(C1_std),
            "C2_mean": float(C2_mean),
            "C2_std": float(C2_std),
        },
    }

    jout = Path(str(args.json_out))
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[rho-ppp] wrote {jout}", flush=True)

    tout = Path(str(args.tex_out))
    _write_tex(tout, rows)
    print(f"[rho-ppp] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

