#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Backtracking entropy gap derived from the Ihara fingerprints table.

Given rho(A) (ordinary adjacency) and rho(B) (Hashimoto non-backtracking),
define:
  Delta_h := log rho(A) - log rho(B) = log(rho(A)/rho(B)),
so that the ratio of ordinary vs non-backtracking closed-walk growth scales like
  (rho(A)/rho(B))^n = exp(n * Delta_h).

Outputs:
  - artifacts/export/parallel_addition_kernels_backtracking_entropy_gap.json
  - sections/generated/tab_parallel_addition_kernels_backtracking_entropy_gap.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class Row:
    name: str
    rho_A: float
    rho_B: float
    delta_h: float
    ratio: float
    factor_n: float


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def make_table(rows: List[Row], n: int) -> str:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_parallel_addition_kernels_backtracking_entropy_gap.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\begin{tabular}{@{}lrrrr@{}}")
    lines.append("\\toprule")
    lines.append("核 & $\\Delta h$ & $\\rho(A)/\\rho(B)$ & $e^{%d\\Delta h}$ & $(\\rho(A)/\\rho(B))^{%d}$\\\\"
                 % (n, n))
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r.name} & {r.delta_h:.6f} & {r.ratio:.6f} & {math.exp(n*r.delta_h):.6g} & {r.factor_n:.6g}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Backtracking entropy gap derived from Ihara fingerprints. "
        "We define $\\Delta h:=\\log\\rho(A)-\\log\\rho(B)$, so that the growth ratio between ordinary closed walks "
        "and non-backtracking closed walks scales like $e^{n\\Delta h}=(\\rho(A)/\\rho(B))^n$.}"
    )
    lines.append("\\label{tab:parallel_addition_kernels_backtracking_entropy_gap}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=str,
        default="",
        help="Input JSON (default: artifacts/export/parallel_addition_kernels_ihara.json)",
    )
    parser.add_argument("--n", type=int, default=50, help="Length n used for amplification factor.")
    parser.add_argument("--no-output", action="store_true")
    args = parser.parse_args()

    in_path = Path(args.input) if args.input else (export_dir() / "parallel_addition_kernels_ihara.json")
    payload = _read_json(in_path)
    rows_in = payload.get("rows", [])

    out: List[Row] = []
    for r in rows_in:
        name = str(r.get("name", ""))
        rho_A = float(r.get("rho_A", 0.0))
        rho_B = float(r.get("rho_B", 0.0))
        if rho_A <= 0 or rho_B <= 0:
            continue
        delta_h = math.log(rho_A) - math.log(rho_B)
        ratio = rho_A / rho_B
        factor_n = ratio ** int(args.n)
        out.append(Row(name=name, rho_A=rho_A, rho_B=rho_B, delta_h=delta_h, ratio=ratio, factor_n=factor_n))

    if not args.no_output:
        out_json = export_dir() / "parallel_addition_kernels_backtracking_entropy_gap.json"
        _write_text(out_json, json.dumps({"n": int(args.n), "rows": [asdict(x) for x in out]}, indent=2, sort_keys=True) + "\n")
        print(f"[par-add-entropy-gap] wrote {out_json}", flush=True)

        out_tex = generated_dir() / "tab_parallel_addition_kernels_backtracking_entropy_gap.tex"
        _write_text(out_tex, make_table(out, n=int(args.n)))
        print(f"[par-add-entropy-gap] wrote {out_tex}", flush=True)


if __name__ == "__main__":
    main()

