#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Discriminant certificate for the A4 Newman ratio minimal polynomial Q4(t).

This script complements exp_collision_kernel_A4_newman_u4_certificate.py by producing
an explicit discriminant factorization and squarefree-kernel fingerprint.

Outputs:
  - artifacts/export/collision_kernel_A4_newman_u4_discriminant_certificate.json
  - sections/generated/eq_collision_kernel_A4_newman_u4_discriminant_factorization.tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Tuple

import sympy as sp

from common_paths import export_dir, generated_dir


def Q4_poly() -> Tuple[sp.Symbol, sp.Poly, Dict[str, object]]:
    t = sp.Symbol("t")
    coeffs = [
        4,
        -64,
        80,
        -46260,
        -127612,
        1584408,
        7293617,
        76445526,
        -26190147,
        -75382686,
        5220754,
        53887216,
        -42120556,
        1739748,
        -3577332,
        760256,
        144576,
        -54720,
        -10880,
        -64,
        64,
    ]
    expr = sum(sp.Integer(c) * t ** (20 - i) for i, c in enumerate(coeffs))
    P = sp.Poly(expr, t, domain=sp.ZZ)
    meta = {"coeffs_deg20_to_0": coeffs, "degree": int(P.degree()), "lc": int(P.LC())}
    return t, P, meta


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute discriminant certificate for Q4(t).")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4_newman_u4_discriminant_certificate.json"),
        help="Output JSON path.",
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_newman_u4_discriminant_factorization.tex"),
        help="Output LaTeX equation path.",
    )
    args = parser.parse_args()

    t, Q4, meta = Q4_poly()
    disc = int(sp.discriminant(Q4.as_expr(), t))
    sign = -1 if disc < 0 else 1
    fac = sp.factorint(abs(disc))

    # Squarefree kernel (with sign): product of primes with odd exponent times sign.
    sf = sign
    for p, e in fac.items():
        if e % 2 == 1:
            sf *= int(p)

    payload: Dict[str, object] = {
        "meta": {
            "script": Path(__file__).name,
            "sympy": sp.__version__,
        },
        "Q4": meta,
        "Disc_Q4": disc,
        "Disc_Q4_factorint": {str(k): int(v) for k, v in fac.items()},
        "Disc_Q4_squarefree_kernel": sf,
    }
    _write_json(Path(args.json_out), payload)
    print(f"[A4-u4-disc] wrote {args.json_out}", flush=True)

    # Render a compact factorization; keep it fully explicit as in other generated eq_* files.
    parts = []
    for p in sorted(fac.keys()):
        e = fac[p]
        if e == 1:
            parts.append(f"{p}")
        else:
            parts.append(f"{p}^{{{e}}}")
    rhs = r"\cdot ".join(parts) if parts else "1"
    rhs = f"-{rhs}" if sign < 0 else rhs

    tex = [
        "% Auto-generated by scripts/exp_collision_kernel_A4_newman_u4_discriminant_certificate.py",
        r"\begin{equation}\label{eq:collision_kernel_A4_newman_u4_discriminant_factorization}",
        r"\boxed{\;",
        rf"\Disc\!\bigl(Q_4(t)\bigr)={rhs}\;",
        r"}",
        r"\end{equation}",
        "",
    ]
    _write_text(Path(args.tex_out), "\n".join(tex))
    print(f"[A4-u4-disc] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

