#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Minimal polynomials and discriminant fingerprints for ADE intersection parameters t_{E_k}.

In the 4th-collision kernel family A_4(t) (see the manuscript), the Perron index curve is
parameterized by

  t(I) := (I^5 - 2 I^4 - 2 I + 2) / I^3,

so that r_4(t(I)) = I when t(I) >= 0.

We specialize to the ADE Jones index points:

  I_{E6} = 4 cos^2(pi/12),
  I_{E7} = 4 cos^2(pi/18),
  I_{E8} = 4 cos^2(pi/30),

and compute:
  - t_{E_k} := t(I_{E_k}) as exact algebraic numbers,
  - the primitive integer minimal polynomials of t_{E_k},
  - discriminants and their prime-power factorizations (including squarefree parts).

Outputs:
  - artifacts/export/collision_kernel_A4_ade_intersection_t_minpoly_discriminant.json
  - sections/generated/eq_collision_kernel_A4_ade_intersection_t_minpoly_discriminant.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import mpmath as mp
import sympy as sp

from common_paths import export_dir, generated_dir


def _fmt(x: mp.mpf, nd: int = 16) -> str:
    return mp.nstr(x, nd)


def _poly_primitive_integer(expr: sp.Expr, var: sp.Symbol) -> sp.Poly:
    """
    Given a polynomial expression over QQ, clear denominators and return a primitive Poly over ZZ
    with positive leading coefficient.
    """
    pQQ = sp.Poly(sp.expand(expr), var, domain=sp.QQ)
    den_lcm = sp.ilcm(*[sp.denom(c) for c in pQQ.all_coeffs()]) if pQQ.degree() >= 0 else sp.Integer(1)
    pZ = sp.Poly(sp.expand(den_lcm * pQQ.as_expr()), var, domain=sp.ZZ)
    content = sp.gcd_list(pZ.all_coeffs()) if pZ.degree() >= 0 else sp.Integer(1)
    pZ = sp.Poly(sp.expand(pZ.as_expr() / content), var, domain=sp.ZZ)
    if pZ.LC() < 0:
        pZ = -pZ
    return pZ


def _factorint_signed(n: sp.Integer) -> Tuple[int, Dict[int, int]]:
    """Return (sign, factorization) where sign in {-1, +1} and factorization is for |n|."""
    n_int = int(n)
    sign = -1 if n_int < 0 else 1
    fac = sp.factorint(abs(n_int))
    return sign, {int(p): int(e) for p, e in fac.items()}


def _factor_tex(sign: int, fac: Dict[int, int]) -> str:
    parts: List[str] = []
    if sign < 0:
        parts.append("-")
    for p in sorted(fac.keys()):
        e = fac[p]
        if e == 1:
            parts.append(f"{p}")
        else:
            parts.append(f"{p}^{{{e}}}")
    # Keep "-" as its own token if present.
    if parts and parts[0] == "-":
        return "-" + r"\cdot ".join(parts[1:]) if len(parts) > 1 else "-"
    return r"\cdot ".join(parts)


def _squarefree_part(fac: Dict[int, int]) -> int:
    sf = 1
    for p, e in fac.items():
        if e % 2 == 1:
            sf *= p
    return sf


@dataclass(frozen=True)
class MinpolyDisc:
    name: str
    # algebraic value (decimal string)
    value: str
    # primitive integer minimal polynomial
    degree: int
    coeffs_desc: List[int]
    # discriminant
    disc: str
    disc_factor: Dict[int, int]
    disc_squarefree_part: int


def _t_of_I(I: sp.Expr) -> sp.Expr:
    return sp.simplify((I**5 - 2 * I**4 - 2 * I + 2) / (I**3))


def _minpoly_disc(name: str, alpha: sp.Expr, *, var: sp.Symbol, dps: int) -> MinpolyDisc:
    minpoly_expr = sp.minimal_polynomial(alpha, var)
    pZ = _poly_primitive_integer(minpoly_expr, var)

    disc = sp.discriminant(pZ.as_expr(), var)
    sign, fac = _factorint_signed(sp.Integer(disc))
    sf = _squarefree_part(fac)

    val = mp.mpf(str(sp.N(alpha, dps)))

    return MinpolyDisc(
        name=name,
        value=_fmt(val, 40),
        degree=int(pZ.degree()),
        coeffs_desc=[int(c) for c in pZ.all_coeffs()],
        disc=str(int(disc)),
        disc_factor=fac,
        disc_squarefree_part=int(sf),
    )


def _write_tex(path: Path, certs: List[MinpolyDisc]) -> None:
    t = sp.Symbol("t")

    def poly_tex(coeffs_desc: List[int]) -> str:
        p = sp.Poly.from_list([sp.Integer(c) for c in coeffs_desc], gens=t)
        return sp.latex(p.as_expr())

    # Locate in the order E6/E7/E8.
    by_name = {c.name: c for c in certs}
    e6 = by_name["E6"]
    e7 = by_name["E7"]
    e8 = by_name["E8"]

    disc7_tex = _factor_tex(1, e7.disc_factor)
    disc8_tex = _factor_tex(1, e8.disc_factor)

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_collision_kernel_A4_ade_intersection_t_minpoly_discriminant.py")
    lines.append(r"\begin{equation}\label{eq:collision_kernel_A4_ade_intersection_t_minpoly_discriminant}")
    lines.append(r"\begin{aligned}")
    lines.append(rf"P_{{E_6}}(t)&:={poly_tex(e6.coeffs_desc)},\\")
    lines.append(rf"P_{{E_7}}(t)&:={poly_tex(e7.coeffs_desc)},\qquad \mathrm{{Disc}}(P_{{E_7}})={disc7_tex},\\")
    lines.append(rf"P_{{E_8}}(t)&:={poly_tex(e8.coeffs_desc)},\qquad \mathrm{{Disc}}(P_{{E_8}})={disc8_tex}.")
    lines.append(r"\end{aligned}")
    lines.append(r"\end{equation}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compute minpolys/discriminants for t_{E6}, t_{E7}, t_{E8}.")
    parser.add_argument("--dps", type=int, default=120, help="Working decimal precision (sympy evalf).")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "collision_kernel_A4_ade_intersection_t_minpoly_discriminant.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_collision_kernel_A4_ade_intersection_t_minpoly_discriminant.tex"),
    )
    args = parser.parse_args()

    dps = int(args.dps)
    if dps < 60:
        raise SystemExit("Require --dps >= 60 for stable algebraic evaluation.")
    mp.mp.dps = dps

    # ADE Jones indices
    I_E6 = sp.simplify(4 * sp.cos(sp.pi / 12) ** 2)
    I_E7 = sp.simplify(4 * sp.cos(sp.pi / 18) ** 2)
    I_E8 = sp.simplify(4 * sp.cos(sp.pi / 30) ** 2)

    t_E6 = _t_of_I(I_E6)
    t_E7 = _t_of_I(I_E7)
    t_E8 = _t_of_I(I_E8)

    t = sp.Symbol("t")
    certs = [
        _minpoly_disc("E6", t_E6, var=t, dps=dps),
        _minpoly_disc("E7", t_E7, var=t, dps=dps),
        _minpoly_disc("E8", t_E8, var=t, dps=dps),
    ]

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps([asdict(c) for c in certs], indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[A4-ADE-minpoly] wrote {jout}", flush=True)

    _write_tex(Path(args.tex_out), certs)
    print(f"[A4-ADE-minpoly] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

