#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spectral gap audit for the window-6 pushforward Markov kernel P6 on X6.

All code is English-only by repository convention.

We consider the Markov kernel on stable types induced by:
  - choose omega uniformly inside the fiber of a stable type w,
  - take one uniform cube step (flip one of 6 bits),
  - observe the next stable type.

This is precisely the pushforward kernel P6(w,w') = A6(w,w') / (6 d^{bin}_6(w)),
where A6 counts directed cube edges between fibers and d^{bin}_6(w) is the fiber size.

We compute:
  - the full eigenvalue list (via the symmetric conjugate using stationarity pi6),
  - the second-largest eigenvalue lambda2,
  - the absolute SLEM lambda_* := max_{i>=2} |lambda_i|,
  - the corresponding gaps 1-lambda2 and 1-lambda_*.

Outputs:
  - artifacts/export/window6_pushforward_markov_spectral_gap.json
  - sections/generated/eq_window6_pushforward_markov_spectral_gap.tex
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from common_paths import export_dir, generated_dir
from common_phi_fold import word_to_str, zeckendorf_digits


def _foldbin6_label(n: int) -> str:
    # For m=6, K(6)=9 (F_{10}=55 ≤ 63 < F_{11}=89), so digits up to k=9 are exact.
    digits = zeckendorf_digits(n, 9)  # digits for weights F_{k+1}, k=1..9
    return word_to_str(digits[:6])


def _build_P6() -> Tuple[List[str], List[int], List[List[Fraction]]]:
    m = 6
    label_of_n = [_foldbin6_label(n) for n in range(1 << m)]
    words = sorted(set(label_of_n))
    if len(words) != 21:
        raise RuntimeError(f"Unexpected |X6|={len(words)} (expected 21).")

    idx = {w: i for i, w in enumerate(words)}
    d = [0 for _ in words]
    for n in range(1 << m):
        d[idx[label_of_n[n]]] += 1

    # Directed edge counts between fibers.
    A6 = [[0 for _ in words] for _ in words]
    for n in range(1 << m):
        i = idx[label_of_n[n]]
        for j in range(m):
            nn = n ^ (1 << j)
            k = idx[label_of_n[nn]]
            A6[i][k] += 1

    # Build P6.
    P6: List[List[Fraction]] = [[Fraction(0) for _ in words] for _ in words]
    for i, w in enumerate(words):
        denom = Fraction(m * d[i], 1)
        for j in range(len(words)):
            P6[i][j] = Fraction(A6[i][j], 1) / denom

    return words, d, P6


def _symmetrize(P: np.ndarray, pi: np.ndarray) -> np.ndarray:
    # S = D^{1/2} P D^{-1/2} is symmetric when P is reversible w.r.t. pi.
    s = np.sqrt(pi)
    S = (s[:, None] * P) / s[None, :]
    # Numerical symmetrization to remove tiny floating errors.
    return 0.5 * (S + S.T)


def _write_eq_tex(*, lambda2: float, gap2: float, lambda_star: float, gap_star: float, out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_window6_pushforward_markov_spectral_gap.py")
    lines.append("\\begin{equation}\\label{eq:window6_pushforward_markov_spectral_gap}")
    lines.append("\\begin{aligned}")
    lines.append(
        "\\lambda_2(P_6)&\\approx "
        + f"{lambda2:.15f}"
        + ",\\qquad 1-\\lambda_2(P_6)\\approx "
        + f"{gap2:.15f}"
        + ",\\\\"
        + "\\lambda_{\\star}(P_6)&:=\\max_{i\\ge 2}|\\lambda_i(P_6)|\\approx "
        + f"{lambda_star:.15f}"
        + ",\\qquad 1-\\lambda_{\\star}(P_6)\\approx "
        + f"{gap_star:.15f}"
        + "."
    )
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute spectral gap constants for the window-6 pushforward kernel P6.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_pushforward_markov_spectral_gap.json"),
        help="Path to JSON audit output.",
    )
    ap.add_argument(
        "--tex-eq-out",
        type=str,
        default=str(generated_dir() / "eq_window6_pushforward_markov_spectral_gap.tex"),
        help="Path to generated TeX equation snippet (\\input{}).",
    )
    args = ap.parse_args()

    words, d, P6_frac = _build_P6()
    n = len(words)

    P = np.zeros((n, n), dtype=np.float64)
    for i in range(n):
        for j in range(n):
            P[i, j] = float(P6_frac[i][j])

    # Stationary distribution pi6(w) = d(w)/64.
    pi = np.array([di / 64.0 for di in d], dtype=np.float64)
    if not np.isclose(pi.sum(), 1.0):
        raise RuntimeError("pi does not sum to 1 (numerical).")

    # Symmetric conjugate and eigenvalues.
    S = _symmetrize(P, pi)
    evals = np.linalg.eigvalsh(S)  # ascending
    evals_desc = evals[::-1]

    lambda1 = float(evals_desc[0])
    lambda2 = float(evals_desc[1])
    lambda_star = float(np.max(np.abs(evals_desc[1:])))

    payload: Dict[str, object] = {
        "m": 6,
        "words": words,
        "fiber_size_d_bin": {w: int(di) for w, di in zip(words, d)},
        "pi6_stationary": {w: float(di / 64.0) for w, di in zip(words, d)},
        "eigenvalues_desc": [float(x) for x in evals_desc.tolist()],
        "lambda1": lambda1,
        "lambda2": lambda2,
        "lambda_star": lambda_star,
        "gap_1_minus_lambda2": float(1.0 - lambda2),
        "gap_1_minus_lambda_star": float(1.0 - lambda_star),
        "sanity": {
            "lambda1_close_to_1": bool(abs(lambda1 - 1.0) < 1e-12),
            "S_symmetric_max_abs_diff": float(np.max(np.abs(S - S.T))),
            "row_stochastic_max_abs_error": float(np.max(np.abs(P.sum(axis=1) - 1.0))),
            "detailed_balance_max_abs_error": float(
                np.max(np.abs((pi[:, None] * P) - (pi[None, :] * P.T)))
            ),
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_out = Path(str(args.tex_eq_out))
    _write_eq_tex(
        lambda2=lambda2,
        gap2=1.0 - lambda2,
        lambda_star=lambda_star,
        gap_star=1.0 - lambda_star,
        out_path=tex_out,
    )

    print(f"[window6_P6_gap] wrote {json_out}", flush=True)
    print(f"[window6_P6_gap] wrote {tex_out}", flush=True)


if __name__ == "__main__":
    main()

