#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: gap ledger invariants for the semigroup <21,34>.

All output is English-only by repository convention.

Let S := <21,34> ⊂ N and let G be its gap set (nonnegative integers not in S).
We compute:
  - genus |G| (count of gaps),
  - sum_{n in G} n and the mean,
  - Apéry-derived congruence truncation lengths g_r and their second-order sums:
      sum g_r, sum binom(g_r,2), sum g_r^2, sum r*g_r.

Outputs:
  - artifacts/export/window6_tail_semigroup_gap_ledger_21_34.json
  - sections/generated/eq_window6_tail_semigroup_gap_ledger_21_34.tex
"""

from __future__ import annotations

import argparse
import json
from math import gcd
from pathlib import Path
from typing import Dict, List, Tuple

from common_paths import export_dir, generated_dir


def _reachable_dp(*, gens: Tuple[int, ...], N: int) -> List[bool]:
    ok = [False] * (N + 1)
    ok[0] = True
    for n in range(1, N + 1):
        ok[n] = any(n - g >= 0 and ok[n - g] for g in gens)
    return ok


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute gap ledger invariants for <21,34>.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "window6_tail_semigroup_gap_ledger_21_34.json"),
        help="Output JSON path.",
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_window6_tail_semigroup_gap_ledger_21_34.tex"),
        help="Output TeX equation path.",
    )
    args = ap.parse_args()

    a = 21
    b = 34
    gens = (a, b)
    g_frob = a * b - a - b  # Frobenius number for two generators
    conductor = g_frob + 1

    ok = _reachable_dp(gens=gens, N=conductor + 100)
    # Gaps are in [1..g_frob]; 0 is reachable.
    gaps = [n for n in range(1, conductor) if not ok[n]]
    genus = len(gaps)
    sum_gaps = sum(gaps)

    # Apéry/congruence truncations.
    inv = pow(b % a, -1, a)  # should be 13
    b_r = [(inv * r) % a for r in range(a)]
    w_r = [b * br for br in b_r]  # Apéry set
    g_r = [(w_r[r] - r) // a for r in range(a)]

    # Ledger sums.
    sum_g_r = sum(g_r)
    sum_choose = sum(gr * (gr - 1) // 2 for gr in g_r)
    sum_g2 = sum(gr * gr for gr in g_r)
    sum_rg = sum(r * g_r[r] for r in range(a))

    # Sum gaps via truncation decomposition: gaps are {r + a*k : 0<=k<g_r}.
    sum_gaps_by_r = 0
    for r in range(a):
        gr = g_r[r]
        # sum_{k=0}^{gr-1} (r + a*k) = gr*r + a*gr*(gr-1)/2
        sum_gaps_by_r += gr * r + a * gr * (gr - 1) // 2

    if sum_gaps_by_r != sum_gaps:
        raise AssertionError("Gap sum mismatch between DP and congruence decomposition.")

    payload: Dict[str, object] = {
        "semigroup": {"generators": list(gens)},
        "frobenius": g_frob,
        "conductor": conductor,
        "genus": genus,
        "sum_gaps": sum_gaps,
        "mean_gaps": {"num": sum_gaps, "den": genus},
        "apery": {
            "modulus": a,
            "inverse_b_mod_a": inv,
            "b_r": b_r,
            "w_r": w_r,
            "g_r": g_r,
        },
        "ledger": {
            "sum_g_r": sum_g_r,
            "sum_binom_g_r_2": sum_choose,
            "sum_g_r_sq": sum_g2,
            "sum_r_g_r": sum_rg,
        },
        "checks": {
            "dp_sum_gaps_by_r": sum_gaps_by_r,
            "dp_max_gap": max(gaps) if gaps else None,
        },
    }

    json_out = Path(str(args.json_out))
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # TeX snippet (ledger).
    tex_out = Path(str(args.tex_out))
    tex_out.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_window6_tail_semigroup_gap_ledger_21_34.py")
    lines.append("\\begin{equation}\\label{eq:window6_tail_semigroup_gap_ledger_21_34}")
    lines.append("\\begin{aligned}")
    lines.append(f"|\\mathcal{{G}}|&={genus},")
    lines.append(f"&\\sum_{{n\\in\\mathcal{{G}}}} n&={sum_gaps},")
    g_mean = gcd(sum_gaps, genus)
    mean_num = sum_gaps // g_mean
    mean_den = genus // g_mean
    mean_tex = f"\\frac{{{mean_num}}}{{{mean_den}}}" if mean_den != 1 else str(mean_num)
    lines.append(f"&\\frac{{1}}{{|\\mathcal{{G}}|}}\\sum_{{n\\in\\mathcal{{G}}}} n&={mean_tex},\\\\")
    lines.append(f"\\sum_{{r=0}}^{{20}} g_r&={sum_g_r},")
    lines.append(f"&\\sum_{{r=0}}^{{20}}\\binom{{g_r}}{{2}}&={sum_choose},")
    lines.append(f"&\\sum_{{r=0}}^{{20}} g_r^2&={sum_g2},")
    lines.append(f"&\\sum_{{r=0}}^{{20}} r\\,g_r&={sum_rg}.")
    lines.append("\\end{aligned}")
    lines.append("\\end{equation}")
    lines.append("")
    tex_out.write_text("\n".join(lines), encoding="utf-8")

    # Hard expectations (guard rails).
    if genus != 330 or sum_gaps != 75460 or sum_choose != 3432 or sum_g2 != 7194 or sum_rg != 3388:
        raise AssertionError("Unexpected ledger invariants.")

    print(f"File: {json_out.relative_to(export_dir().parent.parent)}")
    print(f"File: {tex_out.relative_to(generated_dir().parent.parent)}")


if __name__ == "__main__":
    main()

