#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scan character twists of a 3-state *difference-chain* realization for Fold collision S2.

Background (audit-friendly):
  Let microstates be ω,ω' ∈ {0,1}^m with window value
      N(ω) = sum_{k=1..m} ω_k F_{k+1}.
  For the second collision moment,
      S2(m) = #{(ω,ω') : N(ω) ≡ N(ω') (mod F_{m+2})}.

  Equivalently, write δ_k = ω_k - ω'_k ∈ {-1,0,1}. Each δ_k=0 has multiplicity 2
  (pairs (0,0) or (1,1)); δ_k=±1 has multiplicity 1. Define the difference
  polynomial
      P_m(z) = Π_{k=1..m} (2 + z^{F_{k+1}} + z^{-F_{k+1}})
             = Σ_D a_m(D) z^D,
  where a_m(D) counts pairs (ω,ω') with N(ω)-N(ω') = D (with the above weights).
  Then (since |D|<2F_{m+2} for these weights)
      S2(m) = a_m(0) + a_m(F_{m+2}) + a_m(-F_{m+2}).

  Tracking just three coefficients
      X_m := a_m(0),
      U_m := a_m(F_{m+1}),
      V_m := a_m(F_{m+2}),
  yields an exact 3-state update v_{m+1} = M v_m with
      v_m := (X_m, U_m, V_m)^T,
      M   := [[2,0,2],
              [1,0,2],
              [0,1,0]],
  which has the same characteristic polynomial as the paper's nonnegative
  realization A2 (hence the same Perron root r2 and sub-spectrum).

Difference-chain edge labels and twisting:
  The update M naturally decomposes by the per-step input difference δ ∈ {-1,0,+1}:
    - δ=0 contributes multiplicity 2,
    - δ=+1 contributes multiplicity 1,
    - δ=-1 contributes multiplicity 1,
  in a way that induces a labeled multigraph on the 3 states.

  For a character χ of a cyclic group with χ(1)=u (a root of unity), define the
  twisted transfer matrix
      M(u) = M0 + u M_plus + u^{-1} M_minus,
  where M0, M_plus, M_minus collect the labeled edge multiplicities.

  This script scans u = exp(2π i r/n) (roots of unity) and reports the maximum
  spectral radius ρ(M(u)) over nontrivial twists (u != 1).

Outputs (default):
  - artifacts/export/fold_collision_a2_twist_difference_chain_scan.json
  - sections/generated/tab_fold_collision_a2_twist_difference_chain_scan.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from common_paths import export_dir, generated_dir


def perron_root_r2() -> float:
    """Largest real root of x^3 - 2x^2 - 2x + 2 = 0."""

    def f(x: float) -> float:
        return x**3 - 2.0 * x**2 - 2.0 * x + 2.0

    def df(x: float) -> float:
        return 3.0 * x**2 - 4.0 * x - 2.0

    x = 2.5
    for _ in range(40):
        x = x - f(x) / df(x)
    return float(x)


def twist_matrices() -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (M0, M_plus, M_minus) so that M = M0 + M_plus + M_minus."""
    # See docstring derivation: M = [[2,0,2],[1,0,2],[0,1,0]].
    # δ=0 (multiplicity 2):
    #   X' += 2*X
    #   U' += 2*V
    M0 = np.array([[2, 0, 0], [0, 0, 2], [0, 0, 0]], dtype=np.int64)
    # δ=+1 (multiplicity 1):
    #   X' += V   (via -F_{m+2})
    #   U' += X
    #   V' += U
    M_plus = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=np.int64)
    # δ=-1 (multiplicity 1):
    #   X' += V   (via +F_{m+2})
    M_minus = np.array([[0, 0, 1], [0, 0, 0], [0, 0, 0]], dtype=np.int64)
    return M0, M_plus, M_minus


def M_twisted(u: complex, M0: np.ndarray, Mp: np.ndarray, Mm: np.ndarray) -> np.ndarray:
    return M0.astype(np.complex128) + u * Mp.astype(np.complex128) + (1.0 / u) * Mm.astype(np.complex128)


def spectral_radius(A: np.ndarray) -> float:
    vals = np.linalg.eigvals(A)
    return float(np.max(np.abs(vals)))


@dataclass(frozen=True)
class TwistRecord:
    n: int
    r: int
    u_re: float
    u_im: float
    rho: float


def scan_roots_of_unity(n_max: int) -> List[TwistRecord]:
    M0, Mp, Mm = twist_matrices()
    out: List[TwistRecord] = []
    for n in range(2, n_max + 1):
        for r in range(1, n):
            theta = (2.0 * math.pi * float(r)) / float(n)
            u = complex(math.cos(theta), math.sin(theta))
            A = M_twisted(u, M0=M0, Mp=Mp, Mm=Mm)
            rho = spectral_radius(A)
            out.append(TwistRecord(n=n, r=r, u_re=float(u.real), u_im=float(u.imag), rho=float(rho)))
    return out


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_tex_table(path: Path, rows: List[TwistRecord], r2: float) -> None:
    sqrt_r2 = math.sqrt(r2)
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_collision_a2_twist_difference_chain_scan.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{Twist scan for a 3-state difference-chain realization of the Fold $S_2$ collision kernel. "
        "We scan roots of unity $u=e^{2\\pi i r/n}$ (nontrivial $r$) and report the largest observed spectral "
        "radius $\\rho(M(u))$, together with the Ramanujan-style ratio $\\rho(M(u))/\\sqrt{r_2}$.}"
    )
    lines.append("\\label{tab:fold_collision_a2_twist_difference_chain_scan}")
    lines.append("\\begin{tabular}{r r r r}")
    lines.append("\\toprule")
    lines.append("$n$ & $r$ & $\\rho(M(u))$ & $\\rho(M(u))/\\sqrt{r_2}$\\\\")
    lines.append("\\midrule")
    for rec in rows:
        lines.append(f"{rec.n} & {rec.r} & {rec.rho:.12f} & {(rec.rho / sqrt_r2):.12f}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Scan roots-of-unity twists for the 3-state A2 difference-chain realization.")
    ap.add_argument("--n-max", type=int, default=40, help="Max root-of-unity order n to scan (>=2).")
    ap.add_argument("--top-k", type=int, default=20, help="Write top-k twists by spectral radius to TeX table.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "fold_collision_a2_twist_difference_chain_scan.json"),
        help="Output JSON path.",
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_fold_collision_a2_twist_difference_chain_scan.tex"),
        help="Output TeX table path.",
    )
    args = ap.parse_args()

    n_max = int(args.n_max)
    if n_max < 2:
        raise SystemExit("Require --n-max >= 2")
    top_k = int(args.top_k)
    if top_k < 1:
        raise SystemExit("Require --top-k >= 1")

    # Untwisted base matrix and r2.
    r2 = perron_root_r2()
    sqrt_r2 = math.sqrt(r2)

    # Scan.
    recs = scan_roots_of_unity(n_max=n_max)
    recs_sorted = sorted(recs, key=lambda x: x.rho, reverse=True)
    best = recs_sorted[0]

    # Also record a few canonical twists if present.
    def _find(n: int, r: int) -> TwistRecord | None:
        for rec in recs:
            if rec.n == n and rec.r == r:
                return rec
        return None

    examples: Dict[str, object] = {
        "u=-1 (n=2,r=1)": asdict(_find(2, 1)) if _find(2, 1) else None,
        "u=i (n=4,r=1)": asdict(_find(4, 1)) if _find(4, 1) else None,
        "u=exp(2pi i/3) (n=3,r=1)": asdict(_find(3, 1)) if _find(3, 1) else None,
    }

    payload: Dict[str, object] = {
        "meta": {
            "script": Path(__file__).name,
            "n_max": n_max,
            "top_k": top_k,
        },
        "base": {
            "r2": r2,
            "sqrt_r2": sqrt_r2,
            "M": [[2, 0, 2], [1, 0, 2], [0, 1, 0]],
            "M0": twist_matrices()[0].tolist(),
            "M_plus": twist_matrices()[1].tolist(),
            "M_minus": twist_matrices()[2].tolist(),
        },
        "best_over_scan": asdict(best),
        "examples": examples,
        "top_by_rho": [asdict(rec) for rec in recs_sorted[:top_k]],
    }

    write_json(Path(str(args.json_out)), payload)
    write_tex_table(Path(str(args.tex_out)), rows=recs_sorted[:top_k], r2=r2)

    print(f"[a2-twist-diff-chain] scanned n<= {n_max} (roots of unity).", flush=True)
    print(
        f"[a2-twist-diff-chain] base r2={r2:.12f} sqrt(r2)={sqrt_r2:.12f}",
        flush=True,
    )
    print(
        f"[a2-twist-diff-chain] best: n={best.n} r={best.r} rho={best.rho:.12f} ratio={best.rho/sqrt_r2:.12f}",
        flush=True,
    )
    print(f"[a2-twist-diff-chain] wrote {args.json_out}", flush=True)
    print(f"[a2-twist-diff-chain] wrote {args.tex_out}", flush=True)


if __name__ == "__main__":
    main()

