#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Activated small eigenvalue branch near u=1 for the real-input 40-state kernel, output potential only.

In `sections/appendix/sync_kernel/real_input/app__real-input-40-zeta-u.tex` we define:
  G(lambda,u) := lambda^8 * F(lambda^{-1},u),
so that for u>0 the Perron root is the largest positive real root of G=0.

At u=1 the polynomial loses its degree-8 term in F, and correspondingly G has a
simple root at lambda=0 (the "activated branch"). By the implicit function theorem,
there is a unique analytic branch lambda_act(u) with lambda_act(1)=0 and G=0.

This script computes the Taylor series of lambda_act(u) around u=1:
  lambda_act(u) = sum_{k>=1} a_k (u-1)^k,
to a user-chosen order and emits a reproducible TeX snippet.

Outputs:
  - artifacts/export/real_input_40_output_potential_activated_branch_series.json
  - sections/generated/eq_real_input_40_output_potential_activated_branch_series.tex
"""

from __future__ import annotations

import argparse
import json
import threading
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

import sympy as sp

from common_paths import export_dir, generated_dir


@dataclass(frozen=True)
class ActivatedBranchSeries:
    # coefficients a_k in lambda_act(u)=sum_{k=1}^K a_k (u-1)^k
    order: int
    coeffs: Dict[int, str]


class _Progress:
    def __init__(
        self, *, enabled: bool, every_seconds: float, prefix: str = "[act-branch-series]"
    ) -> None:
        self._enabled = enabled and every_seconds > 0
        self._every_seconds = float(every_seconds)
        self._prefix = prefix
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._t0 = 0.0

    def start(self, msg: str) -> None:
        if not self._enabled:
            return
        self._t0 = time.time()
        print(f"{self._prefix} {msg}", flush=True)

        def _run() -> None:
            while not self._stop.wait(self._every_seconds):
                dt = time.time() - self._t0
                print(f"{self._prefix} still running... elapsed={dt:.1f}s", flush=True)

        self._thread = threading.Thread(target=_run, name="progress", daemon=True)
        self._thread.start()

    def stop(self, msg: str) -> None:
        if not self._enabled:
            return
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=1.0)
        dt = time.time() - self._t0
        print(f"{self._prefix} {msg} elapsed={dt:.1f}s", flush=True)


def _build_G(lam: sp.Symbol, u: sp.Symbol) -> sp.Expr:
    # Must match `sections/appendix/sync_kernel/real_input/app__real-input-40-zeta-u.tex`.
    return (
        lam**8
        - lam**7
        - 6 * u * lam**6
        + 2 * u * lam**5
        + (9 * u**2 - u) * lam**4
        + (u - 3 * u**2) * lam**3
        - (u**3 + 2 * u**2) * lam**2
        + (4 * u**3 - 3 * u**2) * lam
        + (u**3 - u**4)
    )


def _series_lambda_act(order: int) -> Dict[int, sp.Expr]:
    if order < 1:
        raise ValueError("order must be >= 1")
    h = sp.Symbol("h")  # h = u-1
    u = 1 + h
    a = sp.symbols(f"a1:{order+1}")  # a1..a_order
    lam_series = sp.Integer(0)
    for k in range(1, order + 1):
        lam_series += a[k - 1] * h**k
    lam, uu = sp.Symbol("lam"), sp.Symbol("u")
    G = _build_G(lam, uu)
    expr = sp.expand(G.subs({uu: u, lam: lam_series}))
    expr_trunc = sp.series(expr, h, 0, order + 1).removeO()
    eqs = [sp.Eq(sp.expand(expr_trunc.coeff(h, k)), 0) for k in range(1, order + 1)]
    sol = sp.solve(eqs, list(a), dict=True)
    if not sol:
        raise RuntimeError("No series solution found.")
    sol0 = sol[0]
    coeffs: Dict[int, sp.Expr] = {}
    for k in range(1, order + 1):
        coeffs[k] = sp.simplify(sol0[a[k - 1]])
    return coeffs


def _write_tex(path: Path, res: ActivatedBranchSeries) -> None:
    h = sp.Symbol("h")
    expr = sp.Integer(0)
    for k in range(1, res.order + 1):
        ak = sp.sympify(res.coeffs[k])
        expr += ak * h**k
    rhs = sp.latex(expr, symbol_names={h: r"\left(u-1\right)"})

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_output_potential_activated_branch_series.py")
    lines.append("\\begin{remark}[激活分支在 $u=1$ 处的解析展开（可复现）]\\label{rem:real-input-40-activated-branch-series}")
    lines.append("在命题 \\ref{prop:real-input-40-activated-branch-linear} 的设定下，激活分支在 $u=1$ 的邻域解析，且其 Taylor 展开可由 $G(\\lambda,u)=0$ 逐阶匹配系数得到：")
    lines.append("$$")
    lines.append(
        f"\\lambda_\\mathrm{{act}}(u)={rhs}+O\\!\\bigl((u-1)^{{{res.order+1}}}\\bigr)."
    )
    lines.append("$$")
    lines.append("特别地，二次项系数为 $0$。该展开在数值上可用于 $u\\approx1$ 时的分支剥离与病态消元。")
    lines.append("\\end{remark}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Series for activated eigenvalue branch near u=1 (real input 40-state, output potential)."
    )
    parser.add_argument(
        "--order",
        type=int,
        default=6,
        help="Taylor order K for lambda_act(u)=sum_{k=1}^K a_k (u-1)^k.",
    )
    parser.add_argument(
        "--progress-seconds",
        type=float,
        default=20.0,
        help="Print a heartbeat progress line every N seconds (0 disables).",
    )
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(
            export_dir() / "real_input_40_output_potential_activated_branch_series.json"
        ),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(
            generated_dir()
            / "eq_real_input_40_output_potential_activated_branch_series.tex"
        ),
    )
    args = parser.parse_args()

    prog = _Progress(enabled=(args.progress_seconds > 0), every_seconds=args.progress_seconds)
    prog.start(f"computing series up to order={args.order}")
    try:
        coeffs = _series_lambda_act(int(args.order))
        out = ActivatedBranchSeries(
            order=int(args.order),
            coeffs={k: sp.sstr(v) for k, v in coeffs.items()},
        )
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(
            json.dumps(asdict(out), indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        _write_tex(Path(args.tex_out), out)
    finally:
        prog.stop("done")


if __name__ == "__main__":
    main()

