#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fiber reconstruction-graph invariants at the minimal window m=6.

For each stable type x in X_6, we enumerate the fiber size d_6(x)=|Fold_6^{-1}(x)|
exactly (by brute enumeration of Ω_6 via fold_map_packed). At m=6 the component-length
multiset (ℓ_i) of the candidate-site induced path graph Γ_x is uniquely determined
by d_6(x), since k_+=ceil(6/2)=3 and the only possible independent-set counts are
{1,2,3,4,5} with unique (ℓ_i)-types.

We then compute the reconstruction-graph invariants predicted by
  𝓕_x ≅ ∏_i Γ_{ℓ_i}
(Cartesian product of Fibonacci cubes), using the closed forms in the paper:
  - |V(𝓕_x)| = d_6(x),
  - diam(𝓕_x) = Σ_i ℓ_i,
  - dim_□(𝓕_x) = Σ_i ceil(ℓ_i/2),
  - |E(𝓕_x)| from the Cartesian-product edge formula.

This script intentionally does not reconstruct the adjacency of 𝓕_x in microstate
space. The object 𝓕_x is defined (Definition 03a-c) on the independent-set
parameterization and is audited here via exact fiber sizes and derived invariants.

Outputs:
  - artifacts/export/fold_fiber_reconstruction_window6.json
  - sections/generated/tab_fold_fiber_reconstruction_invariants_m6.tex

All output is English-only by repository convention.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from math import ceil
from pathlib import Path
from typing import Dict, List

from common_fold_map_cache import fold_map_packed
from common_paths import export_dir, generated_dir


def _bits_str(w: int, m: int) -> str:
    """m-bit string, MSB-first."""
    return "".join("1" if ((w >> (m - 1 - i)) & 1) else "0" for i in range(m))


def _infer_ell_from_vertex_count(v: int) -> List[int]:
    """For m=6, infer component lengths (ℓ_i) from |V(𝓕_x)| (fiber size)."""
    if v == 1:
        return []
    if v == 2:
        return [1]
    if v == 3:
        return [2]
    if v == 4:
        return [1, 1]
    if v == 5:
        return [3]
    return [-1]


def _fib_upto(n: int) -> List[int]:
    """F_0..F_n with F_0=0,F_1=1."""
    n = int(n)
    if n < 0:
        return []
    f = [0, 1]
    while len(f) <= n:
        f.append(f[-1] + f[-2])
    return f


def _fibcube_vertices(n: int) -> int:
    """|V(Γ_n)| = F_{n+2} with F_0=0,F_1=1."""
    n = int(n)
    fib = _fib_upto(n + 2)
    return int(fib[n + 2])


def _fibcube_edges(n: int) -> int:
    """|E(Γ_n)| = C(n,1) for the window-6 range (n<=3)."""
    n = int(n)
    if n < 0:
        return 0
    if n == 0:
        return 0
    if n == 1:
        return 1
    if n == 2:
        return 2
    if n == 3:
        return 5
    raise ValueError("This window-6 audit only needs Γ_n for n<=3.")


def _cartesian_product_edges(ell: List[int]) -> int:
    """Edge count of ∏_i Γ_{ℓ_i} using the Cartesian-product edge formula."""
    if not ell:
        return 0
    Vs = [_fibcube_vertices(n) for n in ell]
    Es = [_fibcube_edges(n) for n in ell]
    total = 0
    for i in range(len(ell)):
        prod_other = 1
        for j in range(len(ell)):
            if j != i:
                prod_other *= Vs[j]
        total += Es[i] * prod_other
    return int(total)


@dataclass(frozen=True)
class Row:
    x_bits: str
    fiber_size: int
    ell: List[int]
    v: int
    e: int
    diam: int
    dim_sq: int

    def to_dict(self) -> Dict[str, object]:
        return {
            "x_bits": self.x_bits,
            "fiber_size": int(self.fiber_size),
            "ell": [int(a) for a in self.ell],
            "graph": {"v": int(self.v), "e": int(self.e), "diam": int(self.diam), "dim_sq": int(self.dim_sq)},
        }


def write_table(rows: List[Row], out_path: Path) -> None:
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_fold_fiber_reconstruction_window6.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{5pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.08}")
    lines.append(
        (
            "\\caption{Window-$6$ 纤维重构图 $\\mathcal F_x$ 的有限窗审计："
            "对每个稳定类型 $x\\in X_6$，列出纤维大小 $d_6(x)=|\\Fold_6^{-1}(x)|$，"
            "并在单次开关边关系（定义~\\ref{def:pom-fiber-reconstruction-graph}）下计算"
            "$|V|,|E|,\\mathrm{diam},\\dim_{\\square}$ 等不变量。}"
        )
    )
    lines.append("\\label{tab:fold_fiber_reconstruction_invariants_m6}")
    lines.append("\\begin{tabular}{l r l r r r r}")
    lines.append("\\toprule")
    lines.append("$x$ & $d_6(x)$ & $(\\ell_i)$ & $|V|$ & $|E|$ & $\\mathrm{diam}$ & $\\dim_{\\square}$\\\\")
    lines.append("\\midrule")
    for r in rows:
        ell_tex = "(" + ",".join(str(a) for a in r.ell) + ")" if r.ell else "()"
        lines.append(
            f"\\texttt{{{r.x_bits}}} & {r.fiber_size} & ${ell_tex}$ & {r.v} & {r.e} & {r.diam} & {r.dim_sq}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    m = 6
    fold_map = fold_map_packed(m)

    # Build fibers: x_packed -> list of microstates (packed int in [0,2^m)).
    fibers: Dict[int, List[int]] = {}
    for w in range(1 << m):
        x = int(fold_map[w])
        fibers.setdefault(x, []).append(int(w))

    rows: List[Row] = []
    for x in sorted(fibers.keys()):
        fiber = fibers[x]
        v = len(fiber)

        ell = _infer_ell_from_vertex_count(v)
        if -1 in ell:
            raise AssertionError(f"Unexpected fiber size at m=6: x={x} |F_x|={v}")

        # Predicted invariants under 𝓕_x ≅ ∏ Γ_{ℓ_i}.
        v_pred = 1
        for n in ell:
            v_pred *= _fibcube_vertices(n)
        if v_pred != v:
            raise AssertionError(f"Vertex-count mismatch at m=6: ell={ell} gives {v_pred}, but fiber has {v}")

        e = _cartesian_product_edges(ell)
        diam = sum(ell)
        dim_sq = sum(int(ceil(n / 2)) for n in ell)

        rows.append(
            Row(
                x_bits=_bits_str(x, m),
                fiber_size=len(fiber),
                ell=ell,
                v=v,
                e=int(e),
                diam=int(diam),
                dim_sq=int(dim_sq),
            )
        )

    payload: Dict[str, object] = {
        "params": {
            "m": m,
            "definition": {
                "fiber": "Fold_m^{-1}(x)",
                "ell": "component-length multiset (ℓ_i) of Γ_x = P_{k_+}[Adm(x)] inferred from d_6(x) at m=6",
            },
        },
        "rows": [r.to_dict() for r in rows],
    }
    export_path = export_dir() / "fold_fiber_reconstruction_window6.json"
    export_path.parent.mkdir(parents=True, exist_ok=True)
    export_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    tex_path = generated_dir() / "tab_fold_fiber_reconstruction_invariants_m6.tex"
    write_table(rows, tex_path)


if __name__ == "__main__":
    main()

