#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""End-to-end Lucas -> primitive pipeline (real-input-40) with auditable bounds.

This script implements the *minimal-data* pipeline highlighted in:
  - prop:time-space-commuting-diagram (trace -> Möbius/Witt -> Euler/primitive)
  - thm:real-input-40-prime-artin-splitting (mod-4 selection law)
  - cor:real-input-40-logM-fast-prime (3-point evaluation for log Mfrak difference)

Inputs:
  - Lucas trace samples L_n = Tr(F^n) for F=[[1,1],[1,0]], generated by recurrence.

Outputs:
  - primitive counts pi_n = p_n(F)  (Fibonacci base kernel)
  - primitive counts r_n  = p_n(F⊗F) (input skeleton B)
  - primitive counts p_n(M) (real-input-40 kernel) via mod-4 selection law
  - log(Mfrak_M) - log(Mfrak_in) using the 3-point P_F evaluations
  - an explicit truncation bound and the smallest N achieving a target eps

Audits:
  (i) p_n(M) from mod-4 selection equals Möbius on trace closed form
  (ii) prime-length product law: p_p(M) = L_p * pi_p for odd primes p
  (iii) 3-point formula equals series sum_{n>=1} (p_n(M)-r_n)/lambda^n (within tail bd)

All output is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import mpmath as mp

from common_paths import export_dir, generated_dir
from common_phi_fold import Progress


# -------------------------
# Number theory utilities
# -------------------------


def mobius_sieve(n: int) -> List[int]:
    """Return mu[0..n] with mu[0]=0, mu[1]=1 (linear sieve)."""
    if n < 0:
        raise ValueError("n must be >= 0")
    mu = [0] * (n + 1)
    if n >= 1:
        mu[1] = 1
    primes: List[int] = []
    is_comp = [False] * (n + 1)
    for i in range(2, n + 1):
        if not is_comp[i]:
            primes.append(i)
            mu[i] = -1
        for p in primes:
            ip = i * p
            if ip > n:
                break
            is_comp[ip] = True
            if i % p == 0:
                mu[ip] = 0
                break
            mu[ip] = -mu[i]
    return mu


def primitive_from_traces(traces: List[int], mu: List[int], prog: Progress, label: str) -> List[int]:
    """Compute primitive counts p_n from traces a_n via Möbius inversion.

    Convention:
      traces[k-1] = a_k = Tr(A^k)
      p_n = (1/n) * sum_{d|n} mu(d) * a_{n/d}
    """
    n_max = len(traces)
    s = [0] * (n_max + 1)  # s[n] = sum_{d|n} mu(d) * a_{n/d}
    for d in range(1, n_max + 1):
        mu_d = mu[d]
        if mu_d == 0:
            continue
        # n = d*m, contribution mu(d) * a_m
        for m in range(1, n_max // d + 1):
            s[d * m] += mu_d * traces[m - 1]
        prog.tick(f"mobius-sum {label} d={d}/{n_max}")

    out: List[int] = []
    for n in range(1, n_max + 1):
        if s[n] % n != 0:
            raise ValueError(f"non-integer primitive count for {label} n={n}: {s[n]}/{n}")
        out.append(s[n] // n)
    return out


# -------------------------
# Lucas / Fibonacci kernels
# -------------------------


def lucas_traces(n_max: int) -> List[int]:
    """Lucas traces L_n = Tr(F^n) for F=[[1,1],[1,0]].

    Uses:
      L_1=1, L_2=3, L_n = L_{n-1} + L_{n-2} for n>=3.
    """
    if n_max <= 0:
        return []
    if n_max == 1:
        return [1]
    L = [1, 3]
    while len(L) < n_max:
        L.append(L[-1] + L[-2])
    return L[:n_max]


def traces_tensor_square(traces: List[int]) -> List[int]:
    """Tr((F⊗F)^n) = Tr(F^n)^2."""
    return [t * t for t in traces]


def traces_real_input_40_from_lucas(traces_L: List[int]) -> List[int]:
    """Closed-form traces for real-input-40 kernel M in terms of Lucas traces L_n.

    From `sections/appendix/sync_kernel/real_input/app__abel-mertens-universal.tex`:
      a_n(M) = L_n^2 + (-1)^n (L_n + 1) + 2.
    """
    out: List[int] = []
    for n, Ln in enumerate(traces_L, start=1):
        sgn = -1 if (n % 2 == 1) else 1
        out.append(Ln * Ln + sgn * (Ln + 1) + 2)
    return out


# -------------------------
# P_F evaluation + tail bounds
# -------------------------


def tail_bound_geom(q: mp.mpf, N: int) -> mp.mpf:
    """Bound sum_{n>N} q^n/n for 0<q<1: <= q^{N+1}/((N+1)(1-q))."""
    if N < 0:
        raise ValueError("N must be >= 0")
    if not (mp.mpf(0) < q < mp.mpf(1)):
        raise ValueError("q must be in (0,1)")
    return (q ** (N + 1)) / (mp.mpf(N + 1) * (1 - q))


def tail_bound_PF_at_abs_z(abs_z: mp.mpf, N: int, *, phi: mp.mpf) -> mp.mpf:
    """Conservative tail bound for P_F(z)=sum_{n>=1} pi_n z^n using pi_n <= L_n/n.

    For Fibonacci F:
      a_n = L_n <= phi^n + 1, and exact-period points satisfy n*pi_n <= a_n,
    hence
      pi_n <= (phi^n + 1)/n.

    Therefore for |z|<1/phi:
      sum_{n>N} pi_n |z|^n <= sum_{n>N} (phi|z|)^n / n + sum_{n>N} |z|^n / n.
    """
    q1 = phi * abs_z
    q2 = abs_z
    if not (mp.mpf(0) < q1 < mp.mpf(1)):
        raise ValueError("abs_z must be < 1/phi for this tail bound")
    # q2 is automatically < q1 < 1, but keep the formula explicit.
    return tail_bound_geom(q1, N) + tail_bound_geom(q2, N)


def PF_series(pi: List[int], z: mp.mpf, N: int) -> mp.mpf:
    """Partial sum sum_{n=1..N} pi_n z^n."""
    s = mp.mpf("0")
    zz = mp.mpf("1")
    for n in range(1, N + 1):
        zz *= z
        s += mp.mpf(pi[n - 1]) * zz
    return s


def logM_diff_three_point(pi: List[int], N: int, *, lam: mp.mpf) -> mp.mpf:
    """Compute log Mfrak_M - log Mfrak_in via the 3-point formula."""
    inv_lam = mp.mpf(1) / lam
    inv_lam2 = inv_lam * inv_lam
    PF_m = PF_series(pi, -inv_lam, N)
    PF_p2 = PF_series(pi, +inv_lam2, N)
    PF_m2 = PF_series(pi, -inv_lam2, N)
    return inv_lam + inv_lam2 + PF_m + (PF_p2 - PF_m2) / mp.mpf(2)


def required_N_for_eps(eps: mp.mpf, *, lam: mp.mpf, phi: mp.mpf, N_cap: int = 20000) -> int:
    """Smallest N such that the 3-point formula truncation error <= eps."""
    if not (eps > 0):
        raise ValueError("eps must be > 0")
    inv_lam = mp.mpf(1) / lam
    inv_lam2 = inv_lam * inv_lam
    for N in range(0, N_cap + 1):
        bd1 = tail_bound_PF_at_abs_z(abs_z=abs(inv_lam), N=N, phi=phi)
        bd2 = tail_bound_PF_at_abs_z(abs_z=abs(inv_lam2), N=N, phi=phi)
        if bd1 + bd2 <= eps:
            return N
    raise ValueError(f"required_N_for_eps exceeded N_cap={N_cap}")


# -------------------------
# Outputs
# -------------------------


@dataclass(frozen=True)
class Payload:
    n_max: int
    eps_target: str
    N_eps: int
    dps: int
    lambda_value: str
    phi_value: str
    L_10: List[int]
    pi_10: List[int]
    r_10: List[int]
    pM_10: List[int]
    audit_mod4_equals_mobius_trace: bool
    audit_prime_product_law: bool
    audit_three_point_vs_series: bool
    logM_diff_three_point: str
    logM_diff_three_point_tail_bd: str
    logM_diff_series_partial: str
    logM_diff_series_tail_bd: str


def main() -> None:
    parser = argparse.ArgumentParser(description="Lucas -> primitive pipeline for real-input-40 (auditable).")
    parser.add_argument("--n-max", type=int, default=200, help="Max n for integer primitive sequences.")
    parser.add_argument("--eps", type=str, default="1e-12", help="Target absolute error for logM difference.")
    parser.add_argument("--dps", type=int, default=120, help="mpmath precision (decimal digits).")
    parser.add_argument("--no-output", action="store_true", help="Skip writing JSON/TeX outputs.")
    parser.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_lucas_pipeline.json"),
    )
    parser.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "eq_real_input_40_lucas_pipeline.tex"),
    )
    args = parser.parse_args()

    n_max = int(args.n_max)
    if n_max < 2:
        raise SystemExit("--n-max must be >= 2")

    mp.mp.dps = int(args.dps)
    eps = mp.mpf(args.eps)

    prog = Progress("real_input_40_lucas_pipeline", every_seconds=20.0)

    phi = (mp.mpf(1) + mp.sqrt(5)) / mp.mpf(2)
    lam = phi * phi

    # Minimal data requirement for eps on the 3-point formula.
    N_eps = required_N_for_eps(eps, lam=lam, phi=phi)

    # Integer sequences up to n_max (may exceed N_eps; both are useful).
    L = lucas_traces(n_max)
    mu = mobius_sieve(n_max)

    # Primitive for base F (pi_n) and input skeleton B=F⊗F (r_n).
    pi = primitive_from_traces(L, mu, prog, label="F (Lucas traces)")
    r = primitive_from_traces(traces_tensor_square(L), mu, prog, label="B=F⊗F (Lucas^2 traces)")

    # Primitive for M via mod-4 selection law (Artin splitting).
    pM: List[int] = [0] * n_max
    pM[0] = r[0]  # p_1(M)=r_1
    pM[1] = r[1] + pi[1] + pi[0] + 1  # p_2(M)=r_2+pi_2+pi_1+1
    for n in range(3, n_max + 1):
        corr = (-1 if (n % 2 == 1) else 1) * pi[n - 1]
        if n % 4 == 2:
            corr += pi[n // 2 - 1]
        pM[n - 1] = r[n - 1] + corr

    # Audit (i): compare with Möbius on the closed-form trace a_n(M).
    aM = traces_real_input_40_from_lucas(L)
    pM_from_trace = primitive_from_traces(aM, mu, prog, label="M (closed trace from Lucas)")
    audit_mod4_equals_mobius_trace = (pM_from_trace == pM)

    # Audit (ii): prime-length product law p_p(M) = L_p * pi_p for odd primes p.
    # (Theorem statement: p_p(M)=(L_p(L_p-1))/p and pi_p=(L_p-1)/p.)
    def is_prime(k: int) -> bool:
        if k < 2:
            return False
        if k % 2 == 0:
            return k == 2
        x = 3
        while x * x <= k:
            if k % x == 0:
                return False
            x += 2
        return True

    ok_prime_product = True
    for p in range(3, n_max + 1):
        if not is_prime(p):
            continue
        if pM[p - 1] != L[p - 1] * pi[p - 1]:
            ok_prime_product = False
            break
    audit_prime_product_law = ok_prime_product

    # Audit (iii): 3-point formula vs series sum_{n>=1} (p_n(M)-r_n)/lambda^n.
    # Use N=N_eps for both, and certify with tail bounds.
    N = N_eps
    pi_N = pi[:N]

    logdiff_3pt = logM_diff_three_point(pi_N, N, lam=lam)
    bd_3pt = tail_bound_PF_at_abs_z(abs_z=abs(mp.mpf(1) / lam), N=N, phi=phi) + tail_bound_PF_at_abs_z(
        abs_z=abs(mp.mpf(1) / (lam * lam)), N=N, phi=phi
    )

    # Series using q_n := p_n(M) - r_n.
    # For n>=3, q_n = (-1)^n pi_n + 1_{n≡2 mod4} pi_{n/2}. Use the actual (pM-r) integers for safety.
    q = [(pM[i] - r[i]) for i in range(n_max)]
    # Partial sum up to N (needs q_n for n<=N; ensure n_max>=N).
    if N > n_max:
        raise SystemExit("n-max too small for eps-target; increase --n-max")
    logdiff_series = mp.mpf("0")
    inv_lam = mp.mpf(1) / lam
    zz = mp.mpf("1")
    for n in range(1, N + 1):
        zz *= inv_lam
        logdiff_series += mp.mpf(q[n - 1]) * zz

    # Tail bound for the q_n-series: |q_n| <= pi_n + pi_{n/2} <= (L_n/n) + (L_{n/2}/(n/2)).
    # We use a coarse envelope: |q_n| <= 2 * (L_n/n) <= 2*(phi^n+1)/n for n>=1,
    # hence tail <= 2*( tail(q1,N)+tail(q2,N) ) with q1=phi/lam=1/phi, q2=1/lam=1/phi^2.
    abs_z1 = abs(inv_lam)
    bd_series = mp.mpf(2) * tail_bound_PF_at_abs_z(abs_z=abs_z1, N=N, phi=phi)

    audit_three_point_vs_series = (abs(logdiff_3pt - logdiff_series) <= (bd_3pt + bd_series))

    payload = Payload(
        n_max=n_max,
        eps_target=str(args.eps),
        N_eps=N_eps,
        dps=int(args.dps),
        lambda_value=mp.nstr(lam, 40),
        phi_value=mp.nstr(phi, 40),
        L_10=L[:10],
        pi_10=pi[:10],
        r_10=r[:10],
        pM_10=pM[:10],
        audit_mod4_equals_mobius_trace=bool(audit_mod4_equals_mobius_trace),
        audit_prime_product_law=bool(audit_prime_product_law),
        audit_three_point_vs_series=bool(audit_three_point_vs_series),
        logM_diff_three_point=mp.nstr(logdiff_3pt, 40),
        logM_diff_three_point_tail_bd=mp.nstr(bd_3pt, 6),
        logM_diff_series_partial=mp.nstr(logdiff_series, 40),
        logM_diff_series_tail_bd=mp.nstr(bd_series, 6),
    )

    if args.no_output:
        return

    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(asdict(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[real-input-40-lucas] wrote {jout}", flush=True)

    # TeX snippet (compact, audit-focused)
    tout = Path(args.tex_out)
    tout.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_real_input_40_lucas_pipeline.py")
    lines.append(r"\begin{equation*}")
    lines.append(r"\boxed{\ (p_n(M))_{n=1}^{10}=" + "(" + ", ".join(str(x) for x in pM[:10]) + r")\ }")
    lines.append(r"\end{equation*}")
    lines.append(r"\begin{equation*}")
    lines.append(r"\boxed{\ (r_n)_{n=1}^{10}=" + "(" + ", ".join(str(x) for x in r[:10]) + r")\ }")
    lines.append(r"\end{equation*}")
    lines.append(r"\begin{equation*}")
    lines.append(r"\boxed{\ (\pi_n)_{n=1}^{10}=" + "(" + ", ".join(str(x) for x in pi[:10]) + r")\ }")
    lines.append(r"\end{equation*}")
    lines.append("")
    lines.append(r"\begin{equation*}")
    lines.append(
        r"\boxed{\ \log\mathfrak{M}_M-\log\mathfrak{M}_{\mathrm{in}}\approx "
        + payload.logM_diff_three_point
        + r"\ }"
    )
    lines.append(r"\end{equation*}")
    lines.append("")
    lines.append(r"\noindent\textbf{Audits.} ")
    lines.append(
        r"mod-4 splitting vs Möbius(trace): "
        + ("OK" if payload.audit_mod4_equals_mobius_trace else "FAIL")
        + r".\quad prime product law: "
        + ("OK" if payload.audit_prime_product_law else "FAIL")
        + r".\quad 3-point vs series (with tail bd): "
        + ("OK" if payload.audit_three_point_vs_series else "FAIL")
        + r".\quad "
        + r"$N_\varepsilon="
        + str(payload.N_eps)
        + r",\ \mathrm{tail}(3\mathrm{pt})\le "
        + payload.logM_diff_three_point_tail_bd
        + r"$."
    )
    lines.append("")
    tout.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[real-input-40-lucas] wrote {tout}", flush=True)

    if not payload.audit_mod4_equals_mobius_trace:
        raise SystemExit("Audit failed: mod-4 p_n(M) != Möbius on trace formula.")
    if not payload.audit_prime_product_law:
        raise SystemExit("Audit failed: prime product law p_p(M)=L_p*pi_p not satisfied.")
    if not payload.audit_three_point_vs_series:
        raise SystemExit("Audit failed: 3-point constant diff not consistent with series within bounds.")


if __name__ == "__main__":
    main()

