#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract the ((m,2)) slow-mode fingerprint R_{m,2} for the real-input 40-state kernel.

We read the audited 2D arity/negative-carry twist scan output:
  artifacts/export/sync_kernel_real_input_40_arity_2d.json
from scripts/exp_sync_kernel_real_input_40_arity_2d.py,
and compute the two-channel fingerprint components:

  rho_in(m,2) := max_{1<=j<=m-1} rho(M(omega_m^j, 1))
  rho_bd(m,2) := rho(M(1, -1))
  rho_cross(m,2) := max_{1<=j<=m-1} rho(M(omega_m^j, -1))
  rho_{m,2} := max(rho_in, rho_bd, rho_cross)

We also report the channel anisotropy log-ratio:
  A_m := log(rho_in(m,2) / rho_bd(m,2))

We also report a spectral-tax rate and a workload proxy:
  Delta_m := -log(rho_{m,2}/lambda)
  W(m) := log(2m)/Delta_m, using |G|=2m classes for ((m,2)).

Outputs:
  - artifacts/export/real_input_40_rho_m2_fingerprint.json
  - sections/generated/tab_real_input_40_rho_m2_fingerprint.tex

All stdout is English-only by repository convention.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from common_paths import export_dir, generated_dir


def _phi() -> float:
    return (1.0 + math.sqrt(5.0)) / 2.0


def _lambda_phi2() -> float:
    p = _phi()
    return p * p


@dataclass(frozen=True)
class Row:
    m: int
    rho_in_over_lambda: float
    rho_bd_over_lambda: float
    rho_cross_over_lambda: float
    rho_m2_over_lambda: float
    anisotropy_A_m: float
    dominant: str
    competition_holds: bool
    delta_minus_log_rho_over_lambda: float
    workload_W: float


def _fmt(x: float) -> str:
    if not math.isfinite(x):
        return "\\infty"
    return f"{x:.12f}"


def _parse_int_list_csv(s: str) -> Optional[List[int]]:
    s = str(s).strip()
    if not s:
        return None
    out: List[int] = []
    for tok in s.split(","):
        t = tok.strip()
        if not t:
            continue
        out.append(int(t))
    # unique, stable
    seen = set()
    uniq: List[int] = []
    for x in out:
        if x in seen:
            continue
        seen.add(x)
        uniq.append(x)
    return uniq


def _write_tex(path: Path, rows: Sequence[Row]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_real_input_40_rho_m2_fingerprint.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.15}")
    lines.append(
        "\\caption{$((m,2))$ slow-mode fingerprint for the real-input 40-state kernel. "
        "We report $\\rho^{\\mathrm{in}}_{m,2}/\\lambda$ and $\\rho^{\\mathrm{bd}}_{m,2}/\\lambda$, "
        "the cross-twist maximum $\\max_j\\rho(M(\\omega_m^j,-1))/\\lambda$, "
        "and $\\rho_{m,2}/\\lambda$. We also include the anisotropy index "
        "$A_m:=\\log(\\rho^{\\mathrm{in}}_{m,2}/\\rho^{\\mathrm{bd}}_{m,2})$, "
        "and "
        "$\\Delta_m=-\\log(\\rho_{m,2}/\\lambda)$ and the workload proxy "
        "$W(m)=\\log(2m)/\\Delta_m$ (since $|G|=2m$ for $((m,2))$).}"
    )
    lines.append("\\label{tab:real-input-40-rho-m2-fingerprint}")
    lines.append("\\begin{tabular}{r r r r r r l c r r}")
    lines.append("\\toprule")
    lines.append(
        "$m$ & $\\rho^{\\mathrm{in}}/\\lambda$ & $\\rho^{\\mathrm{bd}}/\\lambda$ & $\\rho^{\\times}/\\lambda$"
        " & $\\rho_{m,2}/\\lambda$ & $A_m$ & dom & comp & $\\Delta_m$ & $W(m)$\\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        comp = "Y" if r.competition_holds else "N"
        lines.append(
            f"{r.m} & {_fmt(r.rho_in_over_lambda)} & {_fmt(r.rho_bd_over_lambda)}"
            f" & {_fmt(r.rho_cross_over_lambda)} & {_fmt(r.rho_m2_over_lambda)}"
            f" & {_fmt(r.anisotropy_A_m)} & {r.dominant} & {comp} & {_fmt(r.delta_minus_log_rho_over_lambda)}"
            f" & {_fmt(r.workload_W)}\\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Extract ((m,2)) fingerprint R_{m,2} from arity-2d JSON.")
    ap.add_argument(
        "--in-json",
        type=str,
        default=str(export_dir() / "sync_kernel_real_input_40_arity_2d.json"),
        help="Input JSON from exp_sync_kernel_real_input_40_arity_2d.py",
    )
    ap.add_argument(
        "--m-list",
        type=str,
        default="",
        help="Optional comma-separated m values to include (subset of those present in the JSON).",
    )
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "real_input_40_rho_m2_fingerprint.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_real_input_40_rho_m2_fingerprint.tex"),
    )
    ap.add_argument(
        "--eps",
        type=float,
        default=1e-12,
        help="Tolerance for dominance/competition comparisons.",
    )
    args = ap.parse_args()

    lam = _lambda_phi2()
    want_ms = _parse_int_list_csv(args.m_list)

    in_path = Path(args.in_json)
    payload = json.loads(in_path.read_text(encoding="utf-8"))
    pair_rho: Dict[str, Dict[str, float]] = payload.get("pair_rho", {})
    if not isinstance(pair_rho, dict) or not pair_rho:
        raise SystemExit(f"[rho-m2] missing/empty pair_rho in {in_path}")

    rows: List[Row] = []
    used_pairs: List[str] = []

    for key_pair, rho_vals in pair_rho.items():
        if not isinstance(key_pair, str) or "x" not in key_pair:
            continue
        left, right = key_pair.split("x", 1)
        try:
            m1 = int(left)
            m2 = int(right)
        except ValueError:
            continue
        if m2 != 2:
            continue
        m = m1
        if want_ms is not None and m not in want_ms:
            continue
        if not isinstance(rho_vals, dict):
            continue

        def get(j1: int, j2: int) -> float:
            v = rho_vals.get(f"{j1},{j2}", None)
            if v is None:
                raise KeyError(f"missing key {j1},{j2} in pair_rho[{key_pair}]")
            return float(v)

        rho_in = max(get(j, 0) for j in range(1, m))
        rho_bd = get(0, 1)
        rho_cross = max(get(j, 1) for j in range(1, m))
        rho_m2 = max(rho_in, rho_bd, rho_cross)

        A_m = float("inf")
        if rho_in > 0.0 and rho_bd > 0.0:
            A_m = math.log(rho_in / rho_bd)

        rin = rho_in / lam
        rbd = rho_bd / lam
        rcx = rho_cross / lam
        rm2 = rho_m2 / lam

        dominant = "in"
        if abs(rho_m2 - rho_bd) <= args.eps:
            dominant = "bd"
        if abs(rho_m2 - rho_cross) <= args.eps and rho_cross >= max(rho_in, rho_bd) - args.eps:
            dominant = "x"

        competition_holds = rho_cross <= max(rho_in, rho_bd) + args.eps
        delta = float("inf") if not (rm2 > 0.0 and rm2 < 1.0) else (-math.log(rm2))
        logG = math.log(float(2 * m))
        W = float("inf") if not (delta > 0.0 and math.isfinite(delta)) else (logG / delta)

        rows.append(
            Row(
                m=m,
                rho_in_over_lambda=rin,
                rho_bd_over_lambda=rbd,
                rho_cross_over_lambda=rcx,
                rho_m2_over_lambda=rm2,
                anisotropy_A_m=A_m,
                dominant=dominant,
                competition_holds=bool(competition_holds),
                delta_minus_log_rho_over_lambda=delta,
                workload_W=W,
            )
        )
        used_pairs.append(key_pair)

    if not rows:
        raise SystemExit(f"[rho-m2] no (m,2) pairs found in {in_path}")

    rows.sort(key=lambda r: r.m)

    out_payload: Dict[str, Any] = {
        "meta": {"script": Path(__file__).name, "in_json": str(in_path), "lambda": lam, "pairs_used": used_pairs},
        "rows": [asdict(r) for r in rows],
    }
    jout = Path(args.json_out)
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps(out_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"[rho-m2] wrote {jout}", flush=True)

    tout = Path(args.tex_out)
    _write_tex(tout, rows)
    print(f"[rho-m2] wrote {tout}", flush=True)


if __name__ == "__main__":
    main()

