#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Root-length split audit at the Sp(6)-isotropy scan candidates.

All output is English-only by repository convention.

Given the isotropy scan JSON (Sigma = Hessian of pressure at theta),
we compute average root lengths under the metric Sigma^{-1} for:
  - short roots (6)
  - long roots (12)
  - A2(+) long roots (same-sign)
  - A2(-) long roots (opposite-sign)

We report:
  R_ls := sqrt(mean_long / mean_short)   (expected ~ sqrt(2) at isotropy),
  R_pm := sqrt(mean_A2plus / mean_A2minus) (expected ~ 1).

Outputs (default):
  - artifacts/export/sp6_isotropy_root_split_ratio.json
  - sections/generated/tab_sp6_isotropy_root_split_ratio.tex
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import List, Sequence, Tuple

import numpy as np

from common_paths import export_dir, generated_dir

RootVec = Tuple[int, int, int]


def _roots_B3() -> Tuple[List[RootVec], List[RootVec]]:
    short: List[RootVec] = [
        (+1, 0, 0),
        (-1, 0, 0),
        (0, +1, 0),
        (0, -1, 0),
        (0, 0, +1),
        (0, 0, -1),
    ]
    long: List[RootVec] = [
        (+1, +1, 0),
        (+1, -1, 0),
        (-1, +1, 0),
        (-1, -1, 0),
        (+1, 0, +1),
        (+1, 0, -1),
        (-1, 0, +1),
        (-1, 0, -1),
        (0, +1, +1),
        (0, +1, -1),
        (0, -1, +1),
        (0, -1, -1),
    ]
    return short, long


def _split_A2(long_roots: Sequence[RootVec]) -> Tuple[List[RootVec], List[RootVec]]:
    plus: List[RootVec] = []
    minus: List[RootVec] = []
    for rv in long_roots:
        nz = [x for x in rv if x != 0]
        if len(nz) != 2:
            raise AssertionError(f"Unexpected long root shape: {rv}")
        if nz[0] == nz[1]:
            plus.append(rv)
        else:
            minus.append(rv)
    return plus, minus


def _length_sq(rv: RootVec, ginv: np.ndarray) -> float:
    v = np.array(rv, dtype=float).reshape((3, 1))
    return float((v.T @ ginv @ v)[0, 0])


def _mean(values: Sequence[float]) -> float:
    if not values:
        raise AssertionError("Empty sequence.")
    return float(sum(values) / len(values))


def _tex_table(out_path: Path, rows: List[dict]) -> None:
    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_sp6_isotropy_root_split_ratio.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        "\\caption{Root-length split ratios computed from $\\Sigma^{-1}$ at the top Sp(6)-isotropy scan candidates. "
        "$R_{ls}$ is the short/long ratio and $R_{pm}$ compares the two $A_2$ long-root subsets.}"
    )
    lines.append("\\label{tab:sp6_isotropy_root_split_ratio}")
    lines.append("\\begin{tabular}{r r r r r r}")
    lines.append("\\toprule")
    lines.append("$u$ & $v$ & $w$ & $R_{ls}$ & $R_{pm}$ & $\\log(\\lambda_{\\max}/\\lambda_{\\min})$\\\\")
    lines.append("\\midrule")
    for r in rows:
        u = float(r["weights"]["u"])
        v = float(r["weights"]["v"])
        w = float(r["weights"]["w"])
        rls = float(r["ratio_long_short"])
        rpm = float(r["ratio_A2plus_A2minus"])
        score = float(r["isotropy_score_log_ratio"])
        lines.append(f"{u:.6g} & {v:.6g} & {w:.6g} & {rls:.6g} & {rpm:.6g} & {score:.6g}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Compute root split ratios from Sp(6) isotropy scan outputs.")
    ap.add_argument(
        "--scan-json",
        type=str,
        default=str(export_dir() / "sync_kernel_weighted_sp6_isotropy_scan.json"),
        help="Input isotropy scan JSON (Sigma Hessians).",
    )
    ap.add_argument("--top-k", type=int, default=5, help="Use top-K scan candidates.")
    ap.add_argument(
        "--json-out",
        type=str,
        default=str(export_dir() / "sp6_isotropy_root_split_ratio.json"),
    )
    ap.add_argument(
        "--tex-out",
        type=str,
        default=str(generated_dir() / "tab_sp6_isotropy_root_split_ratio.tex"),
    )
    args = ap.parse_args()

    scan_path = Path(str(args.scan_json))
    if not scan_path.is_file():
        raise SystemExit(f"Missing scan JSON: {scan_path}")

    data = json.loads(scan_path.read_text(encoding="utf-8"))
    best = list(data.get("best", []))
    if not best:
        raise SystemExit("No candidates found in scan JSON.")

    top_k = int(args.top_k)
    if top_k <= 0:
        raise SystemExit("Require --top-k >= 1.")

    short_roots, long_roots = _roots_B3()
    a2_plus, a2_minus = _split_A2(long_roots)

    out_rows: List[dict] = []
    for rec in best[:top_k]:
        Sigma = np.array(rec["pressure_hessian_Sigma"], dtype=float)
        ginv = np.linalg.inv(Sigma)
        short_vals = [_length_sq(rv, ginv) for rv in short_roots]
        long_vals = [_length_sq(rv, ginv) for rv in long_roots]
        plus_vals = [_length_sq(rv, ginv) for rv in a2_plus]
        minus_vals = [_length_sq(rv, ginv) for rv in a2_minus]
        mean_short = _mean(short_vals)
        mean_long = _mean(long_vals)
        mean_plus = _mean(plus_vals)
        mean_minus = _mean(minus_vals)

        out_rows.append(
            {
                "weights": rec.get("weights", {}),
                "sigma_eigenvalues": rec.get("sigma_eigenvalues", []),
                "isotropy_score_log_ratio": float(rec.get("isotropy_score_log_ratio", float("nan"))),
                "mean_short": mean_short,
                "mean_long": mean_long,
                "mean_A2plus": mean_plus,
                "mean_A2minus": mean_minus,
                "ratio_long_short": math.sqrt(mean_long / mean_short),
                "ratio_A2plus_A2minus": math.sqrt(mean_plus / mean_minus),
            }
        )

    # JSON export.
    jout = Path(str(args.json_out))
    jout.parent.mkdir(parents=True, exist_ok=True)
    jout.write_text(json.dumps({"source": str(scan_path), "rows": out_rows}, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # LaTeX table.
    _tex_table(Path(str(args.tex_out)), out_rows)

    print(f"[sp6-isotropy-root-split] wrote {jout}", flush=True)
    print(f"[sp6-isotropy-root-split] wrote {args.tex_out}", flush=True)
    print("[sp6-isotropy-root-split] done", flush=True)


if __name__ == "__main__":
    main()
