#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Fibonacci--Lie resonance ladder for |X_m| = F_{m+2}.

We scan window lengths m and check exact equalities between the stable-type
dimension |X_m|=F_{m+2} and a few classical compact Lie algebra dimensions:
  dim su(N) = N^2 - 1,
  dim so(N) = N(N-1)/2,
  dim sp(2n) = n(2n+1).

Note on conventions:
  - In this paper, we write sp(2n) for the symplectic Lie algebra on a 2n-dimensional
    real symplectic space (so sp(6) has dim 21, sp(10) has dim 55, etc.).
  - Many tables in the literature write the same family as sp(n); here we output
    sp(2n) to remain consistent with the paper's Sp(6)/Sp(10) notation.

Outputs:
- artifacts/export/fibonacci_lie_resonance_ladder.json
- sections/generated/tab_fibonacci_lie_resonance_ladder.tex
- sections/generated/eq_fib_lie_resonance_solutions.tex
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from math import isqrt
from pathlib import Path
from typing import Dict, List, Optional

from common_paths import export_dir, generated_dir
from common_phi_fold import fib_upto


@dataclass(frozen=True)
class Resonance:
    m: int
    F: int  # F_{m+2} = |X_m|
    su_N: Optional[int] = None
    so_N: Optional[int] = None
    sp_n: Optional[int] = None


def _match_su(F: int) -> Optional[int]:
    """Return N if F = N^2 - 1 (N>=2), else None."""
    t = F + 1
    s = isqrt(t)
    if s * s == t and s >= 2:
        return int(s)
    return None


def _match_so(F: int) -> Optional[int]:
    """Return N if F = N(N-1)/2 (N>=2), else None."""
    D = 1 + 8 * F
    s = isqrt(D)
    if s * s != D:
        return None
    N = (1 + s) // 2
    if N >= 2 and N * (N - 1) // 2 == F:
        return int(N)
    return None


def _match_sp(F: int) -> Optional[int]:
    """Return n if F = n(2n+1) (n>=1), else None."""
    D = 1 + 8 * F
    s = isqrt(D)
    if s * s != D:
        return None
    num = s - 1
    if num % 4 != 0:
        return None
    n = num // 4
    if n >= 1 and n * (2 * n + 1) == F:
        return int(n)
    return None


def _tex_resonance_desc(r: Resonance) -> str:
    parts: List[str] = []
    if r.su_N is not None:
        parts.append(f"\\dim\\mathfrak{{su}}({r.su_N})={r.F}")
    if r.so_N is not None:
        parts.append(f"\\dim\\mathfrak{{so}}({r.so_N})={r.F}")
    if r.sp_n is not None:
        parts.append(f"\\dim\\mathfrak{{sp}}({2 * r.sp_n})={r.F}")
    return ";\\ ".join(parts) if parts else "-"


def write_table(rows: List[Resonance], *, m_min: int, m_max: int, out_path: Path) -> None:
    lines: List[str] = []
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{6pt}")
    lines.append(
        (
            "\\caption{Fibonacci--Lie 共振梯：稳定类型维数 $|X_m|=F_{m+2}$ 在小窗口上出现对紧李代数维数的精确共振。"
            "本表列出在 $m\\in[%d,%d]$ 的穷举扫描里出现的全部精确共振点（其余 $m$ 不满足等号）。}"
        )
        % (m_min, m_max)
    )
    lines.append("\\label{tab:fibonacci_lie_resonance_ladder}")
    lines.append("\\begin{tabular}{r r l}")
    lines.append("\\toprule")
    lines.append("$m$ & $|X_m|=F_{m+2}$ & 维数共振 \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r.m} & {r.F} & ${_tex_resonance_desc(r)}$\\\\")
    if not rows:
        lines.append("\\multicolumn{3}{c}{(no resonances in this range)}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_solution_equations(
    *,
    m_min: int,
    m_max: int,
    sol_so: List[Dict[str, int]],
    sol_su: List[Dict[str, int]],
    out_path: Path,
) -> None:
    def _tex_set_pairs(pairs: List[Dict[str, int]]) -> str:
        return "\\{" + ",".join(f"({p['m']},{p['N']})" for p in pairs) + "\\}"

    lines: List[str] = []
    lines.append("% AUTO-GENERATED by scripts/exp_fibonacci_lie_resonance_ladder.py")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append(
        (
            "\\{(m,N):%d\\le m\\le %d,\\ F_{m+2}=\\tfrac{N(N-1)}{2}\\}"
            " &= %s,\\\\"
        )
        % (m_min, m_max, _tex_set_pairs(sol_so))
    )
    lines.append(
        ("\\{(m,N):%d\\le m\\le %d,\\ F_{m+2}=N^2-1\\} &= %s.")
        % (m_min, m_max, _tex_set_pairs(sol_su))
    )
    lines.append("\\end{aligned}")
    lines.append("\\]")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--m-min", type=int, default=1)
    ap.add_argument("--m-max", type=int, default=500)
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    m_min = int(args.m_min)
    m_max = int(args.m_max)
    if m_min < 1 or m_max < m_min:
        raise ValueError("Require 1 <= m_min <= m_max")

    fib = fib_upto(m_max + 2)  # F_1..F_{m_max+2}

    resonances: List[Resonance] = []
    sol_so: List[Dict[str, int]] = []
    sol_su: List[Dict[str, int]] = []

    for m in range(m_min, m_max + 1):
        F = int(fib[m + 1])  # F_{m+2} (list is 0-indexed)
        suN = _match_su(F)
        soN = _match_so(F)
        spn = _match_sp(F)

        if soN is not None:
            sol_so.append({"m": int(m), "N": int(soN), "F": int(F)})
        if suN is not None:
            sol_su.append({"m": int(m), "N": int(suN), "F": int(F)})

        if suN is not None or soN is not None or spn is not None:
            resonances.append(Resonance(m=int(m), F=int(F), su_N=suN, so_N=soN, sp_n=spn))

    payload: Dict[str, object] = {
        "params": {
            "m_min": m_min,
            "m_max": m_max,
            "definition": {"X_m": "|X_m| = F_{m+2}", "F_1": 1, "F_2": 1},
            "dimensions": {
                "su": "dim su(N) = N^2 - 1",
                "so": "dim so(N) = N(N-1)/2",
                "sp": "dim sp(2n) = n(2n+1)",
            },
        },
        "resonances": [
            {
                "m": r.m,
                "F_m_plus_2": r.F,
                "su_N": r.su_N,
                "so_N": r.so_N,
                "sp_n": r.sp_n,
                "sp_2n": (2 * r.sp_n) if r.sp_n is not None else None,
            }
            for r in resonances
        ],
        "solutions": {"so": sol_so, "su": sol_su},
    }

    export_dir().mkdir(parents=True, exist_ok=True)
    (export_dir() / "fibonacci_lie_resonance_ladder.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    write_table(
        resonances,
        m_min=m_min,
        m_max=m_max,
        out_path=generated_dir() / "tab_fibonacci_lie_resonance_ladder.tex",
    )
    write_solution_equations(
        m_min=m_min,
        m_max=m_max,
        sol_so=[{"m": s["m"], "N": s["N"]} for s in sol_so],
        sol_su=[{"m": s["m"], "N": s["N"]} for s in sol_su],
        out_path=generated_dir() / "eq_fib_lie_resonance_solutions.tex",
    )

    print(
        f"[fib_lie_resonance] done m=[{m_min},{m_max}] resonances={len(resonances)} "
        f"so_solutions={len(sol_so)} su_solutions={len(sol_su)}",
        flush=True,
    )


if __name__ == "__main__":
    main()
