#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit certificate: Zeckendorf-shift formulas for Wythoff/Beatty.

This script is English-only by repository convention.

It generates a small LaTeX table snippet that certifies, for a chosen range,
the identity

  floor(n*phi)  = S1(n) - delta(n)
  floor(n*phi^2)= S2(n) - delta(n)

where (d_i) is the Zeckendorf digit expansion of n in Fibonacci weights and
S1,S2 are Zeckendorf shifts.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, getcontext
from pathlib import Path
from typing import List, Tuple


ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "sections" / "generated"


def fib_list(max_i: int) -> List[int]:
    """Return Fibonacci numbers F_0..F_max_i with F_0=0, F_1=1."""
    if max_i < 0:
        raise ValueError("max_i must be >= 0")
    F = [0] * (max_i + 1)
    if max_i >= 0:
        F[0] = 0
    if max_i >= 1:
        F[1] = 1
    for i in range(2, max_i + 1):
        F[i] = F[i - 1] + F[i - 2]
    return F


def zeckendorf_digits(n: int) -> List[int]:
    """Return Zeckendorf digits d_2,d_3,...,d_L for n.

    The returned list has indices starting at i=2 (stored as position 0).
    It satisfies n = sum_{i>=2} d_i F_i with no adjacent 1s.
    """
    if n <= 0:
        raise ValueError("n must be >= 1")

    # Choose L so that F_L <= n < F_{L+1}.
    F = [0, 1]
    while F[-1] <= n:
        F.append(F[-1] + F[-2])
    L = len(F) - 2  # last index with F[L] <= n
    F_full = fib_list(L + 2)
    d = [0] * (L - 1)  # digits for i=2..L

    rem = n
    i = L
    while rem > 0 and i >= 2:
        if F_full[i] <= rem:
            d[i - 2] = 1
            rem -= F_full[i]
            i -= 2
        else:
            i -= 1
    return d


def lowest_one_index(d: List[int]) -> int:
    """Return ell(n) = min{i>=2 : d_i=1}. d stores i=2.. as 0-based."""
    for j, bit in enumerate(d):
        if bit:
            return j + 2
    raise ValueError("digits must have at least one 1")


def shifts(n: int, d: List[int], F: List[int]) -> Tuple[int, int, int]:
    """Compute (S1,S2,delta) from digits d_2..d_L and Fibonacci table F."""
    ell = lowest_one_index(d)
    delta = 1 if (ell % 2 == 0) else 0

    # S1 = sum d_i F_{i+1}, S2 = sum d_i F_{i+2}
    S1 = 0
    S2 = 0
    for j, bit in enumerate(d):
        if not bit:
            continue
        i = j + 2
        S1 += F[i + 1]
        S2 += F[i + 2]
    return S1, S2, delta


@dataclass
class Row:
    n: int
    a: int
    a_formula: int
    b: int
    b_formula: int


def compute_rows(N: int) -> List[Row]:
    getcontext().prec = 80
    phi = (Decimal(1) + Decimal(5).sqrt()) / Decimal(2)

    # Precompute Fibonacci up to a safe bound.
    # For n<=N, the largest index used is about O(log N); we just over-allocate.
    F = fib_list(200)

    rows: List[Row] = []
    for n in range(1, N + 1):
        d = zeckendorf_digits(n)
        S1, S2, delta = shifts(n, d, F)

        a = int((Decimal(n) * phi).to_integral_value(rounding="ROUND_FLOOR"))
        b = int((Decimal(n) * (phi * phi)).to_integral_value(rounding="ROUND_FLOOR"))

        a_formula = S1 - delta
        b_formula = S2 - delta

        if a != a_formula or b != b_formula:
            raise RuntimeError(
                f"Mismatch at n={n}: a={a} vs {a_formula}, b={b} vs {b_formula}"
            )

        rows.append(Row(n=n, a=a, a_formula=a_formula, b=b, b_formula=b_formula))
    return rows


def write_tex(rows: List[Row], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/exp_wythoff_shift_certificate.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{rrrrr}")
    lines.append("\\toprule")
    lines.append(
        "$n$ & $\\lfloor n\\varphi\\rfloor$ & $S_1(n)-\\delta(n)$ & $\\lfloor n\\varphi^2\\rfloor$ & $S_2(n)-\\delta(n)$ \\\\"
    )
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r.n} & {r.a} & {r.a_formula} & {r.b} & {r.b_formula} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Audit certificate for the Zeckendorf-shift Wythoff formulas (Theorem~\\ref{thm:zeckendorf-shift-beatty-wythoff}).}"
    )
    lines.append("\\label{tab:wythoff_shift_certificate}")
    lines.append("\\end{table}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    N = 20
    rows = compute_rows(N)
    out = GEN / "tab_wythoff_shift_certificate.tex"
    write_tex(rows, out)
    print(f"File: {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
