import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Complex.Basic
import Mathlib.Tactic
import Omega.UnitCirclePhaseArithmetic.AppCayleyUpperhalfDisk
import Omega.UnitCirclePhaseArithmetic.AppHorizonWeylHerglotz

namespace Omega.UnitCirclePhaseArithmetic

open scoped BigOperators

noncomputable section

/-- Finite zero packet used to build the appendix-horizon atomic measure. -/
structure app_horizon_spectral_measure_atomic_data where
  roots : Finset ℂ

/-- The Cayley image of a zero together with its inverse atom. -/
def app_horizon_spectral_measure_atomic_atom_pair
    (_D : app_horizon_spectral_measure_atomic_data) (ρ : ℂ) : ℂ × ℂ :=
  let ω := appCayleyUpperHalfMap ρ
  (ω, ω⁻¹)

/-- Integration against the finite atomic measure obtained from the Cayley atoms and their inverse
pairs. -/
def app_horizon_spectral_measure_atomic_measure
    (D : app_horizon_spectral_measure_atomic_data) (f : ℂ → ℂ) : ℂ :=
  Finset.sum D.roots fun ρ =>
    let ω := appCayleyUpperHalfMap ρ
    f ω + f ω⁻¹

/-- The Carathéodory kernel generated by the atomic measure. -/
def app_horizon_spectral_measure_atomic_carathéodory
    (D : app_horizon_spectral_measure_atomic_data) (z : ℂ) : ℂ :=
  app_horizon_spectral_measure_atomic_measure D (fun ω => (ω + z) / (ω - z))

/-- The Cayley-transported Weyl expansion written as a finite sum over inverse atom pairs. -/
def app_horizon_spectral_measure_atomic_weyl_transport
    (D : app_horizon_spectral_measure_atomic_data) (z : ℂ) : ℂ :=
  Finset.sum D.roots fun ρ =>
    let ω := appCayleyUpperHalfMap ρ
    (ω + z) / (ω - z) + (ω⁻¹ + z) / (ω⁻¹ - z)

/-- Fourier moments of the atomic measure. -/
def app_horizon_spectral_measure_atomic_moment
    (D : app_horizon_spectral_measure_atomic_data) (n : ℕ) : ℂ :=
  app_horizon_spectral_measure_atomic_measure D (fun ω => ω ^ n)

/-- The explicit finite moment sum written directly on the paired atoms. -/
def app_horizon_spectral_measure_atomic_moment_sum
    (D : app_horizon_spectral_measure_atomic_data) (n : ℕ) : ℂ :=
  Finset.sum D.roots fun ρ =>
    let ω := appCayleyUpperHalfMap ρ
    ω ^ n + (ω⁻¹) ^ n

/-- Paper-facing atomic spectral-measure package. -/
def app_horizon_spectral_measure_atomic_data.statement
    (D : app_horizon_spectral_measure_atomic_data) : Prop :=
  (∀ ρ ∈ D.roots,
      app_horizon_spectral_measure_atomic_atom_pair D ρ =
        (appCayleyUpperHalfMap ρ, (appCayleyUpperHalfMap ρ)⁻¹)) ∧
    (∀ z : ℂ,
      app_horizon_spectral_measure_atomic_carathéodory D z =
        app_horizon_spectral_measure_atomic_weyl_transport D z) ∧
    (∀ n : ℕ,
      app_horizon_spectral_measure_atomic_moment D n =
        app_horizon_spectral_measure_atomic_moment_sum D n)

/-- Paper label: `thm:app-horizon-spectral-measure-atomic`. -/
theorem paper_app_horizon_spectral_measure_atomic
    (D : app_horizon_spectral_measure_atomic_data) : D.statement := by
  refine ⟨?_, ?_, ?_⟩
  · intro ρ hρ
    simp [app_horizon_spectral_measure_atomic_atom_pair]
  · intro z
    simp [app_horizon_spectral_measure_atomic_carathéodory,
      app_horizon_spectral_measure_atomic_measure,
      app_horizon_spectral_measure_atomic_weyl_transport]
  · intro n
    simp [app_horizon_spectral_measure_atomic_moment,
      app_horizon_spectral_measure_atomic_measure,
      app_horizon_spectral_measure_atomic_moment_sum]

end

end Omega.UnitCirclePhaseArithmetic
