import json
from pathlib import Path
items=json.loads(Path('.stage_a_envs_current.json').read_text(encoding='utf-8'))
keys=['valid','in_scope_present','missing_in_scope_results','weak_in_scope_core_results','proof_gaps','supporting_appendix_or_background','out_of_scope_strong_results','split_candidates','irrelevant_or_remove','naive_truncation_risks','journal_style_gaps']
def row(label,location,reason,required_action,**extra):
 d={'label':label,'location':location,'reason':reason,'required_action':required_action}; d.update(extra); return d
secs=['Problem and contribution','Architecture','Abstract finite-record interface','Primary-claim inventory audit','Current-package instantiation','Case-study witness protocol','Case studies','Primary--supplement interface','Subordinate support-boundary ledger','Command-run boundary']
by={}
for it in items:
 if it['file']=='main.tex':
  s=it['section']; by.setdefault(s,{'a':it['start'],'b':it['end'],'labs':[]}); by[s]['a']=min(by[s]['a'],it['start']); by[s]['b']=max(by[s]['b'],it['end']); by[s]['labs'].append(it['label'])
inp=[]
for s in secs:
 d=by[s]; labs='; '.join(d['labs']); loc=f"main.tex:{d['a']}-{d['b']}"
 reason={
 'Problem and contribution':'Package-shape and nested package-state claims fix the primary/subordinate support convention.',
 'Architecture':'Axis separation, imported BEDC/newmath source-interface extraction, source-snapshot comparison, and source non-escalation are present.',
 'Abstract finite-record interface':'Core finite-record calculus is present: acceptance interface, schema verifier, exactness, bad-subrecord normal forms, publication-safety interface, rigidity, maximality, and no-free-upgrade claims.',
 'Primary-claim inventory audit':'Primary article claims are tied to the current package acceptance/certificate ledger.',
 'Current-package instantiation':'Current-package exactness, row-frozen invariance, extension rigidity, semantic non-escalation, named boundary classifier, and path-verified instance are present.',
 'Case-study witness protocol':'Gate-witness criterion and path-complete witness interface for the four case studies are present.',
 'Case studies':'Review-bundle case coverage and case-witness skeleton rigidity are present.',
 'Primary--supplement interface':'Venue, artifact-role, formal-source, evidence-level, finite-witness, artifact-validation, and primary-support interfaces are present.',
 'Subordinate support-boundary ledger':'Support-surface, archive-equivalence, digest, upload, theorem-inventory, extractor, and local support normal-form claims are present.',
 'Command-run boundary':'Post-edit rerun, support-state reconciliation, route classifier, post-inventory fixed point, command-result closure, and terminal coordinate claims are present.'}[s]
 action='Keep in scope with finite-record/path-verified qualifiers; refresh exact logs and digests after final inventory bytes before claiming current fixed-point support.'
 inp.append(row(labs,loc,reason,action))
inp.append(row('submission_abstract_primary_architecture_claims','submission_abstract.tex:21-195','Primary artifact states the architecture, typed trust boundary, four lessons, finite-record safety claim, and support notes.','Keep synchronized with supplement, primary-claim inventory, and support-boundary wording.'))
snap=[it['label'] for it in items if it['file'].startswith('review_bundle/source_snapshots') and it['label']]
inv={'valid':True,'in_scope_present':inp,
'missing_in_scope_results':[
row('missing:post-inventory-current-byte-closure-refresh','main.tex:8019-10523; review_bundle/theorem_environment_extraction_run.log; review_bundle/FINAL_DIGESTS_SHA256.md','This inventory write changes the bytes that the manuscript later treats as a post-inventory support coordinate; older extractor/digest records are not final for these bytes.','After accepting the inventory, rerun theorem extraction, retained verifiers, and digest generation with command, environment, exit code, and log paths.'),
row('missing:external-support-coordinate','submission_abstract.tex:192-195; main.tex:7021-7727; main.tex:10395-10415','No venue-upload receipt, DOI-bearing supplement, exact supplemental upload, or archive-equivalent byte-equality locator is currently recorded.','Keep support claims local/path-verified unless exact upload or byte-equality archive evidence is added.'),
row('missing:fresh-formal-source-rebuild-and-axiom-audit','main.tex:491-699; main.tex:6027-6133','Imported BEDC/newmath evidence is path/line/label/digest verified, not a fresh Lean/BEDC rebuild or axiom-purity audit.','Do not claim formal-source correctness beyond the bounded interface unless a fresh rebuild/audit coordinate is supplied.'),
row('missing:gate-implementation-soundness-instantiation','main.tex:1219-1263; main.tex:2307-2482; main.tex:3223-4372','Record-gate soundness is an external interface/premise, not a proved semantic correctness theorem for gate implementations.','Keep main results conditional on record-gate soundness or add a separate implementation audit.'),
row('missing:dynamic-artifact-validation-rerun','main.tex:6210-6369; main.tex:8824-8873; submission_abstract.tex:146-152','Finite witness and artifact rows are manifest-bounded case evidence, not fresh dynamic validation of the whole artifact suite.','Require evaluator contracts and fresh rerun logs before any artifact-semantic upgrade.')],
'weak_in_scope_core_results':[
row('weak:presentation-scope-core-obscured-by-support-calculus','main.tex:1038-4424; main.tex:7021-11021','The core theorem chain is present but surrounded by a very large support-boundary calculus for a CICM presentation route.','Keep the primary article focused and treat the support calculus as supplemental, not as a competing theorem program.'),
row('weak:central-publication-safety-proof-readability','main.tex:3090-3167','The main publication-safety proof dispatches through many dependencies and may be hard to audit quickly.','Add a compact proof roadmap or dependency table in a later TeX-edit stage.'),
row('weak:manual-source-interface-extraction-level','main.tex:491-699','Manual bounded extraction plus JSON/snapshot comparison supports the scope but is weaker than automated semantic extraction.','Preserve manual/path-verified qualifiers; do not assume semantic import.')],
'proof_gaps':[
row('gap:self-referential-inventory-fixed-point-needs-final-rerun','main.tex:8019-8519; main.tex:9807-10523','The inventory support coordinate is byte-level self-referential and closes only after extraction/digest logs are regenerated on accepted inventory bytes.','Rerun extractor/verifiers/digest after final JSON/MD bytes or phrase fixed-point claims as pending.'),
row('gap:bibliography-and-venue-live-check-temporality','references.bib:1-54; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-09.log','Venue and bibliography facts are time-sensitive dated records, not timeless upload compliance.','Run a final live venue/bibliography check near submission if current compliance is claimed.'),
row('gap:local-path-evidence-not-reviewer-visible-without-bundle','main.tex:573-586; main.tex:7953-7968; submission_abstract.tex:183-195','Several claims are reviewable only if the support bundle or exact archive-equivalent bytes are available to the reviewer.','Ensure exact support availability or mark those claims local-only.'),
row('gap:record-gate-soundness-external-premise','main.tex:1219-1263; main.tex:3090-3167','The main theorem assumes record-gate soundness rather than proving gate implementation correctness.','State the hypothesis prominently and keep implementation-soundness upgrades separate.')],
'supporting_appendix_or_background':[
row('support:snapshot_imported_discovery_gate_spine labels: '+'; '.join(snap),'review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Bundled source snapshot supplies the imported automated-discovery calculus spine only as pinned background/source evidence.','Preserve citation, commit, line ranges, snapshot digest, and non-escalation qualifiers.'),
row('support:formal-methods-literature','references.bib:9-46; submission_abstract.tex:175-180; main.tex:255-260','Lean, LeanDojo, Draft--Sketch--Prove, and AFP are external background, not new results.','Cite as background only.'),
row('support:bedc-newmath-source-citation','references.bib:1-8; main.tex:402-451','Pinned BEDC/newmath source citation supplies external source surface and workflow context.','Keep exact repository/commit/path metadata and bounded-interface wording.'),
row('support:review-bundle-scripts-and-manifests','review_bundle/certificate_schema.json; review_bundle/current_package_pass_records.json; review_bundle/REVIEW_BUNDLE_MANIFEST.json; review_bundle/*.py','Scripts, schemas, manifests, and logs support deterministic finite-record predicates but not semantic gate correctness.','Submit/archive exact bytes with refreshed SHA rows if reviewer-visible.')],
'out_of_scope_strong_results':[
row('out-of-scope:Rule110/GroundCompiler semantic universality or dynamic validation','main.tex:6210-6369; review_bundle/case_snapshots/rule110_*','Used only as bounded artifact-limitation case evidence; dynamic semantic validation is denied.','Do not expand into Rule110 validation.',candidate_title='Manifest-to-Semantics Validation for Rule110/GroundCompiler Artifacts',source_contribution='Stage A isolates evaluator-contract and dynamic-rerun upgrade gaps.',scope_mismatch='Current article is publication architecture, not artifact semantics.',independent_paper_rationale='Could study evaluator specs, reruns, and manifest-to-semantics upgrades.',needed_to_split=['evaluator contract','fresh rerun logs','artifact digest manifest','semantic validity specification']),
row('out-of-scope:complete BEDC theory exposition','main.tex:289-303; main.tex:491-699','BEDC is an evidence axis and source provider; complete BEDC theory is excluded.','Keep BEDC to interface and architecture role.',candidate_title='BEDC Source-Theory Audit Interfaces',source_contribution='Stage A isolates source-theory/proof-obligation/implementation-contract separation.',scope_mismatch='Present paper needs compiler boundary only.',independent_paper_rationale='A BEDC paper could present theory, Lean interfaces, and obligations.',needed_to_split=['BEDC definitions','Lean rebuild logs','axiom audit','mathematical examples']),
row('out-of-scope:AI-proof-certification-or-automated-acceptance','main.tex:154-160; submission_abstract.tex:55-58','The manuscript rejects AI proof evidence and automated venue acceptance.','Keep as negative boundary.',candidate_title='Trust Boundaries for AI Agents in Formal-Mathematics Publication Workflows',source_contribution='Stage A records agent-boundary and no-free-promotion invariants.',scope_mismatch='Current article is a concrete compiler architecture.',independent_paper_rationale='Could generalize advisory-only agent authority models.',needed_to_split=['agent taxonomy','human promotion protocol','cross-project examples'])],
'split_candidates':[
row('split:archive-equivalent support surfaces and byte-level fixed points','main.tex:7021-8439; main.tex:9634-10591','Digest closure, exact inclusion, archive equivalence, and post-inventory fixed points form a reusable support theory.','Keep package-local here; split only as reproducibility theory.',candidate_title='Byte-Level Support-Surface Fixed Points for Mathematical Software Submissions',source_contribution='Stage A identifies exact inclusion, self-digest avoidance, archive byte equality, and fixed-point machinery.',scope_mismatch='Current route needs support governance, not archival theory.',independent_paper_rationale='Useful for artifact-evaluation and reproducibility bundles.',needed_to_split=['tool-independent digest generator','archive model','multi-venue examples','receipt protocol']),
row('split:finite-record certificate calculus','main.tex:1038-4424','The acceptance interface, stronger-reading preorder, bad-record normal form, and extension-budget calculus are substantial abstract machinery.','Use as proof spine here; split only if generalized.',candidate_title='A Finite-Record Certificate Calculus for Publication Safety Claims',source_contribution='Stage A discovers reusable typed finite-record calculus.',scope_mismatch='Current paper is an applied workflow report.',independent_paper_rationale='Could support generic audit systems.',needed_to_split=['abstract gate category','independent examples','machine-checkable schema semantics']),
row('split:route-governance-and-overlap-blocking','main.tex:5282-5494; review_bundle/case_snapshots/upper_fibers_*','Submitted-route overlap is a structural finite-record blocker.','Keep as one case lesson.',candidate_title='Route-State Ledgers for Preventing Duplicate Mathematical Submissions',source_contribution='Stage A classifies overlap blocking as route-state ledger logic.',scope_mismatch='Present article only needs bounded case evidence.',independent_paper_rationale='Could formalize route states and human/daemon visibility.',needed_to_split=['route-state model','overlap detector','policy examples']),
row('split:theorem-content-gate-for-fake-extensions','main.tex:5282-5494; review_bundle/case_snapshots/fake_extension_*','Fake extensions show code churn and statement reshuffling can mimic progress without theorem-content witnesses.','Keep as a case lesson.',candidate_title='Theorem-Content Gates for AI-Assisted Formal-Mathematics Editing',source_contribution='Stage A classifies fake extensions by missing theorem-content witness.',scope_mismatch='Current paper is not a novelty detector paper.',independent_paper_rationale='Could define theorem-content deltas and detectors.',needed_to_split=['content delta definition','positive/negative corpus','detector implementation'])],
'irrelevant_or_remove':[
row('remove_or_quarantine:local-scratch-stage-a-artifacts','.stage_a_envs_current.json; .stage_a_main_env_table.txt; .stage_a_labels_by_section.txt; .agent_*; .current_*; .prior_inventory_dump.json; _write_inventory*.py','Scratch/parser/prior review artifacts are not part of the paper unless manifest-promoted.','Do not cite or upload scratch artifacts.'),
row('remove_or_quarantine:prior-single-primitive-hierarchy-ledger-context','prompt prior ledger; no in-scope manuscript theorem','L0/L1/L2 hierarchy, EML, Zeckendorf, Richardson, Hankel-Prony, and finite-state strictness belong to another paper.','Do not import hierarchy results here.')],
'naive_truncation_risks':[
row('risk:post-inventory-fixed-point-staleness','main.tex:8019-8519; main.tex:9807-10523','Cross-resolution support over source bytes, inventory bytes, extractor logs, verifier logs, and digests is not invariant under inventory edits.','Regenerate logs/digests after final inventory bytes.'),
row('risk:local-bundle-versus-external-support-surface','main.tex:7021-7727; submission_abstract.tex:192-195','Local files and digest rows do not imply upload, DOI, archive, or public byte equality.','Keep exact-upload/archive-equivalent conditional language.'),
row('risk:manual-line-range-interface-versus-semantic-source-import','main.tex:491-699','Line-range/hash checks descend only to bounded textual rows, not semantic theorem import or Lean rebuild correctness.','Keep manual/path-verified evidence level.'),
row('risk:manifest-bounded-finite-witness-versus-dynamic-artifact-semantics','main.tex:6210-6369; main.tex:8824-8873','Finite witness rows and snapshots can be misread as live dynamic artifact validation.','Require evaluator contracts and fresh reruns for semantic upgrades.'),
row('risk:row-frozen-ledger-versus-general-package-correctness','main.tex:211-228; main.tex:4631-4910','Row-frozen exactness applies only to named rows and declared predicates.','Add new coordinates for future rows or stronger claims.'),
row('risk:venue-freshness-log-versus-upload-time-compliance','main.tex:5637-5864','A dated live check is not invariant venue compliance at upload time.','Refresh near submission.')],
'journal_style_gaps':[
row('style:presentation-versus-supplement-scale','main.tex:67-11086; submission_abstract.tex:21-195','The primary artifact is compact but the supplement has 154 labelled theorem-like environments, heavy for a presentation route.','Keep supplement optional/local technical support if venue requires brevity.'),
row('style:terminology-density','main.tex:1038-4424; submission_abstract.tex:55-128','Record-gate soundness, stronger-reading preorder, finite bad subrecord, no-free-upgrade, and support-coordinate fixed point are dense terms.','Add a glossary or simplify notation.'),
row('style:label-prefix-environment-mismatch','main.tex:8245','The theorem environment has label `prop:manual-theorem-inventory-boundary`, whose prefix mismatches the environment type.','Rename later or document prefix non-semantics; do not edit TeX in inventory stage.'),
row('style:central-theorem-dependency-readability','main.tex:3090-3167; main.tex:6569-6774','The core theorem chain is spread across many labels and support classifiers.','Add dependency diagram or proof skeleton.'),
row('style:bibliography-minimality-and-currentness','references.bib:1-46','Bibliography is minimal but live venue/bibliography metadata can change.','Verify official data immediately before submission.'),
row('style:support-surface-submission-policy-dependency','review_bundle/REVIEW_BUNDLE_MANIFEST.json:17-19','Strong support-surface reading depends on support-file upload or archive-equivalent locator policy.','Confirm route support-file policy before submission.')]
}
inv={k:inv[k] for k in keys}
Path('theorem_inventory.json').write_text(json.dumps(inv,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory','','Stage A theorem inventory for `2026_auditable_theory_to_paper_pipeline`. `theorem_inventory.json` is authoritative; this Markdown mirrors it.','']
for k in keys:
 if k=='valid': md+=['## valid','','`true`','']; continue
 md+=['## '+k.replace('_',' ').title(),'']
 if not inv[k]: md+=['- None recorded.','']; continue
 for x in inv[k]:
  md.append(f"- **{x['label']}** (`{x['location']}`): {x['reason']} Required action: {x['required_action']}")
  if k in ('out_of_scope_strong_results','split_candidates'):
   for e in ('candidate_title','source_contribution','scope_mismatch','independent_paper_rationale'):
    if e in x: md.append(f"  - {e.replace('_',' ')}: {x[e]}")
   if 'needed_to_split' in x: md.append('  - needed to split: '+'; '.join(x['needed_to_split']))
 md.append('')
Path('theorem_inventory.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print(json.dumps({'wrote':['theorem_inventory.json','theorem_inventory.md'],'main_envs':sum(1 for i in items if i['file']=='main.tex'),'snapshot_envs':len(snap)},indent=2))
