import json, pathlib, collections
root=pathlib.Path('.')
items=json.load(open('.direct_envs.json',encoding='utf-8'))
sections=collections.defaultdict(list)
for e in items:
    sections[e['section']].append(e)

def labels_for(section):
    return ', '.join(e['label'] for e in sections[section])

def loc_for(section):
    lst=sections[section]
    return f"main.tex:{lst[0]['line']}-{lst[-1]['end']} ({section})"

section_reasons={
 'section: Problem and contribution': ('Package-state spine: fixes the primary/supplement/bundle/theorem-ledger shape and the conservative P6-to-P7 support-state inclusion.', 'Keep as the front support-contract theorem chain; after this inventory is written, refresh post-inventory logs and digests before claiming final fixed-point support.'),
 'section: Architecture': ('Architecture and source-interface spine: separates BEDC source, Lean markers, finite witnesses, agents, and automath publication records; bounds imported source evidence to pinned paths and finite interface rows.', 'Retain all source-path, line-range, evidence-level, and non-escalation qualifiers; do not upgrade manual/path-verified source rows to public reachability or semantic completeness.'),
 'subsection: Abstract finite-record interface': ('Core finite-record certificate calculus: defines the operational acceptance interface, record-gate soundness interface, schema verifier, dispatch, bad-record obstructions, non-escalation, and the central publication-safety interface theorem.', 'Keep the record-gate-soundness hypothesis explicit in title, abstract, and theorem usage; cite verifier scripts/logs only at their finite-record boundary.'),
 'subsection: Primary-claim inventory audit': ('Current-package acceptance ledger: records the row-frozen certificate ledger used to audit primary load-bearing claims.', 'Keep row-frozen/schema-relative wording; do not read the ledger as semantic truth of every primary sentence.'),
 'subsection: Current-package instantiation': ('Current-package instantiation chain: proves schema-relative exactness, ledger-dependence, row-frozen invariance, extension-coordinate boundary, issue-closure, and no-free-acceptance consequences.', 'Preserve the finite-row and finite-coordinate hypotheses; rerun freshness checks after any edit to the primary or inventory files.'),
 'subsection: Case-study witness protocol': ('Case-study gate witness calculus: formalizes path-complete historical witnesses, four case skeletons, and non-escalation from case rows to fresh daemon/rebuild/artifact claims.', 'Keep each case row tied to gate, observed issue, support path, and safe lesson; require command metadata for any stronger live-rerun reading.'),
 'section: Case studies': ('Four automath/newmath case studies: intake isolation, overlap/submitted blocking, fake-extension rejection, and artifact-limitation disclosure.', 'Use as bounded software-engineering evidence only; do not present as new mathematical theorem content, live benchmark data, or complete artifact validation.'),
 'subsection: Primary--supplement interface': ('Venue and primary--supplement interface: records venue freshness, submission-pack gates, artifact role separation, primary-claim inventory, and primary-to-supplement certification maps.', 'Treat venue and bibliography observations as dated finite records; repeat the live check and update records immediately before any upload-time compliance claim.'),
 'subsection: Review-bundle and archive-equivalence condition': ('Review-bundle/archive support calculus: states exact-inclusion, archive-equivalence, digest closure, theorem-inventory extraction, support-tuple extraction, and case-evidence closure.', 'After this inventory is generated, rerun extractor/verifiers and regenerate FINAL_DIGESTS_SHA256.md to instantiate current-byte support; add upload or archive locator before external-support claims.'),
 'subsection: Command-run boundary': ('Command-run/fixed-point boundary: records command metadata requirements, post-edit rerun gate, final support-state reconciliation, and byte-level fixed-point normal forms.', 'Use only for logs actually rerun from the named source state; stale pre-inventory or pre-edit logs certify only historical byte coordinates.')
}

in_scope=[]
for sec in sections:
    reason, action = section_reasons.get(sec, ('In-scope formal material present in manuscript source.', 'Retain with stated hypotheses and evidence boundaries.'))
    in_scope.append({'label': labels_for(sec), 'location': loc_for(sec), 'reason': reason, 'required_action': action})

inventory={
 'valid': True,
 'in_scope_present': in_scope,
 'missing_in_scope_results': [],
 'weak_in_scope_core_results': [
  {'label':'thm:publication-safety-interface, thm:finite-record-certificate-calculus-spine, thm:publication-safety-maximality, cor:publication-safety-current-package-instance','location':'main.tex:2535, main.tex:2872, main.tex:3811, main.tex:3855','reason':'The central safety theorem is deliberately finite-record-only and conditional on record-gate soundness; it is not implementation soundness, semantic correctness of gates, Lean correctness, or venue acceptance.','required_action':'Keep the abstract/title/theorem wording explicitly conditional; if the article wants a stronger CICM software claim, add a separate audited implementation-soundness theorem with code-level specification, command logs, and proof obligations instead of silently strengthening this result.'},
  {'label':'thm:concrete-finite-script-implementation-soundness, cor:finite-script-rgs-instantiation-boundary, thm:assigned-gate-soundness-audit-boundary','location':'main.tex:2170, main.tex:2268, main.tex:2278','reason':'The finite scripts are shown to implement record projections/checks, not the full semantic correctness of every gate or the real-world validity of every evidence surface.','required_action':'Present these as projection-contract/verifier-boundary results; add independent code review or formalized verifier specifications only if the paper claims implementation soundness.'},
  {'label':'prop:current-package-acceptance-certificate-ledger, thm:current-package-certificate-exactness, cor:row-frozen-current-package-invariance','location':'main.tex:4186, main.tex:4296, main.tex:4499','reason':'The current-package certificate is row-frozen and schema-relative; it is strong enough for the paper’s finite-record claim but too weak for a semantic truth certificate for all primary prose.','required_action':'Keep row-frozen/schema-relative qualifiers in the primary article and supplement; rerun the primary-claim inventory after any edit to submission_abstract.tex.'},
  {'label':'lem:source-interface-extraction-correctness, prop:source-interface-record-file-consistency, thm:bounded-source-interface-maximality, thm:source-interface-semantic-completeness-obstruction','location':'main.tex:487, main.tex:599, main.tex:666, main.tex:823','reason':'The imported BEDC/newmath source interface is a bounded manual/path-verified extraction plus finite record comparison, not a complete BEDC exposition or public byte-equality/semantic completeness certificate.','required_action':'Keep the pinned commit, source path, line ranges, and bounded-paraphrase boundary visible; add public reachability and byte-equality records only if the paper wants current-public-source claims.'}
 ],
 'proof_gaps': [
  {'label':'prop:post-inventory-freshness-obstruction, thm:post-inventory-package-fixed-point, thm:current-inventory-artifact-realization, thm:current-command-result-closure, cor:current-post-inventory-support-tuple-instantiation, cor:stable-replay-post-inventory-tuple','location':'main.tex:9374, main.tex:9003, main.tex:9139, main.tex:9231, main.tex:9277, main.tex:9325; theorem_inventory.json/theorem_inventory.md just created by this stage','reason':'The manuscript’s fixed-point support claims require the theorem inventory bytes, verifier logs, and final digest rows to be produced in the correct order after the inventory files exist. Before this Stage-A output those inventory files were absent; after this output, any pre-inventory logs/digests are stale for the new byte state.','required_action':'After writing the inventory files, rerun review_bundle/extract_theorem_environments.py, verify_certificate_records.py, verify_source_interface_record.py, verify_primary_claim_inventory.py, and regenerate review_bundle/FINAL_DIGESTS_SHA256.md; record the resulting logs before claiming current post-inventory fixed-point support.'},
  {'label':'thm:exact-inclusion-support-surface-realization, thm:public-branch-archive-equivalent-realization, thm:upload-or-archive-instantiation-boundary, cor:upload-or-archive-instantiation-record, prop:no-external-instantiation-from-local-bundle-records','location':'main.tex:6412, main.tex:6456, main.tex:6623, main.tex:6953, main.tex:6985','reason':'The support-surface theorem chain gives conditional exact-inclusion/archive-equivalence criteria but the current package records no completed supplemental upload receipt, DOI, immutable archive, or final public byte-equality locator.','required_action':'Before external-support claims, either submit review_bundle/ exactly with matching final digests or add an archive-equivalent locator with file list, relative paths, digests, manifest semantics, and pinned commit/same-state branch-head byte equality.'},
  {'label':'audit:fresh-venue-record-criterion, thm:venue-rule-freshness-non-escalation, cor:upload-time-venue-compliance-record-requirement, audit:venue-submission-pack-gate','location':'main.tex:5268, main.tex:5311, main.tex:5398, main.tex:5485','reason':'Venue-rule and bibliography facts are temporal. The manuscript has dated local checks, but upload-time compliance is not proved unless the final upload occurs under the checked rule state or an unchanged-rule/replacement record is supplied.','required_action':'Run and record a final venue/bibliography check immediately before upload if the submitted paper will claim upload-time venue compliance; otherwise keep these rows as dated local readiness observations.'},
  {'label':'thm:public-source-reachability-non-escalation, cor:public-source-coordinate-exactness, thm:source-interface-semantic-completeness-obstruction','location':'main.tex:731, main.tex:785, main.tex:823','reason':'The source-interface evidence is pinned and mirrored locally, but the theorem chain explicitly lacks dated remote observation and byte-equality fields for a stronger public-source-currentness or semantic-completeness reading.','required_action':'Do not cite the bounded source interface as public reachability or semantic completeness; add a dated remote fetch, public branch/commit observation, byte comparison, and log if that stronger claim is needed.'},
  {'label':'thm:theorem-inventory-proofchecker-obstruction, thm:deterministic-theorem-environment-extractor-boundary, thm:extractor-domain-exactness-non-gluing, thm:final-byte-extractor-inventory-inclusion','location':'main.tex:7590, main.tex:7412, main.tex:7459, main.tex:7520','reason':'The theorem-inventory extractor proves syntactic label coverage only; it does not inspect proof semantics or certify that the inventory classifications are mathematically correct.','required_action':'Use extractor output only as label-coverage evidence; keep this Stage-A inventory as a human review artifact and do not present it as a proof checker.'}
 ],
 'supporting_appendix_or_background': [
  {'label':'def:architecture-axis-map; supporting citations deMouraKADR2015Lean, YangEtAl2023LeanDojo, JiangEtAl2023DraftSketchProve, BlanchetteHMN2015AFP','location':'main.tex:288; submission_abstract.tex support notes; references.bib','reason':'Lean, LeanDojo, Draft--Sketch--Prove, and AFP mining are contextual software/formal-methods references; they support positioning but are not new results of this paper.','required_action':'Cite them as background only; do not imply the paper contributes a new theorem prover, Lean hammer, proof-archive miner, or formalization method.'},
  {'label':'lem:source-interface-extraction-correctness, prop:reviewable-source-snapshot-interface, prop:source-interface-record-file-consistency','location':'main.tex:487, main.tex:569, main.tex:599; review_bundle/source_snapshots/; review_bundle/source_interface_verification_run.log','reason':'The pinned BEDC/newmath source snapshot and source-interface record are supporting evidence surfaces for imported labels, not a complete BEDC theory presentation.','required_action':'Maintain source paths, commit, line ranges, and bounded summaries; cite BEDC/newmath as source context, not as newly proved content in this paper.'},
  {'label':'prop:machine-readable-certificate-records, prop:finite-certificate-schema-verifier, thm:verifier-input-output-contract, thm:finite-verifier-normal-form','location':'main.tex:1858, main.tex:1293, main.tex:1359, main.tex:1426; review_bundle/certificate_schema.json; review_bundle/verify_certificate_records.py','reason':'The schema and scripts support finite-record checking and reproducibility; their mathematical role is an implementation surface for the record calculus.','required_action':'Keep script behavior, logs, environment, exit codes, and negative boundaries attached to every command-result claim.'},
  {'label':'lem:gate-witness-criterion, prop:path-complete-case-witnesses, thm:case-skeleton-partition, thm:finite-row-case-evidence-closure','location':'main.tex:4913, main.tex:4938, main.tex:4980, main.tex:8233; review_bundle/case_snapshots/','reason':'The four case studies are bounded historical software-engineering witnesses for gates and safe lessons.','required_action':'Retain as case-study support; require new command logs for any live-rerun, benchmark, full-source rebuild, or dynamic validation reading.'},
  {'label':'prior-ledger:2026_single_primitive_universality_hierarchy','location':'Prompt prior research ledger context, not main.tex','reason':'The L0/L1/L2 universality hierarchy, EML/Richardson interface, Zeckendorf protocol arithmetic, and Hankel/Prony certificate material are background memory from another paper pipeline.','required_action':'Use only to avoid rediscovery or accidental scope creep; do not import these results into the auditable theory-compiler article.'}
 ],
 'out_of_scope_strong_results': [
  {'label':'Rule110/full dynamic artifact validation boundary; thm:artifact-suite-non-escalation, thm:current-case-limit-boundary, cor:artifact-limitation-disclosure-instance','location':'main.tex:5836, main.tex:4577, main.tex:4722; review_bundle/case_snapshots/rule110_*','reason':'The manuscript uses artifact limitations only as a case-study lesson, while full dynamic artifact validation or Rule110 universality/exhaustiveness is expressly outside the paper’s central claim.','required_action':'Keep only the bounded artifact-limitation disclosure in this article; route full dynamic validation to a separate artifact or theory paper.','candidate_title':'Dynamic Artifact Validation and Rule110 Evidence Boundaries','source_contribution':'Stage A identified finite witness files, limitation ledgers, and case snapshots that separate bounded artifact evidence from fresh dynamic validation.','scope_mismatch':'The present paper is about finite-record publication safety, not proving Rule110 universality, rerunning artifact suites, or validating semantic substrate behavior.','independent_paper_rationale':'A separate paper could define evaluator contracts, rerun protocols, dynamic validation semantics, and artifact limitation certificates as first-class software artifacts.','needed_to_split':['Formal evaluator contract','fresh rerun command logs','source-state and environment records','semantic validation criteria','artifact-output digest manifest']},
  {'label':'Complete BEDC theory exposition boundary; def:architecture-axis-map, thm:source-interface-semantic-completeness-obstruction','location':'main.tex:288, main.tex:823; pinned BEDC/newmath source snapshot','reason':'The manuscript imports bounded BEDC/newmath source-interface rows but explicitly does not present complete BEDC theory or theoretical closure.','required_action':'Do not expand this article into a BEDC theory paper; keep BEDC as source-interface evidence unless a separate exposition is commissioned.','candidate_title':'BEDC Source Theory, Closure, and Verification Interfaces','source_contribution':'Stage A confirmed that the architecture paper depends on BEDC source paths and labels but only at bounded interface level.','scope_mismatch':'A complete BEDC exposition would dominate the CICM presentation-only architecture contribution.','independent_paper_rationale':'The BEDC source theory, proof obligations, and implementation contracts may support a standalone formal mathematics/software paper.','needed_to_split':['BEDC definitions and closure theorems','Lean verification map','source-to-paper theorem dependency DAG','complete citations and proof obligations']},
  {'label':'Gate implementation soundness; thm:record-gate-implementation-overclaim-obstruction, cor:finite-record-acceptance-not-implementation-soundness, thm:implementation-soundness-extension-criterion','location':'main.tex:1763, main.tex:1819, main.tex:3951','reason':'The paper isolates implementation soundness as a stronger reading requiring extra records; it does not prove gate code correctness or an end-to-end verified compiler.','required_action':'Keep the negative boundary in this article; split verified implementation soundness into a separate engineering/formal verification project if desired.','candidate_title':'Verified Record-Gate Implementation Soundness for Theory-to-Paper Compilers','source_contribution':'Stage A found a reusable obstruction/extension criterion for moving from finite record acceptance to implementation soundness.','scope_mismatch':'The current scope is a finite-record interface theorem under record-gate soundness, not a verified implementation theorem.','independent_paper_rationale':'A verified checker paper could specify gate semantics, prove script correctness, and test the compiler as a reproducible software artifact.','needed_to_split':['Gate semantics specification','script/code audit','formal verifier or tests','implementation logs','negative and positive fixtures']}
 ],
 'split_candidates': [
  {'label':'prior-ledger:2026_single_primitive_universality_hierarchy','location':'Prompt prior research ledger; source_dir D:/omega/automath/papers/publication/2026_single_primitive_universality_hierarchy','reason':'Mathematically substantial prior Stage-A material is unrelated to the auditable theory-compiler route except as attribution memory.','required_action':'Keep out of this manuscript; preserve attribution and route to the existing split-paper pipeline.','candidate_title':'Single-Primitive Universality Hierarchy: Expression, Protocol, and Certificate Levels','source_contribution':'Earlier Stage A discovered the L0/L1/L2 taxonomy, EML universality, Zeckendorf protocol arithmetic, finite-fiber Hankel/Prony certificate universality, finite-state strictness, and conditional Richardson-interface claims.','scope_mismatch':'Those results are mathematical universality and certificate hierarchy theorems, whereas this article is a CICM-style finite-record publication compiler architecture paper.','independent_paper_rationale':'The hierarchy has its own research question, theorem chain, strict separations, and target venue distinct from the software-workflow article.','needed_to_split':['Keep the L0/L1/L2 theorem inventory in its source paper','Resolve Richardson conditionality and replacement-triple status','Separate finite-fiber and finite-state certificate claims','Audit appendix dependencies']},
  {'label':'thm:finite-record-certificate-calculus-spine, thm:finite-extension-budget-normal-form, thm:mixed-interface-overclaim-skeleton, thm:boundary-axis-non-escalation-exactness','location':'main.tex:2535, main.tex:2448, main.tex:3301, main.tex:3165','reason':'The abstract finite-record calculus is reusable and broader than the immediate presentation package.','required_action':'Keep only the calculus needed for this article’s central interface theorem; consider a separate general theory paper for the full algebra of records, gates, bad subrecords, and non-escalation.','candidate_title':'A Finite-Record Certificate Calculus for Auditable Scientific Claims','source_contribution':'Stage A found a coherent abstract calculus of finite records, dispatch tables, bad-record witnesses, extension budgets, and axis non-escalation.','scope_mismatch':'A general calculus would exceed the CICM presentation-only software-workflow scope and obscure the concrete automath/newmath package story.','independent_paper_rationale':'The calculus could be axiomatized independently and applied to other scientific/reproducibility pipelines.','needed_to_split':['Abstract syntax and semantics','Minimality/normal-form theorem chain','Examples outside automath','Independent proof-checking or model examples']},
  {'label':'thm:fake-extension-non-growth, thm:theorem-content-gate-non-escalation, cor:fake-extension-rejection-safe-lesson','location':'main.tex:5745, main.tex:5789, main.tex:5813','reason':'The fake-extension/theorem-content delta machinery can be a standalone method for detecting theorem-looking but content-poor edits.','required_action':'Use only as one bounded case study here; split if developing metrics, lint rules, and evaluation across many papers.','candidate_title':'Theorem-Content Delta Gates for AI-Assisted Mathematics Drafting','source_contribution':'Stage A identified a structural mechanism: file churn, statement reshuffling, or code churn can imitate progress without adding load-bearing theorem content.','scope_mismatch':'The present paper needs the mechanism only as one gate lesson, not a full evaluation methodology.','independent_paper_rationale':'A separate paper could define theorem-content delta metrics, hard lints, benchmarks, and false-positive/false-negative analysis.','needed_to_split':['Dataset of edits','delta metric definitions','lint implementation','evaluation protocol','case taxonomy']},
  {'label':'thm:overlap-gate-blocks-route, thm:submitted-route-non-duplication, cor:overlap-gate-safe-lesson, thm:submitted-active-route-uniqueness-obstruction','location':'main.tex:5667, main.tex:5701, main.tex:5721, main.tex:4625','reason':'Route/submission governance is a strong workflow result but only one component of the finite-record safety architecture.','required_action':'Keep route governance as bounded case evidence in this paper; split only if building a full publication-route management system or policy study.','candidate_title':'Route-State and Overlap Gates for Automated Publication Pipelines','source_contribution':'Stage A isolated submitted-sibling paths, semantic-overlap ledgers, board state, and promotion records as necessary finite coordinates for avoiding duplicate or racing paper routes.','scope_mismatch':'The CICM presentation paper should not become a complete submission-governance framework.','independent_paper_rationale':'A route-governance paper could target tooling for research operations, conflict prevention, and route-state audits.','needed_to_split':['Route-state schema','overlap detection contract','submitted-sibling policy','board-state evidence','multi-project case study']}
 ],
 'irrelevant_or_remove': [
  {'label':'bibliography-local-support-notes:automath-publication-pipeline, auditable-pipeline-review-bundle','location':'references.bib:9, references.bib:17; submission_abstract.tex support notes','reason':'Local support-note bibliography entries are not archival publications and should not be mistaken for public supplemental upload or DOI-bearing evidence.','required_action':'Either keep them clearly marked as submission-local support notes or replace them with an actual archive locator after upload/archive instantiation.'},
  {'label':'audit:venue-submission-pack-gate, audit:command-run-boundary-inventory, thm:four-coordinate-submission-support-skeleton','location':'main.tex:5485, main.tex:8343, main.tex:9530','reason':'Highly package-specific venue/checklist/fixed-point machinery may distract in a compact presentation paper if placed in the main narrative rather than as supplement support.','required_action':'Keep in the technical supplement or review bundle; in the two-page primary article, cite only the summarized finite-record boundary and current no-receipt limitation.'},
  {'label':'prior-ledger:single-primitive-universality-memory','location':'Prompt prior research ledger only','reason':'The EML/Richardson/Zeckendorf/Hankel-Prony universality material has no role in this paper’s theorem chain.','required_action':'Remove any accidental mention from this article; retain only in separate hierarchy paper planning records.'}
 ],
 'naive_truncation_risks': [
  {'label':'thm:nested-package-states, cor:row-frozen-current-package-invariance, thm:post-inventory-support-coordinate-dichotomy, prop:post-inventory-freshness-obstruction','location':'main.tex:223, main.tex:4499, main.tex:8901, main.tex:9374','reason':'A row-frozen or nested finite package state is not invariant under later byte edits to theorem_inventory.json, theorem_inventory.md, logs, or digest rows.','required_action':'Use byte-level stable replay only for the exact recorded tuple; rerun inventory/verifier/digest steps after any edit.'},
  {'label':'lem:source-interface-extraction-correctness, thm:public-source-reachability-non-escalation, thm:source-interface-semantic-completeness-obstruction','location':'main.tex:487, main.tex:731, main.tex:823','reason':'A bounded pinned source snapshot can be naively truncated into a claim about current public repository reachability or semantic completeness.','required_action':'Descend through the stated evidence level: path-verified manual extraction, executable record comparison, or public byte-equality only when the corresponding coordinates are present.'},
  {'label':'thm:case-skeleton-partition, thm:artifact-suite-non-escalation, cor:current-case-behaviour-evidence-criterion','location':'main.tex:4980, main.tex:5836, main.tex:8286','reason':'Finite case snapshots and limitation rows can be misread as fresh dynamic artifact validation or global case-behaviour theorems.','required_action':'Keep case evidence at historical path-verified level; require source state, command, environment, exit code, log path, and outputs for any fresh rerun claim.'},
  {'label':'thm:deterministic-theorem-environment-extractor-boundary, thm:final-byte-extractor-inventory-inclusion, thm:theorem-inventory-proofchecker-obstruction','location':'main.tex:7412, main.tex:7520, main.tex:7590','reason':'Syntactic theorem-environment coverage can be naively truncated into proof correctness or completeness of mathematical obligations.','required_action':'State explicitly that extraction verifies only labelled environment coverage against the inventory, not proof semantics.'},
  {'label':'audit:fresh-venue-record-criterion, thm:venue-rule-freshness-non-escalation, cor:upload-time-venue-compliance-record-requirement','location':'main.tex:5268, main.tex:5311, main.tex:5398','reason':'A dated venue check can be treated as invariant across later website changes or upload-time state.','required_action':'Use an immediately-before-upload record, unchanged-rule bridge, or replacement live check for upload-time compliance claims.'},
  {'label':'thm:exact-inclusion-support-surface-realization, thm:review-bundle-archive-equivalence-criterion, thm:upload-or-archive-instantiation-boundary','location':'main.tex:6412, main.tex:6560, main.tex:6623','reason':'Exact local inclusion, public branch naming, and archive-equivalence can be conflated unless file-list, relative-path, digest, manifest, and locator conditions are all checked.','required_action':'Require support-surface descent through exact inclusion or archive-equivalent replacement; do not substitute prose references for byte-equality coordinates.'}
 ],
 'journal_style_gaps': [
  {'label':'all-formal-labels-count:136','location':'main.tex:174-9564; .direct_envs.json','reason':'The supplement contains 136 theorem-like environments for a CICM presentation-only/workshop route; this is auditable but visually over-theoremized and may obscure the software contribution.','required_action':'In the primary paper, expose only the central finite-record interface theorem, the evidence-axis map, the case-study table, and the no-escalation boundary; leave detailed fixed-point and digest machinery in supplement/review bundle.'},
  {'label':'prop:manual-theorem-inventory-boundary, audit:fresh-venue-record-criterion, audit:venue-submission-pack-gate, audit:submission-artifact-role-separation, audit:review-bundle-availability-condition, audit:case-snapshot-non-rerun-boundary, audit:command-run-boundary-inventory','location':'main.tex:7638, main.tex:5268, main.tex:5485, main.tex:5556, main.tex:8148, main.tex:8202, main.tex:8343','reason':'Several theorem-like environments use nonstandard label prefixes, including a theorem environment labeled prop:manual-theorem-inventory-boundary and proposition environments labeled audit:*; references are not broken, but style and automated tooling may be confused.','required_action':'Either relabel consistently in a later source-edit stage or document that audit:* labels are intentional audit records and that prop:manual-theorem-inventory-boundary is a theorem-environment boundary label.'},
  {'label':'references:bibliography-local-support','location':'references.bib; submission_abstract.tex bibliography section','reason':'The bibliography mixes standard public literature with submission-local support notes and a pinned repository entry; this is acceptable only if clearly distinguished from archival publications.','required_action':'Before submission, verify venue bibliography rules, public accessibility, DOI/arXiv/URL status, and whether local support notes should instead be cited as uploaded supplement files.'},
  {'label':'thm:presentation-route-five-interface-sharpness, thm:four-coordinate-submission-support-skeleton, cor:presentation-summary-non-escalation','location':'main.tex:8626, main.tex:9530, main.tex:8774','reason':'The final support-state theorem chain is precise but may read as self-referential package bookkeeping rather than a mathematical software result unless summarized carefully.','required_action':'Use a concise diagram or table in the presentation version and keep self-referential fixed-point details as audit supplement material.'},
  {'label':'submission-title-and-claim-scope','location':'submission_abstract.tex:10-45; main.tex:18-58','reason':'The phrase “theory compiler” can be overread as a theorem prover, Lean hammer, or automated acceptance system despite the manuscript’s negative boundaries.','required_action':'Keep subtitle and abstract language finite-record-only and under record-gate soundness; avoid marketing language that suggests automated theorem proving, AI proof evidence, or venue acceptance.'}
 ]
}

expected=['valid','in_scope_present','missing_in_scope_results','weak_in_scope_core_results','proof_gaps','supporting_appendix_or_background','out_of_scope_strong_results','split_candidates','irrelevant_or_remove','naive_truncation_risks','journal_style_gaps']
assert list(inventory.keys())==expected
label_text='\n'.join(str(row.get('label','')) for key,value in inventory.items() if isinstance(value,list) for row in value)
missing=[e['label'] for e in items if e['label'] not in label_text]
assert not missing, missing
root.joinpath('theorem_inventory.json').write_text(json.dumps(inventory,indent=2,ensure_ascii=False)+"\n",encoding='utf-8')
md=['# Stage A Theorem Inventory','', 'Scope: CICM presentation-only / mathematical software workshop route for `2026_auditable_theory_to_paper_pipeline`.', '', 'This inventory classifies theorem-like and proof-interface material in `main.tex`, `submission_abstract.tex`, `references.bib`, and `review_bundle/`. It is a Stage A review artifact, not a proof checker.', '']
for key in expected:
    if key=='valid':
        md += ['## valid', f'- `{inventory[key]}`', '']
        continue
    md.append('## '+key.replace('_',' ').title())
    rows=inventory[key]
    if not rows:
        md.append('- No items classified in this category.')
    for row in rows:
        md.append(f"- **Label:** `{row['label']}`")
        md.append(f"  - Location: `{row['location']}`")
        md.append(f"  - Reason: {row['reason']}")
        md.append(f"  - Required action: {row['required_action']}")
        for extra in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale','needed_to_split']:
            if extra in row:
                val=row[extra]
                if isinstance(val,list):
                    val=', '.join(val)
                md.append(f"  - {extra}: {val}")
    md.append('')
root.joinpath('theorem_inventory.md').write_text('\n'.join(md)+"\n",encoding='utf-8')
print('wrote theorem_inventory.json and theorem_inventory.md')
print('formal labels covered',len(items))
