import json
from pathlib import Path

inventory = {
  "valid": True,
  "in_scope_present": [
    {"label":"group:package-shape-and-acceptance-state (prop:final-package-shape-convention; thm:nested-package-states)","location":"main.tex:176; main.tex:225","reason":"Defines the current presentation package shape and the finite row-frozen acceptance-state nesting needed to add the theorem-inventory row without changing earlier accepted rows.","required_action":"Keep as package-local record claims; after the inventory files are written, refresh any support logs before making current fixed-point claims."},
    {"label":"group:architecture-axis-boundary (def:architecture-axis-map; prop:architecture-axis-non-escalation)","location":"main.tex:290; main.tex:329","reason":"Core architecture spine separating BEDC source theory, Lean/formal verification, finite witnesses, advisory agents, and automath publication compilation.","required_action":"Retain in the main paper; use it as the controlling vocabulary for all evidence-level non-escalation claims."},
    {"label":"group:bounded-source-interface (lem:source-interface-extraction-correctness through prop:source-interface-evidence-level-separation)","location":"main.tex:505-899","reason":"Supplies the path-verified imported-source interface and its limits, satisfying the scope rule that load-bearing source claims have source paths and evidence-level qualifiers.","required_action":"Keep the manual/path-verified qualifier explicit; do not let these results imply semantic completeness of the source theory or public reachability unless a separate record is added."},
    {"label":"group:operational-record-interface (def:operational-acceptance-interface through prop:finite-certificate-schema-verifier)","location":"main.tex:990-1311","reason":"Defines the finite record surface, record-gate soundness interface, stronger-reading preorder, certificate schema, and finite verifier used by the central theorem chain.","required_action":"Retain as the formal interface; keep actual gate-implementation correctness outside this schema unless independently logged and checked."},
    {"label":"group:executable-record-normal-forms (thm:verifier-input-output-contract through thm:executable-certificate-construction-invariant)","location":"main.tex:1377-2094","reason":"Establishes schema-relative acceptance, finite-coordinate determination, machine-readable certificate rows, and the negative boundary between record acceptance and implementation soundness.","required_action":"Keep as in-scope proof interface for the software-workshop contribution; cite exact schema and verifier logs when claiming current execution."},
    {"label":"group:claim-dispatch-and-extension-budget (prop:claim-kind-dispatch through prop:publication-safety-dependency-normal-form)","location":"main.tex:2162-2688","reason":"Provides deterministic claim-kind dispatch, obstruction to mixed unsupported readings, finite extension budgets, and the certificate-calculus spine used by the main publication-safety theorem.","required_action":"Retain the finite-budget language; avoid rephrasing these as proof of gate semantics or complete artifact validation."},
    {"label":"group:promotion-main-safety-chain (prop:gate-interface-separation through thm:finite-record-certificate-rigidity)","location":"main.tex:2755-3159","reason":"Contains the central in-scope theorem: under record-gate soundness, accepted load-bearing claims receive finite certificates, while AI advice, scheduler selection, and human promotion remain distinct.","required_action":"Make this the visible theorem spine of the presentation version; preserve the conditional hypothesis and the finite-record-only conclusion."},
    {"label":"group:boundary-axis-current-package-exactness (thm:boundary-axis-non-escalation-exactness through thm:external-interface-projection-no-free-upgrade)","location":"main.tex:3241-4190","reason":"Sharpens the main theorem into non-gluing, maximality, current-package, and positive-extension criteria for stronger readings.","required_action":"Retain as supplement-level support; in the short paper cite only the strongest normal form and obstruction needed for the central claim."},
    {"label":"group:current-package-ledger-audit (prop:current-package-acceptance-certificate-ledger through cor:current-package-path-verified-instantiation)","location":"main.tex:4290-4914","reason":"Classifies the concrete package ledger and current path-verified instantiation while isolating semantic and command-run upgrades.","required_action":"Keep all current-package wording tied to exact source state, row set, and log freshness; do not claim current semantic validation from these rows."},
    {"label":"group:gate-summary-and-case-witnesses (lem:gate-witness-criterion through thm:case-witness-skeleton-rigidity; audit:review-bundle-availability-condition through cor:current-case-behaviour-evidence-criterion)","location":"main.tex:5017-5229; main.tex:8252-8390","reason":"Implements the scope requirement that each case study state the gate, observed issue, and safe lesson, with case rows treated as historical/path-verified evidence rather than reruns.","required_action":"Retain the case rows only as evidence-discipline examples; avoid organizing the short article around individual rejected papers or route names."},
    {"label":"group:venue-and-submission-gates (audit:fresh-venue-record-criterion through audit:submission-artifact-role-separation)","location":"main.tex:5372-5660","reason":"Separates dated venue/bibliography readiness, upload-time compliance, and artifact roles from mathematical or gate-soundness claims.","required_action":"Refresh venue and bibliography checks near actual submission; state historical logs as historical if not freshly rerun."},
    {"label":"group:formal-source-and-finite-witness-boundaries (prop:formal-source-gate-instantiation through prop:primary-supplement-interface-map)","location":"main.tex:5752-6267","reason":"Covers formal-source promotion, evidence-level overclaiming, finite-witness manifest rows, artifact semantic-validity boundaries, and primary-to-supplement claim mapping.","required_action":"Keep finite-witness evidence at manifest/evaluator-row strength unless the package adds dynamic artifact-validation logs."},
    {"label":"group:support-surface-archive-upload-normal-forms (thm:exact-inclusion-support-surface-realization through prop:primary-architectural-fallback-without-external-support)","location":"main.tex:6516-7450","reason":"Gives the exact-inclusion, archive-equivalence, upload, digest, and fallback boundaries for bundle-backed claims.","required_action":"Before submission, either upload/archive the support surface with byte-equality evidence or leave all bundle-backed claims local/path-verified."},
    {"label":"group:theorem-inventory-and-extractor-boundaries (thm:deterministic-theorem-environment-extractor-boundary through cor:current-local-support-normal-form)","location":"main.tex:7516-8197","reason":"States the syntactic theorem-environment extraction and inventory-obligation interface that this Stage A inventory is meant to instantiate.","required_action":"Treat extraction as syntactic coverage only; after this file write, rerun the extractor/verifiers/digest sequence before citing current post-inventory logs."},
    {"label":"group:command-run-and-post-inventory-fixed-point (audit:command-run-boundary-inventory through thm:four-coordinate-submission-support-skeleton)","location":"main.tex:8447-9805","reason":"Closes the in-scope command-result boundary, support-coordinate fixed-point, and final four-coordinate skeleton for the presentation package.","required_action":"Use only conditionally until the inventory bytes and all post-inventory logs are regenerated in the order specified by the manuscript."}
  ],
  "missing_in_scope_results": [],
  "weak_in_scope_core_results": [
    {"label":"thm:publication-safety-interface","location":"main.tex:2948","reason":"The central theorem is strong as an interface theorem but weak as an empirical workflow theorem because record-gate soundness is assumed rather than proved for the actual gate implementations.","required_action":"Keep the statement explicitly conditional; if the article wants an implementation-soundness claim, add separate source paths, command logs, environments, exit codes, and proof obligations for the gate programs."},
    {"label":"lem:source-interface-extraction-correctness; thm:bounded-source-interface-maximality","location":"main.tex:505; main.tex:684","reason":"The imported BEDC/newmath interface is manual/path-verified and bounded; it is not a semantic import of the full source theorem statements.","required_action":"Retain the bounded-source-interface wording and ensure all downstream uses cite only the recorded line ranges, summaries, and evidence-level fields."},
    {"label":"thm:finite-witness-manifest-record-interface; cor:artifact-semantic-validity-boundary","location":"main.tex:5935; main.tex:6055","reason":"Finite witness rows support manifest/evaluator-record evidence, but do not establish dynamic artifact semantics or evaluator correctness.","required_action":"Keep these as finite-record claims; add dynamic validation only through a separate logged artifact-validation gate."},
    {"label":"thm:post-inventory-package-fixed-point; thm:current-inventory-artifact-realization; thm:current-command-result-closure","location":"main.tex:9221; main.tex:9357; main.tex:9449","reason":"The current fixed-point conclusions are only as strong as the post-write rerun order; any edit to inventory bytes makes older extractor, verifier, and digest logs stale.","required_action":"After accepting this inventory, rerun the specified extractor/verifier/final-digest sequence and cite the new logs before asserting a current fixed point."}
  ],
  "proof_gaps": [
    {"label":"literal-label-token-gap","location":"main.tex:660; main.tex:7589","reason":"The manuscript contains literal tokens of the form \\path{\\label{...}}. LaTeX may treat these as path text, but naive theorem-environment extractors can misread them as duplicate labels and produce a spurious duplicate label named '...'.","required_action":"Escape or rephrase literal label examples, or make the extractor demonstrably ignore verbatim/path contexts before relying on exact label inventory."},
    {"label":"prop:manual-theorem-inventory-boundary","location":"main.tex:7742","reason":"The environment is a theorem but its label prefix is 'prop:', which is not mathematically fatal but weakens the claimed deterministic theorem-inventory interface and journal readability.","required_action":"Either relabel consistently in a later manuscript-edit stage or record the prefix mismatch as an accepted syntactic exception in the inventory verifier."},
    {"label":"post-inventory-log-freshness-interface","location":"main.tex:7277; main.tex:7309; main.tex:9221-9805; review_bundle/*.log","reason":"The current-package support theorems require theorem_inventory.json and theorem_inventory.md to exist before extractor, verifier, venue, and digest logs are regenerated; writing this inventory changes the source state and can stale earlier logs.","required_action":"Run the post-inventory command sequence after this write, regenerate FINAL_DIGESTS_SHA256.md, and update any command-result references to the resulting source state."},
    {"label":"review-bundle-external-instantiation-interface","location":"main.tex:6352-7450; references.bib:13-28","reason":"The manuscript correctly distinguishes local/path-verified review_bundle evidence from external upload or archive-equivalent support, but no external receipt or byte-equality archive record is present in the local files inspected.","required_action":"Before submission, either supply an upload/archive-equivalence record or keep every review-bundle-backed claim explicitly local/path-verified."},
    {"label":"venue-bibliography-live-check-interface","location":"main.tex:5372-5589; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-08.log","reason":"Venue and bibliography claims are time-sensitive; the manuscript has dated logs, but those logs are valid only as dated-readiness records and not as future upload-time compliance.","required_action":"Repeat live venue and bibliography verification close to actual submission, or phrase all such evidence as historical dated readiness."}
  ],
  "supporting_appendix_or_background": [
    {"label":"citation:deMouraKADR2015Lean","location":"references.bib:31","reason":"Classical/background system-description citation for Lean; it supports context about proof assistants but is not a new result of this paper.","required_action":"Keep as background citation and avoid using it as evidence for this package's formal-source freshness."},
    {"label":"citation:YangEtAl2023LeanDojo","location":"references.bib:43","reason":"Background citation for retrieval-augmented formal-proving infrastructure adjacent to the paper's advisory-agent setting.","required_action":"Use only for literature positioning; do not make LeanDojo-like method claims."},
    {"label":"citation:JiangEtAl2023DraftSketchProve","location":"references.bib:52","reason":"Background citation for informal-to-formal guidance, relevant to the distinction between AI proposals and proof evidence.","required_action":"Keep as context; do not present Draft--Sketch--Prove as part of the audited implementation unless separately evidenced."},
    {"label":"citation:BlanchetteHMN2015AFP","location":"references.bib:62","reason":"Background citation for formal-proof archive reproducibility and mining; supports context rather than a new theorem chain.","required_action":"Keep as supporting literature and verify venue/bibliographic metadata before final submission."},
    {"label":"citation:bedc-newmath-source","location":"references.bib:1","reason":"Source-repository locator for the BEDC/newmath workspace; it supports pinned-source path claims but is not by itself a public-reachability or semantic-correctness certificate.","required_action":"Use together with pinned commit, source path, and review-bundle/line-range records; add public byte-equality logs if stronger reachability is claimed."},
    {"label":"citation:automath-publication-pipeline; citation:auditable-pipeline-review-bundle","location":"references.bib:11; references.bib:20","reason":"Submission-local support notes for the automath pipeline and review bundle; they are artifact/context references rather than external archival publications.","required_action":"Do not cite these as archival or accepted publications unless an archive-equivalent support surface is added."}
  ],
  "out_of_scope_strong_results": [
    {"label":"prior-ledger:single-primitive-universality-hierarchy","location":"Prior Research Ledger Context; not in main.tex","reason":"The L0/L1/L2 expression/protocol/certificate universality hierarchy is mathematically substantive but unrelated to the auditable theory-to-paper pipeline contribution.","required_action":"Do not import into this article except as background memory for provenance; route to its own paper pipeline.","candidate_title":"Single-Primitive Universality Hierarchy and Certificate Separation","source_contribution":"Earlier Stage A reasoning isolated expression universality, protocol universality, finite-fiber certificate universality, Zeckendorf protocol arithmetic, Hankel-Prony certificates, finite-state strictness, and Richardson-interface conditionality.","scope_mismatch":"The present paper is a CICM-style software/workflow architecture paper about record-gated publication claims, not a mathematics paper on universality, Zeckendorf arithmetic, or certificate separations.","independent_paper_rationale":"The hierarchy has its own definitions, strictness mechanisms, proof obligations, and journal target independent of the pipeline architecture.","needed_to_split":["Keep the hierarchy source directory as the mathematical source of truth","Preserve the conditional printed-root versus unconditional replacement-triple distinction","Prepare a separate theorem inventory and proof-gap ledger for the universality paper"]},
    {"label":"generalized-record-gate-calculus","location":"main.tex:990-4190","reason":"The manuscript develops a broad finite-record certificate calculus whose general form could exceed the specific presentation-package case study.","required_action":"Use only the package-local clauses needed for this article; split generalized axiomatization if it becomes the dominant contribution.","candidate_title":"A Finite-Record Calculus for Publication-Safety Certificates","source_contribution":"Stage A inspection identifies reusable notions of record-gate soundness, stronger-reading preorder, finite-coordinate determination, non-gluing, bad-subrecord extraction, and extension-budget normal form.","scope_mismatch":"A general calculus paper would require abstraction, examples, and metatheory beyond the current BEDC/automath workflow report.","independent_paper_rationale":"The calculus could be useful outside this one pipeline, but would need cleaner definitions and independent implementation examples.","needed_to_split":["Extract package-independent definitions","Prove nontrivial metatheorems outside local record enumeration","Add at least one independent workflow instance"]}
  ],
  "split_candidates": [
    {"label":"split:archive-equivalent-support-surfaces","location":"main.tex:6516-7450; main.tex:9051-9805","reason":"The exact-inclusion, archive-equivalence, digest-refresh, and post-inventory fixed-point machinery is more detailed than needed for a compact presentation paper.","required_action":"Keep only the boundary result in the short article; consider a separate reproducible-artifact note for the full support-surface calculus.","candidate_title":"Archive-Equivalent Support Surfaces for Auditable Research Artifacts","source_contribution":"Stage A identified a coherent finite-byte/digest normal form for local bundle evidence, external archive replacement, upload receipts, and post-edit rerun freshness.","scope_mismatch":"The current article needs the boundary but not the full fixed-point taxonomy of support-coordinate refreshes.","independent_paper_rationale":"Artifact packaging, archive equivalence, and byte-level replay criteria are reusable for reproducibility tooling beyond this pipeline.","needed_to_split":["Define archive-equivalence independently of this manuscript","Add examples from multiple bundles","Provide executable verifier commands and stable artifact identifiers"]},
    {"label":"split:theorem-inventory-extractor-tooling","location":"main.tex:7516-8197; review_bundle/extract_theorem_environments.py","reason":"The deterministic theorem-environment extractor and proofchecker-obstruction interface is a tool contribution adjacent to, but separable from, the pipeline architecture paper.","required_action":"For this article, use it as support evidence only; split if the extractor's correctness and limitations become a standalone technical focus.","candidate_title":"Syntactic Theorem-Inventory Extraction for Auditable Manuscripts","source_contribution":"Stage A identified a finite syntactic coverage interface, non-gluing limitation, proofchecker obstruction, and post-inventory digest closure protocol.","scope_mismatch":"The current paper's central claim is architecture-level record gating, not a complete TeX parser or proof obligation checker.","independent_paper_rationale":"A robust extractor with verbatim/path handling, label normalization, and reproducible logs could be a reusable mathematical-software artifact.","needed_to_split":["Specify the TeX subset precisely","Handle literal label tokens and verbatim contexts","Compare extractor output against LaTeX/aux labels and manuscript environments"]},
    {"label":"split:case-study-governance-taxonomy","location":"main.tex:5117-5321; review_bundle/case_snapshots/","reason":"The four case studies encode a governance taxonomy of intake isolation, overlap blocking, fake-extension rejection, and artifact evidence boundaries.","required_action":"Use only short illustrative rows here; split a richer empirical/governance account if detailed incidents, timelines, or route names are needed.","candidate_title":"Governance Failure Modes in AI-Assisted Formal-Mathematics Publication Pipelines","source_contribution":"Stage A identifies the structural mechanisms behind bad examples rather than merely listing incidents: ungated intake promotion, overlap/submission collision, theorem-looking fake extension, and finite-witness overclaiming.","scope_mismatch":"The present article should not be organized around individual rejected papers or local route names.","independent_paper_rationale":"A separate case-study paper could present richer qualitative evidence, incident timelines, and operational lessons.","needed_to_split":["Anonymize or stabilize case identifiers","Add independent audit logs for each case","Separate governance lessons from the finite-record theorem chain"]}
  ],
  "irrelevant_or_remove": [
    {"label":"literal \\label examples inside \\path","location":"main.tex:660; main.tex:7589","reason":"These are explanatory tokens, not mathematical content, but they create a duplicate-label hazard for simple extractors.","required_action":"Remove, escape, or rewrite the examples in a later manuscript-edit stage."},
    {"label":"redundant post-inventory current-state variants","location":"main.tex:9051-9805","reason":"Many late theorems and corollaries restate nearby fixed-point, freshness, and support-coordinate boundaries; useful for audit bookkeeping but too repetitive for the presentation narrative.","required_action":"Keep the formal support in the supplement if needed, but in the short paper cite one normal form, one dichotomy, and one current-absence boundary."},
    {"label":"submission-local bibliography entries as ordinary literature","location":"references.bib:11-28","reason":"The automath pipeline and review-bundle entries are local support notes, not conventional peer-reviewed or archival references.","required_action":"Do not present them as ordinary literature; move them to artifact metadata or supplement pointers if the venue format permits."}
  ],
  "naive_truncation_risks": [
    {"label":"risk:byte-digest-fixed-point-staleness","location":"main.tex:7277-7378; main.tex:9221-9805","reason":"A finite digest tuple is not invariant under later edits to theorem_inventory.json, theorem_inventory.md, logs, or review_bundle manifests.","required_action":"Regenerate logs and final digests after the last relevant byte change; treat older records as historical only."},
    {"label":"risk:path-verified-source-summary-as-semantic-import","location":"main.tex:505-899","reason":"Line-range summaries and source snapshots do not automatically descend to full semantic source-theory correctness or complete BEDC exposition.","required_action":"Keep imported source claims bounded to recorded fields and cite the source path for every load-bearing use."},
    {"label":"risk:manifest-row-as-artifact-semantics","location":"main.tex:5935-6055","reason":"Finite witness manifest/evaluator rows can be mistaken for dynamic artifact validation or evaluator semantic correctness.","required_action":"State manifest evidence separately from artifact semantics and require extra validation logs for stronger claims."},
    {"label":"risk:local-review-bundle-as-public-archive","location":"main.tex:6352-7224; references.bib:20-28","reason":"A local review_bundle directory is not automatically an uploaded supplement, public branch byte-equality record, or archive-equivalent support surface.","required_action":"Add upload receipt or archive-equivalence records before claiming external support; otherwise keep local/path-verified qualifiers."},
    {"label":"risk:human-promotion-as-daemon-active-track-equivalence","location":"main.tex:2779; main.tex:5819","reason":"Human promotion and daemon-visible active paper tracks are separate workflow states and cannot be truncated to a single 'active' label.","required_action":"Preserve the two-state distinction in every case-study and pipeline claim."},
    {"label":"risk:dated-venue-readiness-as-upload-time-compliance","location":"main.tex:5372-5589","reason":"A dated venue/bibliography check can go stale and does not automatically prove future submission-time compliance.","required_action":"Rerun live checks at upload time or phrase evidence as historical dated readiness."},
    {"label":"risk:syntactic-theorem-inventory-as-proof-checking","location":"main.tex:7516-7794","reason":"The theorem-environment inventory checks labels and syntactic coverage, not mathematical proof correctness.","required_action":"Keep proofchecker-obstruction language explicit and avoid calling the inventory a theorem prover or proof certificate."}
  ],
  "journal_style_gaps": [
    {"label":"presentation-length-and-spine","location":"main.tex:1-9973; submission_abstract.tex:1-193","reason":"The technical supplement contains 139 formal environments and many package-local normal forms, far beyond a compact CICM presentation narrative.","required_action":"For the presentation paper, foreground the architecture-axis definition, record-gate interface, main publication-safety theorem, and four case-study rows; move dense normal forms to supplement."},
    {"label":"local-path-and-current-state-language","location":"main.tex throughout; references.bib:1-28","reason":"Many claims use local paths, current source-state language, and dated logs; this is auditable but awkward for a venue-facing paper unless support artifacts are submitted or archived.","required_action":"Replace local-only references with submitted supplement paths, stable archive locators, or explicitly local/path-verified phrasing."},
    {"label":"theoremization-of-bookkeeping","location":"main.tex:9051-9805 and related normal-form blocks","reason":"Bookkeeping facts are often stated as theorems, which may obscure the central software contribution for workshop reviewers.","required_action":"Consolidate repetitive bookkeeping into definitions, tables, or audit lemmas while preserving all load-bearing proof interfaces in the supplement."},
    {"label":"label-prefix-consistency","location":"main.tex:7742","reason":"A theorem labeled with a 'prop:' prefix weakens navigability and machine-readable convention consistency.","required_action":"Normalize label prefixes in a manuscript-edit stage or document the exception."},
    {"label":"bibliography-and-venue-freshness","location":"references.bib; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-08.log","reason":"The target venue route and some bibliography metadata are time-sensitive and need live verification near submission.","required_action":"Run a fresh venue/bibliography check at final packaging and cite it only at the evidence level supported by its log."}
  ]
}

expected = ["valid","in_scope_present","missing_in_scope_results","weak_in_scope_core_results","proof_gaps","supporting_appendix_or_background","out_of_scope_strong_results","split_candidates","irrelevant_or_remove","naive_truncation_risks","journal_style_gaps"]
assert list(inventory.keys()) == expected
Path('theorem_inventory.json').write_text(json.dumps(inventory, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

lines = ['# Theorem Inventory', '', 'Stage A theorem inventory for `2026_auditable_theory_to_paper_pipeline`.', '', 'This file mirrors `theorem_inventory.json` in human-readable form.']
for key, value in inventory.items():
    if key == 'valid':
        lines += ['', f'## {key}', '', f'`{str(value).lower()}`']
        continue
    lines += ['', f'## {key.replace("_", " ").title()}', '']
    if not value:
        lines.append('- None recorded.')
        continue
    for item in value:
        lines.append(f"- `{item['label']}` — {item['location']}")
        lines.append(f"  - Reason: {item['reason']}")
        lines.append(f"  - Required action: {item['required_action']}")
        for extra in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale']:
            if extra in item:
                lines.append(f"  - {extra.replace('_',' ').title()}: {item[extra]}")
        if 'needed_to_split' in item:
            lines.append('  - Needed to split: ' + '; '.join(item['needed_to_split']))
Path('theorem_inventory.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('wrote theorem_inventory.json and theorem_inventory.md')
