import json, pathlib
root=pathlib.Path('.')
envs=json.loads(root.joinpath('.stage_a_current_envs.json').read_text(encoding='utf-8'))

def labs(pred): return [r['label'] for r in envs if r.get('label') and pred(r)]
def join(xs): return '; '.join(xs)
def item(label,loc,reason,action): return {"label":label,"location":loc,"reason":reason,"required_action":action}
def split(label,loc,reason,action,title,src,mis,rat,need):
    d=item(label,loc,reason,action); d.update({"candidate_title":title,"source_contribution":src,"scope_mismatch":mis,"independent_paper_rationale":rat,"needed_to_split":need}); return d

root_obj={"valid":True,"in_scope_present":[],"missing_in_scope_results":[],"weak_in_scope_core_results":[],"proof_gaps":[],"supporting_appendix_or_background":[],"out_of_scope_strong_results":[],"split_candidates":[],"irrelevant_or_remove":[],"naive_truncation_risks":[],"journal_style_gaps":[]}
R=root_obj
# In-scope groups cover every current theorem/proposition/lemma/corollary/definition/auditrecord label.
groups=[
("package-scope", lambda r:r['start']<270, "main.tex:177-261", "opening package-shape and six-row/seven-row state boundary"),
("architecture", lambda r:r['section']=='section: Architecture', "main.tex:285-1042", "five evidence axes, non-escalation, compressed interface, and bounded imported-source interface"),
("abstract-finite-record-interface", lambda r:r['section']=='subsection: Abstract finite-record interface', "main.tex:1145-4665", "operational acceptance, record-gate soundness interface, certificate schema, verifier normal forms, finite-coordinate obstructions, publication-safety interface, maximality, and no-free-upgrade theorems"),
("current-package-instantiation", lambda r:r['section'] in ['subsection: Primary-claim inventory audit','subsection: Current-package instantiation'], "main.tex:4706-5400", "current-package ledger, row-frozen certificate exactness, semantic non-escalation, and named positive-coordinate classification"),
("case-study-witness-protocol", lambda r:5472<=r['start']<=5730, "main.tex:5472-5715", "gate/issue/lesson witness protocol for the four historical case studies"),
("primary-supplement-interface", lambda r:5827<=r['start']<=6964, "main.tex:5827-6991", "venue freshness, artifact role separation, formal-source gate, evidence-level overclaim obstruction, finite-witness interface, artifact-semantic boundary, and primary-claim inventory mapping"),
("auditrecord-support-interfaces", lambda r:r['env']=='auditrecord', "main.tex:7075; main.tex:7123; main.tex:7149; main.tex:7439; main.tex:7555", "load-bearing auditrecord interfaces for archive equivalence, exact bundle convention, support-mode witness, immutable package state, and mutable-checkout boundary"),
("support-surface-calculus", lambda r:7211<=r['start']<=8143, "main.tex:7211-8179", "exact-inclusion support, public branch locator, upload/archive boundary, digest refresh, submission-support rigidity, and fallback without external support"),
("theorem-inventory-extractor", lambda r:8209<=r['start']<=8905, "main.tex:8209-8938", "deterministic syntactic theorem-environment extraction, inventory inclusion, proofchecker obstruction, digest closure, post-inventory realization, and seven-row theorem-obligation ledger integration"),
("case-evidence-boundary", lambda r:8960<=r['start']<=9098, "main.tex:8960-9122", "review-bundle availability and non-rerun case-evidence boundary"),
("command-run-boundary", lambda r:r['section']=='subsection: Command-run boundary', "main.tex:9158-11496", "command-boundary inventory, post-edit rerun metadata, support-coordinate fixed points, current command-result closure, no-free-upgrade closure, terminal five-coordinate closure, Stage-A2 issue discharge, and final support-coordinate normal form")]
for name,pred,loc,reason in groups:
    R['in_scope_present'].append(item(join(labs(pred)),loc,reason,"Retain as in-scope finite-record support; keep all stated non-escalation and conditionality boundaries explicit."))
R['in_scope_present'].append(item("primary:submission_abstract_methodological_claim; primary:submission_abstract_two_instances; primary:submission_abstract_presentation_artifact","submission_abstract.tex:50-112","primary presentation artifact states the portable auto-formalization method across source theory, formalization, finite evidence, agent activity, and publication state","Keep as the presentation-facing contribution and keep main.tex subordinate technical support."))

R['missing_in_scope_results'] += [
item("missing:post-inventory-rerun-after-current-inventory-bytes","main.tex:10000; main.tex:10136; main.tex:10228; review_bundle/theorem_environment_extraction_run.log","theorem_inventory.json was absent at the start of this Stage A run, while current/post-inventory realization claims require logs and digests generated after the final inventory bytes","After this inventory write, rerun the theorem extractor and retained finite-record verifiers, capture logs, and regenerate digest rows."),
item("missing:external-support-coordinate","main.tex:7763; main.tex:7786; main.tex:10588; main.tex:11196","external submitted support, upload receipt, or archive-equivalent byte-equality locator is intentionally absent","Keep the primary-only/local-support boundary or add exact upload/archive evidence with digest binding."),
item("missing:fresh-formal-source-rebuild-and-axiom-audit","main.tex:6217; main.tex:6284; submission_abstract.tex:110-112","source-interface evidence is path-verified and line-range bounded, not a fresh Lean/BEDC rebuild or axiom audit","Add command, commit, environment, exit code, log path, and axiom/assumption audit records if a fresh formal-verification claim is desired."),
item("missing:dynamic-artifact-validation-rerun","main.tex:6400; main.tex:6520; main.tex:6559; submission_abstract.tex:110-112","finite witness rows are manifest/evaluator-record claims only and do not prove dynamic artifact semantics","Add an artifact-validation gate and rerun log if semantic artifact validity is claimed."),
item("missing:gate-implementation-soundness-instantiation","main.tex:1326; main.tex:2070; main.tex:2490; main.tex:4471; main.tex:4606","record-gate soundness remains an external hypothesis rather than a proof of concrete script or daemon correctness","Keep publication safety conditional or add verified implementation contracts for every assigned gate.")]
R['weak_in_scope_core_results'] += [
item("thm:publication-safety-interface; prop:publication-safety-maximality; cor:publication-safety-current-package-instance","main.tex:3273; main.tex:4331; main.tex:4375","central safety theorem is conditional and finite-record-only, weaker than end-to-end workflow correctness or formal verification","State this limitation prominently and do not strengthen without the missing upgrade coordinates."),
item("lem:source-interface-extraction-correctness; thm:bounded-source-interface-maximality; thm:source-interface-semantic-completeness-obstruction","main.tex:598; main.tex:777; main.tex:968","imported newmath/BEDC interface is complete only for selected bounded line-range records and does not prove semantic truth of imported labels","Keep as path-verified support; add rebuild/semantic extraction evidence for stronger claims."),
item("thm:finite-witness-manifest-record-interface; prop:artifact-validation-gate-unique-semantic-upgrade; cor:artifact-semantic-validity-boundary","main.tex:6400; main.tex:6520; main.tex:6559","finite witness rows give manifest-bounded evidence but not artifact semantic validity","Keep manifest-bounded language or add a separate artifact validation suite."),
item("thm:deterministic-theorem-environment-extractor-boundary; thm:extractor-domain-exactness-non-gluing; thm:theorem-inventory-proofchecker-obstruction; prop:manual-theorem-inventory-boundary","main.tex:8209; main.tex:8256; main.tex:8387; main.tex:8435","the inventory machinery proves syntactic label coverage only, not statement semantics or proof correctness","Use only as inventory coverage, not as a proof checker."),
item("prop:path-complete-case-witnesses; thm:case-witness-skeleton-rigidity; audit:case-snapshot-non-rerun-boundary","main.tex:5497; main.tex:5684; main.tex:9014","case studies are path-complete historical snapshots, not current rerun demonstrations","Keep the gate/issue/lesson framing and avoid claiming fresh case behavior.")]
R['proof_gaps'] += [
item("gap:stale-or-absent-theorem-inventory-artifact","theorem_inventory.json; review_bundle/theorem_environment_extraction_run.log; main.tex:8209-8317","the inventory file did not exist before this Stage A write although stale logs and manuscript statements discuss it as an existing support coordinate","Use this new inventory, rerun extraction, and refresh logs/digests before relying on current realization claims."),
item("gap:stale-source-hashes-in-current-check-logs",".current_source_interface_check.log; .current_extract_check_for_inventory.log; review_bundle/theorem_environment_extraction_run.log","local check logs record older main.tex/theorem_inventory hashes; current main.tex SHA-256 is BA297186E7C3ED6B8C753861011453BD776A76FDFAA3748AB7585095C1C05E97","Regenerate verifier logs from final bytes or phrase them as historical."),
item("gap:label-token-inside-path-example","main.tex:753; main.tex:8282","literal \\label{...} tokens inside \\path examples create duplicate label-looking strings for naive scanners","Escape or rephrase the examples, or require TeX-aware scanners that ignore verbatim/path arguments."),
item("prop:manual-theorem-inventory-boundary","main.tex:8435","a theorem environment carries a prop: label prefix, creating environment/label-kind mismatch","Rename consistently later or record that prefix cannot be used as the sole classifier."),
item("audit:review-bundle-archive-equivalence; audit:exact-bundle-or-final-digest; prop:exact-review-bundle-upload-witness; prop:final-immutable-package-state-certificate; prop:mutable-checkout-observation-boundary","main.tex:7075; main.tex:7123; main.tex:7149; main.tex:7439; main.tex:7555","load-bearing auditrecord environments are outside the extractor's theorem-like domain","Extend extraction to auditrecord or maintain a separate auditrecord coverage check."),
item("gap:record-gate-soundness-unproved-external-hypothesis","main.tex:1326; main.tex:1358; main.tex:3273","publication safety depends on external record-gate soundness; the paper proves interface exactness, not real gate implementation soundness","Keep theorem conditional or add implementation-soundness proofs."),
item("gap:review-bundle-path-locality","review_bundle/; main.tex:7211-7917","many support claims depend on local review_bundle paths; without upload/archive locator an external reader cannot resolve the full support surface","Attach/archive the bundle with byte equality or mark claims local/path-verified only.")]
R['supporting_appendix_or_background'] += [
item("cite:deMouraKADR2015Lean; cite:YangEtAl2023LeanDojo; cite:JiangEtAl2023DraftSketchProve; cite:BlanchetteHMN2015AFP","references.bib:9-46; submission_abstract.tex:30-44; submission_abstract.tex:94-103","background references for Lean, LLM-guided proving, retrieval-augmented theorem proving, and formal proof archives","Use only as literature support and verify bibliographic metadata before submission."),
item("cite:bedc-newmath-source; source_interface_record:16-imported-labels","references.bib:1-7; main.tex:487-615; review_bundle/source_interface_record.json","BEDC/newmath source workspace and sixteen imported labels are supporting source-interface evidence, not self-contained theorem proofs","Keep source paths, commit, snapshot digest, and line ranges."),
item("support:primary_claim_inventory; support:certificate_schema; support:current_package_pass_records; support:submission_interface_map","review_bundle/primary_claim_inventory.json; review_bundle/certificate_schema.json; review_bundle/current_package_pass_records.json; review_bundle/submission_interface_map.json","machine-readable records support the finite-record certificate calculus but not mathematical truth, implementation soundness, or venue acceptance","Keep as artifact support with logs and digest bindings."),
item("support:case_snapshots","review_bundle/case_snapshots/; main.tex:5572-5730; main.tex:8960-9098","case snapshots support the four examples at historical/path-verified level","Retain as evidence bundle material and avoid dynamic-behavior claims.")]
R['out_of_scope_strong_results'] += [
split("out:implementation-sound-gate-daemon","main.tex:2070; main.tex:2490; main.tex:2667; main.tex:4471; main.tex:4606","concrete soundness of automath gates, daemon, scheduler, and scripts is stronger than the paper's finite-record claim","Do not force into this supplement without verified implementation contracts.","Verified Gate Implementations for Auditable AI-Assisted Formal Mathematics Pipelines","Stage A identified a six-coordinate separation between record-level acceptance and concrete implementation soundness.","Present article proves schema-relative finite-record safety under a record-gate-soundness premise.","A verified-gates paper could provide executable semantics, tests, and proofs for the machinery.",["gate specifications","implementation model","replayable logs","soundness tests or proofs","artifact archive"]),
split("out:fresh-bedc-formal-source-verification","main.tex:598-1042; main.tex:6217-6325; submission_abstract.tex:60-67","fresh Lean/BEDC rebuild, axiom audit, and semantic source extraction are stronger than bounded source-interface evidence","Keep out unless formal-source verification budget is added.","A Fresh Formal-Source Audit of BEDC/newmath for AI-Assisted Theory Discovery","Stage A isolated the gap between line-range source records and semantic formal-source verification.","Current route is a methodology presentation, not a complete BEDC theory or rebuild report.","A separate paper could audit declarations, Lean markers, axioms, and closure obligations directly.",["pinned commit","Lean logs","axiom inventory","semantic mapping","reviewable obligations"]),
split("out:dynamic-artifact-semantics-rule110","main.tex:6400-6559; review_bundle/case_snapshots/rule110_STATUS.md","dynamic artifact validation and Rule110 collision/exhaustiveness semantics are excluded from this finite-record package","Do not upgrade manifest rows into semantic artifact claims.","Dynamic Artifact Validation for Finite-Witness Formal-Mathematics Pipelines","Stage A preserved the distinction between manifest/evaluator rows and artifact-semantic validity.","This paper uses artifact limitations only as a case-study lesson and boundary.","A dedicated artifact paper could make validation reproducible and semantically meaningful.",["artifact specification","fresh rerun logs","collision criteria","reproducible environment","public data"]),
split("out:L0-L1-L2-universality-hierarchy","Prior Research Ledger Context from 2026_single_primitive_universality_hierarchy","Odrzywolek/Zeckendorf/certificate-universality hierarchy is mathematically substantive but unrelated to the auditable pipeline contribution","Do not import except as background memory for split attribution.","Expression, Protocol, and Certificate Universality for Single-Primitive Arithmetic Interfaces","Earlier Stage A reasoning discovered L0/L1/L2 taxonomy, Zeckendorf arithmetic, finite-fiber certificates, and strict separations.","This CICM route is about audit methodology and finite-record publication safety, not universality theory.","The hierarchy has its own theorem chain and strictness examples suitable for a separate mathematical paper.",["restore separate paper","verify conditional root hypotheses","separate finite-state/fiber claims","audit no leakage"])]
R['split_candidates'] += [
split("split:end-to-end-workflow-correctness","main.tex:9441; main.tex:9589; main.tex:9702; main.tex:11014; main.tex:11163","stronger end-to-end readings are decomposed into finite upgrade coordinates","Keep as boundary result here; split only if coordinates are supplied.","End-to-End Correctness Decomposition for Auditable AI Research Pipelines","Stage A identified a reusable five-interface/five-issue normal form.","Present article should remain a compact methodology paper.","The decomposition may generalize beyond BEDC/automath.",["abstract model","multiple examples","coordinate semantics","verified evidence"]),
split("split:publication-route-governance-and-overlap-blocking","main.tex:5441-5730; main.tex:5827-6215; review_bundle/case_snapshots/","overlap blocking, fake-extension rejection, and venue freshness are strong route-governance material but can overwhelm the method","Use concise case lessons here; split process report if desired.","Route Governance and Overlap Blocking in AI-Assisted Mathematical Publication Pipelines","Stage A surfaced a structured gate/issue/lesson protocol.","CICM scope is auto-formalization methodology, not publication operations as main object.","Route data could interest scholarly-infrastructure venues.",["route records","governance metrics","chronology","policy comparison"]),
split("split:finite-record-certificate-calculus","main.tex:1145-4665","the abstract certificate calculus is much larger than needed for a short presentation artifact","Compress here or split as reusable framework.","A Finite-Record Certificate Calculus for Auditable Research Automation","Stage A found schemas, coordinates, bad subrecords, maximality, and no-free-upgrade obstructions embedded in the supplement.","The route needs an applied method more than a full calculus.","The calculus could be specified and proved independently.",["minimal axioms","independent examples","schema spec","soundness/completeness proof","framework comparison"])]
R['irrelevant_or_remove'] += [
item("thm:stage-a2-round-one-issue-coordinate-discharge; prop:exact-stage-a2-issue-skeleton; cor:stage-a2-round-one-support-chain-closure","main.tex:11312; main.tex:11366; main.tex:11437","Stage-A2 issue-discharge material is internal pipeline bookkeeping and may distract from the presentation contribution","Move to review_bundle/appendix ledger or compress to a summary."),
item("irrelevant:literal-label-examples-in-path","main.tex:753; main.tex:8282","literal label tokens inside path examples are not mathematical content and create scanner ambiguity","Replace with escaped pseudocode later."),
item("prop:final-immutable-package-state-certificate; prop:mutable-checkout-observation-boundary","main.tex:7439; main.tex:7555","mutable-checkout/final-package observations are useful locally but implementation-local for a compact presentation","Keep in review bundle or compress unless needed by a support-coordinate theorem.")]
R['naive_truncation_risks'] += [
item("risk:finite-record-acceptance-as-implementation-soundness","main.tex:2070; main.tex:2139; main.tex:4471; main.tex:4606","finite accepted records may be mistaken for sound implementation of gates or daemon","Require implementation-soundness coordinate for concrete gate correctness."),
item("risk:source-line-range-as-semantic-source-truth","main.tex:598-1042","source labels and line ranges are stable finite records, not semantic proofs or rebuild results","Descend through bounded source-interface; add rebuild/axiom audit for stronger claims."),
item("risk:manifest-witness-as-artifact-semantics","main.tex:6400; main.tex:6520; main.tex:6559","manifest/evaluator rows can be overread as dynamic artifact semantic validity","Use artifact-validation gate as unique semantic upgrade."),
item("risk:local-digest-as-external-support","main.tex:7211-7917; main.tex:10588; main.tex:11196","local paths and digest rows do not glue to external submitted support without upload/archive locator","Separate local/path-verified and external-support coordinates."),
item("risk:row-frozen-certificate-as-post-edit-freshness","main.tex:5054; main.tex:8071; main.tex:9251; main.tex:10000","row-frozen certificate is not invariant under edits without rerun metadata and digest refresh","Rerun checks after every inventory or manuscript edit."),
item("risk:theorem-label-coverage-as-proof-correctness","main.tex:8209; main.tex:8256; main.tex:8387","the extractor proves only syntactic label inclusion, not proof checking","State theorem_inventory.json is inventory, not proof checker."),
item("risk:human-promotion-as-daemon-active-track-equivalence","main.tex:3100; submission_abstract.tex:67-72","human promotion and daemon-visible active tracks are distinct pipeline states","Preserve separation in each case-study lesson.")]
R['journal_style_gaps'] += [
item("style:overlarge-theoremized-supplement","main.tex:1-11587","about 11.5k lines and 160 theorem-like environments is large for a compact CICM presentation-only paper","Keep submission_abstract.tex primary and make the supplement optional, or compress the theorem chain."),
item("style:self-referential-current-package-theorems","main.tex:8209-11496","late theorems certify current inventory, digest, and support state; useful for audit but reads as internal bookkeeping","Move most fixed-point material to machine-readable ledger or appendix summary."),
item("style:bibliography-and-live-venue-verification","references.bib:1-46; research_directive.md:Publication Goal","bibliography is sparse and directive requires live venue/bibliography verification before route finalization","Verify current venue rules and add related-work citations."),
item("style:external-artifact-accessibility","review_bundle/; main.tex:7049-7917","review bundle is referenced through local paths; without archive/upload, reviewers cannot reproduce support surface","Attach bundle, publish archive, or explicitly limit claim to primary-only external support."),
item("style:title-and-scope-alignment","main.tex:18; research_directive.md:Central Claim; submission_abstract.tex:1-44","supplement title says auditable theory compiler while directive says theory-to-paper pipelines; relationship should be harmonized","Use consistent title/scope language across primary abstract, supplement, and metadata.")]

all_labels=[r['label'] for r in envs if r.get('label')]
text='\n'.join(str(x.get('label','')) for k,v in R.items() if isinstance(v,list) for x in v)
miss=[x for x in all_labels if x not in text]
if miss: raise SystemExit('inventory missing labels: '+', '.join(miss))
root.joinpath('theorem_inventory.json').write_text(json.dumps(R,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Stage A Theorem Inventory\n\n', 'Scope: CICM presentation-only / mathematical software workshop route for `2026_auditable_theory_to_paper_pipeline`.\n\n', f'Scanned `{len(envs)}` formal/audit environments from `main.tex`; all current labels are represented in `theorem_inventory.json`.\n\n']
for k,v in R.items():
    if k=='valid': continue
    md.append(f'## {k}\n\n')
    if not v: md.append('- None.\n\n')
    for x in v:
        md.append(f"- `{x['label']}` — {x['location']}: {x['reason']} Required action: {x['required_action']}\n")
        if 'candidate_title' in x: md.append(f"  - Split candidate: {x['candidate_title']}; needed: {', '.join(x['needed_to_split'])}.\n")
    md.append('\n')
root.joinpath('theorem_inventory.md').write_text(''.join(md),encoding='utf-8')
print('wrote theorem_inventory.json and theorem_inventory.md')
