import json, pathlib
items=json.load(open('.stage_a_envs_current_full.json',encoding='utf-8'))

def labels_for(file, section):
    labs=[i['label'] for i in items if i['file']==file and i['section']==section and i['label']]
    return '; '.join(labs)

def line_range(file, section):
    rows=[i for i in items if i['file']==file and i['section']==section]
    return f"{file}:{min(i['line'] for i in rows)}-{max(i['endline'] for i in rows)}" if rows else file

def row(label, location, reason, required_action, **extra):
    d={"label":label,"location":location,"reason":reason,"required_action":required_action}; d.update(extra); return d

keys=["valid","in_scope_present","missing_in_scope_results","weak_in_scope_core_results","proof_gaps","supporting_appendix_or_background","out_of_scope_strong_results","split_candidates","irrelevant_or_remove","naive_truncation_risks","journal_style_gaps"]
inv={k: [] for k in keys}; inv['valid']=True
sections=[
('group:package-shape-and-nested-state','main.tex','Scope and theoremization boundary.','Defines the selected presentation package, support tuple, and conservative six-row to seven-row state inclusion used by final support-coordinate claims.','Keep as package-local record claims; refresh extractor/verifier/digest logs after this inventory rewrite before citing current fixed-point claims.'),
('group:architecture-axis-boundary','main.tex','Architecture','Gives the five-axis architecture and bounded imported-source interface: BEDC source theory, Lean/formal verification, finite witnesses, advisory agents, and automath publication compilation.','Retain as the controlling vocabulary; keep source-interface use at bounded path-verified/executable-record level.'),
('group:abstract-finite-record-interface','main.tex','Abstract finite-record interface','Contains the central finite-record calculus: operational acceptance, record-gate soundness, schema verifier, finite-coordinate determination, extension budget, bad-subrecord obstruction, publication-safety interface, and no-free-upgrade boundary.','Retain as the mathematical/software-audit spine; keep record-gate soundness and non-implementation-soundness hypotheses explicit.'),
('group:current-package-instantiation','main.tex','Primary-claim inventory audit','Records the current package acceptance-certificate ledger.','Use with the following current-package exactness group; do not read it as semantic validation.'),
('group:current-package-exactness','main.tex','Current-package instantiation','Instantiates the certificate calculus for the current six accepted rows and proves row-frozen, path-verified, non-semantic current-package boundaries.','Retain; distinguish P6+ from the later theorem-inventory/P7+ support coordinate.'),
('group:case-study-witnesses','main.tex','Case-study witness protocol','Formalizes the gate-witness criterion and path-complete witnesses for the four case studies.','Keep case evidence path-verified/historical unless fresh command logs are added.'),
('group:case-evidence-protocol','main.tex','Case-evidence protocol.','Proves review-bundle case snapshot coverage and rigidity of the case-witness skeleton.','Retain as case-study support, not as daemon/full-source/artifact rerun evidence.'),
('group:submission-primary-interface','main.tex','Submission-interface checklist.','Connects venue/readiness records, artifact roles, formal-source gate, finite witness rows, primary-claim inventory, and primary/supplement interface.','Keep venue/upload claims dated, conditional, or historical unless an upload receipt/archive record is added.'),
('group:review-bundle-archive-theorem-inventory','main.tex','Review-bundle and archive-equivalence condition','Classifies exact supplemental inclusion, archive-equivalent support, digest refresh, syntactic theorem-environment extraction, theorem-inventory boundary, and local no-receipt fallback.','Retain; rerun extractor/verifier/digest after inventory edits before invoking current-byte fixed-point instances.'),
('group:command-run-final-support-closure','main.tex','Command-run boundary','Captures command-run metadata, post-edit rerun gate, fixed-point support coordinates, current command-result closure, external-support absence, and no-free-upgrade closure.','Retain; every current-execution claim needs command, source state, environment, exit code, and log path.'),
]
for name,file,sec,reason,action in sections:
    inv['in_scope_present'].append(row(f"{name} ({labels_for(file,sec)})", line_range(file,sec), reason, action))
inv['in_scope_present'].append(row('group:primary-presentation-claims','submission_abstract.tex:27-186','The short primary text states the architecture and finite-record safety claim, conditional on the technical supplement and review-bundle support surface; it denies fresh Lean rebuilds, artifact reruns, upload, venue acceptance, and end-to-end gate correctness.','Keep aligned with main.tex and review_bundle; preserve local/path-verified qualifiers unless exact support is submitted or archived.'))
inv['in_scope_present'].append(row(f"group:imported-discovery-source-snapshot ({labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Pipeline states')}; {labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Transition classes')}; {labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Discovery claims')}; {labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Gate theorems')}; {labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Lineage and selection')}; {labels_for('review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex','Pipeline adequacy')})",'review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex:18-457','Pinned imported source snapshot with 21 definitions and 15 theorem/corollary interfaces for automated-discovery gates, used here only through bounded source-interface records.','Keep as imported support/background, not as new contribution of this paper; cite pinned path, commit, line ranges, and extraction boundary.'))
inv['in_scope_present'].append(row('cor:stage-a2-support-coordinate-resolution-normal-form','main.tex:10376','Closes the Stage A2 support-coordinate issues as a labelled corollary: refreshed local theorem-inventory support is syntactic/finite-record only; external support remains exact-upload/archive-conditional; actual gate implementation soundness remains an explicit hypothesis; dynamic artifact and formal-source semantic reruns are not current evidence.','Retain as the terminal normal form for this presentation route; stronger readings require the finite upgrade coordinates listed in the corollary.'))
inv['missing_in_scope_results']=[]
inv['weak_in_scope_core_results']=[
row('weak:over-theoremized finite-record calculus for presentation route','main.tex:1031-10283','The supplement is proof-complete at record level but has 146 main theorem-like environments, risking obscuring the compact workshop contribution.','Add a dependency diagram or named theorem spine in the primary note; keep auxiliary variants visibly supplemental.'),
row('weak:record-gate soundness remains hypothesis-heavy','main.tex:1212; main.tex:3066','The main safety theorem is valuable only under explicit finite-record hypotheses, especially record-gate soundness.','State schema-relative finite-record safety under record-gate soundness in abstract/introduction.'),
row('weak:source-interface extraction is bounded paraphrase','main.tex:512-940','The source interface supports path-verified label/line/summary evidence, not exact theorem import, public reachability validation, or Lean rebuild evidence.','Make every imported-label use factor through the finite source-interface table.'),
row('weak:theorem-inventory extractor proves syntactic coverage only','main.tex:7822-8048; review_bundle/extract_theorem_environments.py:1','The extractor checks labelled theorem-like environments in main.tex against inventory labels; it does not check proof semantics or prose obligations.','Describe extractor success as label coverage only; keep semantic classification in this Stage A inventory.')]
inv['proof_gaps']=[
row('conditional:external support upload/archive not instantiated','main.tex:10376; review_bundle/FINAL_DIGESTS_SHA256.md','The manuscript now proves this as an absence/conditionality result rather than an unconditional external-support claim.','Keep support local/path-verified unless exact upload/archive and digest equality are recorded.'),
row('conditional:record-gate implementation soundness not discharged for real implementations','main.tex:1880; main.tex:10376','The finite-record theorem explicitly assumes record-gate soundness and classifies implementation soundness as a separate upgrade coordinate.','Keep explicit hypothesis or add implementation-soundness extension coordinates in a future expanded package.'),
row('conditional:semantic formal-source and artifact reruns not supplied','main.tex:6129-6166; main.tex:10376','The manuscript now treats Lean/BEDC rebuilds, axiom-purity, daemon execution, and dynamic artifact validation as absent unless fresh command-result/evaluator rows are added.','Do not present these semantic reruns as current evidence in this route.')]
inv['supporting_appendix_or_background']=[
row('background:Lean theorem prover and AI theorem-proving literature','references.bib:27-63','Lean, LeanDojo, Draft/Sketch/Prove, and AFP-mining citations provide external context, not new results.','Use as related work and verify bibliography before submission.'),
row('background:pinned BEDC/newmath source snapshot','references.bib:1-7; review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex:18-457','The automated discovery-gate chain is prior source material imported through bounded source interface.','Cite pinned commit and keep imported labels at bounded evidence level.'),
row('background:review-bundle scripts and manifests','review_bundle/certificate_schema.json; review_bundle/current_package_pass_records.json; review_bundle/REVIEW_BUNDLE_MANIFEST.json; review_bundle/*.py','Scripts/manifests support finite-record claims but are not proof of semantic gate correctness.','Submit as supplemental artifacts with refreshed digest rows.'),
row('background:four case-study snapshot files','review_bundle/case_snapshots/*','Case snapshots provide path-verified historical examples, not fresh daemon/overlap-checker/Rule110 reruns.','Cite the non-rerun boundary.')]
inv['out_of_scope_strong_results']=[
row('out-of-scope:single-primitive universality hierarchy and finite-fiber certificate universality','prior research ledger supplied in prompt','Prior ledger results are unrelated to the auditable theory-to-paper compiler theorem chain.','Do not import into this manuscript; keep in separate pipeline.',candidate_title='Single-Primitive Universality Hierarchy and Certificate Universality',source_contribution='Stage A reasoning identified L0/L1/L2 taxonomy, EML/Odrzywolek universality, Zeckendorf certificates, Richardson interfaces, and separations.',scope_mismatch='Current article concerns finite-record audit architecture for publication workflows, not algebraic/computability universality.',independent_paper_rationale='The hierarchy has independent mathematical content and named theorem obligations.',needed_to_split=['own scope_contract and inventory','conditional printed-root/replacement-triple Richardson boundary','separate finite-fiber and finite-state claims']),
row('out-of-scope:Rule110/GroundCompiler semantic universality or dynamic validation','main.tex:6129-6166','Current manuscript uses Rule110/GroundCompiler only as bounded artifact-limitation case evidence and denies dynamic rerun/universality claims.','Do not expand current paper into Rule110 validation.',candidate_title='Manifest-to-Semantics Validation for Rule110/GroundCompiler Artifacts',source_contribution='Stage A identifies a clean finite-record artifact boundary and missing semantic upgrade coordinates.',scope_mismatch='Semantic artifact validation requires evaluator evidence beyond the compiler architecture.',independent_paper_rationale='A separate artifact paper could study manifest-to-semantic upgrades through evaluator contracts and reruns.',needed_to_split=['evaluator specification','fresh command logs','artifact digest manifest','collision/exhaustiveness limitation analysis'])]
inv['split_candidates']=[
row('split:finite-record certificate calculus as standalone paper','main.tex:1031-4371','Finite-coordinate determination, stronger-reading preorder, bad-subrecord extraction, extension budgets, and no-free-upgrade theorems are more general than this presentation package.','Keep only needed spine here; consider extraction later.',candidate_title='A Finite-Record Certificate Calculus for Auditable Scientific Claims',source_contribution='Stage A identifies reusable schema-relative acceptance and finite bad-subrecord calculus.',scope_mismatch='Full calculus is too broad for compact architecture paper.',independent_paper_rationale='Could apply to artifact evaluation, reproducibility packages, and software audit ledgers.',needed_to_split=['tool-independent definitions','external examples','provenance/reproducibility comparison','proof compression']),
row('split:archive-equivalent support surfaces and byte-level fixed points','main.tex:6658-8696; main.tex:9422-9914','Exact inclusion, archive-equivalent locators, digest closure, post-inventory fixed points, and stable replay form a reusable publication-support theory.','Keep as support-boundary machinery in current paper.',candidate_title='Byte-Level Support-Surface Fixed Points for Mathematical Software Submissions',source_contribution='Stage A identifies exact supplemental inclusion, acyclic self-digest avoidance, and branch/archive equivalence theory.',scope_mismatch='Current route is an auditable theory-to-paper architecture, not full archival reproducibility theory.',independent_paper_rationale='Could support practical artifact-evaluation and reproducibility guidance.',needed_to_split=['general archive model','tool-independent digest generator','multi-venue examples','mutable branch-head treatment']),
row('split:automated theorem-discovery gate methodology','review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex:18-457','Imported source snapshot has theorem genomes, classifier shifts, scoring weights, lineage DAGs, and discovery gates.','Use only as bounded imported evidence here.',candidate_title='Auditable Gates for Automated Theory Discovery',source_contribution='Stage A identifies complete prior chain around discovery claims, genome compression, public weights, demotion, and lineage.',scope_mismatch='Current article is about publication compilation and audit boundaries, not internal discovery methodology.',independent_paper_rationale='Discovery-gate interface can stand as a methodology paper for AI theorem search.',needed_to_split=['full source statements/proofs','genome extraction examples','gate behavior evaluation','relation to theorem-proving literature'])]
inv['irrelevant_or_remove']=[
row('remove_or_quarantine:root scratch and prior Stage A helper artifacts','._stage_a* / .agent_* / _tmp_* / .prior_inventory_dump.json','Local scratch files are not part of submitted support unless named in digest/manifest and may confuse reviewers.','Do not cite or upload scratch artifacts; keep only selected support files.'),
row('remove_or_condense:duplicate local-readiness venue logs','review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-04.log through 2026-06-09.md','Multiple dated venue checks are history; only the current retained check should be load-bearing.','Keep as historical logs or submit only current check plus changelog.'),
row('remove_or_demote:audit-prefixed proposition labels','main.tex:5554; main.tex:5771; main.tex:5842; main.tex:8558; main.tex:8612; main.tex:8753','audit:* labels are useful but can confuse theorem-inventory tooling as a separate environment family.','Add a notation note that audit:* labels are proposition-style audit interfaces.')]
inv['naive_truncation_risks']=[
row('risk:six-row versus seven-row package states','main.tex:232; main.tex:4451; main.tex:8307','Treating P6+ invariance as unchanged after adding the theorem-ledger row would silently upgrade the finite projection.','Always state P6+ or P7+ and rerun checks after adding inventory rows.'),
row('risk:path-verified versus command-run evidence','main.tex:3022; main.tex:8753; main.tex:9820','A path/table/snapshot can be mistaken for command-result invariant; command-run needs command, source state, environment, exit code, and log path.','Require the full command tuple for current-execution claims.'),
row('risk:local bundle versus external support surface','main.tex:6658-7559; main.tex:10119','Local files and digest rows do not imply exact upload, DOI, archive minting, or public byte equality.','Preserve conditional exact-upload/archive-equivalent language.'),
row('risk:bounded source rows versus full BEDC/Lean semantics','main.tex:512-940','Finite labels, line ranges, summaries, and evidence levels do not import full theorem semantics or fresh Lean rebuilds.','Use imported claims only through finite source-interface projection.'),
row('risk:Rule110 limitation versus semantic artifact validity','main.tex:6094-6166; main.tex:6242-6345','The Rule110 row supports limitation disclosure/status, not universality, exhaustiveness, or dynamic evaluator rerun.','Add artifact-validation/evaluator command coordinate for stronger readings.'),
row('risk:syntactic theorem coverage versus proof checking','main.tex:7822-8048; review_bundle/extract_theorem_environments.py:1','Extractor domain is labelled theorem-like environments in main.tex and not proof semantics or prose obligations.','Treat extractor success as label coverage only.')]
inv['journal_style_gaps']=[
row('style:primary/supplement split needs concise theorem spine','submission_abstract.tex:79-122; main.tex:1031-4371','A workshop reviewer may not track a 10k-line supplement unless the central spine is highlighted.','Add compact dependency graph/table in primary note.'),
row('style:notation density and repeated skeleton terminology','main.tex:2464-4371','Skeleton, rigidity, normal form, no-free-upgrade, fixed point, support surface, and finite coordinate are used heavily.','Add glossary and keep primary statements operational.'),
row('style:record-gate soundness should headline the claim','submission_abstract.tex:32-47; main.tex:3066','The abstract includes conditionality, but it must be unmistakable because implementation correctness is not certified.','Use phrase schema-relative finite-record safety under record-gate soundness.'),
row('style:live venue/bibliography verification date sensitivity','research_directive.md:5-11; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-09.log','Venue requirements and bibliography links can change.','Rerun live checks near upload or mark route notes historical.'),
row('style:bibliography sparse for artifact/provenance context','references.bib:1-63','Bibliography covers Lean/AI proving but has limited artifact evaluation/provenance/reproducibility context.','Add venue-appropriate references after live verification.')]
inv={k:inv[k] for k in keys}
pathlib.Path('theorem_inventory.json').write_text(json.dumps(inv,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory\n','Stage A theorem inventory for `2026_auditable_theory_to_paper_pipeline`.\n']
for k in keys:
    if k=='valid': md += ['## valid\n',f'`{str(inv[k]).lower()}`\n']; continue
    md.append('## '+k.replace('_',' ').title()+'\n')
    if not inv[k]: md.append('No entries.\n'); continue
    for r in inv[k]:
        md.append(f'- **{r["label"]}** (`{r["location"]}`): {r["reason"]} Required action: {r["required_action"]}')
        for kk in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale']:
            if kk in r: md.append(f'  - {kk.replace("_"," ").title()}: {r[kk]}')
        if 'needed_to_split' in r: md.append('  - Needed To Split: '+'; '.join(r['needed_to_split']))
        md.append('')
pathlib.Path('theorem_inventory.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print('wrote')
