import json, pathlib
records=json.loads(pathlib.Path('_stage_a_live_envs.json').read_text(encoding='utf-8'))
sections=[]
for section in ['Problem and contribution','Architecture','Operational interface','Gate summary','Case studies','Evidence boundary']:
    rs=[r for r in records if r['section']==section]
    if not rs: continue
    labels='; '.join(r['label'] for r in rs if r['label'])
    loc=f"main.tex:{rs[0]['line']}; main.tex:{rs[-1]['line']}"
    if section=='Problem and contribution': reason='Package-shape and row-frozen package-state claims that initialize the finite support surface.'
    elif section=='Architecture': reason='Architecture/source-interface definitions and non-escalation results separating source, Lean/formal verification, finite witnesses, agents, and publication compilation.'
    elif section=='Operational interface': reason='Core finite-record certificate calculus, schema/verifier interface, record-gate soundness boundary, main publication-safety theorem, and current-package instantiation.'
    elif section=='Gate summary': reason='Compact gate-witness criterion and path-complete case-witness interface.'
    elif section=='Case studies': reason='Path-verified review-bundle case-snapshot coverage and rigidity for the four in-scope case studies.'
    else: reason='Evidence-boundary chain for venue freshness, formal-source promotion limits, finite witnesses, support surfaces, theorem inventory, command logs, and post-inventory fixed points.'
    sections.append({'label':labels,'location':loc,'reason':reason,'required_action':'Keep in scope as stated; preserve finite-record/non-escalation wording and rerun dependent support checks after inventory files change.'})
imported=['thm:automated-discovery-dna-completeness-obligation','cor:automated-discovery-statement-code-insufficient','thm:automated-discovery-mechanical-not-discovery','thm:automated-discovery-compression-not-discovery','thm:automated-discovery-certificate-ledger-required','thm:automated-discovery-positive-implies-discovery','thm:automated-discovery-scored-claims-public-weights','thm:automated-discovery-gate-kind-sound','thm:automated-discovery-demotion-soundness','thm:automated-discovery-lineage-dag','thm:automated-discovery-lowest-score-not-best-target','thm:automated-discovery-selection-favours-classifier-change','thm:automated-discovery-no-unpaid-discovery','thm:automated-discovery-pipeline-safety','thm:automated-discovery-pipeline-theorem','prin:automated-discovery-principle']
sections.append({'label':'; '.join(imported),'location':'source_interface_record.json; review_bundle/source_interface_verification_run.log; THEOREM_LIST.md:11','reason':'Imported BEDC discovery-gate source-interface spine used only through bounded paraphrase rows, source path, pinned commit, line ranges, snapshot, and finite record comparison.','required_action':'Treat as imported/background source-interface records, not new theorems proved in this article; add exact source statements only if quoted.'})
I={
'valid':True,
'in_scope_present':sections,
'missing_in_scope_results':[{'label':'post-write theorem_inventory fixed-point rerun','location':'theorem_inventory.json:1; theorem_inventory.md:1; review_bundle/FINAL_DIGESTS_SHA256.md:14','reason':'The manuscript claims post-inventory fixed-point/digest closure over theorem_inventory.json and theorem_inventory.md bytes; this Stage A run creates those files, so existing digest rows and logs cannot certify the newly written bytes.','required_action':'After accepting this inventory, rerun the theorem-environment extractor, certificate verifier, source-interface verifier, primary-claim verifier, and final digest generation.'}],
'weak_in_scope_core_results':[
{'label':'thm:publication-safety-interface','location':'main.tex:2872','reason':'Central theorem is intentionally schema-relative and finite-record-only; coherent for CICM software/workflow scope but weak if read as implementation soundness or mathematical proof-assistant soundness.','required_action':'Frame as certificate-carrying workflow interface and avoid Lean, daemon, artifact-semantic, or venue-acceptance overclaim.'},
{'label':'def:record-gate-soundness-external-interface; thm:assigned-gate-soundness-audit-boundary','location':'main.tex:1153; main.tex:2278','reason':'Record-gate soundness is an external interface/hypothesis, not a proved property of actual gate implementations.','required_action':'Keep the theorem chain conditional on record-gate soundness or add implementation-level proof/command records in a later version.'},
{'label':'lem:source-interface-extraction-correctness; thm:bounded-source-interface-maximality','location':'main.tex:487; main.tex:666','reason':'Imported BEDC results are represented by bounded paraphrase rows and line-range checks, not exact theorem statements or formal replay.','required_action':'Keep use at bounded-interface level or attach exact checked source statements before quoting.'},
{'label':'thm:finite-witness-manifest-record-interface; cor:artifact-semantic-validity-boundary','location':'main.tex:5831; main.tex:5971','reason':'Finite-witness rows are manifest/evaluator records only and do not dynamically validate artifact semantics.','required_action':'Do not use as Rule110, artifact-exhaustiveness, or semantic-validity theorem.'},
{'label':'thm:deterministic-theorem-environment-extractor-boundary; thm:theorem-inventory-proofchecker-obstruction','location':'main.tex:7412; main.tex:7590','reason':'Extractor certifies syntactic theorem-like label coverage, not statement semantics or proof correctness.','required_action':'Describe theorem_inventory.json/md as manual Stage A inventory plus label coverage, not proof checking.'},
{'label':'thm:public-branch-archive-equivalent-realization; cor:upload-or-archive-instantiation-record','location':'main.tex:6456; main.tex:6962','reason':'Archive equivalence is conditional on exact upload or byte-equality locator; no DOI, venue-upload receipt, or public byte-equality log is currently claimed.','required_action':'Supply exact supplemental material or a public locator plus byte-equality record before external support claims.'}],
'proof_gaps':[
{'label':'digest/bootstrap gap for newly written inventory','location':'review_bundle/FINAL_DIGESTS_SHA256.md:14; review_bundle/FINAL_DIGESTS_SHA256.md:15','reason':'Existing digest manifest lists inventory hashes that cannot be assumed to match the inventory files produced by this run.','required_action':'Regenerate digest manifest and dependent verification logs after finalizing inventory files.'},
{'label':'literal label-token collision','location':'main.tex:642; main.tex:7485','reason':'Two prose examples contain literal \\label{...}; naive label scanners see a duplicate label named "...". This is a structural bad-example mechanism, not just a typo.','required_action':'In a later TeX cleanup, escape or rephrase the examples so scanners cannot parse them as labels.'},
{'label':'prop:manual-theorem-inventory-boundary','location':'main.tex:7638','reason':'The environment is a theorem but the label uses a prop: prefix, which can confuse inventory and journal-style review.','required_action':'Align label prefix with environment or document stable historical label naming.'},
{'label':'auditrecord-domain gap','location':'main.tex:6274; main.tex:6321; main.tex:6347; main.tex:6639; main.tex:6754','reason':'Support-critical auditrecord labels lie outside the theorem-environment extractor domain.','required_action':'Inventory auditrecord labels manually or extend the extractor domain and rerun it.'},
{'label':'source-interface exact-statement gap','location':'THEOREM_LIST.md:31; main.tex:487','reason':'Local theorem list warns that exact source statements must be reread before quotation; manuscript currently uses bounded paraphrases.','required_action':'Do not quote imported BEDC labels as exact theorem statements unless exact text is added and checked.'},
{'label':'upload-time venue-compliance gap','location':'main.tex:5385; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-08.md:1','reason':'Venue and bibliography checks are dated support records, not upload receipts or future-stable compliance certificates.','required_action':'Run a fresh venue/bibliography check at actual submission time with command, environment, exit code, and log path.'},
{'label':'current-command-result closure after edits','location':'main.tex:9231; main.tex:9325','reason':'Command-result closure and stable replay depend on unchanged checked byte tuples; writing inventory files changes the inventory coordinate.','required_action':'Treat existing closure as stale for the new inventory bytes until post-write reruns update the tuple.'}],
'supporting_appendix_or_background':[
{'label':'deMouraKADR2015Lean','location':'references.bib:25','reason':'Classical Lean system citation supporting Lean as an independent verification axis.','required_action':'Use as background only; do not claim Lean build success without command logs.'},
{'label':'YangEtAl2023LeanDojo; JiangEtAl2023DraftSketchProve; BlanchetteHMN2015AFP','location':'references.bib:37; references.bib:44; references.bib:54','reason':'External AI/formal-proof tooling and proof-mining literature for related-work context.','required_action':'Cite as context; keep novelty on auditable publication/compiler workflow.'},
{'label':'bedc-newmath-source','location':'references.bib:1; source_interface_record.json:1','reason':'Pinned source repository/commit for imported BEDC discovery-gate interface.','required_action':'Preserve pinned commit and bounded-source wording; do not rely on branch-head drift.'},
{'label':'automath-publication-pipeline; auditable-pipeline-review-bundle','location':'references.bib:9; references.bib:17','reason':'Submission-local support notes, not ordinary external published references.','required_action':'Use only with exact supplemental inclusion or archive-equivalent byte equality.'},
{'label':'review_bundle case snapshots','location':'review_bundle/case_snapshots/program_board_machine.md; review_bundle/case_snapshots/upper_fibers_semantic_overlap_blockers.md; review_bundle/case_snapshots/fake_extension_artifact_inventory.md; review_bundle/case_snapshots/rule110_STATUS.md','reason':'Historical path-verified case evidence for intake isolation, overlap/submitted blocking, fake-extension rejection, and artifact-limitation disclosure.','required_action':'Do not infer dynamic reruns or semantic validation.'},
{'label':'review_bundle verifier scripts and logs','location':'review_bundle/verify_certificate_records.py; review_bundle/verify_source_interface_record.py; review_bundle/verify_primary_claim_inventory.py; review_bundle/theorem_environment_extraction_run.log','reason':'Executable finite-record checks supporting schema, source-interface, primary-claim, and theorem-environment coverage.','required_action':'Retain metadata and rerun after inventory changes before final support closure.'},
{'label':'submission_abstract.tex primary article','location':'submission_abstract.tex:1','reason':'Primary two-page presentation source has no theorem environments but is the main submission artifact.','required_action':'Keep theorem-heavy material in main.tex as supplement unless venue requests otherwise.'}],
'out_of_scope_strong_results':[
{'label':'single-primitive universality hierarchy ledger','location':'prior research ledger in prompt','reason':'L0/L1/L2 universality hierarchy, EML, Zeckendorf, Richardson, and finite-state strictness are strong results from another pipeline.','required_action':'Do not import into this CICM workflow paper except as background memory.','candidate_title':'Single-Primitive Universality Hierarchy','source_contribution':'Earlier Stage A reasoning identified expression/protocol/certificate universality levels with separations and finite-fiber mechanisms.','scope_mismatch':'Present article is a mathematical-software/workflow paper, not a universality or number-system paper.','independent_paper_rationale':'The hierarchy has independent mathematical content and a separate source paper/route.','needed_to_split':['Keep L0/L1/L2 labels in the separate universality manuscript.','Do not cite them as evidence for this workflow paper.','Mention only as a source-workspace example if a concrete path-verified case row is added.']},
{'label':'Rule110 universality or full dynamic artifact validation','location':'scope_contract.md:13; review_bundle/case_snapshots/rule110_STATUS.md','reason':'Explicitly out of scope; current manuscript uses it only as artifact-limitation disclosure.','required_action':'Keep limitation-disclosure case study; do not prove or imply Rule110 universality or exhaustiveness.','candidate_title':'Rule110 Artifact Validation and Exhaustiveness Audit','source_contribution':'Review bundle records collision/exhaustiveness audit findings and status evidence around Rule110 artifacts.','scope_mismatch':'A full validation paper needs semantic artifact proofs and reruns beyond finite-record publication support.','independent_paper_rationale':'Dynamic validation/exhaustiveness criteria could support a separate artifact-evaluation paper.','needed_to_split':['Define artifact semantics independently.','Provide reproducible rerun commands/logs.','Prove or falsify exhaustiveness claims at artifact level.']},
{'label':'complete BEDC theory exposition','location':'research_directive.md:29; scope_contract.md:12','reason':'Full BEDC theory paper is explicitly outside the workflow route.','required_action':'Keep BEDC content limited to finite-kernel/source-interface context and pinned labels.'}],
'split_candidates':[
{'label':'route-safe claim selection complexity','location':'oracle_stage_a_escalation.json; main.tex:2751','reason':'Planning material suggests stronger route-safe selection theory with certificate verification, NP-hard optimization, and scheduler non-completeness.','required_action':'Do not force into current paper unless scope is rewritten and artifacts are added.','candidate_title':'Certificate-Checkable but NP-Hard Route-Safe Selection for AI-Assisted Formal-Mathematics Publication Pipelines','source_contribution':'Stage A escalation proposed RSCS objects, verifier algorithms, NP-hardness via Independent Set, tractable fragments, and scheduler non-completeness.','scope_mismatch':'Would change the central contribution from finite-record audit interface to complexity theory.','independent_paper_rationale':'The complexity separation could stand alone as a mathematical-software routing paper.','needed_to_split':['Define RSCS schema/verifier.','Prove runtime and NP-hardness.','Add examples and overlap ledgers.','Update scope and avoid overlap.']},
{'label':'implementation-sound gate programs','location':'main.tex:3951; main.tex:4086','reason':'Manuscript gives extension/no-free-upgrade criteria, not implementation soundness for gate programs.','required_action':'Keep as future work unless specifications, tests, and command logs are supplied.','candidate_title':'Implementation Soundness for Auditable Publication Gate Programs','source_contribution':'Current theorem chain isolates the missing coordinate for implementation-level claims.','scope_mismatch':'Requires program verification/testing beyond a presentation-only finite-record interface.','independent_paper_rationale':'A verified gate suite would be valuable as a software artifact paper.','needed_to_split':['Formalize gate specifications.','Bind gates to source/environment/command/logs.','Add fixtures and regression tests.','Prove or validate implementation soundness.']},
{'label':'provenance/attestation framework for manuscript support surfaces','location':'main.tex:6412; main.tex:6787; references.bib','reason':'Support-surface/digest machinery resembles provenance systems but does not claim SLSA, in-toto, DOI, or archive compliance.','required_action':'Split only if actual attestation artifacts and external archive records are introduced.','candidate_title':'Certificate-Carrying Manuscript Support Surfaces','source_contribution':'Manuscript defines exact-inclusion, digest, archive-equivalence, and upload-or-archive boundaries.','scope_mismatch':'A provenance framework paper needs external standards/artifacts, not only local finite records.','independent_paper_rationale':'Could become reusable manuscript-provenance architecture.','needed_to_split':['Choose/define attestation standard.','Generate attestations.','Compare with provenance systems.','Archive immutable support surfaces.']},
{'label':'full BEDC/Lean source-closure audit','location':'main.tex:5648; main.tex:5715; references.bib:1','reason':'Current paper distinguishes formal-source markers from closure; full audit would replay Lean/BEDC builds and obligations.','required_action':'Keep outside unless fresh rebuild records and formal-source obligations are added.','candidate_title':'Lean-Backed BEDC Source Closure Audit','source_contribution':'Manuscript identifies formal-source promotion obstruction and missing evidence coordinates.','scope_mismatch':'A source-closure audit is a BEDC/formalization paper, not a publication-pipeline paper.','independent_paper_rationale':'Successful rebuild/closure audit would be a stronger formal-methods artifact contribution.','needed_to_split':['Record exact source state/commands.','Supply build logs.','Map markers to closure obligations.','Separate source theory from workflow claims.']}],
'irrelevant_or_remove':[
{'label':'literal \\label{...} examples','location':'main.tex:642; main.tex:7485','reason':'Prose examples create false positives for naive scanners.','required_action':'Remove/escape in later TeX cleanup; keep as structural scanner hazard here.'},
{'label':'root temporary extractor artifacts','location':'_stage_a_live_envs.json; _stage_a_live_envs_table.tsv; .current_formal_envs.json','reason':'Temporary diagnostics are not part of the submitted theorem chain unless included in a support tuple.','required_action':'Do not cite temporary root files; rely on submitted inventory and review_bundle logs.'},
{'label':'prior single-primitive universality ledger','location':'prior research ledger in prompt','reason':'Strong but irrelevant to current software-workflow contribution.','required_action':'Do not add to manuscript scope; preserve as split-paper memory.'},
{'label':'ordinary publication-upload or venue-acceptance implications','location':'main.tex:6919; main.tex:7120','reason':'Paper lacks upload receipts, DOI records, and venue acceptance; any prose implying these is overclaim.','required_action':'Remove accidental language reading local support as external acceptance/upload completion.'}],
'naive_truncation_risks':[
{'label':'row-frozen package-state invariance','location':'main.tex:223; main.tex:4499','reason':'Finite six/seven-row support state is invariant only for the frozen row set, not future changed records.','required_action':'When rows change, rerun finite-record calculus.'},
{'label':'bounded source-interface descent','location':'main.tex:487; main.tex:823','reason':'Line-range bounded paraphrase does not descend to semantic completeness of the whole BEDC source.','required_action':'Keep claims at label/path/commit/range level unless exact semantics are added.'},
{'label':'local digest surface versus external archive','location':'main.tex:6412; main.tex:6456; main.tex:6919','reason':'Local digest table is not invariant under upload, branch movement, archive replacement, or venue submission without byte equality.','required_action':'Require exact inclusion or byte-equality locator for external support.'},
{'label':'command logs after source edits','location':'main.tex:8436; main.tex:9231; main.tex:9325','reason':'Zero-exit logs certify only the recorded source state/byte tuple; inventory writing changes the tuple.','required_action':'Rerun post-edit checks after every inventory/support edit.'},
{'label':'theorem-environment extraction versus proof correctness','location':'main.tex:7412; main.tex:7590','reason':'Finite label coverage is syntactic and does not glue to statement semantics or proof validity.','required_action':'Do not present inventory as proof checking.'},
{'label':'manifest finite-witness rows versus artifact semantics','location':'main.tex:5831; main.tex:5971','reason':'Finite manifest rows do not automatically validate artifact semantics, exhaustiveness, or evaluator behaviour.','required_action':'Keep artifact case studies at record-evidence level unless semantic validation is supplied.'}],
'journal_style_gaps':[
{'label':'theorem-environment overuse','location':'main.tex:174; main.tex:9530','reason':'Supplement contains 141 theorem-like/audit formal items, many bookkeeping/package-state claims; CICM readers may see over-theoremization.','required_action':'Keep primary concise and supplement subordinate; consider moving routine support claims to audit records/tables later.'},
{'label':'title and abstract boundary','location':'main.tex:19; main.tex:28; submission_abstract.tex:1','reason':'Supplement title emphasizes finite-record safety while route is presentation-only auditable theory compiler.','required_action':'Ensure primary/supplement roles are consistently stated.'},
{'label':'label naming consistency','location':'main.tex:7638','reason':'Theorem with prop: label prefix is stylistically confusing.','required_action':'Normalize label prefix later or document stable identifiers.'},
{'label':'external reference posture','location':'references.bib:9; references.bib:17','reason':'Some bibliography entries are submission-local support notes, not ordinary scholarly references.','required_action':'Verify venue expectations and add conventional related-work citations where appropriate.'},
{'label':'conditional support surface','location':'review_bundle/FINAL_DIGESTS_SHA256.md:3; main.tex:6412','reason':'Many claims are externally valid only under exact/byte-equivalent support-bundle inclusion.','required_action':'Package support files exactly and state condition prominently.'},
{'label':'novelty framing','location':'research_directive.md:9; main.tex:162','reason':'Contribution is workflow/compiler architecture, not a new theorem-proving method.','required_action':'Frame novelty as auditable separation of evidence surfaces and finite-record gates.'}]
}
keys=['valid','in_scope_present','missing_in_scope_results','weak_in_scope_core_results','proof_gaps','supporting_appendix_or_background','out_of_scope_strong_results','split_candidates','irrelevant_or_remove','naive_truncation_risks','journal_style_gaps']
assert list(I)==keys
pathlib.Path('theorem_inventory.json').write_text(json.dumps(I,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory','','Stage A theorem inventory for `2026_auditable_theory_to_paper_pipeline`.','','Bounded by `scope_contract.md`, `scope_contract.json`, `research_directive.md`, manuscript TeX/Bib files, and explicitly referenced review-bundle support files. Manuscript `.tex` files were not edited.','']
for k in keys[1:]:
    md += ['## '+k.replace('_',' ').title(),'']
    for item in I[k]:
        md.append(f"- `{item['label']}`")
        md.append(f"  - Location: `{item['location']}`")
        md.append(f"  - Reason: {item['reason']}")
        md.append(f"  - Required action: {item['required_action']}")
        for e in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale']:
            if e in item: md.append(f"  - {e.replace('_',' ').title()}: {item[e]}")
        if 'needed_to_split' in item: md.append('  - Needed to split: '+'; '.join(item['needed_to_split']))
    md.append('')
pathlib.Path('theorem_inventory.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print('wrote', len(records), 'formal/audit records into grouped inventory')
