import json
from pathlib import Path
items=json.loads(Path('_inventory_envs_fresh.json').read_text(encoding='utf-8'))

def labels_between(start,end):
    return '; '.join(i['label'] for i in items if i['file']=='main.tex' and start <= i['line'] <= end and i['label'])

def row(label, location, reason, required_action, **extra):
    d={"label":label,"location":location,"reason":reason,"required_action":required_action}
    d.update(extra)
    return d

inv={"valid":True,
"in_scope_present":[
row(labels_between(184,337),"main.tex:184-376","Package-shape and architecture-axis formalities are present and directly support the central separation of source, formal, artifact, agent, route, and support records.","Keep as in-scope; ensure presentation text states that these are finite-record architecture claims, not implementation or venue claims."),
row(labels_between(513,941),"main.tex:399-979","The imported BEDC/newmath source-interface chain is present: manual extraction, JSON/snapshot comparison, public-source non-escalation, and bounded semantic-completeness obstruction.","Keep as in-scope support for imported discovery-gate claims; cite the pinned source path and keep exact line/digest records with the submitted bundle."),
row(labels_between(1032,1976),"main.tex:1032-2050","The operational acceptance interface, record-gate soundness interface, schema verifier, executable normal form, acceptance exactness, coordinate boundary, and machine-readable certificate records are present.","Keep as the core formal interface; preserve the explicit conditionality on record-gate soundness and schema-relative finite records."),
row(labels_between(2078,3067),"main.tex:2078-3167","The deterministic dispatch, script-boundary, assigned-gate, finite-obstruction, extension-budget, dependency-order, promotion/daemon separation, advisory scheduler, minimal bad-record witness, and main publication-safety interface are present.","Keep as the main theorem chain; add or reference a proof for the main interface theorem rather than relying only on surrounding dependency prose."),
row(labels_between(3174,4372),"main.tex:3174-4424","The stronger-reading obstruction and no-free-upgrade chain is present, including implementation-soundness upgrade criterion, boundary-axis exactness, five-axis upgrade obstruction, maximality, and external-interface projection.","Keep as in-scope boundary control; ensure stronger-reading claims always require explicit finite extension coordinates."),
row(labels_between(4472,5096),"main.tex:4472-5140","The current-package instantiation chain is present: acceptance ledger, bounded schema-relative exactness, row-frozen invariance, semantic non-escalation, named boundary classifier, and path-verified instance.","Keep as current-package support, but refresh verifier logs/digests after the final inventory bytes are fixed."),
row(labels_between(5199,5411),"main.tex:5199-5449","The four case-study witness skeleton is present: gate witness criterion, path-complete witnesses, review-bundle coverage, and skeleton rigidity.","Keep as the case-study theorem interface; preserve gate, observed issue, and safe lesson for each case."),
row(labels_between(5554,6574),"main.tex:5554-6626","The venue, source, evidence-level, finite-witness, artifact-semantic, and primary-claim inventory boundary chain is present.","Keep as boundary material; do not read venue/bibliography checks, finite witness rows, or primary inventory rows as semantic or upload-time guarantees."),
row(labels_between(6685,7757),"main.tex:6685-7799","The review-bundle/archive-equivalence and support-surface chain is present, including exact inclusion, public branch equivalence, final digest closure, upload boundary, and no-receipt non-escalation.","Keep as support-surface governance; instantiate externally only by exact upload or byte-equality archive locator with matching final digests."),
row(labels_between(7823,10433),"main.tex:7823-10480","The theorem-inventory, post-inventory fixed-point, command-run boundary, final support-state reconciliation, presentation-route classifier, and no-free-upgrade closure chain is present.","Keep as finite-record closure support, but treat it as conditional on post-inventory reruns and final digest regeneration for the exact bytes submitted."),
row("submission_abstract_primary_claims","submission_abstract.tex:21-164; review_bundle/primary_claim_inventory.json","The two-page presentation states the architecture and finite-record-only safety boundary without theorem environments; its load-bearing claims are enumerated in the primary-claim inventory.","Keep synchronized with the supplement; any edited primary sentence needs a refreshed primary-claim inventory and support map."),
row("references_support","references.bib:1-54","The bibliography supplies supporting citations for the pinned BEDC/newmath source, automath pipeline, review bundle, Lean, LeanDojo, Draft--Sketch--Prove, and AFP background.","Use as context/support only; do not present cited classical or external systems as new results of this paper.")],
"missing_in_scope_results":[],
"weak_in_scope_core_results":[
row("thm:publication-safety-interface","main.tex:3067","The central theorem is correctly bounded but is conditional on the finite predicate RGS and does not establish implementation soundness of gate programs, Lean/BEDC rebuild correctness, artifact semantics, daemon behavior, upload, archive availability, or venue acceptance.","For CICM presentation framing, state this as an interface theorem under explicit hypotheses; if a stronger title or claim is desired, add the implementation/source/environment/log coordinates instead of broadening prose."),
row("thm:current-package-certificate-exactness; prop:current-package-acceptance-certificate-ledger","main.tex:4472-4698","The current-package exactness result is row-frozen and schema-relative to declared verifier rows; it is not theorem adequacy or semantic truth of every package claim.","Keep the row-frozen wording; add a concise reviewer note explaining the exact verifier domain and why this is sufficient for a presentation-only software paper."),
row("thm:finite-witness-manifest-record-interface; cor:artifact-semantic-validity-boundary","main.tex:6117-6364","The finite-witness interface supports manifest-bounded historical artifact rows, but not dynamic Rule110/GroundCompiler semantic validation or fresh evaluator reruns.","Preserve the artifact-limitation disclosure; add fresh evaluator logs only if the paper wants artifact-semantic claims."),
row("lem:source-interface-extraction-correctness; thm:bounded-source-interface-maximality","main.tex:513-756","The imported source interface is manual/path-verified and pinned-snapshot bounded; it does not prove semantic truth of the imported source theorems or a fresh Lean/BEDC rebuild.","Keep as bounded source-interface evidence; avoid phrasing it as a formal rebuild or complete BEDC exposition."),
row("thm:deterministic-theorem-environment-extractor-boundary; thm:theorem-inventory-proofchecker-obstruction","main.tex:7823-8048","The theorem-inventory checker is syntactic label coverage only; it deliberately excludes statement semantics, proof validity, auditrecord environments, and adequacy of theorem statements.","Keep as syntactic inventory support; do not use it as proof-checking evidence.")],
"proof_gaps":[
row("thm:publication-safety-interface","main.tex:3067-3167","The central theorem is stated and heavily cross-referenced, but no explicit proof environment follows it; the manuscript relies on dependency-order prose and later results rather than a local proof of the theorem as stated.","Add a proof immediately after the theorem or explicitly mark it as a corollary of the preceding schema-exactness, obstruction, extension-budget, and maximality results with a formal proof paragraph."),
row("duplicate-syntactic-label-token","main.tex:668; main.tex:7896","Two proof paragraphs contain the literal token \\path{\\label{...}}, which the bundled extractor reads as a label named '...'; the extractor therefore reports a duplicate label even though this is explanatory prose.","Escape or rewrite the illustrative token in the TeX source in a later editing stage, or update the extractor to ignore labels inside path/prose examples; do not rely on current extractor success until this is fixed."),
row("post_inventory_digest_fixed_point","theorem_inventory.json; theorem_inventory.md; review_bundle/FINAL_DIGESTS_SHA256.md:20-21","The support-surface theorems require the inventory files, extractor log, verifier logs, and final digest manifest to be regenerated after the final inventory bytes exist; writing this inventory changes those bytes and makes any pre-existing digest rows stale.","After accepting the inventory content, rerun the theorem-environment extractor and finite-record verifiers, then regenerate FINAL_DIGESTS_SHA256.md before treating post-inventory support-coordinate theorems as instantiated."),
row("review_bundle_external_instantiation","main.tex:6685-7799; submission_abstract.tex:42-54","The manuscript correctly says external support is conditional on exact supplemental upload or archive-equivalent byte equality, but no receipt/DOI/upload record is present in the source package.","Keep the current non-escalation boundary; add a receipt or byte-equality archive locator only at submission time if external support is claimed."),
row("command_run_claim_boundary","main.tex:8754-8868","Command-result claims are allowed only with command, source state, environment, exit code, and log path; several current-package closure statements are conditional on retained logs rather than fresh full gate execution.","Retain historical/path-verified phrasing unless exact rerun metadata is supplied for the asserted command-result claim."),
row("venue_freshness_boundary","main.tex:5554-5841; references.bib","Venue and bibliography records are dated local-readiness checks and not upload-time venue compliance or acceptance records.","Refresh venue/bibliography checks near submission and phrase them as dated checks unless a venue upload record exists.")],
"supporting_appendix_or_background":[
row("imported_automated_discovery_spine","review_bundle/source_snapshots/automated_theory_discovery_pipeline_calculus_3fb3d6a0641767388a401883062aa522ea0b397b.tex; main.tex:399-756","The discovery-gate definitions and theorems imported from the pinned newmath source are background/source-interface evidence for this architecture paper, not new theorems proved here.","Cite the pinned path, commit, line ranges, and source_interface_record.json; keep imported claims bounded to the sixteen-row interface used by the manuscript."),
row("lean_and_ai_formalization_background","references.bib:25-54","Lean, LeanDojo, Draft--Sketch--Prove, and AFP are classical/external context for proof assistants, AI-assisted proving, and formal archives.","Use only as literature context; do not treat them as evidence for this package's gate soundness or artifact semantics."),
row("review_bundle_scripts","review_bundle/verify_certificate_records.py; review_bundle/verify_source_interface_record.py; review_bundle/extract_theorem_environments.py","The scripts support finite schema checks, source-interface comparison, and syntactic theorem-label extraction; they are tools for record evidence, not independent mathematical proof checkers.","Retain command logs with source hashes and exit codes whenever script outcomes are cited."),
row("case_snapshot_material","review_bundle/case_snapshots/","The case files are historical/path-verified snapshots illustrating intake isolation, overlap/submitted blocking, fake-extension rejection, and artifact limitation disclosure.","Use them as bounded case evidence; do not infer fresh daemon behavior or dynamic artifact validation."),
row("primary_claim_inventory","review_bundle/primary_claim_inventory.json","The primary claim inventory is a support ledger for the two-page presentation's load-bearing sentences.","Refresh after edits to submission_abstract.tex and keep evidence levels aligned with the supplement.")],
"out_of_scope_strong_results":[row("L0_L1_L2_universality_hierarchy_prior_stage_a_memory","prior research ledger context; not part of main.tex or submission_abstract.tex","The EML/Zeckendorf/protocol/certificate universality hierarchy is mathematically strong but unrelated to the present paper's auditable theory-to-paper compiler architecture.","Do not import these theorems into this article except as historical context for pipeline provenance if needed.",candidate_title="Single-Primitive Universality Hierarchy and Finite-Fiber Certificates",source_contribution="Earlier Stage A reasoning identified a three-level L0/L1/L2 taxonomy, EML expression universality, Zeckendorf protocol/certificate universality, obstruction and separation results, finite-fiber Hankel-Prony certificates, and finite-state strictness mechanisms.",scope_mismatch="This CICM presentation-only paper is about finite-record publication safety, source/gate/support separation, and AI-assisted workflow auditability; it is not a new universality or arithmetic theory paper.",independent_paper_rationale="The hierarchy has its own mathematical research question, theorem chain, and proof burden suitable for a separate Proc. AMS-style or theory paper.",needed_to_split=["Keep the L0/L1/L2 definitions and theorems in the separate universality manuscript","Provide independent proofs for EML, Zeckendorf, finite-fiber, and separation claims","Do not make any of those results load-bearing for the present workflow architecture paper"])],
"split_candidates":[
row("gate_implementation_soundness_program_logic","main.tex:2288-2541; main.tex:3174-3339; main.tex:4237-4424","The manuscript repeatedly identifies implementation soundness of concrete gate programs as a stronger extension coordinate rather than a proved current-package result.","Keep this article at finite-record interface level; open a separate implementation-audit paper only if source code specifications, commands, environments, logs, and proof obligations are supplied.",candidate_title="Implementation Soundness for Auditable Publication Gates",source_contribution="Stage A inventory finds a precise six-coordinate skeleton for upgrading from record-gate soundness to concrete gate implementation soundness.",scope_mismatch="The current presentation route intentionally proves no gate implementation correctness beyond recorded finite predicates.",independent_paper_rationale="A full program-logic treatment of publication gates would be a self-contained software verification contribution.",needed_to_split=["Formal specifications for each gate program","Immutable source-state and environment records","Executable test/rebuild logs","Proof tying implementation I/O to the record predicates"]),
row("artifact_semantic_validation_for_finite_witnesses","main.tex:6117-6364; review_bundle/case_snapshots/rule110_STATUS.md","The artifact interface is manifest-bounded and explicitly not a dynamic semantic-validation theorem for Rule110/GroundCompiler artifacts.","Do not strengthen the present paper; split only if evaluator contracts and fresh semantic validation logs are produced.",candidate_title="Semantic Validation of Finite Witness Artifacts in Formal-Mathematics Pipelines",source_contribution="The current manuscript isolates the unique semantic upgrade coordinate for finite witness artifacts.",scope_mismatch="The CICM presentation paper needs artifact-limitation disclosure, not a full semantic artifact-validation theory.",independent_paper_rationale="A dynamic artifact validator with contracts and replayable logs could become a separate mathematical-software artifact paper.",needed_to_split=["Evaluator contract","Fresh command logs and environment records","Semantic validity criteria","Comparison against manifest-bounded historical rows"]),
row("semantic_theorem_inventory_and_proof_adequacy_checker","main.tex:7823-8048","The current theorem inventory checker is intentionally syntactic label coverage and rejects any semantic/proof-checker reading.","Keep this inventory syntactic; split a semantic adequacy checker only with a parser, proof-dependency model, and checker evidence.",candidate_title="Semantic Theorem-Inventory Checking for Publication Packages",source_contribution="The manuscript cleanly identifies the non-gluing boundary between label extraction, statement semantics, and proof correctness.",scope_mismatch="The present paper's finite-record support only needs bounded label inventory, not automated proof adequacy.",independent_paper_rationale="A semantic inventory checker could be an independent contribution for formal-methods publication tooling.",needed_to_split=["Formal grammar for target TeX theorem statements","Proof dependency extraction","Adequacy specification","Validation corpus and logs"]),
row("publication_route_archive_equivalence_protocol","main.tex:6685-7799","The upload/archive-equivalence normal forms are useful but occupy a large support-governance subsystem beyond the core finite-record theorem.","For the current article, keep only the exact-inclusion/non-escalation boundary needed for support claims; consider a separate tooling note for archive-equivalence protocols.",candidate_title="Byte-Equality Archive Equivalence for Supplemental Mathematical Software Packages",source_contribution="Stage A inventory finds a reusable exact-upload or byte-equality locator protocol with digest closure and mutable-checkout non-certification.",scope_mismatch="The presentation-only route should not be dominated by archive mechanics unless the venue specifically requests artifact-packaging details.",independent_paper_rationale="Digest-based archive equivalence and support-surface instantiation are reusable across publication workflows.",needed_to_split=["Stable archive locator rules","Digest-generation protocol","Submission-time receipt model","Examples across multiple packages"])],
"irrelevant_or_remove":[
row("accidental_universality_material","prior research ledger context only","Any EML, Zeckendorf, Hankel-Prony, finite-state strictness, Richardson-interface, or L0/L1/L2 separation material would be irrelevant to this architecture paper if inserted.","Keep out of the manuscript and route to the separate universality hierarchy pipeline."),
row("theoremized_support_bookkeeping_density","main.tex:6685-10480","Many late support-coordinate statements are relevant as boundary checks but read as theoremized bookkeeping rather than mathematical-software contribution in a short CICM presentation.","For final venue packaging, consider moving repetitive support-coordinate normal forms into an appendix or review bundle summary while preserving the core finite-record theorem chain."),
row("fake_extension_or_bad_example_mechanism","review_bundle/case_snapshots/fake_extension_artifact_inventory.md; main.tex:5299-5499","The fake-extension case is not a standalone mathematical counterexample; its structural mechanism is unsupported extension of finite records beyond an assigned gate/evidence level.","Keep only the mechanism and safe lesson; remove anecdotal route detail if space constrained.")],
"naive_truncation_risks":[
row("row_frozen_current_package","main.tex:4472-5140","Current-package exactness is invariant only for the declared finite rows; adding or editing claims changes the support surface and can invalidate the row-frozen conclusion.","Require a refreshed ledger, primary inventory, theorem inventory, and verifier logs after any load-bearing edit."),
row("post_inventory_fixed_point","main.tex:7823-10480","The post-inventory support coordinate is a fixed point over file bytes, extractor output, verifier logs, and digest rows; treating old digest rows as invariant after inventory edits is a truncation error.","Regenerate logs and digests after the final theorem_inventory.json and theorem_inventory.md bytes are fixed."),
row("finite_witness_manifest_rows","main.tex:6117-6364","Finite witness rows do not descend automatically to artifact semantic validity across evaluator versions, dynamic runs, or unbounded Rule110/GroundCompiler claims.","Keep manifest-bounded phrasing unless evaluator contracts and fresh semantic validation logs are supplied."),
row("public_branch_archive_equivalence","main.tex:6685-7799","A branch/path locator is mutable and not invariant under later branch movement; archive equivalence requires byte equality against the final digest table.","Use exact supplemental upload or a pinned byte-equality archive record, not a moving branch pointer alone."),
row("source_snapshot_import","main.tex:399-979","The pinned source snapshot supports only listed line ranges and bounded summaries; public repository reachability or source text availability does not imply semantic completeness, formal rebuild, or all-source import.","Keep the finite imported-interface table as the only source-coordinate used in proofs."),
row("theorem_environment_extractor_domain","main.tex:7823-8048","The extractor domain is finite and syntactic; treating label coverage as statement coverage, proof coverage, or auditrecord coverage would be a naive invariant extension.","State syntactic domain and proof-checker obstruction whenever invoking inventory completeness."),
row("venue_rule_freshness","main.tex:5554-5841","Dated venue/bibliography checks do not remain invariant up to upload time without an unchanged-rule or fresh upload-time record.","Refresh near submission or phrase as historical local-readiness evidence.")],
"journal_style_gaps":[
row("presentation_vs_technical_supplement_scale","main.tex:67-10531; submission_abstract.tex:21-164","The supplement contains 150+ formal environments for a presentation-only route; this is much heavier than a typical CICM short paper even if the two-page primary artifact is compact.","Keep the two-page article focused on architecture and move detailed finite-record calculus to supplemental material explicitly marked as support."),
row("theorem_naming_and_label_mismatch","main.tex:8049","A theorem environment has label prop:manual-theorem-inventory-boundary; the label prefix does not match the environment type and may confuse reviewers and automated tooling.","Rename in a later TeX-edit stage or document that label prefixes are not semantic; do not edit TeX during this inventory stage."),
row("central_theorem_proof_presentation","main.tex:3067-3167","The central theorem's proof presentation is diffuse: it cites many later and earlier results instead of giving a compact proof immediately after the statement.","Add a short proof or proof roadmap adjacent to the theorem for reviewer readability."),
row("terminology_density","main.tex:1032-4424","Terms such as RGS, finite bad subrecord, stronger-reading preorder, support-coordinate fixed point, and no-free-upgrade are precise but numerous for a workshop audience.","Add a one-paragraph glossary or compress notation in the primary presentation."),
row("citation_and_live_verification","references.bib; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-09.log","Venue and bibliography data are temporally unstable and should be verified close to submission.","Run a final live venue/bibliography check before submission and record command, source state, environment, exit code, and log path if cited as current."),
row("support_surface_submission_dependency","submission_abstract.tex:42-54; main.tex:6685-7799","The paper's external support depends on exact supplemental upload or archive-equivalent byte equality; if the venue cannot accept the full support surface, several support claims remain local only.","Before submission, confirm supplemental-file policy and either upload the exact bundle or downgrade external-support wording to local/path-verified support."),
row("self_referential_inventory_packaging","main.tex:7823-10480","The manuscript theoremizes the fact that theorem_inventory.json and theorem_inventory.md must exist and be hashed, which is structurally sound but may appear self-referential without a final fixed-point log.","After final inventory acceptance, rerun and retain the fixed-point extraction and digest logs; explain self-reference as a byte-level packaging convention, not a mathematical premise.")]
}
keys=["valid","in_scope_present","missing_in_scope_results","weak_in_scope_core_results","proof_gaps","supporting_appendix_or_background","out_of_scope_strong_results","split_candidates","irrelevant_or_remove","naive_truncation_risks","journal_style_gaps"]
inv={k:inv[k] for k in keys}
Path('theorem_inventory.json').write_text(json.dumps(inv,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory\n','Stage A theorem inventory for `2026_auditable_theory_to_paper_pipeline`. This inventory is scope-bound to the stable scope files, manuscript sources, bibliography, and named support bundle records.\n']
for k in keys:
    if k=='valid':
        md += ['## valid\n', '`true`\n']
        continue
    md.append('## '+k.replace('_',' ').title()+'\n')
    if not inv[k]:
        md.append('- None recorded.\n')
        continue
    for it in inv[k]:
        md.append(f"- **{it['label']}** (`{it['location']}`): {it['reason']} Required action: {it['required_action']}")
        if k in ('out_of_scope_strong_results','split_candidates'):
            for extra in ('candidate_title','source_contribution','scope_mismatch','independent_paper_rationale'):
                if extra in it:
                    md.append(f"  - {extra.replace('_',' ')}: {it[extra]}")
            if 'needed_to_split' in it:
                md.append('  - needed to split: '+'; '.join(it['needed_to_split']))
        md.append('')
    md.append('')
Path('theorem_inventory.md').write_text('\n'.join(md),encoding='utf-8')
print('wrote theorem_inventory.json and theorem_inventory.md')
