import json, re
from pathlib import Path
items=json.loads(Path('_stage_a_inventory_current_envs.json').read_text(encoding='utf-8'))
labels=[it['label'] for it in items if it.get('label')]
def row(label, location, reason, action, **extra):
    d={'label':label,'location':location,'reason':reason,'required_action':action}
    d.update(extra)
    return d
clusters=[
('prop:final-package-shape-convention; thm:nested-package-states','main.tex:174; main.tex:223','Final package shape and six/seven-row support-state nesting.','Keep in scope; refresh post-inventory support logs before final claims.'),
('def:architecture-axis-map; prop:architecture-axis-non-escalation','main.tex:288; main.tex:327','Architecture-axis separation for source theory, Lean markers, finite witnesses, agents, and publication compiler.','Keep as architecture spine; use external systems only at declared evidence levels.'),
('lem:source-interface-extraction-correctness; prop:manual-source-interface-non-escalation; prop:reviewable-source-snapshot-interface; prop:source-interface-record-file-consistency; thm:bounded-source-interface-maximality; thm:public-source-reachability-non-escalation; cor:public-source-coordinate-exactness; thm:source-interface-semantic-completeness-obstruction; prop:source-interface-evidence-level-separation','main.tex:487-872','Bounded BEDC/newmath source-interface import and no semantic-completeness escalation.','Keep path/commit/line/label boundaries; require fresh BEDC/Lean logs for semantic upgrades.'),
('def:operational-acceptance-interface; def:record-gate-soundness-external-interface; prop:record-gate-soundness-external-interface-exactness; def:stronger-reading-preorder; def:certificate-schema-acceptance-table','main.tex:963-1244','Finite claim, gate, evidence, certificate, record-gate soundness, stronger-reading, and verifier-schema interfaces.','Keep as definitions; do not claim actual gate implementation soundness.'),
('prop:finite-certificate-schema-verifier; thm:verifier-input-output-contract; thm:finite-verifier-normal-form; thm:record-acceptance-exactness; cor:executable-schema-exactness-negative-fixture; thm:finite-coordinate-determination-boundary; thm:record-interface-rigidity','main.tex:1284-1654','Schema-relative verifier exactness, negative fixture, coordinate classifier, and refresh fixed point.','Keep in scope; verify against current JSON records and logs.'),
('thm:record-gate-implementation-overclaim-obstruction; cor:finite-record-acceptance-not-implementation-soundness; prop:machine-readable-certificate-records; thm:executable-record-non-escalation; thm:executable-certificate-construction-invariant; prop:claim-kind-dispatch; thm:mixed-claim-projection-obstruction; thm:concrete-finite-script-implementation-soundness; cor:finite-script-rgs-instantiation-boundary; thm:assigned-gate-soundness-audit-boundary','main.tex:1754-2269','Obstruction/construction layer separating executable finite records from implementation soundness.','Keep exact command/log requirements for any command-result reading.'),
('thm:finite-certificate-obstruction-skeleton; thm:finite-record-certificate-calculus-spine; thm:finite-extension-budget-normal-form; prop:publication-safety-dependency-normal-form; prop:gate-interface-separation; cor:human-promotion-daemon-active-track-separation; prop:scheduler-selection-advisory; prop:publication-safety-minimal-bad-record-witness','main.tex:2338-2742','Bad-subrecord, finite-record calculus spine, extension-budget, gate-separation, human-promotion, daemon-track, and scheduler-advisory mechanisms.','Use as structural mechanism for bad examples and overclaim counterexamples.'),
('thm:publication-safety-interface; thm:finite-record-certificate-rigidity; thm:boundary-axis-non-escalation-exactness; thm:mixed-interface-overclaim-skeleton; thm:presentation-scoped-boundary-normal-form; thm:five-axis-upgrade-obstruction; thm:current-boundary-skeleton-non-gluing; prop:certificate-constructor-bad-subrecord-extractor; prop:publication-safety-maximality; cor:publication-safety-current-package-instance; cor:finite-record-gate-soundness-boundary; thm:implementation-soundness-extension-criterion; cor:submitted-gate-implementation-contract-dichotomy; thm:external-interface-projection-no-free-upgrade','main.tex:2786-3997','Main conditional finite-record publication-safety chain and maximality/non-gluing/no-free-upgrade boundaries.','Keep in scope; state dependence on external record-gate soundness prominently.'),
('prop:current-package-acceptance-certificate-ledger; thm:current-package-certificate-exactness; thm:manual-ledger-dependence-boundary; cor:row-frozen-current-package-invariance; thm:current-package-extension-coordinate-rigidity; thm:current-package-semantic-non-escalation; thm:named-boundary-positive-coordinate-classification; cor:current-package-path-verified-instantiation','main.tex:4097-4721','Current-package ledger, row-frozen exactness, rigidity, semantic non-escalation, and positive-coordinate classification.','Keep in scope; update row/log references after package edits.'),
('lem:gate-witness-criterion; prop:path-complete-case-witnesses; prop:review-bundle-case-snapshot-coverage; thm:case-witness-skeleton-rigidity','main.tex:4824-5036','Case-study witness protocol for intake, overlap/submitted blocking, fake-extension rejection, and artifact boundaries.','Keep each case as gate, observed issue, safe lesson, and evidence level.'),
('audit:fresh-venue-record-criterion; thm:venue-rule-freshness-non-escalation; cor:historical-venue-record-non-escalation; cor:upload-time-venue-compliance-record-requirement; prop:round-five-venue-record-instantiation; audit:venue-submission-pack-gate; audit:submission-artifact-role-separation','main.tex:5179-5467','Venue freshness, historical-route boundary, upload-time requirement, and artifact role separation.','Refresh live venue checks near submission; do not claim acceptance or upload.'),
('prop:formal-source-gate-instantiation; thm:formal-source-promotion-obstruction; thm:evidence-level-overclaim-obstruction; thm:finite-witness-manifest-record-interface; cor:artifact-semantic-validity-boundary; prop:primary-claim-row-classification; prop:primary-inventory-freshness-criterion; prop:primary-supplement-interface-map','main.tex:5559-6062','Formal-source, evidence-level, finite-witness, artifact-semantic, primary-claim, and primary/supplement boundaries.','Keep finite-witness manifests distinct from semantic artifact validation.'),
('thm:exact-inclusion-support-surface-realization; thm:public-branch-archive-equivalent-realization; cor:submission-time-support-instantiation-test; thm:final-support-surface-closure; thm:workspace-final-package-reconciliation; thm:support-surface-normal-form; thm:support-surface-invariant-compression; thm:upload-or-archive-instantiation-boundary; cor:upload-or-archive-instantiation-record; prop:no-external-instantiation-from-local-bundle-records; prop:upload-or-archive-instantiation-update-protocol; cor:current-no-receipt-support-surface-non-escalation; cor:fresh-inventory-digest-instance-this-source-state; thm:digest-closure-refresh-criterion; thm:submission-support-refresh-rigidity; prop:primary-architectural-fallback-without-external-support','main.tex:6311-7245','Support-surface, archive-equivalence, digest closure, refresh rigidity, no-receipt, and fallback architecture machinery.','Do not promote local digest closure to external support without post-change refresh, locator, or receipt rows.'),
('thm:deterministic-theorem-environment-extractor-boundary; thm:extractor-domain-exactness-non-gluing; thm:final-byte-extractor-inventory-inclusion; thm:theorem-inventory-proofchecker-obstruction; prop:manual-theorem-inventory-boundary; prop:regenerated-theorem-inventory-digest-closure; cor:current-theorem-inventory-digest-instance; prop:post-inventory-fixed-point-support-certificate; thm:post-inventory-finite-record-realization; thm:theorem-obligation-ledger-boundary; prop:post-inventory-support-tuple-extraction-certificate; prop:submitted-theorem-inventory-availability','main.tex:7233-7832','Theorem-inventory/extractor boundary, non-gluing, proofchecker obstruction, digest closure, realization, and submitted ledger.','Keep syntactic coverage separate from proof correctness; this inventory supplies the missing artifact.'),
('prop:submission-support-instantiation-field-normal-form; cor:current-local-support-normal-form; audit:review-bundle-availability-condition; audit:case-snapshot-non-rerun-boundary; thm:finite-row-case-evidence-closure; cor:current-case-behaviour-evidence-criterion','main.tex:7858-8107','Review-bundle availability, absent external-support fields, local support, case non-rerun boundary, and finite-row case closure.','Preserve local/conditional status where upload/archive receipt is absent.'),
('audit:command-run-boundary-inventory; thm:post-edit-rerun-metadata-gate; thm:final-local-support-state-reconciliation; thm:presentation-route-five-interface-sharpness; thm:submission-support-fixed-point-normal-form; cor:presentation-summary-non-escalation; thm:post-inventory-support-coordinate-dichotomy; prop:final-refreshed-coordinate-instantiation; thm:post-inventory-package-fixed-point; cor:current-post-inventory-realization; thm:current-inventory-artifact-realization; thm:current-command-result-closure; cor:current-post-inventory-support-tuple-instantiation; cor:stable-replay-post-inventory-tuple; prop:post-inventory-freshness-obstruction; cor:local-fixed-point-external-boundary; thm:four-coordinate-submission-support-skeleton','main.tex:8164-9149','Final command-boundary, post-edit rerun, five-interface sharpness, fixed point, command-result closure, freshness obstruction, replay, and four-coordinate skeleton.','Rerun extractor/verifiers/digest after writing inventory before asserting final-byte fixed point.')
]
covered=set()
for c in clusters:
    covered.update(re.findall(r'\b(?:def|lem|prop|thm|cor|audit|prin):[A-Za-z0-9_.:-]+', c[0]))
if sorted(set(labels)-covered):
    raise SystemExit('uncovered labels: '+repr(sorted(set(labels)-covered)))
obj={
 'valid': True,
 'in_scope_present':[row(*c) for c in clusters],
 'missing_in_scope_results':[
  row('theorem_inventory.json; theorem_inventory.md','root package files','Required by the manuscript theorem-obligation ledger and post-inventory support coordinate, but absent at the start of this review.','Create both files with complete label coverage and retain them as load-bearing support artifacts.'),
  row('fresh post-inventory verifier/digest logs','main.tex:8757-8792; review_bundle/','The fixed-point theorem requires inventory write followed by extractor, verifiers, optional venue check, and digest generation; existing logs cannot certify newly written inventory bytes until rerun.','After accepting this inventory, rerun the manuscript-specified command sequence and regenerate FINAL_DIGESTS_SHA256.md.')],
 'weak_in_scope_core_results':[
  row('thm:publication-safety-interface','main.tex:2786','Correctly conditional on record-gate soundness, but title/abstract wording may read as stronger end-to-end publication safety.','Keep in scope and keep conditional finite-record boundary prominent; do not demote.'),
  row('thm:presentation-route-five-interface-sharpness','main.tex:8447','Headline route result packages several conditional/local interfaces; without upload/archive coordinate it is not unconditional submission-readiness.','Keep as route theorem while stating exact supplemental upload or archive-equivalent locator as a condition.'),
  row('thm:current-package-certificate-exactness','main.tex:4207','Exact only relative to declared schema and ledger rows; it does not validate proof semantics or all prose claims.','Retain schema-relative qualifiers and avoid semantic proof-checking claims.'),
  row('thm:deterministic-theorem-environment-extractor-boundary','main.tex:7233','Extractor covers labelled definition/lemma/proposition/theorem/corollary environments in main.tex only and excludes proof semantics.','Keep syntactic boundary explicit; do not use extractor success as proof correctness.')],
 'proof_gaps':[
  row('audit:command-run-boundary-inventory','main.tex:8164-8181','Command rows name refreshed logs, but post-inventory rows must be rerun after these inventory files exist.','Rerun command rows after writing inventory and regenerate digest/logs.'),
  row('thm:post-inventory-package-fixed-point','main.tex:8757-8792','Current-instance use is conditional until the ordered post-inventory procedure succeeds.','Treat fixed-point corollaries as conditional until rerun sequence succeeds.'),
  row('cor:current-post-inventory-realization; thm:current-inventory-artifact-realization; cor:current-post-inventory-support-tuple-instantiation; cor:stable-replay-post-inventory-tuple','main.tex:8856-9069','These depend on accepted inventory bytes and replay/digest metadata and become stale after inventory edits.','Refresh logs and digest or mark current-realization claims conditional.'),
  row('prop:manual-theorem-inventory-boundary','main.tex:7459','Theorem environment has prop: label prefix, creating a style/interface mismatch despite resolvable references.','Later TeX repair should align environment and label prefix; no TeX edit in this stage.'),
  row('source_interface_record.json','main.tex:487-872; review_bundle/verify_source_interface_record.py','Source-interface proof is path/line/label comparison to a pinned snapshot, not independent BEDC theorem semantics.','Require fresh BEDC/Lean logs for any semantic-source upgrade.'),
  row('record-gate soundness interface','main.tex:1144-1176; main.tex:2786','Record-gate soundness is an external predicate/hypothesis, not proved for actual gate programs.','State gate-implementation soundness only as a stronger reading requiring extra records.'),
  row('venue and bibliography freshness','main.tex:5179-5396; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-08.log','Live route and bibliography checks are date-sensitive and do not certify acceptance or upload-time status.','Refresh before submission or phrase as dated route-readiness only.'),
  row('review_bundle external support','main.tex:6311-7013; main.tex:7969','Local bundle paths and digest rules exist, but no DOI, upload receipt, or public byte-equality receipt is present.','Upload exact bundle or supply archive-equivalent locator with byte equality.')],
 'supporting_appendix_or_background':[
  row('Lean theorem prover background','references.bib:25','External formal-verification infrastructure; the paper does not introduce a new prover or prove Lean correctness.','Keep as background citation.'),
  row('LeanDojo and Draft-Sketch-Prove background','references.bib:37; references.bib:44','Motivates advisory AI theorem-proving roles, not part of the new theorem chain.','Use only for context.'),
  row('Archive of Formal Proofs mining background','references.bib:54','Classical/background context for proof repositories and mining.','Keep citation need explicit when discussing repository scale.'),
  row('bedc-newmath-source; automath-publication-pipeline; auditable-pipeline-review-bundle','references.bib:1; references.bib:9; references.bib:17','Source/support artifacts for the local case study, not independent mathematical theorems.','Use as artifact citations with path/commit/digest boundaries.'),
  row('submission_abstract.tex','submission_abstract.tex:1','Primary presentation text has no theorem-like environments and is supported by main.tex/review_bundle.','Keep theorem inventory scoped to main.tex labels while mapping primary claims to support.')],
 'out_of_scope_strong_results':[
  row('gate implementation soundness for actual daemon/checker programs','main.tex:1754-1819; main.tex:3862-3997','Finite-record acceptance is separated from proving all gate implementations satisfy specifications.','Do not force into this presentation paper.',candidate_title='Implementation Soundness for Auditable Mathematics Publication Gates',source_contribution='Stage A isolates record-gate soundness as an external interface and identifies coordinates needed for upgrade.',scope_mismatch='The current paper is architecture and finite-record boundaries, not full gate-program verification.',independent_paper_rationale='A separate paper could specify gate programs and prove implementation/specification equivalence.',needed_to_split=['Formal gate specs','Fresh command logs and fixtures','Implementation/specification proof evidence','Environment-drift threat model']),
  row('semantic validation of Rule110/GroundCompiler and finite-witness artifacts','main.tex:5742-5862; review_bundle/case_snapshots/','Artifact evidence is manifest-bounded/path-verified; dynamic semantic validation is out of scope.','Keep only bounded manifest/case evidence here.',candidate_title='Dynamic Artifact Validation for Finite-Witness Mathematical Software Pipelines',source_contribution='Stage A identifies artifact-semantic validation as a missing upgrade coordinate.',scope_mismatch='Would broaden the paper into artifact validation.',independent_paper_rationale='Case snapshots and negative boundaries can seed a validation study.',needed_to_split=['Evaluator contracts','Fresh rerun logs','Semantic oracles','Failure taxonomy']),
  row('complete BEDC theory exposition and fresh Lean/BEDC rebuild','main.tex:487-872; main.tex:5559-5667','The paper imports bounded source-interface rows but not complete BEDC exposition or fresh rebuild.','Do not expand into a BEDC theory paper.',candidate_title='Source-Theory Verification Interfaces for BEDC/newmath',source_contribution='Stage A separates pinned source-interface extraction from semantic source verification.',scope_mismatch='Full BEDC/Lean verification would dominate the presentation route.',independent_paper_rationale='The source-interface record gives a boundary for future formal-source verification.',needed_to_split=['Fresh Lean/BEDC build logs','Axiom-purity records','Marker-resolution audits','Full BEDC obligation exposition'])],
 'split_candidates':[
  row('finite-record certificate calculus','main.tex:963-3997','In scope here, but the abstract seven-field calculus may be independent of the case study.','Keep only minimal calculus needed here; split only if expanded.',candidate_title='A Finite-Record Calculus for Auditable Publication Claims',source_contribution='Stage A identifies schema, stronger-reading preorder, bad-subrecord obstruction, extension budget, and non-gluing pattern.',scope_mismatch='Standalone calculus needs more formal examples than this route can carry.',independent_paper_rationale='Reusable for other mathematical-software audit pipelines.',needed_to_split=['Path-independent model','Machine-checkable schema semantics','Examples outside automath','Comparison with provenance systems']),
  row('support-surface archive-equivalence theory','main.tex:6311-7013','Support-surface normal forms may exceed the core architecture narrative if generalized.','Use only exact upload/archive condition needed for this route.',candidate_title='Archive-Equivalent Support Surfaces for Computational Mathematics Submissions',source_contribution='Stage A isolates exact inclusion, locator, digest closure, no-receipt non-escalation, and update protocols.',scope_mismatch='General archive policy is adjacent infrastructure.',independent_paper_rationale='Could formalize byte-level support surfaces for reproducible submissions.',needed_to_split=['Archive model','Digest threat model','Multiple archive case studies','Recommended workflow']),
  row('theorem-inventory extractor as proof-obligation ledger tool','main.tex:7233-7832; review_bundle/extract_theorem_environments.py','In scope as support infrastructure, but tool design/evaluation could be separate.','Keep only syntactic coverage and non-proofchecker boundary here.',candidate_title='Syntactic Theorem-Inventory Ledgers for AI-Assisted Mathematical Writing',source_contribution='Stage A produces labelled-environment coverage and separates inventory completeness from proof correctness.',scope_mismatch='Tool paper needs UX, benchmarking, and integration details.',independent_paper_rationale='Reusable for LaTeX-heavy formal mathematics pipelines.',needed_to_split=['Manuscript corpus','Extraction metrics','CI/proof-assistant integration','Human semantic review protocol']),
  row('prior L0/L1/L2 universality hierarchy ledger','prompt prior research ledger context','Earlier EML/Zeckendorf/certificate-universality hierarchy is unrelated to this pipeline paper.','Do not import those results into this article.',candidate_title='Single-Primitive Universality Hierarchies and Certificate Universality',source_contribution='Earlier Stage A found expression/protocol/certificate universality, Zeckendorf arithmetic, Hankel-Prony fibers, and strict finite-state covers.',scope_mismatch='Algebraic/computability universality is not software-workflow audit architecture.',independent_paper_rationale='The ledger already gives a coherent separate mathematical theorem chain.',needed_to_split=['Dedicated scope contract','Full universality proofs','Separate bibliography/inventory','No dependence on this paper'])],
 'irrelevant_or_remove':[
  row('duplicated or over-detailed support-boundary theoremization','main.tex:6311-9149','Many support-coordinate statements are valid bookkeeping but too numerous for the two-page narrative.','Do not delete core claims here; later compress presentation text while keeping supplement coverage.'),
  row('root-level temporary extraction files','_*.json; *.tmp.json; theorem_items.tsv; _stage_a_numbered_envs.txt','Scratch extraction files are not submitted support unless manifest/digest promotes them.','Keep out of manuscript claims and final support bundle unless intentionally promoted.'),
  row('prior review verdicts','P4_REVIEW.md; stage_a_audit.json; oracle_stage_a_escalation.json','Prompt says to ignore previous review verdicts unless quoted; they are not source contract files.','Do not rely on them as proof evidence.')],
 'naive_truncation_risks':[
  row('row-frozen current-package invariance','main.tex:4410; main.tex:4207','Edits to records/logs/inventory bytes can be mistaken for invariant package truth unless row-frozen source state is enforced.','After support-file edits, rerun checks and digest or retain only previous source-state claim.'),
  row('post-inventory fixed point','main.tex:8757-8792','A digest generated before inventory/verifier refresh is not invariant under later inventory edits.','Use ordered post-inventory rerun; never use pre-inventory logs for final bytes.'),
  row('source-interface import','main.tex:487-872','Pinned ranges and labels can be misread as semantic invariants across source revisions.','Require path, commit, digest, line range, and label match before import.'),
  row('review-bundle/archive-equivalence','main.tex:6311-7013; review_bundle/FINAL_DIGESTS_SHA256.md','Local digest rows do not descend to public archive or venue-upload support automatically.','Require archive-equivalent locator or upload receipt field.'),
  row('case-study snapshots','main.tex:4924-5127; main.tex:8023-8054','Historical snapshots can be mistaken for current daemon/artifact behavior.','State gate, issue, safe lesson, evidence level; require fresh reruns for operational claims.'),
  row('venue freshness','main.tex:5179-5396','Dated route-readiness checks decay as venue pages and rules change.','Refresh immediately before submission and avoid timeless venue claims.')],
 'journal_style_gaps':[
  row('two-page CICM presentation compression','submission_abstract.tex; main.tex:90-150','The supplement has 131 theorem-like environments, too many for the presentation narrative.','Use submission_abstract.tex as readable paper and main.tex as supplement.'),
  row('conditional theorem titles and claims','main.tex:2786; main.tex:8447; submission_abstract.tex:35-43','Titles like publication safety may look stronger than conditional finite-record content.','Preserve prominent qualifiers: record-gate soundness, finite-record only, no venue acceptance.'),
  row('bibliography live verification','references.bib; review_bundle/VENUE_BIBLIOGRAPHY_LIVE_CHECK_2026-06-08.md','Small bibliography is artifact-heavy and route locators are live/date-sensitive.','Refresh official links before submission and separate artifacts from peer-reviewed citations.'),
  row('notation density','main.tex:963-3997','Certificate calculus notation is heavy for a software-workshop audience.','Add/retain a symbol-to-workflow table in presentation and defer formalism to supplement.'),
  row('label-prefix consistency','main.tex:7459','Theorem environment labelled prop:manual-theorem-inventory-boundary is stylistically inconsistent.','Repair in later TeX stage by aligning environment and label prefix.'),
  row('overfull boxes in final compile','compile_stage_a2_theoremization_round1_2026-06-08_xelatex_final.log','Final compile has many overfull hbox warnings, including long path/table/theorem lines.','Perform layout pass after theorem inventory and logs stabilize.')]
}
Path('theorem_inventory.json').write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory','', 'Stage A inventory for `2026_auditable_theory_to_paper_pipeline`. This mirrors `theorem_inventory.json` and does not edit TeX sources.']
for k,v in obj.items():
    if k=='valid': continue
    md += ['', '## '+k]
    if not v: md.append('- *(none)*')
    for r in v:
        md.append(f"- **{r['label']}** (`{r['location']}`): {r['reason']} Required action: {r['required_action']}")
        for ek in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale','needed_to_split']:
            if ek in r:
                val=r[ek]
                md.append(f"  - {ek}: " + ('; '.join(val) if isinstance(val,list) else str(val)))
Path('theorem_inventory.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print(json.dumps(obj,ensure_ascii=False))
