import json, pathlib
inventory = {
  "valid": True,
  "in_scope_present": [
    {"label":"prop:primitive-symbolic-exclusion; cor:primitive-symbolic-summability-exclusion; rem:symbolic-product-role","location":"sec_preliminaries.tex:4; sec_preliminaries.tex:64; sec_preliminaries.tex:94","reason":"Classical finite-state zeta determinant/Euler product is present, including primitive-orbit Mobius inversion and separation from trace-class summability.","required_action":"Keep as preliminary/background with citations; do not present as new."},
    {"label":"prop:fredholm-witt-bridge; rem:witt-arithmetic-flexibility; rem:witt-versus-cyclic-data; prop:cyclic-witt-compatibility","location":"sec_fredholm_witt_cyclic.tex:15; sec_fredholm_witt_cyclic.tex:100; sec_fredholm_witt_cyclic.tex:110; sec_fredholm_witt_cyclic.tex:136","reason":"Fredholm-Witt identity and cyclic-data Witt-coordinate formula are present, with the clarification that trace-class Witt coordinates are complex and not cyclic divisor multiplicities.","required_action":"Retain as notation bridge; keep finite-state arithmetic remarks subordinate."},
    {"label":"def:cyclic-data-trace-budget; lem:single-cyclic-block-spectrum; lem:finite-cyclic-truncation-determinant; lem:direct-cyclic-weierstrass-product; lem:cyclic-product-trace-norm-limit; lem:choice-of-roots; prop:cyclic-data-construction-interface","location":"sec_fredholm_cyclic_construction.tex:47; sec_fredholm_cyclic_construction.tex:105; sec_fredholm_cyclic_construction.tex:142; sec_fredholm_cyclic_construction.tex:188; sec_fredholm_cyclic_construction.tex:274; sec_fredholm_cyclic_construction.tex:370; sec_fredholm_cyclic_construction.tex:417","reason":"Core cyclic datum, positive-exponent determinant convention, product convergence, trace-norm direct-sum construction, and root-choice unitary invariance are present.","required_action":"Keep as construction backbone; preserve finite-subset/local-uniform product convention."},
    {"label":"def:closed-nonzero-support; lem:normal-support-range-closure; prop:sharp-trace-budget-support-obstruction; prop:collapsed-spectral-multiplicities","location":"sec_fredholm_cyclic_construction.tex:553; sec_fredholm_cyclic_construction.tex:566; sec_fredholm_cyclic_construction.tex:598; sec_fredholm_cyclic_construction.tex:707","reason":"Closed support/range convention and collapsed multiplicity function M_D are present and feed the central trace-budget identity.","required_action":"Keep in core; do not weaken because these support normal classification and full-fiber minimization."},
    {"label":"prop:fredholm-regularized-zero-divisor-correspondence; lem:fredholm-spectral-rigidity; lem:product-side-cyclic-divisor-multiplicity","location":"sec_fredholm_threshold_classification.tex:4; sec_fredholm_threshold_classification.tex:71; sec_fredholm_threshold_classification.tex:102","reason":"Fredholm/regularized zero-divisor correspondence and product-side cyclic divisor multiplicity interface are present and force the collapsed non-zero eigenvalue multiset.","required_action":"Keep as proof interface; cite classical Fredholm determinant and zero-divisor results explicitly."},
    {"label":"thm:normal-realizability-threshold","location":"sec_fredholm_threshold_classification.tex:163","reason":"Exact trace-class threshold for cyclic data is present, including equivalence of summability, normal trace-class realization, trace-class realization, and forced trace budget inequality.","required_action":"Keep as main in-scope theorem; preserve positive-exponent determinant and finite-subproduct interpretation."},
    {"label":"thm:collapsed-multiset-normal-realisation; cor:arbitrary-collapsed-multiset-normal-realisation; thm:cyclic-fredholm-realisation; def:block-cyclic-normal-realisation; lem:cyclic-sum-range-closure; cor:block-cyclic-rigidity; cor:finite-rank-realisation; rem:summability-sharpness","location":"sec_fredholm_threshold_classification.tex:282; sec_fredholm_threshold_classification.tex:360; sec_fredholm_threshold_classification.tex:423; sec_fredholm_threshold_classification.tex:628; sec_fredholm_threshold_classification.tex:640; sec_fredholm_threshold_classification.tex:714; sec_fredholm_threshold_classification.tex:788; sec_fredholm_threshold_classification.tex:774","reason":"Normal realization/classification is present: determinant data collapse to M_D, normal realizations are classified up to zero summands, and finite Euler products give finite-rank models.","required_action":"Keep in main theorem chain; foreground collapsed-multiset classification rather than cyclic packaging."},
    {"label":"rem:nonnormal-obstruction-after-realisation","location":"sec_fredholm_threshold_classification.tex:580","reason":"Structural bad example is present: quasinilpotent/nonnormal determinant-invisible freedom shows normality cannot be dropped from normal classification.","required_action":"Retain as structural mechanism, not merely an anecdotal example."},
    {"label":"lem:weyl-ky-fan-trace-class; lem:weyl-fan-schatten-p-sum; lem:ordered-nonzero-root-flag; lem:ringrose-prescribed-diagonal; lem:trace-norm-schur-compressions; lem:schatten-schur-compressions","location":"sec_fredholm_spectral_rigidity.tex:46; sec_fredholm_spectral_rigidity.tex:89; sec_fredholm_spectral_rigidity.tex:141; sec_fredholm_spectral_rigidity.tex:197; sec_fredholm_spectral_rigidity.tex:434; sec_fredholm_spectral_rigidity.tex:466","reason":"Classical analytic operator-theory tools needed for lower bounds and Schur/Ringrose triangularization are present.","required_action":"Classify as supporting classical inputs with citations, not new contributions."},
    {"label":"lem:two-by-two-trace-norm-pinching; lem:two-by-two-schatten-pinching; lem:uniform-two-by-two-schatten-modulus; lem:trace-triangular-equality-pinching; lem:zero-sector-schur-elimination-equality-fiber; lem:schatten-triangular-equality-pinching","location":"sec_fredholm_spectral_rigidity.tex:285; sec_fredholm_spectral_rigidity.tex:329; sec_fredholm_spectral_rigidity.tex:380; sec_fredholm_spectral_rigidity.tex:518; sec_fredholm_spectral_rigidity.tex:590; sec_fredholm_spectral_rigidity.tex:659","reason":"New pinching/equality mechanism is present, including zero-sector elimination needed for full nonnormal-fiber minimizer rigidity.","required_action":"Keep in core proof chain; load-bearing for equality rigidity."},
    {"label":"thm:determinant-fiber-trace-minimality","location":"sec_fredholm_spectral_rigidity.tex:772","reason":"Main full trace-class determinant-fiber theorem is present: sharp trace-norm lower bound, cyclic model attainment, and equality iff normal cyclic model plus zero summand.","required_action":"Keep as central IEOT theorem; do not demote or move to appendix."},
    {"label":"cor:schur-entry-stability; prop:finite-chosen-schur-window-distance-bound; thm:tail-controlled-trace-distance; cor:chosen-tail-stability-criterion; thm:uniform-chosen-schur-tail-modulus; thm:finite-dimensional-trace-stability; prop:two-by-two-square-root-sharpness","location":"sec_fredholm_spectral_rigidity.tex:958; sec_fredholm_spectral_rigidity.tex:1033; sec_fredholm_spectral_rigidity.tex:1115; sec_fredholm_spectral_rigidity.tex:1236; sec_fredholm_spectral_rigidity.tex:1287; sec_fredholm_spectral_rigidity.tex:1401; sec_fredholm_spectral_rigidity.tex:2155","reason":"Trace-minimizer stability package is present and tied to chosen Schur tails, finite windows, finite-dimensional square-root stability, and sharp obstruction.","required_action":"Keep as in-scope consequence; preserve chosen-tail hypotheses."},
    {"label":"def:finite-weyl-horn-body; lem:zero-inclusive-finite-horn-theorem; lem:zero-inclusive-log-majorization-fan-dominance; thm:finite-dimensional-weyl-horn-cyclic-determinant-fiber; prop:finite-horn-subordinate-trace-chain; cor:universal-finite-dimensional-symmetric-gauge-minimization; prop:strict-weak-majorization-gauge-rigidity; cor:finite-dimensional-gauge-minimizer-taxonomy; prop:arbitrary-gauge-taxonomy-sharpness; cor:exact-fixed-dimensional-schatten-budget-range; cor:horn-boundary-trace-stability","location":"sec_fredholm_spectral_rigidity.tex:1538; sec_fredholm_spectral_rigidity.tex:1557; sec_fredholm_spectral_rigidity.tex:1631; sec_fredholm_spectral_rigidity.tex:1683; sec_fredholm_spectral_rigidity.tex:1768; sec_fredholm_spectral_rigidity.tex:1830; sec_fredholm_spectral_rigidity.tex:1890; sec_fredholm_spectral_rigidity.tex:1940; sec_fredholm_spectral_rigidity.tex:1995; sec_fredholm_spectral_rigidity.tex:2053; sec_fredholm_spectral_rigidity.tex:2105","reason":"Research-directive Weyl-Horn package is present: zero-inclusive Horn/Li-Mathias interface, exact fixed-dimensional singular-value body, gauge minimization, equality taxonomy, sharpness example, budget range, and Horn-boundary reading.","required_action":"Keep as finite-dimensional consequence; retain no-cross-dimensional-descent warning."},
    {"label":"def:regularized-determinant-normalization; lem:regularized-determinant-extension-cyclic-factor; prop:regularized-zero-divisor-chain; lem:regularized-cyclic-finite-subset-products; thm:schatten-cyclic-model-membership; thm:schatten-cyclic-regularized-determinant; cor:regularized-controlled-extension-scope; prop:regularized-domain-boundary; lem:regularized-determinant-spectral-rigidity; lem:schatten-collapsed-multiplicities; thm:schatten-determinant-fiber-minimality; thm:schatten-forced-prescribed-budget-obstruction; cor:prescribed-schatten-finite-skeleton-freezing; prop:prescribed-schatten-chain-scope; cor:schatten-prescribed-budget-boundary; prop:schatten-natural-domain-budget-boundary; thm:finite-dimensional-schatten-stability","location":"sec_fredholm_cyclic_construction.tex:830; sec_fredholm_cyclic_construction.tex:850; sec_fredholm_cyclic_construction.tex:891; sec_fredholm_cyclic_construction.tex:979; sec_fredholm_cyclic_construction.tex:1046; sec_fredholm_cyclic_construction.tex:1081; sec_fredholm_cyclic_construction.tex:1255; sec_fredholm_cyclic_construction.tex:1300; sec_fredholm_spectral_rigidity.tex:494; sec_fredholm_spectral_rigidity.tex:2220; sec_fredholm_spectral_rigidity.tex:2285; sec_fredholm_spectral_rigidity.tex:2441; sec_fredholm_spectral_rigidity.tex:2508; sec_fredholm_spectral_rigidity.tex:2580; sec_fredholm_spectral_rigidity.tex:2653; sec_fredholm_spectral_rigidity.tex:2701; sec_fredholm_spectral_rigidity.tex:2765","reason":"Prescribed-budget Schatten/regularized determinant extension advertised in abstract is present, including det_r normalization, sharp S_p budget, forced-budget obstruction, rigidity, finite-dimensional stability, and natural-domain boundary caveat.","required_action":"Keep only if enlarged Schatten scope remains intended; otherwise split coherently rather than weakening individual theorems."},
    {"label":"thm:cyclic-data-classification; thm:main-trace-class-rigidity; thm:trace-class-rigidity-consequences; cor:trace-rigidity-nonnormal-skeleton-package; cor:trace-rigidity-stability-boundary-package; cor:trace-rigidity-finite-horn-package; cor:determinant-intrinsic-trace-budget","location":"sec_fredholm_spectral_rigidity.tex:2914; sec_fredholm_spectral_rigidity.tex:3026; sec_fredholm_spectral_rigidity.tex:3113; sec_fredholm_spectral_rigidity.tex:3195; sec_fredholm_spectral_rigidity.tex:3219; sec_fredholm_spectral_rigidity.tex:3246; sec_fredholm_spectral_rigidity.tex:3306","reason":"Final synthesis theorem chain is present: determinant equality iff collapsed multiplicities agree, exact trace threshold, full-fiber minimizer rigidity, and organized downstream packages.","required_action":"Keep as main scope summary and use it to police downstream claims."}
  ],
  "missing_in_scope_results": [],
  "weak_in_scope_core_results": [
    {"label":"lem:zero-inclusive-finite-horn-theorem","location":"sec_fredholm_spectral_rigidity.tex:1557","reason":"Present, but journal-facing edge case remains: the proof relies on Li-Mathias covering zero eigenvalues and zero singular values directly.","required_action":"Verify the exact cited theorem/page and add a sentence or backup citation for the zero-inclusive rank-deficient case."},
    {"label":"thm:schatten-determinant-fiber-minimality; thm:schatten-forced-prescribed-budget-obstruction; prop:schatten-natural-domain-budget-boundary","location":"sec_fredholm_spectral_rigidity.tex:2285; sec_fredholm_spectral_rigidity.tex:2441; sec_fredholm_spectral_rigidity.tex:2701","reason":"The prescribed-budget Schatten extension is coherent but broad relative to the trace-class Fredholm determinant fiber promised by title/scope.","required_action":"Strengthen roadmap/dependency explanation, or split the regularized determinant chain if IEOT scope pressure is severe."}
  ],
  "proof_gaps": [
    {"label":"prop:fredholm-regularized-zero-divisor-correspondence","location":"sec_fredholm_threshold_classification.tex:4","reason":"Classical but load-bearing; exact det_r class assumptions and the passage from local logarithm to entire zero divisor should be pinned to references.","required_action":"Add precise references for regularized determinant analyticity/zero divisors and logarithmic expansion domain."},
    {"label":"lem:ringrose-prescribed-diagonal; lem:ordered-nonzero-root-flag","location":"sec_fredholm_spectral_rigidity.tex:141; sec_fredholm_spectral_rigidity.tex:197","reason":"Equality/stability proofs depend on a Ringrose/Schur basis with prescribed non-zero algebraic eigenvalue order and zero quotient tail; this is delicate in infinite compact settings.","required_action":"Ensure the invariant flag/root-space ordering is explicit and cite Ringrose for triangularization; state that the remaining quotient has spectrum {0}."},
    {"label":"lem:zero-sector-schur-elimination-equality-fiber","location":"sec_fredholm_spectral_rigidity.tex:590","reason":"Key new interface eliminating strict upper-triangular entries in the trace-norm equality case, including quasinilpotent zero sector; failure would break main minimizer classification.","required_action":"Final proof review should check finite Schur compression limits and entries crossing into the zero sector."},
    {"label":"thm:normal-realizability-threshold; lem:product-side-cyclic-divisor-multiplicity","location":"sec_fredholm_threshold_classification.tex:102; sec_fredholm_threshold_classification.tex:163","reason":"Necessity depends on product-side finite-subset convergence implying divisor multiplicity inclusion for every cyclic root, a subtle directed-net divisor-stability argument.","required_action":"Make the isolating disk and Hurwitz/Rouche-style directed-net argument explicit enough for referees."},
    {"label":"cor:exact-fixed-dimensional-schatten-budget-range","location":"sec_fredholm_spectral_rigidity.tex:2053","reason":"Unboundedness proof changes one Schur off-diagonal entry; this preserves determinant but should not be confused with staying in a fixed unitary orbit.","required_action":"Add a clarifying sentence that only eigenvalues/characteristic polynomial are preserved."}
  ],
  "supporting_appendix_or_background": [
    {"label":"Classical finite-state zeta and primitive orbit background","location":"sec_preliminaries.tex:4; sec_preliminaries.tex:64; sec_preliminaries.tex:94","reason":"Sets notation and excludes conflation with finite-state symbolic dynamics; classical/background rather than new.","required_action":"Keep concise with citations; do not expand into symbolic dynamics theory."},
    {"label":"Classical Fredholm, Weyl-Ky Fan, Weyl-Fan, Ringrose, Horn-Li-Mathias inputs","location":"sec_fredholm_threshold_classification.tex:4; sec_fredholm_spectral_rigidity.tex:46; sec_fredholm_spectral_rigidity.tex:89; sec_fredholm_spectral_rigidity.tex:197; sec_fredholm_spectral_rigidity.tex:1557","reason":"External operator/matrix theory tools used to prove new determinant-fiber consequences.","required_action":"State as cited interfaces; avoid implying new proofs of classical theorems."},
    {"label":"thm:nonnormal-jordan-classification; prop:zero-part-freedom-interface; def:root-space-equivalence-relations; lem:compact-riesz-root-space-quasinilpotent-complement; thm:quasinilpotent-stabilization-nonzero-invariants; thm:stable-nonzero-skeleton-classification; def:finite-support-skeleton-quotient; thm:finite-support-quasinilpotent-quotient; prop:zero-sector-invisibility-obstruction; lem:finite-support-quotient-closure-order; thm:nonnormal-quotient-degeneration; cor:nonnormal-fiber-unbounded; rem:algebraic-partitions-not-unitary-classes","location":"sec_appendix_finite_skeleton.tex:22; sec_appendix_finite_skeleton.tex:218; sec_appendix_finite_skeleton.tex:278; sec_appendix_finite_skeleton.tex:295; sec_appendix_finite_skeleton.tex:339; sec_appendix_finite_skeleton.tex:401; sec_appendix_finite_skeleton.tex:482; sec_appendix_finite_skeleton.tex:550; sec_appendix_finite_skeleton.tex:601; sec_appendix_finite_skeleton.tex:712; sec_appendix_finite_skeleton.tex:765; sec_appendix_finite_skeleton.tex:840; sec_appendix_finite_skeleton.tex:955","reason":"Finite non-zero skeleton quotient is appendix-level structure explaining residual nonnormal freedom and quasinilpotent zero-sector invisibility; not needed for main trace-class threshold/minimizer proof.","required_action":"Keep as appendix/support if length allows; otherwise split without weakening main chain."}
  ],
  "out_of_scope_strong_results": [
    {"label":"regularized-Schatten-prescribed-budget-package","location":"sec_fredholm_cyclic_construction.tex:830-1329; sec_fredholm_spectral_rigidity.tex:2220-2889","reason":"Strong present package but broadens the paper from trace-class Fredholm determinant fibers to regularized determinants and Schatten-budget theory.","required_action":"Consider as split-paper material if shortening is needed; if retained, keep prescribed-budget/natural-domain warnings prominent.","candidate_title":"Prescribed cyclic divisors for regularized Schatten determinants","source_contribution":"Stage A found a complete chain for det_r normalization, exact S_p cyclic-model membership, forced finite prescribed budget, minimization/equality rigidity, and finite-dimensional S_p stability.","scope_mismatch":"The core paper concerns trace-class Fredholm determinant fibers; this chain uses regularized determinants and a prescribed finite-budget subfiber rather than the full natural det_r domain.","independent_paper_rationale":"The package has its own threshold, normalization, boundary obstruction, and rigidity theorem.","needed_to_split":["Move det_r normalization and cyclic-factor formulas to a new paper.","Import collapsed multiplicity and triangular pinching interfaces.","State natural-domain boundary as a main limitation.","Leave only a short outlook in the current paper."]},
    {"label":"finite-nonzero-skeleton-quotient-package","location":"sec_appendix_finite_skeleton.tex:22-961","reason":"Substantial finite-support nonnormal quotient and degeneration theory after ignoring trace-class quasinilpotent zero summands.","required_action":"Keep as appendix only if it supports the narrative; otherwise split as finite-skeleton classification.","candidate_title":"Finite non-zero skeleton quotients in trace-class determinant fibers","source_contribution":"Stage A identified finite Jordan-profile data away from zero while the quasinilpotent zero sector remains determinant-invisible and stabilizing.","scope_mismatch":"The main IEOT article needs only nonnormal freedom and equality-rigidity obstruction, not full quotient/closure-order classification.","independent_paper_rationale":"Quotient, closure order, stabilization invariants, and degeneration at sharp budget form an independent classification story.","needed_to_split":["Extract Riesz root-space and quasinilpotent stabilization preliminaries.","State finite-support hypotheses independently.","Develop closure-order and sharp-budget degeneration as main results.","Retain a short obstruction example in current article."]}
  ],
  "split_candidates": [
    {"label":"fixed-dimensional-Weyl-Horn-fiber-geometry","location":"sec_fredholm_spectral_rigidity.tex:1538-2135","reason":"Currently in scope by research directive, but can stand alone if narrowing around trace-class rigidity is required.","required_action":"Retain unless journal length/scope pressure requires separation.","candidate_title":"Weyl-Horn bodies of finite cyclic determinant fibers","source_contribution":"Stage A added exact singular-value image, universal symmetric-gauge minimization, exact Schatten-budget range, and Horn-boundary trace stability reading.","scope_mismatch":"Finite-dimensional matrix geometry derived from collapsed divisor, while central paper is infinite-dimensional trace-class Fredholm determinant rigidity.","independent_paper_rationale":"Horn body, gauge taxonomy, sharp non-strict-gauge example, and budget-range/unboundedness results form a compact matrix-theoretic article.","needed_to_split":["Import collapsed cyclic divisor notation.","Cite Horn/Li-Mathias realization.","Keep zero-padding/non-stable-Horn warnings.","Use trace-class paper as motivation."]},
    {"label":"chosen-Schur-tail-stability-theory","location":"sec_fredholm_spectral_rigidity.tex:958-1455; sec_fredholm_spectral_rigidity.tex:2105-2197; sec_fredholm_spectral_rigidity.tex:2765-2889","reason":"In-scope as consequence of minimizer rigidity but separable if the paper becomes too long.","required_action":"Keep tail hypotheses; do not replace by false basis-free global stability modulus.","candidate_title":"Schur-tail stability near trace-class determinant-fiber minimizers","source_contribution":"Stage A organized finite-window, chosen-tail, uniform chosen-Schur-tail, finite-dimensional trace, and prescribed-budget Schatten stability around pinching.","scope_mismatch":"Quantifies perturbative behavior beyond threshold/classification/minimizer theorem chain.","independent_paper_rationale":"Chosen-tail modulus and sharp square-root obstruction support a focused stability paper.","needed_to_split":["Extract triangular pinching lemmas.","Import determinant-fiber minimizer theorem.","Develop examples requiring tail hypotheses.","Separate trace-class and S_p variants."]}
  ],
  "irrelevant_or_remove": [
    {"label":"prior-ledger-single-primitive-universality-hierarchy","location":"prompt prior research ledger only; not in manuscript sources","reason":"L0/L1/L2 universality, Zeckendorf folds, Richardson/EML material, and finite-fiber certificate universality belong to a different paper and are not used here.","required_action":"Do not import or rediscover; keep only as out-of-scope ledger memory."}
  ],
  "naive_truncation_risks": [
    {"label":"finite-subset product convention for D_D","location":"sec_fredholm_cyclic_construction.tex:47-72; sec_fredholm_threshold_classification.tex:163-207","reason":"Countable cyclic determinant identity is locally uniform finite-subset convergence, not arbitrary truncation invariant without proof.","required_action":"Keep directed finite-subset convention and normal convergence proof."},
    {"label":"cyclic truncations L_D^(N)","location":"sec_fredholm_cyclic_construction.tex:274","reason":"Finite truncations approximate only through trace-norm convergence; individual truncation data are not determinant-fiber invariants of the infinite model.","required_action":"Retain trace-norm and locally uniform determinant convergence whenever truncations are used."},
    {"label":"finite Weyl-Horn bodies HWH(Lambda_D,N)","location":"sec_fredholm_spectral_rigidity.tex:1538-1555; sec_fredholm_spectral_rigidity.tex:1683; sec_fredholm_spectral_rigidity.tex:3246","reason":"Manuscript correctly treats HWH(Lambda_D,N) as fixed-dimensional; naive truncation would mistake zero-padded Horn bodies for a stable inverse system.","required_action":"Keep no-transition/no-descent warnings."},
    {"label":"chosen Schur windows and tail moduli","location":"sec_fredholm_spectral_rigidity.tex:958-1399","reason":"Finite Schur-window pinching controls selected entries only after basis and tails are chosen; naive truncation would yield a false basis-free global modulus.","required_action":"Preserve chosen-basis, compression-tail, and diagonal-tail hypotheses."},
    {"label":"regularized finite-subset cyclic products","location":"sec_fredholm_cyclic_construction.tex:979; sec_fredholm_spectral_rigidity.tex:2441","reason":"Regularized determinant product is a prescribed finite-subset net with exponential corrections; natural det_r-domain membership alone does not imply prescribed S_p budget.","required_action":"Keep finite-subset net hypotheses and natural-domain boundary proposition."}
  ],
  "journal_style_gaps": [
    {"label":"manuscript-length-and-scope-density","location":"main.tex:abstract; sec_introduction.tex:1; sec_fredholm_spectral_rigidity.tex:772-3306; sec_appendix_finite_skeleton.tex:1-961","reason":"Paper contains trace-class chain plus stability, Weyl-Horn, Schatten regularized, and finite-skeleton packages; ambitious for IEOT unless hierarchy is sharply signposted.","required_action":"Use synthesis theorem and roadmap to distinguish core from consequences; consider splitting one package if needed."},
    {"label":"classical-result-packaging","location":"sec_fredholm_spectral_rigidity.tex:46; sec_fredholm_spectral_rigidity.tex:89; sec_fredholm_spectral_rigidity.tex:197; sec_fredholm_spectral_rigidity.tex:1557","reason":"Several classical facts are stated as lemmas; acceptable for self-containment but must not obscure novelty.","required_action":"Mark classical lemmas explicitly and keep citations precise."},
    {"label":"notation-load","location":"sec_fredholm_cyclic_construction.tex:47; sec_fredholm_spectral_rigidity.tex:725-754; sec_fredholm_spectral_rigidity.tex:1538-1555","reason":"D_D, M_D, Sigma_D, tau_D,p, Lambda_D,N, HWH, det_r, and finite-subset conventions create high notation load.","required_action":"Maintain a consolidated notation block and cross-reference it from introduction."},
    {"label":"bibliography-coverage-for-new-Weyl-Horn-package","location":"references.bib:101; references.bib:123; references.bib:421; sec_fredholm_spectral_rigidity.tex:1557-1624","reason":"Horn, Li-Mathias, Weyl-Ky Fan, Ringrose, and regularized determinant references are present; zero-inclusive use should be referee-proofed.","required_action":"Double-check exact theorem/page citations and add backup reference if needed."},
    {"label":"LaTeX-reference-integrity","location":"main.log; all .tex files","reason":"Local scan found 114 labels, 414 references, and 99 citations with no undefined references or citations; main.log showed no undefined-reference warnings.","required_action":"Maintain after later edits; rerun LaTeX after final revisions."}
  ]
}
keys=["valid","in_scope_present","missing_in_scope_results","weak_in_scope_core_results","proof_gaps","supporting_appendix_or_background","out_of_scope_strong_results","split_candidates","irrelevant_or_remove","naive_truncation_risks","journal_style_gaps"]
assert list(inventory.keys()) == keys
pathlib.Path('theorem_inventory.json').write_text(json.dumps(inventory, indent=2, ensure_ascii=False), encoding='utf-8')
md=["# Stage A Theorem Inventory", "", "Paper: `2026_fredholm_determinants_cyclic_block_spectral_rigidity_jst`", "", "This inventory classifies theorem-like material against `scope_contract.md`, `scope_contract.json`, and `research_directive.md`. It does not edit manuscript `.tex` files.", ""]
for key in keys[1:]:
    md += [f"## {key}", ""]
    if not inventory[key]:
        md += ["- None.", ""]
        continue
    for item in inventory[key]:
        md.append(f"- **{item['label']}** (`{item['location']}`)")
        md.append(f"  - Reason: {item['reason']}")
        md.append(f"  - Required action: {item['required_action']}")
        for extra in ["candidate_title","source_contribution","scope_mismatch","independent_paper_rationale"]:
            if extra in item:
                md.append(f"  - {extra.replace('_',' ').title()}: {item[extra]}")
        if "needed_to_split" in item:
            md.append("  - Needed to split: " + "; ".join(item["needed_to_split"]))
    md.append("")
pathlib.Path('theorem_inventory.md').write_text('\n'.join(md), encoding='utf-8')
print('WROTE', len(inventory['in_scope_present']), 'in_scope items')
