import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Nat.Prime.Int
import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Topology.Instances.AddCircle.DenseSubgroup
import Mathlib.Tactic

namespace Omega.GU

private lemma prime_log_ratio_irrational {p q : ℕ} (hp : Nat.Prime p) (hq : Nat.Prime q)
    (hpq : p ≠ q) : Irrational (Real.log (p : ℝ) / Real.log (q : ℝ)) := by
  rw [Irrational]
  intro hRat
  rcases hRat with ⟨r, hr⟩
  let k : ℕ := Int.toNat r.num
  have hp_gt : 1 < (p : ℝ) := by exact_mod_cast hp.one_lt
  have hq_gt : 1 < (q : ℝ) := by exact_mod_cast hq.one_lt
  have hp_pos : 0 < (p : ℝ) := by positivity
  have hq_pos : 0 < (q : ℝ) := by positivity
  have hp_log_pos : 0 < Real.log (p : ℝ) := Real.log_pos hp_gt
  have hq_log_pos : 0 < Real.log (q : ℝ) := Real.log_pos hq_gt
  have hq_log_ne : Real.log (q : ℝ) ≠ 0 := hq_log_pos.ne'
  have hratio_pos : 0 < Real.log (p : ℝ) / Real.log (q : ℝ) := by
    exact div_pos hp_log_pos hq_log_pos
  have hr_pos_real : (0 : ℝ) < r := by
    simpa [hr] using hratio_pos
  have hr_pos : 0 < r := by
    exact (Rat.cast_pos (K := ℝ) (q := r)).mp hr_pos_real
  have hnum_pos : 0 < r.num := Rat.num_pos.mpr hr_pos
  have hk_ne : k ≠ 0 := by
    intro hk0
    have hk0' : Int.toNat r.num = 0 := by simpa [k] using hk0
    have hk0_le : r.num ≤ 0 := Int.toNat_eq_zero.mp hk0'
    exact (not_le_of_gt hnum_pos) hk0_le
  have hk_cast_int : (k : ℤ) = r.num := by
    simpa [k] using Int.toNat_of_nonneg hnum_pos.le
  have hk_cast : (k : ℝ) = (r.num : ℝ) := by
    exact_mod_cast hk_cast_int
  have hden_ne : (r.den : ℝ) ≠ 0 := by positivity
  have hratio : Real.log (p : ℝ) / Real.log (q : ℝ) = (r.num : ℝ) / (r.den : ℝ) := by
    simpa [Rat.cast_def] using hr.symm
  have hcross : (r.den : ℝ) * Real.log (p : ℝ) = (r.num : ℝ) * Real.log (q : ℝ) := by
    field_simp [hq_log_ne, hden_ne] at hratio
    linarith
  have hpow_log : (r.den : ℝ) * Real.log (p : ℝ) = (k : ℝ) * Real.log (q : ℝ) := by
    rw [hk_cast]
    exact hcross
  have hpow_real : (p : ℝ) ^ r.den = (q : ℝ) ^ k := by
    calc
      (p : ℝ) ^ r.den = Real.exp ((r.den : ℝ) * Real.log (p : ℝ)) := by
        rw [Real.exp_nat_mul, Real.exp_log hp_pos]
      _ = Real.exp ((k : ℝ) * Real.log (q : ℝ)) := by rw [hpow_log]
      _ = (q : ℝ) ^ k := by
        rw [Real.exp_nat_mul, Real.exp_log hq_pos]
  have hpow_nat : p ^ r.den = q ^ k := by
    exact_mod_cast hpow_real
  have hp_eq_q : p = q :=
    (Nat.Prime.pow_inj' hp hq (Nat.ne_zero_of_lt r.den_pos) hk_ne hpow_nat).1
  exact hpq hp_eq_q

/-- Time parameter for the two-prime phase subgroup. -/
structure GroupJGPrimeRegisterPhaseData where
  t : ℝ
  ht : t ≠ 0

/-- The logarithmic two-prime phase subgroup used to witness Bohr density. -/
def GroupJGPrimeRegisterPhaseData.phaseImageDense (D : GroupJGPrimeRegisterPhaseData) : Prop :=
  Dense (AddSubgroup.closure {D.t * Real.log (2 : ℝ), D.t * Real.log (3 : ℝ)} : Set ℝ)

/-- The two-prime logarithmic subgroup generated by `t log 2` and `t log 3` is dense in `ℝ`
because the ratio `log 2 / log 3` is irrational; this is the concrete Bohr-density certificate
used for the prime-register phase wrapper.
    thm:group-jg-prime-register-phase-bohr-dense -/
theorem paper_group_jg_prime_register_phase_bohr_dense (D : GroupJGPrimeRegisterPhaseData) :
    D.phaseImageDense := by
  rw [GroupJGPrimeRegisterPhaseData.phaseImageDense, dense_addSubgroupClosure_pair_iff]
  have hlog3_pos : 0 < Real.log (3 : ℝ) := by
    have hthree : (1 : ℝ) < 3 := by norm_num
    exact Real.log_pos hthree
  have hlog3_ne : Real.log (3 : ℝ) ≠ 0 := hlog3_pos.ne'
  have hratio :
      (D.t * Real.log (2 : ℝ)) / (D.t * Real.log (3 : ℝ)) = Real.log (2 : ℝ) / Real.log (3 : ℝ) := by
    field_simp [D.ht, hlog3_ne]
  rw [hratio]
  exact prime_log_ratio_irrational (by native_decide) (by native_decide) (by decide)

end Omega.GU
