import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Tactic

namespace Omega.GU

/-- The explicit `SL₂(ℤ)` matrix attached to the tail triple `(21, 34, 55)`. -/
def tailTripleMatrix : Matrix (Fin 2) (Fin 2) ℤ
  | 0, 0 => 34
  | 0, 1 => 21
  | 1, 0 => 55
  | 1, 1 => 34

/-- The characteristic polynomial evaluated at a real scalar. -/
def tailTripleCharPoly (x : ℝ) : ℝ :=
  x ^ 2 - 68 * x + 1

/-- The larger real root, hence the spectral radius of the tail matrix. -/
noncomputable def tailTripleSpectralRadius : ℝ :=
  34 + Real.sqrt 1155

/-- The entropy readout attached to the hyperbolic tail matrix. -/
noncomputable def tailTripleEntropy : ℝ :=
  Real.log tailTripleSpectralRadius

private lemma tailTriple_det : tailTripleMatrix.det = 1 := by
  norm_num [tailTripleMatrix, Matrix.det_fin_two]

private lemma tailTriple_charpoly_plus :
    tailTripleCharPoly (34 + Real.sqrt 1155) = 0 := by
  have hsq : (Real.sqrt 1155) ^ 2 = 1155 := by rw [Real.sq_sqrt] <;> positivity
  unfold tailTripleCharPoly
  nlinarith

private lemma tailTriple_charpoly_minus :
    tailTripleCharPoly (34 - Real.sqrt 1155) = 0 := by
  have hsq : (Real.sqrt 1155) ^ 2 = 1155 := by rw [Real.sq_sqrt] <;> positivity
  unfold tailTripleCharPoly
  nlinarith

/-- Paper-facing wrapper for the hyperbolic `SL₂(ℤ)` element generated by the tail triple
    `(21, 34, 55)`. -/
theorem paper_terminal_window6_sl2z_hyperbolic_from_tail_triple :
    tailTripleMatrix.det = 1 ∧
    tailTripleCharPoly (34 + Real.sqrt 1155) = 0 ∧
    tailTripleCharPoly (34 - Real.sqrt 1155) = 0 ∧
    (34 - Real.sqrt 1155) * (34 + Real.sqrt 1155) = 1 ∧
    1 < tailTripleSpectralRadius ∧
    tailTripleEntropy = Real.log (34 + Real.sqrt 1155) := by
  refine ⟨tailTriple_det, tailTriple_charpoly_plus, tailTriple_charpoly_minus, ?_, ?_, rfl⟩
  · have hsq : (Real.sqrt 1155) ^ 2 = 1155 := by rw [Real.sq_sqrt] <;> positivity
    nlinarith
  · unfold tailTripleSpectralRadius
    nlinarith [Real.sqrt_nonneg 1155]
