import Mathlib.Analysis.Convex.Topology
import Mathlib.Tactic

namespace Omega.GU

/-- The normalized one-step count vector of a six-channel binary microstate. -/
def terminal6DNormalizedCountVector (x : Fin 6 → Fin 2) : Fin 6 → ℝ :=
  fun i => (x i : ℝ)

/-- Reachable six-channel mean states generated by normalized binary count vectors. -/
noncomputable def terminal6DReachableMeanSet : Set (Fin 6 → ℝ) :=
  convexHull ℝ (Set.range terminal6DNormalizedCountVector)

/-- Paper label: `prop:terminal-6d-reachable-mean-convex-body`. -/
theorem paper_terminal_6d_reachable_mean_convex_body :
    IsCompact terminal6DReachableMeanSet ∧ Convex ℝ terminal6DReachableMeanSet := by
  refine ⟨?_, ?_⟩
  · simpa [terminal6DReachableMeanSet] using
      (Set.finite_range terminal6DNormalizedCountVector).isCompact_convexHull
  · simpa [terminal6DReachableMeanSet] using
      (convex_convexHull ℝ (Set.range terminal6DNormalizedCountVector))

end Omega.GU
