import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Tactic

namespace Omega.GU

open Matrix

/-- The linear span of the six edge operators, viewed as the Lie-envelope proxy used in this file. -/
def window6LieEnvelope (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) :
    Submodule Real (Matrix (Fin 21) (Fin 21) Real) :=
  Submodule.span Real (Set.range L)

/-- The linear span of the six edge operators together with the identity matrix. -/
def window6EdgeFluxClosure (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) :
    Submodule Real (Matrix (Fin 21) (Fin 21) Real) :=
  Submodule.span Real ({1} ∪ Set.range L)

/-- Chapter-local formulation of the statement that the edge Lie envelope already contains every
traceless `21 × 21` real matrix. -/
def Window6LieEnvelopeIsSl21 (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) : Prop :=
  ∀ A : Matrix (Fin 21) (Fin 21) Real, Matrix.trace A = 0 → A ∈ window6LieEnvelope L

/-- Chapter-local formulation of full matrix saturation: adjoining the identity to the six edge
operators spans all endomorphisms of the `21`-dimensional carrier. -/
def Window6EdgeFluxFullMatrixSaturation (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) : Prop :=
  ∀ A : Matrix (Fin 21) (Fin 21) Real, A ∈ window6EdgeFluxClosure L

private lemma window6LieEnvelope_le_edgeFluxClosure
    (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) :
    window6LieEnvelope L ≤ window6EdgeFluxClosure L := by
  refine Submodule.span_le.2 ?_
  rintro _ ⟨i, rfl⟩
  exact Submodule.subset_span (by right; exact ⟨i, rfl⟩)

/-- If the Lie envelope generated by the six edge operators is already `sl(21)`, then adjoining
the identity matrix gives all of `gl(21) = End(V)`. This is the finite-dimensional matrix version
of the paper argument.
    thm:window6-edge-flux-full-matrix-saturation -/
theorem paper_window6_edge_flux_full_matrix_saturation
    (L : Fin 6 → Matrix (Fin 21) (Fin 21) Real) (hLie : Window6LieEnvelopeIsSl21 L) :
    Window6EdgeFluxFullMatrixSaturation L := by
  intro A
  let c : Real := Matrix.trace A / 21
  have htraceless : Matrix.trace (A - c • (1 : Matrix (Fin 21) (Fin 21) Real)) = 0 := by
    rw [Matrix.trace_sub, Matrix.trace_smul, Matrix.trace_one]
    norm_num [c]
  have hsl : A - c • (1 : Matrix (Fin 21) (Fin 21) Real) ∈ window6LieEnvelope L := by
    exact hLie _ htraceless
  have hsl' : A - c • (1 : Matrix (Fin 21) (Fin 21) Real) ∈ window6EdgeFluxClosure L :=
    window6LieEnvelope_le_edgeFluxClosure L hsl
  have hI : (1 : Matrix (Fin 21) (Fin 21) Real) ∈ window6EdgeFluxClosure L := by
    exact Submodule.subset_span (by left; rfl)
  have hcI : c • (1 : Matrix (Fin 21) (Fin 21) Real) ∈ window6EdgeFluxClosure L := by
    exact Submodule.smul_mem (window6EdgeFluxClosure L) c hI
  have hadd : (A - c • (1 : Matrix (Fin 21) (Fin 21) Real)) + c • (1 : Matrix (Fin 21) (Fin 21) Real) ∈
      window6EdgeFluxClosure L := by
    exact Submodule.add_mem (window6EdgeFluxClosure L) hsl' hcI
  simpa [c, sub_eq_add_neg, add_assoc] using hadd

end Omega.GU
