import Mathlib.Tactic
import Omega.GU.Window6B3SupportCount

namespace Omega.GU

open Finset

/-- The same `19`-point `B₃` support, now cut out from `{-1,0,1}^3` by the equation
`x₁ x₂ x₃ = 0`. -/
def window6B3SupportProductZero : Finset (ℤ × ℤ × ℤ) :=
  Omega.GU.Window6B3SupportCount.cube27.filter (fun p => p.1 * p.2.1 * p.2.2 = 0)

/-- The monomial generators of the lex initial ideal: `x₁^3`, `x₂^3`, `x₃^3`, `x₁x₂x₃`. -/
def window6B3InitialIdealGeneratorExponents : Finset (ℕ × ℕ × ℕ) :=
  {(3, 0, 0), (0, 3, 0), (0, 0, 3), (1, 1, 1)}

/-- Membership in the monomial ideal generated by `x₁^3`, `x₂^3`, `x₃^3`, `x₁x₂x₃`. -/
def window6B3InLexInitialIdeal (e : ℕ × ℕ × ℕ) : Prop :=
  3 ≤ e.1 ∨ 3 ≤ e.2.1 ∨ 3 ≤ e.2.2 ∨ (0 < e.1 ∧ 0 < e.2.1 ∧ 0 < e.2.2)

/-- The standard monomials are those with exponents in `{0,1,2}^3` and at least one zero
coordinate. -/
def window6B3StandardMonomials : Finset (ℕ × ℕ × ℕ) :=
  (range 3 ×ˢ range 3 ×ˢ range 3).filter (fun e => e.1 = 0 ∨ e.2.1 = 0 ∨ e.2.2 = 0)

/-- The total degree of a monomial exponent triple. -/
def window6B3TotalDegree (e : ℕ × ℕ × ℕ) : ℕ :=
  e.1 + e.2.1 + e.2.2

/-- Hilbert-function coefficient obtained by counting standard monomials of degree `d`. -/
def window6B3HilbertCoefficient (d : ℕ) : ℕ :=
  (window6B3StandardMonomials.filter (fun e => window6B3TotalDegree e = d)).card

/-- Concrete quotient/Hilbert-series package for the window-6 `B₃` support. -/
def window6B3SupportVanishingIdealHilbertStatement : Prop :=
  window6B3SupportProductZero = Omega.GU.Window6B3SupportCount.supportZero ∧
    window6B3InitialIdealGeneratorExponents.card = 4 ∧
    window6B3StandardMonomials.card = 19 ∧
    (∀ e : ℕ × ℕ × ℕ,
      e ∈ window6B3StandardMonomials ↔
        e ∈ range 3 ×ˢ range 3 ×ˢ range 3 ∧ ¬ window6B3InLexInitialIdeal e) ∧
    window6B3HilbertCoefficient 0 = 1 ∧
    window6B3HilbertCoefficient 1 = 3 ∧
    window6B3HilbertCoefficient 2 = 6 ∧
    window6B3HilbertCoefficient 3 = 6 ∧
    window6B3HilbertCoefficient 4 = 3 ∧
    window6B3HilbertCoefficient 5 = 0 ∧
    window6B3StandardMonomials.card = Omega.GU.Window6B3SupportCount.supportZero.card

private lemma window6B3_support_product_zero_eq :
    window6B3SupportProductZero = Omega.GU.Window6B3SupportCount.supportZero := by
  decide

private lemma window6B3_standard_monomials_spec (e : ℕ × ℕ × ℕ) :
    e ∈ window6B3StandardMonomials ↔
      e ∈ range 3 ×ˢ range 3 ×ˢ range 3 ∧ ¬ window6B3InLexInitialIdeal e := by
  constructor
  · intro he
    rcases mem_filter.mp he with ⟨hbox, hzero⟩
    refine ⟨hbox, ?_⟩
    intro hinit
    rcases hinit with h1 | h2 | h3 | hpos
    · rcases mem_product.mp hbox with ⟨ha, hbc⟩
      have ha3 : e.1 < 3 := mem_range.mp ha
      omega
    · rcases mem_product.mp hbox with ⟨ha, hbc⟩
      rcases mem_product.mp hbc with ⟨hb, hc⟩
      have hb3 : e.2.1 < 3 := mem_range.mp hb
      omega
    · rcases mem_product.mp hbox with ⟨ha, hbc⟩
      rcases mem_product.mp hbc with ⟨hb, hc⟩
      have hc3 : e.2.2 < 3 := mem_range.mp hc
      omega
    · rcases hzero with h1 | h2 | h3 <;> omega
  · rintro ⟨hbox, hinit⟩
    rcases mem_product.mp hbox with ⟨ha, hbc⟩
    rcases mem_product.mp hbc with ⟨hb, hc⟩
    refine mem_filter.mpr ⟨hbox, ?_⟩
    by_cases h1 : e.1 = 0
    · exact Or.inl h1
    · by_cases h2 : e.2.1 = 0
      · exact Or.inr <| Or.inl h2
      · by_cases h3 : e.2.2 = 0
        · exact Or.inr <| Or.inr h3
        · exfalso
          apply hinit
          right
          right
          right
          constructor
          · exact Nat.pos_of_ne_zero h1
          constructor
          · exact Nat.pos_of_ne_zero h2
          · exact Nat.pos_of_ne_zero h3

theorem window6B3SupportVanishingIdealHilbertStatement_true :
    window6B3SupportVanishingIdealHilbertStatement := by
  refine ⟨window6B3_support_product_zero_eq, by decide, by decide, ?_, by decide, by decide,
    by decide, by decide, by decide, by decide, ?_⟩
  · intro e
    exact window6B3_standard_monomials_spec e
  · rw [Omega.GU.Window6B3SupportCount.supportZero_card]
    decide

/-- Paper label: `thm:window6-b3-support-vanishing-ideal-hilbert`. -/
def paper_window6_b3_support_vanishing_ideal_hilbert : Prop :=
  window6B3SupportVanishingIdealHilbertStatement

theorem paper_window6_b3_support_vanishing_ideal_hilbert_verified :
    paper_window6_b3_support_vanishing_ideal_hilbert :=
  window6B3SupportVanishingIdealHilbertStatement_true

end Omega.GU
