import Mathlib.Data.Real.Basic
import Mathlib.Order.ConditionallyCompleteLattice.Basic
import Mathlib.Tactic

namespace Omega.SyncKernelRealInput

noncomputable section

/-- Concrete transfer-operator interface for the multifractal pressure package.  The Perron branch
defines the pressure, `largeValueLogFrequency` records the frequency exponent, and the two
Gartner-Ellis outputs are stored as concrete laws about these recorded objects. -/
structure gm_multifractal_pressure_legendre_data where
  stateCount : ℕ
  primitiveLength : ℕ
  perronRoot : ℝ → ℝ
  pressure : ℝ → ℝ
  sigma : ℝ
  largeValueLogFrequency : ℕ → ℝ
  spectralGapConstant : ℝ
  stateCount_pos : 0 < stateCount
  primitiveLength_pos : 0 < primitiveLength
  pressure_eq_log_perron : pressure = fun β => Real.log (perronRoot β)
  large_value_frequency :
    ∀ m,
      largeValueLogFrequency m =
        -(m : ℝ) *
          sSup (Set.range fun β : ℝ => β * sigma - pressure β)
  strict_convex_iff_spectral_gap :
    (∀ β₁ β₂ : ℝ,
        β₁ ≠ β₂ →
          pressure ((β₁ + β₂) / 2) < (pressure β₁ + pressure β₂) / 2) ↔
      0 < spectralGapConstant

/-- Legendre-Fenchel rate function generated by the pressure. -/
def gm_multifractal_pressure_legendre_rate
    (D : gm_multifractal_pressure_legendre_data) (σ : ℝ) : ℝ :=
  sSup (Set.range fun β : ℝ => β * σ - D.pressure β)

/-- Midpoint strict convexity of the pressure. -/
def gm_multifractal_pressure_legendre_strict_convex_pressure
    (D : gm_multifractal_pressure_legendre_data) : Prop :=
  ∀ β₁ β₂ : ℝ,
    β₁ ≠ β₂ →
      D.pressure ((β₁ + β₂) / 2) < (D.pressure β₁ + D.pressure β₂) / 2

/-- The concrete spectral-gap predicate carried by the transfer-operator package. -/
def gm_multifractal_pressure_legendre_spectral_gap
    (D : gm_multifractal_pressure_legendre_data) : Prop :=
  0 < D.spectralGapConstant

/-- Packaged multifractal pressure law: the rate function is the Legendre transform, the
large-value log-frequency has exponent `-m I(σ)`, and strict convexity matches spectral gap. -/
def gm_multifractal_pressure_legendre_law
    (D : gm_multifractal_pressure_legendre_data) : Prop :=
  (∀ σ, gm_multifractal_pressure_legendre_rate D σ =
      sSup (Set.range fun β : ℝ => β * σ - D.pressure β)) ∧
    (∀ m,
      D.largeValueLogFrequency m =
        -(m : ℝ) * gm_multifractal_pressure_legendre_rate D D.sigma) ∧
    (gm_multifractal_pressure_legendre_strict_convex_pressure D ↔
      gm_multifractal_pressure_legendre_spectral_gap D)

/-- Paper label: `thm:gm-multifractal-pressure-legendre`. -/
theorem paper_gm_multifractal_pressure_legendre
    (D : gm_multifractal_pressure_legendre_data) :
    gm_multifractal_pressure_legendre_law D := by
  refine ⟨?_, ?_, ?_⟩
  · intro σ
    rfl
  · intro m
    simpa [gm_multifractal_pressure_legendre_rate] using D.large_value_frequency m
  · simpa [gm_multifractal_pressure_legendre_strict_convex_pressure,
      gm_multifractal_pressure_legendre_spectral_gap] using D.strict_convex_iff_spectral_gap

end

end Omega.SyncKernelRealInput
