import Mathlib.Data.Finset.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Tactic
import Omega.CircleDimension.ArithmeticSingularRingOneParameterSubgroups

open scoped BigOperators

namespace Omega.CircleDimension

/-- Concrete presentation coordinates `(q, (n_p))` for the arithmetic singular ring model. -/
abbrev ArithmeticSingularRingPrimePresentation (S : Finset Nat) := ℝ × (S → ℝ)

/-- Shift by the relation generated by `(1, -1_S)`. -/
def arithmeticSingularRingPrimeShift {S : Finset Nat}
    (x : ArithmeticSingularRingPrimePresentation S) (t : ℝ) :
    ArithmeticSingularRingPrimePresentation S :=
  (x.1 + t, fun p => x.2 p - t)

/-- Quotient relation generated by the simultaneous shift `(q, n_p) ↦ (q + t, n_p - t)`. -/
def arithmeticSingularRingPrimeRel (S : Finset Nat)
    (x y : ArithmeticSingularRingPrimePresentation S) : Prop :=
  ∃ t : ℝ, y = arithmeticSingularRingPrimeShift x t

lemma arithmeticSingularRingPrimeRel_refl {S : Finset Nat}
    (x : ArithmeticSingularRingPrimePresentation S) :
    arithmeticSingularRingPrimeRel S x x := by
  refine ⟨0, ?_⟩
  ext <;> simp [arithmeticSingularRingPrimeShift]

lemma arithmeticSingularRingPrimeRel_symm {S : Finset Nat}
    {x y : ArithmeticSingularRingPrimePresentation S} :
    arithmeticSingularRingPrimeRel S x y → arithmeticSingularRingPrimeRel S y x := by
  rintro ⟨t, rfl⟩
  refine ⟨-t, ?_⟩
  ext
  · simp [arithmeticSingularRingPrimeShift]
  · simp [arithmeticSingularRingPrimeShift, sub_eq_add_neg]

lemma arithmeticSingularRingPrimeRel_trans {S : Finset Nat}
    {x y z : ArithmeticSingularRingPrimePresentation S} :
    arithmeticSingularRingPrimeRel S x y →
      arithmeticSingularRingPrimeRel S y z →
        arithmeticSingularRingPrimeRel S x z := by
  rintro ⟨t, rfl⟩ ⟨u, rfl⟩
  refine ⟨t + u, ?_⟩
  ext
  · simp [arithmeticSingularRingPrimeShift, add_assoc]
  · simp [arithmeticSingularRingPrimeShift, sub_eq_add_neg]
    ring_nf

/-- The quotient identifying representatives that differ by the `(1, -1_S)` relation. -/
def arithmeticSingularRingPrimeSetoid (S : Finset Nat) :
    Setoid (ArithmeticSingularRingPrimePresentation S) where
  r := arithmeticSingularRingPrimeRel S
  iseqv := ⟨arithmeticSingularRingPrimeRel_refl,
    arithmeticSingularRingPrimeRel_symm, arithmeticSingularRingPrimeRel_trans⟩

/-- Quotient presentation of the arithmetic singular ring. -/
abbrev ArithmeticSingularRingPrimeQuotient (S : Finset Nat) :=
  Quotient (arithmeticSingularRingPrimeSetoid S)

/-- Total prime frequency attached to `omega`. -/
def totalPrimeFrequency {S : Finset Nat} (omega : S → ℝ) : ℝ :=
  ∑ p : S, omega p

/-- Linear evaluation on presentation coordinates. -/
def primePresentationEval {S : Finset Nat} (omega : S → ℝ)
    (x : ArithmeticSingularRingPrimePresentation S) : ℝ :=
  x.1 * totalPrimeFrequency omega + ∑ p : S, x.2 p * omega p

lemma primePresentationEval_shift {S : Finset Nat} (omega : S → ℝ)
    (x : ArithmeticSingularRingPrimePresentation S) (t : ℝ) :
    primePresentationEval omega (arithmeticSingularRingPrimeShift x t) =
      primePresentationEval omega x := by
  unfold primePresentationEval arithmeticSingularRingPrimeShift totalPrimeFrequency
  have hsum :
      (∑ p : S, (x.2 p - t) * omega p) =
        (∑ p : S, x.2 p * omega p) - ∑ p : S, t * omega p := by
    calc
      (∑ p : S, (x.2 p - t) * omega p) =
          ∑ p : S, (x.2 p * omega p - t * omega p) := by
            refine Finset.sum_congr rfl ?_
            intro p hp
            ring
      _ = (∑ p : S, x.2 p * omega p) - ∑ p : S, t * omega p := by
            rw [Finset.sum_sub_distrib]
  rw [hsum, ← Finset.mul_sum]
  ring

lemma primePresentationEval_respects_rel {S : Finset Nat} (omega : S → ℝ)
    {x y : ArithmeticSingularRingPrimePresentation S}
    (h : arithmeticSingularRingPrimeRel S x y) :
    primePresentationEval omega x = primePresentationEval omega y := by
  rcases h with ⟨t, rfl⟩
  exact (primePresentationEval_shift omega x t).symm

/-- Evaluation expressed through a compatible one-parameter subgroup. -/
def subgroupPrimePresentationEval {S : Finset Nat}
    (G : arithmeticSingularRingOneParameterSubgroups S)
    (x : ArithmeticSingularRingPrimePresentation S) : ℝ :=
  primePresentationEval G.torusFrequency x

lemma subgroupPrimePresentationEval_respects_rel {S : Finset Nat}
    (G : arithmeticSingularRingOneParameterSubgroups S)
    {x y : ArithmeticSingularRingPrimePresentation S}
    (h : arithmeticSingularRingPrimeRel S x y) :
    subgroupPrimePresentationEval G x = subgroupPrimePresentationEval G y :=
  primePresentationEval_respects_rel G.torusFrequency h

/-- The descended character on the quotient presentation. -/
def arithmeticSingularRingPrimeCharacter {S : Finset Nat}
    (G : arithmeticSingularRingOneParameterSubgroups S) :
    ArithmeticSingularRingPrimeQuotient S → ℝ :=
  Quotient.lift (subgroupPrimePresentationEval G) <| by
    intro x y hxy
    exact subgroupPrimePresentationEval_respects_rel G hxy

/-- Character-evaluation formula on the quotient presentation of the arithmetic singular ring. -/
def ArithmeticSingularRingPrimeFrequencyCharacterEval (S : Finset Nat) (omega : S → ℝ) : Prop :=
  ∃ χ : ArithmeticSingularRingPrimeQuotient S → ℝ,
    ∀ x : ArithmeticSingularRingPrimePresentation S,
      χ (Quotient.mk (arithmeticSingularRingPrimeSetoid S) x) = primePresentationEval omega x

/-- The prime-frequency functional kills the presentation relation generated by `(1, -1_S)`,
therefore it descends to the quotient and evaluates characters by the displayed formula.
    prop:cdim-arithmetic-singular-ring-prime-frequency-character-eval -/
theorem paper_cdim_arithmetic_singular_ring_prime_frequency_character_eval
    {S : Finset Nat} (omega : S → Real) :
    ArithmeticSingularRingPrimeFrequencyCharacterEval S omega := by
  let e := paper_cdim_arithmetic_singular_ring_one_parameter_subgroups S
  let G : arithmeticSingularRingOneParameterSubgroups S := e.symm omega
  have hG : G.torusFrequency = omega := by
    dsimp [G, e, paper_cdim_arithmetic_singular_ring_one_parameter_subgroups,
      subgroupOfTorusFrequencyVector]
  refine ⟨arithmeticSingularRingPrimeCharacter G, ?_⟩
  intro x
  change subgroupPrimePresentationEval G x = primePresentationEval omega x
  simp [subgroupPrimePresentationEval, hG]

end Omega.CircleDimension
