import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.FreeAndStrongRankCondition
import Mathlib.Tactic

namespace Omega.CircleDimension

open scoped BigOperators

noncomputable section

/-- An explicit finite-rank feature map for the basepoint scan. -/
def basepointFeatureMap {κ : ℕ} (v : ℝ → Fin κ → ℂ) (x : ℝ) : Fin κ → ℂ :=
  v x

/-- The Gram kernel generated by the feature map. -/
def basepointKernel {κ : ℕ} (v : ℝ → Fin κ → ℂ) (x y : ℝ) : ℂ :=
  ∑ k : Fin κ, star (v x k) * v y k

/-- The diagonal scan profile attached to the kernel. -/
def basepointProfile {κ : ℕ} (v : ℝ → Fin κ → ℂ) (x : ℝ) : ℂ :=
  basepointKernel v x x

/-- The subspace generated by all feature vectors. -/
def basepointGeneratedSpace {κ : ℕ} (v : ℝ → Fin κ → ℂ) : Submodule ℂ (Fin κ → ℂ) :=
  Submodule.span ℂ (Set.range (basepointFeatureMap v))

private lemma basepoint_feature_mem_span {κ : ℕ} (v : ℝ → Fin κ → ℂ) (x : ℝ) :
    basepointFeatureMap v x ∈ basepointGeneratedSpace v := by
  exact Submodule.subset_span ⟨x, rfl⟩

/-- The finite-rank basepoint scan kernel is the Gram kernel of its explicit feature map, its
diagonal reads off the scan profile, and any linearly independent family of `κ` kernel sections
forces the generated RKHS to have dimension `κ`.
    thm:cdim-basepoint-scan-finite-rank-rkhs -/
theorem paper_cdim_basepoint_scan_finite_rank_rkhs
    {κ : ℕ} (v : ℝ → Fin κ → ℂ) (anchors : Fin κ → ℝ)
    (hlin : LinearIndependent ℂ (fun j => basepointFeatureMap v (anchors j))) :
    (∀ x y : ℝ,
      basepointKernel v x y = ∑ k : Fin κ, star (basepointFeatureMap v x k) * basepointFeatureMap v y k) ∧
      (∀ x : ℝ, basepointKernel v x x = basepointProfile v x) ∧
      Module.finrank ℂ (basepointGeneratedSpace v) = κ := by
  have hanchor_le :
      Submodule.span ℂ (Set.range fun j : Fin κ => basepointFeatureMap v (anchors j)) ≤
        basepointGeneratedSpace v := by
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨j, rfl⟩
    exact basepoint_feature_mem_span v (anchors j)
  have hlower : κ ≤ Module.finrank ℂ (basepointGeneratedSpace v) := by
    calc
      κ = Module.finrank ℂ
            (Submodule.span ℂ (Set.range fun j : Fin κ => basepointFeatureMap v (anchors j))) := by
            simpa [Fintype.card_fin] using
              (finrank_span_eq_card (R := ℂ)
                (b := fun j : Fin κ => basepointFeatureMap v (anchors j)) hlin).symm
      _ ≤ Module.finrank ℂ (basepointGeneratedSpace v) := Submodule.finrank_mono hanchor_le
  have hupper : Module.finrank ℂ (basepointGeneratedSpace v) ≤ κ := by
    calc
      Module.finrank ℂ (basepointGeneratedSpace v) ≤ Module.finrank ℂ (Fin κ → ℂ) :=
        Submodule.finrank_le _
      _ = κ := by simpa using Module.finrank_fintype_fun_eq_card (R := ℂ) (η := Fin κ)
  exact ⟨by intro x y; rfl, by intro x; rfl, le_antisymm hupper hlower⟩

end

end Omega.CircleDimension
