import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Tactic

namespace Omega.CircleDimension

open scoped BigOperators

/-- Same-time address assignments in the finite visible register. -/
abbrev VisibleAddressState (A : Type*) := A → Bool

/-- Finite-dimensional visible wavefunctions on the same-time address space. -/
abbrev VisibleWavefunction (A : Type*) := VisibleAddressState A → ℂ

/-- Concrete observable operators on visible wavefunctions. -/
abbrev VisibleOperator (A : Type*) := VisibleWavefunction A → VisibleWavefunction A

/-- Diagonal multiplication by the scalar profile `f`. -/
def diagonalOperator {A : Type*} (f : VisibleAddressState A → ℂ) : VisibleOperator A :=
  fun ψ x => f x * ψ x

/-- The local projection fixing the value at one address. -/
def localProjection {A : Type*} (a : A) (bit : Bool) : VisibleOperator A :=
  diagonalOperator fun x => if x a = bit then 1 else 0

/-- The same-time address projection is the product of the commuting local projections. -/
def sameTimeAddressProjection {A : Type*} [Fintype A] (addr : VisibleAddressState A) :
    VisibleOperator A :=
  diagonalOperator fun x => ∏ a, if x a = addr a then (1 : ℂ) else 0

/-- The visible algebra generated by same-time projections is modeled by diagonal operators. -/
def visibleVonNeumannAlgebra (A : Type*) : Set (VisibleOperator A) :=
  Set.range (@diagonalOperator A)

/-- Commutation for visible operators. -/
def OperatorsCommute {A : Type*} (T S : VisibleOperator A) : Prop :=
  T ∘ S = S ∘ T

/-- The diagonal visible algebra is commutative. -/
def visibleVonNeumannAlgebraCommutative (A : Type*) : Prop :=
  ∀ ⦃T S : VisibleOperator A⦄,
    T ∈ visibleVonNeumannAlgebra A →
      S ∈ visibleVonNeumannAlgebra A →
        OperatorsCommute T S

lemma diagonalOperator_commute {A : Type*} (f g : VisibleAddressState A → ℂ) :
    OperatorsCommute (diagonalOperator f) (diagonalOperator g) := by
  funext ψ
  funext x
  simp [OperatorsCommute, diagonalOperator, mul_comm, mul_left_comm, mul_assoc]

lemma sameTimeAddressProjection_mem_visibleVonNeumannAlgebra
    {A : Type*} [Fintype A] (addr : VisibleAddressState A) :
    sameTimeAddressProjection addr ∈ visibleVonNeumannAlgebra A := by
  refine ⟨fun x => ∏ a, if x a = addr a then (1 : ℂ) else 0, rfl⟩

lemma sameTimeAddressProjection_commute {A : Type*} [Fintype A]
    (addr₁ addr₂ : VisibleAddressState A) :
    OperatorsCommute (sameTimeAddressProjection addr₁) (sameTimeAddressProjection addr₂) := by
  exact diagonalOperator_commute _ _

lemma visibleVonNeumannAlgebra_commutative (A : Type*) :
    visibleVonNeumannAlgebraCommutative A := by
  intro T S hT hS
  rcases hT with ⟨f, rfl⟩
  rcases hS with ⟨g, rfl⟩
  exact diagonalOperator_commute f g

/-- Paper package: same-time address projections lie in the diagonal visible algebra, commute
pairwise, and therefore generate a commutative visible von Neumann algebra.
    prop:cdim-commutative-visible-algebra -/
theorem paper_cdim_commutative_visible_algebra (A : Type*) [Fintype A] :
    (∀ addr : VisibleAddressState A,
      sameTimeAddressProjection addr ∈ visibleVonNeumannAlgebra A) ∧
      (∀ addr₁ addr₂ : VisibleAddressState A,
        OperatorsCommute (sameTimeAddressProjection addr₁) (sameTimeAddressProjection addr₂)) ∧
      visibleVonNeumannAlgebraCommutative A := by
  refine ⟨sameTimeAddressProjection_mem_visibleVonNeumannAlgebra, ?_, ?_⟩
  · intro addr₁ addr₂
    exact sameTimeAddressProjection_commute addr₁ addr₂
  · exact visibleVonNeumannAlgebra_commutative A

end Omega.CircleDimension
