import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.Tactic
import Omega.CircleDimension.UnitarySelfAdjointLog

namespace Omega.CircleDimension

noncomputable section

open ReadableTimeWordPrincipalPhaseGeneratorData

/-- The finite-spectrum generator fixed by the principal-branch logarithm package. -/
def cdimContinuousUnitaryGenerator : ReadableTimeWordPrincipalPhaseGeneratorData := ⟨⟩

/-- The principal phases used to generate the continuous unitary family. -/
def cdimContinuousUnitaryPhase (k : Fin 4) : ℝ :=
  cdimContinuousUnitaryGenerator.principalPhase k

/-- The target unitary spectrum at time `1`. -/
def cdimContinuousUnitarySpectrum (k : Fin 4) : ℂ :=
  cdimContinuousUnitaryGenerator.shiftSpectrum k

/-- The real-parameter unitary family generated by the bounded self-adjoint phase operator. -/
def cdimContinuousUnitaryFamily (s : ℝ) (k : Fin 4) : ℂ :=
  Complex.exp (((-(s * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I)

/-- Paper label: `thm:cdim-continuous-unitary-group`. -/
theorem paper_cdim_continuous_unitary_group :
    (∀ k, |cdimContinuousUnitaryPhase k| ≤ Real.pi) ∧
      (∀ s t k,
        cdimContinuousUnitaryFamily (s + t) k =
          cdimContinuousUnitaryFamily s k * cdimContinuousUnitaryFamily t k) ∧
      (∀ k, Continuous fun s => cdimContinuousUnitaryFamily s k) ∧
      (∀ k, cdimContinuousUnitaryFamily 0 k = 1) ∧
      (∀ k, cdimContinuousUnitaryFamily 1 k = cdimContinuousUnitarySpectrum k) := by
  rcases paper_cdim_unitary_selfadjoint_log cdimContinuousUnitaryGenerator with ⟨hBound, hRecover⟩
  refine ⟨hBound, ?_, ?_, ?_, ?_⟩
  · intro s t k
    have hsum :
        (((-((s + t) * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I) =
          (((-(s * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I) +
            (((-(t * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I) := by
      calc
        (((-((s + t) * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I)
            = (((-(s * cdimContinuousUnitaryPhase k) + -(t * cdimContinuousUnitaryPhase k) : ℝ) :
                ℂ) * Complex.I) := by
                congr 1
                ring_nf
        _ = (((( -(s * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) +
              (((-(t * cdimContinuousUnitaryPhase k) : ℝ) : ℂ))) * Complex.I) := by
              rw [Complex.ofReal_add]
        _ = (((-(s * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I) +
              (((-(t * cdimContinuousUnitaryPhase k) : ℝ) : ℂ) * Complex.I) := by
              ring_nf
    rw [cdimContinuousUnitaryFamily, cdimContinuousUnitaryFamily, cdimContinuousUnitaryFamily, hsum]
    exact Complex.exp_add _ _
  · intro k
    continuity
  · intro k
    simp [cdimContinuousUnitaryFamily]
  · intro k
    simpa [cdimContinuousUnitaryFamily, cdimContinuousUnitarySpectrum,
      cdimContinuousUnitaryPhase, cdimContinuousUnitaryGenerator] using hRecover k

end

end Omega.CircleDimension
