import Mathlib.Analysis.Complex.Trigonometric
import Mathlib.Analysis.InnerProductSpace.LinearMap
import Mathlib.LinearAlgebra.Span.Basic

namespace Omega.CircleDimension

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- The rank-one projector attached to a vector `ψ`. -/
noncomputable abbrev pureStateProjector (ψ : H) : H →L[ℂ] H :=
  InnerProductSpace.rankOne ℂ ψ ψ

/-- The minimal density-operator wrapper used in this chapter. -/
structure DensityOperator (H : Type u) [NormedAddCommGroup H] [InnerProductSpace ℂ H] where
  operator : H →L[ℂ] H

/-- A pure state is modeled as an extreme point of the chapter's state space. The ambient state
space is recorded via normalized rank-one projectors, which is sufficient for the present chapter.
-/
def DensityOperator.IsPure (ρ : DensityOperator H) : Prop :=
  ∀ σ τ : DensityOperator H, ∀ a b : ℝ,
    0 < a →
    0 < b →
    a + b = 1 →
    (∃ ψ : H, ‖ψ‖ = 1 ∧ σ.operator = pureStateProjector ψ) →
    (∃ ψ : H, ‖ψ‖ = 1 ∧ τ.operator = pureStateProjector ψ) →
    ρ.operator = (a : ℂ) • σ.operator + (b : ℂ) • τ.operator →
    σ = ρ ∧ τ = ρ

/-- Rank-one projectors coming from unit vectors. -/
def DensityOperator.IsRankOneProjector (ρ : DensityOperator H) : Prop :=
  ∃ ψ : H, ‖ψ‖ = 1 ∧ ρ.operator = pureStateProjector ψ

/-- The range of a pure rank-one projector is the line generated by its vector. -/
def DensityOperator.HasOneDimensionalRange (ρ : DensityOperator H) : Prop :=
  ∃ ψ : H, ψ ≠ 0 ∧ LinearMap.range ρ.operator.toLinearMap = Submodule.span ℂ ({ψ} : Set H)

/-- The projector only depends on the ray of the unit vector. -/
def DensityOperator.PhaseInvariant (ρ : DensityOperator H) : Prop :=
  ∀ ψ : H, ‖ψ‖ = 1 → ∀ θ : ℝ,
    ρ.operator = pureStateProjector ψ →
      ρ.operator = pureStateProjector (Complex.exp (θ * Complex.I) • ψ)

@[simp] theorem pureStateProjector_apply (ψ x : H) :
    pureStateProjector ψ x = inner ℂ ψ x • ψ := by
  simp [pureStateProjector]

omit [InnerProductSpace ℂ H] in
private theorem pureStateProjector_nonzero {ψ : H} (hψ : ‖ψ‖ = 1) : ψ ≠ 0 := by
  intro hzero
  simp [hzero] at hψ

/-- A unit-vector rank-one projector is idempotent. -/
theorem pureStateProjector_isIdempotent {ψ : H} (hψ : ‖ψ‖ = 1) :
    IsIdempotentElem (pureStateProjector ψ) := by
  exact
    (InnerProductSpace.isIdempotentElem_rankOne_self_iff (𝕜 := ℂ) (x := ψ)
      (pureStateProjector_nonzero hψ)).2 hψ

private theorem pureStateProjector_mem_span (ψ x : H) :
    pureStateProjector ψ x ∈ Submodule.span ℂ ({ψ} : Set H) := by
  simpa [pureStateProjector_apply] using
    Submodule.smul_mem (Submodule.span ℂ ({ψ} : Set H)) (inner ℂ ψ x)
      (Submodule.mem_span_singleton_self ψ)

/-- The range of a unit-vector rank-one projector is exactly the line that it spans. -/
theorem pureStateProjector_range_eq_span {ψ : H} (hψ : ‖ψ‖ = 1) :
    LinearMap.range (pureStateProjector ψ).toLinearMap = Submodule.span ℂ ({ψ} : Set H) := by
  ext y
  constructor
  · rintro ⟨x, rfl⟩
    exact pureStateProjector_mem_span ψ x
  · intro hy
    rw [Submodule.mem_span_singleton] at hy
    rcases hy with ⟨a, rfl⟩
    refine ⟨a • ψ, ?_⟩
    have hsq : ((‖ψ‖ : ℂ) ^ 2) = 1 := by simp [hψ]
    simp [pureStateProjector, hsq]

/-- Multiplying a unit vector by a global phase does not change its rank-one projector. -/
theorem pureStateProjector_phase_invariant (ψ : H) (θ : ℝ) :
    pureStateProjector (Complex.exp (θ * Complex.I) • ψ) = pureStateProjector ψ := by
  set z : ℂ := Complex.exp (θ * Complex.I)
  have hz : star z * z = 1 := by
    simp [z, Complex.conj_mul', Complex.norm_exp_ofReal_mul_I]
  ext x
  rw [pureStateProjector_apply, pureStateProjector_apply]
  calc
    inner ℂ (z • ψ) x • (z • ψ) = ((star z * inner ℂ ψ x) * z) • ψ := by
      simp [inner_smul_left, smul_smul, mul_assoc]
    _ = ((star z * z) * inner ℂ ψ x) • ψ := by
      simp [mul_left_comm, mul_comm]
    _ = (1 * inner ℂ ψ x) • ψ := by rw [hz]
    _ = inner ℂ ψ x • ψ := by simp

/-- Paper label: `prop:cdim-pure-states-rank-one`. -/
def paper_cdim_pure_states_rank_one {H : Type*} [NormedAddCommGroup H]
    [InnerProductSpace ℂ H] : Prop :=
  (∀ ρ : DensityOperator H,
    ρ.IsPure ↔ ρ.IsRankOneProjector ∧ ρ.HasOneDimensionalRange ∧ ρ.PhaseInvariant) ∧
    (∀ ψ : H, ‖ψ‖ = 1 →
      IsIdempotentElem (pureStateProjector ψ) ∧
        LinearMap.range (pureStateProjector ψ).toLinearMap = Submodule.span ℂ ({ψ} : Set H) ∧
        ∀ θ : ℝ,
          pureStateProjector (Complex.exp (θ * Complex.I) • ψ) = pureStateProjector ψ)

end Omega.CircleDimension
