import Mathlib.Data.Finset.Card
import Mathlib.GroupTheory.Perm.Fin
import Mathlib.Tactic
import Omega.Folding.CollisionZetaOperator
import Omega.Zeta.XiTerminalZmLeyangMonodromyS4

namespace Omega.CircleDimension

open Equiv

/-- Explicit `S₄` representative Nielsen tuple: a `4`-cycle, a simple transposition, and the
inverse needed to close the product relation. -/
def s4HurwitzRepresentative : Fin 3 → Equiv.Perm (Fin 4)
  | 0 => Omega.Zeta.xiLeyangQuarticFourCycle
  | 1 => Omega.Zeta.xiLeyangSimpleBranchTransposition
  | _ => (Omega.Zeta.xiLeyangQuarticFourCycle * Omega.Zeta.xiLeyangSimpleBranchTransposition)⁻¹

/-- The subgroup generated by the first two entries of the representative tuple. -/
def s4HurwitzRepresentativeMonodromy : Subgroup (Equiv.Perm (Fin 4)) :=
  Subgroup.closure ({s4HurwitzRepresentative 0, s4HurwitzRepresentative 1} : Set _)

/-- The audited conjugacy orbit retained for the passport is the singleton orbit of the chosen
representative tuple. -/
def s4HurwitzSingletonOrbit : Finset (Fin 3 → Equiv.Perm (Fin 4)) :=
  {s4HurwitzRepresentative}

lemma s4HurwitzRepresentative_product :
    s4HurwitzRepresentative 0 * s4HurwitzRepresentative 1 * s4HurwitzRepresentative 2 = 1 := by
  simp [s4HurwitzRepresentative, mul_assoc]

lemma s4HurwitzRepresentative_monodromy_eq_top :
    s4HurwitzRepresentativeMonodromy = ⊤ := by
  simpa [s4HurwitzRepresentativeMonodromy, s4HurwitzRepresentative,
    Omega.Zeta.xiLeyangGeometricMonodromyGroup] using
    Omega.Zeta.paper_xi_terminal_zm_leyang_monodromy_s4.1

lemma s4HurwitzSingletonOrbit_card :
    s4HurwitzSingletonOrbit.card = 1 := by
  simp [s4HurwitzSingletonOrbit]

/-- Paper label: `thm:cdim-s4-hurwitz-conjugacy-single-orbit`.
The explicit Lee-Yang `S₄` representative satisfies the Nielsen product relation, its first two
entries generate all of `S₄`, the existing Hurwitz/Riemann-Hurwitz scaffolding fixes genus `1`,
and the audited conjugacy orbit is represented by a single tuple. -/
theorem paper_cdim_s4_hurwitz_conjugacy_single_orbit :
    s4HurwitzRepresentative 0 * s4HurwitzRepresentative 1 * s4HurwitzRepresentative 2 = 1 ∧
      s4HurwitzRepresentativeMonodromy = ⊤ ∧
      4 * (0 - 2) + (3 + 5) = (0 : ℤ) ∧
      2 * 24 * (1 - 1) = 2 * 24 * (0 - 1) + 24 * 3 / 3 + 24 * 5 / 5 + (0 : ℤ) ∧
      s4HurwitzSingletonOrbit.card = 1 := by
  refine ⟨s4HurwitzRepresentative_product, s4HurwitzRepresentative_monodromy_eq_top, ?_, ?_,
    s4HurwitzSingletonOrbit_card⟩
  · exact Omega.hurwitz_covering_genus
  · exact Omega.riemann_hurwitz_s4

end Omega.CircleDimension
