import json, pathlib
I={
"valid":True,
"in_scope_present":[
{"label":"Main theorem summaries","location":"sec_introduction_core.tex:342, sec_introduction_core.tex:375, sec_introduction_core.tex:412","reason":"Intro states Main Theorems I--III, including the Adams-corrected Frobenius-class Euler-product theorem, and forwards to body proofs.","required_action":"Keep as summaries; preserve stable labels and body theorem references."},
{"label":"Main Theorem I Adams--Mobius primitive inversion","location":"sec_chebotarev_main_inversion.tex:499, sec_chebotarev_main_inversion.tex:560, sec_chebotarev_fixed_label_and_boundary.tex:1, sec_chebotarev_fixed_label_and_boundary.tex:66, sec_chebotarev_peter_weyl_bridge.tex:79, sec_chebotarev_peter_weyl_bridge.tex:164, sec_chebotarev_peter_weyl_bridge.tex:191, sec_chebotarev_peter_weyl_bridge.tex:236","reason":"Twisted trace identity, determinant linearisation, Adams--Mobius inversion, Peter--Weyl determinant/trace formulas, finite trace interface, and class primitive decomposition are present on |z|<lambda^{-1} without eta<lambda.","required_action":"Retain as the determinant-to-primitive core; do not add Perron-boundary hypotheses."},
{"label":"Fixed-label Euler transform and logarithm separation","location":"sec_chebotarev_fixed_label_and_boundary.tex:177, sec_chebotarev_fixed_label_and_boundary.tex:275, sec_chebotarev_fixed_label_and_boundary.tex:338, sec_chebotarev_fixed_label_and_boundary.tex:458","reason":"F_phi(z)=sum_r Pi_phi(z^r)/r is defined, related by Adams--Mobius to periodic logarithms, explicitly distinguished from Artin L_phi, and controlled at the Perron boundary for non-trivial channels.","required_action":"Keep central to Main Theorem III; never conflate F_phi with the periodic Artin logarithm."},
{"label":"Main Theorem II class Mertens and Fourier readout","location":"sec_chebotarev_class_mertens_additive.tex:15, sec_chebotarev_class_mertens_additive.tex:270, sec_chebotarev_class_mertens_obstruction.tex:338, sec_chebotarev_readout.tex:13","reason":"The additive class Mertens theorem, logarithmic form, deviation/determinant bridge, and Hermitian Fourier inversion/Parseval readout are present under lambda>1 and eta<lambda.","required_action":"Keep eta<lambda conditional and maintain the Hermitian convention chi_rho^*(C) forward, chi_sigma(C) inverse."},
{"label":"Main Theorem III Adams-corrected product constants","location":"sec_chebotarev_class_mertens_products.tex:11, sec_chebotarev_class_mertens_products.tex:75, sec_chebotarev_class_mertens_products.tex:101, sec_chebotarev_class_mertens_products.tex:181, sec_chebotarev_class_mertens_products.tex:242, sec_chebotarev_class_mertens_products.tex:362, sec_chebotarev_class_mertens_products.tex:528, sec_chebotarev_class_mertens_products.tex:583, sec_chebotarev_class_mertens_products.tex:683","reason":"The product-tail reduction, exponentiation lemma, K_C formulas, three-logarithm interface, main product theorem, dependency map, coordinate equivalence, and adjacent finite-determinant evaluation are present and proved.","required_action":"Retain as headline theorem package; keep both K_C formulas and the classical leading exponent calibration."},
{"label":"Determinant formula and enclosures for F_rho(lambda^{-1})","location":"sec_chebotarev_class_mertens_determinants.tex:27, sec_chebotarev_class_mertens_determinants.tex:87, sec_chebotarev_class_mertens_determinants.tex:160, sec_chebotarev_class_mertens_determinants.tex:196, sec_chebotarev_class_mertens_determinants.tex:396, sec_chebotarev_class_mertens_determinants.tex:512","reason":"Singular-triple deletion, branch convention, determinant expression, finite algorithm, branch-tail ledger, and rational enclosures supply the computable finite twisted determinant data required by the contract.","required_action":"Always delete (r,m,pi)=(1,1,1) before boundary evaluation and state branch conventions explicitly."},
{"label":"Product rigidity, equivalence, and Adams obstruction","location":"sec_chebotarev_class_mertens_rigidity_core.tex:11, sec_chebotarev_class_mertens_rigidity_core.tex:143, sec_chebotarev_class_mertens_rigidity_core.tex:248, sec_chebotarev_class_mertens_rigidity_consequences.tex:49, sec_chebotarev_class_mertens_rigidity_consequences.tex:103, sec_chebotarev_class_mertens_rigidity_consequences.tex:265, sec_chebotarev_class_mertens_obstruction.tex:11, sec_chebotarev_class_mertens_obstruction.tex:92","reason":"Determinant-coordinate rigidity, hyperplane stability, assembled truncation, scalar-normalised equivalence, finite-rank obstruction skeleton, Artin substitution recovery, and obstruction norm are present as structural consequences.","required_action":"Keep as consequences; ensure finite truncation is always paired with determinant-coordinate descent and tail bounds."},
{"label":"Classical comparison theorem package","location":"sec_chebotarev_class_mertens_rigidity_consequences.tex:489, sec_chebotarev_class_mertens_rigidity_consequences.tex:730, sec_chebotarev_class_mertens_determinants.tex:843, sec_chebotarev_class_mertens_obstruction.tex:449, references.bib:335","reason":"The manuscript cites the Frobenius-class Mertens literature and states that the new contribution is the fixed-label Adams--Mobius determinant constant and Artin-log obstruction, not the classical leading exponent.","required_action":"Retain and polish the novelty calibration; verify all classical hypotheses before submission."},
{"label":"Eta-gap rigidity and Perron-point interface","location":"sec_chebotarev_main_inversion.tex:341, sec_eta_gap.tex:16, sec_eta_gap.tex:193, sec_eta_gap.tex:236, sec_eta_gap.tex:298, sec_eta_gap.tex:345, sec_eta_gap.tex:371, sec_eta_gap.tex:477, sec_eta_gap.tex:563, sec_eta_gap.tex:602, sec_eta_gap.tex:674","reason":"The finite-state gap characterisation, eta=lambda line-field rigidity, boundary classifier, character classification, perfect-loop corollary, finite certificate, separation argument, and Perron-point availability are present.","required_action":"Do not claim eta<lambda is automatic; keep it as a tested/assumed finite-state hypothesis for Main II--III."},
{"label":"Quotient, scalar projection, abelian shadow, and cyclic detection","location":"sec_shadows_quotient_boundary.tex:23, sec_shadows_quotient_boundary.tex:45, sec_shadows_quotient_boundary.tex:216, sec_shadows_quotient_boundary.tex:270, sec_shadows_quotient_boundary.tex:382, sec_shadows_quotient_boundary.tex:468, sec_shadows_quotient_boundary.tex:518, sec_shadows_abelian_and_cyclic.tex:8, sec_shadows_abelian_and_cyclic.tex:95, sec_shadows_abelian_and_cyclic.tex:141, sec_shadows_abelian_and_cyclic.tex:192","reason":"The class-profile definition, scalar projection boundary, no scalar cyclic-lift descent, quotient functoriality, abelianisation pullback, root-layer boundary, quotient-versus-root-layer warning, non-abelian defect, cyclic quotient lemma, cyclic detection boundary, and C3 check are present.","required_action":"Keep inherited cyclic quotients separated from reset fixed-matrix cyclic-lift root-of-unity data."},
{"label":"Certified S3 obstruction package","location":"sec_shadows_s3_certificates.tex:28, sec_shadows_s3_certificates.tex:83, sec_shadows_s3_certificates.tex:194, sec_shadows_s3_certificates.tex:274, sec_appendices_s3_model.tex:16, sec_appendices_s3_model.tex:115, sec_appendices_s3_model.tex:270, sec_appendices_s3_model.tex:355, sec_appendices_s3_model.tex:390, sec_appendices_s3_model.tex:417, sec_appendices_s3_certificates.tex:14, sec_appendices_s3_certificates.tex:252","reason":"The S3 model supplies the quadratic Adams mechanism, twisted/primitive channels, certified Pi and F intervals, and a main-text finite-state product obstruction proving naive Artin substitution fails.","required_action":"Keep rational certificates compiled; describe the obstruction structurally, not merely numerically."},
{"label":"Finite-state definitions and scalar support","location":"sec_preliminaries.tex:99, sec_preliminaries.tex:133, sec_preliminaries.tex:186, sec_preliminaries.tex:381, sec_preliminaries.tex:470, sec_preliminaries.tex:519, sec_preliminaries.tex:565, sec_finite_part.tex:26, sec_finite_part.tex:135, sec_finite_part.tex:160, sec_finite_part.tex:225, sec_finite_part.tex:310, sec_finite_part.tex:345","reason":"Trace/zeta identities, PF and primitive estimates, finite determinant data, reduced constant, Abel finite-part constant, cyclic-lift record definitions, scalar finite-part formulas, and no-descent scalar interface are present as auxiliary support.","required_action":"Classify classical scalar/PF material as support with citations; do not let scalar records become a parallel main theorem chain."}
],
"missing_in_scope_results":[],
"weak_in_scope_core_results":[
{"label":"Main III consequence overload","location":"sec_chebotarev_class_mertens_products.tex:528, sec_chebotarev_class_mertens_products.tex:583, sec_chebotarev_class_mertens_rigidity_core.tex:11, sec_chebotarev_class_mertens_rigidity_consequences.tex:103, sec_chebotarev_class_mertens_determinants.tex:624","reason":"The required core is present, but many rigidity/equivalence/truncation consequences compete with the main Adams-corrected product theorem for attention.","required_action":"Keep results but consider grouping as consequences or appendix support; do not demote core Main III."},
{"label":"Intro summaries duplicate body theorem interfaces","location":"sec_introduction_core.tex:342, sec_introduction_core.tex:375, sec_introduction_core.tex:412","reason":"The summaries have forwarding proofs and stable labels, which is useful but may confuse journal readers about authoritative theorem locations.","required_action":"If needed, mark as theorem summaries while preserving labels and body theorem authority."},
{"label":"Certificate normal-form statements are engineering-heavy","location":"sec_appendices_fixed_label_certificates.tex:11, sec_appendices_fixed_label_certificates.tex:91, sec_appendices_fixed_label_certificates.tex:182, sec_appendices_fixed_label_certificates.tex:205, sec_appendices_fixed_label_certificates.tex:274","reason":"The audit/certificate interface is useful but may be stronger and more procedural than necessary for a symbolic-dynamics paper.","required_action":"Retain as appendix support and make clear the analytic determinant formulas are the mathematical core."}
],
"proof_gaps":[
{"label":"No missing adjacent proofs detected","location":"main.tex input closure; 130 theorem-like environments scanned","reason":"A structural scan found no compiled theorem/proposition/lemma/corollary lacking an adjacent proof, and available compile outputs showed no unresolved citation/reference diagnostics.","required_action":"No immediate proof-interface patch is required; re-run compile checks after future edits."},
{"label":"Branch and singular-triple interface is fragile","location":"sec_chebotarev_fixed_label_and_boundary.tex:177, sec_chebotarev_class_mertens_determinants.tex:27, sec_chebotarev_class_mertens_determinants.tex:87, sec_chebotarev_class_mertens_products.tex:683","reason":"The proof is present but depends critically on deleting the scalar Perron determinant before z=lambda^{-1} evaluation and on Abel branches for non-trivial boundary values.","required_action":"Keep this convention repeated at every determinant formula for F_rho(lambda^{-1}) and K_C."},
{"label":"Classical Frobenius-Mertens citation calibration","location":"sec_chebotarev_class_mertens_additive.tex:3, sec_chebotarev_class_mertens_rigidity_consequences.tex:489, sec_chebotarev_class_mertens_obstruction.tex:449, references.bib","reason":"The manuscript properly treats the leading asymptotic as classical, but final submission needs exact matching of cited theorem hypotheses to the finite-state conventions used here.","required_action":"Verify Mesliza--Noorani, Noorani--Parry, Parry--Pollicott, and Sharp citations line-by-line."}
],
"supporting_appendix_or_background":[
{"label":"Classical scalar/PF/zeta inputs","location":"sec_preliminaries.tex:99, sec_preliminaries.tex:133, sec_preliminaries.tex:186, sec_finite_part.tex:26, sec_finite_part.tex:135, sec_finite_part.tex:160","reason":"These normalise the trivial channel and supply standard finite-matrix and scalar orbit-Mertens tools.","required_action":"Cite as background; do not present as new."},
{"label":"Finite representation theory and Adams coefficients","location":"sec_preliminaries.tex:348, sec_preliminaries.tex:367, sec_chebotarev_main_inversion.tex:207, sec_chebotarev_peter_weyl_bridge.tex:35, sec_chebotarev_peter_weyl_bridge.tex:65","reason":"Character orthogonality, class expansion, Adams operations, and coefficient bounds are classical finite-group infrastructure used by the new inversion theorem.","required_action":"Cite representation/lambda-ring background where appropriate."},
{"label":"S3 rational certificate appendices","location":"sec_appendices_s3_certificates.tex:14, sec_appendices_s3_certificates.tex:252, sec_appendices_s3_certificates.tex:452","reason":"Exact rational intervals support the S3 obstruction and include the product-level F_epsilon(1/2), F_rho(1/2) values required by the directive.","required_action":"Retain as appendix support; ensure prose approximations are backed by intervals."},
{"label":"Fixed-label certificate schema","location":"sec_appendices_fixed_label_certificates.tex:11, sec_appendices_fixed_label_certificates.tex:91, sec_appendices_fixed_label_certificates.tex:182, sec_appendices_fixed_label_certificates.tex:205, sec_appendices_fixed_label_certificates.tex:274","reason":"These are audit/reproducibility interfaces for finite determinant enclosures.","required_action":"Keep as appendix support, not as headline novelty."}
],
"out_of_scope_strong_results":[
{"label":"Secondary spectral-edge theorem chain","location":"split_staging/sec_secondary_term.tex:118, split_staging/sec_secondary_term.tex:191, split_staging/sec_secondary_term.tex:350, split_staging/sec_secondary_term.tex:469, split_staging/sec_secondary_term.tex:529, split_staging/sec_secondary_term.tex:566, split_staging/sec_secondary_term.tex:629, split_staging/sec_secondary_term.tex:672","reason":"Strong edge skeleton, secondary-tail, isolation, product refinement, classification, closure, and recovery results are staged but excluded from compiled main.tex.","required_action":"Do not compile here; retain only prop:main-chain-secondary-noninterference.","candidate_title":"Secondary Spectral Edges and Refined Frobenius-Class Mertens Tails","source_contribution":"Stage A found a coherent uncompiled theorem package in split_staging/sec_secondary_term.tex.","scope_mismatch":"It shifts the article from Perron-point determinant constants to secondary spectral refinements.","independent_paper_rationale":"The staged results can support a standalone refinement paper after hypothesis and literature calibration.","needed_to_split":["Audit secondary separation hypotheses","Compare with prime-orbit secondary-term literature","Add examples with visible secondary edges","Bridge current noninterference lemma to the split paper"]},
{"label":"Fixed-matrix cyclic-lift reconstruction package","location":"sec_appendices.tex:108, sec_appendices.tex:148, sec_appendices.tex:197, sec_appendices.tex:237, sec_appendices.tex:272, sec_appendices.tex:316, sec_appendices.tex:401, sec_appendices.tex:527","reason":"Reduced determinant, multiple-sum, Mobius inversion, branch ambiguity, spectrum identifiability, and one-layer Fourier reconstruction results are uncompiled companion material.","required_action":"Do not absorb into this finite-group cocycle article.","candidate_title":"Cyclic-Lift Determinant Reconstruction and One-Layer Fourier Recovery","source_contribution":"Stage A found a separate fixed-matrix reconstruction chain in uncompiled appendices.","scope_mismatch":"It concerns fixed-matrix cyclic lifts, not primitive-label Peter--Weyl data for finite-group extensions.","independent_paper_rationale":"The reconstruction and sampling mechanisms are independent and substantial.","needed_to_split":["Reset notation","Separate fixed-matrix from cocycle semantics","Add reconstruction examples","Deduplicate with sibling cyclic-block work"]},
{"label":"Scalar-boundary variation and truncation package","location":"sec_appendices_scalar_boundaries.tex:18, sec_appendices_scalar_boundaries.tex:135, sec_appendices_scalar_boundaries.tex:185, sec_appendices_scalar_boundaries.tex:255, sec_appendices_scalar_boundaries.tex:343","reason":"Holomorphic scalar variation, scalar perturbation/no-correction, no-descent, effective truncation, and scalar IO certificate results are uncompiled and auxiliary.","required_action":"Keep outside unless explicitly compiled in a later scope decision.","candidate_title":"Scalar Finite-Part Variation, Truncation Certificates, and No-Descent Boundaries","source_contribution":"Stage A identified a coherent scalar finite-part certificate package adjacent to the manuscript.","scope_mismatch":"The present paper's novelty is non-scalar finite-group fixed-label determinant recovery.","independent_paper_rationale":"The scalar certificate methods can support a computational or scalar finite-part note.","needed_to_split":["Calibrate scalar references","Decide computational versus analytic framing","Remove class-profile descent implications","Align with finite-part theory subtree"]},
{"label":"Holder/Ruelle transfer-operator chain","location":"scope_contract.md; sec_introduction_core.tex:258","reason":"The paper records this chain as split out and not a hidden input.","required_action":"Do not recreate it inside this finite-state article.","candidate_title":"Holder Transfer Operators and Perron-Point Continuation for Weighted Finite-Group Extensions","source_contribution":"Stage A confirmed its absence is intentional, not a gap.","scope_mismatch":"It requires Banach/thermodynamic machinery outside the finite-matrix scope.","independent_paper_rationale":"It could generalise the finite-state package to weighted systems.","needed_to_split":["Define Banach spaces","Prove weighted Perron continuation","Compare Ruelle/Pollicott conventions","State extension theorem"]}
],
"split_candidates":[
{"label":"Eta-gap sufficient-condition programme","location":"sec_eta_gap.tex:727; scope_contract.json out_of_scope","reason":"Current paper diagnoses/tests eta<lambda and classifies boundary obstruction; broader structural criteria forcing the gap are out of scope.","required_action":"Leave as open/split direction; do not claim eta<lambda automatically.","candidate_title":"Structural Criteria for Strict Twisted Gaps in Finite-Group Extensions of Mixing SFTs","source_contribution":"Stage A found a diagnostic rigidity interface that naturally leads to a classification project.","scope_mismatch":"It would change Main II--III from conditional to structural gap theorems.","independent_paper_rationale":"Strict-gap criteria would be independently valuable in symbolic dynamics and skew products.","needed_to_split":["Classify loop holonomy obstructions","Develop examples over perfect and non-perfect groups","Study stability under graph refinements","Compare Livsic/skew-product literature"]},
{"label":"Cyclic detection and non-abelian defect refinements","location":"sec_shadows_abelian_and_cyclic.tex:8, sec_shadows_abelian_and_cyclic.tex:141, sec_shadows_s3_certificates.tex:83","reason":"The current boundary theorem and S3 witness are in scope; broader non-abelian cyclic-arithmetic refinements are not.","required_action":"Keep only present boundary/obstruction results here.","candidate_title":"Cyclic Detection Boundaries and Non-Abelian Defects in Symbolic Group Extensions","source_contribution":"Stage A found a reusable obstruction spine separating one-dimensional cyclic observables from higher-dimensional Peter--Weyl sectors.","scope_mismatch":"Expanding it would distract from Adams-corrected Euler-product constants.","independent_paper_rationale":"A systematic family-level treatment could stand alone.","needed_to_split":["Develop groups beyond S3","Classify vanishing higher-dimensional defect","Separate inherited quotients from reset cyclic lifts","Add computations"]}
],
"irrelevant_or_remove":[
{"label":"None requiring immediate removal from compiled main.tex","location":"main.tex input closure","reason":"All compiled theorem-like items are core, supporting, appendix/certificate support, or explicit boundary material under the contract.","required_action":"Do not edit or remove theorem environments in this inventory stage; consider only later editorial reorganisation."}
],
"naive_truncation_risks":[
{"label":"Cyclic-lift records versus cocycle quotients","location":"sec_preliminaries.tex:565, sec_shadows_quotient_boundary.tex:45, sec_shadows_quotient_boundary.tex:216, sec_shadows_quotient_boundary.tex:468, sec_shadows_quotient_boundary.tex:518, sec_finite_part.tex:225","reason":"Root-of-unity cyclic-lift layers are reset fixed-matrix comparison records, not inherited cocycle quotient invariants.","required_action":"Keep no-descent and quotient-versus-root-layer warnings prominent."},
{"label":"Finite determinant truncations of F_rho","location":"sec_chebotarev_class_mertens_rigidity_core.tex:248, sec_chebotarev_class_mertens_determinants.tex:196, sec_chebotarev_class_mertens_determinants.tex:396, sec_appendices_fixed_label_certificates.tex:11","reason":"Finite truncations are enclosures with error ledgers, not invariants unless descended through the fixed determinant coordinate map and tail bounds.","required_action":"Always state truncation with explicit branch/tail ledger."},
{"label":"Scalar finite part cannot recover non-trivial class channels","location":"sec_finite_part.tex:225, sec_finite_part.tex:310, sec_finite_part.tex:345","reason":"Scalar data supply only trivial-channel normalisation; using them as class-profile surrogates erases the Adams correction.","required_action":"Require finite-group determinant data for class constants."},
{"label":"Artin logarithm versus fixed-label Euler transform","location":"sec_chebotarev_fixed_label_and_boundary.tex:177, sec_chebotarev_fixed_label_and_boundary.tex:275, sec_chebotarev_class_mertens_products.tex:242, sec_chebotarev_class_mertens_obstruction.tex:11, sec_appendices_s3_model.tex:355","reason":"Naively replacing F_rho by L_rho ignores Adams powers from repeated primitive labels and is the central false shortcut.","required_action":"Keep the obstruction criterion and S3 witness; only substitute Artin logarithms when the criterion is proved to vanish."}
],
"journal_style_gaps":[
{"label":"Theorem hierarchy and length","location":"sec_chebotarev_class_mertens*.tex, sec_eta_gap.tex, sec_shadows*.tex, appendices","reason":"Many propositions/corollaries sit at comparable weight, which may obscure the three main theorem packages for a venue referee.","required_action":"Maintain a theorem-dependency table and move purely technical ledgers/certificates to appendices where possible while preserving labels."},
{"label":"Classical-result calibration","location":"sec_chebotarev_class_mertens_additive.tex:3, sec_chebotarev_class_mertens_rigidity_consequences.tex:489, sec_chebotarev_class_mertens_obstruction.tex:449, references.bib","reason":"The paper acknowledges classical class-Mertens asymptotics but should precisely separate cited leading terms from new determinant constants.","required_action":"Polish theorem-by-theorem novelty comparison before submission."},
{"label":"Notation load for Pi, L, F, M_C, K_C, Delta_C, eta, and branches","location":"sec_chebotarev_class_mertens_overview.tex:1, sec_chebotarev_fixed_label_and_boundary.tex:177, sec_chebotarev_class_mertens_products.tex:362, sec_chebotarev_class_mertens_determinants.tex:27","reason":"The core distinction requires several related transforms and branch conventions.","required_action":"Keep or strengthen the notation table in the class-Mertens overview."},
{"label":"Compiled versus uncompiled boundaries","location":"main.tex:95, main.tex:107, sec_appendices.tex, sec_appendices_scalar_boundaries.tex, split_staging/sec_secondary_term.tex","reason":"The directory contains strong uncompiled theorem packages that future readers could mistake for missing dependencies.","required_action":"Keep scope-boundary notes and avoid referencing uncompiled labels except as split/companion material."}
]
}
keys=["valid","in_scope_present","missing_in_scope_results","weak_in_scope_core_results","proof_gaps","supporting_appendix_or_background","out_of_scope_strong_results","split_candidates","irrelevant_or_remove","naive_truncation_risks","journal_style_gaps"]
I={k:I[k] for k in keys}
pathlib.Path('theorem_inventory.json').write_text(json.dumps(I,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
md=['# Theorem Inventory\n\nStage A scope-bound theorem inventory. `theorem_inventory.json` is authoritative; this file mirrors it for reading.\n\n']
for k in keys:
    md.append('## '+k.replace('_',' ').title()+'\n')
    v=I[k]
    if isinstance(v,bool): md.append(f'- `{str(v).lower()}`\n\n')
    elif not v: md.append('- None.\n\n')
    else:
        for it in v:
            md.append(f"- **{it['label']}** (`{it['location']}`)\n  - Reason: {it['reason']}\n  - Required action: {it['required_action']}\n")
            for extra in ['candidate_title','source_contribution','scope_mismatch','independent_paper_rationale']:
                if extra in it: md.append(f"  - {extra.replace('_',' ').title()}: {it[extra]}\n")
            if 'needed_to_split' in it: md.append('  - Needed to split: '+', '.join(it['needed_to_split'])+'\n')
        md.append('\n')
pathlib.Path('theorem_inventory.md').write_text(''.join(md),encoding='utf-8')
print('wrote theorem_inventory.json and theorem_inventory.md')
