import Omega.DerivedConsequences.DerivedLocalizedPhaseFibersSadicTorsorForgetting
import Omega.DerivedConsequences.DerivedFiniteAnomalyLedgerNoFaithfulMultiplicativeSkeleton
import Omega.DerivedConsequences.DerivedM2Level3Common24Defect15ExactSequence
import Omega.DerivedConsequences.DerivedProjectivePathGibbsCumulants
