import Omega.Multiscale.PadicHypercubeStokesHaar
import Omega.Multiscale.RobustNormalizedStokesWithDefectBudget
import Omega.Multiscale.SolenoidNormalizedStokesL2ScalingCriticalDegree
import Omega.Multiscale.StokesPeriodModuleCovectorNormalization
