import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.Tactic
import Omega.POM.MomentResonance

namespace Omega.POM

/-- The ambient real moment-vector space for the `d + Delta` visible coordinates. -/
abbrev MomentAmbient (d Delta : ℕ) := Fin (d + Delta) → ℝ

/-- The minimal visible linear realization space generated by the moment vectors with `m ≥ m₀`. -/
def visibleMomentSubspace (m0 : ℕ) {d Delta : ℕ} (M : ℕ → MomentAmbient d Delta) :
    Submodule ℝ (MomentAmbient d Delta) :=
  Submodule.span ℝ (Set.range fun m : {n : ℕ // m0 ≤ n} => M m.1)

/-- The coordinate functional associated to a coefficient vector. -/
def coordinateFunctional {n : ℕ} (alpha : Fin n → ℝ) : Module.Dual ℝ (Fin n → ℝ) where
  toFun v := ∑ i, alpha i * v i
  map_add' v w := by
    simp [mul_add, Finset.sum_add_distrib]
  map_smul' c v := by
    change ∑ i, alpha i * (c * v i) = c * ∑ i, alpha i * v i
    calc
      ∑ i, alpha i * (c * v i) = ∑ i, c * (alpha i * v i) := by
        apply Finset.sum_congr rfl
        intro i hi
        ring
      _ = c * ∑ i, alpha i * v i := by
        rw [Finset.mul_sum]

/-- The coordinate-functional construction is linear in the coefficient vector. -/
def coordinateFunctionalLinear {n : ℕ} :
    (Fin n → ℝ) →ₗ[ℝ] Module.Dual ℝ (Fin n → ℝ) where
  toFun := coordinateFunctional
  map_add' alpha beta := by
    ext v
    simp [coordinateFunctional, add_mul, Finset.sum_add_distrib]
  map_smul' c alpha := by
    apply DFunLike.ext
    intro w
    change ∑ i, (c * alpha i) * w i = c * ∑ i, alpha i * w i
    calc
      ∑ i, (c * alpha i) * w i = ∑ i, c * (alpha i * w i) := by
        apply Finset.sum_congr rfl
        intro i hi
        ring
      _ = c * ∑ i, alpha i * w i := by
        rw [Finset.mul_sum]

theorem coordinateFunctional_injective {n : ℕ} :
    Function.Injective (@coordinateFunctional n) := by
  intro alpha beta h
  funext i
  let e : Fin n → ℝ := fun j => if j = i then 1 else 0
  have hi := congrArg (fun f : Module.Dual ℝ (Fin n → ℝ) => f e) h
  simpa [e, coordinateFunctional] using hi

/-- The `Delta` independent annihilating constraints from
`paper_pom_delta_counts_constraints` force the quotient by the minimal visible realization space
to have dimension at least `Delta`, so at least `Delta` extra independent linear readout axes are
needed to separate the hidden directions.
    cor:pom-delta-min-extra-readouts -/
theorem paper_pom_delta_min_extra_readouts
    (d Delta m0 : ℕ)
    (M : ℕ → MomentAmbient d Delta)
    (T : Matrix (Fin (d + Delta)) (Fin (d + Delta)) ℝ)
    (hInv : IsUnit T.det)
    (hTail : ∀ m ≥ m0, ∀ j : Fin Delta, (T.mulVec (M m)) (Fin.natAdd d j) = 0) :
    Delta ≤ Module.finrank ℝ ((MomentAmbient d Delta) ⧸ visibleMomentSubspace m0 M) := by
  obtain ⟨constraints, hlin, hvanish⟩ :=
    paper_pom_delta_counts_constraints d Delta m0 M T hInv hTail
  let V : Submodule ℝ (MomentAmbient d Delta) := visibleMomentSubspace m0 M
  have hAnn : ∀ j, coordinateFunctional (constraints j) ∈ V.dualAnnihilator := by
    intro j
    rw [Submodule.mem_dualAnnihilator]
    intro v hv
    change v ∈ Submodule.span ℝ (Set.range fun m : {n : ℕ // m0 ≤ n} => M m.1) at hv
    refine Submodule.span_induction
      (p := fun x _ => coordinateFunctional (constraints j) x = 0) ?_ ?_ ?_ ?_ hv
    · rintro _ ⟨m, rfl⟩
      exact hvanish m.1 m.2 j
    · simp [coordinateFunctional]
    · intro x y hx hy hx0 hy0
      have hxsum : ∑ i, constraints j i * x i = 0 := by
        simpa [coordinateFunctional] using hx0
      have hysum : ∑ i, constraints j i * y i = 0 := by
        simpa [coordinateFunctional] using hy0
      calc
        ∑ i, constraints j i * (x i + y i) =
            ∑ i, constraints j i * x i + ∑ i, constraints j i * y i := by
              simp [mul_add, Finset.sum_add_distrib]
        _ = 0 := by rw [hxsum, hysum]; simp
    · intro c x hx hx0
      have hxsum : ∑ i, constraints j i * x i = 0 := by
        simpa [coordinateFunctional] using hx0
      calc
        ∑ i, constraints j i * (c * x i) = c * ∑ i, constraints j i * x i := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro i hi
          ring
        _ = c * 0 := by rw [hxsum]
        _ = 0 := by simp
  let lifted : Fin Delta → V.dualAnnihilator := fun j =>
    ⟨coordinateFunctional (constraints j), hAnn j⟩
  have hlinLifted :
      LinearIndependent ℝ
        (fun j => ((lifted j : V.dualAnnihilator) : Module.Dual ℝ (MomentAmbient d Delta))) := by
    have hker :
        (coordinateFunctionalLinear :
          MomentAmbient d Delta →ₗ[ℝ] Module.Dual ℝ (MomentAmbient d Delta)).ker = ⊥ := by
      exact LinearMap.ker_eq_bot.mpr coordinateFunctional_injective
    simpa [lifted] using
      hlin.map'
        (coordinateFunctionalLinear :
          MomentAmbient d Delta →ₗ[ℝ] Module.Dual ℝ (MomentAmbient d Delta))
        hker
  have hlinSubtype : LinearIndependent ℝ lifted := by
    exact LinearIndependent.of_comp V.dualAnnihilator.subtype hlinLifted
  have hcard : Delta ≤ Module.finrank ℝ V.dualAnnihilator := by
    simpa [V] using hlinSubtype.fintype_card_le_finrank
  have hEq : Module.finrank ℝ ((MomentAmbient d Delta) ⧸ V) = Module.finrank ℝ V.dualAnnihilator := by
    have hquot := Submodule.finrank_quotient_add_finrank V
    have hdual := Subspace.finrank_add_finrank_dualAnnihilator_eq V
    omega
  rw [hEq]
  exact hcard

end Omega.POM
