import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Omega.POM

/-- Concrete data for the diagonal keep-resample channel. The diagonal kernel entry is interpreted
as the keep probability, while the off-diagonal mass is generated by resampling from the fixed
law `resample`. -/
structure DiagonalRateKeepResampleChannelData where
  State : Type
  instDecidableEqState : DecidableEq State
  kernel : State → State → ℝ
  resample : State → ℝ
  diagonal_nonneg : ∀ x, 0 ≤ kernel x x
  diagonal_le_one : ∀ x, kernel x x ≤ 1
  channelFactorization :
    ∀ x y, kernel x y = (if y = x then kernel x x else 0) + (1 - kernel x x) * resample y

attribute [instance] DiagonalRateKeepResampleChannelData.instDecidableEqState

/-- Keep probability extracted from the diagonal of the channel kernel. -/
def DiagonalRateKeepResampleChannelData.keepProb
    (D : DiagonalRateKeepResampleChannelData) (x : D.State) : ℝ :=
  D.kernel x x

/-- The diagonal kernel entry is a genuine probability. -/
def DiagonalRateKeepResampleChannelData.keepProbInUnitInterval
    (D : DiagonalRateKeepResampleChannelData) : Prop :=
  ∀ x, 0 ≤ D.keepProb x ∧ D.keepProb x ≤ 1

/-- The keep probability is exactly the diagonal channel mass. -/
def DiagonalRateKeepResampleChannelData.diagonalFormula
    (D : DiagonalRateKeepResampleChannelData) : Prop :=
  ∀ x, D.keepProb x = D.kernel x x

/-- Away from the diagonal, the channel law factors through the resampling distribution. -/
def DiagonalRateKeepResampleChannelData.offDiagonalResampleFormula
    (D : DiagonalRateKeepResampleChannelData) : Prop :=
  ∀ ⦃x y : D.State⦄, y ≠ x → D.kernel x y = (1 - D.keepProb x) * D.resample y

/-- The diagonal-rate channel splits into a keep move with probability `K(x,x)` and a resample
move carrying the remaining mass.
    prop:pom-diagonal-rate-keep-resample-channel -/
theorem paper_pom_diagonal_rate_keep_resample_channel (D : DiagonalRateKeepResampleChannelData) :
    D.keepProbInUnitInterval ∧ D.diagonalFormula ∧ D.offDiagonalResampleFormula := by
  refine ⟨?_, ?_, ?_⟩
  · intro x
    exact ⟨D.diagonal_nonneg x, D.diagonal_le_one x⟩
  · intro x
    rfl
  · intro x y hxy
    rw [D.channelFactorization x y]
    simp [DiagonalRateKeepResampleChannelData.keepProb, hxy]

end Omega.POM
