import Mathlib.Data.Matrix.Reflection
import Mathlib.Tactic

open Matrix

namespace Omega.POM

/-- Scalar model for the `q`-fold tensorization of a transition weight. -/
def momqTensorizedScalar (q t : Nat) : Nat :=
  t ^ q

/-- Tensorized multiplication agrees with multiplication before tensorization. -/
theorem momqTensorizedScalar_mul (q t₀ t₁ : Nat) :
    momqTensorizedScalar q t₁ * momqTensorizedScalar q t₀ =
      momqTensorizedScalar q (t₁ * t₀) := by
  simpa [momqTensorizedScalar] using (mul_pow t₁ t₀ q).symm

/-- The block kernel `A_q^{ten}` encoded as a `2 × 2` matrix. -/
def momqTensorKernelA (q : Nat) : Matrix (Fin 2) (Fin 2) Nat :=
  !![momqTensorizedScalar q 1, momqTensorizedScalar q 1;
    momqTensorizedScalar q 1, momqTensorizedScalar q 2]

/-- Recursive block matrices `C_m^(q)` generated by right multiplication with `A_q^{ten}`. -/
def momqTensorKernelC (q : Nat) : Nat → Matrix (Fin 2) (Fin 2) Nat
  | 0 => 1
  | m + 1 => momqTensorKernelC q m * momqTensorKernelA q

/-- Paper-facing power formula for the tensor kernel blocks. -/
def MomqTensorKernelPowerFormula (q m : Nat) : Prop :=
  momqTensorKernelC q m = momqTensorKernelA q ^ m

theorem momqTensorKernelC_eq_pow (q : Nat) :
    ∀ m, momqTensorKernelC q m = momqTensorKernelA q ^ m
  | 0 => by
      simp [momqTensorKernelC, momqTensorKernelA]
  | m + 1 => by
      simp [momqTensorKernelC, momqTensorKernelC_eq_pow q m, pow_succ]

/-- Block-matrix power formula for the tensor kernel.
    prop:pom-momq-tensor-kernel-noncommutative-fibonacci-powers -/
theorem paper_pom_momq_tensor_kernel_noncommutative_fibonacci_powers
    (q m : Nat) : MomqTensorKernelPowerFormula q m := by
  simpa [MomqTensorKernelPowerFormula] using momqTensorKernelC_eq_pow q m

end Omega.POM
