import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Order.ConditionallyCompleteLattice.Basic
import Mathlib.Tactic

namespace Omega.POM

noncomputable section

/-- Concrete finite-volume exponential moment under uniform composition normalization. -/
def pom_multiplicity_energy_ldp_uniform_uniformExpectation
    (partitionFunction : ℕ → ℝ → ℝ) (L : ℕ) (t : ℝ) : ℝ :=
  partitionFunction L (1 + t) / partitionFunction L 1

/-- Legendre-Fenchel rate generated by the uniform normalized log-mgf. -/
def pom_multiplicity_energy_ldp_uniform_legendreRate
    (normalizedLogMgfLimit : ℝ → ℝ) (e : ℝ) : ℝ :=
  sSup
    (Set.range fun t : {t : ℝ // -1 < t} =>
      (t : ℝ) * e - normalizedLogMgfLimit (t : ℝ))

/-- Data for the uniform-composition multiplicity LDP interface: the pressure evaluator, the
uniform normalization limit, and the Legendre-rate certificate. -/
structure pom_multiplicity_energy_ldp_uniform_data where
  pom_multiplicity_energy_ldp_uniform_partitionFunction : ℕ → ℝ → ℝ
  pom_multiplicity_energy_ldp_uniform_pressureLimit : ℝ → ℝ
  pom_multiplicity_energy_ldp_uniform_lambda : ℝ → ℝ
  pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit : ℝ → ℝ
  pom_multiplicity_energy_ldp_uniform_rate : ℝ → ℝ
  pom_multiplicity_energy_ldp_uniform_pressureLimit_eval :
    ∀ q : ℝ, 0 < q →
      pom_multiplicity_energy_ldp_uniform_pressureLimit q =
        Real.log (pom_multiplicity_energy_ldp_uniform_lambda q)
  pom_multiplicity_energy_ldp_uniform_logMgfLimit_from_uniform_pressure :
    ∀ t : ℝ, -1 < t →
      pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit t =
        pom_multiplicity_energy_ldp_uniform_pressureLimit (1 + t) -
          pom_multiplicity_energy_ldp_uniform_pressureLimit 1
  pom_multiplicity_energy_ldp_uniform_rate_formula :
    ∀ e : ℝ,
      pom_multiplicity_energy_ldp_uniform_rate e =
        pom_multiplicity_energy_ldp_uniform_legendreRate
          pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit e

namespace pom_multiplicity_energy_ldp_uniform_data

/-- Uniform-composition LDP conclusion: finite-volume normalization, pressure log-mgf, and
Legendre transform rate. -/
def uniformEnergyLDP (D : pom_multiplicity_energy_ldp_uniform_data) : Prop :=
  (∀ L : ℕ, ∀ t : ℝ,
    pom_multiplicity_energy_ldp_uniform_uniformExpectation
        D.pom_multiplicity_energy_ldp_uniform_partitionFunction L t =
      D.pom_multiplicity_energy_ldp_uniform_partitionFunction L (1 + t) /
        D.pom_multiplicity_energy_ldp_uniform_partitionFunction L 1) ∧
    (∀ t : ℝ, -1 < t →
      D.pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit t =
        Real.log (D.pom_multiplicity_energy_ldp_uniform_lambda (1 + t)) -
          Real.log (D.pom_multiplicity_energy_ldp_uniform_lambda 1)) ∧
      ∀ e : ℝ,
        D.pom_multiplicity_energy_ldp_uniform_rate e =
          pom_multiplicity_energy_ldp_uniform_legendreRate
            D.pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit e

end pom_multiplicity_energy_ldp_uniform_data

/-- Paper label: `thm:pom-multiplicity-energy-ldp-uniform`. Replacing the fiber-weighted
normalization by the uniform composition normalization leaves the partition-function ratio in the
same form; the pressure identities at `1 + t` and `1` give the limiting log-mgf, and the rate is
the corresponding Legendre-Fenchel transform. -/
theorem paper_pom_multiplicity_energy_ldp_uniform
    (D : pom_multiplicity_energy_ldp_uniform_data) : D.uniformEnergyLDP := by
  refine ⟨?_, ?_, ?_⟩
  · intro L t
    rfl
  · intro t ht
    have hq : 0 < 1 + t := by linarith
    have h1 : (0 : ℝ) < 1 := by norm_num
    calc
      D.pom_multiplicity_energy_ldp_uniform_normalizedLogMgfLimit t =
          D.pom_multiplicity_energy_ldp_uniform_pressureLimit (1 + t) -
            D.pom_multiplicity_energy_ldp_uniform_pressureLimit 1 := by
        exact D.pom_multiplicity_energy_ldp_uniform_logMgfLimit_from_uniform_pressure t ht
      _ = Real.log (D.pom_multiplicity_energy_ldp_uniform_lambda (1 + t)) -
          Real.log (D.pom_multiplicity_energy_ldp_uniform_lambda 1) := by
        rw [D.pom_multiplicity_energy_ldp_uniform_pressureLimit_eval (1 + t) hq,
          D.pom_multiplicity_energy_ldp_uniform_pressureLimit_eval 1 h1]
  · intro e
    exact D.pom_multiplicity_energy_ldp_uniform_rate_formula e

end

end Omega.POM
