import Mathlib.Tactic
import Omega.POM.OracleCriticalWindowGaussian

namespace Omega.POM

noncomputable section

/-- Concrete critical-window Edgeworth data.  The scale is the first correction scale
(`m^{-1/2}` in the paper), while the threshold and success probabilities are kept separate so
the soft-tail transfer from the Gaussian-window theorem can be reused. -/
structure pom_oracle_critical_window_edgeworth_data where
  pom_oracle_critical_window_edgeworth_sigma : ℝ
  pom_oracle_critical_window_edgeworth_kappa3 : ℝ
  pom_oracle_critical_window_edgeworth_scale : ℕ → ℝ
  pom_oracle_critical_window_edgeworth_normalCDF : ℝ → ℝ
  pom_oracle_critical_window_edgeworth_normalPDF : ℝ → ℝ
  pom_oracle_critical_window_edgeworth_thresholdProbability : ℝ → ℕ → ℝ
  pom_oracle_critical_window_edgeworth_softTailRemainder : ℝ → ℕ → ℝ
  pom_oracle_critical_window_edgeworth_successProbability : ℝ → ℕ → ℝ

/-- The standardized critical-window coordinate. -/
def pom_oracle_critical_window_edgeworth_z
    (D : pom_oracle_critical_window_edgeworth_data) (t : ℝ) : ℝ :=
  t / D.pom_oracle_critical_window_edgeworth_sigma

/-- The first Edgeworth coefficient generated by the third pressure derivative. -/
def pom_oracle_critical_window_edgeworth_coefficient
    (D : pom_oracle_critical_window_edgeworth_data) (t : ℝ) : ℝ :=
  D.pom_oracle_critical_window_edgeworth_kappa3 /
      (6 * D.pom_oracle_critical_window_edgeworth_sigma ^ 3) *
    (1 - pom_oracle_critical_window_edgeworth_z D t ^ 2) *
      D.pom_oracle_critical_window_edgeworth_normalPDF
        (pom_oracle_critical_window_edgeworth_z D t)

/-- The third-order local expansion at the threshold side of the critical window. -/
def pom_oracle_critical_window_edgeworth_thresholdExpansion
    (D : pom_oracle_critical_window_edgeworth_data) : Prop :=
  ∀ t : ℝ,
    Filter.Tendsto
      (fun m : ℕ =>
        D.pom_oracle_critical_window_edgeworth_thresholdProbability t m -
          (D.pom_oracle_critical_window_edgeworth_normalCDF
              (pom_oracle_critical_window_edgeworth_z D t) +
            pom_oracle_critical_window_edgeworth_coefficient D t *
              D.pom_oracle_critical_window_edgeworth_scale m))
      Filter.atTop (nhds 0)

/-- The same soft-tail Laplace decomposition used in the Gaussian critical-window transfer. -/
def pom_oracle_critical_window_edgeworth_successLaplaceDecomposition
    (D : pom_oracle_critical_window_edgeworth_data) : Prop :=
  ∀ t : ℝ,
    Filter.Tendsto
        (fun m : ℕ => D.pom_oracle_critical_window_edgeworth_softTailRemainder t m)
        Filter.atTop (nhds 0) ∧
      (∀ᶠ m in Filter.atTop,
        D.pom_oracle_critical_window_edgeworth_successProbability t m =
          D.pom_oracle_critical_window_edgeworth_thresholdProbability t m +
            D.pom_oracle_critical_window_edgeworth_softTailRemainder t m)

/-- The paper-facing Edgeworth conclusion: after subtracting the Gaussian term and the cubic
correction, the remaining success error tends to zero. -/
def pom_oracle_critical_window_edgeworth_successExpansion
    (D : pom_oracle_critical_window_edgeworth_data) : Prop :=
  ∀ t : ℝ,
    Filter.Tendsto
      (fun m : ℕ =>
        D.pom_oracle_critical_window_edgeworth_successProbability t m -
          (D.pom_oracle_critical_window_edgeworth_normalCDF
              (pom_oracle_critical_window_edgeworth_z D t) +
            pom_oracle_critical_window_edgeworth_coefficient D t *
              D.pom_oracle_critical_window_edgeworth_scale m))
      Filter.atTop (nhds 0)

/-- Concrete theorem statement for `thm:pom-oracle-critical-window-edgeworth`. -/
def pom_oracle_critical_window_edgeworth_statement
    (D : pom_oracle_critical_window_edgeworth_data) : Prop :=
  pom_oracle_critical_window_edgeworth_thresholdExpansion D →
    pom_oracle_critical_window_edgeworth_successLaplaceDecomposition D →
      pom_oracle_critical_window_edgeworth_successExpansion D

/-- Paper label: `thm:pom-oracle-critical-window-edgeworth`. -/
theorem paper_pom_oracle_critical_window_edgeworth
    (D : pom_oracle_critical_window_edgeworth_data) :
    pom_oracle_critical_window_edgeworth_statement D := by
  intro hthreshold hlaplace t
  rcases hlaplace t with ⟨htail, hdecomp⟩
  have hthreshold_t := hthreshold t
  have hsum :
      Filter.Tendsto
        (fun m : ℕ =>
          (D.pom_oracle_critical_window_edgeworth_thresholdProbability t m -
            (D.pom_oracle_critical_window_edgeworth_normalCDF
                (pom_oracle_critical_window_edgeworth_z D t) +
              pom_oracle_critical_window_edgeworth_coefficient D t *
                D.pom_oracle_critical_window_edgeworth_scale m)) +
            D.pom_oracle_critical_window_edgeworth_softTailRemainder t m)
        Filter.atTop (nhds (0 + 0)) :=
    hthreshold_t.add htail
  have hcongr :
      (fun m : ℕ =>
        D.pom_oracle_critical_window_edgeworth_successProbability t m -
          (D.pom_oracle_critical_window_edgeworth_normalCDF
              (pom_oracle_critical_window_edgeworth_z D t) +
            pom_oracle_critical_window_edgeworth_coefficient D t *
              D.pom_oracle_critical_window_edgeworth_scale m)) =ᶠ[Filter.atTop]
        fun m : ℕ =>
          (D.pom_oracle_critical_window_edgeworth_thresholdProbability t m -
            (D.pom_oracle_critical_window_edgeworth_normalCDF
                (pom_oracle_critical_window_edgeworth_z D t) +
              pom_oracle_critical_window_edgeworth_coefficient D t *
                D.pom_oracle_critical_window_edgeworth_scale m)) +
            D.pom_oracle_critical_window_edgeworth_softTailRemainder t m := by
    filter_upwards [hdecomp] with m hm
    rw [hm]
    ring
  simpa using hsum.congr' hcongr.symm

end

end Omega.POM
