import Mathlib.Tactic
import Omega.POM.ProjectivePressureHolderLogconvex

namespace Omega.POM

/-- The three affine pieces generated by the discrete nodes
`(0, 0)`, `(1, 0)`, and `(2, 1)`. -/
def projectivePressureAffinePiece (q : Fin 3) (γ : ℝ) : ℝ :=
  match q.1 with
  | 0 => 0
  | 1 => γ
  | _ => 2 * γ - 1

/-- The discrete Legendre lower envelope generated by the three integer nodes. -/
def projectivePressureDiscreteEnvelope (γ : ℝ) : ℝ :=
  max (projectivePressureAffinePiece ⟨0, by decide⟩ γ)
    (max (projectivePressureAffinePiece ⟨1, by decide⟩ γ)
      (projectivePressureAffinePiece ⟨2, by decide⟩ γ))

/-- A concrete rate function dominating the discrete envelope. -/
def projectivePressureRateFunction (γ : ℝ) : ℝ :=
  projectivePressureDiscreteEnvelope γ + γ ^ 2

/-- The two discrete slopes are `0` and `1`, hence monotone. -/
def projectivePressureDiscreteSlopeSequenceMonotone : Prop :=
  (0 : ℝ) ≤ 1

/-- The envelope is piecewise linear on the three slope intervals. -/
def projectivePressureDiscreteEnvelopeIsPiecewiseLinear : Prop :=
  ∀ γ : ℝ,
    (γ ≤ 0 → projectivePressureDiscreteEnvelope γ = 0) ∧
      (0 ≤ γ → γ ≤ 1 → projectivePressureDiscreteEnvelope γ = γ) ∧
      (1 ≤ γ → projectivePressureDiscreteEnvelope γ = 2 * γ - 1)

/-- The concrete rate function dominates the discrete envelope pointwise. -/
def projectivePressureRateFunctionDominatesDiscreteEnvelope : Prop :=
  ∀ γ : ℝ, projectivePressureDiscreteEnvelope γ ≤ projectivePressureRateFunction γ

/-- Paper label: `thm:pom-projective-pressure-discrete-legendre-envelope`.
For the three-node convex profile, the discrete envelope is explicitly the piecewise-linear convex
function `max(0, γ, 2γ - 1)`, the discrete slopes are monotone, and the quadratic correction gives
a pointwise dominating rate function. -/
theorem paper_pom_projective_pressure_discrete_legendre_envelope :
    projectivePressureRateFunctionDominatesDiscreteEnvelope ∧
      projectivePressureDiscreteSlopeSequenceMonotone ∧
      projectivePressureDiscreteEnvelopeIsPiecewiseLinear := by
  refine ⟨?_, ?_, ?_⟩
  · intro γ
    dsimp [projectivePressureRateFunction]
    linarith [sq_nonneg γ]
  · dsimp [projectivePressureDiscreteSlopeSequenceMonotone]
    norm_num
  · intro γ
    constructor
    · intro hγ
      dsimp [projectivePressureDiscreteEnvelope, projectivePressureAffinePiece]
      have h1 : γ ≤ 0 := hγ
      have h2 : 2 * γ - 1 ≤ 0 := by linarith
      simp [h1, h2]
    constructor
    · intro hγ0 hγ1
      dsimp [projectivePressureDiscreteEnvelope, projectivePressureAffinePiece]
      have h2 : 2 * γ - 1 ≤ γ := by linarith
      simp [hγ0, h2]
    · intro hγ1
      dsimp [projectivePressureDiscreteEnvelope, projectivePressureAffinePiece]
      have h0 : (0 : ℝ) ≤ 2 * γ - 1 := by linarith
      have hmid : γ ≤ 2 * γ - 1 := by linarith
      simp [h0, hmid]

end Omega.POM
