import Mathlib.Tactic
import Omega.POM.HankelSyndromeModuleKernelEqualsMultiples

namespace Omega.POM

/-- Concrete resonance-window package for comparing the rectangular `H(q)^T` kernel with the
square Hankel kernel already handled by `paper_pom_hankel_syndrome_module_kernel_equals_multiples`.
The sets live on the same coefficient space `Fin n → ℤ`; `nullModeKernel` is the resonance-window
kernel, `squareKernel` is the square Hankel kernel, and `multipleModule` is the truncated multiple
module generated by the minimal annihilator. -/
structure ResonanceHankelNullIntegralPrincipalizationData where
  kernelEqualsMultiplesData : HankelSyndromeKernelEqualsMultiplesData
  n : ℕ
  L : ℕ
  hLn : n ≤ L
  nullModeKernel : Set (Fin n → ℤ)
  squareKernel : Set (Fin n → ℤ)
  multipleModule : Set (Fin n → ℤ)
  nullMode_eq_squareKernel : nullModeKernel = squareKernel
  squareKernel_subset_multipleModule :
    kernelEqualsMultiplesData.kernelContainedInMultiples → squareKernel ⊆ multipleModule
  multipleModule_subset_squareKernel :
    kernelEqualsMultiplesData.multiplesContainedInKernel → multipleModule ⊆ squareKernel

namespace ResonanceHankelNullIntegralPrincipalizationData

/-- Paper conclusion: the resonance-window null modes agree with the truncated multiple module. -/
def nullModesEqMultiples (D : ResonanceHankelNullIntegralPrincipalizationData) : Prop :=
  D.nullModeKernel = D.multipleModule

end ResonanceHankelNullIntegralPrincipalizationData

open ResonanceHankelNullIntegralPrincipalizationData

/-- Paper label: `thm:pom-resonance-hankel-null-integral-principalization`. -/
theorem paper_pom_resonance_hankel_null_integral_principalization
    (D : ResonanceHankelNullIntegralPrincipalizationData) : D.nullModesEqMultiples := by
  rcases
      paper_pom_hankel_syndrome_module_kernel_equals_multiples D.kernelEqualsMultiplesData with
    ⟨hKernelContainedInMultiples, hMultiplesContainedInKernel⟩
  apply Set.Subset.antisymm
  · intro x hx
    have hxSquare : x ∈ D.squareKernel := by simpa [D.nullMode_eq_squareKernel] using hx
    exact D.squareKernel_subset_multipleModule hKernelContainedInMultiples hxSquare
  · intro x hx
    have hxSquare : x ∈ D.squareKernel :=
      D.multipleModule_subset_squareKernel hMultiplesContainedInKernel hx
    simpa [D.nullMode_eq_squareKernel] using hxSquare

end Omega.POM
