import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Tactic
import Omega.POM.DispersionLqLowerBound
import Omega.POM.SpectrumLegendreUpper

namespace Omega.POM

namespace FiberDispersionIndexData

/-- The logarithmic intermittency deficit extracted from the Cauchy--Schwarz moment comparison. -/
noncomputable def pom_spectrum_intermittency_deficit_value
    (D : FiberDispersionIndexData) : ℝ :=
  Real.log (((D.m : ℝ) * D.sqMoment) / D.totalMass ^ (2 : ℕ))

lemma pom_spectrum_intermittency_deficit_value_nonneg (D : FiberDispersionIndexData) :
    0 ≤ D.pom_spectrum_intermittency_deficit_value := by
  have hcs : D.totalMass ^ (2 : ℕ) ≤ (D.m : ℝ) * D.sqMoment :=
    (paper_pom_dispersion_lq_lower_bound D).1
  have hden_pos : 0 < D.totalMass ^ (2 : ℕ) := sq_pos_of_pos D.totalMass_pos
  have hratio_ge_one :
      1 ≤ ((D.m : ℝ) * D.sqMoment) / D.totalMass ^ (2 : ℕ) := by
    rw [one_le_div₀ hden_pos]
    simpa [mul_comm, mul_left_comm, mul_assoc] using hcs
  exact Real.log_nonneg hratio_ge_one

end FiberDispersionIndexData

/-- Concrete data for the spectrum-intermittency deficit: finite fiber dispersion data plus the
pointwise bounds used by the Legendre upper-envelope wrapper. -/
structure pom_spectrum_intermittency_deficit_data where
  dispersion : FiberDispersionIndexData
  f : ℝ → ℝ
  tau : ℝ → ℝ
  legendre_bound : ∀ q γ : ℝ, 2 ≤ q → 0 ≤ γ → f γ ≤ tau q - q * γ

namespace pom_spectrum_intermittency_deficit_data

/-- The paper-facing statement: the intermittency deficit is nonnegative, and the spectrum is
bounded above by the Legendre envelope generated by the stored pressure bounds. -/
def statement (D : pom_spectrum_intermittency_deficit_data) : Prop :=
  0 ≤ D.dispersion.pom_spectrum_intermittency_deficit_value ∧
    ∀ γ : ℝ, 0 ≤ γ →
      D.f γ ≤ sInf {x : ℝ | ∃ q : ℝ, 2 ≤ q ∧ x = D.tau q - q * γ}

end pom_spectrum_intermittency_deficit_data

/-- Paper label: `cor:pom-spectrum-intermittency-deficit`. The Cauchy--Schwarz moment comparison
gives a ratio at least `1`; monotonicity of `log` gives the nonnegative deficit, while the
existing Legendre wrapper supplies the envelope upper bound. -/
theorem paper_pom_spectrum_intermittency_deficit
    (D : pom_spectrum_intermittency_deficit_data) : D.statement := by
  refine ⟨D.dispersion.pom_spectrum_intermittency_deficit_value_nonneg, ?_⟩
  exact paper_pom_spectrum_legendre_upper D.f D.tau D.legendre_bound

end Omega.POM
