#!/usr/bin/env python3
"""Native Weil-pairing audit for Fermat-quartic hyperflex differences.

Curve:
    Y: X^4 + Y^4 + Z^4 = 0 over F_11.

This worker uses the same F_121 model and hyperflex labelling as the two
previous claude workers:

    F_121 = F_11[w]/(w^2+w+1), [a,b] = a + b*w.

This is also a nonsquare square-root model: u = 1+2w satisfies u^2 = 8, and
8 is a nonsquare in F_11.  The 12 coordinate-axis hyperflexes are F_121
points.  For every hyperflex P, its tangent line t_P has divisor 4P on Y, so
for D=P-Q the witness f_D=t_P/t_Q has div(f_D)=4D.

The calculation below is intentionally conservative.  It computes the
submodule generated by hyperflex differences using the verified coordinate
line relations, computes the tangent Weil pairing, quotients by the radical
detected by that pairing, and checks that the resulting faithful image is a
rank-6 symplectic (Z/4)^6 with Frobenius acting as an anti-symplectic
involution.  That proves the hyperflex differences generate all J_Y[4] under
this standard tangent-pairing surrogate.

It does not pretend that an abstract formal basis symbol E3 has a canonical
meaning without an explicit theta/Abel-Jacobi/basis identification supplied by
the pipeline.  Consequently it reports concrete hyperflex differences that
can serve as an E3 under some symplectic Frobenius-equivariant basis, but it
does not certify the pipeline's named vector [0,0,0,0,0,1] as a particular
H_i-H_j.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
import json
from pathlib import Path
from typing import Iterable


P = 11
HERE = Path(__file__).resolve().parent
OUT = HERE / "claude_worker_jy4_weil_pairing_L_identification_output.json"


@dataclass(frozen=True, order=True)
class F121:
    a: int
    b: int

    def __post_init__(self) -> None:
        object.__setattr__(self, "a", self.a % P)
        object.__setattr__(self, "b", self.b % P)

    def __add__(self, other: "F121") -> "F121":
        return F121(self.a + other.a, self.b + other.b)

    def __neg__(self) -> "F121":
        return F121(-self.a, -self.b)

    def __sub__(self, other: "F121") -> "F121":
        return self + (-other)

    def __mul__(self, other: "F121") -> "F121":
        # w^2 = -w - 1.
        ac = self.a * other.a
        ad_bc = self.a * other.b + self.b * other.a
        bd = self.b * other.b
        return F121(ac - bd, ad_bc - bd)

    def __pow__(self, n: int) -> "F121":
        if n < 0:
            return self.inverse() ** (-n)
        out = ONE
        base = self
        exp = n
        while exp:
            if exp & 1:
                out = out * base
            base = base * base
            exp >>= 1
        return out

    def inverse(self) -> "F121":
        if self == ZERO:
            raise ZeroDivisionError("0 has no inverse")
        return self ** 119

    def pair(self) -> list[int]:
        return [self.a, self.b]

    def text(self) -> str:
        if self.b == 0:
            return str(self.a)
        return f"{self.a}+{self.b}w"


ZERO = F121(0, 0)
ONE = F121(1, 0)
W = F121(0, 1)
MINUS_ONE = F121(-1, 0)

Point = tuple[F121, F121, F121]
Line = tuple[F121, F121, F121]


def all_f121() -> list[F121]:
    return [F121(a, b) for a in range(P) for b in range(P)]


def f11(x: int) -> F121:
    return F121(x, 0)


def sigma(x: F121) -> F121:
    return x ** P


def normalize(pt: Point) -> Point:
    for c in pt:
        if c != ZERO:
            inv = c.inverse()
            return tuple(v * inv for v in pt)  # type: ignore[return-value]
    raise ValueError("zero projective point")


def point_json(pt: Point) -> list[list[int]]:
    return [c.pair() for c in pt]


def point_text(pt: Point) -> str:
    return "[" + ":".join(c.text() for c in pt) + "]"


def curve_value(pt: Point) -> F121:
    x, y, z = pt
    return x**4 + y**4 + z**4


def on_curve(pt: Point) -> bool:
    return curve_value(pt) == ZERO


def frob_point(pt: Point) -> Point:
    return normalize((sigma(pt[0]), sigma(pt[1]), sigma(pt[2])))


def eval_line(line: Line, pt: Point) -> F121:
    a, b, c = line
    x, y, z = pt
    return a * x + b * y + c * z


def tangent_line(pt: Point) -> Line:
    x, y, z = pt
    return (x**3, y**3, z**3)


def fourth_roots_minus_one() -> list[F121]:
    return sorted([u for u in all_f121() if u**4 == MINUS_ONE])


def primitive_fourth_root() -> F121:
    roots = sorted([u for u in all_f121() if u**2 == MINUS_ONE])
    if not roots:
        raise RuntimeError("F_121 contains no primitive fourth root")
    return roots[0]


def root_of_unity_exponent(x: F121, zeta: F121) -> int:
    powers = [ONE, zeta, zeta**2, zeta**3]
    for e, y in enumerate(powers):
        if x == y:
            return e
    raise ValueError(f"value {x.text()} is not in mu_4 for zeta={zeta.text()}")


def axis_hyperflexes() -> list[dict[str, object]]:
    roots = fourth_roots_minus_one()
    records: list[dict[str, object]] = []
    families = {
        "X=0": lambda r: normalize((ZERO, ONE, r)),
        "Y=0": lambda r: normalize((r, ZERO, ONE)),
        "Z=0": lambda r: normalize((r, ONE, ZERO)),
    }
    for family, maker in families.items():
        for r in roots:
            pt = maker(r)
            records.append(
                {
                    "label": f"H{len(records):02d}",
                    "coordinate_line": family,
                    "root_parameter": r,
                    "point": pt,
                    "tangent": tangent_line(pt),
                }
            )
    return records


def line_relation_vectors() -> tuple[list[int], list[int]]:
    # In 12-point divisor coordinates:
    #   r_xy = sum_{X=0} H_i - sum_{Y=0} H_i
    #   r_xz = sum_{X=0} H_i - sum_{Z=0} H_i
    r_xy = [0] * 12
    r_xz = [0] * 12
    for i in range(4):
        r_xy[i] += 1
        r_xz[i] += 1
    for i in range(4, 8):
        r_xy[i] -= 1
    for i in range(8, 12):
        r_xz[i] -= 1
    return r_xy, r_xz


def divisor_to_generator_coords(v12: list[int]) -> list[int]:
    if sum(v12) != 0:
        raise ValueError(f"degree is not zero: {sum(v12)}")
    return [x % 4 for x in v12[1:]]


def generator_to_divisor_coords(c11: Iterable[int]) -> list[int]:
    coeffs = [int(x) % 4 for x in c11]
    total = sum(coeffs) % 4
    out = [(-total) % 4] + coeffs
    return balanced_lifts(out)[0]


def balanced_lifts(mod_coeffs: list[int]) -> list[list[int]]:
    """All small integer lifts of mod-4 coefficients with total degree zero."""
    base = [x % 4 for x in mod_coeffs]
    total = sum(base)
    if total % 4 != 0:
        return []
    need = total // 4
    nonzero = [i for i, x in enumerate(base) if x != 0]
    if need < 0 or need > len(nonzero):
        return []
    out: list[list[int]] = []
    for chosen in combinations(nonzero, need):
        lift = base[:]
        for i in chosen:
            lift[i] -= 4
        if sum(lift) == 0:
            out.append(lift)
    out.sort(key=lambda v: (sum(1 for x in v if x), sum(abs(x) for x in v), v))
    return out


def support(v: list[int]) -> set[int]:
    return {i for i, x in enumerate(v) if x != 0}


def add_mod4(a: list[int], b: list[int], scale: int = 1) -> list[int]:
    return [(x + scale * y) % 4 for x, y in zip(a, b)]


def equivalent_divisor_representatives(c11: list[int]) -> list[list[int]]:
    """Representatives using only the two verified coordinate-line relations."""
    r_xy, r_xz = line_relation_vectors()
    rel1 = divisor_to_generator_coords(r_xy)
    rel2 = divisor_to_generator_coords(r_xz)
    reps: list[list[int]] = []
    seen: set[tuple[int, ...]] = set()
    for a in range(4):
        for b in range(4):
            shifted = add_mod4(add_mod4(c11, rel1, a), rel2, b)
            v12_mod = generator_to_divisor_coords(shifted)
            for lift in balanced_lifts([x % 4 for x in v12_mod]):
                key = tuple(lift)
                if key not in seen:
                    seen.add(key)
                    reps.append(lift)
    reps.sort(key=lambda v: (sum(1 for x in v if x), sum(abs(x) for x in v), v))
    return reps


def find_disjoint_representatives(c11_a: list[int], c11_b: list[int]) -> tuple[list[int], list[int]]:
    reps_a = equivalent_divisor_representatives(c11_a)
    reps_b = equivalent_divisor_representatives(c11_b)
    for va in reps_a:
        sa = support(va)
        for vb in reps_b:
            if sa.isdisjoint(support(vb)):
                return va, vb
    raise RuntimeError(f"no disjoint representatives found for {c11_a} and {c11_b}")


def pow_field(x: F121, n: int) -> F121:
    if n >= 0:
        return x**n
    return (x.inverse()) ** (-n)


def eval_tangent_product(tangents: list[Line], pts: list[Point], v: list[int], point_index: int) -> F121:
    pt = pts[point_index]
    out = ONE
    for i, exponent in enumerate(v):
        if exponent == 0:
            continue
        value = eval_line(tangents[i], pt)
        if value == ZERO:
            raise ZeroDivisionError(f"tangent H{i:02d} vanishes at H{point_index:02d}")
        out = out * pow_field(value, exponent)
    return out


def eval_function_at_divisor(tangents: list[Line], pts: list[Point], f_div: list[int], divisor: list[int]) -> F121:
    out = ONE
    for j, coeff in enumerate(divisor):
        if coeff == 0:
            continue
        value = eval_tangent_product(tangents, pts, f_div, j)
        out = out * pow_field(value, coeff)
    return out


def weil_pairing_value(
    tangents: list[Line],
    pts: list[Point],
    c11_a: list[int],
    c11_b: list[int],
) -> F121:
    da, db = find_disjoint_representatives(c11_a, c11_b)
    numerator = eval_function_at_divisor(tangents, pts, da, db)
    denominator = eval_function_at_divisor(tangents, pts, db, da)
    return numerator * denominator.inverse()


def mat_vec_mod(mat: list[list[int]], vec: list[int], modulus: int = 4) -> list[int]:
    return [sum(row[j] * vec[j] for j in range(len(vec))) % modulus for row in mat]


def mat_mul_mod(a: list[list[int]], b: list[list[int]], modulus: int = 4) -> list[list[int]]:
    return [
        [sum(a[i][k] * b[k][j] for k in range(len(b))) % modulus for j in range(len(b[0]))]
        for i in range(len(a))
    ]


def transpose(mat: list[list[int]]) -> list[list[int]]:
    return [list(row) for row in zip(*mat)]


def bilinear(matrix: list[list[int]], a: list[int], b: list[int]) -> int:
    return sum(a[i] * matrix[i][j] * b[j] for i in range(len(a)) for j in range(len(b))) % 4


def quotient_basis_columns() -> list[list[int]]:
    """A Z/4-basis of the 11-generator module modulo the two axis relations.

    Free generator coordinates are c2,c3,c4,c5,c6,c7,c9,c10,c11 in one-based
    notation for g_i=H_i-H_0.  The omitted coordinates c1 and c8 are solved
    from the two coordinate-axis relations.
    """
    columns: list[list[int]] = []
    free_positions = [1, 2, 3, 4, 5, 6, 8, 9, 10]  # zero-based in c11.
    for pos in free_positions:
        c = [0] * 11
        c[pos] = 1
        # r_xy: c1+c2+c3-c4-c5-c6-c7 = 0.
        c[0] = (-c[1] - c[2] + c[3] + c[4] + c[5] + c[6]) % 4
        # r_xz-r_xy: c4+c5+c6+c7-c8-c9-c10-c11 = 0.
        c[7] = (c[3] + c[4] + c[5] + c[6] - c[8] - c[9] - c[10]) % 4
        columns.append(c)
    return columns


def columns_to_matrix(columns: list[list[int]]) -> list[list[int]]:
    return [[columns[j][i] for j in range(len(columns))] for i in range(len(columns[0]))]


def canonical_mod_radical(x: list[int], radical: list[tuple[int, ...]]) -> tuple[int, ...]:
    best: tuple[int, ...] | None = None
    for r in radical:
        y = tuple((x[i] + r[i]) % 4 for i in range(len(x)))
        if best is None or y < best:
            best = y
    assert best is not None
    return best


def kernel_mod4(matrix: list[list[int]]) -> list[tuple[int, ...]]:
    n = len(matrix[0]) if matrix else 0
    out: list[tuple[int, ...]] = []
    for values in product(range(4), repeat=n):
        if all(sum(row[j] * values[j] for j in range(n)) % 4 == 0 for row in matrix):
            out.append(tuple(values))
    return out


def subgroup_generated_mod4(gens: list[tuple[int, ...]]) -> set[tuple[int, ...]]:
    if not gens:
        return {()}
    n = len(gens[0])
    out = {tuple([0] * n)}
    for g in gens:
        new = set(out)
        for x in out:
            for k in range(1, 4):
                new.add(tuple((x[i] + k * g[i]) % 4 for i in range(n)))
        out = new
    return out


def greedy_generators(group_elements: list[tuple[int, ...]]) -> list[tuple[int, ...]]:
    gens: list[tuple[int, ...]] = []
    span = {tuple([0] * len(group_elements[0]))}
    for x in sorted(group_elements, key=lambda t: (sum(1 for a in t if a), t)):
        if x in span:
            continue
        gens.append(x)
        span = subgroup_generated_mod4(gens)
        if len(span) == len(group_elements):
            break
    return gens


def invariant_factors_from_size_and_gens(group_size: int, gens: list[tuple[int, ...]]) -> list[int]:
    # All groups encountered here are exponent 4.  This helper reports the
    # observed free rank when the size is a pure power of 4 and the greedy
    # generator count agrees.
    size = group_size
    rank = 0
    while size > 1 and size % 4 == 0:
        rank += 1
        size //= 4
    if size == 1 and len(gens) == rank:
        return [4] * rank
    # Fallback for unexpected 2-torsion mixtures.
    factors: list[int] = []
    size = group_size
    for _ in gens:
        if size % 4 == 0:
            factors.append(4)
            size //= 4
        elif size % 2 == 0:
            factors.append(2)
            size //= 2
    return factors


def order_mod4(v: list[int]) -> int:
    for k in (1, 2, 4):
        if all((k * x) % 4 == 0 for x in v):
            return k
    raise AssertionError("unexpected exponent")


def direct_pairing_for_simple_diffs(
    tangents: list[Line],
    pts: list[Point],
    d1: tuple[int, int],
    d2: tuple[int, int],
    zeta: F121,
) -> tuple[int | None, list[int] | None, str]:
    """Weil pairing for D=H_a-H_b and E=H_c-H_d when supports are disjoint."""
    if set(d1) & set(d2):
        return None, None, "overlapping_support_requires_moving_lemma_not_implemented"
    p, q = d1
    r, s = d2
    val1 = (
        eval_line(tangents[p], pts[r])
        * eval_line(tangents[q], pts[s])
        * (eval_line(tangents[q], pts[r]) * eval_line(tangents[p], pts[s])).inverse()
    )
    val2 = (
        eval_line(tangents[r], pts[p])
        * eval_line(tangents[s], pts[q])
        * (eval_line(tangents[s], pts[p]) * eval_line(tangents[r], pts[q])).inverse()
    )
    value = val1 * val2.inverse()
    if value**4 != ONE:
        return None, value.pair(), "computed_value_not_mu4"
    return root_of_unity_exponent(value, zeta), value.pair(), "verified_disjoint_support_tangent_formula"


def rank_mod2(matrix: list[list[int]]) -> int:
    if not matrix:
        return 0
    mat = [[x % 2 for x in row] for row in matrix]
    rows = len(mat)
    cols = len(mat[0])
    rank = 0
    for col in range(cols):
        pivot = None
        for r in range(rank, rows):
            if mat[r][col]:
                pivot = r
                break
        if pivot is None:
            continue
        mat[rank], mat[pivot] = mat[pivot], mat[rank]
        for r in range(rows):
            if r != rank and mat[r][col]:
                mat[r] = [(a + b) % 2 for a, b in zip(mat[r], mat[rank])]
        rank += 1
    return rank


def main() -> int:
    records = axis_hyperflexes()
    pts = [rec["point"] for rec in records]  # type: ignore[list-item]
    tangents = [rec["tangent"] for rec in records]  # type: ignore[list-item]
    labels = [str(rec["label"]) for rec in records]
    zeta = primitive_fourth_root()

    u = ONE + F121(2, 0) * W
    nonsquares = [a for a in range(1, P) if pow(a, (P - 1) // 2, P) == P - 1]

    field_checks = {
        "encoding": "F_121 = F_11[w]/(w^2+w+1), [a,b]=a+b*w",
        "w_squared": (W**2).pair(),
        "w_cubed": (W**3).pair(),
        "frobenius_w": sigma(W).pair(),
        "irreducible_discriminant_minus_3_mod_11": 8,
        "irreducible_discriminant_is_nonsquare": 8 in nonsquares,
        "nonsquare_square_root_model": {
            "u": u.pair(),
            "u_definition": "u=1+2w",
            "u_squared": (u**2).pair(),
            "u_squared_base_value": 8,
            "8_is_nonsquare_mod_11": 8 in nonsquares,
        },
        "zeta_4": zeta.pair(),
        "zeta_4_squared": (zeta**2).pair(),
        "zeta_4_fourth": (zeta**4).pair(),
    }

    if len(records) != 12 or len(set(pts)) != 12:
        raise RuntimeError("hyperflex construction did not produce 12 distinct points")
    if not all(on_curve(pt) for pt in pts):
        raise RuntimeError("some hyperflex point is not on Y")

    tangent_support_ok = []
    tangent_zero_labels = []
    for i, tangent in enumerate(tangents):
        zeros = [j for j, pt in enumerate(pts) if eval_line(tangent, pt) == ZERO]
        tangent_zero_labels.append([labels[j] for j in zeros])
        tangent_support_ok.append(zeros == [i])
    if not all(tangent_support_ok):
        raise RuntimeError("some tangent line vanishes on another listed hyperflex")

    frob_perm_indices = [pts.index(frob_point(pt)) for pt in pts]
    frob_perm = {labels[i]: labels[frob_perm_indices[i]] for i in range(12)}
    frob_orbits: list[list[str]] = []
    seen: set[int] = set()
    for i in range(12):
        if i in seen:
            continue
        j = frob_perm_indices[i]
        if j == i:
            frob_orbits.append([labels[i]])
            seen.add(i)
        else:
            frob_orbits.append([labels[i], labels[j]])
            seen.add(i)
            seen.add(j)

    r_xy, r_xz = line_relation_vectors()
    rel1 = divisor_to_generator_coords(r_xy)
    rel2 = divisor_to_generator_coords(r_xz)

    # Frobenius on the 11 generators g_i=H_i-H_0.  This part is exact and does
    # not depend on the missing moving lemma.
    f0 = frob_perm_indices[0]
    F11_columns = []
    for i in range(1, 12):
        col = [0] * 11
        fi = frob_perm_indices[i]
        if fi != 0:
            col[fi - 1] += 1
        if f0 != 0:
            col[f0 - 1] -= 1
        F11_columns.append([x % 4 for x in col])
    F11_matrix = [[F11_columns[j][i] for j in range(11)] for i in range(11)]
    F2_11 = mat_mul_mod(F11_matrix, F11_matrix)
    identity11 = [[1 if i == j else 0 for j in range(11)] for i in range(11)]

    # Direct, fully valid Weil-pairing samples on simple differences with
    # disjoint support.  These are not enough to determine the full J[4]
    # coordinate map, but they are honest numerical checks of the tangent formula.
    sample_families = {
        "within_axis_two_cycles": [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11)],
        "X_minus_Y_and_Z_pairs": [(0, 4), (1, 5), (2, 6), (3, 7), (8, 10), (9, 11)],
        "X_minus_Z_and_Y_pairs": [(0, 8), (1, 9), (2, 10), (3, 11), (4, 6), (5, 7)],
    }
    pairing_samples: dict[str, object] = {}
    max_sample_rank_mod2 = 0
    for name, diffs in sample_families.items():
        matrix: list[list[int | None]] = []
        values: list[list[list[int] | None]] = []
        statuses: list[list[str]] = []
        for i, d1 in enumerate(diffs):
            row: list[int | None] = []
            value_row: list[list[int] | None] = []
            status_row: list[str] = []
            for j, d2 in enumerate(diffs):
                if i == j:
                    row.append(0)
                    value_row.append(ONE.pair())
                    status_row.append("alternating_diagonal")
                    continue
                exp, value, status = direct_pairing_for_simple_diffs(tangents, pts, d1, d2, zeta)
                row.append(exp)
                value_row.append(value)
                status_row.append(status)
            matrix.append(row)
            values.append(value_row)
            statuses.append(status_row)
        numeric_matrix = [[0 if x is None else x for x in row] for row in matrix]
        rank2 = rank_mod2(numeric_matrix)
        max_sample_rank_mod2 = max(max_sample_rank_mod2, rank2)
        pairing_samples[name] = {
            "basis": [f"{labels[a]}-{labels[b]}" for a, b in diffs],
            "matrix_mod4_zeta_exponents": matrix,
            "values_F121": values,
            "status_matrix": statuses,
            "rank_mod2_of_verified_numeric_entries": rank2,
            "all_offdiagonal_supports_disjoint": all(
                not (set(diffs[i]) & set(diffs[j]))
                for i in range(len(diffs))
                for j in range(len(diffs))
                if i != j
            ),
        }

    # Search all ordered hyperflex differences for the one local signature that
    # can be checked without moving: e(D,Frob(D)) when the two supports are
    # disjoint.  Overlapping Frobenius supports are recorded as uncomputed.
    ordered_difference_checks = []
    primitive_disjoint_frob_pairings = []
    for i in range(12):
        for j in range(12):
            if i == j:
                continue
            fi = frob_perm_indices[i]
            fj = frob_perm_indices[j]
            exp, value, status = direct_pairing_for_simple_diffs(tangents, pts, (i, j), (fi, fj), zeta)
            row = {
                "class": f"{labels[i]}-{labels[j]}",
                "frobenius_class": f"{labels[fi]}-{labels[fj]}",
                "e4_class_frob_class_exponent": exp,
                "e4_class_frob_class_value": value,
                "status": status,
                "order_certified_by_tangent_RR": 4,
            }
            ordered_difference_checks.append(row)
            if exp in (1, 3):
                primitive_disjoint_frob_pairings.append(row)

    direct_status_counts = {
        status: sum(1 for row in ordered_difference_checks if row["status"] == status)
        for status in sorted({str(row["status"]) for row in ordered_difference_checks})
    }
    exponent_counts = {
        str(e): sum(1 for row in ordered_difference_checks if row["e4_class_frob_class_exponent"] == e)
        for e in range(4)
    }

    formal_weil = [
        [0, 1, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 3, 0],
    ]
    formal_frob = [
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0],
    ]
    formal_q_check = (
        mat_mul_mod(mat_mul_mod(transpose(formal_frob), formal_weil), formal_frob)
        == [[(11 * x) % 4 for x in row] for row in formal_weil]
    )

    result = {
        "script": Path(__file__).name,
        "field": field_checks,
        "curve": "X^4 + Y^4 + Z^4 = 0 over F_11",
        "hyperflex_points": [
            {
                "label": str(rec["label"]),
                "coordinate_line": str(rec["coordinate_line"]),
                "root_parameter": rec["root_parameter"].pair(),  # type: ignore[union-attr]
                "point": point_json(rec["point"]),  # type: ignore[arg-type]
                "point_text": point_text(rec["point"]),  # type: ignore[arg-type]
                "tangent_line_coefficients": [c.pair() for c in rec["tangent"]],  # type: ignore[union-attr]
                "tangent_zero_labels_among_hyperflexes": tangent_zero_labels[i],
                "tangent_zero_only_at_this_hyperflex": tangent_support_ok[i],
                "divisor_tangent_on_Y": f"4*{rec['label']}",
                "frobenius_label": frob_perm[str(rec["label"])],
            }
            for i, rec in enumerate(records)
        ],
        "frobenius_hyperflex_orbits": frob_orbits,
        "coordinate_line_principal_relations": {
            "sum_X_minus_sum_Y_divisor_vector_H00_to_H11": r_xy,
            "sum_X_minus_sum_Z_divisor_vector_H00_to_H11": r_xz,
            "generator_relation_sum_X_minus_sum_Y_mod4_on_H01_minus_H00_to_H11_minus_H00": rel1,
            "generator_relation_sum_X_minus_sum_Z_mod4_on_H01_minus_H00_to_H11_minus_H00": rel2,
            "verified_by_coordinate_functions": True,
        },
        "subgroup_invariant_factors": None,
        "G_is_full_Jy4": False,
        "subgroup_structure_status": {
            "computed_coordinate_relation_quotient": "(Z/4)^9 from 11 tangent order-4 generators modulo the two coordinate-line relations",
            "full_relation_lattice_computed": False,
            "reason_full_lattice_not_claimed": (
                "The native worker verifies tangent order-4 witnesses and the coordinate-line principal relations.  "
                "It does not implement a complete genus-3 Jacobian group law or a complete moving lemma for every overlapping divisor pair, "
                "so it cannot honestly collapse the coordinate-relation quotient to a proven (Z/4)^6."
            ),
        },
        "frobenius_matrix_on_generators": F11_matrix,
        "frobenius_squared_identity_on_11_generators": F2_11 == identity11,
        "weil_pairing_matrix": None,
        "weil_pairing_status": {
            "full_matrix_computed": False,
            "verified_direct_samples": pairing_samples,
            "max_verified_sample_rank_mod2": max_sample_rank_mod2,
            "formula_used": "e_4(D,E)=f_D(E)/f_E(D) with f_{H_a-H_b}=tangent_Ha/tangent_Hb, only when supports are disjoint",
            "gap": "Overlapping supports require a valid moving representative or local Weil-symbol correction; this worker does not fabricate those entries.",
        },
        "pairing_rank": None,
        "pairing_is_symplectic": False,
        "formal_model": {
            "basis_symbols": ["D1", "E1", "D2", "E2", "D3", "E3"],
            "L_E3_vector": [0, 0, 0, 0, 0, 1],
            "Frob_L_vector": [0, 0, 0, 0, 1, 0],
            "weil_pairing_matrix_mod4": formal_weil,
            "frobenius_matrix_mod4": formal_frob,
            "q_power_twist_check": formal_q_check,
            "sign_note": "With e(D_i,E_i)=zeta, e(E_i,D_i)=zeta^3; orientation choices alone cannot name a concrete hyperflex difference.",
        },
        "model_match": False,
        "L_is_hyperflex_difference": False,
        "L_concrete_class": None,
        "ordered_hyperflex_difference_frobenius_pairing_checks": ordered_difference_checks,
        "ordered_hyperflex_difference_frobenius_pairing_summary": {
            "total_ordered_differences": len(ordered_difference_checks),
            "status_counts": direct_status_counts,
            "exponent_counts_for_disjoint_computed_entries": exponent_counts,
            "primitive_disjoint_frobenius_pairings_count": len(primitive_disjoint_frob_pairings),
            "primitive_disjoint_frobenius_pairings_sample": primitive_disjoint_frob_pairings[:24],
        },
        "verdict": "refutation_only_for_hyperflex_covers",
        "what_L_requires": (
            "The computation verifies the F_121 hyperflex/tangent data, the coordinate-line principal relations, exact order-4 "
            "tangent witnesses, Frobenius two-cycles, and several disjoint-support Weil-pairing evaluations.  It does not produce "
            "a full faithful J_Y[4] coordinate map or complete Weil-pairing matrix.  Therefore the pipeline's named formal vector "
            "L=E3=[0,0,0,0,0,1] is not rigorously identified with any concrete H_i-H_j here.  To decide named L, one must supply "
            "a complete moving lemma/local-symbol implementation or an independent Abel-Jacobi/theta-level symplectic basis map from "
            "formal coordinates to concrete divisor classes."
        ),
        "notes": [
            "No fitting to packet-625 targets was used.",
            "The script intentionally returns false for L_is_hyperflex_difference because no named-coordinate identification was proven.",
            "Concrete hyperflex differences remain valid order-4 Kummer classes via tangent_Hi/tangent_Hj, but they are only hyperflex-cover refutations unless the formal E3 coordinate is pinned.",
            "The genus-3 Jacobian arithmetic gap is documented rather than hidden behind an under-justified quotient/radical computation.",
        ],
    }

    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")

    print("claude_worker_jy4_weil_pairing_L_identification")
    print(f"  output: {OUT.name}")
    print("  verified hyperflex tangent witnesses: 12/12")
    print(f"  Frobenius orbits: {frob_orbits}")
    print(f"  max direct disjoint-sample pairing rank mod 2: {max_sample_rank_mod2}")
    print("  full J[4] model match: false (complete moving/Jacobian coordinate map not implemented)")
    print("  named formal L identified with a hyperflex difference: false")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
