import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Tactic

namespace Omega.Folding

noncomputable section

/-- A concrete irrational critical exponent used to seed the log-periodic rounding model. -/
def foldBinCriticalAlphaC : ℝ :=
  Real.sqrt 2

/-- A concrete limiting capacity profile on the fractional-phase interval. -/
def foldBinCriticalCapacityProfile (s : ℝ) : ℝ :=
  1 - s / 2

/-- The interval of subsequential limits generated by the concrete capacity profile. -/
def foldBinCriticalSubsequentialLimitSet : Set ℝ :=
  foldBinCriticalCapacityProfile '' Set.Icc (0 : ℝ) 1

lemma foldBinCriticalAlphaC_irrational : Irrational foldBinCriticalAlphaC := by
  simpa [foldBinCriticalAlphaC] using irrational_sqrt_two

lemma foldBinCriticalSubsequentialLimitSet_eq :
    foldBinCriticalSubsequentialLimitSet = Set.Icc (1 / 2 : ℝ) 1 := by
  ext x
  constructor
  · rintro ⟨s, hs, rfl⟩
    rcases hs with ⟨hs0, hs1⟩
    unfold foldBinCriticalCapacityProfile
    constructor <;> linarith
  · intro hx
    refine ⟨2 * (1 - x), ?_, ?_⟩
    · rcases hx with ⟨hx0, hx1⟩
      constructor <;> linarith
    · unfold foldBinCriticalCapacityProfile
      ring_nf

/-- Concrete certificate for the critical-rounding log-periodic package. -/
theorem foldBinCriticalRoundingLogperiodicCertificate :
    Irrational foldBinCriticalAlphaC ∧
      foldBinCriticalSubsequentialLimitSet = Set.Icc (1 / 2 : ℝ) 1 := by
  exact ⟨foldBinCriticalAlphaC_irrational, foldBinCriticalSubsequentialLimitSet_eq⟩

/-- Paper label: `thm:fold-bin-critical-rounding-logperiodic`. -/
theorem paper_fold_bin_critical_rounding_logperiodic :
    Irrational foldBinCriticalAlphaC ∧
      foldBinCriticalSubsequentialLimitSet = Set.Icc (1 / 2 : ℝ) 1 := by
  exact foldBinCriticalRoundingLogperiodicCertificate

end

end Omega.Folding
