import Mathlib.Data.Finset.Prod
import Mathlib.Tactic
import Omega.Folding.FoldGaugeAnomalyP10HChebotarevProductLaw
import Omega.Folding.FoldGaugeAnomalyP10HLinearDisjointness

namespace Omega.Folding

/-- The audited biquadratic abelianization generated by the two quadratic subfields. -/
def fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_biquadratic_abelianization
    : Finset (ℤ × ℤ) :=
  ({0, foldGaugeAnomalyP10QuadraticSubfield} : Finset ℤ).product
    ({0, foldGaugeAnomalyHQuadraticSubfield} : Finset ℤ)

/-- The single Frobenius-signature class in the audited biquadratic abelianization. -/
def fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class :
    Finset (ℤ × ℤ) :=
  {(foldGaugeAnomalyP10QuadraticSubfield, foldGaugeAnomalyHQuadraticSubfield)}

lemma fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_abelianization_card :
    (fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_biquadratic_abelianization).card =
      4 := by
  unfold fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_biquadratic_abelianization
  norm_num [Finset.card_product, foldGaugeAnomalyP10QuadraticSubfield,
    foldGaugeAnomalyHQuadraticSubfield]

lemma fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class_card :
    fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class.card = 1 := by
  unfold fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class
  simp

/-- Paper label: `cor:fold-gauge-anomaly-P10-H-max-abelian-and-quadratic-equidistribution`.
The existing `P10/H` direct-product package gives the biquadratic abelianization with four
quadratic-signature classes, so a single class has density `1/4`. -/
def paper_fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution : Prop :=
  foldGaugeAnomalyP10HDirectProductGalois ∧
    ((((fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class).card :
          ℚ) /
        ((fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_biquadratic_abelianization).card :
          ℚ)) =
      (1 / 4 : ℚ))

theorem fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_holds :
    paper_fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution := by
  rcases paper_fold_gauge_anomaly_P10_H_linear_disjointness with ⟨_, _, _, hdirect, _⟩
  refine ⟨hdirect, ?_⟩
  rw [fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_target_class_card,
    fold_gauge_anomaly_p10_h_max_abelian_and_quadratic_equidistribution_abelianization_card]
  norm_num

end Omega.Folding
