import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic
import Omega.Folding.ResonanceDiscSquareclassIndependenceQ12Q17

namespace Omega.Folding

open scoped BigOperators

/-- The six audited discriminant characters, represented by the standard `F₂` basis. -/
def killo_fold_resonance_disc_characters_q12_17_character
    (i : Fin 6) : Fin 6 → ZMod 2 :=
  Pi.single i 1

/-- A putative dependence expressing the `i`th character through the other five. -/
def killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five
    (i : Fin 6) : Prop :=
  ∃ coeff : Fin 6 → ZMod 2,
    coeff i = 0 ∧
      (∑ j : Fin 6,
          Pi.single j (coeff j : ZMod 2)) =
        killo_fold_resonance_disc_characters_q12_17_character i

/-- The quadratic-field containment obstruction is the same `F₂` span obstruction. -/
def killo_fold_resonance_disc_characters_q12_17_quadratic_field_containment
    (i : Fin 6) : Prop :=
  killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five i

lemma killo_fold_resonance_disc_characters_q12_17_coordinate_sum
    (coeff : Fin 6 → ZMod 2) (i : Fin 6) :
    (∑ j : Fin 6,
        Pi.single j (coeff j : ZMod 2)) i =
      coeff i := by
  simp

lemma killo_fold_resonance_disc_characters_q12_17_not_in_span_of_other_five
    (i : Fin 6) :
    ¬ killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five i := by
  rintro ⟨coeff, hcoeff, hsum⟩
  have hcoord := congrFun hsum i
  rw [killo_fold_resonance_disc_characters_q12_17_coordinate_sum coeff i] at hcoord
  simp [killo_fold_resonance_disc_characters_q12_17_character, hcoeff] at hcoord

/-- Paper-facing character package: no discriminant character is generated by the other five, and
the corresponding quadratic field is not contained in the compositum of the other five. -/
def killo_fold_resonance_disc_characters_q12_17_statement : Prop :=
  (∀ i : Fin 6,
    ¬ killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five i) ∧
  ∀ i : Fin 6,
    ¬ killo_fold_resonance_disc_characters_q12_17_quadratic_field_containment i

/-- Paper label: `cor:killo-fold-resonance-disc-characters-q12-17`. -/
theorem paper_killo_fold_resonance_disc_characters_q12_17 :
    killo_fold_resonance_disc_characters_q12_17_statement := by
  have hNoSpan : ∀ i : Fin 6,
      ¬ killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five i :=
    paper_killo_fold_resonance_disc_squareclass_independence_q12_17
      True
      (∀ i : Fin 6,
        ¬ killo_fold_resonance_disc_characters_q12_17_in_span_of_other_five i)
      trivial
      (fun _ => killo_fold_resonance_disc_characters_q12_17_not_in_span_of_other_five)
  exact ⟨hNoSpan, by
    simpa [killo_fold_resonance_disc_characters_q12_17_quadratic_field_containment] using
      hNoSpan⟩

end Omega.Folding
