import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.Nat.Fib.Basic
import Mathlib.Tactic
import Omega.Folding.FoldCongruenceModSemirings
import Omega.Folding.ModSemiringsKernelImageGcd

namespace Omega

/-- The modulus identified with the fold quotient in degree `m`. -/
def foldModSemiringModulus (m : ℕ) : ℕ :=
  Nat.fib (m + 2)

/-- The `gcd` controlling the annihilator of multiplication by the residue class `a`. -/
def foldAnnihilatorKernel (m a : ℕ) : ℕ :=
  Nat.gcd a (foldModSemiringModulus m)

/-- The principal generator of the annihilator ideal in `ℤ/(F_{m+2})`. -/
def foldAnnihilatorGenerator (m a : ℕ) : ℕ :=
  foldModSemiringModulus m / foldAnnihilatorKernel m a

/-- The truncated valuation vector is encoded by the factorization of the annihilator kernel. -/
def foldAnnihilatorValuation (m a p : ℕ) : ℕ :=
  (foldAnnihilatorKernel m a).factorization p

/-- Inclusion in the annihilator lattice transported to the `gcd` side. -/
def foldAnnihilatorIncluded (m a b : ℕ) : Prop :=
  foldAnnihilatorKernel m a ∣ foldAnnihilatorKernel m b

/-- In the fold semiring modulo `F_{m+2}`, annihilators are generated by the complementary quotient
`F_{m+2} / gcd(a, F_{m+2})`, and inclusion of annihilators is equivalent to the product order on
the prime valuations of the corresponding `gcd` kernels.
    thm:fold-mod-semirings-annihilator-valuation-lattice -/
theorem paper_fold_mod_semirings_annihilator_valuation_lattice (m a b : ℕ) :
    foldAnnihilatorGenerator m a = foldModSemiringModulus m / Nat.gcd a (foldModSemiringModulus m) ∧
      (foldAnnihilatorIncluded m a b ↔
        ∀ p : ℕ, foldAnnihilatorValuation m a p ≤ foldAnnihilatorValuation m b p) := by
  refine ⟨rfl, ?_⟩
  have hmod_pos : 0 < foldModSemiringModulus m := by
    simp [foldModSemiringModulus]
  have hga0 : Nat.gcd a (foldModSemiringModulus m) ≠ 0 := by
    exact (Nat.gcd_pos_of_pos_right a hmod_pos).ne'
  have hgb0 : Nat.gcd b (foldModSemiringModulus m) ≠ 0 := by
    exact (Nat.gcd_pos_of_pos_right b hmod_pos).ne'
  rw [show foldAnnihilatorIncluded m a b ↔
      Nat.gcd a (foldModSemiringModulus m) ∣ Nat.gcd b (foldModSemiringModulus m) by rfl]
  rw [← Nat.factorization_le_iff_dvd hga0 hgb0]
  simp [foldAnnihilatorValuation, foldAnnihilatorKernel, Finsupp.le_def]

end Omega
