import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Omega.SyncKernelWeighted.PressureAnalyticRadiusDiscriminantFormula
import Omega.SyncKernelWeighted.PressureUnitCircleBranchAngles

namespace Omega.SyncKernelWeighted

noncomputable section

/-- The audited unit-circle obstruction obtained by restricting the completed branch polynomial
along `s = 2 cos (θ / 2)`. -/
def delta_branchpoints_discriminant_lock_unit_circle_obstruction
    (D : PressureUnitCircleBranchAnglesData) (θ : ℝ) : Prop :=
  D.branchPolynomial (2 * Real.cos (θ / 2)) = 0

/-- Paper-facing discriminant lock: the branch obstruction is exactly the discriminant-zero
criterion, and on the unit-circle slice the audited obstruction set is even and generated by the
three certified branch angles. -/
def delta_branchpoints_discriminant_lock_statement : Prop :=
  pressureBranchpointCriterion ∧
    ∀ D : PressureUnitCircleBranchAnglesData,
      (∀ θ : ℝ,
          delta_branchpoints_discriminant_lock_unit_circle_obstruction D θ ↔
            delta_branchpoints_discriminant_lock_unit_circle_obstruction D (-θ)) ∧
        0 < D.t1 ∧
          D.t1 < D.t2 ∧
            D.t2 < D.t3 ∧
              D.t3 ≤ Real.pi ∧
                delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t1) ∧
                  delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t2) ∧
                    delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t3) ∧
                      ∀ t : ℝ,
                        0 < t →
                          t ≤ Real.pi →
                            delta_branchpoints_discriminant_lock_unit_circle_obstruction
                                D (2 * t) →
                              t = D.t1 ∨ t = D.t2 ∨ t = D.t3

/-- Paper label: `prop:delta-branchpoints-discriminant-lock`. -/
theorem paper_delta_branchpoints_discriminant_lock :
    delta_branchpoints_discriminant_lock_statement := by
  refine ⟨paper_sync_kernel_analytic_radius_discriminant_formula.1, ?_⟩
  intro D
  rcases paper_pressure_unit_circle_branch_angles D with
    ⟨ht1_pos, ht12, ht23, ht3_le, hbranch1, hbranch2, hbranch3, hclassify⟩
  have hobs1 :
      delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t1) := by
    simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
      show (2 * D.t1) / 2 = D.t1 by ring] using hbranch1
  have hobs2 :
      delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t2) := by
    simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
      show (2 * D.t2) / 2 = D.t2 by ring] using hbranch2
  have hobs3 :
      delta_branchpoints_discriminant_lock_unit_circle_obstruction D (2 * D.t3) := by
    simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
      show (2 * D.t3) / 2 = D.t3 by ring] using hbranch3
  refine ⟨?_, ht1_pos, ht12, ht23, ht3_le, hobs1, hobs2, hobs3, ?_⟩
  · intro θ
    constructor <;> intro h
    · simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
        show (-θ) / 2 = -(θ / 2) by ring, Real.cos_neg] using h
    · simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
        show (-θ) / 2 = -(θ / 2) by ring, Real.cos_neg] using h
  · intro t ht0 htpi ht
    exact hclassify t ht0 htpi (by
      simpa [delta_branchpoints_discriminant_lock_unit_circle_obstruction,
        show (2 * t) / 2 = t by ring] using ht)

end

end Omega.SyncKernelWeighted
