import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Tactic
import Omega.SyncKernelWeighted.RealInput40ChiReparam4d

namespace Omega.SyncKernelWeighted

noncomputable section

/-- A concrete scalar interface depending only on the three reparameterized combinations
`a = θₑ + θχ`, `b = θ₋`, and `c = θ₂ - θχ`. -/
def chi_gauge_ward_nullmode_scalar (thetaE thetaMinus theta2 thetaChi : ℝ) : ℝ :=
  (thetaE + thetaChi) + thetaMinus + (theta2 - thetaChi)

/-- The same scalar interface written directly in the reduced `(a, b, c)` variables. -/
def chi_gauge_ward_nullmode_reduced_scalar (a b c : ℝ) : ℝ :=
  a + b + c

/-- The affine line generated by the gauge null vector `v₀ = (1, 0, -1, -1)`. -/
def chi_gauge_ward_nullmode_null_path
    (thetaE thetaMinus theta2 thetaChi t : ℝ) : ℝ :=
  chi_gauge_ward_nullmode_scalar (thetaE + t) thetaMinus (theta2 - t) (thetaChi - t)

/-- Paper-facing package for the χ-gauge Ward identity and the null mode. -/
def chi_gauge_ward_nullmode_statement : Prop :=
  (∀ thetaE thetaChi thetaMinus theta2 : RealInput40Matrix, ∀ phiE phiMinus phi2 : ℝ,
      realInput40MatrixReparametrized thetaE thetaChi thetaMinus theta2 phiE phiMinus phi2 ∧
        realInput40SpectralRadiusReparametrized thetaE thetaChi thetaMinus theta2 phiE phiMinus
          phi2 ∧
        realInput40ZetaReparametrized thetaE thetaChi thetaMinus theta2 phiE phiMinus phi2 ∧
        realInput40LogMReparametrized thetaE thetaChi thetaMinus theta2 phiE phiMinus phi2) ∧
    (∀ thetaE thetaMinus theta2 thetaChi : ℝ,
      let a := thetaE + thetaChi
      let b := thetaMinus
      let c := theta2 - thetaChi
      chi_gauge_ward_nullmode_scalar thetaE thetaMinus theta2 thetaChi =
          chi_gauge_ward_nullmode_reduced_scalar a b c ∧
        deriv (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus theta2 x) thetaChi =
          deriv (fun x => chi_gauge_ward_nullmode_scalar x thetaMinus theta2 thetaChi) thetaE -
            deriv (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus x thetaChi) theta2 ∧
        deriv (fun t => chi_gauge_ward_nullmode_null_path thetaE thetaMinus theta2 thetaChi t) 0 =
          0 ∧
        deriv
            (fun t => deriv (fun s =>
              chi_gauge_ward_nullmode_null_path thetaE thetaMinus theta2 thetaChi s) t)
            0 =
          0)

/-- Paper label: `cor:chi-gauge-ward-nullmode`. -/
theorem paper_chi_gauge_ward_nullmode : chi_gauge_ward_nullmode_statement := by
  refine ⟨?_, ?_⟩
  · intro thetaE thetaChi thetaMinus theta2 phiE phiMinus phi2
    exact paper_real_input_40_chi_reparam_4d thetaE thetaChi thetaMinus theta2 phiE phiMinus
      phi2
  · intro thetaE thetaMinus theta2 thetaChi
    dsimp
    have hchi :
        deriv (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus theta2 x) thetaChi = 0 := by
      have hfun :
          (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus theta2 x) =
            fun _ : ℝ => thetaE + thetaMinus + theta2 := by
        funext x
        simp [chi_gauge_ward_nullmode_scalar]
        ring
      rw [hfun]
      simp
    have hthetaE :
        deriv (fun x => chi_gauge_ward_nullmode_scalar x thetaMinus theta2 thetaChi) thetaE = 1 := by
      have hfun :
          (fun x => chi_gauge_ward_nullmode_scalar x thetaMinus theta2 thetaChi) =
            fun x : ℝ => x + (thetaMinus + theta2) := by
        funext x
        simp [chi_gauge_ward_nullmode_scalar]
        ring
      rw [hfun]
      simp
    have htheta2 :
        deriv (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus x thetaChi) theta2 = 1 := by
      have hfun :
          (fun x => chi_gauge_ward_nullmode_scalar thetaE thetaMinus x thetaChi) =
            fun x : ℝ => x + (thetaE + thetaMinus) := by
        funext x
        simp [chi_gauge_ward_nullmode_scalar]
        ring
      rw [hfun]
      simp
    have hpath :
        (fun t => chi_gauge_ward_nullmode_null_path thetaE thetaMinus theta2 thetaChi t) =
          fun _ : ℝ => thetaE + thetaMinus + theta2 := by
      funext t
      simp [chi_gauge_ward_nullmode_null_path, chi_gauge_ward_nullmode_scalar]
      ring
    have hpath_deriv :
        (fun t => deriv (fun s =>
          chi_gauge_ward_nullmode_null_path thetaE thetaMinus theta2 thetaChi s) t) =
          fun _ : ℝ => 0 := by
      funext t
      rw [hpath]
      simp
    refine ⟨?_, ?_, ?_, ?_⟩
    · simp [chi_gauge_ward_nullmode_scalar, chi_gauge_ward_nullmode_reduced_scalar]
    · linarith
    · rw [hpath]
      simp
    · rw [hpath_deriv]
      simp

end

end Omega.SyncKernelWeighted
