import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Real
import Mathlib.Tactic
import Omega.SyncKernelWeighted.RealInput40LogMTruncBound

namespace Omega.SyncKernelWeighted

noncomputable section

/-- Concrete finite-sample audit data for the real-input-40 logarithmic Mertens stability
functional. The sampled drift is the finite Möbius--Abel perturbation generated by the recorded
sample errors, while the pointwise envelope is the truncation-tail majorant from the appendix. -/
structure RealInput40LogMStabilityFunctionalData where
  A : ℝ
  lam : ℝ
  K : ℕ
  sampleCount : ℕ
  sampleError : ℕ → ℝ
  hA : 0 ≤ A
  hlam : 1 < lam
  sampleBound :
    ∀ n, n < sampleCount → |sampleError n| ≤ realInput40LogMTruncTerm A lam K n

namespace RealInput40LogMStabilityFunctionalData

/-- The audited drift obtained by aggregating the finitely many sampled errors. -/
def sampledDrift (D : RealInput40LogMStabilityFunctionalData) : ℝ :=
  Finset.sum (Finset.range D.sampleCount) D.sampleError

/-- The finite sampled drift is controlled by the closed truncation bound from the appendix. -/
def Holds (D : RealInput40LogMStabilityFunctionalData) : Prop :=
  |D.sampledDrift| ≤ realInput40LogMTruncClosedBound D.A D.lam D.K

end RealInput40LogMStabilityFunctionalData

/-- Paper label: `prop:real-input-40-logM-stability-functional`.
Finite sampled perturbations of the Möbius--Abel logarithmic functional are bounded by the same
closed truncation majorant as the geometric tail from the appendix. -/
theorem paper_real_input_40_logM_stability_functional
    (D : RealInput40LogMStabilityFunctionalData) : D.Holds := by
  have htrunc := paper_real_input_40_logM_trunc_bound D.A D.lam D.K D.hA D.hlam
  have hlam0 : 0 < D.lam := lt_trans zero_lt_one D.hlam
  have hr0 : 0 ≤ D.lam⁻¹ := inv_nonneg.mpr hlam0.le
  have hr1 : D.lam⁻¹ < 1 := by
    simpa using inv_lt_one_of_one_lt₀ D.hlam
  have hterm_nonneg : ∀ n, 0 ≤ realInput40LogMTruncTerm D.A D.lam D.K n := by
    intro n
    exact div_nonneg (mul_nonneg D.hA (pow_nonneg hr0 _)) (by positivity)
  have hmajorant_summable :
      Summable (fun n ↦ realInput40LogMTruncMajorant D.A D.lam D.K n) := by
    have hgeom : Summable (fun n : ℕ ↦ (D.lam⁻¹) ^ n) := summable_geometric_of_lt_one hr0 hr1
    convert hgeom.mul_left (D.A / (D.K + 1) * (D.lam⁻¹) ^ (D.K + 1)) using 1
    ext n
    rw [realInput40LogMTruncMajorant, pow_add]
    ring
  have hterm_summable :
      Summable (fun n ↦ realInput40LogMTruncTerm D.A D.lam D.K n) :=
    Summable.of_nonneg_of_le hterm_nonneg htrunc.1 hmajorant_summable
  have hfinite_bound :
      |D.sampledDrift| ≤
        Finset.sum (Finset.range D.sampleCount) (fun n =>
          realInput40LogMTruncTerm D.A D.lam D.K n) := by
    rw [RealInput40LogMStabilityFunctionalData.sampledDrift]
    calc
      |Finset.sum (Finset.range D.sampleCount) D.sampleError|
        ≤ Finset.sum (Finset.range D.sampleCount) (fun n => |D.sampleError n|) := by
            exact Finset.abs_sum_le_sum_abs _ _
      _ ≤ Finset.sum (Finset.range D.sampleCount) (fun n =>
            realInput40LogMTruncTerm D.A D.lam D.K n) := by
            refine Finset.sum_le_sum ?_
            intro n hn
            exact D.sampleBound n (Finset.mem_range.mp hn)
  have hpartial_le :
      Finset.sum (Finset.range D.sampleCount) (fun n =>
        realInput40LogMTruncTerm D.A D.lam D.K n) ≤
        ∑' n, realInput40LogMTruncTerm D.A D.lam D.K n := by
    exact hterm_summable.sum_le_tsum (Finset.range D.sampleCount) (fun n _ ↦ hterm_nonneg n)
  calc
    |D.sampledDrift|
      ≤ Finset.sum (Finset.range D.sampleCount) (fun n =>
          realInput40LogMTruncTerm D.A D.lam D.K n) := hfinite_bound
    _ ≤ ∑' n, realInput40LogMTruncTerm D.A D.lam D.K n := hpartial_le
    _ ≤ realInput40LogMTruncGeomBound D.A D.lam D.K := htrunc.2.1
    _ = realInput40LogMTruncClosedBound D.A D.lam D.K := htrunc.2.2

end

end Omega.SyncKernelWeighted
