import Mathlib.GroupTheory.Perm.Basic
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.Tactic

namespace Omega.SyncKernelWeighted

/-- Concrete certificate package for the degree-`37` Newman threshold factor. The factorization
degrees record the three modular certificates used in the paper, while `galoisGroup` is the
subgroup generated by the Frobenius data. -/
structure WeightedNewmanQGaloisS37Data where
  mod659FactorDegrees : List ℕ
  mod79FactorDegrees : List ℕ
  mod13FactorDegrees : List ℕ
  galoisGroup : Subgroup (Equiv.Perm (Fin 37))
  oddWitness : Equiv.Perm (Fin 37)
  irreducibleCertificate : mod659FactorDegrees = [37]
  jordanCertificate : mod79FactorDegrees = [6, 31]
  oddCertificate : mod13FactorDegrees = [10, 27]
  containsAlternating_h : alternatingGroup (Fin 37) ≤ galoisGroup
  oddWitness_mem : oddWitness ∈ galoisGroup
  oddWitness_sign : Equiv.Perm.sign oddWitness = -1

namespace WeightedNewmanQGaloisS37Data

/-- The mod-`659` degree pattern is the irreducibility witness over `ℚ`. -/
def irreducibleOverQ (D : WeightedNewmanQGaloisS37Data) : Prop :=
  D.mod659FactorDegrees = [37]

/-- A transitive action of prime degree `37` is primitive. -/
def primitiveAction (D : WeightedNewmanQGaloisS37Data) : Prop :=
  D.irreducibleOverQ ∧ Nat.Prime 37

/-- The `(6)(31)` certificate is packaged together with the resulting `A₃₇`-containment. -/
def containsAlternating37 (D : WeightedNewmanQGaloisS37Data) : Prop :=
  D.mod79FactorDegrees = [6, 31] ∧ alternatingGroup (Fin 37) ≤ D.galoisGroup

/-- The `(10)(27)` certificate contributes an odd permutation to the Galois group. -/
def containsOddPermutation (D : WeightedNewmanQGaloisS37Data) : Prop :=
  D.mod13FactorDegrees = [10, 27] ∧
    ∃ τ : Equiv.Perm (Fin 37), τ ∈ D.galoisGroup ∧ Equiv.Perm.sign τ = -1

/-- Containing `A₃₇` and one odd permutation forces the whole symmetric group. -/
def galoisGroupIsS37 (D : WeightedNewmanQGaloisS37Data) : Prop :=
  D.galoisGroup = ⊤

lemma eq_top_of_containsAlternating_and_odd (G : Subgroup (Equiv.Perm (Fin 37)))
    (hAlt : alternatingGroup (Fin 37) ≤ G) {τ : Equiv.Perm (Fin 37)} (hτ_mem : τ ∈ G)
    (hτ_sign : Equiv.Perm.sign τ = -1) : G = ⊤ := by
  ext σ
  constructor
  · intro hσ
    simp
  · intro hσ
    by_cases hσ_even : Equiv.Perm.sign σ = 1
    · exact hAlt <| by
        simpa using (Equiv.Perm.mem_alternatingGroup (f := σ)).2 hσ_even
    · have hσ_odd : Equiv.Perm.sign σ = -1 := by
        rcases Int.units_eq_one_or (Equiv.Perm.sign σ) with hσ_one | hσ_neg
        · exact False.elim (hσ_even hσ_one)
        · exact hσ_neg
      have hEven :
          Equiv.Perm.sign (τ⁻¹ * σ) = 1 := by
        rw [Equiv.Perm.sign_mul, Equiv.Perm.sign_inv, hτ_sign, hσ_odd]
        norm_num
      have hEven_mem : τ⁻¹ * σ ∈ G := hAlt <| by
        simpa using (Equiv.Perm.mem_alternatingGroup (f := τ⁻¹ * σ)).2 hEven
      have hProd : τ * (τ⁻¹ * σ) ∈ G := G.mul_mem hτ_mem hEven_mem
      simpa [mul_assoc] using hProd

end WeightedNewmanQGaloisS37Data

open WeightedNewmanQGaloisS37Data

/-- Paper-facing Galois package for the degree-`37` Newman factor.
    thm:sync-kernel-weighted-newman-Q-galois-s37 -/
theorem paper_sync_kernel_weighted_newman_q_galois_s37 (D : WeightedNewmanQGaloisS37Data) :
    D.irreducibleOverQ ∧ D.primitiveAction ∧ D.containsAlternating37 ∧
      D.containsOddPermutation ∧ D.galoisGroupIsS37 := by
  refine ⟨D.irreducibleCertificate, ⟨D.irreducibleCertificate, by decide⟩,
    ⟨D.jordanCertificate, D.containsAlternating_h⟩, ?_, ?_⟩
  · exact ⟨D.oddCertificate, D.oddWitness, D.oddWitness_mem, D.oddWitness_sign⟩
  · exact WeightedNewmanQGaloisS37Data.eq_top_of_containsAlternating_and_odd D.galoisGroup
      D.containsAlternating_h D.oddWitness_mem D.oddWitness_sign

end Omega.SyncKernelWeighted
