import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Tactic
import Omega.GroupUnification.GroupJGEllipsePrimeHomomorphism

namespace Omega.GroupUnification

/-- Equality of the `t`-phase coordinate means that the same logarithmic norm difference lands in
the period lattice generated by `t`. -/
def groupJGTwoFrequencyCircleCoordinate (t : ℝ) (r s : PrimeRegisterObject) : Prop :=
  ∃ m : ℤ, Real.log (groupJGEllipseAxis r) - Real.log (groupJGEllipseAxis s) = m * t

/-- Simultaneous equality of the two phase coordinates. -/
def groupJGTwoFrequencyCircleReadoutEq (t₁ t₂ : ℝ) (r s : PrimeRegisterObject) : Prop :=
  groupJGTwoFrequencyCircleCoordinate t₁ r s ∧
    groupJGTwoFrequencyCircleCoordinate t₂ r s

lemma groupJG_twoFrequency_log_difference_eq_zero {t₁ t₂ x : ℝ}
    (_ht₁ : 0 < t₁) (ht₂ : 0 < t₂) (hirr : Irrational (t₁ / t₂))
    (h₁ : ∃ m : ℤ, x = m * t₁) (h₂ : ∃ n : ℤ, x = n * t₂) :
    x = 0 := by
  rcases h₁ with ⟨m, hm⟩
  rcases h₂ with ⟨n, hn⟩
  by_contra hx
  have hm0 : m ≠ 0 := by
    intro hm0
    apply hx
    rw [hm, hm0]
    simp
  have hn0 : n ≠ 0 := by
    intro hn0
    apply hx
    rw [hn, hn0]
    simp
  have ht₂0 : t₂ ≠ 0 := ht₂.ne'
  have hm_real : (m : ℝ) ≠ 0 := by
    exact_mod_cast hm0
  have hcross : (m : ℝ) * t₁ = (n : ℝ) * t₂ := by
    linarith [hm, hn]
  have hratio : t₁ / t₂ = (n : ℝ) / (m : ℝ) := by
    field_simp [ht₂0, hm_real]
    nlinarith [hcross]
  exact (irrational_iff_ne_rational _).mp hirr n m hm0 <| by
    simpa using hratio

/-- If two phase readouts coincide at incommensurable periods, then the underlying prime-register
norms agree and hence the original prime registers agree.
    thm:group-jg-twofrequency-circle-readout-injective -/
theorem paper_group_jg_twofrequency_circle_readout_injective
    {t₁ t₂ : ℝ} (ht₁ : 0 < t₁) (ht₂ : 0 < t₂) (hirr : Irrational (t₁ / t₂))
    {r s : PrimeRegisterObject} (hreadout : groupJGTwoFrequencyCircleReadoutEq t₁ t₂ r s) :
    r = s := by
  have hzero :
      Real.log (groupJGEllipseAxis r) - Real.log (groupJGEllipseAxis s) = 0 :=
    groupJG_twoFrequency_log_difference_eq_zero ht₁ ht₂ hirr hreadout.1 hreadout.2
  have hrpos : 0 < groupJGEllipseAxis r := by
    change (0 : ℝ) < (groupJGPrimeNorm r : ℝ)
    exact_mod_cast (groupJGPrimeNorm_pos r)
  have hspos : 0 < groupJGEllipseAxis s := by
    change (0 : ℝ) < (groupJGPrimeNorm s : ℝ)
    exact_mod_cast (groupJGPrimeNorm_pos s)
  have hlog : Real.log (groupJGEllipseAxis r) = Real.log (groupJGEllipseAxis s) := by
    linarith
  have haxis : groupJGEllipseAxis r = groupJGEllipseAxis s := by
    have hexp := congrArg Real.exp hlog
    simpa [Real.exp_log hrpos, Real.exp_log hspos] using hexp
  have hnorm : groupJGPrimeNorm r = groupJGPrimeNorm s := by
    have haxis' : (groupJGPrimeNorm r : ℝ) = (groupJGPrimeNorm s : ℝ) := by
      simpa [groupJGEllipseAxis] using haxis
    exact Nat.cast_injective (R := ℝ) haxis'
  exact (groupJGPrimeNorm_injective hnorm)

end Omega.GroupUnification
