import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.NumberTheory.Real.GoldenRatio
import Mathlib.Tactic

open Filter
open scoped Topology goldenRatio

namespace Omega.Conclusion

noncomputable section

/-- The golden inverse constant used by the second harmonic grid. -/
def conclusion_binfold_harmonic_staircase_kinks_phi_inv : ℝ :=
  (Real.goldenRatio)⁻¹

/-- Harmonic grid generated by the jump points `c / n`, `n ≥ 1`. -/
def conclusion_binfold_harmonic_staircase_kinks_harmonic_grid (c : ℝ) : Set ℝ :=
  {x | ∃ n : ℕ, 0 < n ∧ x = c / n}

/-- The two-grid kink set appearing in the bin-fold audit staircase. -/
def conclusion_binfold_harmonic_staircase_kinks_kink_set : Set ℝ :=
  conclusion_binfold_harmonic_staircase_kinks_harmonic_grid 1 ∪
    conclusion_binfold_harmonic_staircase_kinks_harmonic_grid
      conclusion_binfold_harmonic_staircase_kinks_phi_inv

/-- The same set recorded from the two admissible constants `1` and `φ⁻¹`. -/
def conclusion_binfold_harmonic_staircase_kinks_jump_set : Set ℝ :=
  {x | ∃ c : ℝ,
    c ∈ ({1, conclusion_binfold_harmonic_staircase_kinks_phi_inv} : Set ℝ) ∧
      ∃ n : ℕ, 0 < n ∧ x = c / n}

/-- Reciprocal sequence for a harmonic grid. -/
def conclusion_binfold_harmonic_staircase_kinks_reciprocal_sequence (c : ℝ) (n : ℕ) : ℝ :=
  c * (((n : ℝ) + 1)⁻¹)

/-- The reciprocal sequence tends to zero. -/
def conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero (c : ℝ) : Prop :=
  Tendsto (conclusion_binfold_harmonic_staircase_kinks_reciprocal_sequence c) atTop (𝓝 0)

/-- Exact equality between the kink locations and the two harmonic jump grids. -/
def conclusion_binfold_harmonic_staircase_kinks_kink_set_exact : Prop :=
  conclusion_binfold_harmonic_staircase_kinks_kink_set =
    conclusion_binfold_harmonic_staircase_kinks_jump_set

/-- Both harmonic grids have the same limiting endpoint, witnessed by reciprocal convergence to
zero. -/
def conclusion_binfold_harmonic_staircase_kinks_unique_accumulation_zero : Prop :=
  conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero 1 ∧
    conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero
      conclusion_binfold_harmonic_staircase_kinks_phi_inv

lemma conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero_of_const
    (c : ℝ) :
    conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero c := by
  have hbase :
      Tendsto (fun n : ℕ => (1 / ((n : ℝ) + 1) : ℝ)) atTop (𝓝 0) :=
    tendsto_one_div_add_atTop_nhds_zero_nat
  simpa [conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero,
    conclusion_binfold_harmonic_staircase_kinks_reciprocal_sequence, one_div] using
    tendsto_const_nhds.mul hbase

/-- Paper label: `cor:conclusion-binfold-harmonic-staircase-kinks`. The kink set is the union of
the two harmonic jump grids with constants `1` and `φ⁻¹`; the reciprocal sequences for both grids
converge to `0`, giving the common accumulation endpoint. -/
theorem paper_conclusion_binfold_harmonic_staircase_kinks :
    conclusion_binfold_harmonic_staircase_kinks_kink_set_exact ∧
      conclusion_binfold_harmonic_staircase_kinks_unique_accumulation_zero := by
  refine ⟨?_, ?_⟩
  · ext x
    constructor
    · intro hx
      rcases hx with hx | hx
      · exact ⟨1, by simp, hx⟩
      · exact ⟨conclusion_binfold_harmonic_staircase_kinks_phi_inv, by simp, hx⟩
    · rintro ⟨c, hc, n, hn, rfl⟩
      rcases hc with rfl | rfl
      · exact Or.inl ⟨n, hn, rfl⟩
      · exact Or.inr ⟨n, hn, rfl⟩
  · exact ⟨conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero_of_const 1,
      conclusion_binfold_harmonic_staircase_kinks_reciprocal_tends_zero_of_const
        conclusion_binfold_harmonic_staircase_kinks_phi_inv⟩

end

end Omega.Conclusion
