import Mathlib.NumberTheory.Real.GoldenRatio
import Mathlib.Tactic
import Omega.Conclusion.BinfoldMellinEscortSemigroup

namespace Omega.Conclusion

noncomputable section

/-- The golden parameter for the normalized relative-density mother law. -/
def conclusion_binfold_relative_density_normalized_mother_law_phi : ℝ :=
  Real.goldenRatio

/-- Uniform two-point reference mass. -/
def conclusion_binfold_relative_density_normalized_mother_law_uniformMass (_b : Bool) : ℝ :=
  1 / 2

/-- The golden two-atom mother law, reused from the Mellin escort package. -/
def conclusion_binfold_relative_density_normalized_mother_law_motherMass (b : Bool) : ℝ :=
  binfoldMellinBaseLaw conclusion_binfold_relative_density_normalized_mother_law_phi b

/-- The density of the mother law relative to the uniform two-point reference. -/
def conclusion_binfold_relative_density_normalized_mother_law_density (b : Bool) : ℝ :=
  conclusion_binfold_relative_density_normalized_mother_law_motherMass b /
    conclusion_binfold_relative_density_normalized_mother_law_uniformMass b

/-- The two-point `f`-divergence generated by the normalized relative density. -/
def conclusion_binfold_relative_density_normalized_mother_law_fDivergence
    (f : ℝ → ℝ) : ℝ :=
  conclusion_binfold_relative_density_normalized_mother_law_uniformMass false *
      f (conclusion_binfold_relative_density_normalized_mother_law_density false) +
    conclusion_binfold_relative_density_normalized_mother_law_uniformMass true *
      f (conclusion_binfold_relative_density_normalized_mother_law_density true)

/-- Paper label: `thm:conclusion-binfold-relative-density-normalized-mother-law`.
The golden two-atom mother law is normalized over the uniform binary reference, its relative
density has the two displayed closed forms, and every two-point `f`-divergence is the corresponding
uniform average of `f` evaluated at those densities. -/
theorem paper_conclusion_binfold_relative_density_normalized_mother_law :
    0 < conclusion_binfold_relative_density_normalized_mother_law_phi ∧
      conclusion_binfold_relative_density_normalized_mother_law_motherMass false +
          conclusion_binfold_relative_density_normalized_mother_law_motherMass true =
        1 ∧
      conclusion_binfold_relative_density_normalized_mother_law_density false =
        2 * conclusion_binfold_relative_density_normalized_mother_law_phi /
          (1 + conclusion_binfold_relative_density_normalized_mother_law_phi) ∧
      conclusion_binfold_relative_density_normalized_mother_law_density true =
        2 / (1 + conclusion_binfold_relative_density_normalized_mother_law_phi) ∧
      (∀ f : ℝ → ℝ,
        conclusion_binfold_relative_density_normalized_mother_law_fDivergence f =
          (1 / 2) *
              f
                (2 * conclusion_binfold_relative_density_normalized_mother_law_phi /
                  (1 + conclusion_binfold_relative_density_normalized_mother_law_phi)) +
            (1 / 2) *
              f
                (2 / (1 + conclusion_binfold_relative_density_normalized_mother_law_phi))) ∧
      BinfoldMellinEscortSemigroup
        conclusion_binfold_relative_density_normalized_mother_law_phi := by
  have hphi : 0 < conclusion_binfold_relative_density_normalized_mother_law_phi := by
    simpa [conclusion_binfold_relative_density_normalized_mother_law_phi] using
      Real.goldenRatio_pos
  have hden :
      (1 + conclusion_binfold_relative_density_normalized_mother_law_phi : ℝ) ≠ 0 := by
    positivity
  refine ⟨hphi, ?_, ?_, ?_, ?_, ?_⟩
  · unfold conclusion_binfold_relative_density_normalized_mother_law_motherMass
      conclusion_binfold_relative_density_normalized_mother_law_phi binfoldMellinBaseLaw
    field_simp [hden]
    ring
  · unfold conclusion_binfold_relative_density_normalized_mother_law_density
      conclusion_binfold_relative_density_normalized_mother_law_motherMass
      conclusion_binfold_relative_density_normalized_mother_law_uniformMass
      binfoldMellinBaseLaw
    field_simp [hden]
  · unfold conclusion_binfold_relative_density_normalized_mother_law_density
      conclusion_binfold_relative_density_normalized_mother_law_motherMass
      conclusion_binfold_relative_density_normalized_mother_law_uniformMass
      binfoldMellinBaseLaw
    field_simp [hden]
  · intro f
    unfold conclusion_binfold_relative_density_normalized_mother_law_fDivergence
    rw [show
        conclusion_binfold_relative_density_normalized_mother_law_density false =
          2 * conclusion_binfold_relative_density_normalized_mother_law_phi /
            (1 + conclusion_binfold_relative_density_normalized_mother_law_phi) by
        unfold conclusion_binfold_relative_density_normalized_mother_law_density
          conclusion_binfold_relative_density_normalized_mother_law_motherMass
          conclusion_binfold_relative_density_normalized_mother_law_uniformMass
          binfoldMellinBaseLaw
        field_simp [hden]
        ,
      show
        conclusion_binfold_relative_density_normalized_mother_law_density true =
          2 / (1 + conclusion_binfold_relative_density_normalized_mother_law_phi) by
        unfold conclusion_binfold_relative_density_normalized_mother_law_density
          conclusion_binfold_relative_density_normalized_mother_law_motherMass
          conclusion_binfold_relative_density_normalized_mother_law_uniformMass
          binfoldMellinBaseLaw
        field_simp [hden]
        ]
    simp [conclusion_binfold_relative_density_normalized_mother_law_uniformMass]
  · simpa [conclusion_binfold_relative_density_normalized_mother_law_phi] using
      paper_conclusion_binfold_mellin_escort_semigroup

end

end Omega.Conclusion
