import Mathlib.MeasureTheory.Group.AddCircle
import Mathlib.Topology.Instances.AddCircle.DenseSubgroup
import Mathlib.Tactic

namespace Omega.Conclusion

/-- Paper label: `thm:conclusion-circle-closed-subgroup-classification`.

For the unit additive circle, every closed subgroup is either the whole circle or a cyclic subgroup
generated by a finite-order element, and every infinite subgroup is dense. -/
def conclusion_circle_closed_subgroup_classification_statement : Prop :=
  (∀ s : AddSubgroup (AddCircle (1 : ℝ)),
      IsClosed (s : Set (AddCircle (1 : ℝ))) →
        s = ⊤ ∨ ∃ a : AddCircle (1 : ℝ), addOrderOf a ≠ 0 ∧ s = AddSubgroup.zmultiples a) ∧
    ∀ s : AddSubgroup (AddCircle (1 : ℝ)),
      Set.Infinite (s : Set (AddCircle (1 : ℝ))) → Dense (s : Set (AddCircle (1 : ℝ)))

theorem paper_conclusion_circle_closed_subgroup_classification :
    conclusion_circle_closed_subgroup_classification_statement := by
  haveI : Fact (0 < (1 : ℝ)) := ⟨zero_lt_one⟩
  refine ⟨?_, ?_⟩
  · intro s hsClosed
    by_cases hsDense : Dense (s : Set (AddCircle (1 : ℝ)))
    · left
      have hsSet : (s : Set (AddCircle (1 : ℝ))) = Set.univ := by
        rw [← hsClosed.closure_eq, hsDense.closure_eq]
      ext x
      change x ∈ (s : Set (AddCircle (1 : ℝ))) ↔ x ∈ (⊤ : AddSubgroup (AddCircle (1 : ℝ)))
      simp [hsSet]
    · right
      have hsNot :
          ¬ ∀ a : AddCircle (1 : ℝ), addOrderOf a ≠ 0 → s ≠ AddSubgroup.zmultiples a := by
        simpa [AddCircle.dense_addSubgroup_iff_ne_zmultiples (p := (1 : ℝ)) (s := s)] using hsDense
      push_neg at hsNot
      exact hsNot
  · intro s hsInfinite
    have hsDenseCriterion :
        ∀ a : AddCircle (1 : ℝ), addOrderOf a ≠ 0 → s ≠ AddSubgroup.zmultiples a := by
      intro a ha hsEq
      have haFinite : IsOfFinAddOrder a := addOrderOf_pos_iff.mp (Nat.pos_of_ne_zero ha)
      have hsFinite : Set.Finite (s : Set (AddCircle (1 : ℝ))) := by
        simpa [hsEq] using haFinite.finite_zmultiples
      exact hsFinite.not_infinite hsInfinite
    exact
      (AddCircle.dense_addSubgroup_iff_ne_zmultiples (p := (1 : ℝ)) (s := s)).2 hsDenseCriterion

end Omega.Conclusion
