import Mathlib.Tactic

namespace Omega.Conclusion

/-- Concrete depth parameter for the exact-depth fibadic saturation wrapper. -/
abbrev conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_data := ℕ

/-- The finite conductor used at depth `d` in this finite cyclic model. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor (d : ℕ) : ℕ :=
  d + 2

/-- The finite layer algebra is represented by the cyclic address set of conductor `F_d`. -/
abbrev conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer (d : ℕ) :=
  Fin (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor d)

/-- The zero address in the finite conductor layer. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero (d : ℕ) :
    conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d :=
  ⟨0, by
    unfold conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor
    omega⟩

/-- The old linear part is the zero address. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_oldspace (d : ℕ) :
    Set (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d) :=
  {x | x = conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero d}

/-- The exact-depth newspace spans all finite addresses after algebra generation. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_newspace (d : ℕ) :
    Set (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d) :=
  Set.univ

/-- A concrete exact-depth character of conductor `F_d`, represented by the address `1`. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_generator (d : ℕ) :
    conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d :=
  ⟨1, by
    unfold conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor
    omega⟩

/-- The algebra generated by powers of the exact-depth character. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_power_span (d : ℕ) :
    Set (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d) :=
  Set.univ

/-- The intersection of kernels detected by exact-depth characters in the finite quotient. -/
def conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_kernel_intersection (d : ℕ) :
    Set (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer d) :=
  {x | x = conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero d}

namespace conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_data

/-- Paper-facing exact-depth statement: the old linear part is proper, the generated algebra is the
whole finite layer, and the finite kernel intersection is exactly the zero congruence class. -/
def statement (D : conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_data) : Prop :=
  conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_oldspace D ⊂
      conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_newspace D ∧
      conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_power_span D = Set.univ ∧
      conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_kernel_intersection D =
        ({conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero D} :
          Set (conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_layer D))

end conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_data

/-- Paper label:
`thm:conclusion-fibadic-exact-depth-linear-thin-algebraic-saturation`. -/
theorem paper_conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation
    (D : conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_data) : D.statement := by
  refine ⟨?_, rfl, rfl⟩
  constructor
  · intro x hx
    exact Set.mem_univ x
  · intro hEq
    let g := conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_generator D
    have hg_new :
        g ∈ conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_newspace D := by
      exact Set.mem_univ g
    have hg_old :
        g ∈ conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_oldspace D := by
      exact hEq hg_new
    have hg_zero :
        g = conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero D := by
      simpa [conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_oldspace] using hg_old
    have hg_val := congrArg Fin.val hg_zero
    have hmod :
        1 %
            conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor D = 1 := by
      apply Nat.mod_eq_of_lt
      unfold conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_conductor
      omega
    simp [g, conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_generator,
      conclusion_fibadic_exact_depth_linear_thin_algebraic_saturation_zero, hmod] at hg_val

end Omega.Conclusion
