import Mathlib.Tactic

namespace Omega.Conclusion

noncomputable section

/-- The finite critical phase set for the normalized finite-dimensional model. -/
abbrev conclusion_finite_dimensional_normalized_critical_phase_finite_comb_data :=
  Finset ℝ

/-- The integer translate of one normalized critical phase. -/
def conclusion_finite_dimensional_normalized_critical_phase_finite_comb_translate
    (θ : ℝ) : Set ℝ :=
  {u | ∃ n : ℤ, u = θ + n}

/-- The finite union of integer translates generated by the critical phase set. -/
def conclusion_finite_dimensional_normalized_critical_phase_finite_comb_comb
    (Φ : Finset ℝ) : Set ℝ :=
  {u | ∃ θ ∈ Φ,
    u ∈ conclusion_finite_dimensional_normalized_critical_phase_finite_comb_translate θ}

/-- Normalized critical ordinates attached to the finite critical phase set. -/
def conclusion_finite_dimensional_normalized_critical_phase_finite_comb_ordinates
    (Φ : Finset ℝ) : Set ℝ :=
  conclusion_finite_dimensional_normalized_critical_phase_finite_comb_comb Φ

/-- Concrete finite-comb statement for normalized critical ordinates. -/
def conclusion_finite_dimensional_normalized_critical_phase_finite_comb_statement
    (D : conclusion_finite_dimensional_normalized_critical_phase_finite_comb_data) : Prop :=
  ∀ u : ℝ,
    u ∈ conclusion_finite_dimensional_normalized_critical_phase_finite_comb_ordinates D ↔
      ∃ θ ∈ D, ∃ n : ℤ, u = θ + n

/-- Paper label: `thm:conclusion-finite-dimensional-normalized-critical-phase-finite-comb`. -/
theorem paper_conclusion_finite_dimensional_normalized_critical_phase_finite_comb
    (D : conclusion_finite_dimensional_normalized_critical_phase_finite_comb_data) :
    conclusion_finite_dimensional_normalized_critical_phase_finite_comb_statement D := by
  intro u
  simp [
    conclusion_finite_dimensional_normalized_critical_phase_finite_comb_ordinates,
    conclusion_finite_dimensional_normalized_critical_phase_finite_comb_comb,
    conclusion_finite_dimensional_normalized_critical_phase_finite_comb_translate]

end

end Omega.Conclusion
