import Mathlib

namespace Omega.Conclusion

/-- A concrete three-fiber Walsh simplex model in `R^2`. -/
def conclusion_fold_walsh_principal_minors_unique_relation_vector
    (i : Fin 3) (j : Fin 2) : ℝ :=
  if i = 0 then
    if j = 0 then 1 else 0
  else if i = 1 then
    if j = 0 then 0 else 1
  else
    -1

/-- The Gram entry for the concrete Walsh simplex model. -/
def conclusion_fold_walsh_principal_minors_unique_relation_gram
    (i j : Fin 3) : ℝ :=
  ∑ k : Fin 2,
    conclusion_fold_walsh_principal_minors_unique_relation_vector i k *
      conclusion_fold_walsh_principal_minors_unique_relation_vector j k

/-- The `2 x 2` principal minor attached to two fibers. -/
def conclusion_fold_walsh_principal_minors_unique_relation_twoMinor
    (i j : Fin 3) : ℝ :=
  conclusion_fold_walsh_principal_minors_unique_relation_gram i i *
      conclusion_fold_walsh_principal_minors_unique_relation_gram j j -
    conclusion_fold_walsh_principal_minors_unique_relation_gram i j *
      conclusion_fold_walsh_principal_minors_unique_relation_gram j i

/-- Linear relations among the three Walsh simplex fibers. -/
def conclusion_fold_walsh_principal_minors_unique_relation_relation
    (a : Fin 3 → ℝ) : Prop :=
  a 0 = a 2 ∧ a 1 = a 2

/-- Concrete statement: proper principal minors are positive and the full relation space is
one-dimensional, generated by the all-ones fiber relation. -/
def conclusion_fold_walsh_principal_minors_unique_relation_statement : Prop :=
  (∀ i : Fin 3,
    0 < conclusion_fold_walsh_principal_minors_unique_relation_gram i i) ∧
  (∀ i j : Fin 3, i ≠ j →
    conclusion_fold_walsh_principal_minors_unique_relation_twoMinor i j = 1) ∧
  (∀ a : Fin 3 → ℝ,
    conclusion_fold_walsh_principal_minors_unique_relation_relation a ↔
      ∃ c : ℝ, ∀ i : Fin 3, a i = c) ∧
  (∀ omitted : Fin 3, ∀ a : Fin 3 → ℝ, a omitted = 0 →
    conclusion_fold_walsh_principal_minors_unique_relation_relation a →
      ∀ i : Fin 3, a i = 0)

theorem paper_conclusion_fold_walsh_principal_minors_unique_relation :
    conclusion_fold_walsh_principal_minors_unique_relation_statement := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro i
    fin_cases i <;>
      norm_num [conclusion_fold_walsh_principal_minors_unique_relation_gram,
        conclusion_fold_walsh_principal_minors_unique_relation_vector]
  · intro i j hij
    fin_cases i <;> fin_cases j <;>
      simp_all [conclusion_fold_walsh_principal_minors_unique_relation_twoMinor,
        conclusion_fold_walsh_principal_minors_unique_relation_gram,
        conclusion_fold_walsh_principal_minors_unique_relation_vector] <;>
      norm_num
  · intro a
    constructor
    · intro h
      refine ⟨a 2, ?_⟩
      intro i
      fin_cases i <;>
        simp [conclusion_fold_walsh_principal_minors_unique_relation_relation] at h ⊢ <;>
        tauto
    · rintro ⟨c, hc⟩
      simp [conclusion_fold_walsh_principal_minors_unique_relation_relation, hc]
  · intro omitted a ha hrel i
    have hconst :
        ∃ c : ℝ, ∀ i : Fin 3, a i = c := by
      exact
        ((show
          conclusion_fold_walsh_principal_minors_unique_relation_relation a ↔
            ∃ c : ℝ, ∀ i : Fin 3, a i = c from by
          constructor
          · intro h
            refine ⟨a 2, ?_⟩
            intro i
            fin_cases i <;>
              simp [conclusion_fold_walsh_principal_minors_unique_relation_relation] at h ⊢ <;>
              tauto
          · rintro ⟨c, hc⟩
            simp [conclusion_fold_walsh_principal_minors_unique_relation_relation, hc])).1 hrel
    rcases hconst with ⟨c, hc⟩
    have hc_zero : c = 0 := by
      rw [← hc omitted]
      exact ha
    rw [hc i, hc_zero]

end Omega.Conclusion
