import Mathlib.Data.Bool.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Order.Monotone.Basic
import Mathlib.Tactic

namespace Omega.Conclusion

/-- Coordinatewise order on finite Boolean or real inputs. -/
def CoordinatewiseLE {n : ℕ} {α : Type*} [LE α] (x y : Fin n → α) : Prop :=
  ∀ i, x i ≤ y i

/-- Free-energy gates generated by coordinates, constants, addition, and `max`. -/
inductive FreeEnergyGate (n : ℕ) where
  | input : Fin n → FreeEnergyGate n
  | const : ℝ → FreeEnergyGate n
  | add : FreeEnergyGate n → FreeEnergyGate n → FreeEnergyGate n
  | maxGate : FreeEnergyGate n → FreeEnergyGate n → FreeEnergyGate n

/-- Evaluate a free-energy gate on a real input vector. -/
def FreeEnergyGate.eval {n : ℕ} : FreeEnergyGate n → (Fin n → ℝ) → ℝ
  | .input i, x => x i
  | .const c, _ => c
  | .add g h, x => g.eval x + h.eval x
  | .maxGate g h, x => max (g.eval x) (h.eval x)

/-- Coordinatewise monotonicity of a real-valued gate on `ℝ^n`. -/
def CoordinatewiseMonotone {n : ℕ} (F : (Fin n → ℝ) → ℝ) : Prop :=
  ∀ x y, CoordinatewiseLE x y → F x ≤ F y

/-- The `0/1` embedding of the Boolean cube into `ℝ^n`. -/
def boolCubeEmbedding {n : ℕ} (x : Fin n → Bool) : Fin n → ℝ :=
  fun i => if x i then 1 else 0

/-- Threshold compilation of a free-energy gate to a Boolean function. -/
def CompilesToBoolean {n : ℕ} (g : FreeEnergyGate n) (f : (Fin n → Bool) → Bool) : Prop :=
  ∀ x, f x = decide (0 ≤ g.eval (boolCubeEmbedding x))

/-- Monotonicity on the Boolean cube. -/
def MonotoneBoolFunction {n : ℕ} (f : (Fin n → Bool) → Bool) : Prop :=
  ∀ x y, CoordinatewiseLE x y → f x = true → f y = true

/-- Boolean negation on one input bit. -/
def boolNotGate : (Fin 1 → Bool) → Bool :=
  fun x => !(x 0)

/-- Odd parity on two input bits. -/
def oddParityTwoGate : (Fin 2 → Bool) → Bool :=
  fun x => Bool.xor (x 0) (x 1)

lemma boolCubeEmbedding_monotone {n : ℕ} {x y : Fin n → Bool}
    (hxy : CoordinatewiseLE x y) :
    CoordinatewiseLE (boolCubeEmbedding x) (boolCubeEmbedding y) := by
  intro i
  have hi := hxy i
  cases hx : x i <;> cases hy : y i <;> simp [boolCubeEmbedding, hx, hy] at hi ⊢
  case true.false =>
    exact False.elim ((by decide : ¬ (true ≤ false)) hi)

lemma eval_coordinatewise_monotone {n : ℕ} (g : FreeEnergyGate n) :
    CoordinatewiseMonotone g.eval := by
  induction g with
  | input i =>
      intro x y hxy
      exact hxy i
  | const c =>
      intro x y hxy
      rfl
  | add g h hg hh =>
      intro x y hxy
      exact add_le_add (hg x y hxy) (hh x y hxy)
  | maxGate g h hg hh =>
      intro x y hxy
      simpa [FreeEnergyGate.eval] using max_le_max (hg x y hxy) (hh x y hxy)

lemma compiled_boolean_monotone {n : ℕ} (g : FreeEnergyGate n) (f : (Fin n → Bool) → Bool)
    (hcompile : CompilesToBoolean g f) :
    MonotoneBoolFunction f := by
  intro x y hxy hx
  have hx' : 0 ≤ g.eval (boolCubeEmbedding x) := by
    exact Bool.of_decide_true (by simpa [CompilesToBoolean, hcompile x] using hx)
  have hmono :=
    eval_coordinatewise_monotone g (boolCubeEmbedding x) (boolCubeEmbedding y)
      (boolCubeEmbedding_monotone hxy)
  have hy' : 0 ≤ g.eval (boolCubeEmbedding y) := le_trans hx' hmono
  have hydec : decide (0 ≤ g.eval (boolCubeEmbedding y)) = true := Bool.decide_true hy'
  simpa [CompilesToBoolean, hcompile y] using hydec

lemma boolNotGate_not_monotone : ¬ MonotoneBoolFunction boolNotGate := by
  intro hmono
  let x : Fin 1 → Bool := fun _ => false
  let y : Fin 1 → Bool := fun _ => true
  have hxy : CoordinatewiseLE x y := by
    intro i
    fin_cases i
    · simp [x, y]
  have hx : boolNotGate x = true := by
    simp [boolNotGate, x]
  have hy := hmono x y hxy hx
  simp [boolNotGate, y] at hy

lemma oddParityTwoGate_not_monotone : ¬ MonotoneBoolFunction oddParityTwoGate := by
  intro hmono
  let x : Fin 2 → Bool := fun i => i = 0
  let y : Fin 2 → Bool := fun _ => true
  have hxy : CoordinatewiseLE x y := by
    intro i
    fin_cases i
    · simp [x, y]
    · simp [x, y]
  have hx : oddParityTwoGate x = true := by
    simp [oddParityTwoGate, x]
  have hy := hmono x y hxy hx
  simp [oddParityTwoGate, y] at hy

/-- Addition, `max`, and constants preserve coordinatewise monotonicity, so any Boolean-valued
gate compiled from these free-energy primitives is monotone on the Boolean cube. Consequently,
`NOT` and odd parity are excluded from the closure.
    prop:conclusion-free-energy-gates-monotonicity-obstruction -/
theorem paper_conclusion_free_energy_gates_monotonicity_obstruction :
    (∀ n : ℕ, ∀ g : FreeEnergyGate n, CoordinatewiseMonotone g.eval) ∧
      (∀ n : ℕ, ∀ g : FreeEnergyGate n, ∀ f : (Fin n → Bool) → Bool,
        CompilesToBoolean g f → MonotoneBoolFunction f) ∧
      (∀ g : FreeEnergyGate 1, ¬ CompilesToBoolean g boolNotGate) ∧
      (∀ g : FreeEnergyGate 2, ¬ CompilesToBoolean g oddParityTwoGate) := by
  refine ⟨fun n g => eval_coordinatewise_monotone g, ?_, ?_, ?_⟩
  · intro n g f hcompile
    exact compiled_boolean_monotone g f hcompile
  · intro g hcompile
    exact boolNotGate_not_monotone (compiled_boolean_monotone g boolNotGate hcompile)
  · intro g hcompile
    exact oddParityTwoGate_not_monotone (compiled_boolean_monotone g oddParityTwoGate hcompile)

end Omega.Conclusion
