import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic
import Omega.Conclusion.ScreenMaxConditionalComplexityEqualsRank
import Omega.SPG.CoordinateBundleScreenCount
import Omega.SPG.ScreenKernelConnectedComponents

namespace Omega.Conclusion

/-- The full internal screen component count is obtained by taking `s = n` in the coordinate-bundle
closed form, leaving only the bulk component and the isolated exterior vertex `∞`. -/
def fullInternalScreenComponentCount (m n : ℕ) : ℕ :=
  Omega.SPG.CoordinateBundleScreenCount.screenComponentCount m n n

/-- The corresponding screen-kernel rank is `c - 1`. -/
def fullInternalScreenKernelRank (m n : ℕ) : ℕ :=
  fullInternalScreenComponentCount m n - 1

/-- The surviving generator is the all-ones chain on the unique free component. -/
def fullInternalScreenAllOnesChain : Fin 1 → ZMod 2 :=
  fullScreenCoordinate 1

/-- Paper label: `thm:conclusion-full-internal-screen-global-complement-law`. The all-internal
screen has exactly two connected components, so the screen-kernel framework gives rank `1`; the
remaining free component is generated by the all-ones chain. -/
theorem paper_conclusion_full_internal_screen_global_complement_law (m n : ℕ) :
    fullInternalScreenComponentCount m n = 2 ∧
      fullInternalScreenKernelRank m n = 1 ∧
      screenCoordinateComplexity fullInternalScreenAllOnesChain = 1 := by
  have hcomp : fullInternalScreenComponentCount m n = 2 := by
    simp [fullInternalScreenComponentCount, Omega.SPG.CoordinateBundleScreenCount.screenComponentCount]
  have hframework :
      fullInternalScreenKernelRank m n + 1 = fullInternalScreenComponentCount m n := by
    rw [fullInternalScreenKernelRank]
    exact Omega.SPG.ScreenKernelConnectedComponents.free_components_count
      (fullInternalScreenComponentCount m n) (by omega)
  have hker : fullInternalScreenKernelRank m n = 1 := by
    rw [hcomp] at hframework
    omega
  refine ⟨hcomp, hker, ?_⟩
  simpa [fullInternalScreenAllOnesChain] using screenCoordinateComplexity_fullScreenCoordinate 1

end Omega.Conclusion
