import Mathlib.Data.Finset.Card
import Omega.Conclusion.CoordinateBundleKernelSlabDecomposition
import Omega.Conclusion.FullInternalScreenGlobalComplementLaw
import Omega.SPG.FullInternalScreenOneDefectBoundaryClosure

namespace Omega.Conclusion

/-- The full visible index set `J = [n]`. -/
abbrev conclusion_full_internal_visibility_unique_global_mode_fullIndexSet
    (n : ℕ) : Finset (Fin n) :=
  Finset.univ

/-- The surviving global mode `Ω_m`, represented by the all-ones chain on the unique free block. -/
abbrev conclusion_full_internal_visibility_unique_global_mode_globalCubeSum
    (_m : ℕ) : Fin 1 → ZMod 2 :=
  fullInternalScreenAllOnesChain

/-- The slab count that survives after specializing to the full internal visibility screen. -/
def conclusion_full_internal_visibility_unique_global_mode_slabCount (m n : ℕ) : ℕ :=
  (Omega.SPG.CoordinateBundleScreenCount.screenComponentCount m n
      (conclusion_full_internal_visibility_unique_global_mode_fullIndexSet n).card) - 1

/-- Residual audit defect after adjoining an external boundary family. -/
def conclusion_full_internal_visibility_unique_global_mode_boundaryDefect
    (m n : ℕ) (B : Finset ℕ) : ℕ :=
  if B.Nonempty then Omega.SPG.CoordinateBundleScreenCount.auditCost m n n - 1
  else Omega.SPG.CoordinateBundleScreenCount.auditCost m n n

/-- Paper label: `thm:conclusion-full-internal-visibility-unique-global-mode`. For `J = [n]`,
  the slab decomposition leaves a single surviving mode; it is generated by the global all-ones
chain, and any nonempty external boundary family removes that last defect. -/
theorem paper_conclusion_full_internal_visibility_unique_global_mode (m n : ℕ) :
    conclusion_full_internal_visibility_unique_global_mode_slabCount m n = 1 ∧
      fullInternalScreenKernelRank m n = 1 ∧
      screenCoordinateComplexity
          (conclusion_full_internal_visibility_unique_global_mode_globalCubeSum m) = 1 ∧
      (∀ B : Finset ℕ, B.Nonempty →
        conclusion_full_internal_visibility_unique_global_mode_boundaryDefect m n B = 0) := by
  have hslab :
      conclusion_full_internal_visibility_unique_global_mode_slabCount m n = 1 := by
    calc
      conclusion_full_internal_visibility_unique_global_mode_slabCount m n
          = Omega.SPG.CoordinateBundleScreenCount.screenComponentCount m n n - 1 := by
              simp [conclusion_full_internal_visibility_unique_global_mode_slabCount,
                conclusion_full_internal_visibility_unique_global_mode_fullIndexSet]
      _ = 2 ^ (m * (n - n)) := paper_conclusion_coordinate_bundle_kernel_slab_decomposition m n n
      _ = 1 := by simp
  rcases paper_conclusion_full_internal_screen_global_complement_law m n with ⟨_, hker, hmode⟩
  rcases Omega.SPG.paper_spg_full_internal_screen_one_defect_boundary_closure m n with ⟨_, haudit⟩
  refine ⟨hslab, hker, ?_, ?_⟩
  · simpa [conclusion_full_internal_visibility_unique_global_mode_globalCubeSum] using hmode
  · intro B hB
    simp [conclusion_full_internal_visibility_unique_global_mode_boundaryDefect, hB, haudit]

end Omega.Conclusion
