import Mathlib.Analysis.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic

namespace Omega.Conclusion

noncomputable section

/-- The rational cosine value attached to the hypercube phase indexed by `(d, k)`. -/
def conclusion_hypercube_phase_quadratic_closure_phase_cos (d k : ℕ) : ℝ :=
  ((((1 : ℚ) - (2 * k : ℚ) / d : ℚ)) : ℝ)

/-- The sine value attached to the hypercube phase, written as a rational multiple of the
quadratic radical `sqrt (k (d - k))`. -/
def conclusion_hypercube_phase_quadratic_closure_phase_sin (d k : ℕ) : ℝ :=
  ((((2 : ℚ) / d : ℚ)) : ℝ) * Real.sqrt (k * (d - k))

/-- The hyperbola-leaf point `r e^{iθ} + r⁻¹ e^{-iθ}` written with the explicit trigonometric
coordinates used in the paper. -/
def conclusion_hypercube_phase_quadratic_closure_point (d k : ℕ) (r : ℚ) : ℂ :=
  Complex.mk
    ((((r : ℝ) + (r : ℝ)⁻¹) * conclusion_hypercube_phase_quadratic_closure_phase_cos d k))
    ((((r : ℝ) - (r : ℝ)⁻¹) * conclusion_hypercube_phase_quadratic_closure_phase_sin d k))

/-- Paper-facing quadratic-closure package for hypercube phases: the cosine is rational, the
sine is a rational multiple of `sqrt (k (d - k))`, and the corresponding leaf point has rational
real part and imaginary part in the same quadratic line. -/
def conclusion_hypercube_phase_quadratic_closure_statement : Prop :=
  ∀ d k : ℕ, 0 < d → k ≤ d → ∀ r : ℚ,
    ∃ qc qs qre qim : ℚ,
      conclusion_hypercube_phase_quadratic_closure_phase_cos d k = qc ∧
        conclusion_hypercube_phase_quadratic_closure_phase_sin d k =
          (qs : ℝ) * Real.sqrt (k * (d - k)) ∧
        (conclusion_hypercube_phase_quadratic_closure_point d k r).re = qre ∧
        (conclusion_hypercube_phase_quadratic_closure_point d k r).im =
          (qim : ℝ) * Real.sqrt (k * (d - k))

/-- Paper label: `thm:conclusion-hypercube-phase-quadratic-closure`. The explicit trigonometric
formulas show that the hypercube phase cosine is rational, the sine lies in the quadratic line
generated by `sqrt (k (d - k))`, and the associated Joukowsky point has the same quadratic-field
closure pattern in its coordinates. -/
theorem paper_conclusion_hypercube_phase_quadratic_closure :
    conclusion_hypercube_phase_quadratic_closure_statement := by
  intro d k hd hk r
  let qc : ℚ := (1 : ℚ) - (2 * k : ℚ) / d
  let qs : ℚ := (2 : ℚ) / d
  let qre : ℚ := (r + r⁻¹) * qc
  let qim : ℚ := (r - r⁻¹) * qs
  refine ⟨qc, qs, qre, qim, ?_, ?_, ?_, ?_⟩
  · simp [conclusion_hypercube_phase_quadratic_closure_phase_cos, qc]
  · simp [conclusion_hypercube_phase_quadratic_closure_phase_sin, qs]
  · simp [conclusion_hypercube_phase_quadratic_closure_point,
      conclusion_hypercube_phase_quadratic_closure_phase_cos, qc, qre]
  · simp [conclusion_hypercube_phase_quadratic_closure_point,
      conclusion_hypercube_phase_quadratic_closure_phase_sin, qs, qim]
    ring

end

end Omega.Conclusion
