import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Tactic

namespace Omega.Conclusion

noncomputable section

/-- Concrete two-prime Godel/log-lattice package. -/
structure conclusion_jg_godel_loglattice_approximation_witness where
  left_prime : ℝ
  right_prime : ℝ
  left_prime_pos : 0 < left_prime
  right_prime_pos : 0 < right_prime
  left_index : ℤ
  right_index : ℤ
  target_log : ℝ

/-- The chosen lattice point in logarithmic coordinates. -/
def conclusion_jg_godel_loglattice_approximation_log_lattice_point
    (w : conclusion_jg_godel_loglattice_approximation_witness) : ℝ :=
  (w.left_index : ℝ) * Real.log w.left_prime + (w.right_index : ℝ) * Real.log w.right_prime

/-- The corresponding ledger element is the exponential of the chosen log-lattice point. -/
def conclusion_jg_godel_loglattice_approximation_ledger_value
    (w : conclusion_jg_godel_loglattice_approximation_witness) : ℝ :=
  Real.exp (conclusion_jg_godel_loglattice_approximation_log_lattice_point w)

/-- The full two-prime log lattice generated by the two logarithmic scales. -/
def conclusion_jg_godel_loglattice_approximation_log_lattice
    (w : conclusion_jg_godel_loglattice_approximation_witness) : Set ℝ :=
  Set.range fun mn : ℤ × ℤ =>
    (mn.1 : ℝ) * Real.log w.left_prime + (mn.2 : ℝ) * Real.log w.right_prime

/-- Absolute log-approximation errors against the whole lattice. -/
def conclusion_jg_godel_loglattice_approximation_log_error_set
    (w : conclusion_jg_godel_loglattice_approximation_witness) : Set ℝ :=
  Set.range fun mn : ℤ × ℤ =>
    |w.target_log -
      ((mn.1 : ℝ) * Real.log w.left_prime + (mn.2 : ℝ) * Real.log w.right_prime)|

/-- Distance from the target logarithm to the two-prime log lattice. -/
def conclusion_jg_godel_loglattice_approximation_distance_to_lattice
    (w : conclusion_jg_godel_loglattice_approximation_witness) : ℝ :=
  sInf (conclusion_jg_godel_loglattice_approximation_log_error_set w)

/-- Paper-facing package: the ledger element is an exponential of a log-lattice point, its
logarithmic error is exactly the absolute difference to that lattice point, and the infimum of the
error set is by definition the distance to the lattice. -/
def conclusion_jg_godel_loglattice_approximation_statement
    (w : conclusion_jg_godel_loglattice_approximation_witness) : Prop :=
  conclusion_jg_godel_loglattice_approximation_ledger_value w =
      Real.exp (conclusion_jg_godel_loglattice_approximation_log_lattice_point w) ∧
    conclusion_jg_godel_loglattice_approximation_log_lattice_point w ∈
        conclusion_jg_godel_loglattice_approximation_log_lattice w ∧
    |Real.log (conclusion_jg_godel_loglattice_approximation_ledger_value w) - w.target_log| =
      |w.target_log -
        conclusion_jg_godel_loglattice_approximation_log_lattice_point w| ∧
    |w.target_log - conclusion_jg_godel_loglattice_approximation_log_lattice_point w| ∈
        conclusion_jg_godel_loglattice_approximation_log_error_set w ∧
    conclusion_jg_godel_loglattice_approximation_distance_to_lattice w =
      sInf (conclusion_jg_godel_loglattice_approximation_log_error_set w)

/-- Rewriting the two-prime ledger value through its log-lattice coordinate turns the logarithmic
approximation term into the absolute distance to the lattice point, and the infimum of the error
set is exactly the distance-to-lattice quantity.
    prop:conclusion-jg-godel-loglattice-approximation -/
theorem paper_conclusion_jg_godel_loglattice_approximation
    (w : conclusion_jg_godel_loglattice_approximation_witness) :
    conclusion_jg_godel_loglattice_approximation_statement w := by
  refine ⟨rfl, ?_, ?_, ?_, rfl⟩
  · refine ⟨(w.left_index, w.right_index), ?_⟩
    simp [conclusion_jg_godel_loglattice_approximation_log_lattice_point]
  · simp [conclusion_jg_godel_loglattice_approximation_ledger_value,
      conclusion_jg_godel_loglattice_approximation_log_lattice_point, abs_sub_comm]
  · refine ⟨(w.left_index, w.right_index), ?_⟩
    simp [conclusion_jg_godel_loglattice_approximation_log_lattice_point]

end

end Omega.Conclusion
