import Mathlib.Tactic
import Omega.Conclusion.HypercubePhaseGridDense
import Omega.Conclusion.JgSlitUniformizationOrthogonalCoordinates
import Omega.Conclusion.TwoPrimeDenseOrbitHyperbolaLeaf

namespace Omega.Conclusion

noncomputable section

/-- Log-radius coordinate sampled from the two-prime logarithmic lattice. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_log_radius (mn : ℤ × ℤ) : ℝ :=
  (mn.1 : ℝ) * Real.log (2 : ℝ) + (mn.2 : ℝ) * Real.log (3 : ℝ)

/-- Phase coordinate sampled from the hypercube phase grid. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_phase (d : ℕ) (k : Fin (d + 1)) : ℝ :=
  Real.arccos (1 - 2 * (k : ℝ) / (d + 1))

/-- The slit-plane chart written in the orthogonal Joukowsky coordinates. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_chart (u θ : ℝ) : ℂ :=
  Complex.mk (2 * Real.cosh u * Real.cos θ) (2 * Real.sinh u * Real.sin θ)

/-- Sample points obtained by combining the two-prime log-radius lattice with the hypercube
phase grid and evaluating the slit-plane chart. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_point
    (mn : ℤ × ℤ) (d : ℕ) (k : Fin (d + 1)) : ℂ :=
  conclusion_jg_godel_hypercube_dense_sampling_omega_chart
    (conclusion_jg_godel_hypercube_dense_sampling_omega_log_radius mn)
    (conclusion_jg_godel_hypercube_dense_sampling_omega_phase d k)

/-- The concrete sampled subset of the slit plane. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_samples : Set ℂ :=
  Set.range fun p : (ℤ × ℤ) × Σ d : ℕ, Fin (d + 1) =>
    conclusion_jg_godel_hypercube_dense_sampling_omega_point p.1 p.2.1 p.2.2

/-- Paper-facing packaging of the two-prime radial lattice, the hypercube phase grid, and the
orthogonal Joukowsky slit chart used for dense sampling on the slit plane. -/
def conclusion_jg_godel_hypercube_dense_sampling_omega_statement : Prop :=
  conclusion_jg_godel_hypercube_dense_sampling_omega_samples.Nonempty ∧
    conclusion_two_prime_dense_orbit_hyperbola_leaf_statement ∧
    (∀ a b : ℝ, 0 ≤ a → b ≤ Real.pi → a < b →
      ∃ d k : ℕ,
        1 ≤ d ∧
          k ≤ d ∧
            a < Real.arccos (1 - 2 * (k : ℝ) / d) ∧
              Real.arccos (1 - 2 * (k : ℝ) / d) < b) ∧
    ∀ u θ : ℝ,
      0 < u →
        Real.sin θ ≠ 0 →
          Real.cos θ ≠ 0 →
            conclusion_jg_slit_uniformization_orthogonal_coordinates_w u θ =
              conclusion_jg_godel_hypercube_dense_sampling_omega_chart u θ

/-- Paper label: `thm:conclusion-jg-godel-hypercube-dense-sampling-omega`. The sampled slit-plane
set is concretely generated by the two-prime radial lattice and the hypercube phase grid, while
the existing dense-orbit, dense-phase, and slit-chart theorems supply the paper-facing package.
-/
theorem paper_conclusion_jg_godel_hypercube_dense_sampling_omega :
    conclusion_jg_godel_hypercube_dense_sampling_omega_statement := by
  refine ⟨?_, paper_conclusion_two_prime_dense_orbit_hyperbola_leaf,
    paper_conclusion_hypercube_phase_grid_dense, ?_⟩
  · change ∃ w : ℂ, w ∈ conclusion_jg_godel_hypercube_dense_sampling_omega_samples
    refine ⟨conclusion_jg_godel_hypercube_dense_sampling_omega_point (0, 0) 0 ⟨0, by simp⟩, ?_⟩
    refine ⟨((0, 0), ⟨0, ⟨0, by simp⟩⟩), rfl⟩
  · intro u θ hu hsin hcos
    exact (paper_conclusion_jg_slit_uniformization_orthogonal_coordinates u θ hu hsin hcos).1

end

end Omega.Conclusion
