import Mathlib.GroupTheory.Perm.Basic
import Mathlib.Tactic

namespace Omega.Conclusion

/-- Ordered off-diagonal pairs in a `4`-element set. The paper's ordered pair `(1, 2)` is encoded
here as `(0, 1)` using Lean's `Fin 4` indexing. -/
abbrev OrderedDistinctPair4 := {p : Fin 4 × Fin 4 // p.1 ≠ p.2}

/-- The distinguished ordered off-diagonal pair. -/
def offDiagonalBasePair : OrderedDistinctPair4 := ⟨(0, 1), by decide⟩

/-- The natural `S₄`-action on ordered distinct pairs. -/
def permuteOrderedDistinctPair (σ : Equiv.Perm (Fin 4)) (p : OrderedDistinctPair4) :
    OrderedDistinctPair4 :=
  ⟨(σ p.1.1, σ p.1.2), by
    intro h
    exact p.2 (σ.injective h)⟩

/-- Stabilizer of the ordered off-diagonal pair. -/
def offDiagonalPairStabilizer (σ : Equiv.Perm (Fin 4)) : Prop :=
  permuteOrderedDistinctPair σ offDiagonalBasePair = offDiagonalBasePair

/-- The transposition exchanging the two coordinates complementary to `(0, 1)`. -/
def offDiagonalTransposition : Equiv.Perm (Fin 4) := Equiv.swap 2 3

/-- The order-two subgroup generated by the complementary transposition. -/
def offDiagonalTranspositionQuotient (σ : Equiv.Perm (Fin 4)) : Prop :=
  σ = 1 ∨ σ = offDiagonalTransposition

/-- The off-diagonal self-fiber stabilizer is exactly the transposition subgroup on the complementary
coordinates, so the quotient cover has degree `2`.
    prop:conclusion-leyang-offdiagonal-transposition-quotient -/
theorem paper_conclusion_leyang_offdiagonal_transposition_quotient :
    (∀ σ : Equiv.Perm (Fin 4),
      offDiagonalPairStabilizer σ ↔ offDiagonalTranspositionQuotient σ) ∧
    (1 : Equiv.Perm (Fin 4)) ≠ offDiagonalTransposition := by
  constructor
  · intro σ
    constructor
    · intro hσ
      simp [offDiagonalPairStabilizer, offDiagonalTranspositionQuotient, offDiagonalTransposition,
        permuteOrderedDistinctPair, offDiagonalBasePair] at hσ ⊢
      rcases hσ with ⟨h0, h1⟩
      have h2 : σ 2 = (2 : Fin 4) ∨ σ 2 = (3 : Fin 4) := by
        have hs2lt : (σ 2 : ℕ) < 4 := (σ 2).2
        interval_cases hs2 : (σ 2 : ℕ)
        · exfalso
          exact (by decide : (2 : Fin 4) ≠ 0) (σ.injective ((Fin.ext hs2).trans h0.symm))
        · exfalso
          exact (by decide : (2 : Fin 4) ≠ 1) (σ.injective ((Fin.ext hs2).trans h1.symm))
        · exact Or.inl (Fin.ext hs2)
        · exact Or.inr (Fin.ext hs2)
      rcases h2 with h2 | h2
      · left
        apply Equiv.Perm.ext
        intro i
        fin_cases i
        · simpa using h0
        · simpa using h1
        · simpa using h2
        · have h3 : σ 3 = (3 : Fin 4) := by
            have hs3lt : (σ 3 : ℕ) < 4 := (σ 3).2
            interval_cases hs3 : (σ 3 : ℕ)
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 0) (σ.injective ((Fin.ext hs3).trans h0.symm))
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 1) (σ.injective ((Fin.ext hs3).trans h1.symm))
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 2) (σ.injective ((Fin.ext hs3).trans h2.symm))
            · exact Fin.ext hs3
          simpa using h3
      · right
        apply Equiv.Perm.ext
        intro i
        fin_cases i
        · simpa [offDiagonalTransposition] using h0
        · simpa [offDiagonalTransposition] using h1
        · simpa [offDiagonalTransposition] using h2
        · have h3 : σ 3 = (2 : Fin 4) := by
            have hs3lt : (σ 3 : ℕ) < 4 := (σ 3).2
            interval_cases hs3 : (σ 3 : ℕ)
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 0) (σ.injective ((Fin.ext hs3).trans h0.symm))
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 1) (σ.injective ((Fin.ext hs3).trans h1.symm))
            · exact Fin.ext hs3
            · exfalso
              exact (by decide : (3 : Fin 4) ≠ 2) (σ.injective ((Fin.ext hs3).trans h2.symm))
          simpa [offDiagonalTransposition] using h3
    · intro hσ
      rcases hσ with hσ | hσ
      · subst hσ
        simp [offDiagonalPairStabilizer, permuteOrderedDistinctPair, offDiagonalBasePair]
      · subst hσ
        simp [offDiagonalPairStabilizer, offDiagonalTransposition, permuteOrderedDistinctPair,
          offDiagonalBasePair]
        constructor <;> decide
  · intro h
    have h' := congrArg (fun τ : Equiv.Perm (Fin 4) => τ 2) h
    simp [offDiagonalTransposition] at h'

/-- The boundary second-moment identity determines the point count and therefore the Frobenius
trace of `D`.
    cor:conclusion-leyang-boundary-second-moment-trace-readout -/
theorem paper_conclusion_leyang_boundary_second_moment_trace_readout (p aE Mp ram : ℤ) :
    ∃! data : ℤ × ℤ, Mp = data.1 - ram + aE ∧ data.2 = p + 1 - data.1 := by
  refine ⟨(Mp + ram - aE, p + 1 - (Mp + ram - aE)), ?_, ?_⟩
  · constructor <;> ring
  · intro data hdata
    rcases hdata with ⟨hMp, htrace⟩
    apply Prod.ext
    · linarith
    · linarith

end Omega.Conclusion
