import Mathlib.Tactic

namespace Omega.Conclusion

/-- The three conjugacy classes of `S₃`, represented by their Lee--Yang splitting types. -/
inductive conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class
  | identity
  | transposition
  | threeCycle
  deriving DecidableEq, Fintype, Repr

open conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class

/-- The finite probability table coming from the class sizes in `S₃`. -/
noncomputable def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob :
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class → ℝ
  | identity => (1 : ℝ) / 6
  | transposition => (1 : ℝ) / 2
  | threeCycle => (1 : ℝ) / 3

/-- The sign character on the three Lee--Yang Frobenius classes. -/
def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_sign :
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class → ℤ
  | identity => 1
  | transposition => -1
  | threeCycle => 1

/-- A constant model of the independent discriminant sign `χ₁₀`. -/
def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_chi10
    (_c :
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class) :
    ℤ :=
  1

/-- The joint quadratic shadow generated by `χ₁₀` and the Lee--Yang sign character. -/
def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_shadow
    (c :
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class) :
    ℤ × ℤ :=
  (conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_chi10 c,
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_sign c)

/-- The total probability of the positive Lee--Yang sign fiber. -/
noncomputable def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass :
    ℝ :=
  conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob identity +
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob threeCycle

/-- The total probability of the negative Lee--Yang sign fiber. -/
noncomputable def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_negative_mass :
    ℝ :=
  conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob transposition

/-- Conditional distribution on the positive Lee--Yang sign fiber. -/
noncomputable def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond :
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class → ℝ
  | identity =>
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob identity /
        conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass
  | transposition => 0
  | threeCycle =>
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob threeCycle /
        conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass

/-- Binary Shannon entropy of the remaining positive-sign two-class distribution. -/
noncomputable def
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_binary_entropy :
    ℝ :=
  -(1 / 3 : ℝ) * Real.log (1 / 3 : ℝ) -
    (2 / 3 : ℝ) * Real.log (2 / 3 : ℝ)

/-- The exact conditional entropy after adjoining both quadratic shadows. -/
noncomputable def
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_conditional_entropy :
    ℝ :=
  (1 / 2 : ℝ) *
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_binary_entropy

/-- Concrete non-measurability of the three-class variable with respect to the two quadratic
shadows: no decoder from the shadow values recovers the class on all three atoms. -/
def conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_not_measurable :
    Prop :=
  ¬ ∃ decode :
      ℤ × ℤ →
        conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_class,
      ∀ c,
        decode
            (conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_shadow c) =
          c

/-- Concrete statement for the finite `S₃` table, the positive-sign conditional distribution, the
exact residual entropy, and the resulting non-measurability. -/
noncomputable def
    paper_conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_statement :
    Prop :=
  conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob identity =
      (1 : ℝ) / 6 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob
        transposition =
      (1 : ℝ) / 2 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob threeCycle =
      (1 : ℝ) / 3 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass =
      (1 : ℝ) / 2 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_negative_mass =
      (1 : ℝ) / 2 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond
        identity =
      (1 : ℝ) / 3 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond
        transposition =
      0 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond
        threeCycle =
      (2 : ℝ) / 3 ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_conditional_entropy =
      (1 / 2 : ℝ) *
        (-(1 / 3 : ℝ) * Real.log (1 / 3 : ℝ) -
          (2 / 3 : ℝ) * Real.log (2 / 3 : ℝ)) ∧
    0 <
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_conditional_entropy ∧
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_not_measurable

lemma conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive :
    0 <
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_conditional_entropy := by
  have hlog13 : Real.log (1 / 3 : ℝ) < 0 := by
    exact Real.log_neg (by norm_num) (by norm_num)
  have hlog23 : Real.log (2 / 3 : ℝ) < 0 := by
    exact Real.log_neg (by norm_num) (by norm_num)
  have hterm13 : 0 < -(1 / 3 : ℝ) * Real.log (1 / 3 : ℝ) := by
    exact mul_pos_of_neg_of_neg (by norm_num) hlog13
  have hterm23 : 0 < -(2 / 3 : ℝ) * Real.log (2 / 3 : ℝ) := by
    exact mul_pos_of_neg_of_neg (by norm_num) hlog23
  unfold conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_conditional_entropy
  unfold conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_binary_entropy
  nlinarith

lemma conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_nonmeasurable :
    conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_not_measurable := by
  rintro ⟨decode, hdecode⟩
  have hid :
      decode (1, 1) = identity := by
    simpa [conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_shadow,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_chi10,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_sign] using
      hdecode identity
  have hthree :
      decode (1, 1) = threeCycle := by
    simpa [conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_shadow,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_chi10,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_sign] using
      hdecode threeCycle
  exact noConfusion (hid.symm.trans hthree)

/-- Paper label:
`thm:conclusion-leyang-quadratic-shadows-incomplete-with-exact-conditional-entropy`. -/
theorem paper_conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy :
    paper_conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_statement := by
  unfold paper_conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_statement
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · rfl
  · rfl
  · rfl
  · norm_num [
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob]
  · norm_num [
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_negative_mass,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob]
  · norm_num [
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob]
  · rfl
  · norm_num [
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_cond,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive_mass,
      conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_prob]
  · rfl
  · exact conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_positive
  · exact conclusion_leyang_quadratic_shadows_incomplete_with_exact_conditional_entropy_nonmeasurable

end Omega.Conclusion
