import Mathlib.Tactic
import Omega.Conclusion.M2Level3Delta0RamificationSplitting

namespace Omega.Conclusion

/-- The unique Klingen line generated by the vanishing direction of the `Δ₀` transvection. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_line := Fin 1

/-- The remaining unramified Klingen lines inside `v⊥`. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines :=
  Fin 12

/-- The Klingen lines lying in `3`-cycle orbits. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_lines := Fin 9

/-- Above the special line, all four flag lifts stay relatively unramified. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_relative_unramified
    := Fin 4

/-- Above an ordinary `1`-cycle line there is one relatively unramified flag component. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_unramified
    := Fin 1

/-- Above an ordinary `1`-cycle line the remaining three lifts form one relative `3`-cycle. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_three_cycle
    := Fin 1

/-- Above a Klingen `3`-cycle line there are four relatively unramified flag components. -/
abbrev conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_relative_unramified
    := Fin 4

/-- Concrete `Δ₀` splitting package for the forgetful map from flags to Klingen lines. -/
def conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_statement : Prop :=
  Fintype.card conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_line = 1 ∧
    Fintype.card
        conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines =
      12 ∧
    Fintype.card
        conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_lines =
      9 ∧
    Fintype.card conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_line +
        Fintype.card
          conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines =
      delta0ProjectiveOneCycles ∧
    Fintype.card conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_lines =
      delta0ProjectiveThreeCycles ∧
    Fintype.card
        conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_relative_unramified =
      4 ∧
    Fintype.card
        conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_unramified +
          3 *
            Fintype.card
              conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_three_cycle =
        4 ∧
    Fintype.card
        conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_relative_unramified =
      4 ∧
    Fintype.card
          conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_relative_unramified *
          Fintype.card conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_line +
        Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_unramified *
          Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines =
      delta0FlagOneCycles ∧
    Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_three_cycle *
          Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines +
        Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_relative_unramified *
          Fintype.card
            conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_lines =
      delta0FlagThreeCycles ∧
    (Fintype.card
          conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_relative_unramified *
        Fintype.card conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_special_line +
      Fintype.card
          conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_unramified *
        Fintype.card
          conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines) +
        3 *
          (Fintype.card
                conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_relative_three_cycle *
              Fintype.card
                conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_other_one_cycle_lines +
            Fintype.card
                conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_relative_unramified *
              Fintype.card
                conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_three_cycle_lines) =
      delta0FlagTotalObjects

/-- Paper label: `thm:conclusion-m2-level3-flag-over-klingen-delta0-refined-splitting`. -/
theorem paper_conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting :
    conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_statement := by
  rcases paper_conclusion_m2_level3_delta0_ramification_splitting with
    ⟨hProjOne, hProjThree, _, _, hFlagOne, hFlagThree, _, _⟩
  unfold conclusion_m2_level3_flag_over_klingen_delta0_refined_splitting_statement
  rw [hProjOne, hProjThree, hFlagOne, hFlagThree]
  native_decide

end Omega.Conclusion
