import Mathlib.Tactic
import Omega.Conclusion.PrimeLogRhOperatorCountablePrimeRank

namespace Omega.Conclusion

/-- Integer translates of one normalized critical phase for the finite-comb obstruction. -/
def conclusion_prime_log_finite_rank_congruence_twist_class_nogo_translate
    (θ : ℝ) : Set ℝ :=
  {u | ∃ n : ℤ, u = θ + n}

/-- The finite-comb closure generated by finitely many normalized critical phases. -/
def conclusion_prime_log_finite_rank_congruence_twist_class_nogo_comb
    (criticalPhases : Finset ℝ) : Set ℝ :=
  {u | ∃ θ ∈ criticalPhases,
    u ∈ conclusion_prime_log_finite_rank_congruence_twist_class_nogo_translate θ}

/-- Concrete finite-comb certificate used by the no-go wrapper. -/
def conclusion_prime_log_finite_rank_congruence_twist_class_nogo_finiteCombStatement
    (criticalPhases : Finset ℝ) : Prop :=
  ∀ u : ℝ,
    u ∈ conclusion_prime_log_finite_rank_congruence_twist_class_nogo_comb criticalPhases ↔
      ∃ θ ∈ criticalPhases, ∃ n : ℤ, u = θ + n

/-- Abstract finite-rank congruence-twist closure class, recorded by concrete finite-comb
ordinates, a prime-log necessity predicate, and a missing-prime-log obstruction. -/
def conclusion_prime_log_finite_rank_congruence_twist_class_nogo_closedClass
    (Carrier : Type*) (criticalPhases : Finset ℝ) (ordinate : Carrier → ℝ)
    (carriesPrimeLog satisfiesRHGate finiteRankVisible : Carrier → Prop) : Prop :=
  (∀ K, finiteRankVisible K →
      ordinate K ∈
        conclusion_prime_log_finite_rank_congruence_twist_class_nogo_comb criticalPhases) ∧
    (∀ K, satisfiesRHGate K → carriesPrimeLog K) ∧
      (∀ K, finiteRankVisible K → ¬ carriesPrimeLog K)

/-- Concrete no-go statement combining finite-comb rigidity, congruence-kernel failure, and the
countably infinite prime-rank obstruction. -/
def conclusion_prime_log_finite_rank_congruence_twist_class_nogo_statement : Prop :=
  ∀ (Carrier : Type*) (criticalPhases : Finset ℝ) (ordinate : Carrier → ℝ)
    (carriesPrimeLog satisfiesRHGate finiteRankVisible : Carrier → Prop),
    conclusion_prime_log_finite_rank_congruence_twist_class_nogo_closedClass
        Carrier criticalPhases ordinate carriesPrimeLog satisfiesRHGate finiteRankVisible →
      conclusion_prime_log_finite_rank_congruence_twist_class_nogo_finiteCombStatement
          criticalPhases ∧
        (∀ K, finiteRankVisible K → ¬ satisfiesRHGate K) ∧
          (∀ D : conclusion_prime_log_rh_operator_countable_prime_rank_data,
            ¬ D.hasFiniteRankFaithfulModel)

/-- Paper label: `thm:conclusion-prime-log-finite-rank-congruence-twist-class-nogo`. -/
theorem paper_conclusion_prime_log_finite_rank_congruence_twist_class_nogo :
    conclusion_prime_log_finite_rank_congruence_twist_class_nogo_statement := by
  intro Carrier criticalPhases ordinate carriesPrimeLog satisfiesRHGate finiteRankVisible hclass
  refine ⟨?_, ?_, ?_⟩
  · intro u
    simp [conclusion_prime_log_finite_rank_congruence_twist_class_nogo_comb,
      conclusion_prime_log_finite_rank_congruence_twist_class_nogo_translate]
  · intro K hvisible hgate
    exact hclass.2.2 K hvisible (hclass.2.1 K hgate)
  · intro D
    exact (paper_conclusion_prime_log_rh_operator_countable_prime_rank D).2.2

end Omega.Conclusion
