import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic

namespace Omega.Conclusion

open Matrix

noncomputable section

/-- A finitely supported prime-exponent ledger on the single audited prime `2`. -/
abbrev conclusion_qpos_sqrtp_phase_injection_ledger :=
  Fin 1 → ℤ

/-- The audited prime ledger used in the one-prime phase model. -/
def conclusion_qpos_sqrtp_phase_injection_prime (_i : Fin 1) : ℕ :=
  2

/-- Lift the prime-exponent ledger to the real phase coordinate generated by `√2`. -/
def conclusion_qpos_sqrtp_phase_injection_phase
    (e : conclusion_qpos_sqrtp_phase_injection_ledger) : ℝ :=
  ∑ i : Fin 1, (e i : ℝ) * Real.sqrt (conclusion_qpos_sqrtp_phase_injection_prime i)

/-- Multiplication of positive rationals corresponds to addition of prime exponents in the ledger.
-/
theorem conclusion_qpos_sqrtp_phase_injection_phase_add
    (e e' : conclusion_qpos_sqrtp_phase_injection_ledger) :
    conclusion_qpos_sqrtp_phase_injection_phase (e + e') =
      conclusion_qpos_sqrtp_phase_injection_phase e +
        conclusion_qpos_sqrtp_phase_injection_phase e' := by
  simp [conclusion_qpos_sqrtp_phase_injection_phase]
  ring

/-- The `√2` phase coordinate is nonzero, so the one-prime ledger is read off uniquely. -/
theorem conclusion_qpos_sqrtp_phase_injection_phase_injective :
    Function.Injective conclusion_qpos_sqrtp_phase_injection_phase := by
  intro e e' hphase
  funext i
  fin_cases i
  have hsqrt_ne : (Real.sqrt (conclusion_qpos_sqrtp_phase_injection_prime 0 : ℕ)) ≠ 0 := by
    dsimp [conclusion_qpos_sqrtp_phase_injection_prime]
    positivity
  have hcoord :
      (e 0 : ℝ) * Real.sqrt (conclusion_qpos_sqrtp_phase_injection_prime 0 : ℕ) =
        (e' 0 : ℝ) * Real.sqrt (conclusion_qpos_sqrtp_phase_injection_prime 0 : ℕ) := by
    simpa [conclusion_qpos_sqrtp_phase_injection_phase] using hphase
  have hcoeff : (e 0 : ℝ) = (e' 0 : ℝ) := by
    exact mul_right_cancel₀ hsqrt_ne hcoord
  exact_mod_cast hcoeff

/-- Paper label: `prop:conclusion-qpos-sqrtp-phase-injection`. In the concrete one-prime ledger
model, exponent addition makes the `√2` phase map a homomorphism, and the nonzero generator
`√2` makes that phase map injective. -/
theorem paper_conclusion_qpos_sqrtp_phase_injection :
    (∀ e e' : conclusion_qpos_sqrtp_phase_injection_ledger,
      conclusion_qpos_sqrtp_phase_injection_phase (e + e') =
        conclusion_qpos_sqrtp_phase_injection_phase e +
          conclusion_qpos_sqrtp_phase_injection_phase e') ∧
      Function.Injective conclusion_qpos_sqrtp_phase_injection_phase := by
  exact ⟨conclusion_qpos_sqrtp_phase_injection_phase_add,
    conclusion_qpos_sqrtp_phase_injection_phase_injective⟩

end

end Omega.Conclusion
