import Mathlib.NumberTheory.Real.Irrational
import Mathlib.Tactic

namespace Omega.Conclusion

/-- The specialized primitive atom equation at `u = 5`, written over the real comparison field. -/
noncomputable def conclusion_realinput40_primitive_atom_q5_field_break_atom (z : ℝ) : ℝ :=
  1 - 5 * z ^ 2

/-- The positive root supplied after adjoining `sqrt 5`. -/
noncomputable def conclusion_realinput40_primitive_atom_q5_field_break_positive_root : ℝ :=
  1 / Real.sqrt 5

/-- The negative root supplied after adjoining `sqrt 5`. -/
noncomputable def conclusion_realinput40_primitive_atom_q5_field_break_negative_root : ℝ :=
  -(1 / Real.sqrt 5)

/-- The base field obstruction is represented by the absence of a rational copy of `sqrt 5`. -/
def conclusion_realinput40_primitive_atom_q5_field_break_base_lacks_sqrt5 : Prop :=
  ¬ ∃ q : ℚ, (q : ℝ) = Real.sqrt 5

/-- The quadratic extension generated by `sqrt 5` supplies the two atom roots. -/
def conclusion_realinput40_primitive_atom_q5_field_break_extension_supplies_roots : Prop :=
  conclusion_realinput40_primitive_atom_q5_field_break_atom
      conclusion_realinput40_primitive_atom_q5_field_break_positive_root = 0 ∧
    conclusion_realinput40_primitive_atom_q5_field_break_atom
      conclusion_realinput40_primitive_atom_q5_field_break_negative_root = 0 ∧
    conclusion_realinput40_primitive_atom_q5_field_break_positive_root ≠
      conclusion_realinput40_primitive_atom_q5_field_break_negative_root

/-- Paper-facing local-field certificate for
`thm:conclusion-realinput40-primitive-atom-q5-field-break`. -/
def conclusion_realinput40_primitive_atom_q5_field_break_statement : Prop :=
  conclusion_realinput40_primitive_atom_q5_field_break_base_lacks_sqrt5 ∧
    conclusion_realinput40_primitive_atom_q5_field_break_extension_supplies_roots

theorem conclusion_realinput40_primitive_atom_q5_field_break_base_certificate :
    conclusion_realinput40_primitive_atom_q5_field_break_base_lacks_sqrt5 := by
  rintro ⟨q, hq⟩
  have hsqrt5_irr : Irrational (Real.sqrt 5) :=
    Nat.Prime.irrational_sqrt (show Nat.Prime 5 by norm_num)
  exact hsqrt5_irr.ne_rat q hq.symm

theorem conclusion_realinput40_primitive_atom_q5_field_break_roots_certificate :
    conclusion_realinput40_primitive_atom_q5_field_break_extension_supplies_roots := by
  have hsqrt_ne : (Real.sqrt 5 : ℝ) ≠ 0 := by positivity
  have hsqrt_sq : (Real.sqrt 5 : ℝ) ^ 2 = 5 := Real.sq_sqrt (by positivity)
  refine ⟨?_, ?_, ?_⟩
  · unfold conclusion_realinput40_primitive_atom_q5_field_break_atom
      conclusion_realinput40_primitive_atom_q5_field_break_positive_root
    field_simp [hsqrt_ne]
    rw [hsqrt_sq]
    norm_num
  · unfold conclusion_realinput40_primitive_atom_q5_field_break_atom
      conclusion_realinput40_primitive_atom_q5_field_break_negative_root
    field_simp [hsqrt_ne]
    rw [hsqrt_sq]
    norm_num
  · unfold conclusion_realinput40_primitive_atom_q5_field_break_positive_root
      conclusion_realinput40_primitive_atom_q5_field_break_negative_root
    have hpos : 0 < (1 / Real.sqrt 5 : ℝ) := by positivity
    have hneg : (-(1 / Real.sqrt 5) : ℝ) < 0 := by linarith
    exact ne_of_gt (lt_trans hneg hpos)

/-- Paper label: `thm:conclusion-realinput40-primitive-atom-q5-field-break`. -/
theorem paper_conclusion_realinput40_primitive_atom_q5_field_break :
    conclusion_realinput40_primitive_atom_q5_field_break_statement := by
  exact
    ⟨conclusion_realinput40_primitive_atom_q5_field_break_base_certificate,
      conclusion_realinput40_primitive_atom_q5_field_break_roots_certificate⟩

end Omega.Conclusion
