import Mathlib.Tactic
import Omega.Folding.KilloS4Genus49JacobianComputableIsogeny

namespace Omega.Conclusion

/-- The conjugacy-class subgroup quotients recorded in the `S₄` Hurwitz Jacobian tower. -/
inductive conclusion_s4_hurwitz_jacobian_four_generator_semiring_subgroup
  | s4
  | a4
  | d8
  | s3
  | c4
  | v4
  | c3
  | c2
  | one
  deriving DecidableEq

/-- Exponent vector in the semiring generated by `(J(H), J(Z), J(CF), P)`. -/
abbrev conclusion_s4_hurwitz_jacobian_four_generator_semiring_vector := ℕ × ℕ × ℕ × ℕ

/-- The explicit semiring coordinates of each quotient Jacobian. -/
def conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector :
    conclusion_s4_hurwitz_jacobian_four_generator_semiring_subgroup →
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_vector
  | .s4 => (0, 0, 0, 0)
  | .a4 => (1, 0, 0, 0)
  | .d8 => (0, 1, 0, 0)
  | .s3 => (0, 0, 1, 0)
  | .c4 => (0, 1, 0, 1)
  | .v4 => (1, 2, 0, 0)
  | .c3 => (1, 0, 1, 1)
  | .c2 => (0, 1, 2, 1)
  | .one => (1, 2, 3, 3)

/-- The Jacobian dimension attached to one exponent vector, using the audited generator
dimensions `(5, 4, 3, 9)`. -/
def conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension
    (U : conclusion_s4_hurwitz_jacobian_four_generator_semiring_subgroup) : ℕ :=
  let (a, b, c, d) := conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector U
  5 * a + 4 * b + 3 * c + 9 * d

/-- Paper label: `thm:conclusion-s4-hurwitz-jacobian-four-generator-semiring`.
The audited genus-`49` decomposition has generator dimensions `[5, 4, 3, 9]` and multiplicities
`[1, 2, 3, 3]`. Every standard quotient Jacobian is therefore represented by an explicit exponent
vector in the semiring generated by `(J(H), J(Z), J(CF), P)`. -/
theorem paper_conclusion_s4_hurwitz_jacobian_four_generator_semiring
    (Q : Polynomial ℚ) :
    Omega.Folding.killo_s4_genus49_jacobian_computable_isogeny_factor_dimensions = [5, 4, 3, 9] ∧
      Omega.Folding.killo_s4_genus49_jacobian_computable_isogeny_factor_multiplicities =
        [1, 2, 3, 3] ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .s4 = (0, 0, 0, 0) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .a4 = (1, 0, 0, 0) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .d8 = (0, 1, 0, 0) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .s3 = (0, 0, 1, 0) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .c4 = (0, 1, 0, 1) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .v4 = (1, 2, 0, 0) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .c3 = (1, 0, 1, 1) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .c2 = (0, 1, 2, 1) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector .one = (1, 2, 3, 3) ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .s4 = 0 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .a4 = 5 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .d8 = 4 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .s3 = 3 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .c4 = 13 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .v4 = 13 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .c3 = 17 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .c2 = 19 ∧
      conclusion_s4_hurwitz_jacobian_four_generator_semiring_quotient_dimension .one = 49 ∧
      ∀ U : conclusion_s4_hurwitz_jacobian_four_generator_semiring_subgroup,
        ∃ a b c d,
          conclusion_s4_hurwitz_jacobian_four_generator_semiring_exponent_vector U = (a, b, c, d) := by
  rcases Omega.Folding.paper_killo_s4_genus49_jacobian_computable_isogeny Q with
    ⟨_, _, _, hdim, hmult, htotal, _, _, _, _⟩
  refine ⟨hdim, hmult, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, ?_, ?_, ?_, ?_, ?_, ?_, ?_,
    ?_, ?_, ?_⟩
  · decide
  · decide
  · decide
  · decide
  · decide
  · decide
  · decide
  · decide
  · decide
  · intro U
    cases U <;> exact ⟨_, _, _, _, rfl⟩

end Omega.Conclusion
