import Mathlib.Data.Finset.Card
import Mathlib.Data.Real.Basic

namespace Omega.Conclusion

/-- Finite basis model for the free part of the restriction image of extendable boundary classes. -/
def stokesExtensionImage {α : Type*} (L : Finset α) : Finset α := L

/-- Boundary pairing restricted to the extension image. -/
def stokesExtensionPairing {α : Type*} (ω : α → α → ℝ) : α → α → ℝ := ω

/-- The extension image is isotropic when every pair of extendable classes has zero boundary
pairing. -/
def stokesExtensionIsotropic {α : Type*} (ω : α → α → ℝ) (L : Finset α) : Prop :=
  ∀ x ∈ stokesExtensionImage L, ∀ y ∈ stokesExtensionImage L,
    stokesExtensionPairing ω x y = 0

/-- Circle-dimension proxy for the free lattice generated by the extendable boundary classes. -/
def stokesExtensionCdim {α : Type*} (L : Finset α) : Nat :=
  (stokesExtensionImage L).card

/-- Stokes vanishing makes the extension image isotropic, and any precomputed half-rank bound for
an even-dimensional symplectic boundary space translates directly into the `b / 2` estimate.
    prop:conclusion-stokes-extension-isotropic-half-rank -/
theorem paper_conclusion_stokes_extension_isotropic_half_rank
    {α : Type*} [DecidableEq α]
    (ω : α → α → ℝ) (L : Finset α) (b halfRank : Nat)
    (hStokes : ∀ x ∈ stokesExtensionImage L, ∀ y ∈ stokesExtensionImage L,
      stokesExtensionPairing ω x y = 0)
    (hb : b = 2 * halfRank)
    (hHalf : stokesExtensionCdim L ≤ halfRank) :
    stokesExtensionIsotropic ω L ∧ stokesExtensionCdim L ≤ b / 2 := by
  refine ⟨by simpa [stokesExtensionIsotropic] using hStokes, ?_⟩
  simpa [stokesExtensionCdim, hb] using hHalf

end Omega.Conclusion
