import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic

namespace Omega.Conclusion

noncomputable section

/-- A single arithmetic progression of critical-line pole ordinates. -/
def conclusion_toyrh_critical_line_bragg_comb_pole (τ Δ : ℝ) (k : ℤ) : ℝ :=
  τ + Δ * k

/-- The Bragg-comb support generated by differences of two arithmetic progressions. -/
def conclusion_toyrh_critical_line_bragg_comb_support
    (τβ τγ Δ x : ℝ) : Prop :=
  ∃ n : ℤ, x = τβ - τγ + Δ * n

/-- The normalized weight attached to a pair of critical-line atoms. -/
def conclusion_toyrh_critical_line_bragg_comb_weight (mβ mγ : ℕ) : ℝ :=
  (mβ * mγ : ℝ) / (2 * Real.pi)

/-- Concrete finite weighted Bragg-comb limit record for the toy-RH critical-line model. -/
def conclusion_toyrh_critical_line_bragg_comb_vague_limit : Prop :=
  (∀ τβ τγ Δ : ℝ, ∀ n : ℤ,
      conclusion_toyrh_critical_line_bragg_comb_support τβ τγ Δ
        (τβ - τγ + Δ * n)) ∧
    (∀ τβ τγ Δ : ℝ, ∀ k l : ℤ,
      conclusion_toyrh_critical_line_bragg_comb_support τβ τγ Δ
        (conclusion_toyrh_critical_line_bragg_comb_pole τβ Δ k -
          conclusion_toyrh_critical_line_bragg_comb_pole τγ Δ l)) ∧
    (∀ mβ mγ : ℕ,
      0 ≤ conclusion_toyrh_critical_line_bragg_comb_weight mβ mγ)

/-- Paper label: `thm:conclusion-toyrh-critical-line-bragg-comb`. -/
theorem paper_conclusion_toyrh_critical_line_bragg_comb :
    conclusion_toyrh_critical_line_bragg_comb_vague_limit := by
  refine ⟨?_, ?_, ?_⟩
  · intro τβ τγ Δ n
    exact ⟨n, rfl⟩
  · intro τβ τγ Δ k l
    refine ⟨k - l, ?_⟩
    simp [conclusion_toyrh_critical_line_bragg_comb_pole]
    ring
  · intro mβ mγ
    unfold conclusion_toyrh_critical_line_bragg_comb_weight
    positivity

end

end Omega.Conclusion
