import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Tactic
import Omega.GU.GroupJGPrimeRegisterPhaseBohrDense

namespace Omega.Conclusion

noncomputable section

/-- The additive logarithmic lattice generated by the two prime scales `2` and `3`. -/
def conclusion_two_prime_dense_orbit_hyperbola_leaf_log_lattice : Set ℝ :=
  (AddSubgroup.closure {Real.log (2 : ℝ), Real.log (3 : ℝ)} : Set ℝ)

/-- Hyperbola-leaf parametrization written in logarithmic coordinates `x = log r`. -/
def conclusion_two_prime_dense_orbit_hyperbola_leaf_log_point (θ x : ℝ) : ℂ :=
  (Complex.exp (x : ℂ) + Complex.exp (-(x : ℂ))) * Complex.cos (θ : ℂ) +
    (Complex.exp (x : ℂ) - Complex.exp (-(x : ℂ))) * Complex.sin (θ : ℂ) * Complex.I

/-- The same leaf parametrization written directly with the radial variable `r > 0`. -/
def conclusion_two_prime_dense_orbit_hyperbola_leaf_radial_point (θ r : ℝ) : ℂ :=
  (((r + r⁻¹) * Real.cos θ : ℝ) : ℂ) + ((((r - r⁻¹) * Real.sin θ : ℝ) : ℂ) * Complex.I)

/-- Paper-facing two-prime dense-orbit package: the logarithmic subgroup generated by `log 2`
and `log 3` is dense in `ℝ`, and the standard hyperbola-leaf parametrization factors through the
positive-radius change of variables `r = exp x`. -/
def conclusion_two_prime_dense_orbit_hyperbola_leaf_statement : Prop :=
  Dense conclusion_two_prime_dense_orbit_hyperbola_leaf_log_lattice ∧
    ∀ θ : ℝ, Real.sin θ * Real.cos θ ≠ 0 →
      Continuous (conclusion_two_prime_dense_orbit_hyperbola_leaf_log_point θ) ∧
        ∀ x : ℝ,
          0 < Real.exp x ∧
            conclusion_two_prime_dense_orbit_hyperbola_leaf_log_point θ x =
              conclusion_two_prime_dense_orbit_hyperbola_leaf_radial_point θ (Real.exp x)

/-- Paper label: `prop:conclusion-two-prime-dense-orbit-hyperbola-leaf`. The existing
two-prime Bohr-density certificate gives density of the logarithmic scale lattice, and the
hyperbola-leaf parametrization is exactly the continuous transport of that dense set through
`r = exp x`. -/
theorem paper_conclusion_two_prime_dense_orbit_hyperbola_leaf :
    conclusion_two_prime_dense_orbit_hyperbola_leaf_statement := by
  refine ⟨?_, ?_⟩
  · simpa [Omega.GU.GroupJGPrimeRegisterPhaseData.phaseImageDense,
      conclusion_two_prime_dense_orbit_hyperbola_leaf_log_lattice] using
      Omega.GU.paper_group_jg_prime_register_phase_bohr_dense ⟨1, one_ne_zero⟩
  · intro θ _hθ
    refine ⟨?_, ?_⟩
    · simpa [conclusion_two_prime_dense_orbit_hyperbola_leaf_log_point] using
        (show Continuous (fun x : ℝ =>
          (Complex.exp (x : ℂ) + Complex.exp (-(x : ℂ))) * Complex.cos (θ : ℂ) +
            (Complex.exp (x : ℂ) - Complex.exp (-(x : ℂ))) *
              Complex.sin (θ : ℂ) * Complex.I) by
          continuity)
    · intro x
      refine ⟨Real.exp_pos x, ?_⟩
      simp [conclusion_two_prime_dense_orbit_hyperbola_leaf_log_point,
        conclusion_two_prime_dense_orbit_hyperbola_leaf_radial_point, Complex.exp_neg]

end

end Omega.Conclusion
