import Mathlib.Tactic

namespace Omega.Conclusion

/-- Integer coordinates in the basis
`e₁ ∧ e₂, e₁ ∧ e₃, e₂ ∧ e₃` of the exterior square. -/
abbrev conclusion_window6_exterior_shell_smith_geometry_triple := ℤ × ℤ × ℤ

/-- The full exterior lattice `Ω₄`. -/
def conclusion_window6_exterior_shell_smith_geometry_omega4
    (_x : conclusion_window6_exterior_shell_smith_geometry_triple) : Prop :=
  True

/-- The exterior lattice generated by `(1,0,1) ∧ (1,0,-1) = -2(e₁ ∧ e₃)`. -/
def conclusion_window6_exterior_shell_smith_geometry_omega3
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) : Prop :=
  ∃ a : ℤ, x = (0, -2 * a, 0)

/-- The primitive line description of `Ω₃`. -/
def conclusion_window6_exterior_shell_smith_geometry_omega3_line
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) : Prop :=
  ∃ a : ℤ, x = (0, 2 * a, 0)

/-- The three explicit wedge generators for `Ω₂`. -/
def conclusion_window6_exterior_shell_smith_geometry_omega2
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) : Prop :=
  ∃ a b c : ℤ, x = (-a - b, -a + b, -2 * c)

/-- Parity form of the `Ω₂` lattice. -/
def conclusion_window6_exterior_shell_smith_geometry_omega2_parity
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) : Prop :=
  (∃ k : ℤ, x.1 - x.2.1 = 2 * k) ∧ ∃ l : ℤ, x.2.2 = 2 * l

/-- Smith diagonal certified for `Ω₄`. -/
def conclusion_window6_exterior_shell_smith_geometry_smith_omega4 : List ℕ :=
  [1, 1, 1]

/-- Smith diagonal certified for `Ω₃`. -/
def conclusion_window6_exterior_shell_smith_geometry_smith_omega3 : List ℕ :=
  [2]

/-- Smith diagonal certified for `Ω₂`. -/
def conclusion_window6_exterior_shell_smith_geometry_smith_omega2 : List ℕ :=
  [1, 2, 2]

/-- Concrete gcd and determinant certificates for the three displayed Smith forms. -/
def conclusion_window6_exterior_shell_smith_geometry_smith_certificates : Prop :=
  Nat.gcd 1 (Nat.gcd 1 1) = 1 ∧
    Int.natAbs (-2 : ℤ) = 2 ∧
      Nat.gcd 1 (Nat.gcd 1 2) = 1 ∧
        Nat.gcd 2 (Nat.gcd 2 4) = 2 ∧
          Int.natAbs (4 : ℤ) = 4

/-- Paper-facing exterior-shell Smith geometry statement. -/
def conclusion_window6_exterior_shell_smith_geometry_statement : Prop :=
  (∀ x : conclusion_window6_exterior_shell_smith_geometry_triple,
      conclusion_window6_exterior_shell_smith_geometry_omega4 x ↔ True) ∧
    (∀ x : conclusion_window6_exterior_shell_smith_geometry_triple,
      conclusion_window6_exterior_shell_smith_geometry_omega3 x ↔
        conclusion_window6_exterior_shell_smith_geometry_omega3_line x) ∧
      (∀ x : conclusion_window6_exterior_shell_smith_geometry_triple,
        conclusion_window6_exterior_shell_smith_geometry_omega2 x ↔
          conclusion_window6_exterior_shell_smith_geometry_omega2_parity x) ∧
        conclusion_window6_exterior_shell_smith_geometry_smith_omega4 = [1, 1, 1] ∧
          conclusion_window6_exterior_shell_smith_geometry_smith_omega3 = [2] ∧
            conclusion_window6_exterior_shell_smith_geometry_smith_omega2 = [1, 2, 2] ∧
              conclusion_window6_exterior_shell_smith_geometry_smith_certificates

lemma conclusion_window6_exterior_shell_smith_geometry_omega3_iff_line
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) :
    conclusion_window6_exterior_shell_smith_geometry_omega3 x ↔
      conclusion_window6_exterior_shell_smith_geometry_omega3_line x := by
  constructor
  · rintro ⟨a, rfl⟩
    exact ⟨-a, by ring_nf⟩
  · rintro ⟨a, rfl⟩
    exact ⟨-a, by ring_nf⟩

lemma conclusion_window6_exterior_shell_smith_geometry_omega2_iff_parity
    (x : conclusion_window6_exterior_shell_smith_geometry_triple) :
    conclusion_window6_exterior_shell_smith_geometry_omega2 x ↔
      conclusion_window6_exterior_shell_smith_geometry_omega2_parity x := by
  constructor
  · rintro ⟨a, b, c, rfl⟩
    refine ⟨⟨-b, by ring_nf⟩, ⟨-c, by ring_nf⟩⟩
  · rcases x with ⟨u, v, w⟩
    rintro ⟨⟨k, hk⟩, ⟨l, hl⟩⟩
    refine ⟨-u + k, -k, -l, ?_⟩
    have hk' : u - v = 2 * k := by simpa using hk
    have hl' : w = 2 * l := by simpa using hl
    have hv : v = -(k * 2) + u := by omega
    have hw : w = 2 * l := hl'
    ext
    all_goals simp [hv, hw]
    all_goals ring_nf

/-- Paper label: `thm:conclusion-window6-exterior-shell-smith-geometry`. -/
theorem paper_conclusion_window6_exterior_shell_smith_geometry :
    conclusion_window6_exterior_shell_smith_geometry_statement := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro x
    simp [conclusion_window6_exterior_shell_smith_geometry_omega4]
  · exact conclusion_window6_exterior_shell_smith_geometry_omega3_iff_line
  · exact conclusion_window6_exterior_shell_smith_geometry_omega2_iff_parity
  · rfl
  · rfl
  · rfl
  · norm_num [conclusion_window6_exterior_shell_smith_geometry_smith_certificates]

end Omega.Conclusion
