import Mathlib.Tactic

namespace Omega.Conclusion

/-- The geometric averaging scalar on the three odd boundary generators. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_average
    (v : Fin 3 → ℚ) : ℚ :=
  (v 0 + v 1 + v 2) / 3

/-- The projector onto the diagonal synchronous direction. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_projector
    (v : Fin 3 → ℚ) : Fin 3 → ℚ :=
  fun _ => conclusion_window6_geometric_odd_operator_shadow_onedim_average v

/-- The projector-fixed vectors are exactly the synchronous odd sums. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_fixed
    (v : Fin 3 → ℚ) : Prop :=
  conclusion_window6_geometric_odd_operator_shadow_onedim_projector v = v

/-- The diagonal copy generated by one synchronous odd direction. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_diagonal
    (c : ℚ) : Fin 3 → ℚ :=
  fun _ => c

/-- Concrete statement of the diagonal-shadow identification. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_diagonalShadowFormula : Prop :=
  ∀ v : Fin 3 → ℚ,
    conclusion_window6_geometric_odd_operator_shadow_onedim_fixed v ↔
      ∃ c : ℚ, v = conclusion_window6_geometric_odd_operator_shadow_onedim_diagonal c

/-- The geometric shadow keeps one dimension. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_shadowDim : ℕ :=
  1

/-- The ambient odd sector has dimension `3`, so rank/nullity leaves quotient dimension `2`. -/
def conclusion_window6_geometric_odd_operator_shadow_onedim_quotientDim : ℕ :=
  Fintype.card (Fin 3) - conclusion_window6_geometric_odd_operator_shadow_onedim_shadowDim

lemma conclusion_window6_geometric_odd_operator_shadow_onedim_fixed_iff (v : Fin 3 → ℚ) :
    conclusion_window6_geometric_odd_operator_shadow_onedim_fixed v ↔
      ∃ c : ℚ, v = conclusion_window6_geometric_odd_operator_shadow_onedim_diagonal c := by
  constructor
  · intro h
    refine ⟨conclusion_window6_geometric_odd_operator_shadow_onedim_average v, ?_⟩
    funext i
    have hi := congrFun h i
    simpa [conclusion_window6_geometric_odd_operator_shadow_onedim_projector,
      conclusion_window6_geometric_odd_operator_shadow_onedim_diagonal,
      conclusion_window6_geometric_odd_operator_shadow_onedim_average] using hi.symm
  · rintro ⟨c, rfl⟩
    funext i
    have hthree : (3 : ℚ) ≠ 0 := by norm_num
    simp [conclusion_window6_geometric_odd_operator_shadow_onedim_projector,
      conclusion_window6_geometric_odd_operator_shadow_onedim_diagonal,
      conclusion_window6_geometric_odd_operator_shadow_onedim_average]
    field_simp [hthree]
    ring

/-- Paper label: `prop:conclusion-window6-geometric-odd-operator-shadow-onedim`. The three
one-dimensional odd generators average onto the diagonal synchronous copy, that fixed subspace has
dimension `1`, and rank/nullity leaves a `2`-dimensional quotient. -/
theorem paper_conclusion_window6_geometric_odd_operator_shadow_onedim :
    conclusion_window6_geometric_odd_operator_shadow_onedim_diagonalShadowFormula ∧
    conclusion_window6_geometric_odd_operator_shadow_onedim_shadowDim = 1 ∧
    conclusion_window6_geometric_odd_operator_shadow_onedim_quotientDim = 2 := by
  refine ⟨?_, rfl, ?_⟩
  · intro v
    exact conclusion_window6_geometric_odd_operator_shadow_onedim_fixed_iff v
  · norm_num [conclusion_window6_geometric_odd_operator_shadow_onedim_quotientDim,
      conclusion_window6_geometric_odd_operator_shadow_onedim_shadowDim]
