import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic

namespace Omega.Conclusion

open Finset
open scoped BigOperators

/-- The boundary character group `(\mathbb{Z}/2)^3`, written in coordinates. -/
structure Window6BoundaryCharacter where
  ε₁ : Bool
  ε₂ : Bool
  ε₃ : Bool
deriving DecidableEq, Fintype

/-- The cyclic `C₃` action by rotating coordinates. -/
def rotateBoundaryCharacter (χ : Window6BoundaryCharacter) : Window6BoundaryCharacter :=
  ⟨χ.ε₂, χ.ε₃, χ.ε₁⟩

/-- The orbit generated by the `C₃` rotation. -/
def boundaryCharacterOrbit (χ : Window6BoundaryCharacter) : Finset Window6BoundaryCharacter :=
  {χ, rotateBoundaryCharacter χ, rotateBoundaryCharacter (rotateBoundaryCharacter χ)}

def χ000 : Window6BoundaryCharacter := ⟨false, false, false⟩
def χ111 : Window6BoundaryCharacter := ⟨true, true, true⟩
def χ100 : Window6BoundaryCharacter := ⟨true, false, false⟩
def χ010 : Window6BoundaryCharacter := ⟨false, true, false⟩
def χ001 : Window6BoundaryCharacter := ⟨false, false, true⟩
def χ110 : Window6BoundaryCharacter := ⟨true, true, false⟩
def χ101 : Window6BoundaryCharacter := ⟨true, false, true⟩
def χ011 : Window6BoundaryCharacter := ⟨false, true, true⟩

/-- The two singleton orbits. -/
def boundaryOrbit000 : Finset Window6BoundaryCharacter := {χ000}
def boundaryOrbit111 : Finset Window6BoundaryCharacter := {χ111}

/-- The two nontrivial `C₃`-orbits. -/
def boundaryOrbitSingle : Finset Window6BoundaryCharacter := {χ100, χ010, χ001}
def boundaryOrbitDouble : Finset Window6BoundaryCharacter := {χ110, χ101, χ011}

/-- Explicit enumeration of all eight characters. -/
theorem boundaryCharacter_univ :
    (Finset.univ : Finset Window6BoundaryCharacter) =
      {χ000, χ111, χ100, χ010, χ001, χ110, χ101, χ011} := by
  native_decide

/-- Paper-facing orbit stratification of the window-6 boundary character group into
`1 + 1 + 3 + 3` under the coordinate-rotation action of `C₃`.
    thm:conclusion-window6-boundary-superselection-c3-orbit-stratification -/
theorem paper_conclusion_window6_boundary_superselection_c3_orbit_stratification :
    boundaryCharacterOrbit χ000 = boundaryOrbit000 ∧
    boundaryCharacterOrbit χ111 = boundaryOrbit111 ∧
    boundaryCharacterOrbit χ100 = boundaryOrbitSingle ∧
    boundaryCharacterOrbit χ110 = boundaryOrbitDouble ∧
    (∀ {α : Type*} [AddCommMonoid α] (M : Window6BoundaryCharacter → α),
      (∑ χ, M χ) =
        M χ000 + M χ111 + boundaryOrbitSingle.sum M + boundaryOrbitDouble.sum M) := by
  refine ⟨by native_decide, by native_decide, by native_decide, by native_decide, ?_⟩
  intro α _ M
  rw [boundaryCharacter_univ, boundaryOrbitSingle, boundaryOrbitDouble]
  repeat rw [Finset.sum_insert]
  · simp [add_left_comm, add_comm]
  all_goals decide

end Omega.Conclusion
