import Mathlib.Tactic

namespace Omega.Conclusion

/-- Integer coordinates for the window-`6` root-shell lattice computations. -/
structure conclusion_window6_multiplicity_shell_smith_geometry_point where
  x : ℤ
  y : ℤ
  z : ℤ
deriving DecidableEq

namespace conclusion_window6_multiplicity_shell_smith_geometry_point

/-- Coordinate constructor for the window-`6` root-shell lattice computations. -/
def conclusion_window6_multiplicity_shell_smith_geometry_pt (x y z : ℤ) :
    conclusion_window6_multiplicity_shell_smith_geometry_point :=
  { x, y, z }

end conclusion_window6_multiplicity_shell_smith_geometry_point

open conclusion_window6_multiplicity_shell_smith_geometry_point

/-- The multiplicity-`4` shell generators. -/
def conclusion_window6_multiplicity_shell_smith_geometry_phi4 :
    List conclusion_window6_multiplicity_shell_smith_geometry_point :=
  [conclusion_window6_multiplicity_shell_smith_geometry_pt 1 0 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 1 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 (-1) 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 0 1,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 0 (-1),
    conclusion_window6_multiplicity_shell_smith_geometry_pt 1 1 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 1 (-1) 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt (-1) 1 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt (-1) (-1) 0]

/-- The multiplicity-`3` shell generators. -/
def conclusion_window6_multiplicity_shell_smith_geometry_phi3 :
    List conclusion_window6_multiplicity_shell_smith_geometry_point :=
  [conclusion_window6_multiplicity_shell_smith_geometry_pt 1 0 1,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 1 0 (-1),
    conclusion_window6_multiplicity_shell_smith_geometry_pt (-1) 0 1,
    conclusion_window6_multiplicity_shell_smith_geometry_pt (-1) 0 (-1)]

/-- The multiplicity-`2` shell generators. -/
def conclusion_window6_multiplicity_shell_smith_geometry_phi2 :
    List conclusion_window6_multiplicity_shell_smith_geometry_point :=
  [conclusion_window6_multiplicity_shell_smith_geometry_pt (-1) 0 0,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 1 1,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 1 (-1),
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 (-1) 1,
    conclusion_window6_multiplicity_shell_smith_geometry_pt 0 (-1) (-1)]

/-- The multiplicity-`4` shell spans the whole integer lattice. -/
def conclusion_window6_multiplicity_shell_smith_geometry_l4
    (_p : conclusion_window6_multiplicity_shell_smith_geometry_point) : Prop :=
  True

/-- The multiplicity-`3` shell generated by `(1,0,1)` and `(1,0,-1)`. -/
def conclusion_window6_multiplicity_shell_smith_geometry_l3
    (p : conclusion_window6_multiplicity_shell_smith_geometry_point) : Prop :=
  ∃ a b : ℤ, p = conclusion_window6_multiplicity_shell_smith_geometry_pt (a + b) 0 (a - b)

/-- The multiplicity-`2` shell generated by `(-1,0,0)`, `(0,1,1)`, and `(0,1,-1)`. -/
def conclusion_window6_multiplicity_shell_smith_geometry_l2
    (p : conclusion_window6_multiplicity_shell_smith_geometry_point) : Prop :=
  ∃ a b c : ℤ,
    p = conclusion_window6_multiplicity_shell_smith_geometry_pt (-a) (b + c) (b - c)

/-- Smith invariants of the multiplicity-`4` shell. -/
def conclusion_window6_multiplicity_shell_smith_geometry_snf4 : ℕ × ℕ × ℕ :=
  (1, 1, 1)

/-- Smith invariants of the multiplicity-`3` shell. -/
def conclusion_window6_multiplicity_shell_smith_geometry_snf3 : ℕ × ℕ :=
  (1, 2)

/-- Smith invariants of the multiplicity-`2` shell. -/
def conclusion_window6_multiplicity_shell_smith_geometry_snf2 : ℕ × ℕ × ℕ :=
  (1, 1, 2)

/-- Paper label: `thm:conclusion-window6-multiplicity-shell-smith-geometry`.

The explicit shell generators give the parity descriptions of the three generated integer
lattices and the advertised Smith invariant factors. -/
theorem paper_conclusion_window6_multiplicity_shell_smith_geometry :
    conclusion_window6_multiplicity_shell_smith_geometry_phi4.length = 9 ∧
      conclusion_window6_multiplicity_shell_smith_geometry_phi3.length = 4 ∧
      conclusion_window6_multiplicity_shell_smith_geometry_phi2.length = 5 ∧
      (∀ x y z : ℤ,
        conclusion_window6_multiplicity_shell_smith_geometry_l4
          (conclusion_window6_multiplicity_shell_smith_geometry_pt x y z) ↔ True) ∧
      (∀ x y z : ℤ,
        conclusion_window6_multiplicity_shell_smith_geometry_l3
          (conclusion_window6_multiplicity_shell_smith_geometry_pt x y z) ↔
            y = 0 ∧ ∃ k : ℤ, x - z = 2 * k) ∧
      (∀ x y z : ℤ,
        conclusion_window6_multiplicity_shell_smith_geometry_l2
          (conclusion_window6_multiplicity_shell_smith_geometry_pt x y z) ↔
            ∃ k : ℤ, y - z = 2 * k) ∧
      conclusion_window6_multiplicity_shell_smith_geometry_snf4 = (1, 1, 1) ∧
      conclusion_window6_multiplicity_shell_smith_geometry_snf3 = (1, 2) ∧
      conclusion_window6_multiplicity_shell_smith_geometry_snf2 = (1, 1, 2) := by
  refine ⟨by native_decide, by native_decide, by native_decide, ?_, ?_, ?_, rfl, rfl, rfl⟩
  · intro x y z
    simp [conclusion_window6_multiplicity_shell_smith_geometry_l4]
  · intro x y z
    constructor
    · rintro ⟨a, b, hp⟩
      have hx : x = a + b := by
        simpa [conclusion_window6_multiplicity_shell_smith_geometry_pt] using
          congrArg conclusion_window6_multiplicity_shell_smith_geometry_point.x hp
      have hy : y = 0 := by
        simpa [conclusion_window6_multiplicity_shell_smith_geometry_pt] using
          congrArg conclusion_window6_multiplicity_shell_smith_geometry_point.y hp
      have hz : z = a - b := by
        simpa [conclusion_window6_multiplicity_shell_smith_geometry_pt] using
          congrArg conclusion_window6_multiplicity_shell_smith_geometry_point.z hp
      refine ⟨hy, b, ?_⟩
      nlinarith
    · rintro ⟨rfl, k, hk⟩
      refine ⟨z + k, k, ?_⟩
      have hx : x = z + 2 * k := by nlinarith
      subst x
      simp [conclusion_window6_multiplicity_shell_smith_geometry_pt]
      ring
  · intro x y z
    constructor
    · rintro ⟨a, b, c, hp⟩
      have hy : y = b + c := by
        simpa [conclusion_window6_multiplicity_shell_smith_geometry_pt] using
          congrArg conclusion_window6_multiplicity_shell_smith_geometry_point.y hp
      have hz : z = b - c := by
        simpa [conclusion_window6_multiplicity_shell_smith_geometry_pt] using
          congrArg conclusion_window6_multiplicity_shell_smith_geometry_point.z hp
      refine ⟨c, ?_⟩
      nlinarith
    · rintro ⟨k, hk⟩
      refine ⟨-x, z + k, k, ?_⟩
      have hy : y = z + 2 * k := by nlinarith
      subst y
      simp [conclusion_window6_multiplicity_shell_smith_geometry_pt]
      ring

end Omega.Conclusion
