import Mathlib.Logic.Relation
import Mathlib.Order.WellFounded

namespace Omega.EA.RewriteCore

/-- Letters of the exact rewrite system from the projection core paper. -/
inductive Letter where
  | Z
  | E (n : Nat)
  deriving DecidableEq, Repr

/-- Words in the exact rewrite system. -/
abbrev Word := List Letter

/-- One-step reductions generated by `ZZ → Z` and `E_m E_n → E_{min(m,n)}`. -/
inductive Step : Word → Word → Prop where
  | z (u v : Word) :
      Step (u ++ Letter.Z :: Letter.Z :: v) (u ++ Letter.Z :: v)
  | e (u v : Word) (m n : Nat) :
      Step (u ++ Letter.E m :: Letter.E n :: v) (u ++ Letter.E (min m n) :: v)

/-- Reflexive-transitive closure of the rewrite relation. -/
abbrev Reduces := Relation.ReflTransGen Step

/-- Push one letter onto a normal-form suffix. -/
def push : Letter → Word → Word
  | a, [] => [a]
  | Letter.Z, Letter.Z :: rest => Letter.Z :: rest
  | Letter.E m, Letter.E n :: rest => Letter.E (min m n) :: rest
  | a, b :: rest => a :: b :: rest

/-- Normal form obtained by collapsing maximal `Z`-blocks and `E`-blocks. -/
def normalize (w : Word) : Word :=
  w.foldr push []

@[simp] lemma normalize_nil : normalize [] = [] := rfl

@[simp] lemma normalize_cons (a : Letter) (w : Word) :
    normalize (a :: w) = push a (normalize w) := rfl

@[simp] lemma normalize_append (u v : Word) :
    normalize (u ++ v) = u.foldr push (normalize v) := by
  simp [normalize, List.foldr_append]

@[simp] lemma push_z_z (w : Word) :
    push Letter.Z (push Letter.Z w) = push Letter.Z w := by
  cases w with
  | nil =>
      rfl
  | cons a rest =>
      cases a <;> rfl

@[simp] lemma push_e_e (m n : Nat) (w : Word) :
    push (Letter.E m) (push (Letter.E n) w) = push (Letter.E (min m n)) w := by
  cases w with
  | nil =>
      rfl
  | cons a rest =>
      cases a <;> simp [push, Nat.min_left_comm, Nat.min_comm]

lemma step_length_lt {w w' : Word} (h : Step w w') : w'.length < w.length := by
  cases h <;> simp

lemma step_preserves_normalize {w w' : Word} (h : Step w w') :
    normalize w = normalize w' := by
  cases h with
  | z u v =>
      simp [normalize_append, push_z_z]
  | e u v m n =>
      simp [normalize_append, push_e_e]

lemma step_append_left (u : Word) {w w' : Word} (h : Step w w') :
    Step (u ++ w) (u ++ w') := by
  cases h with
  | z u' v' =>
      simpa [List.append_assoc] using Step.z (u ++ u') v'
  | e u' v' m n =>
      simpa [List.append_assoc] using Step.e (u ++ u') v' m n

lemma reduces_append_left (u : Word) {w w' : Word} (h : Reduces w w') :
    Reduces (u ++ w) (u ++ w') := by
  exact h.lift (fun x => u ++ x) (fun a b hab => step_append_left u hab)

theorem reduces_to_normalize : ∀ w : Word, Reduces w (normalize w)
  | [] => Relation.ReflTransGen.refl
  | a :: w =>
      have htail : Reduces (a :: w) (a :: normalize w) := by
        simpa using reduces_append_left [a] (reduces_to_normalize w)
      have hpush : Reduces (a :: normalize w) (push a (normalize w)) := by
        cases hnorm : normalize w with
        | nil =>
            cases a <;> exact Relation.ReflTransGen.refl
        | cons b rest =>
            cases a with
            | Z =>
                cases b with
                | Z =>
                    simpa [push] using
                      (Relation.ReflTransGen.single (Step.z [] rest))
                | E n =>
                    exact Relation.ReflTransGen.refl
            | E m =>
                cases b with
                | Z =>
                    exact Relation.ReflTransGen.refl
                | E n =>
                    simpa [push] using
                      (Relation.ReflTransGen.single (Step.e [] rest m n))
      Relation.ReflTransGen.trans htail hpush

lemma reduces_preserves_normalize {w w' : Word} (h : Reduces w w') :
    normalize w = normalize w' := by
  induction h with
  | refl =>
      rfl
  | tail hab hbc ih =>
      exact ih.trans (step_preserves_normalize hbc)

/-- Any two one-step reducts admit a common normal-form descendant. -/
theorem step_locallyConfluent {w x y : Word} (hx : Step w x) (hy : Step w y) :
    ∃ z, Reduces x z ∧ Reduces y z := by
  refine ⟨normalize w, ?_, ?_⟩
  · simpa [(step_preserves_normalize hx).symm] using reduces_to_normalize x
  · simpa [(step_preserves_normalize hy).symm] using reduces_to_normalize y

/-- Any two reducts admit a common normal-form descendant. -/
theorem confluent {w x y : Word} (hx : Reduces w x) (hy : Reduces w y) :
    ∃ z, Reduces x z ∧ Reduces y z := by
  refine ⟨normalize w, ?_, ?_⟩
  · simpa [(reduces_preserves_normalize hx).symm] using reduces_to_normalize x
  · simpa [(reduces_preserves_normalize hy).symm] using reduces_to_normalize y

end Omega.EA.RewriteCore
