import Omega.Folding.Rewrite

namespace Omega.EA

open Omega.Rewrite

set_option maxHeartbeats 400000 in
/-- Additivity of the Zeckendorf value functional on finitely supported digit configurations. -/
private theorem value_add (a b : DigitCfg) : value (a + b) = value a + value b := by
  classical
  unfold value weighted
  rw [Finsupp.sum_add_index']
  · simp
  · intro _ b₁ b₂
    simp [Nat.add_mul]

/-- The commutative-monoid congruence generated by the local Fibonacci rewrite rules. -/
inductive FibCongruence : DigitCfg → DigitCfg → Prop
  | step {a b : DigitCfg} : Step a b → FibCongruence a b
  | refl (a : DigitCfg) : FibCongruence a a
  | symm {a b : DigitCfg} : FibCongruence a b → FibCongruence b a
  | trans {a b c : DigitCfg} : FibCongruence a b → FibCongruence b c → FibCongruence a c
  | add {a b c d : DigitCfg} :
      FibCongruence a b → FibCongruence c d → FibCongruence (a + c) (b + d)

theorem FibCongruence.value_eq {a b : DigitCfg} (h : FibCongruence a b) : value a = value b := by
  induction h with
  | step hStep =>
      exact value_invariant_step _ _ hStep
  | refl _ =>
      rfl
  | symm h ih =>
      exact ih.symm
  | trans _ _ ih₁ ih₂ =>
      exact ih₁.trans ih₂
  | add _ _ ih₁ ih₂ =>
      rw [value_add, value_add, ih₁, ih₂]

/-- Setoid quotient by the Fibonacci congruence. -/
def fibCongruenceSetoid : Setoid DigitCfg where
  r := FibCongruence
  iseqv := ⟨FibCongruence.refl, FibCongruence.symm, FibCongruence.trans⟩

instance : Zero (Quotient fibCongruenceSetoid) where
  zero := Quotient.mk _ 0

noncomputable instance : Add (Quotient fibCongruenceSetoid) where
  add x y :=
    Quotient.liftOn₂ x y
      (fun a b => Quotient.mk _ (a + b))
      (fun _ _ _ _ ha hb => Quotient.sound (FibCongruence.add ha hb))

/-- The descended value map on the quotient by Fibonacci congruence. -/
def fibValue : Quotient fibCongruenceSetoid → Nat :=
  Quotient.lift value (fun _ _ h => FibCongruence.value_eq h)

@[simp] theorem fibValue_mk (a : DigitCfg) : fibValue ⟦a⟧ = value a := rfl

@[simp] theorem fibValue_zero : fibValue 0 = 0 := rfl

@[simp] theorem fibValue_add (x y : Quotient fibCongruenceSetoid) :
    fibValue (x + y) = fibValue x + fibValue y := by
  refine Quotient.inductionOn₂ x y ?_
  intro a b
  change fibValue ⟦a + b⟧ = value a + value b
  simp [fibValue, value_add]

/-- Paper-facing seed: Fibonacci congruence preserves the value map, and the value map therefore
    descends to the quotient as an additive map.
    prop:val-invariant -/
theorem paper_zeckendorf_val_invariant_seeds :
    (∀ a b : DigitCfg, FibCongruence a b → value a = value b) ∧
      ∃ f : Quotient fibCongruenceSetoid → Nat,
        (∀ a : DigitCfg, f ⟦a⟧ = value a) ∧
          f 0 = 0 ∧
          (∀ x y : Quotient fibCongruenceSetoid, f (x + y) = f x + f y) := by
  refine ⟨fun a b h => FibCongruence.value_eq h, ?_⟩
  exact ⟨fibValue, fibValue_mk, fibValue_zero, fibValue_add⟩

/-- Paper-facing wrapper for the Zeckendorf value invariant statement.
    prop:val-invariant -/
theorem paper_zeckendorf_val_invariant :
    (∀ a b : DigitCfg, FibCongruence a b → value a = value b) ∧
      ∃ f : Quotient fibCongruenceSetoid → Nat,
        (∀ a : DigitCfg, f ⟦a⟧ = value a) ∧
          f 0 = 0 ∧
          (∀ x y : Quotient fibCongruenceSetoid, f (x + y) = f x + f y) := by
  exact paper_zeckendorf_val_invariant_seeds

/-- Paper-label wrapper for `prop:val-invariant`. -/
theorem paper_val_invariant :
    (∀ a b : DigitCfg, FibCongruence a b → value a = value b) ∧
      ∃ f : Quotient fibCongruenceSetoid → Nat,
        (∀ a : DigitCfg, f ⟦a⟧ = value a) ∧
          f 0 = 0 ∧
          (∀ x y : Quotient fibCongruenceSetoid, f (x + y) = f x + f y) := by
  exact paper_zeckendorf_val_invariant

end Omega.EA
