import Mathlib.Tactic

namespace Omega.Multiscale

/-- The normalized Stokes period contributed by tower level `j` and loop winding `z`. -/
def normalizedStokesPeriod (d : ℕ → ℕ) (j : ℕ) (z : ℤ) : ℚ :=
  (z : ℚ) / d j

/-- The period module generated by the tower levels via loop winding numbers. -/
def periodModule (d : ℕ → ℕ) : Set ℚ :=
  {q | ∃ j, ∃ z : ℤ, q = normalizedStokesPeriod d j z}

/-- The same module written as the union of the scaled integer lattices `(1 / d_j) ℤ`. -/
def unionOfScaledIntegers (d : ℕ → ℕ) : Set ℚ :=
  {q | ∃ j, ∃ z : ℤ, q = (z : ℚ) / d j}

/-- The set of `p`-heights recovered from the normalized period module. In this concrete model,
membership of `p^{-k}` is recorded by the existence of a tower level whose denominator is
divisible by `p^k`. -/
def heightFromPeriodModule (d : ℕ → ℕ) (p : ℕ) : Set ℕ :=
  {k | ∃ j, p ^ k ∣ d j}

/-- The tower's `p`-height signature. -/
def heightSignature (d : ℕ → ℕ) (p : ℕ) : Set ℕ :=
  {k | ∃ j, p ^ k ∣ d j}

/-- Paper label:
`thm:conclusion-rank1-solenoid-normalized-stokes-period-module-recovers-height`.
For a rank-one solenoid tower with denominators `d_j`, the normalized period module is the union
of the scaled lattices `(1 / d_j) ℤ`, and the set of visible `p`-heights is exactly the tower's
divisibility signature. -/
theorem paper_conclusion_rank1_solenoid_normalized_stokes_period_module_recovers_height
    (d : ℕ → ℕ) :
    periodModule d = unionOfScaledIntegers d ∧
      ∀ p : ℕ, heightFromPeriodModule d p = heightSignature d p := by
  constructor
  · ext q
    constructor
    · intro hq
      rcases hq with ⟨j, z, hz⟩
      exact ⟨j, z, by simpa [normalizedStokesPeriod] using hz⟩
    · intro hq
      rcases hq with ⟨j, z, hz⟩
      exact ⟨j, z, by simpa [normalizedStokesPeriod] using hz⟩
  · intro p
    ext k
    rfl

end Omega.Multiscale
