#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate a small multiscale residual audit table (rotation scan).

This script is English-only by repository convention.

It computes the cross-resolution projective TV residual

  E_{m,N} = TV( p_m , (prefix)_* p_{m+1} )

for a small (m,N) grid under a fixed irrational rotation scan, and writes a
LaTeX table snippet for local audit (not the main experiment summary table).
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np

from common_phi_fold import PHI, Progress, fold_m


ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "sections" / "generated"


def _pack_bits_to_int(bits: Iterable[int], m: int) -> int:
    x = 0
    for b in bits:
        x = (x << 1) | (1 if b else 0)
    return x & ((1 << m) - 1)


def _int_to_bits(x: int, m: int) -> List[int]:
    return [(x >> (m - 1 - i)) & 1 for i in range(m)]


def build_fold_map(m: int, prog: Progress) -> List[int]:
    size = 1 << m
    out = [0] * size
    for w in range(size):
        bits = _int_to_bits(w, m)
        folded = fold_m(bits)
        out[w] = _pack_bits_to_int(folded, m)
        prog.tick(f"build_fold_map m={m} w={w}/{size}")
    return out


def rotation_bits(alpha: float, x0: float, beta: float, n: int) -> np.ndarray:
    ts = np.arange(n, dtype=np.float64)
    xs = (x0 + alpha * ts) % 1.0
    return (xs < beta).astype(np.uint8)


def count_folded_hist(
    s: np.ndarray, m: int, N: int, fold_map: List[int], prog: Progress
) -> Dict[int, int]:
    if N + m - 1 > len(s):
        raise ValueError("s too short for requested N,m")
    mask = (1 << m) - 1
    w = _pack_bits_to_int(s[:m], m)
    counts: Dict[int, int] = {}
    for t in range(N):
        if t > 0:
            w = ((w << 1) & mask) | int(s[t + m - 1])
        folded = fold_map[w]
        counts[folded] = counts.get(folded, 0) + 1
        prog.tick(f"count m={m} t={t}/{N}")
    return counts


def count_folded_hist_m1_and_boundary(
    s: np.ndarray,
    m: int,
    N: int,
    fold_map_m: List[int],
    fold_map_m1: List[int],
    prog: Progress,
) -> Tuple[Dict[int, int], int]:
    """Count folded (m+1)-hist and boundary event rate.

    Boundary event B_{m+1} (paper Def. fold-boundary-event) is:
      last_bit(window_{m+1}) == 1  and  last_bit(Fold_m(prefix_m)) == 1.
    """

    m1 = m + 1
    if N + m1 - 1 > len(s):
        raise ValueError("s too short for requested N,m+1")
    mask_m1 = (1 << m1) - 1

    w = _pack_bits_to_int(s[:m1], m1)
    counts: Dict[int, int] = {}
    boundary = 0
    for t in range(N):
        if t > 0:
            w = ((w << 1) & mask_m1) | int(s[t + m1 - 1])

        folded_m1 = fold_map_m1[w]
        counts[folded_m1] = counts.get(folded_m1, 0) + 1

        last_bit = w & 1
        if last_bit:
            prefix = w >> 1
            if fold_map_m[prefix] & 1:
                boundary += 1

        prog.tick(f"count m1={m1} t={t}/{N}")

    return counts, boundary


def pushforward_truncate_last_bit(counts_m1: Dict[int, int]) -> Dict[int, int]:
    out: Dict[int, int] = {}
    for w, c in counts_m1.items():
        out[w >> 1] = out.get(w >> 1, 0) + c
    return out


def tv_distance_int(p: Dict[int, float], q: Dict[int, float]) -> float:
    keys = set(p.keys()) | set(q.keys())
    s = 0.0
    for k in keys:
        s += abs(p.get(k, 0.0) - q.get(k, 0.0))
    return 0.5 * s


def write_tex(rows: List[Tuple[int, int, float, float]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append(
        "% Auto-generated by scripts/exp_rotation_multiscale_residual_summary.py"
    )
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{rrrr}")
    lines.append("\\toprule")
    lines.append("$m$ & $N$ & $E_{m,N}$ & $\\hat\\mu_{m+1,N}(\\mathcal{B}_{m+1})$ \\\\")
    lines.append("\\midrule")
    for m, N, e, b in rows:
        lines.append(f"{m} & {N} & {e:.6g} & {b:.6g} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Cross-resolution projective residual $E_{m,N}$ and the boundary perturbation rate $\\hat\\mu_{m+1,N}(\\mathcal{B}_{m+1})$ in the rotation scan model (small audit grid).}"
    )
    lines.append("\\label{tab:rotation_multiscale_residual_audit_grid}")
    lines.append("\\end{table}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    prog = Progress("exp_rotation_multiscale_residual", every_seconds=20.0)

    alpha = 1.0 / PHI
    beta = 1.0 / PHI
    x0 = 0.123

    ms: Sequence[int] = [6, 8, 10, 12]
    Ns: Sequence[int] = [10_000, 30_000, 100_000]

    t0 = time.time()
    fold_maps: Dict[int, List[int]] = {}
    for m in sorted(set(ms) | {m + 1 for m in ms}):
        fold_maps[m] = build_fold_map(m, prog)

    rows: List[Tuple[int, int, float, float]] = []
    Nmax = max(Ns)
    for m in ms:
        s_len = Nmax + (m + 1) - 1
        s = rotation_bits(alpha, x0, beta, s_len)
        for N in Ns:
            counts_m = count_folded_hist(
                s=s, m=m, N=N, fold_map=fold_maps[m], prog=prog
            )
            counts_m1, boundary = count_folded_hist_m1_and_boundary(
                s=s,
                m=m,
                N=N,
                fold_map_m=fold_maps[m],
                fold_map_m1=fold_maps[m + 1],
                prog=prog,
            )

            p_m: Dict[int, float] = {k: v / float(N) for k, v in counts_m.items()}
            p_m1_push = pushforward_truncate_last_bit(counts_m1)
            p_push: Dict[int, float] = {k: v / float(N) for k, v in p_m1_push.items()}
            e = tv_distance_int(p_m, p_push)
            b = boundary / float(N)
            rows.append((m, N, e, b))
            prog.tick(f"done m={m} N={N} E={e:.6g} B={b:.6g}")

    out = GEN / "tab_rotation_multiscale_residual_audit_grid.tex"
    write_tex(rows, out)
    dt = time.time() - t0
    print(
        f"[exp_rotation_multiscale_residual] WROTE {out.relative_to(ROOT)} in {dt:.1f}s",
        flush=True,
    )


if __name__ == "__main__":
    main()
