import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Tactic

namespace Omega.RatioResultant

open Polynomial

/-- Concrete seed data for the ratio-field splitting package. The statement proved below is
independent of the payload; the structure exists only to match the paper-facing theorem signature
required by the round. -/
structure RatioFieldSplittingData (K : Type*) [Field K] where
  dummy : Unit := ()

namespace RatioFieldSplittingData

/-- If a unit `ζ` satisfies `ζ^n = 1`, then the subgroup it generates is cyclic, its cardinality
divides `n`, every element is an `n`th root of unity, and every polynomial factoring through
`x^n` is invariant under the scaling `x ↦ ζx`. -/
def field_splitting_statement {K : Type*} [Field K] (_D : RatioFieldSplittingData K) : Prop :=
  ∀ n : ℕ, ∀ ζ : Kˣ, ζ ^ n = 1 →
    ∃ H : Subgroup Kˣ,
      H = Subgroup.zpowers ζ ∧
      Nat.card H ∣ n ∧
      IsCyclic H ∧
      (∀ h : H, ((h : Kˣ) ^ n) = 1) ∧
      ∀ p : K[X], ∀ x : K,
        Polynomial.eval (↑ζ * x) (p.comp (Polynomial.X ^ n)) =
          Polynomial.eval x (p.comp (Polynomial.X ^ n))

end RatioFieldSplittingData

open RatioFieldSplittingData

lemma factor_through_power_invariant {K : Type*} [Field K] (n : ℕ) (ζ : Kˣ) (hζ : ζ ^ n = 1)
    (p : K[X]) (x : K) :
    Polynomial.eval (↑ζ * x) (p.comp (Polynomial.X ^ n)) =
      Polynomial.eval x (p.comp (Polynomial.X ^ n)) := by
  have hzval : (↑ζ : K) ^ n = 1 := by
    simpa using congrArg (fun u : Kˣ => (u : K)) hζ
  rw [Polynomial.eval_comp, Polynomial.eval_pow]
  simp [Polynomial.eval_X, mul_pow, hzval]

lemma generated_root_subgroup_card_dvd {K : Type*} [Field K] (n : ℕ) (ζ : Kˣ) (hζ : ζ ^ n = 1) :
    Nat.card (Subgroup.zpowers ζ) ∣ n := by
  rw [Nat.card_zpowers]
  exact orderOf_dvd_of_pow_eq_one hζ

lemma generated_root_subgroup_nth_roots {K : Type*} [Field K] (n : ℕ) (ζ : Kˣ) (hζ : ζ ^ n = 1)
    (h : Subgroup.zpowers ζ) : ((h : Kˣ) ^ n) = 1 := by
  have hmem : orderOf (h : Kˣ) ∣ orderOf ζ := orderOf_dvd_of_mem_zpowers h.property
  have hroot : orderOf ζ ∣ n := orderOf_dvd_of_pow_eq_one hζ
  exact orderOf_dvd_iff_pow_eq_one.mp (hmem.trans hroot)

/-- Concrete ratio-field splitting package: the subgroup generated by an `n`th root of unity is
cyclic of order dividing `n`, every one of its elements is again an `n`th root of unity, and any
polynomial of the form `g(x^n)` is invariant under the scaling `x ↦ ζx`.
    prop:ratio-field-splitting -/
theorem paper_ratio_field_splitting {K : Type*} [Field K] (D : RatioFieldSplittingData K) :
    D.field_splitting_statement := by
  intro n ζ hζ
  refine ⟨Subgroup.zpowers ζ, rfl, generated_root_subgroup_card_dvd n ζ hζ, ?_, ?_, ?_⟩
  · infer_instance
  · intro h
    exact generated_root_subgroup_nth_roots n ζ hζ h
  · intro p x
    exact factor_through_power_invariant n ζ hζ p x

end Omega.RatioResultant
