import Omega.OperatorAlgebra.FoldOptimalDelinkingCurve

namespace Omega.OperatorAlgebra

noncomputable section

/-- Tensorizing the optimal delinking curve over `n` rounds scales both the index gap and the
randomness budget linearly, so the lower envelope is exactly homogeneous of degree `1` along the
nonnegative ray generated by `n`.
    thm:op-algebra-multi-round-strong-converse-linear-leakage -/
theorem paper_op_algebra_multi_round_strong_converse_linear_leakage
    (Gamma h : ℝ) (n : ℕ) :
    foldOptimalDelinkingCurve ((n : ℝ) * Gamma) ((n : ℝ) * h) =
      (n : ℝ) * foldOptimalDelinkingCurve Gamma h := by
  have hn : (0 : ℝ) ≤ n := by
    exact_mod_cast Nat.zero_le n
  by_cases hh : h ≤ Gamma
  · have hgap : 0 ≤ Gamma - h := sub_nonneg.mpr hh
    have hscaled : 0 ≤ (n : ℝ) * Gamma - (n : ℝ) * h := by
      nlinarith
    unfold foldOptimalDelinkingCurve
    rw [max_eq_left hscaled, max_eq_left hgap]
    ring
  · have hgap : Gamma - h ≤ 0 := by
      linarith [lt_of_not_ge hh]
    have hscaled : (n : ℝ) * Gamma - (n : ℝ) * h ≤ 0 := by
      nlinarith
    unfold foldOptimalDelinkingCurve
    rw [max_eq_right hscaled, max_eq_right hgap]
    ring

end

end Omega.OperatorAlgebra
