import Mathlib

namespace Omega.Zeta

noncomputable section

/-- Concrete carrier for the φ-adic Mellin pole-lattice package. The Mellin-side function is
periodic with a fixed vertical step, the pole set is cut out by a rationalized witness function,
and principal parts are transported unchanged along the same lattice. -/
structure ConclusionPhiadicMellinPoleLatticeRigidityData where
  period : ℂ
  anchor : ℂ
  mellin : ℂ → ℂ
  rationalPoleWitness : ℂ → ℂ
  poleSet : Set ℂ
  principalPart : ℂ → ℂ
  hperiodic : ∀ s : ℂ, mellin (s + period) = mellin s
  hpole_iff_rational : ∀ s : ℂ, s ∈ poleSet ↔ rationalPoleWitness s = 0
  hrational_periodic : ∀ s : ℂ, rationalPoleWitness (s + period) = rationalPoleWitness s
  hprincipal_periodic :
    ∀ s : ℂ, s ∈ poleSet → principalPart (s + period) = principalPart s
  hoff_lattice : ∀ s : ℂ, s ∈ poleSet → ∃ n : ℤ, s = anchor + n • period

namespace ConclusionPhiadicMellinPoleLatticeRigidityData

/-- The Mellin-side model is periodic on the vertical lattice generated by the chosen step. -/
def verticalLatticePeriodicity (D : ConclusionPhiadicMellinPoleLatticeRigidityData) : Prop :=
  ∀ s : ℂ, D.mellin (s + D.period) = D.mellin s

/-- Poles and principal parts are rigid along the full vertical lattice orbit. -/
def poleLatticeRigidity (D : ConclusionPhiadicMellinPoleLatticeRigidityData) : Prop :=
  ∀ s : ℂ, s ∈ D.poleSet →
    s + D.period ∈ D.poleSet ∧ D.principalPart (s + D.period) = D.principalPart s

/-- Every pole lies on the declared vertical lattice, so there are no isolated off-lattice poles. -/
def noIsolatedOffLatticePole (D : ConclusionPhiadicMellinPoleLatticeRigidityData) : Prop :=
  ∀ s : ℂ, s ∈ D.poleSet → ∃ n : ℤ, s = D.anchor + n • D.period

end ConclusionPhiadicMellinPoleLatticeRigidityData

open ConclusionPhiadicMellinPoleLatticeRigidityData

/-- Paper label: `thm:conclusion-phiadic-mellin-pole-lattice-rigidity`. Once the Mellin variable
is periodic under the vertical lattice step and the same rationalized pole witness cuts out the
pole set on every translate, poles and their principal parts move rigidly along the whole lattice
orbit, and no pole can occur away from that orbit. -/
theorem paper_conclusion_phiadic_mellin_pole_lattice_rigidity
    (D : ConclusionPhiadicMellinPoleLatticeRigidityData) :
    D.verticalLatticePeriodicity ∧ D.poleLatticeRigidity ∧ D.noIsolatedOffLatticePole := by
  refine ⟨D.hperiodic, ?_, D.hoff_lattice⟩
  intro s hs
  have hs0 : D.rationalPoleWitness s = 0 := (D.hpole_iff_rational s).mp hs
  have hshift0 : D.rationalPoleWitness (s + D.period) = 0 := by
    rw [D.hrational_periodic s]
    exact hs0
  exact ⟨(D.hpole_iff_rational (s + D.period)).mpr hshift0, D.hprincipal_periodic s hs⟩

end

end Omega.Zeta
