import Mathlib.Tactic
import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
import Mathlib.RingTheory.RootsOfUnity.Complex

namespace Omega.Zeta.CyclotomicSectorIdentity

open Complex Finset Polynomial Real

/-- Primitive `q`-th root of unity index `k`: `exp(2πi·k/q)`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
noncomputable def rootOfUnity (q k : ℕ) : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I * k / q)

/-- Index 0 root: `ω_q^0 = 1`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem rootOfUnity_zero (q : ℕ) : rootOfUnity q 0 = 1 := by
  unfold rootOfUnity
  simp

/-- Concrete identity at `q = 1`: `∏_{k<1} (1 - x·ω_1^k) = 1 - x`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem prod_one_sub_x_root_of_unity_one (x : ℂ) :
    ∏ k ∈ Finset.range 1, (1 - x * rootOfUnity 1 k) = 1 - x ^ 1 := by
  rw [Finset.prod_range_one, rootOfUnity_zero]
  ring

/-- The `q = 2` case: `(1 - x·1)·(1 - x·(-1)) = 1 - x²`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem rootOfUnity_two_one : rootOfUnity 2 1 = -1 := by
  unfold rootOfUnity
  push_cast
  rw [show (2 * (Real.pi : ℂ) * Complex.I * 1 / 2) = Real.pi * Complex.I by ring]
  exact Complex.exp_pi_mul_I

/-- `q = 2` case: `∏_{k<2}(1 - x·ω_2^k) = 1 - x²`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem prod_one_sub_x_root_of_unity_two (x : ℂ) :
    ∏ k ∈ Finset.range 2, (1 - x * rootOfUnity 2 k) = 1 - x ^ 2 := by
  rw [Finset.prod_range_succ, Finset.prod_range_one,
      rootOfUnity_zero, rootOfUnity_two_one]
  ring

/-- Paper package (concrete `q = 1, 2` cases).
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem paper_finite_part_cyclic_lift_cyclotomic_sector_q12 (x : ℂ) :
    (∏ k ∈ Finset.range 1, (1 - x * rootOfUnity 1 k) = 1 - x ^ 1) ∧
    (∏ k ∈ Finset.range 2, (1 - x * rootOfUnity 2 k) = 1 - x ^ 2) :=
  ⟨prod_one_sub_x_root_of_unity_one x, prod_one_sub_x_root_of_unity_two x⟩

-- Phase R600: q = 4 cyclotomic sector product
-- ══════════════════════════════════════════════════════════════

/-- `ω₄¹ = i`: the first primitive 4th root of unity.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem rootOfUnity_four_one : rootOfUnity 4 1 = Complex.I := by
  unfold rootOfUnity
  push_cast
  rw [show (2 * (Real.pi : ℂ) * Complex.I * 1 / 4) = Real.pi / 2 * Complex.I by ring]
  exact Complex.exp_pi_div_two_mul_I

/-- `ω₄² = -1`: the second primitive 4th root of unity.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem rootOfUnity_four_two : rootOfUnity 4 2 = -1 := by
  unfold rootOfUnity
  push_cast
  rw [show (2 * (Real.pi : ℂ) * Complex.I * 2 / 4) = Real.pi * Complex.I by ring]
  exact Complex.exp_pi_mul_I

/-- `ω₄³ = -i`: the third primitive 4th root of unity.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem rootOfUnity_four_three : rootOfUnity 4 3 = -Complex.I := by
  unfold rootOfUnity
  push_cast
  rw [show (2 * (Real.pi : ℂ) * Complex.I * 3 / 4) =
    Real.pi * Complex.I + Real.pi / 2 * Complex.I by ring]
  rw [Complex.exp_add, Complex.exp_pi_mul_I, Complex.exp_pi_div_two_mul_I]
  ring

/-- `q = 4` case: `∏_{k<4}(1 - x·ω₄^k) = 1 - x⁴`.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem prod_one_sub_x_root_of_unity_four (x : ℂ) :
    ∏ k ∈ Finset.range 4, (1 - x * rootOfUnity 4 k) = 1 - x ^ 4 := by
  rw [show (4 : ℕ) = 3 + 1 from rfl, Finset.prod_range_succ,
      show (3 : ℕ) = 2 + 1 from rfl, Finset.prod_range_succ,
      show (2 : ℕ) = 1 + 1 from rfl, Finset.prod_range_succ,
      Finset.prod_range_one,
      rootOfUnity_zero, rootOfUnity_four_one, rootOfUnity_four_two, rootOfUnity_four_three]
  have hI2 : Complex.I ^ 2 = -1 := Complex.I_sq
  linear_combination (x ^ 4 - x ^ 2) * hI2

/-- Paper package (concrete `q = 1, 2, 4` cases).
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem paper_finite_part_cyclic_lift_cyclotomic_sector_q1234 (x : ℂ) :
    (∏ k ∈ Finset.range 1, (1 - x * rootOfUnity 1 k) = 1 - x ^ 1) ∧
    (∏ k ∈ Finset.range 2, (1 - x * rootOfUnity 2 k) = 1 - x ^ 2) ∧
    (∏ k ∈ Finset.range 4, (1 - x * rootOfUnity 4 k) = 1 - x ^ 4) :=
  ⟨prod_one_sub_x_root_of_unity_one x, prod_one_sub_x_root_of_unity_two x,
   prod_one_sub_x_root_of_unity_four x⟩

/-- For positive order, the explicit exponential enumeration is generated by the first root. -/
theorem rootOfUnity_eq_pow_rootOfUnity_one {q k : ℕ} (hq : q ≠ 0) :
    rootOfUnity q k = rootOfUnity q 1 ^ k := by
  have hqC : (q : ℂ) ≠ 0 := by
    exact_mod_cast hq
  have hroot1 : rootOfUnity q 1 = Complex.exp (2 * Real.pi * Complex.I / q) := by
    unfold rootOfUnity
    congr 1
    field_simp [hqC]
    norm_num
  calc
    rootOfUnity q k = Complex.exp (k * (2 * Real.pi * Complex.I / q)) := by
      unfold rootOfUnity
      congr 1
      field_simp [hqC]
    _ = Complex.exp (2 * Real.pi * Complex.I / q) ^ k := by rw [Complex.exp_nat_mul]
    _ = rootOfUnity q 1 ^ k := by rw [hroot1]

/-- The first nontrivial root in the explicit enumeration is primitive. -/
theorem isPrimitiveRoot_rootOfUnity_one (q : ℕ) (hq : 2 ≤ q) : IsPrimitiveRoot (rootOfUnity q 1) q := by
  have hq0 : q ≠ 0 := by omega
  unfold rootOfUnity
  simpa using Complex.isPrimitiveRoot_exp q hq0

/-- General cyclotomic sector factorization over the `q`-th roots of unity.
    prop:finite-part-cyclic-lift-cyclotomic-sector -/
theorem paper_finite_part_cyclic_lift_cyclotomic_sector (q : ℕ) (hq : 2 ≤ q) (x : ℂ) :
    ∏ k ∈ Finset.range q, (1 - x * rootOfUnity q k) = 1 - x ^ q := by
  classical
  have hq0 : q ≠ 0 := by omega
  have hqpos : 0 < q := Nat.pos_of_ne_zero hq0
  letI : NeZero q := ⟨hq0⟩
  let ζ := rootOfUnity q 1
  have hζ : IsPrimitiveRoot ζ q := by
    simpa [ζ] using isPrimitiveRoot_rootOfUnity_one q hq
  have hinj : Set.InjOn (rootOfUnity q) (↑(Finset.range q) : Set ℕ) := by
    intro a ha b hb hab
    apply hζ.pow_inj (Finset.mem_range.mp ha) (Finset.mem_range.mp hb)
    simpa [ζ, rootOfUnity_eq_pow_rootOfUnity_one (k := a) hq0,
      rootOfUnity_eq_pow_rootOfUnity_one (k := b) hq0] using hab
  have himage : Finset.image (rootOfUnity q) (Finset.range q) = nthRootsFinset q (1 : ℂ) := by
    ext η
    constructor
    · intro hη
      rcases Finset.mem_image.mp hη with ⟨k, hk, rfl⟩
      rw [mem_nthRootsFinset hqpos]
      rw [rootOfUnity_eq_pow_rootOfUnity_one (k := k) hq0]
      change (ζ ^ k) ^ q = 1
      calc
        (ζ ^ k) ^ q = ζ ^ (k * q) := by rw [pow_mul]
        _ = ζ ^ (q * k) := by rw [Nat.mul_comm]
        _ = (ζ ^ q) ^ k := by rw [← pow_mul]
        _ = 1 ^ k := by rw [hζ.pow_eq_one]
        _ = 1 := one_pow k
    · intro hη
      rw [mem_nthRootsFinset hqpos] at hη
      obtain ⟨k, hk, hkη⟩ := hζ.eq_pow_of_pow_eq_one hη
      exact Finset.mem_image.mpr ⟨k, Finset.mem_range.mpr hk, by
        rw [rootOfUnity_eq_pow_rootOfUnity_one (k := k) hq0]
        exact hkη⟩
  calc
    ∏ k ∈ Finset.range q, (1 - x * rootOfUnity q k) =
        ∏ η ∈ Finset.image (rootOfUnity q) (Finset.range q), (1 - x * η) := by
      symm
      exact Finset.prod_image hinj
    _ = ∏ η ∈ nthRootsFinset q (1 : ℂ), (1 - x * η) := by rw [himage]
    _ = 1 - x ^ q := by
      simpa [one_pow, mul_comm] using
        (hζ.pow_sub_pow_eq_prod_sub_mul (x := (1 : ℂ)) (y := x) hqpos).symm

end Omega.Zeta.CyclotomicSectorIdentity
