import Mathlib

namespace Omega.Zeta

/-- The five branch points of the Kummer cover `u^3 = F(μ)`: `0`, the two golden-ratio roots,
and the two poles `± i`. -/
inductive xi_degree11_cyclic_cubic_normalization_genus3_branch_point where
  | zero
  | phi_plus
  | phi_minus
  | imag_pos
  | imag_neg
  deriving DecidableEq, Repr

/-- The ordered branch-point packet appearing in the paper. -/
def xi_degree11_cyclic_cubic_normalization_genus3_branch_points :
    List xi_degree11_cyclic_cubic_normalization_genus3_branch_point :=
  [xi_degree11_cyclic_cubic_normalization_genus3_branch_point.zero,
    xi_degree11_cyclic_cubic_normalization_genus3_branch_point.phi_plus,
    xi_degree11_cyclic_cubic_normalization_genus3_branch_point.phi_minus,
    xi_degree11_cyclic_cubic_normalization_genus3_branch_point.imag_pos,
    xi_degree11_cyclic_cubic_normalization_genus3_branch_point.imag_neg]

/-- The Kummer cover `u^3 = F(μ)` has degree `3` over the `μ`-line. -/
def xi_degree11_cyclic_cubic_normalization_genus3_cover_degree : ℕ := 3

/-- Every recorded branch point is totally ramified. -/
def xi_degree11_cyclic_cubic_normalization_genus3_ramification_index
    (_ : xi_degree11_cyclic_cubic_normalization_genus3_branch_point) : ℕ :=
  3

/-- Total ramification contribution `Σ (e - 1)` from the five totally ramified points. -/
def xi_degree11_cyclic_cubic_normalization_genus3_total_ramification : ℕ :=
  xi_degree11_cyclic_cubic_normalization_genus3_branch_points.length *
    (xi_degree11_cyclic_cubic_normalization_genus3_ramification_index
      xi_degree11_cyclic_cubic_normalization_genus3_branch_point.zero - 1)

/-- The genus given by the explicit Riemann-Hurwitz computation. -/
def xi_degree11_cyclic_cubic_normalization_genus3_genus : ℕ := 3

/-- The cyclic deck group generated by `u ↦ ω u`. -/
abbrev xi_degree11_cyclic_cubic_normalization_genus3_deck_group := Fin 3

/-- The generator of the cubic deck group. -/
def xi_degree11_cyclic_cubic_normalization_genus3_deck_transform
    (u : xi_degree11_cyclic_cubic_normalization_genus3_deck_group) :
    xi_degree11_cyclic_cubic_normalization_genus3_deck_group :=
  u + 1

/-- Paper-facing package for the degree-`11` cyclic cubic normalization. -/
def xi_degree11_cyclic_cubic_normalization_genus3_statement : Prop :=
  xi_degree11_cyclic_cubic_normalization_genus3_branch_points.length = 5 ∧
    xi_degree11_cyclic_cubic_normalization_genus3_branch_points.Nodup ∧
    xi_degree11_cyclic_cubic_normalization_genus3_cover_degree = 3 ∧
    (∀ p ∈ xi_degree11_cyclic_cubic_normalization_genus3_branch_points,
      xi_degree11_cyclic_cubic_normalization_genus3_ramification_index p = 3) ∧
    xi_degree11_cyclic_cubic_normalization_genus3_total_ramification = 10 ∧
    2 * xi_degree11_cyclic_cubic_normalization_genus3_genus - 2 =
      xi_degree11_cyclic_cubic_normalization_genus3_total_ramification -
        2 * xi_degree11_cyclic_cubic_normalization_genus3_cover_degree ∧
    xi_degree11_cyclic_cubic_normalization_genus3_genus = 3 ∧
    Fintype.card xi_degree11_cyclic_cubic_normalization_genus3_deck_group = 3 ∧
    (∀ u : xi_degree11_cyclic_cubic_normalization_genus3_deck_group,
      (xi_degree11_cyclic_cubic_normalization_genus3_deck_transform^[3]) u = u) ∧
    xi_degree11_cyclic_cubic_normalization_genus3_deck_transform 0 ≠
      (0 : xi_degree11_cyclic_cubic_normalization_genus3_deck_group)

/-- Paper label: `thm:xi-degree11-cyclic-cubic-normalization-genus3`. -/
theorem paper_xi_degree11_cyclic_cubic_normalization_genus3 :
    xi_degree11_cyclic_cubic_normalization_genus3_statement := by
  unfold xi_degree11_cyclic_cubic_normalization_genus3_statement
    xi_degree11_cyclic_cubic_normalization_genus3_branch_points
    xi_degree11_cyclic_cubic_normalization_genus3_cover_degree
    xi_degree11_cyclic_cubic_normalization_genus3_ramification_index
    xi_degree11_cyclic_cubic_normalization_genus3_total_ramification
    xi_degree11_cyclic_cubic_normalization_genus3_genus
    xi_degree11_cyclic_cubic_normalization_genus3_deck_transform
  native_decide

end Omega.Zeta
