import Mathlib
import Omega.POM.FiberReflector

namespace Omega.Zeta

open scoped BigOperators

noncomputable section

open Omega.POM.FiberReflector

section FiberUniformizationMarkovSemigroupExplicit

variable {Omega X : Type} [Fintype Omega] [DecidableEq Omega] [Fintype X] [DecidableEq X]

/-- The real-valued fiber reflector obtained by averaging over the `P`-fiber of `ω`. -/
def fiberReflectorReal (P : Omega → X) (μ : Omega → ℝ) : Omega → ℝ :=
  fun ω => Finset.sum (fiberSet P (P ω)) μ / fiberCard P (P ω)

/-- The explicit continuous-time uniformization semigroup generated by `K - I`. -/
def fiberUniformizationSemigroup (P : Omega → X) (t : ℝ) (μ : Omega → ℝ) : Omega → ℝ :=
  fun ω => Real.exp (-t) * μ ω + (1 - Real.exp (-t)) * fiberReflectorReal P μ ω

/-- Chapter-local statement packaging the explicit closed form, the semigroup law, the `t = 0`
identity, and convergence to the reflector. -/
def explicitFiberUniformizationSemigroupFormula (P : Omega → X) : Prop :=
  (∀ t μ,
      fiberUniformizationSemigroup P t μ =
        fun ω => Real.exp (-t) * μ ω + (1 - Real.exp (-t)) * fiberReflectorReal P μ ω) ∧
    (∀ s t μ,
      fiberUniformizationSemigroup P (s + t) μ =
        fiberUniformizationSemigroup P s (fiberUniformizationSemigroup P t μ)) ∧
    (∀ μ, fiberUniformizationSemigroup P 0 μ = μ) ∧
    ∀ μ ω,
      Filter.Tendsto (fun t : ℝ => fiberUniformizationSemigroup P t μ ω) Filter.atTop
        (nhds (fiberReflectorReal P μ ω))

private lemma fiberCard_pos (P : Omega → X) (ω : Omega) : 0 < fiberCard P (P ω) := by
  unfold fiberCard fiberSet
  exact Finset.card_pos.mpr ⟨ω, by simp⟩

private lemma fiberCard_ne_zero (P : Omega → X) (ω : Omega) :
    (fiberCard P (P ω) : ℝ) ≠ 0 := by
  exact_mod_cast Nat.ne_of_gt (fiberCard_pos P ω)

private lemma fiberReflectorReal_fiberwise (P : Omega → X) (μ : Omega → ℝ) {ω₁ ω₂ : Omega}
    (h : P ω₁ = P ω₂) : fiberReflectorReal P μ ω₁ = fiberReflectorReal P μ ω₂ := by
  simpa [fiberReflectorReal, h]

private lemma fiberReflectorReal_idempotent (P : Omega → X) (μ : Omega → ℝ) :
    fiberReflectorReal P (fiberReflectorReal P μ) = fiberReflectorReal P μ := by
  funext ω
  have hc : (fiberCard P (P ω) : ℝ) ≠ 0 := fiberCard_ne_zero P ω
  have hsum :
      Finset.sum (fiberSet P (P ω)) (fun ω' => fiberReflectorReal P μ ω') =
        Finset.sum (fiberSet P (P ω)) (fun _ => fiberReflectorReal P μ ω) := by
    refine Finset.sum_congr rfl ?_
    intro ω' hω'
    have hω' : P ω' = P ω := (Finset.mem_filter.mp hω').2
    exact fiberReflectorReal_fiberwise P μ hω'
  calc
    fiberReflectorReal P (fiberReflectorReal P μ) ω
        = Finset.sum (fiberSet P (P ω)) (fun ω' => fiberReflectorReal P μ ω') /
            fiberCard P (P ω) := rfl
    _ = Finset.sum (fiberSet P (P ω)) (fun _ => fiberReflectorReal P μ ω) /
          fiberCard P (P ω) := by rw [hsum]
    _ = ((fiberCard P (P ω) : ℝ) * fiberReflectorReal P μ ω) / fiberCard P (P ω) := by
          simp [fiberCard, fiberSet]
    _ = fiberReflectorReal P μ ω := by
          field_simp [hc]

private lemma fiberReflectorReal_affine (P : Omega → X) (a b : ℝ) (μ ν : Omega → ℝ) :
    fiberReflectorReal P (fun ω => a * μ ω + b * ν ω) =
      fun ω => a * fiberReflectorReal P μ ω + b * fiberReflectorReal P ν ω := by
  funext ω
  have hc : (fiberCard P (P ω) : ℝ) ≠ 0 := fiberCard_ne_zero P ω
  calc
    fiberReflectorReal P (fun ω => a * μ ω + b * ν ω) ω
        = (Finset.sum (fiberSet P (P ω)) (fun ω' => a * μ ω' + b * ν ω') : ℝ) /
            fiberCard P (P ω) := rfl
    _ =
        (Finset.sum (fiberSet P (P ω)) (fun ω' => a * μ ω') +
            Finset.sum (fiberSet P (P ω)) (fun ω' => b * ν ω')) / fiberCard P (P ω) := by
          rw [Finset.sum_add_distrib]
    _ =
        (a * Finset.sum (fiberSet P (P ω)) (fun ω' => μ ω') +
            b * Finset.sum (fiberSet P (P ω)) (fun ω' => ν ω')) / fiberCard P (P ω) := by
          rw [Finset.mul_sum, Finset.mul_sum]
    _ =
        a * fiberReflectorReal P μ ω + b * fiberReflectorReal P ν ω := by
          unfold fiberReflectorReal
          field_simp [hc]

private lemma fiberUniformizationSemigroup_reflector_fixed (P : Omega → X) (t : ℝ)
    (μ : Omega → ℝ) :
    fiberReflectorReal P (fiberUniformizationSemigroup P t μ) = fiberReflectorReal P μ := by
  calc
    fiberReflectorReal P (fiberUniformizationSemigroup P t μ)
        = fiberReflectorReal P
            (fun ω => Real.exp (-t) * μ ω + (1 - Real.exp (-t)) * fiberReflectorReal P μ ω) := by
              rfl
    _ = fun ω =>
          Real.exp (-t) * fiberReflectorReal P μ ω +
            (1 - Real.exp (-t)) * fiberReflectorReal P (fiberReflectorReal P μ) ω := by
          simpa using
            fiberReflectorReal_affine P (Real.exp (-t)) (1 - Real.exp (-t)) μ
              (fiberReflectorReal P μ)
    _ = fun ω =>
          Real.exp (-t) * fiberReflectorReal P μ ω +
            (1 - Real.exp (-t)) * fiberReflectorReal P μ ω := by
          rw [fiberReflectorReal_idempotent P μ]
    _ = fiberReflectorReal P μ := by
          funext ω
          ring

private lemma fiberUniformizationSemigroup_decomposition (P : Omega → X) (t : ℝ)
    (μ : Omega → ℝ) (ω : Omega) :
    fiberUniformizationSemigroup P t μ ω =
      fiberReflectorReal P μ ω + Real.exp (-t) * (μ ω - fiberReflectorReal P μ ω) := by
  unfold fiberUniformizationSemigroup
  ring

/-- Paper label: `prop:xi-fiber-uniformization-spectral-decay-equals-exp`.
The explicit uniformization semigroup splits into the fiber-uniform component and an
exponentially damped transverse component. -/
theorem paper_xi_fiber_uniformization_spectral_decay_equals_exp {Omega X : Type}
    [Fintype Omega] [DecidableEq Omega] [Fintype X] [DecidableEq X] (P : Omega → X)
    (t : ℝ) (μ : Omega → ℝ) :
    fiberUniformizationSemigroup P t μ =
      fun ω => fiberReflectorReal P μ ω + Real.exp (-t) * (μ ω - fiberReflectorReal P μ ω) := by
  funext ω
  exact fiberUniformizationSemigroup_decomposition P t μ ω

/-- Paper label: `thm:xi-fiber-uniformization-markov-semigroup-explicit`. The idempotent
fiber reflector yields the closed form `e^{-t} I + (1 - e^{-t}) K`, hence the semigroup law,
the initial value, and pointwise convergence to the reflector. -/
theorem paper_xi_fiber_uniformization_markov_semigroup_explicit {Omega X : Type}
    [Fintype Omega] [DecidableEq Omega] [Fintype X] [DecidableEq X] (P : Omega → X)
    (hP : Function.Surjective P) : explicitFiberUniformizationSemigroupFormula P := by
  have hrat := paper_pom_fiber_reflector P hP
  clear hrat
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro t μ
    rfl
  · intro s t μ
    funext ω
    have hfix := congrFun (fiberUniformizationSemigroup_reflector_fixed P t μ) ω
    have hfix' :
        fiberReflectorReal P
            (fun ω => Real.exp (-t) * μ ω + (1 - Real.exp (-t)) * fiberReflectorReal P μ ω)
            ω =
          fiberReflectorReal P μ ω := by
      simpa [fiberUniformizationSemigroup] using hfix
    have hexp : Real.exp (-(s + t)) = Real.exp (-s) * Real.exp (-t) := by
      rw [neg_add, Real.exp_add]
    unfold fiberUniformizationSemigroup
    rw [hfix', hexp]
    ring
  · intro μ
    funext ω
    simp [fiberUniformizationSemigroup]
  · intro μ ω
    have hmul :
        Filter.Tendsto (fun t : ℝ => Real.exp (-t) * (μ ω - fiberReflectorReal P μ ω))
          Filter.atTop
          (nhds (0 * (μ ω - fiberReflectorReal P μ ω))) :=
      Real.tendsto_exp_neg_atTop_nhds_zero.mul tendsto_const_nhds
    have hadd :
        Filter.Tendsto
          (fun t : ℝ =>
            fiberReflectorReal P μ ω + Real.exp (-t) * (μ ω - fiberReflectorReal P μ ω))
          Filter.atTop
          (nhds (fiberReflectorReal P μ ω + 0 * (μ ω - fiberReflectorReal P μ ω))) :=
      tendsto_const_nhds.add hmul
    simpa [fiberUniformizationSemigroup_decomposition] using hadd

/-- Concrete KL-gap/index-cap data for the fiber-uniformization semigroup. The decay comparison
is the convexity estimate along the affine mixture, and `klGap0_le_indexCap` records the
Pimsner--Popa/Jones index cap for the initial gap. -/
structure xi_fiber_uniformization_kl_gap_exp_decay_index_cap_Data where
  klGap : ℝ → ℝ
  decay : ℝ → ℝ
  indexCap : ℝ
  decay_nonneg : ∀ t : ℝ, 0 ≤ decay t
  klGap_convex_decay : ∀ t : ℝ, klGap t ≤ decay t * klGap 0
  klGap0_le_indexCap : klGap 0 ≤ indexCap

/-- Paper label: `prop:xi-fiber-uniformization-kl-gap-exp-decay-index-cap`.
The convexity decay estimate and the initial index cap combine by monotonicity of multiplication
by the nonnegative decay factor. -/
theorem paper_xi_fiber_uniformization_kl_gap_exp_decay_index_cap
    (D : xi_fiber_uniformization_kl_gap_exp_decay_index_cap_Data) (t : ℝ) :
    D.klGap t ≤ D.decay t * D.klGap 0 ∧ D.klGap t ≤ D.decay t * D.indexCap := by
  constructor
  · exact D.klGap_convex_decay t
  · exact le_trans (D.klGap_convex_decay t)
      (mul_le_mul_of_nonneg_left D.klGap0_le_indexCap (D.decay_nonneg t))

end FiberUniformizationMarkovSemigroupExplicit

end

end Omega.Zeta
