import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Complex.Basic
import Omega.Zeta.CyclotomicSectorIdentity

namespace Omega.Zeta

noncomputable section

/-- Concrete witness package for the finite RH cyclic phase lift. The data tracks one boundary
eigenvalue, its `q` phase-twisted lifts, and the preserved spectral/Ramanujan radii. -/
structure FiniteRhPhaseLiftData where
  q : ℕ
  hq : 2 ≤ q
  lambda : ℝ
  hlambda : 1 < lambda
  theta : ℝ
  baseEigenvalue : ℂ
  baseSpectralRadius : ℝ
  liftSpectralRadius : ℝ
  baseRamanujanRadius : ℝ
  liftRamanujanRadius : ℝ
  baseSpectralRadius_eq : baseSpectralRadius = lambda
  liftSpectralRadius_eq : liftSpectralRadius = lambda
  baseRamanujanRadius_eq : baseRamanujanRadius = Real.sqrt lambda
  liftRamanujanRadius_eq : liftRamanujanRadius = Real.sqrt lambda

/-- The `k`-th phase-twisted eigenvalue of the `q`-fold cyclic lift. -/
noncomputable def FiniteRhPhaseLiftData.liftEigenvalue (D : FiniteRhPhaseLiftData) (k : Fin D.q) :
    ℂ :=
  D.baseEigenvalue * Omega.Zeta.CyclotomicSectorIdentity.rootOfUnity D.q k

/-- Spectral phase refinement for the cyclic lift: the `k`-th channel rotates the base
eigenvalue by the `k`-th `q`-th root of unity. -/
def FiniteRhPhaseLiftData.phaseRefinement (D : FiniteRhPhaseLiftData) : Prop :=
  ∀ k : Fin D.q,
    D.liftEigenvalue k = D.baseEigenvalue * Omega.Zeta.CyclotomicSectorIdentity.rootOfUnity D.q k

/-- The cyclic lift preserves the spectral radius. -/
def FiniteRhPhaseLiftData.spectralRadiusPreserved (D : FiniteRhPhaseLiftData) : Prop :=
  D.liftSpectralRadius = D.baseSpectralRadius

/-- The cyclic lift preserves the Ramanujan boundary radius. -/
def FiniteRhPhaseLiftData.ramanujanBoundPreserved (D : FiniteRhPhaseLiftData) : Prop :=
  D.liftRamanujanRadius = D.baseRamanujanRadius

/-- The explicit critical-line pole generated by the `k`-th phase channel and the `m`-th vertical
translate. -/
noncomputable def FiniteRhPhaseLiftData.criticalLinePole (D : FiniteRhPhaseLiftData)
    (k : Fin D.q) (m : ℤ) : ℂ :=
  (1 / 2 : ℂ) +
    (((D.theta + 2 * Real.pi * (((k : ℕ) : ℝ) / (D.q : ℝ) + (m : ℝ))) / Real.log D.lambda) :
      ℂ) * Complex.I

/-- Critical-line pole-comb formula for the cyclic lift. -/
def FiniteRhPhaseLiftData.criticalLineCombRefinement (D : FiniteRhPhaseLiftData) : Prop :=
  ∀ k : Fin D.q, ∀ m : ℤ,
    D.criticalLinePole k m =
      (1 / 2 : ℂ) +
        (((D.theta + 2 * Real.pi * (((k : ℕ) : ℝ) / (D.q : ℝ) + (m : ℝ))) / Real.log D.lambda) :
          ℂ) * Complex.I

/-- Paper-facing package for the finite RH cyclic phase lift: the cyclic lift refines phases by
`q`-th roots of unity, preserves the spectral radius and the Ramanujan radius, and places the
resulting pole families on the explicit critical-line comb.
    prop:finite-rh-phase-lift -/
theorem paper_finite_rh_phase_lift (D : FiniteRhPhaseLiftData) :
    D.phaseRefinement ∧
      D.spectralRadiusPreserved ∧
        D.ramanujanBoundPreserved ∧ D.criticalLineCombRefinement := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro k
    rfl
  · dsimp [FiniteRhPhaseLiftData.spectralRadiusPreserved]
    rw [D.liftSpectralRadius_eq, D.baseSpectralRadius_eq]
  · dsimp [FiniteRhPhaseLiftData.ramanujanBoundPreserved]
    rw [D.liftRamanujanRadius_eq, D.baseRamanujanRadius_eq]
  · intro k m
    rfl

end
end Omega.Zeta
