import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Omega.Zeta

open scoped BigOperators

noncomputable section

/-- Concrete data for a finite family of vertical arithmetic progressions coming from a
finite-determinant model. Each family has a real part, an imaginary offset, and a positive step
size. -/
structure FiniteDeterminantArithmeticLatticeData where
  familyCount : ℕ
  sigma : Fin familyCount → ℝ
  offset : Fin familyCount → ℝ
  step : Fin familyCount → ℝ
  step_pos : ∀ j : Fin familyCount, 0 < step j

/-- The `n`-th point on the `j`-th vertical arithmetic progression. -/
def progressionPoint (D : FiniteDeterminantArithmeticLatticeData) (j : Fin D.familyCount)
    (n : ℤ) : ℝ :=
  D.offset j + (n : ℝ) * D.step j

/-- Imaginary parts appearing in the strip `a < Re(s) < b`. -/
def stripImaginarySet (D : FiniteDeterminantArithmeticLatticeData) (a b : ℝ) : Set ℝ :=
  {t : ℝ | ∃ j : Fin D.familyCount, a < D.sigma j ∧ D.sigma j < b ∧
      ∃ n : ℤ, t = progressionPoint D j n}

/-- Pairwise differences of strip imaginary parts. -/
def stripImaginaryDifferenceSet (D : FiniteDeterminantArithmeticLatticeData) (a b : ℝ) : Set ℝ :=
  {x : ℝ | ∃ t ∈ stripImaginarySet D a b, ∃ t' ∈ stripImaginarySet D a b, x = t - t'}

/-- Finite offset-difference set coming from the finitely many vertical progressions. -/
def finiteDeterminantOffsetDifferences (D : FiniteDeterminantArithmeticLatticeData) : Finset ℝ :=
  (Finset.univ.product Finset.univ).image fun jk : Fin D.familyCount × Fin D.familyCount =>
    D.offset jk.1 - D.offset jk.2

/-- The subgroup generated by the finitely many step sizes, written as an explicit integer linear
combination set. -/
def finiteDeterminantStepLattice (D : FiniteDeterminantArithmeticLatticeData) : Set ℝ :=
  {x : ℝ | ∃ z : Fin D.familyCount → ℤ,
      x = Finset.sum Finset.univ fun j : Fin D.familyCount => (z j : ℝ) * D.step j}

/-- Arithmetic-lattice closure for finite-determinant models: every strip difference decomposes as
a finite offset difference plus an element of the subgroup generated by the step sizes. -/
def finiteDeterminantArithmeticLatticeClaim (D : FiniteDeterminantArithmeticLatticeData) : Prop :=
  ∀ a b : ℝ, stripImaginaryDifferenceSet D a b ⊆
    {x : ℝ | ∃ e ∈ (finiteDeterminantOffsetDifferences D : Set ℝ),
      ∃ y ∈ finiteDeterminantStepLattice D, x = e + y}

/-- The difference set of finitely many vertical arithmetic progressions lies in a finite set of
offset differences translated by the subgroup generated by the step sizes.
    cor:finite-determinant-arithmetic-lattice -/
theorem paper_finite_determinant_arithmetic_lattice (D : FiniteDeterminantArithmeticLatticeData) :
    finiteDeterminantArithmeticLatticeClaim D := by
  intro a b x hx
  rcases hx with ⟨t, ⟨j, haj, hjb, n, rfl⟩, t', ⟨k, hak, hkb, n', rfl⟩, rfl⟩
  let y : ℝ := (n : ℝ) * D.step j + (-(n' : ℝ)) * D.step k
  refine ⟨D.offset j - D.offset k, ?_, y, ?_, ?_⟩
  · unfold finiteDeterminantOffsetDifferences
    refine Finset.mem_image.mpr ?_
    refine ⟨(j, k), ?_, rfl⟩
    simp
  · unfold finiteDeterminantStepLattice
    let z : Fin D.familyCount → ℤ := fun i => (if i = j then n else 0) + (if i = k then -n' else 0)
    refine ⟨z, ?_⟩
    dsimp [y, z]
    simp [add_mul, Finset.sum_add_distrib]
  · simp [progressionPoint, y]
    ring

/-- The normalized atom mass contributed by a full arithmetic progression to the ordered
two-point difference statistic at offset `nΔ`. In the chapter-local wrapper, one full progression
contributes the constant density `1 / Δ`. -/
def arithmeticProgressionDifferenceAtomMass (Δ : ℝ) (_n : ℤ) : ℝ :=
  1 / Δ

/-- Chapter-local proxy for the statement that every lattice offset `nΔ` carries a positive atom in
the limiting two-point difference statistic generated by one complete arithmetic progression. -/
def fullProgressionStatisticalLattice (Δ : ℝ) : Prop :=
  ∀ n : ℤ, 1 / Δ ≤ arithmeticProgressionDifferenceAtomMass Δ n

/-- If one vertical arithmetic progression survives inside the strip, then the existing arithmetic
lattice theorem packages the difference-set obstruction, and that full progression contributes the
uniform atom lower bound `1 / Δ` at every lattice offset `nΔ`.
    cor:finite-determinant-statistical-lattice -/
theorem paper_finite_determinant_statistical_lattice (D : FiniteDeterminantArithmeticLatticeData)
    (j : Fin D.familyCount) :
    finiteDeterminantArithmeticLatticeClaim D ∧
      fullProgressionStatisticalLattice (D.step j) ∧
      0 < arithmeticProgressionDifferenceAtomMass (D.step j) 0 := by
  refine ⟨paper_finite_determinant_arithmetic_lattice D, ?_, ?_⟩
  · intro n
    simp [arithmeticProgressionDifferenceAtomMass]
  · have hstep : 0 < D.step j := D.step_pos j
    simp [arithmeticProgressionDifferenceAtomMass]
    positivity

end
end Omega.Zeta
