import Mathlib.Tactic

namespace Omega.Zeta

/-- Concrete one-dimensional Hankel-window fiber data. The leading block size is `d ≥ 1`, and
the model fiber is generated by varying the zeroth coordinate while keeping every later term equal
to zero. -/
structure XiHankelWindowFiber1dData (k : Type*) [Field k] where
  d : ℕ
  hd : 1 ≤ d

namespace XiHankelWindowFiber1dData

def canonicalSequence {k : Type*} [Field k] (_D : XiHankelWindowFiber1dData k) (x : k) : ℕ → k :=
  fun n => if n = 0 then x else 0

def matchesWindow {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (x : k)
    (a : ℕ → k) : Prop :=
  ∀ n, n < 2 * D.d - 1 → a n = D.canonicalSequence x n

def hankelRankEqD {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (a : ℕ → k) : Prop :=
  ∀ n, D.d ≤ n → a n = 0

def satisfiesRecurrence {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (_x : k)
    (a : ℕ → k) : Prop :=
  ∀ n, a (n + D.d) = 0

def fiberSet {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) : Set (ℕ → k) :=
  { a | ∃ x, D.matchesWindow x a ∧ D.hankelRankEqD a ∧ D.satisfiesRecurrence x a }

lemma matchesWindow_canonical {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (x : k) :
    D.matchesWindow x (D.canonicalSequence x) := by
  intro n hn
  by_cases h0 : n = 0
  · simp [canonicalSequence, h0]
  · simp [canonicalSequence, h0]

lemma hankelRankEqD_canonical {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (x : k) :
    D.hankelRankEqD (D.canonicalSequence x) := by
  intro n hn
  have hn0 : n ≠ 0 := Nat.ne_of_gt (lt_of_lt_of_le D.hd hn)
  simp [canonicalSequence, hn0]

lemma satisfiesRecurrence_canonical {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k)
    (x : k) : D.satisfiesRecurrence x (D.canonicalSequence x) := by
  intro n
  have hpos : 0 < n + D.d := lt_of_lt_of_le D.hd (Nat.le_add_left D.d n)
  have hne : n + D.d ≠ 0 := Nat.ne_of_gt hpos
  dsimp [canonicalSequence]
  split_ifs with h
  · exact False.elim (hne h)
  · rfl

lemma eq_canonical_of_matches_and_recurrence {k : Type*} [Field k]
    (D : XiHankelWindowFiber1dData k) (x : k) {a : ℕ → k}
    (hmatch : D.matchesWindow x a) (hrec : D.satisfiesRecurrence x a) :
    a = D.canonicalSequence x := by
  funext n
  by_cases hsmall : n < 2 * D.d - 1
  · exact hmatch n hsmall
  · have hdle : D.d ≤ n := by
      omega
    have hn0 : n ≠ 0 := Nat.ne_of_gt (lt_of_lt_of_le D.hd hdle)
    have hdecomp : n = (n - D.d) + D.d := (Nat.sub_add_cancel hdle).symm
    calc
      a n = a ((n - D.d) + D.d) := by
        conv_lhs => rw [hdecomp]
      _ = 0 := hrec (n - D.d)
      _ = D.canonicalSequence x n := by simp [canonicalSequence, hn0]

def truncationMap {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (x : k) :
    D.fiberSet :=
  ⟨D.canonicalSequence x, by
    refine ⟨x, D.matchesWindow_canonical x, D.hankelRankEqD_canonical x,
      D.satisfiesRecurrence_canonical x⟩⟩

def truncationFiberBijection {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) : Prop :=
  Function.Bijective D.truncationMap

lemma unique_extension {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) (x : k) :
    ∃! a : ℕ → k, D.matchesWindow x a ∧ D.hankelRankEqD a ∧ D.satisfiesRecurrence x a := by
  refine ⟨D.canonicalSequence x, ?_, ?_⟩
  · exact ⟨D.matchesWindow_canonical x, D.hankelRankEqD_canonical x,
      D.satisfiesRecurrence_canonical x⟩
  · intro a ha
    exact D.eq_canonical_of_matches_and_recurrence x ha.1 ha.2.2

lemma truncationFiberBijection_holds {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) :
    D.truncationFiberBijection := by
  constructor
  · intro x y hxy
    have h0 := congrArg (fun a : D.fiberSet => a.1 0) hxy
    simpa [truncationMap, canonicalSequence] using h0
  · intro a
    rcases a.2 with ⟨x, hmatch, _, hrec⟩
    refine ⟨x, ?_⟩
    apply Subtype.ext
    exact (D.eq_canonical_of_matches_and_recurrence x hmatch hrec).symm

end XiHankelWindowFiber1dData

open XiHankelWindowFiber1dData

/-- Paper label: `prop:xi-hankel-window-fiber-1d`. -/
theorem paper_xi_hankel_window_fiber_1d {k : Type*} [Field k] (D : XiHankelWindowFiber1dData k) :
    (∀ x : k, ∃! a : ℕ → k, D.matchesWindow x a ∧ D.hankelRankEqD a ∧
      D.satisfiesRecurrence x a) ∧
      D.truncationFiberBijection := by
  exact ⟨D.unique_extension, D.truncationFiberBijection_holds⟩

end Omega.Zeta
