import Mathlib.Tactic
import Omega.Zeta.PrefixReadoutOrthogonalErrorDecomposition

namespace Omega.Zeta

open Omega.Experiments.MarkovTVSampleComplexity

noncomputable section

/-- The real-valued time-tail threshold before applying the integer ceiling. -/
noncomputable def prefix_audit_explicit_stopping_frontier_time_threshold_raw
    (K1 groupCard epsilon lambda tau : ℝ) : ℝ :=
  Real.log (3 * K1 * groupCard / tau) / (((1 / 2 : ℝ) + epsilon) * Real.log lambda)

/-- The displayed time-tail stopping threshold, encoded as a real-valued ceiling. -/
noncomputable def prefix_audit_explicit_stopping_frontier_time_threshold
    (K1 groupCard epsilon lambda tau : ℝ) : ℝ :=
  (⌈prefix_audit_explicit_stopping_frontier_time_threshold_raw
    K1 groupCard epsilon lambda tau⌉₊ : ℝ)

/-- The real-valued finite-data threshold before applying the integer ceiling. -/
noncomputable def prefix_audit_explicit_stopping_frontier_data_threshold_raw
    (stateCount gammaPs tau deltaConf : ℝ) : ℝ :=
  (9 * stateCount ^ 2 / (2 * gammaPs * tau ^ 2)) *
    Real.log (2 * stateCount / deltaConf)

/-- The displayed finite-data stopping threshold, encoded as a real-valued ceiling. -/
noncomputable def prefix_audit_explicit_stopping_frontier_data_threshold
    (stateCount gammaPs tau deltaConf : ℝ) : ℝ :=
  (⌈prefix_audit_explicit_stopping_frontier_data_threshold_raw
    stateCount gammaPs tau deltaConf⌉₊ : ℝ)

lemma prefix_audit_explicit_stopping_frontier_time_raw_le_threshold
    (K1 groupCard epsilon lambda tau : ℝ) :
    prefix_audit_explicit_stopping_frontier_time_threshold_raw K1 groupCard epsilon lambda tau ≤
      prefix_audit_explicit_stopping_frontier_time_threshold K1 groupCard epsilon lambda tau := by
  exact Nat.le_ceil _

lemma prefix_audit_explicit_stopping_frontier_data_raw_le_threshold
    (stateCount gammaPs tau deltaConf : ℝ) :
    prefix_audit_explicit_stopping_frontier_data_threshold_raw stateCount gammaPs tau deltaConf ≤
      prefix_audit_explicit_stopping_frontier_data_threshold stateCount gammaPs tau deltaConf := by
  exact Nat.le_ceil _

/-- Concrete data for the explicit prefix-audit stopping frontier. The two monotonicity fields
record that once the corresponding real-valued threshold has been crossed, the time and data
budget terms are each at most `tau / 3`; the ceiling fields identify the paper's displayed
integer thresholds. -/
structure prefix_audit_explicit_stopping_frontier_data where
  tau : ℝ
  observedError : ℝ
  timeTail : ℝ
  sampleCount : ℝ
  stateCount : ℝ
  deltaConf : ℝ
  gammaPs : ℝ
  fiberAmbiguity : ℝ
  nullGap : ℝ
  K1 : ℝ
  groupCard : ℝ
  epsilon : ℝ
  lambda : ℝ
  n : ℝ
  N : ℝ
  nStar : ℝ
  NStar : ℝ
  hNStar :
    nStar =
      prefix_audit_explicit_stopping_frontier_time_threshold K1 groupCard epsilon lambda tau
  hSampleStar :
    NStar = prefix_audit_explicit_stopping_frontier_data_threshold stateCount gammaPs tau deltaConf
  hAtFrontierTime : nStar ≤ n
  hAtFrontierData : NStar ≤ N
  hFourBudget :
    observedError ≤
      timeTail +
        (stateCount / 2) * markovTvEnvelopeRadius sampleCount stateCount deltaConf gammaPs +
          fiberAmbiguity + nullGap
  hTimeMonotoneBudget :
    prefix_audit_explicit_stopping_frontier_time_threshold_raw K1 groupCard epsilon lambda tau ≤ n →
      timeTail ≤ tau / 3
  hDataMonotoneBudget :
    prefix_audit_explicit_stopping_frontier_data_threshold_raw stateCount gammaPs tau deltaConf ≤ N →
      (stateCount / 2) * markovTvEnvelopeRadius sampleCount stateCount deltaConf gammaPs ≤ tau / 3
  hFiberBudget : fiberAmbiguity ≤ tau / 3
  hNullBudget : nullGap ≤ 0

namespace prefix_audit_explicit_stopping_frontier_data

/-- The total-error claim represented by the explicit frontier certificate. -/
def totalErrorLe (D : prefix_audit_explicit_stopping_frontier_data) : Prop :=
  D.observedError ≤ D.tau

/-- The northeast quadrant generated by the two explicit stopping thresholds. -/
def stoppingRegion (D : prefix_audit_explicit_stopping_frontier_data) : Set (ℝ × ℝ) :=
  {p | D.nStar ≤ p.1 ∧ D.NStar ≤ p.2}

/-- Repackage the explicit frontier hypotheses as the existing orthogonal-error certificate. -/
def prefix_audit_explicit_stopping_frontier_to_orthogonal_data
    (D : prefix_audit_explicit_stopping_frontier_data) :
    prefix_readout_orthogonal_error_decomposition_data :=
  { prefix_readout_orthogonal_error_decomposition_tau := D.tau
    prefix_readout_orthogonal_error_decomposition_observed_error := D.observedError
    prefix_readout_orthogonal_error_decomposition_time_tail := D.timeTail
    prefix_readout_orthogonal_error_decomposition_sample_count := D.sampleCount
    prefix_readout_orthogonal_error_decomposition_state_count := D.stateCount
    prefix_readout_orthogonal_error_decomposition_delta_conf := D.deltaConf
    prefix_readout_orthogonal_error_decomposition_gamma_ps := D.gammaPs
    prefix_readout_orthogonal_error_decomposition_fiber_ambiguity := D.fiberAmbiguity
    prefix_readout_orthogonal_error_decomposition_null_gap := D.nullGap
    prefix_readout_orthogonal_error_decomposition_h_four_budget := D.hFourBudget
    prefix_readout_orthogonal_error_decomposition_h_time_budget := by
      apply D.hTimeMonotoneBudget
      calc
        prefix_audit_explicit_stopping_frontier_time_threshold_raw
              D.K1 D.groupCard D.epsilon D.lambda D.tau
            ≤ prefix_audit_explicit_stopping_frontier_time_threshold
                D.K1 D.groupCard D.epsilon D.lambda D.tau :=
          prefix_audit_explicit_stopping_frontier_time_raw_le_threshold
            D.K1 D.groupCard D.epsilon D.lambda D.tau
        _ = D.nStar := D.hNStar.symm
        _ ≤ D.n := D.hAtFrontierTime
    prefix_readout_orthogonal_error_decomposition_h_data_budget := by
      apply D.hDataMonotoneBudget
      calc
        prefix_audit_explicit_stopping_frontier_data_threshold_raw
              D.stateCount D.gammaPs D.tau D.deltaConf
            ≤ prefix_audit_explicit_stopping_frontier_data_threshold
                D.stateCount D.gammaPs D.tau D.deltaConf :=
          prefix_audit_explicit_stopping_frontier_data_raw_le_threshold
            D.stateCount D.gammaPs D.tau D.deltaConf
        _ = D.NStar := D.hSampleStar.symm
        _ ≤ D.N := D.hAtFrontierData
    prefix_readout_orthogonal_error_decomposition_h_fiber_budget := D.hFiberBudget
    prefix_readout_orthogonal_error_decomposition_h_null_budget := D.hNullBudget }

end prefix_audit_explicit_stopping_frontier_data

open prefix_audit_explicit_stopping_frontier_data

/-- Paper label: `thm:prefix-audit-explicit-stopping-frontier`. The displayed ceiling thresholds
place the time-tail and finite-data terms below their `tau / 3` budgets; the fiber and `NULL`
budgets are supplied independently, so the orthogonal-error decomposition gives the total audit
bound, and the stopping region is the northeast quadrant generated by the two thresholds. -/
theorem paper_prefix_audit_explicit_stopping_frontier
    (D : prefix_audit_explicit_stopping_frontier_data) :
    D.totalErrorLe ∧ D.stoppingRegion = {p | D.nStar ≤ p.1 ∧ D.NStar ≤ p.2} := by
  refine ⟨?_, rfl⟩
  have hDecomp :=
    paper_prefix_readout_orthogonal_error_decomposition
      D.prefix_audit_explicit_stopping_frontier_to_orthogonal_data
  exact hDecomp.2

end

end Omega.Zeta
