import Mathlib.Tactic

namespace Omega.Zeta

open Polynomial

/-- Coefficient-vector model for the truncated polynomial ring `ℤ[λ]/(λ^n)`. -/
def coeffVector (n : ℕ) (p : ℤ[X]) : Fin n → ℤ := fun i => p.coeff i

/-- Truncated multiplication by `λ` on coefficient vectors. -/
def truncatedShiftFun (n : ℕ) (v : Fin n → ℤ) (i : Fin n) : ℤ :=
  if h : i.1 = 0 then
    0
  else
    v ⟨i.1 - 1, by omega⟩

/-- Truncated multiplication by `λ`: shift coefficients one step to the right and discard the
top coefficient. -/
def truncatedShift (n : ℕ) : (Fin n → ℤ) →ₗ[ℤ] (Fin n → ℤ) where
  toFun := truncatedShiftFun n
  map_add' v w := by
    ext i
    by_cases h : i.1 = 0 <;> simp [truncatedShiftFun, h]
  map_smul' a v := by
    ext i
    by_cases h : i.1 = 0 <;> simp [truncatedShiftFun, h]

@[simp] lemma truncatedShift_apply (n : ℕ) (v : Fin n → ℤ) (i : Fin n) :
    truncatedShift n v i = truncatedShiftFun n v i := rfl

/-- The tail lattice generated by `λ^m`: vectors whose first `m` coefficients vanish. -/
def tailLattice (n m : ℕ) : Submodule ℤ (Fin n → ℤ) where
  carrier := { v | ∀ i : Fin n, i.1 < m → v i = 0 }
  zero_mem' := by simp
  add_mem' := by
    intro v w hv hw i hi
    rw [Pi.add_apply, hv i hi, hw i hi, add_zero]
  smul_mem' := by
    intro a v hv i hi
    simp [hv i hi]

/-- Shift-invariance for sublattices of the truncated coefficient model. -/
def ShiftInvariant (n : ℕ) (L : Submodule ℤ (Fin n → ℤ)) : Prop :=
  ∀ ⦃v : Fin n → ℤ⦄, v ∈ L → truncatedShift n v ∈ L

/-- Saturation in the concrete sense: if a nonzero integer multiple lies in the lattice, then so
does the vector itself. -/
def Saturated {n : ℕ} (L : Submodule ℤ (Fin n → ℤ)) : Prop :=
  ∀ ⦃a : ℤ⦄, a ≠ 0 → ∀ ⦃v : Fin n → ℤ⦄, a • v ∈ L → v ∈ L

/-- Coefficient vectors of multiples of a fixed polynomial, truncated modulo `X^n`. -/
def principalIdealLattice (n : ℕ) (P : ℤ[X]) : Submodule ℤ (Fin n → ℤ) where
  carrier := { v | ∃ Q : ℤ[X], coeffVector n (Q * P) = v }
  zero_mem' := by
    refine ⟨0, ?_⟩
    ext i
    simp [coeffVector]
  add_mem' := by
    rintro v w ⟨Q, rfl⟩ ⟨R, rfl⟩
    refine ⟨Q + R, ?_⟩
    ext i
    simp [coeffVector, add_mul]
  smul_mem' := by
    rintro a v ⟨Q, rfl⟩
    refine ⟨C a * Q, ?_⟩
    ext i
    simp [coeffVector, mul_assoc]

/-- Witness polynomial obtained by deleting the first `m` zero coefficients of a vector in the
tail lattice. -/
noncomputable def tailWitness (n m : ℕ) (_hmn : m ≤ n) (v : Fin n → ℤ) : ℤ[X] :=
  Finset.sum (Finset.range (n - m)) fun j =>
    C (if h : j + m < n then v ⟨j + m, h⟩ else 0) * X ^ j

lemma coeff_tailWitness (n m : ℕ) (hmn : m ≤ n) (v : Fin n → ℤ) (d : ℕ) :
    (tailWitness n m hmn v).coeff d =
      if hd : d < n - m then v ⟨d + m, by omega⟩ else 0 := by
  by_cases hd : d < n - m
  · have hdm : d + m < n := by omega
    simp [tailWitness, hd, hdm]
  · simp [tailWitness, hd]

lemma principalIdealLattice_X_pow_eq_tailLattice (n m : ℕ) (hmn : m ≤ n) :
    principalIdealLattice n (X ^ m : ℤ[X]) = tailLattice n m := by
  ext v
  constructor
  · rintro ⟨Q, rfl⟩ i hi
    dsimp [coeffVector]
    simpa [Nat.not_le_of_lt hi] using (Polynomial.coeff_mul_X_pow' Q m i.1)
  · intro hv
    refine ⟨tailWitness n m hmn v, ?_⟩
    ext i
    dsimp [coeffVector]
    by_cases hm : m ≤ i.1
    · have hlt : i.1 - m < n - m := by omega
      rw [Polynomial.coeff_mul_X_pow']
      rw [coeff_tailWitness n m hmn v (i.1 - m)]
      simp [hm, hlt, Nat.sub_add_cancel hm]
    · rw [Polynomial.coeff_mul_X_pow']
      simp [hm, hv i (lt_of_not_ge hm)]

lemma tailLattice_shiftInvariant (n m : ℕ) : ShiftInvariant n (tailLattice n m) := by
  intro v hv i hi
  by_cases h0 : i.1 = 0
  · simp [truncatedShift_apply, truncatedShiftFun, h0]
  · have hpred : i.1 - 1 < m := by omega
    simpa [truncatedShift_apply, truncatedShiftFun, h0] using hv ⟨i.1 - 1, by omega⟩ hpred

lemma tailLattice_saturated (n m : ℕ) : Saturated (tailLattice n m) := by
  intro a ha v hav i hi
  have hmul : a * v i = 0 := by
    simpa [Pi.smul_apply] using hav i hi
  exact (mul_eq_zero.mp hmul).resolve_left ha

lemma monic_generator_of_tailLattice_eq_X_pow (n m : ℕ) (hmn : m ≤ n) {P : ℤ[X]}
    (hmonic : P.Monic) (hdeg : P.natDegree = m)
    (hP : principalIdealLattice n P = tailLattice n m) :
    P = X ^ m := by
  have hmem : coeffVector n P ∈ tailLattice n m := by
    have : coeffVector n P ∈ principalIdealLattice n P := by
      refine ⟨1, ?_⟩
      ext i
      simp [coeffVector]
    simpa [hP] using this
  ext k
  by_cases hk : k < m
  · have hk' : k < n := lt_of_lt_of_le hk hmn
    have hzero : P.coeff k = 0 := hmem ⟨k, hk'⟩ hk
    simp [Polynomial.coeff_X_pow, hk.ne, hzero]
  · by_cases hkm : k = m
    · subst hkm
      rw [Polynomial.coeff_X_pow_self]
      simpa [hdeg] using hmonic.coeff_natDegree
    · have hgt : m < k := lt_of_le_of_ne (Nat.le_of_not_gt hk) (Ne.symm hkm)
      have hzero : P.coeff k = 0 := Polynomial.coeff_eq_zero_of_natDegree_lt (by simpa [hdeg] using hgt)
      simp [Polynomial.coeff_X_pow, hkm, hzero]

/-- Concrete paper-facing model: in the truncated polynomial ring `ℤ[λ]/(λ^n)`, the saturated
shift-invariant tail lattice is exactly the principal ideal generated by `λ^m`, and this monic
generator is unique.
    thm:xi-saturated-shift-invariant-lattice-principal-ideal -/
theorem paper_xi_saturated_shift_invariant_lattice_principal_ideal (n m : ℕ) (hmn : m ≤ n) :
    let L := tailLattice n m
    ShiftInvariant n L ∧
      Saturated L ∧
      ∃! P : ℤ[X], P.Monic ∧ P.natDegree = m ∧ principalIdealLattice n P = L := by
  dsimp
  refine ⟨tailLattice_shiftInvariant n m, tailLattice_saturated n m, ?_⟩
  refine ⟨X ^ m, ?_, ?_⟩
  · exact ⟨Polynomial.monic_X_pow m, Polynomial.natDegree_X_pow m,
      principalIdealLattice_X_pow_eq_tailLattice n m hmn⟩
  · intro P hP
    rcases hP with ⟨hmonic, hdeg, hEq⟩
    exact monic_generator_of_tailLattice_eq_X_pow n m hmn hmonic hdeg hEq

end Omega.Zeta
