import Mathlib.Data.Complex.Basic
import Mathlib.Tactic
import Omega.Zeta.XiCdimLocalizationSolenoidContinuousHomClassification
import Omega.Zeta.XiCdimLocalizationSolenoidNoNontrivialTorusInput

namespace Omega.Zeta

noncomputable section

/-- Concrete finite-dimensional diagonal unitary package used as the paper-facing surrogate for a
continuous unitary representation of the localized solenoid. The single circle character is encoded
by the unit-modulus generator `characterValue`, and each coordinate is an integral power of that
generator specified by `weights`. -/
structure xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_data where
  S : Finset ℕ
  dimension : ℕ
  characterValue : ℂ
  characterValue_unit : ‖characterValue‖ = 1
  weights : Fin dimension → ℕ

/-- The circle character generated by the distinguished unit-modulus scalar. -/
def xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character
    (D :
      xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_data)
    (n : ℕ) : ℂ :=
  D.characterValue ^ n

/-- The simultaneous diagonal normal form obtained by evaluating the single character on the
integer weights of each basis vector. -/
def xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_diagonal_entry
    (D :
      xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_data)
    (n : ℕ) (i : Fin D.dimension) : ℂ :=
  xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character
    D (n * D.weights i)

/-- Paper-facing normal form statement: the localized-solenoid continuous-hom classification and
the torus-input obstruction hold for the chosen support, and the finite-dimensional unitary image
is simultaneously diagonalized by a single circle character with unit-modulus entries. -/
def xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_statement
    (D :
      xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_data) :
    Prop :=
  XiCdimLocalizationSolenoidContinuousHomClassification D.S D.S ∧
    xiCdimLocalizationSolenoidNoNontrivialTorusInput D.S D.dimension ∧
    ∃ χ : ℕ → ℂ,
      χ 0 = 1 ∧
        (∀ n m, χ (n + m) = χ n * χ m) ∧
        (∀ n i,
          xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_diagonal_entry
              D n i =
            χ (n * D.weights i)) ∧
        ∀ n i,
          ‖xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_diagonal_entry
              D n i‖ = 1

/-- Paper label: `thm:xi-cdim-localization-solenoid-finite-dimensional-unitary-single-character-
normal-form`. The existing continuous-hom classification gives the single-circle factor, the
torus-input obstruction blocks higher-rank torus inputs, and the resulting commuting circle image
is already encoded by the diagonal character powers `χ^(weights i)`. -/
theorem paper_xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form
    (D :
      xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_data) :
    xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_statement
      D := by
  refine ⟨paper_xi_cdim_localization_solenoid_continuous_hom_classification D.S D.S,
    paper_xi_cdim_localization_solenoid_no_nontrivial_torus_input D.S D.dimension, ?_⟩
  refine ⟨
    xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character
      D,
    ?_, ?_, ?_, ?_⟩
  · simp [xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character]
  · intro n m
    simp [xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character,
      pow_add]
  · intro n i
    rfl
  · intro n i
    rw [xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_diagonal_entry,
      xi_cdim_localization_solenoid_finite_dimensional_unitary_single_character_normal_form_single_character,
      norm_pow, D.characterValue_unit, one_pow]

end

end Omega.Zeta
