import Mathlib.Tactic

namespace Omega.Zeta

/-- A unit boundary-kernel centered at the integer point `a`. -/
def xiBoundaryKernelCode (a : ℤ) : ℤ → ℕ :=
  fun x => if x = a then 1 else 0

/-- A finite positive atomic measure concentrated at the integer point `a`. -/
def xiAtomicMeasure (a : ℤ) (w : ℕ) : ℤ → ℕ :=
  fun x => if x = a then w else 0

lemma xiBoundaryKernelCode_injective : Function.Injective xiBoundaryKernelCode := by
  intro a b hcode
  by_contra hab
  have hEval := congrFun hcode a
  simp [xiBoundaryKernelCode, hab] at hEval

/-- Concrete finite positive-measure data for the boundary-kernel cone. The support points are
strictly ordered so that the boundary-kernel coding is injective on atoms. -/
structure XiDefectDensityConeData where
  κ : ℕ
  atom : Fin κ → ℤ
  multiplicity : Fin κ → ℕ
  atoms_strictMono : StrictMono atom
  multiplicity_pos : ∀ j, 0 < multiplicity j

namespace XiDefectDensityConeData

/-- The coded boundary kernel attached to one atom. -/
def kernelCode (D : XiDefectDensityConeData) (j : Fin D.κ) : ℤ → ℕ :=
  xiBoundaryKernelCode (D.atom j)

/-- The Dirac ray generated by one support point. -/
def diracRay (D : XiDefectDensityConeData) (j : Fin D.κ) : ℤ → ℕ :=
  xiAtomicMeasure (D.atom j) 1

/-- The integer-weight atomic measure attached to one support point. -/
def atomicMeasure (D : XiDefectDensityConeData) (j : Fin D.κ) : ℤ → ℕ :=
  xiAtomicMeasure (D.atom j) (D.multiplicity j)

/-- Injectivity of the finite boundary-kernel coding. -/
def injectiveCoding (D : XiDefectDensityConeData) : Prop :=
  Function.Injective D.kernelCode

/-- Every extreme ray is generated by a Dirac mass at an integer point. -/
def extremeRaysAreDirac (D : XiDefectDensityConeData) : Prop :=
  ∀ j, D.kernelCode j = D.diracRay j

/-- Integer points in the cone are exactly the discrete atomic measures with positive integer
multiplicities. -/
def integerMultiplicityLattice (D : XiDefectDensityConeData) : Prop :=
  ∀ j, ∃ n : ℕ, 0 < n ∧ D.atomicMeasure j = xiAtomicMeasure (D.atom j) n

end XiDefectDensityConeData

/-- Paper label: `prop:xi-defect-density-cone-choquet-extreme`. In the concrete finite atomic
model, uniqueness of the boundary kernels makes the coding injective, the extreme rays are the
Dirac generators, and integer points are the positive integer-weight atomic measures. -/
theorem paper_xi_defect_density_cone_choquet_extreme (D : XiDefectDensityConeData) :
    D.injectiveCoding ∧ D.extremeRaysAreDirac ∧ D.integerMultiplicityLattice := by
  refine ⟨?_, ?_, ?_⟩
  · intro i j hij
    have hatom : D.atom i = D.atom j := xiBoundaryKernelCode_injective hij
    exact D.atoms_strictMono.injective hatom
  · intro j
    ext x
    simp [XiDefectDensityConeData.kernelCode, XiDefectDensityConeData.diracRay,
      xiBoundaryKernelCode, xiAtomicMeasure]
  · intro j
    exact ⟨D.multiplicity j, D.multiplicity_pos j, rfl⟩

end Omega.Zeta
