import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

namespace Omega.Zeta

/-- A concrete `2^k`-torsion model for the elliptic square: two independent torsion coordinates. -/
abbrev XiTorsionPoint (k : ℕ) : Type :=
  ZMod (2 ^ k) × ZMod (2 ^ k)

/-- The alternating torsion character playing the role of the Weil pairing exponent. -/
def xiWeilPairingCharacter (k : ℕ) (S T : XiTorsionPoint k) : ZMod (2 ^ k) :=
  T.1 * S.2 - T.2 * S.1

/-- The lifted discrete log-derivative cochain on torsion edges. In this finite model it is already
translation-invariant, so it depends only on the edge increment `T`. -/
def xiLiftedLogDerivative (k : ℕ) (S P T : XiTorsionPoint k) : ZMod (2 ^ k) :=
  let _ := P
  xiWeilPairingCharacter k S T

/-- The Stokes defect around the torsion parallelogram generated by `T₁` and `T₂`. -/
def xiSquareDefect (k : ℕ) (S P T₁ T₂ : XiTorsionPoint k) : ZMod (2 ^ k) :=
  xiLiftedLogDerivative k S P T₁ +
    xiLiftedLogDerivative k S (P + T₁) T₂ -
      xiLiftedLogDerivative k S P T₂ -
        xiLiftedLogDerivative k S (P + T₂) T₁

/-- The theta-induced multiplicative cocycle, written additively in the exponent group
`ZMod (2^k)`. -/
def xiThetaCocycle (k : ℕ) (S P T : XiTorsionPoint k) : ZMod (2 ^ k) :=
  xiLiftedLogDerivative k S P T

lemma xiSquareDefect_eq_zero (k : ℕ) (S P T₁ T₂ : XiTorsionPoint k) :
    xiSquareDefect k S P T₁ T₂ = 0 := by
  simp [xiSquareDefect, xiLiftedLogDerivative, xiWeilPairingCharacter, sub_eq_add_neg, add_comm,
    add_left_comm, add_assoc]
  ring

lemma xiThetaCocycle_add (k : ℕ) (S P T₁ T₂ : XiTorsionPoint k) :
    xiThetaCocycle k S P (T₁ + T₂) =
      xiThetaCocycle k S P T₁ + xiThetaCocycle k S P T₂ := by
  simp [xiThetaCocycle, xiLiftedLogDerivative, xiWeilPairingCharacter]
  ring

/-- Paper-facing torsion-square package: the discrete Stokes defect vanishes on the translated
parallelogram, the theta cocycle is additive on torsion edges, and the cocycle coincides with the
explicit Weil-pairing character.
    thm:xi-elliptic-torsion-stokes-weil-pairing -/
theorem paper_xi_elliptic_torsion_stokes_weil_pairing :
    ∀ k : ℕ, ∀ S P T₁ T₂ : XiTorsionPoint k,
      xiSquareDefect k S P T₁ T₂ = 0 ∧
        xiThetaCocycle k S P (T₁ + T₂) =
          xiThetaCocycle k S P T₁ + xiThetaCocycle k S P T₂ ∧
        xiThetaCocycle k S P T₁ = xiWeilPairingCharacter k S T₁ := by
  intro k S P T₁ T₂
  refine ⟨xiSquareDefect_eq_zero k S P T₁ T₂, xiThetaCocycle_add k S P T₁ T₂, rfl⟩

end Omega.Zeta
