import Mathlib.RingTheory.ClassGroup
import Mathlib.Tactic

namespace Omega.Zeta

open scoped nonZeroDivisors

noncomputable section

/-- Principal scalings of invertible fractional ideals: these are exactly the principal
fractional ideals generated by units of the fraction field. -/
def xi_hankel_invertible_ideal_subclass_pic_principal_scalings
    (R K : Type*) [CommRing R] [Field K] [Algebra R K] [IsFractionRing R K] :
    Subgroup (FractionalIdeal R⁰ K)ˣ :=
  (toPrincipalIdeal R K).range

/-- The scaled quotient of the invertible fractional-ideal subclass. -/
abbrev xi_hankel_invertible_ideal_subclass_pic_scaled_quotient
    (R K : Type*) [CommRing R] [Field K] [Algebra R K] [IsFractionRing R K] :=
  (FractionalIdeal R⁰ K)ˣ ⧸
    xi_hankel_invertible_ideal_subclass_pic_principal_scalings R K

/-- A quotient class satisfies a Hankel nonnegative-kernelization criterion when one of its
invertible fractional-ideal representatives satisfies the representative-level criterion. -/
def xi_hankel_invertible_ideal_subclass_pic_quotient_nonnegativeCriterion
    {R K : Type*} [CommRing R] [Field K] [Algebra R K] [IsFractionRing R K]
    (criterion : (FractionalIdeal R⁰ K)ˣ → Prop)
    (Q : xi_hankel_invertible_ideal_subclass_pic_scaled_quotient R K) : Prop :=
  ∃ I : (FractionalIdeal R⁰ K)ˣ,
    QuotientGroup.mk'
      (xi_hankel_invertible_ideal_subclass_pic_principal_scalings R K) I = Q ∧
      criterion I

/-- A Picard/class group class satisfies the same criterion when one of its invertible
fractional-ideal representatives maps to that class. -/
def xi_hankel_invertible_ideal_subclass_pic_picard_nonnegativeCriterion
    {R K : Type*} [CommRing R] [IsDomain R] [Field K] [Algebra R K] [IsFractionRing R K]
    (criterion : (FractionalIdeal R⁰ K)ˣ → Prop) (C : ClassGroup R) : Prop :=
  ∃ I : (FractionalIdeal R⁰ K)ˣ, ClassGroup.mk I = C ∧ criterion I

/-- Paper label: `cor:xi-hankel-invertible-ideal-subclass-pic`.
The invertible full-lattice subclass, modeled by invertible fractional ideals modulo scalar
multiplication, is the Picard/class group. Consequently any representative-level
nonnegative-kernelization criterion restates on the Picard class by transporting along this
quotient equivalence. -/
theorem paper_xi_hankel_invertible_ideal_subclass_pic
    (R K : Type*) [CommRing R] [IsDomain R] [Field K] [Algebra R K] [IsFractionRing R K]
    (criterion : (FractionalIdeal R⁰ K)ˣ → Prop) :
    Nonempty
        (ClassGroup R ≃*
          xi_hankel_invertible_ideal_subclass_pic_scaled_quotient R K) ∧
      ∀ C : ClassGroup R,
        xi_hankel_invertible_ideal_subclass_pic_picard_nonnegativeCriterion
            (R := R) (K := K) criterion C ↔
          xi_hankel_invertible_ideal_subclass_pic_quotient_nonnegativeCriterion
            (R := R) (K := K) criterion (ClassGroup.equiv K C) := by
  constructor
  · exact ⟨ClassGroup.equiv K⟩
  · intro C
    constructor
    · rintro ⟨I, hI, hcriterion⟩
      refine ⟨I, ?_, hcriterion⟩
      simpa [xi_hankel_invertible_ideal_subclass_pic_principal_scalings] using
        congrArg (ClassGroup.equiv K) hI
    · rintro ⟨I, hI, hcriterion⟩
      refine ⟨I, ?_, hcriterion⟩
      apply (ClassGroup.equiv K).injective
      simpa [xi_hankel_invertible_ideal_subclass_pic_principal_scalings] using hI

end

end Omega.Zeta
