import Mathlib.Tactic
import Omega.Zeta.XiJDiscriminant2IsogenyVelu

namespace Omega.Zeta

/-- The invariant quotient coming from translation by the rational `2`-torsion point has degree
`2`. -/
def xi_j_discriminant_translation_fixed_field_quotient_degree : ℕ := 2

/-- Concrete fixed-field packaging: the Vélu target coordinates are invariant under the partner
translation `(u, y) ↦ (B / u, -B y / u²)`, satisfy the quotient Weierstrass equation, and encode a
degree-`2` quotient. -/
def xi_j_discriminant_translation_fixed_field_quotient_statement : Prop :=
  ∀ A B u y : ℚ, B ≠ 0 → u ≠ 0 →
    xi_j_discriminant_2isogeny_velu_sourceEquation A B u y →
      xi_j_discriminant_2isogeny_velu_targetEquation A B
          (xi_j_discriminant_2isogeny_velu_xTarget A B u)
          (xi_j_discriminant_2isogeny_velu_yTarget B u y) ∧
        xi_j_discriminant_2isogeny_velu_xTarget A B
            (xi_j_discriminant_2isogeny_velu_partnerPoint B u y).1 =
          xi_j_discriminant_2isogeny_velu_xTarget A B u ∧
        xi_j_discriminant_2isogeny_velu_yTarget B
            (xi_j_discriminant_2isogeny_velu_partnerPoint B u y).1
            (xi_j_discriminant_2isogeny_velu_partnerPoint B u y).2 =
          xi_j_discriminant_2isogeny_velu_yTarget B u y ∧
        xi_j_discriminant_translation_fixed_field_quotient_degree = 2

/-- Paper label: `cor:xi-j-discriminant-translation-fixed-field-quotient`. The explicit Vélu
coordinates are invariant under translation by the rational `2`-torsion partner, land on the
quotient Weierstrass model, and package the fixed-field quotient as a degree-`2` invariant
quotient generated by those coordinates. -/
theorem paper_xi_j_discriminant_translation_fixed_field_quotient :
    xi_j_discriminant_translation_fixed_field_quotient_statement := by
  intro A B u y hB hu hsrc
  refine ⟨xi_j_discriminant_2isogeny_velu_targetEquation_of_source hu hsrc, ?_, ?_, rfl⟩
  · simpa [xi_j_discriminant_2isogeny_velu_partnerPoint] using
      (xi_j_discriminant_2isogeny_velu_x_partner (A := A) hB hu)
  · simpa [xi_j_discriminant_2isogeny_velu_partnerPoint] using
      (xi_j_discriminant_2isogeny_velu_y_partner hB hu)

end Omega.Zeta
