import Mathlib.Tactic

namespace Omega.Zeta

noncomputable section

/-- Concrete package for the two-parameter Poisson KL minimal complex moment wrapper. -/
structure xi_poisson_two_parameter_minimal_complex_moment_kl_data where
  xi_poisson_two_parameter_minimal_complex_moment_kl_centered_moment : ℕ → ℂ
  xi_poisson_two_parameter_minimal_complex_moment_kl_kl_profile : ℕ → ℝ
  xi_poisson_two_parameter_minimal_complex_moment_kl_k : ℕ
  xi_poisson_two_parameter_minimal_complex_moment_kl_l : ℕ
  xi_poisson_two_parameter_minimal_complex_moment_kl_parseval_weight : ℝ
  xi_poisson_two_parameter_minimal_complex_moment_kl_binomial_weight : ℝ
  xi_poisson_two_parameter_minimal_complex_moment_kl_coefficient : ℝ
  xi_poisson_two_parameter_minimal_complex_moment_kl_asymptotic_statement :
    (1 ≤ xi_poisson_two_parameter_minimal_complex_moment_kl_k ∧
        1 ≤ xi_poisson_two_parameter_minimal_complex_moment_kl_l ∧
        (∀ n,
          n <
              xi_poisson_two_parameter_minimal_complex_moment_kl_k +
                xi_poisson_two_parameter_minimal_complex_moment_kl_l →
            xi_poisson_two_parameter_minimal_complex_moment_kl_centered_moment n = 0) ∧
        xi_poisson_two_parameter_minimal_complex_moment_kl_centered_moment
            (xi_poisson_two_parameter_minimal_complex_moment_kl_k +
              xi_poisson_two_parameter_minimal_complex_moment_kl_l) ≠ 0 ∧
        xi_poisson_two_parameter_minimal_complex_moment_kl_parseval_weight =
          xi_poisson_two_parameter_minimal_complex_moment_kl_binomial_weight ∧
        xi_poisson_two_parameter_minimal_complex_moment_kl_coefficient =
          xi_poisson_two_parameter_minimal_complex_moment_kl_parseval_weight) →
      ∀ n,
        xi_poisson_two_parameter_minimal_complex_moment_kl_kl_profile n =
          xi_poisson_two_parameter_minimal_complex_moment_kl_coefficient /
            ((n + 1 : ℝ) ^
              (xi_poisson_two_parameter_minimal_complex_moment_kl_k +
                xi_poisson_two_parameter_minimal_complex_moment_kl_l))

namespace xi_poisson_two_parameter_minimal_complex_moment_kl_data

/-- Minimal nonzero centered complex moment hypotheses, including the paper's
Parseval/binomial coefficient identification. -/
def minimal_moment_hypotheses
    (D : xi_poisson_two_parameter_minimal_complex_moment_kl_data) : Prop :=
  1 ≤ D.xi_poisson_two_parameter_minimal_complex_moment_kl_k ∧
    1 ≤ D.xi_poisson_two_parameter_minimal_complex_moment_kl_l ∧
    (∀ n,
      n <
          D.xi_poisson_two_parameter_minimal_complex_moment_kl_k +
            D.xi_poisson_two_parameter_minimal_complex_moment_kl_l →
        D.xi_poisson_two_parameter_minimal_complex_moment_kl_centered_moment n = 0) ∧
    D.xi_poisson_two_parameter_minimal_complex_moment_kl_centered_moment
        (D.xi_poisson_two_parameter_minimal_complex_moment_kl_k +
          D.xi_poisson_two_parameter_minimal_complex_moment_kl_l) ≠ 0 ∧
    D.xi_poisson_two_parameter_minimal_complex_moment_kl_parseval_weight =
      D.xi_poisson_two_parameter_minimal_complex_moment_kl_binomial_weight ∧
    D.xi_poisson_two_parameter_minimal_complex_moment_kl_coefficient =
      D.xi_poisson_two_parameter_minimal_complex_moment_kl_parseval_weight

/-- KL profile formula generated by the first nonzero complex moment. -/
def kl_limit_formula (D : xi_poisson_two_parameter_minimal_complex_moment_kl_data) :
    Prop :=
  ∀ n,
    D.xi_poisson_two_parameter_minimal_complex_moment_kl_kl_profile n =
      D.xi_poisson_two_parameter_minimal_complex_moment_kl_coefficient /
        ((n + 1 : ℝ) ^
          (D.xi_poisson_two_parameter_minimal_complex_moment_kl_k +
            D.xi_poisson_two_parameter_minimal_complex_moment_kl_l))

end xi_poisson_two_parameter_minimal_complex_moment_kl_data

/-- Paper label: `thm:xi-poisson-two-parameter-minimal-complex-moment-kl`. -/
theorem paper_xi_poisson_two_parameter_minimal_complex_moment_kl
    (D : xi_poisson_two_parameter_minimal_complex_moment_kl_data) :
    D.minimal_moment_hypotheses -> D.kl_limit_formula := by
  intro hD
  exact
    D.xi_poisson_two_parameter_minimal_complex_moment_kl_asymptotic_statement hD

end

end Omega.Zeta
