import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic
import Omega.Zeta.XiReverseKLRadiusRenormalizationCyclicSymmetrization

open Filter
open scoped BigOperators Topology

namespace Omega.Zeta

/-- The positive reverse-KL drop produced by the chapter-local cyclic symmetrization seed. -/
noncomputable def xiReverseKLPadicCascadeSeed : ℝ :=
  xiReverseKLBaseEntropy - xiReverseKLRenormalizedEntropy

/-- The `j`-th entropy level in the concrete `p`-power cascade. -/
noncomputable def xiReverseKLPadicEntropy (p j : ℕ) : ℝ :=
  xiReverseKLPadicCascadeSeed / p ^ j

/-- The positive entropy lost between consecutive `p`-power levels. -/
noncomputable def xiReverseKLPadicLayerGap (p j : ℕ) : ℝ :=
  xiReverseKLPadicEntropy p j - xiReverseKLPadicEntropy p (j + 1)

lemma xiReverseKLPadicCascadeSeed_pos : 0 < xiReverseKLPadicCascadeSeed := by
  exact sub_pos.mpr paper_xi_reversekl_radius_renormalization_cyclic_symmetrization.2.1

/-- Paper label: `thm:xi-reversekl-padic-entropy-cascade`.
The concrete `p`-power tower generated by the chapter-local reverse-KL drop seed is antitone,
converges to `0`, and telescopes into a positive layer decomposition. -/
theorem paper_xi_reversekl_padic_entropy_cascade (p : ℕ) (hp : 2 ≤ p) :
    0 < xiReverseKLPadicCascadeSeed ∧
      Antitone (xiReverseKLPadicEntropy p) ∧
      Tendsto (xiReverseKLPadicEntropy p) atTop (𝓝 0) ∧
      (∀ j, 0 ≤ xiReverseKLPadicLayerGap p j) ∧
      (∀ n, Finset.sum (Finset.range n) (fun j => xiReverseKLPadicLayerGap p j) =
        xiReverseKLPadicCascadeSeed - xiReverseKLPadicEntropy p n) := by
  have hseed_pos : 0 < xiReverseKLPadicCascadeSeed := xiReverseKLPadicCascadeSeed_pos
  have hp1 : 1 ≤ p := le_trans (by norm_num) hp
  have hanti : Antitone (xiReverseKLPadicEntropy p) := by
    intro i j hij
    have hpow : p ^ i ≤ p ^ j := Nat.pow_le_pow_right hp1 hij
    have hcast : (p ^ i : ℝ) ≤ p ^ j := by exact_mod_cast hpow
    have hpi_pos : 0 < (p ^ i : ℝ) := by positivity
    have hpj_pos : 0 < (p ^ j : ℝ) := by positivity
    have hinv : (p ^ j : ℝ)⁻¹ ≤ (p ^ i : ℝ)⁻¹ := by
      exact (inv_le_inv₀ hpj_pos hpi_pos).2 hcast
    have hmul := mul_le_mul_of_nonneg_left hinv (le_of_lt hseed_pos)
    simpa [xiReverseKLPadicEntropy, div_eq_mul_inv, mul_comm, mul_left_comm, mul_assoc] using hmul
  have hlimit : Tendsto (xiReverseKLPadicEntropy p) atTop (𝓝 0) := by
    have hp0 : (0 : ℝ) < p := by
      exact_mod_cast lt_of_lt_of_le (by norm_num : 0 < (2 : ℕ)) hp
    have hp_real : (1 : ℝ) < p := by
      exact_mod_cast lt_of_lt_of_le (by norm_num : 1 < (2 : ℕ)) hp
    have hlt : (p : ℝ)⁻¹ < 1 := by
      exact inv_lt_one_of_one_lt₀ hp_real
    have hpow :
        Tendsto (fun j : ℕ => ((p : ℝ)⁻¹) ^ j) atTop (𝓝 0) := by
      exact tendsto_pow_atTop_nhds_zero_of_lt_one (by positivity) hlt
    have hmul : Tendsto (fun j : ℕ => xiReverseKLPadicCascadeSeed * ((p : ℝ)⁻¹) ^ j) atTop (𝓝 0) := by
      simpa using (Tendsto.const_mul xiReverseKLPadicCascadeSeed hpow)
    have hEq :
        (fun j : ℕ => xiReverseKLPadicEntropy p j) =
          fun j => xiReverseKLPadicCascadeSeed * ((p : ℝ)⁻¹) ^ j := by
      funext j
      rw [xiReverseKLPadicEntropy, div_eq_mul_inv]
      simp [inv_pow]
    simpa [hEq] using hmul
  have hgap_nonneg : ∀ j, 0 ≤ xiReverseKLPadicLayerGap p j := by
    intro j
    exact sub_nonneg.mpr (hanti (Nat.le_succ j))
  refine ⟨hseed_pos, hanti, hlimit, hgap_nonneg, ?_⟩
  intro n
  induction n with
  | zero =>
      simp [xiReverseKLPadicLayerGap, xiReverseKLPadicEntropy]
  | succ n ih =>
      rw [Finset.sum_range_succ, ih, xiReverseKLPadicLayerGap]
      ring

end Omega.Zeta
