import Mathlib.Data.Matrix.Basic
import Mathlib.Tactic

namespace Omega.Zeta

/-- Concrete finite integer-matrix package for the RH holonomy curvature criterion.  Rows are the
finite critical-square defects and columns are the chosen central integer coordinates. -/
structure xi_rh_finite_curvature_matrix_criterion_data where
  xi_rh_finite_curvature_matrix_criterion_row_count : ℕ
  xi_rh_finite_curvature_matrix_criterion_column_count : ℕ
  xi_rh_finite_curvature_matrix_criterion_matrix :
    Matrix (Fin xi_rh_finite_curvature_matrix_criterion_row_count)
      (Fin xi_rh_finite_curvature_matrix_criterion_column_count) ℤ
  xi_rh_finite_curvature_matrix_criterion_gauged_matrix :
    Matrix (Fin xi_rh_finite_curvature_matrix_criterion_row_count)
      (Fin xi_rh_finite_curvature_matrix_criterion_column_count) ℤ
  xi_rh_finite_curvature_matrix_criterion_holonomy :
    Set (Fin xi_rh_finite_curvature_matrix_criterion_column_count → ℤ)
  xi_rh_finite_curvature_matrix_criterion_generates :
    ∀ z,
      z ∈ xi_rh_finite_curvature_matrix_criterion_holonomy →
        ∃ coeff : Fin xi_rh_finite_curvature_matrix_criterion_row_count → ℤ,
          z =
            fun j =>
              ∑ i,
                coeff i * xi_rh_finite_curvature_matrix_criterion_matrix i j
  xi_rh_finite_curvature_matrix_criterion_row_in_holonomy :
    ∀ i,
      (fun j => xi_rh_finite_curvature_matrix_criterion_matrix i j) ∈
        xi_rh_finite_curvature_matrix_criterion_holonomy
  xi_rh_finite_curvature_matrix_criterion_gauge_eq :
    ∀ i j,
      xi_rh_finite_curvature_matrix_criterion_gauged_matrix i j =
        xi_rh_finite_curvature_matrix_criterion_matrix i j

/-- The finite defect matrix is the zero integer matrix. -/
def xi_rh_finite_curvature_matrix_criterion_matrix_zero
    (D : xi_rh_finite_curvature_matrix_criterion_data) : Prop :=
  ∀ i j, D.xi_rh_finite_curvature_matrix_criterion_matrix i j = 0

/-- The holonomy subgroup generated by the finite critical-square defects is zero. -/
def xi_rh_finite_curvature_matrix_criterion_holonomy_zero
    (D : xi_rh_finite_curvature_matrix_criterion_data) : Prop :=
  ∀ z,
    z ∈ D.xi_rh_finite_curvature_matrix_criterion_holonomy →
      z = 0

/-- In one central coordinate, checking the scalar defect entries is the same as checking that the
whole finite curvature matrix is zero. -/
def xi_rh_finite_curvature_matrix_criterion_scalar_defect_zero_test
    (D : xi_rh_finite_curvature_matrix_criterion_data) : Prop :=
  ∀ hcol : D.xi_rh_finite_curvature_matrix_criterion_column_count = 1,
    ((∀ i,
        D.xi_rh_finite_curvature_matrix_criterion_matrix i
          (Fin.cast hcol.symm (0 : Fin 1)) = 0) ↔
      xi_rh_finite_curvature_matrix_criterion_matrix_zero D)

/-- Zero curvature is invariant under the recorded gauge-coordinate change. -/
def xi_rh_finite_curvature_matrix_criterion_gauge_invariant
    (D : xi_rh_finite_curvature_matrix_criterion_data) : Prop :=
  ((∀ i j, D.xi_rh_finite_curvature_matrix_criterion_gauged_matrix i j = 0) ↔
    xi_rh_finite_curvature_matrix_criterion_matrix_zero D)

/-- Paper-facing finite matrix criterion: finite generation identifies holonomy vanishing with
zero integer curvature matrix, the scalar one-coordinate test is exact, and gauge choice does not
change the zero test. -/
def xi_rh_finite_curvature_matrix_criterion_statement
    (D : xi_rh_finite_curvature_matrix_criterion_data) : Prop :=
  (xi_rh_finite_curvature_matrix_criterion_matrix_zero D ↔
      xi_rh_finite_curvature_matrix_criterion_holonomy_zero D) ∧
    xi_rh_finite_curvature_matrix_criterion_scalar_defect_zero_test D ∧
      xi_rh_finite_curvature_matrix_criterion_gauge_invariant D

/-- Paper label: `prop:xi-rh-finite-curvature-matrix-criterion`. -/
theorem paper_xi_rh_finite_curvature_matrix_criterion
    (D : xi_rh_finite_curvature_matrix_criterion_data) :
    xi_rh_finite_curvature_matrix_criterion_statement D := by
  refine ⟨?_, ?_, ?_⟩
  · constructor
    · intro hzero z hz
      obtain ⟨coeff, rfl⟩ :=
        D.xi_rh_finite_curvature_matrix_criterion_generates z hz
      funext j
      calc
        ∑ i, coeff i * D.xi_rh_finite_curvature_matrix_criterion_matrix i j =
            ∑ _i, 0 := by
          apply Finset.sum_congr rfl
          intro i _hi
          simp [hzero i j]
        _ = 0 := by simp
    · intro hhol i j
      have hrow :=
        hhol (fun j => D.xi_rh_finite_curvature_matrix_criterion_matrix i j)
          (D.xi_rh_finite_curvature_matrix_criterion_row_in_holonomy i)
      exact congrFun hrow j
  · intro hcol
    constructor
    · intro hscalar i j
      have hj : j = Fin.cast hcol.symm (0 : Fin 1) := by
        ext
        omega
      simpa [hj] using hscalar i
    · intro hzero i
      exact hzero i (Fin.cast hcol.symm (0 : Fin 1))
  · constructor
    · intro hgauge i j
      rw [← D.xi_rh_finite_curvature_matrix_criterion_gauge_eq i j]
      exact hgauge i j
    · intro hzero i j
      rw [D.xi_rh_finite_curvature_matrix_criterion_gauge_eq i j]
      exact hzero i j

end Omega.Zeta
