import Mathlib.Tactic

namespace Omega.Zeta

universe u

/-- Concrete scale-time connection data on a family of oriented squares.  Each square records the
four directed edge increments: top and bottom run left-to-right, while left and right run
top-to-bottom. -/
structure xi_scale_time_connection_holonomy_criterion_data where
  xi_scale_time_connection_holonomy_criterion_square : Type u
  xi_scale_time_connection_holonomy_criterion_top :
    xi_scale_time_connection_holonomy_criterion_square → ℤ
  xi_scale_time_connection_holonomy_criterion_right :
    xi_scale_time_connection_holonomy_criterion_square → ℤ
  xi_scale_time_connection_holonomy_criterion_bottom :
    xi_scale_time_connection_holonomy_criterion_square → ℤ
  xi_scale_time_connection_holonomy_criterion_left :
    xi_scale_time_connection_holonomy_criterion_square → ℤ

namespace xi_scale_time_connection_holonomy_criterion_data

/-- The oriented square holonomy `top + right - bottom - left`. -/
def squareHolonomy (D : xi_scale_time_connection_holonomy_criterion_data)
    (s : D.xi_scale_time_connection_holonomy_criterion_square) : ℤ :=
  D.xi_scale_time_connection_holonomy_criterion_top s +
    D.xi_scale_time_connection_holonomy_criterion_right s -
      D.xi_scale_time_connection_holonomy_criterion_bottom s -
        D.xi_scale_time_connection_holonomy_criterion_left s

/-- The additive subgroup generated by all square holonomies. -/
def generatedHolonomySubgroup (D : xi_scale_time_connection_holonomy_criterion_data) :
    AddSubgroup ℤ :=
  AddSubgroup.closure (Set.range D.squareHolonomy)

/-- Triviality of the subgroup generated by the square holonomies. -/
def holonomySubgroupTrivial (D : xi_scale_time_connection_holonomy_criterion_data) : Prop :=
  D.generatedHolonomySubgroup = ⊥

/-- A global unified time is a compatible choice of corner times on each recorded square whose
edge differences recover the connection increments. -/
def globalUnifiedTime (D : xi_scale_time_connection_holonomy_criterion_data) : Prop :=
  ∃ time00 time10 time01 time11 :
      D.xi_scale_time_connection_holonomy_criterion_square → ℤ,
    ∀ s,
      D.xi_scale_time_connection_holonomy_criterion_top s = time10 s - time00 s ∧
        D.xi_scale_time_connection_holonomy_criterion_right s = time11 s - time10 s ∧
          D.xi_scale_time_connection_holonomy_criterion_bottom s = time11 s - time01 s ∧
            D.xi_scale_time_connection_holonomy_criterion_left s = time01 s - time00 s

private theorem xi_scale_time_connection_holonomy_criterion_zero_of_global
    (D : xi_scale_time_connection_holonomy_criterion_data) (hglobal : D.globalUnifiedTime) :
    ∀ s, D.squareHolonomy s = 0 := by
  rcases hglobal with ⟨time00, time10, time01, time11, htime⟩
  intro s
  rcases htime s with ⟨htop, hright, hbottom, hleft⟩
  rw [squareHolonomy, htop, hright, hbottom, hleft]
  ring

private theorem xi_scale_time_connection_holonomy_criterion_global_of_zero
    (D : xi_scale_time_connection_holonomy_criterion_data)
    (hzero : ∀ s, D.squareHolonomy s = 0) :
    D.globalUnifiedTime := by
  refine ⟨fun _ => 0, D.xi_scale_time_connection_holonomy_criterion_top,
    D.xi_scale_time_connection_holonomy_criterion_left,
    fun s => D.xi_scale_time_connection_holonomy_criterion_top s +
      D.xi_scale_time_connection_holonomy_criterion_right s, ?_⟩
  intro s
  have hs := hzero s
  rw [squareHolonomy] at hs
  constructor
  · simp
  constructor
  · simp
  constructor
  ·
    change
      D.xi_scale_time_connection_holonomy_criterion_bottom s =
        D.xi_scale_time_connection_holonomy_criterion_top s +
            D.xi_scale_time_connection_holonomy_criterion_right s -
          D.xi_scale_time_connection_holonomy_criterion_left s
    omega
  · simp

private theorem xi_scale_time_connection_holonomy_criterion_zero_iff_trivial
    (D : xi_scale_time_connection_holonomy_criterion_data) :
    (∀ s, D.squareHolonomy s = 0) ↔ D.holonomySubgroupTrivial := by
  constructor
  · intro hzero
    apply le_antisymm
    · rw [generatedHolonomySubgroup, AddSubgroup.closure_le]
      intro z hz
      rcases hz with ⟨s, rfl⟩
      simp [hzero s]
    · exact bot_le
  · intro htrivial s
    have hmem : D.squareHolonomy s ∈ D.generatedHolonomySubgroup :=
      AddSubgroup.subset_closure ⟨s, rfl⟩
    rw [holonomySubgroupTrivial] at htrivial
    have hbot : D.squareHolonomy s ∈ (⊥ : AddSubgroup ℤ) := by
      rw [← htrivial]
      exact hmem
    simpa using hbot

end xi_scale_time_connection_holonomy_criterion_data

/-- Paper label: `thm:xi-scale-time-connection-holonomy-criterion`.  For concrete square
connection data, compatible square-corner time gauges exist exactly when the subgroup generated by
the square holonomies is trivial. -/
theorem paper_xi_scale_time_connection_holonomy_criterion
    (D : xi_scale_time_connection_holonomy_criterion_data) :
    D.globalUnifiedTime ↔ D.holonomySubgroupTrivial := by
  constructor
  · intro hglobal
    exact
      (xi_scale_time_connection_holonomy_criterion_data.xi_scale_time_connection_holonomy_criterion_zero_iff_trivial D).mp
        (xi_scale_time_connection_holonomy_criterion_data.xi_scale_time_connection_holonomy_criterion_zero_of_global D hglobal)
  · intro htrivial
    exact
      xi_scale_time_connection_holonomy_criterion_data.xi_scale_time_connection_holonomy_criterion_global_of_zero D
        ((xi_scale_time_connection_holonomy_criterion_data.xi_scale_time_connection_holonomy_criterion_zero_iff_trivial D).mpr htrivial)

end Omega.Zeta
