import Mathlib.Order.ConditionallyCompleteLattice.Basic
import Mathlib.Tactic

namespace Omega.Zeta

noncomputable section

/-- Pressure variational expression generated by the tail entropy. -/
def xi_tail_entropy_pressure_capacity_variational_pressureSup
    (alphaStar : ℝ) (tailEntropy : ℝ → ℝ) (q : ℝ) : ℝ :=
  sSup
    (Set.range fun γ : {γ : ℝ // 0 ≤ γ ∧ γ ≤ alphaStar} =>
      q * (γ : ℝ) + tailEntropy (γ : ℝ))

/-- Capacity variational expression generated by the same tail entropy on the truncated interval. -/
def xi_tail_entropy_pressure_capacity_variational_capacitySup
    (alphaStar : ℝ) (tailEntropy : ℝ → ℝ) (β : ℝ) : ℝ :=
  sSup
    (Set.range fun γ : {γ : ℝ // 0 ≤ γ ∧ γ ≤ min β alphaStar} =>
      (γ : ℝ) + tailEntropy (γ : ℝ))

/-- Concrete conclusion: the integral identities and the pressure/capacity Laplace principles. -/
def xi_tail_entropy_pressure_capacity_variational_conclusion
    (continuousCapacity capacityIntegral mellinMoment mellinIntegral : ℕ → ℝ → ℝ)
    (alphaStar : ℝ) (tailEntropy pressure capacityExponent : ℝ → ℝ) : Prop :=
  (∀ m : ℕ, ∀ T : ℝ, continuousCapacity m T = capacityIntegral m T) ∧
    (∀ m : ℕ, ∀ q : ℝ, 0 < q → mellinMoment m q = mellinIntegral m q) ∧
      (∀ q : ℝ,
        0 < q →
          pressure q =
            xi_tail_entropy_pressure_capacity_variational_pressureSup alphaStar tailEntropy q) ∧
        ∀ β : ℝ,
          0 ≤ β →
            capacityExponent β =
              xi_tail_entropy_pressure_capacity_variational_capacitySup alphaStar tailEntropy β

/-- Paper label: `thm:xi-tail-entropy-pressure-capacity-variational`.
The Mellin and capacity identities reduce both spectra to finite-interval Laplace principles:
one on the full interval `[0, α_*]`, and one on the truncated interval `[0, min β α_*]`. -/
theorem paper_xi_tail_entropy_pressure_capacity_variational
    (continuousCapacity capacityIntegral mellinMoment mellinIntegral : ℕ → ℝ → ℝ)
    (alphaStar : ℝ) (tailEntropy pressure capacityExponent : ℝ → ℝ)
    (capacity_identity :
      ∀ m : ℕ, ∀ T : ℝ, continuousCapacity m T = capacityIntegral m T)
    (mellin_identity :
      ∀ m : ℕ, ∀ q : ℝ, 0 < q → mellinMoment m q = mellinIntegral m q)
    (pressure_laplace :
      ∀ q : ℝ,
        0 < q →
          pressure q =
            xi_tail_entropy_pressure_capacity_variational_pressureSup alphaStar tailEntropy q)
    (capacity_laplace :
      ∀ β : ℝ,
        0 ≤ β →
          capacityExponent β =
            xi_tail_entropy_pressure_capacity_variational_capacitySup alphaStar tailEntropy β) :
    xi_tail_entropy_pressure_capacity_variational_conclusion
      continuousCapacity capacityIntegral mellinMoment mellinIntegral alphaStar tailEntropy
        pressure capacityExponent := by
  exact ⟨capacity_identity, mellin_identity, pressure_laplace, capacity_laplace⟩

end

end Omega.Zeta
