import Mathlib.Tactic
import Omega.POM.BCQuotientUniversal
import Omega.POM.BCVisibleQuotientEventualStability

namespace Omega.Zeta

universe u v w

/-- Generating relation for the stabilized BC quotient. -/
def xi_terminal_gbc_stabilized_terminal_object_generator {α : Type u} {β : Type v}
    (leftMap rightMap : α → β) : β → β → Prop :=
  fun x y => ∃ a, x = leftMap a ∧ y = rightMap a

/-- Setoid generated by the BC relations. -/
def xi_terminal_gbc_stabilized_terminal_object_setoid {α : Type u} {β : Type v}
    (leftMap rightMap : α → β) : Setoid β :=
  Relation.EqvGen.setoid
    (xi_terminal_gbc_stabilized_terminal_object_generator leftMap rightMap)

/-- The stabilized BC quotient. -/
abbrev xi_terminal_gbc_stabilized_terminal_object_bc_quotient {α : Type u} {β : Type v}
    (leftMap rightMap : α → β) :=
  Quotient (xi_terminal_gbc_stabilized_terminal_object_setoid leftMap rightMap)

/-- Canonical projection to the stabilized BC quotient. -/
def xi_terminal_gbc_stabilized_terminal_object_projection {α : Type u} {β : Type v}
    (leftMap rightMap : α → β) :
    β → xi_terminal_gbc_stabilized_terminal_object_bc_quotient leftMap rightMap :=
  Quotient.mk (xi_terminal_gbc_stabilized_terminal_object_setoid leftMap rightMap)

/-- Paper label: `thm:xi-terminal-gbc-stabilized-terminal-object`.
The eventual stabilization stage of the finite BC quotient chain can be promoted to a terminal
stage: once the subgroup chain stabilizes, choosing `M = max m_π m₀` preserves stabilization, and
the strictly commuting quotient map factors uniquely through the stabilized BC quotient. -/
theorem paper_xi_terminal_gbc_stabilized_terminal_object
    {G : Type*} [Group G] [Fintype G]
    {α : Type u} {β : Type v} {γ : Type w}
    (N : ℕ → Subgroup G) (hmono : ∀ m, N (m + 1) ≤ N m)
    (m0 : ℕ)
    (leftMap rightMap : α → β) (quotientMap : β → γ)
    (hstrict : ∀ a, quotientMap (leftMap a) = quotientMap (rightMap a)) :
    ∃ mπ M : ℕ,
      M = max mπ m0 ∧
      (∀ m ≥ mπ, N m = N mπ) ∧
      (∀ m ≥ M, N m = N M) ∧
      ∃! f : xi_terminal_gbc_stabilized_terminal_object_bc_quotient leftMap rightMap → γ,
        ∀ x, f (xi_terminal_gbc_stabilized_terminal_object_projection leftMap rightMap x) =
          quotientMap x := by
  obtain ⟨mπ, hmπ⟩ := Omega.POM.paper_pom_bc_visible_quotient_eventual_stability N hmono
  let D : Omega.POM.BCQuotientUniversalData :=
    { α := α
      β := β
      γ := γ
      leftMap := leftMap
      rightMap := rightMap
      quotientMap := quotientMap
      strictlyCommutes := hstrict }
  have hfactor : D.factorsThroughBCQuotient :=
    (Omega.POM.paper_pom_bc_quotient_universal D).2
  refine ⟨mπ, max mπ m0, rfl, hmπ, ?_, ?_⟩
  · intro m hm
    have hmπ_le : mπ ≤ m := le_trans (le_max_left mπ m0) hm
    have hMπ : N (max mπ m0) = N mπ := hmπ _ (le_max_left mπ m0)
    calc
      N m = N mπ := hmπ _ hmπ_le
      _ = N (max mπ m0) := hMπ.symm
  · simpa [Omega.POM.BCQuotientUniversalData.factorsThroughBCQuotient,
      xi_terminal_gbc_stabilized_terminal_object_bc_quotient,
      xi_terminal_gbc_stabilized_terminal_object_projection,
      xi_terminal_gbc_stabilized_terminal_object_setoid,
      xi_terminal_gbc_stabilized_terminal_object_generator,
      Omega.POM.BCQuotientUniversalData.BCQuotient,
      Omega.POM.BCQuotientUniversalData.bcProjection,
      Omega.POM.BCQuotientUniversalData.bcSetoid,
      Omega.POM.BCQuotientUniversalData.bcGenerator, D] using hfactor

end Omega.Zeta
