import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Tactic

namespace Omega.Zeta

open scoped BigOperators

/-- Concrete data for the equal-value Fibonacci partition aggregation formula.

The multiplicity vector records a base partition of `m`; the integer interval `[sMin, sMax]`
parametrizes the collision class generated by replacing `(4,4,2,2)` with `(10,1,1)`. -/
structure xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data where
  m : ℕ
  multiplicity : ℕ → ℕ
  sMin : ℤ
  sMax : ℤ

namespace xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data

/-- The finite integer interval of collision parameters. -/
def partitionInterval
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) : Finset ℤ :=
  Finset.Icc D.sMin D.sMax

/-- Multiplicities after moving `s` steps along the Fibonacci collision line. -/
def shiftedMultiplicity
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) (s : ℤ)
    (r : ℕ) : ℕ :=
  if r = 1 then Int.toNat ((D.multiplicity 1 : ℤ) + 2 * s)
  else if r = 2 then Int.toNat ((D.multiplicity 2 : ℤ) - 2 * s)
  else if r = 4 then Int.toNat ((D.multiplicity 4 : ℤ) - 2 * s)
  else if r = 10 then Int.toNat ((D.multiplicity 10 : ℤ) + s)
  else D.multiplicity r

/-- Total number of parts in the partition indexed by `s`. -/
def partCount
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) (s : ℤ) : ℕ :=
  ∑ r ∈ Finset.Icc 1 D.m, D.shiftedMultiplicity s r

/-- Closed-form coefficient of the partition indexed by `s`. -/
def coefficient
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) (s : ℤ) : ℚ :=
  (D.m : ℚ) * (Nat.factorial (D.partCount s - 1) : ℚ) /
    ∏ r ∈ Finset.Icc 1 D.m, (Nat.factorial (D.shiftedMultiplicity s r) : ℚ)

/-- Aggregated coefficient over the integer interval parametrizing one equal-value class. -/
def aggregatedCoeff
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) : ℚ :=
  ∑ s ∈ D.partitionInterval, D.coefficient s

end xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data

/-- The paper statement: the aggregate coefficient is the finite interval sum of the closed-form
partition coefficients along the Fibonacci collision class. -/
def xi_terminal_replica_softcore_partition_fib_aggregated_coeff_statement
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) : Prop :=
  D.aggregatedCoeff = ∑ s ∈ D.partitionInterval, D.coefficient s

/-- Paper label: `prop:xi-terminal-replica-softcore-partition-fib-aggregated-coeff`. -/
theorem paper_xi_terminal_replica_softcore_partition_fib_aggregated_coeff
    (D : xi_terminal_replica_softcore_partition_fib_aggregated_coeff_data) :
    xi_terminal_replica_softcore_partition_fib_aggregated_coeff_statement D := by
  rfl

end Omega.Zeta
