import Mathlib.Data.Finset.Card
import Mathlib.Tactic
import Omega.Zeta.XiTimePart9vkResonanceShadowFiniteStepPoleGeneration

open scoped BigOperators

namespace Omega.Zeta

/-- Concrete rational-depth data for the scalar continued-fraction splitting. -/
structure xi_time_part9vk_scalar_continued_fraction_depth_splitting_data where
  S : ℕ → ℂ → ℂ
  term : ℕ → ℂ → ℂ
  hS1 : S 1 = term 2
  hrec : ∀ N, 1 ≤ N → S (N + 1) = fun z => S N z + term (N + 2) z

namespace xi_time_part9vk_scalar_continued_fraction_depth_splitting_data

/-- The fold-side scalar shadow has the two finite poles recorded by the rational shadow. -/
def xi_time_part9vk_scalar_continued_fraction_depth_splitting_fold_poles :
    Finset ℕ :=
  {0, 1}

/-- The fold shadow has exactly two finite poles. -/
def fold_depth_eq_two
    (_D : xi_time_part9vk_scalar_continued_fraction_depth_splitting_data) : Prop :=
  xi_time_part9vk_scalar_continued_fraction_depth_splitting_fold_poles.card = 2

/-- The finite-step resonance shadow is generated by the expected interval of pole terms. -/
def resonance_no_terminating_cf
    (D : xi_time_part9vk_scalar_continued_fraction_depth_splitting_data) : Prop :=
  ∀ N, 1 ≤ N → D.S N = fun z => ∑ n ∈ Finset.Icc 2 (N + 1), D.term n z

/-- The two-pole fold side and the finite-step resonance side cannot be bridged by a terminating
continued fraction in this scalar shadow model. -/
def depth_barrier
    (D : xi_time_part9vk_scalar_continued_fraction_depth_splitting_data) : Prop :=
  D.fold_depth_eq_two ∧ D.resonance_no_terminating_cf

end xi_time_part9vk_scalar_continued_fraction_depth_splitting_data

/-- Paper label: `prop:xi-time-part9vk-scalar-continued-fraction-depth-splitting`. -/
theorem paper_xi_time_part9vk_scalar_continued_fraction_depth_splitting
    (D : xi_time_part9vk_scalar_continued_fraction_depth_splitting_data) :
    D.fold_depth_eq_two ∧ D.resonance_no_terminating_cf ∧ D.depth_barrier := by
  have hfold : D.fold_depth_eq_two := by
    change
      xi_time_part9vk_scalar_continued_fraction_depth_splitting_data.xi_time_part9vk_scalar_continued_fraction_depth_splitting_fold_poles.card =
        2
    native_decide
  have hres : D.resonance_no_terminating_cf :=
    paper_xi_time_part9vk_resonance_shadow_finite_step_pole_generation D.S D.term D.hS1 D.hrec
  exact ⟨hfold, hres, hfold, hres⟩

end Omega.Zeta
