import Mathlib.Analysis.Complex.Exponential
import Mathlib.Tactic
import Omega.Core.OdometerJoukowsky

namespace Omega.Zeta

open scoped BigOperators

noncomputable section

/-- Concrete finite-support probability data for the Fourier--Joukowsky generation package. -/
structure xi_time_part60ae_fourier_joukowsky_generation_principle_data where
  xi_time_part60ae_fourier_joukowsky_generation_principle_support : Finset ℤ
  xi_time_part60ae_fourier_joukowsky_generation_principle_weight : ℤ → ℝ
  xi_time_part60ae_fourier_joukowsky_generation_principle_weight_nonneg :
    ∀ n ∈ xi_time_part60ae_fourier_joukowsky_generation_principle_support,
      0 ≤ xi_time_part60ae_fourier_joukowsky_generation_principle_weight n
  xi_time_part60ae_fourier_joukowsky_generation_principle_total_mass :
    Finset.sum xi_time_part60ae_fourier_joukowsky_generation_principle_support
      (fun n => xi_time_part60ae_fourier_joukowsky_generation_principle_weight n) = 1
  xi_time_part60ae_fourier_joukowsky_generation_principle_carrierFrequency : ℝ
  xi_time_part60ae_fourier_joukowsky_generation_principle_roseFrequency : ℝ
  xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyX : ℝ
  xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyY : ℝ

/-- Finite characteristic function attached to the packaged probability table. -/
def xi_time_part60ae_fourier_joukowsky_generation_principle_characteristicFunction
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) (t : ℝ) : ℂ :=
  Finset.sum D.xi_time_part60ae_fourier_joukowsky_generation_principle_support fun n =>
    (D.xi_time_part60ae_fourier_joukowsky_generation_principle_weight n : ℂ) *
      Complex.exp ((((n : ℝ) * t : ℝ) : ℂ) * Complex.I)

/-- The same finite sum, read as the Fourier expansion. -/
def xi_time_part60ae_fourier_joukowsky_generation_principle_fourierExpansion
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) (t : ℝ) : ℂ :=
  Finset.sum D.xi_time_part60ae_fourier_joukowsky_generation_principle_support fun n =>
    (D.xi_time_part60ae_fourier_joukowsky_generation_principle_weight n : ℂ) *
      Complex.exp ((((n : ℝ) * t : ℝ) : ℂ) * Complex.I)

/-- Normalized Joukowsky gate `J(z)/2`. -/
def xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky
    (z : ℂ) : ℂ :=
  (1 / 2 : ℂ) * Omega.POM.joukowsky z

/-- Rose curve generated by multiplying the carrier phase by the normalized Joukowsky cosine gate. -/
def xi_time_part60ae_fourier_joukowsky_generation_principle_roseCurve
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) (t : ℝ) : ℂ :=
  Complex.exp
      (((D.xi_time_part60ae_fourier_joukowsky_generation_principle_carrierFrequency * t : ℝ) :
          ℂ) * Complex.I) *
    xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky
      (Complex.exp
        (((D.xi_time_part60ae_fourier_joukowsky_generation_principle_roseFrequency * t : ℝ) :
            ℂ) * Complex.I))

/-- Lissajous pair obtained by applying the normalized Joukowsky gate in both coordinates. -/
def xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousJoukowsky
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) (t : ℝ) : ℂ × ℂ :=
  (xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky
      (Complex.exp
        (((D.xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyX * t :
            ℝ) : ℂ) * Complex.I)),
    xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky
      (Complex.exp
        (((D.xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyY * t :
            ℝ) : ℂ) * Complex.I)))

namespace xi_time_part60ae_fourier_joukowsky_generation_principle_data

/-- The characteristic function is exactly its finite Fourier expansion. -/
def characteristicFunctionRealization
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) : Prop :=
  ∀ t : ℝ,
    xi_time_part60ae_fourier_joukowsky_generation_principle_characteristicFunction D t =
      xi_time_part60ae_fourier_joukowsky_generation_principle_fourierExpansion D t

/-- Euler's identity turns the normalized Joukowsky gate into the rose cosine factor. -/
def roseIdentity
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) : Prop :=
  ∀ t : ℝ,
    xi_time_part60ae_fourier_joukowsky_generation_principle_roseCurve D t =
      Complex.exp
          (((D.xi_time_part60ae_fourier_joukowsky_generation_principle_carrierFrequency * t :
              ℝ) : ℂ) * Complex.I) *
        (Real.cos
          (D.xi_time_part60ae_fourier_joukowsky_generation_principle_roseFrequency * t) : ℂ)

/-- Coordinatewise normalized Joukowsky turns the unit-circle Lissajous lift into cosines. -/
def lissajousJoukowskyFactorization
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) : Prop :=
  ∀ t : ℝ,
    xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousJoukowsky D t =
      ((Real.cos
          (D.xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyX * t) :
            ℂ),
        (Real.cos
          (D.xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousFrequencyY * t) :
            ℂ))

end xi_time_part60ae_fourier_joukowsky_generation_principle_data

lemma xi_time_part60ae_fourier_joukowsky_generation_principle_normalized_exp
    (θ : ℝ) :
    xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky
        (Complex.exp ((θ : ℂ) * Complex.I)) =
      (Real.cos θ : ℂ) := by
  rw [xi_time_part60ae_fourier_joukowsky_generation_principle_normalizedJoukowsky,
    Omega.POM.joukowsky_exp_I_mul]
  ring

/-- Paper label: `thm:xi-time-part60ae-fourier-joukowsky-generation-principle`. -/
theorem paper_xi_time_part60ae_fourier_joukowsky_generation_principle
    (D : xi_time_part60ae_fourier_joukowsky_generation_principle_data) :
    D.characteristicFunctionRealization ∧ D.roseIdentity ∧
      D.lissajousJoukowskyFactorization := by
  refine ⟨?_, ?_, ?_⟩
  · intro t
    rfl
  · intro t
    rw [xi_time_part60ae_fourier_joukowsky_generation_principle_roseCurve,
      xi_time_part60ae_fourier_joukowsky_generation_principle_normalized_exp]
  · intro t
    rw [xi_time_part60ae_fourier_joukowsky_generation_principle_lissajousJoukowsky,
      xi_time_part60ae_fourier_joukowsky_generation_principle_normalized_exp,
      xi_time_part60ae_fourier_joukowsky_generation_principle_normalized_exp]

end

end Omega.Zeta
