import Mathlib.Data.Rat.Lemmas
import Mathlib.Tactic

namespace Omega.Zeta

/-- Concrete finite-frequency data for
`thm:xi-time-part65g-frequency-prime-support-kernel-recovery`. The support field is tied to the
actual rational denominators by `..._denominator_prime_support_spec`. -/
structure xi_time_part65g_frequency_prime_support_kernel_recovery_data where
  xi_time_part65g_frequency_prime_support_kernel_recovery_frequency : List ℚ
  xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support : Finset ℕ
  xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support_spec :
    ∀ p : ℕ,
      p ∈ xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support ↔
        p.Prime ∧
          ∃ q ∈ xi_time_part65g_frequency_prime_support_kernel_recovery_frequency, p ∣ q.den

namespace xi_time_part65g_frequency_prime_support_kernel_recovery_data

/-- The prime support of the root-closed carrier generated by the finite frequency family. -/
def xi_time_part65g_frequency_prime_support_kernel_recovery_root_closed_carrier
    (D : xi_time_part65g_frequency_prime_support_kernel_recovery_data) : Finset ℕ :=
  D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support

/-- The valuation-depth maximum over the finite frequency list, truncated to detecting whether a
prime occurs with positive denominator valuation. -/
def xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max
    (p : ℕ) : List ℚ → ℕ
  | [] => 0
  | q :: qs =>
      max (if p.Prime ∧ p ∣ q.den then 1 else 0)
        (xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p qs)

/-- The common prime-register kernel detects exactly positive valuation depth in this finite
model. -/
def xi_time_part65g_frequency_prime_support_kernel_recovery_common_kernel_detects_prime
    (D : xi_time_part65g_frequency_prime_support_kernel_recovery_data) (p : ℕ) : Prop :=
  1 ≤
    xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p
      D.xi_time_part65g_frequency_prime_support_kernel_recovery_frequency

private lemma xi_time_part65g_frequency_prime_support_kernel_recovery_depth_pos_iff
    (p : ℕ) :
    ∀ qs : List ℚ,
      1 ≤
          xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p qs ↔
        p.Prime ∧ ∃ q ∈ qs, p ∣ q.den
  | [] => by
      simp [xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max]
  | q :: qs => by
      by_cases hq : p.Prime ∧ p ∣ q.den
      · simp [xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max, hq]
      · have ih :=
          xi_time_part65g_frequency_prime_support_kernel_recovery_depth_pos_iff p qs
        constructor
        · intro hdepth
          have htail : 1 ≤
              xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p qs := by
            simpa [xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max,
              hq] using hdepth
          rcases ih.mp htail with ⟨hp, q', hqmem, hqdiv⟩
          exact ⟨hp, ⟨q', by simp [hqmem], hqdiv⟩⟩
        · rintro ⟨hp, q', hqmem, hqdiv⟩
          rcases List.mem_cons.mp hqmem with rfl | hqtail
          · exact False.elim (hq ⟨hp, hqdiv⟩)
          · have htail : 1 ≤
                xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p qs :=
              ih.mpr ⟨hp, ⟨q', hqtail, hqdiv⟩⟩
            simpa [xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max,
              hq] using htail

/-- Concrete statement: the root-closed carrier has exactly the declared denominator-prime
support, and the same support is recovered from positive common-kernel valuation depth. -/
def xi_time_part65g_frequency_prime_support_kernel_recovery_statement
    (D : xi_time_part65g_frequency_prime_support_kernel_recovery_data) : Prop :=
  (∀ p : ℕ,
      p ∈ D.xi_time_part65g_frequency_prime_support_kernel_recovery_root_closed_carrier ↔
        p ∈ D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support) ∧
    (∀ p : ℕ,
      p ∈ D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support ↔
        1 ≤
          xi_time_part65g_frequency_prime_support_kernel_recovery_valuation_depth_max p
            D.xi_time_part65g_frequency_prime_support_kernel_recovery_frequency) ∧
      ∀ p : ℕ,
        p ∈ D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support ↔
          D.xi_time_part65g_frequency_prime_support_kernel_recovery_common_kernel_detects_prime p

end xi_time_part65g_frequency_prime_support_kernel_recovery_data

open xi_time_part65g_frequency_prime_support_kernel_recovery_data

/-- Paper label: `thm:xi-time-part65g-frequency-prime-support-kernel-recovery`. -/
theorem paper_xi_time_part65g_frequency_prime_support_kernel_recovery
    (D : xi_time_part65g_frequency_prime_support_kernel_recovery_data) :
    xi_time_part65g_frequency_prime_support_kernel_recovery_statement D := by
  refine ⟨?_, ?_, ?_⟩
  · intro p
    rfl
  · intro p
    rw [D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support_spec,
      xi_time_part65g_frequency_prime_support_kernel_recovery_depth_pos_iff]
  · intro p
    rw [xi_time_part65g_frequency_prime_support_kernel_recovery_common_kernel_detects_prime]
    rw [D.xi_time_part65g_frequency_prime_support_kernel_recovery_denominator_prime_support_spec,
      xi_time_part65g_frequency_prime_support_kernel_recovery_depth_pos_iff]

end Omega.Zeta
