import Mathlib.Data.Fintype.Perm
import Mathlib.Tactic

namespace Omega.Zeta

/-- The `S₁₀` Frobenius component in the dual-fingerprint finite model. -/
abbrev xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G10 :=
  Equiv.Perm (Fin 10)

/-- The `S₃` Frobenius component in the dual-fingerprint finite model. -/
abbrev xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G3 :=
  Equiv.Perm (Fin 3)

/-- Conjugacy-invariant finite events in one Frobenius component. -/
def xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassEvent
    {G : Type*} [Group G] (E : Finset G) : Prop :=
  ∀ σ τ : G, σ ∈ E ↔ τ * σ * τ⁻¹ ∈ E

/-- Indicator of a finite event as a real-valued class function. -/
def xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator
    {G : Type*} [DecidableEq G] (E : Finset G) (σ : G) : ℝ :=
  if σ ∈ E then 1 else 0

/-- A real-valued class function on a finite Frobenius component. -/
def xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction
    {G : Type*} [Group G] (f : G → ℝ) : Prop :=
  ∀ σ τ : G, f (τ * σ * τ⁻¹) = f σ

/-- Concrete density functionals for the dual-fingerprint product space. -/
structure xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context where
  density10 :
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G10 → ℝ) → ℝ
  density3 :
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G3 → ℝ) → ℝ
  densityProduct :
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G10 ×
      xi_time_part62ea_dualfingerprint_boolean_strong_product_law_G3 → ℝ) → ℝ
  xi_time_part62ea_dualfingerprint_classfunction_prime_average_factorization_tensor_independence_h :
    ∀ f g,
      xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction f →
        xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction g →
          densityProduct (fun x => f x.1 * g x.2) = density10 f * density3 g

/-- Tensor independence for all class functions on the two Frobenius components. -/
def xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context.class_function_tensor_independence
    (D : xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context) : Prop :=
  ∀ f g,
    xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction f →
      xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction g →
        D.densityProduct (fun x => f x.1 * g x.2) = D.density10 f * D.density3 g

/-- Boolean product law for all events generated by conjugacy classes. -/
def xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context.boolean_product_law
    (D : xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context) : Prop :=
  ∀ E F,
    xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassEvent E →
      xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassEvent F →
        D.densityProduct
            (fun x =>
              xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator E x.1 *
                xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator F x.2) =
          D.density10
              (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator E) *
            D.density3
              (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator F)

lemma xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator_classFunction
    {G : Type*} [Group G] [DecidableEq G] (E : Finset G)
    (hE : xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassEvent E) :
    xi_time_part62ea_dualfingerprint_boolean_strong_product_law_ClassFunction
      (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator E) := by
  intro σ τ
  unfold xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator
  by_cases hmem : σ ∈ E
  · have hconj : τ * σ * τ⁻¹ ∈ E := (hE σ τ).mp hmem
    simp [hmem, hconj]
  · have hconj : τ * σ * τ⁻¹ ∉ E := by
      intro h
      exact hmem ((hE σ τ).mpr h)
    simp [hmem, hconj]

/-- Paper label: `thm:xi-time-part62ea-dualfingerprint-boolean-strong-product-law`. -/
theorem paper_xi_time_part62ea_dualfingerprint_boolean_strong_product_law
    (D : xi_time_part62ea_dualfingerprint_boolean_strong_product_law_Context) :
    D.class_function_tensor_independence -> D.boolean_product_law := by
  intro htensor E F hE hF
  exact htensor
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator E)
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator F)
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator_classFunction E hE)
    (xi_time_part62ea_dualfingerprint_boolean_strong_product_law_indicator_classFunction F hF)

end Omega.Zeta
